### ISSUE TITLE
"npm install" not working for me

### ISSUE THREAD

**Issue by mlchild** [howdyai/botkit#10]
As a total newbie to node.js/npm (I'm an iOS developer), ran into a substantial # of roadblocks installing botkit. I figured out I had to install all these npm packages to make it work, but would have been nice for that to be in the instructions.

**Comment by benbrown** [comment]
Good call! They get installed automatically if you use npm, though if you install from Github you need to do "npm install" to install all dependencies.

**Comment by mlchild** [comment]
Ah, okay. I used the instructions on this page https://docs.npmjs.com/getting-started/installing-node (sudo npm install npm -g) and I still had to install all the modules individually.

**Comment by ZuzooVn** [comment]
@benbrown : what's your development environment? I am using Mac OS X 10.11 and have the same problems: https://github.com/howdyai/botkit/issues/2

**Comment by akhanukov** [comment]
I'm on Mac OS X 10.9.5 (getting ready to go El Capitan any minute!), but I also had the same identical problem and solution to @mlchild and @ZuzooVn. Except I'm more of a PHP focused guy who should have spent more time brushing up on his JS skills 10 years ago. :) Anyway, thanks for botkit! Have it installed and about to get my hands dirty. (And I must add, this Node/Angular/etc world is fascinating and addicting.)

**Comment by RafaelCosman** [comment]
Is this issue reproducible by anyone?

**Comment by anonrig** [comment]
I believe this problem is user oriented. Therefore, closing the issue. If this issue is reproduced please open an issue with the methodology in CONTRIBUTING.md file.

Thank you.
