### ISSUE TITLE
Is there a way to access variables stored with convo.setVar()?

### ISSUE THREAD

**Issue by CitiVince** [howdyai/botkit#1006]
Basically what the title says. I would like to use variables stored with `convo.setVar()` later on in the conversation. I tried `convo.extractResponses()` and `convo.extractResponse()` but this only seems to give access to actual responses.

**Comment by benbrown** [comment]
`convo.vars.fieldname` is where they live.

**Comment by CitiVince** [comment]
I couldn't find it anywhere in the docs. Thank you very much!
