### ISSUE TITLE
Send message from the server

### ISSUE THREAD

**Issue by Yulgana33** [howdyai/botkit#1019]
I need to send a message after a user opens (or better, after he closes) a webview in Messenger. How can I do this?

In facebook.js

webserver.get('/index', isLoggedIn, function(req, res){
            res.render('index.ejs',{
                    user : req.user 
                });
            req.on("end", function() {console.log("SEND A MESSAGE?"); });

**Comment by ouadie-lahdioui** [comment]
BTW [messenger extensions](https://developers.facebook.com/docs/messenger-platform/webview/close) allow to do some thing like that.
