### ISSUE TITLE
How to insert dynamically generated message while using bot.createConversation()?

### ISSUE THREAD

**Issue by CitiVince** [howdyai/botkit#1022]
So the goal is to have the controller react to a postback, ask for the user's location, use the data in a function that generates a message and insert this message into the next question.

However, I get an error before the convo starts due to `convo.vars.generated_cards` being undefined at the time the convo is being generated. What's the best approach to handle this type of problem?

Here's a generic example of my code:

```
controller.hears(['MY_POSTBACK'], 'facebook_postback', (bot, message) => {
  bot.createConversation(message, (err, convo) => {

    convo.addQuestion({text: "Where are you?",
      quick_replies: [{content_type: "location"}]
      }, (res, convo) => {
        
        convo.setVar('location', res.attachments[0].payload.coordinates)

        convo.gotoThread('tell_location')

    }, {key: "user_location"})

    convo.beforeThread('tell_location', (convo, next) => {
      
      let get_data = new Promise((resolve, reject) => {
        myFirstFunction(convo.vars.location, resolve)
      })

      get_data
        .then(mySecondFunction)
        .then((data) => { 

          convo.setVar('received_data', data.data)
          convo.setVar('generated_cards', data.cards)
          
          next()
        })      
    })

    convo.addMessage(convo.vars.generated_cards.text,'tell_location')

    convo.activate()

  }) 
})
```

**Comment by benbrown** [comment]
The issue here is that you are referring to a variable that has not yet been created.

As it is, you're creating convo.vars.generated_cards only after the user starts the conversation and finds their way to the `tell_location` thread. However, your call to convo.addMessage happens immediately upon creating the conversation.

To fix this, you could move your call to convo.addMessage inside the get_data callback, right before your call to next().

**Comment by benbrown** [comment]
Let me know if this solves your problem!

**Comment by CitiVince** [comment]
Hi Ben, yes, that solves the problem!

I thought that the yet to be created variable was the issue, but didn't realize it was possible to use `gotoThread()` to reference a thread that will be created later down the road. 

Thanks a lot your help!
