### ISSUE TITLE
channel storage question

### ISSUE THREAD

**Issue by pgoldweic** [howdyai/botkit#1024]
I'm trying to use botkit's channel storage (with Spark) to temporarily save the messages exchanged in a conversation (while the app considers that a particular conversation is going on). However, something is not clear to me: given that my bot only replies to direct messages or mentions by a user, can I trust that there will be a unique channel representing all conversations between the bot and a particular user? This seems to be the case right now but I'd like to confirm.

**Comment by pgoldweic** [comment]
@peterswimm I noticed you labeled this question with: slack-related, although I'm actually using Spark instead (I edited the question to note this).

**Comment by benbrown** [comment]
The channel id (found in `message.channel`) is unique to the "space" in which the messages are sent.

So, any message received as a 1:1 message (`direct_messages`) will have the same channel ID for any given user.

Messages received in other rooms will have a `message.channel` value related to the _room_, not the _user_.

**Comment by pgoldweic** [comment]
Thanks!
