### ISSUE TITLE
Deactivate or shutdown a bot on error?

### ISSUE THREAD

**Issue by mralanlee** [howdyai/botkit#1025]
I'm currently running Botkit for Facebook, and host multiple bots on through a single instance. Yesterday, one of the clients we had our bot hooked up to revoked the page token access, so we were getting an error of an OAuth Exception from Facebook. However, this affected all of our other bots running on that instance and causing them to non-responsive. 

Is there a way to pragmatically or manually shut down a bot, OR to have that single bot ignored per page_id?

**Comment by ouadie-lahdioui** [comment]
Hello, how you host multiple bots on through a single instance ?

Can you share some codes ?

**Comment by peterswimm** [comment]
@kniteshift ^?

**Comment by kniteshift** [comment]
I will create a dummy repository.

**Comment by kniteshift** [comment]
@peterswimm @ouadie-lahdioui 

https://github.com/kniteshift/multitenancy-botkit-demo

Sorry this is a slimmed down version but I can do my best to answer any questions if you have it.

**Comment by ouadie-lahdioui** [comment]
You can surround each bot spcific code with a try-catch bloc to catch all errors and react on that, in this case your main node thread will not stoped.

You can also start a new node child process for each bot to not impact your main thread if a child stoped.
