### ISSUE TITLE
BotKit bot not online slack

### ISSUE THREAD

**Issue by totalvm** [howdyai/botkit#1027]
Botkit bot doesn't show as online on slack and doesn't respond at all.

steps:
- 1 clone repo to glitch (via your site)
- 2 make new slack team
- 3 create bot user
- 4 add clientId, clientSecret to .env file
- 5 go to the url to add my bot and approve
- 6 bot is added to slack, sends me a message
- 7 bot stays offline, no response and no logs

**Comment by peterswimm** [comment]
For step 7, how do you know the bot is offline? Have you checked that everything is setup properly on the Slack side per this document?

https://github.com/howdyai/botkit/blob/master/docs/provisioning/slack-events-api.md

**Comment by totalvm** [comment]
Yes I have done that, I know because the bot shows as offline.
I tried directly with the slack node sdk and same token/credentials and it works.

**Comment by peterswimm** [comment]
When you added the tokens to the glitch project, did you use the ADD TO SLACK button in your glitch to add your bot to your team? You'll need to do this to create the simple storage the starter kit uses.

**Comment by totalvm** [comment]
Yes I did, actually I've set up 3 botkit projects before, but now they don't seem to work anymore. My other bot projects still work, but when I try a new one with a clone (and the rights keys) it doesn't seem to work.

**Comment by peterswimm** [comment]
Under Distribution in the Slack portal, can you visit the url listed under 'Sharable URL' to reinstall your bot and see if that works?

**Comment by peterswimm** [comment]
Are you installing them on the same team they were created for?

**Comment by totalvm** [comment]
Yes I was, it was a newly created team and was only logged in to that slack.
I've solved it by using the slack-node-sdk for now.

**Comment by peterswimm** [comment]
I'm suspicious that something either changed in your code, or we are missing a step in the provisioning topic, but will close this for now since you are using a different framework.
