### ISSUE TITLE
message_received is being triggered for every message the bot sends too. how can I know the difference when it is the user who sent (FACEBOOK)? 

### ISSUE THREAD

**Issue by Yulgana33** [howdyai/botkit#1029]
I am working with facebook messenger; there are some instructions that I want to execute when the bot user sent a message to the bot. I've come to notice that message_received is being trigger also when the bot sends a message without receiving one directly from the user.

What event handler is trigger only when the user sends the message and not bot or how can I know that this message_received is because the bot sends a message but not because the user sent a message?

**Comment by benbrown** [comment]
@Yulgana33 This is due to the `message_echo` webhook subscription.

In version 0.6.1, these will now trigger `message_echo` events in Botkit instead of `message_received` events.
