### ISSUE TITLE
Dynamically spawn on post request?

### ISSUE THREAD

**Issue by kniteshift** [howdyai/botkit#1031]
I have a custom express web server, where a payload for the bot configuration details are sent to my BotKit API - is it possible to dynamically spawn Facebook bot from this? If so, what's the best way to execute this, or is there an example available?

**Comment by benbrown** [comment]
Take a look at how we do this in the botkit starter kit projects - there is an example webhook receive endpoint in each one.

What platform are you building for?

**Comment by benbrown** [comment]
Take a look here:

https://github.com/howdyai/botkit-starter-facebook/blob/master/components/routes/incoming_webhooks.js

**Comment by kniteshift** [comment]
@benbrown sorry - I may have poorly worded my question. I guess what I meant to say was dynamically launch it. The method shares, generally requires you to initialize the Botkit configuration statically in the Botkit.js file.

What I want to do is, if I have a completely webservice where people can sign up to their bot to be spawned on their facebook page id, while providing an access token. I can save the data on my web service and then do a POST request to my Chat Bot (Botkit) API to load the credentials and details to launch/deploy a new bot.

**Comment by benbrown** [comment]
Gotcha.

Alas, right now, Botkit doesn't have great support for multi-tenant Facebook bots. You can definitely do it - but it is up to you to connect and manage the multiple instances. I'd search here for conversations about this issue.
