### ISSUE TITLE
Interactive Replies in Conversations Removed?

### ISSUE THREAD

**Issue by TheJimFactor** [howdyai/botkit#1032]
I'm trying to have a button click inside of a conversation.ask count a button click as a reply to the question, but right now all I'm getting is the callback, nothing in the conversation. I'm using the setting from the july 2017 documentation.

The documentation no longer makes reference to setting the attribute: Botkit.slackbot({interactive_replies:true})

This seems to be the commit that took it out: https://github.com/howdyai/botkit/commit/27699d40edc2db439871acb2ea69a3537b0d42ab#diff-90c105aa71d459531f021bddf2deebc0

**Comment by benbrown** [comment]
@TheJimFactor Yes, this option was deprecated in version 0.6.0 that was released this monday.

You no longer need a special option to receive the callback as part of your conversation. It should receive the .payload value of the button.

**Comment by benbrown** [comment]
@TheJimFactor Did this help?

**Comment by TheJimFactor** [comment]
Thank you! I'll make sure I'm on the right version.
