### ISSUE TITLE
bot.reply doesn't working with Bot Framework

### ISSUE THREAD

**Issue by SilvaLA59** [howdyai/botkit#1033]
I'm having an issue using Botkit with BotFramework. When I send a message to my bot It's responding nothing back. Someone knows what is wrong?

	var Botkit = require('../lib/Botkit.js');
	const apiaibotkit = require('../lib/api-ai-botkit');
	var builder = require('botbuilder');
	var controller = Botkit.botframeworkbot({
		debug: true
	});

	var bot = controller.spawn({
		appId: process.env.MICROSOFT_APP_ID,
		appPassword: process.env.MICROSOFT_APP_PASSWORD
	});

	controller.setupWebserver(process.env.port || 3000, function(err, webserver) {
		controller.createWebhookEndpoints(controller.webserver, bot, function() {
			console.log('ONLINE!');        
		});
	});

	controller.hears(['hello', 'hi'], 'message_received', function(bot, message) {

		controller.storage.users.get(message.user, function(err, user) {
			if (user && user.name) {
				console.log('Hello com nome ' + user.name);
				bot.reply(message, 'Hello ' + user.name + '!!');
			} else {
				console.log('Hello sem nome');
				bot.reply(message, 'Hello.', function(err) {
				  console.error(err);
				});
			}
		});
	});

**Comment by SilvaLA59** [comment]
I found, the problem is happening just on last botkit version(0.0.6) I tried using 0.5.8 and it works.

**Comment by peterswimm** [comment]
This might be related to recent pipeline changes. I would stick with 0.5.8 until we've had a chance to take a look.

https://github.com/howdyai/botkit/blob/master/docs/readme-pipeline.md

**Comment by teerapat2539** [comment]
you try follow this  https://github.com/howdyai/botkit/blob/master/docs/readme.md

**Comment by benbrown** [comment]
@SilvaLA59 This has been fixed in version 0.6.1! Sorry for the trouble.

**Comment by chetanmekha** [comment]
Hello Team,
I tried to connect with botframework but no success. bot.reply not returning result back to skype. Please find below my debug log,
`  user: 'skype:29:1nw5d7Lk_jhkjMo1Uvz-doUxDLxKaE2T7y45Z6mWe17A',
  channel: 'skype:29:1nw5d7Lk_jhkjMo1Uvz-doUxDLxKaE2T7y45Z6mWe17A',
  address: 
   { id: '1507023405050',
     channelId: 'skype',
     user: 
      { id: '29:1nw5d7Lk_jhkjMo1Uvz-doUxDLxKaE2T7y45Z6mWe17A',
        name: 'chetan mekha' },
     conversation: { id: '29:1nw5d7Lk_jhkjMo1Uvz-doUxDLxKaE2T7y45Z6mWe17A' },
     bot: 
      { id: '28:8c5962e2-c87f-4cba-8cfa-9c96437d9a21',
        name: 'SBIG_Insurance' },
     serviceUrl: 'https://smba.trafficmanager.net/apis/' },
  to: 'skype:29:1nw5d7Lk_jhkjMo1Uvz-doUxDLxKaE2T7y45Z6mWe17A' }
SENDING VIA BOT FRAMEWORK { text: 'Hello.',
  address: 
   { id: '1507023405050',
     channelId: 'skype',
     user: 
      { id: '29:1nw5d7Lk_jhkjMo1Uvz-doUxDLxKaE2T7y45Z6mWe17A',
        name: 'chetan mekha' },
     conversation: { id: '29:1nw5d7Lk_jhkjMo1Uvz-doUxDLxKaE2T7y45Z6mWe17A' },
     bot: 
      { id: '28:8c5962e2-c87f-4cba-8cfa-9c96437d9a21',
        name: 'SBIG_Insurance' },
     serviceUrl: 'https://smba.trafficmanager.net/apis/' },
  to: 'skype:29:1nw5d7Lk_jhkjMo1Uvz-doUxDLxKaE2T7y45Z6mWe17A',
  type: 'message' }
null
`
@benbrown @peterswimm @teerapat2539  Please help me out over this.
