### ISSUE TITLE
Conversation ended ubruptly

### ISSUE THREAD

**Issue by abhinav118** [howdyai/botkit#1036]
"Conversation is over with status complete"
debug error

Please can anyone help

**Comment by peterswimm** [comment]
Can you post a code snippet? That is not an error, it's a status message.

**Comment by abhinav118** [comment]
@peterswimm 

'debug: Conversation is over with status completed '

This occurs inside our flow, abruptly or abnormally. Can you please help me understand when this would occur theoretically?

**Comment by peterswimm** [comment]
That is the console message, but it would be useful to know what your code is trying to do when it occurs. Are you pining a third party service or datastore for information to use in your code?

If you can provide an example of code that causes this message to appear, we can see if there is something you can do to minimize it.

**Comment by abhinav118** [comment]
While going thru the chat flow , we receive this debug message and the bot abruptly ends the session and goes thru *(handling default message). Bot replies with - "i cant understand, i am still learning. please use the menu" kinda message. The user cant go frward and has to restart the chat session by going thru Menu. Do you know why this would occur? @kniteshift can share the code if required.

**Comment by peterswimm** [comment]
It would be useful to see your code.

**Comment by kniteshift** [comment]
@peterswimm 

In one of of our objects, in 

```
controller.storage.users.get(message.user, async (err, user) => {
     user.orderData.items.push(item);
     if(err) console.log('Error:' + err + '- occurring at addItemToOrder')
     let orderDetails = await this.getOrderDetails(user.orderData);
     bot.startConversation(message, (err, convo) => {
      convo.sayFirst(orderDetails);

      setTimeout(() => {
        // This is another method within the object
        this.displayPayButton(bot, message, user.orderData);
        convo.next();
      }, 1500)
     })
});

```

We've noticed that the "Conversation has ended happens here", as well as a few other places. To give you more information...

We're using version 0.5 of the BotKit API. The platform is on Facebook. We are not using any other type of storage module (like Mongo, Redis, or SQL).  We also have `receive_via_postback` and `require_delivery` set to `true`

**Comment by peterswimm** [comment]
That timeout is causing the issue, settimeout is async, so the conversation will end before setTimeout completes. You should consider using threads to do your db query to ensure the process completes before the conversation can continue:

https://github.com/howdyai/botkit/blob/1ca7a16bc9e2daba2d18b3b0224cb18619ce79a9/docs/readme.md#conversation-threads
Which would look something like:

```

// using async functions with a conversation requires use of threads!

// send a message with an action field
// this action will cause botkit to call gotoThread('completed')
// after the message is sent
convo.say({
    text: 'DOING A THING',
    action: 'completed'
});
convo.addMessage('Success!','completed');
convo.addMessage('FAILED!', 'failed');
convo.beforeThread('completed', function(convo, next) {

    asyncprocess().then(function() {
        // continue on to completed thread
        next(); 
    }).catch(function() {
        // catch error in the failed thread
        convo.gotoThread('failed');
    })

});
```

**Comment by kniteshift** [comment]
@peterswimm

I see. I see some other instances of where it's occurring as well, however I will need to dig in the logs to see if it's because we're using an async function.

I guess another thing I can try to do is wrapping the `controller.storage.users.get` in a new Promise and then chain the conversation after the data is resolved.

Just wanted to get clarity, does a "Conversation ended with a status complete" mean that the session is complete?

**Comment by peterswimm** [comment]
That would work as well.

That status message basicly means there is nothing left to process in the thread, did you have any other questions?

**Comment by constantx** [comment]
> nothing left to process in the thread

In the thread or in the conversation? The doc seems to read as `conversation.on('end')` is for the whole conversation.
