### ISSUE TITLE
"bodyParser is not defined" in Facebook.js

### ISSUE THREAD

**Issue by lorenzhk** [howdyai/botkit#1041]
`botkit/lib/Facebook.js:368
            webserver.post('/facebook/receive', bodyParser.json({verify: verifyRequest}));
                                                ^
ReferenceError: bodyParser is not defined`

I believe the bodyParser require statement is needed but removed in v0.6.0

**Comment by benbrown** [comment]
DOH! Thanks for pointing this out. 0.6.1 will fix this!
