### ISSUE TITLE
Chat Bot Platform like Chatfuel

### ISSUE THREAD

**Issue by VishalWaman** [howdyai/botkit#1042]
We are looking for Tech Stack for developing a Chat Bot Platform like Chatfuel, 
Can anyone help in suggesting Tech Stack for this, or some package ?
How can we use BotKit for this ?

**Comment by peterswimm** [comment]
Using Botkit and Botkit Studio is a great way to have the full stack of features you need to work on your bot:
https://botkit.ai/

I saw your email to Botkit support, and will follow up with you directly to talk about your project!
