### ISSUE TITLE
Send message from the server 

### ISSUE THREAD

**Issue by Yulgana33** [howdyai/botkit#1043]
I need to send a message after a user opens (or better, after he closes) a webview in Messenger. How can I do this?

In facebook.js

webserver.get('/index', isLoggedIn, function(req, res){
            res.render('index.ejs',{
                    user : req.user 
                });
            req.on("end", function() {console.log("SEND A MESSAGE?"); });

**Comment by benbrown** [comment]
This is a duplicate issue, filed by the same person.

@Yulgana33, please be respectful of this shared space. You already opened this issue, and someone already responded to you with a possible solution.
