### ISSUE TITLE
not_authed when starting RTM connection [SLACK]

### ISSUE THREAD

**Issue by TheMachineHere** [howdyai/botkit#1046]
Hi, 

I have a slack bot that i wrote in Jan-Mar 2017. However, when I make a new bot with the same code and start it, i get the error "not_authed". 

I've debugged the issue and my token is good (ie, if i make a https://slack.com/api/rtm.connect POST call with my token as a body parameter, it works fine and i get a result back). It just seems to be the `bot.startRTM ` method that doesn't seem to be working. 

My code is at the bottom:

```
this.controller = botkit.slackbot({
            debug: false,
            stats_optout: true
});
this.bot = this.controller.spawn({
            token: my_bot_access_token_is_here
});

 this.bot.startRTM(function(err, bot, payload) {
        if (err) {
                console.log(err); //I GET THE ERROR "not_authed"
        }
});
```

Any Ideas?

**Comment by peterswimm** [comment]
I see that you are talking on the developer slack community, we will continue the discussion there.

**Comment by peterswimm** [comment]
FYI it was resolved here: https://dev4slack.slack.com/archives/C0AV5N8NA/p1505833922000482

The OP was supplying an empty token to "this.controller.spawn"
