### ISSUE TITLE
Alternative to convo.repeat() with changing variables?

### ISSUE THREAD

**Issue by CitiVince** [howdyai/botkit#1047]
I'm looking for a way to repeat a question, keep the two default response patterns but use changing variables in the repeated question. From what I understand, a question once asked will remain compiled (for lack of a better term) and not change even if the variable used during creation changed. Here is what I tried:

```
bot.startConversation(message, (err, convo) => {

  convo.setVar('foo', "bar")

  convo.ask({
    text: "how about {{vars.foo}}?",
    quick_replies: [
       {  content_type: "text",
          title: "yes",
          payload: "YES" },
       {  content_type: "text",
          title: "no",
          payload: "NO" }
      ]}, [
         
         { pattern: "yes",
           callback: function(response, convo){
              // placeholder for actual logic
              convo.next() }
          },
          { pattern: "no",
            callback: function(response, convo){

                   convo.setVar('foo', "buzz")
                   convo.repeat()
                   convo.next() }
        }])
})
```
In this example, the goal is to have the first question be "How about bar?" and when repeated "How about buzz". In the actual application, every repetition after a user saying "no" would take the next item from an array of arbitrary length to be inserted and repeat the question. If the user answers with "yes", then move on. 

Is there a different approach recommended for this kind of problem?

**Comment by CitiVince** [comment]
So I found a way to achieve what I wanted by creating (instead of starting) a conversation, naming the messages / questions and then instead of using 'convo.repeat()' using 'convo.gotoThread('the_question')'

Would still be interested if this is the best approach to repeat a question with changing variables. Thanks!

**Comment by benbrown** [comment]
@CitiVince I am so glad to hear that you achieved this with threads! 

I was going to suggest exactly this approach! Yes, this is the best way to achieve what you want to do.

**Comment by CitiVince** [comment]
@benbrown great, thanks for your feedback!

**Comment by gcfabri** [comment]
Hey @CitiVince, could you give a sample of your code? I'll appreciate.

**Comment by CitiVince** [comment]
Hi @gcfabri. See the code below. I changed the simplified example from above, so please be aware that this isn't the actual working code. So apologies if there are are typos. But the logic should be the same. 

```javascript
bot.createConversation(message, (err, convo) => {

  convo.setVar('foo', "bar")

  convo.addMessage({text:"hi there", action:"my_question"}, 'default')

  convo.addQuestion({
    text: "how about {{vars.foo}}?",
    quick_replies: [
       {  content_type: "text",
          title: "yes",
          payload: "YES" },
       {  content_type: "text",
          title: "no",
          payload: "NO" }
      ]}, [
         
         { pattern: "yes",
           callback: function(response, convo){
              // placeholder for actual logic
              convo.gotoThread('goodbye_message')
              convo.next() }
          },
          { pattern: "no",
            callback: function(response, convo){

                   convo.setVar('foo', "buzz")
                   
                   convo.gotoThread('my_question')
                   convo.next() }
        }],{},'my_question')
  
  convo.addMessage({text: "goodbye"}, 'goodbye_message')

  convo.activate()

})
```

Hope that helps, let me know if you have more questions.

**Comment by gcfabri** [comment]
@CitiVince , thanks for your attention. Is correct to go to a thread before its creation? I am facing an error on console like: "debug: WARN: gotoThread() to an invalid thread! my_question"

**Comment by CitiVince** [comment]
@gcfabri I'm also still discovering the details of botkit, but here are some observations that could help you:

- at the end of `.addQuestion()` you're missing an object to extract responses, which in my case is empty but probably needs to be passed along. 

```javascript
convo.addQuestion({text:"something"},[/* patterns & callbacks */], {}, 'thread_name')
``` 

- add `convo.next()` after `convo.gotoThread()`

- you probably need to have one thread named `default` to define the conversation's entry point. Since you only have the question, try naming that `default`

Hope that helps!

**Comment by Raniazy** [comment]
The convo pushes messages to "ask" or "say" in an array : convo.sent
You can easily change the first message in convo.sent before preforming convo.repeat()
`convo.set[0].text = ""How about buzz"`

hope that helps !

**Comment by CitiVince** [comment]
@Raniazy that's great to know, thank you very much! Can you by any chance point me to a documentation / thread that gives more insights to what's happening behind the scenes?

**Comment by Raniazy** [comment]
Hey @CitiVince 
Here's a link to botkit's docs : https://github.com/howdyai/botkit/tree/master/docs
it has cool examples

**Comment by Raniazy** [comment]
By the way. The solution I gave you was found no where, I just tought about it by chance, and it worked very well. :smile:

**Comment by gcfabri** [comment]
@CitiVince thank you. I forgot to add a 'default' thread. It is working properly now.
@Raniazy nice, thank you.

**Comment by TheDApact** [comment]
I've tried convo.gotoThread instead of convo.repeat in order to add some convo.say before repeating the question.
My problem is it seems an addQuestion thread has to be named "default" or the question won't fire. But when i'm calling gotoThread("default"), it is the previous question that fire (Q-2), not the last (Q-1). What am I missing?

**Comment by benbrown** [comment]
You can add questions to any thread - just make sure to pass it in as the last parameter to addQuestion.  (there are 4 parameters in total)

https://botkit.ai/docs/core.html#convoaddquestion

**Comment by TheDApact** [comment]
Hey @benbrown what i 'm trying to understand is:
1. Is it correct that a thread in convo.addQuestion can only be named "default"?
2. Is it normal that my firstQuestion will be repeated when call convo.gotoThread in the example below? 

```
firstQuestion = function(response, convo) {
    convo.addQuestion("my first question",
        function(response, convo) {
            switch (response.quick_reply.payload) {
                    case "yes":
                        yesThread(response, convo);
                        break;
                    case "no":
                        noThread(response, convo);
                        break;
                    default:
                        convo.repeat();
                }
                convo.next();
        }, {}, "default"
    );
};

secondQuestion = function(response, convo) {
    convo.addQuestion("my second question",
        function(response, convo) {
            switch (response.quick_reply.payload) {
                    case "yes":
                        yesThread(response, convo);
                        convo.addMessage({text:'Say this before repeat', action: "default"}, "addedMessage")
                        convo.gotoThread("addedMessage"); 
                        break;
                    case "no":
                        noThread(response, convo);
                        break;
                    default:
                        convo.repeat();
                }
                convo.next();
        }, {}, "default"
    );
};
```
 I expect secondQuestion to be repeat instead...

**Comment by TheDApact** [comment]
hey @benbrown , I still can't find my way out of this :( any thought on my question above?
