### ISSUE TITLE
Convo does not send messages facebook

### ISSUE THREAD

**Issue by afbayonac** [howdyai/botkit#1048]
I change to last version   "botkit": "^0.6.1"

**app.js** file 
```
const debug = require('debug')('bot:main')
const config = require('./config/config')
const YAML = require('read-yaml')
const format = require('strat')
const texts = YAML.sync('./text.yaml')
const Botkit = require('../botkit')
const rp = require('request-promise')

/* ------------------------- config bot ------------------------------------- */

var controller = Botkit.facebookbot({
  debug: true,
  log: true,
  access_token: config.FB_ACCESS_TOKEN,
  verify_token: config.FB_VERIFY_TOKEN,
  app_secret: config.FB_APP_SECRET,
  validate_requests: true
})

// Set up Facebook "thread settings" such as get started button, persistent menu
require('./components/settings')(controller)

// Set up Facebook "webhok" and spawn executed
require('./components/webhook')(controller)

controller.hears(/^hello$/, ['message_received'], (bot, message) => {
  bot.reply(message, 'bot working')
})

controller.hears(/^hello convo$/, ['message_received'], (bot, message) => {
  bot.startConversation(message, (err, convo) => {
    if (err) {
      return console.log(err)
    }
    convo.say('convo working')
  })
})


const bot = controller.spawn()
```
**debug**
![screenshot_2017-09-19_14-06-14](https://user-images.githubusercontent.com/11819544/30610490-e38b98e2-9d43-11e7-8acb-a6ea3f997f33.png)

**messenger**
![screenshot_2017-09-19_14-06-59](https://user-images.githubusercontent.com/11819544/30610581-40019aae-9d44-11e7-8df3-dc0585f06f95.png)

**Comment by benbrown** [comment]
Make sure you call `controller.startTicking()`.

The `tick` is what drives conversations.

**Comment by afbayonac** [comment]
ho, work ! , but this was not necessary in previous versions.

**Comment by benbrown** [comment]
It is called internally by Botkit as part of the setupWebserver function, which you are not calling in this code.

**Comment by afbayonac** [comment]
is called in components/settings

**Comment by afbayonac** [comment]
https://github.com/howdyai/botkit/blob/85f92b4fe1e5203d672ad7c0db8e2fb3b87eeb6a/lib/CoreBot.js#L1260

**Comment by afbayonac** [comment]
https://github.com/howdyai/botkit/blob/85f92b4fe1e5203d672ad7c0db8e2fb3b87eeb6a/lib/CoreBot.js#L1260
