### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by Yulgana33** [howdyai/botkit#1051]
for (var e = 0; e < obj.entry.length; e++) {
                  for (var m = 0; m < obj.entry[e].messaging.length; m++) {
                      var facebook_message = obj.entry[e].messaging[m];
 -                    if (facebook_message.message) {
 +                    if (facebook_message.message && !facebook_message.message.quick_reply) {
                          var message = {
                              text: facebook_message.message.text,
                              user: facebook_message.sender.id,
 @@ -313,6 +313,23 @@ function Facebookbot(configuration) {
                              facebook_botkit.receiveMessage(bot, message);
                          }
  
 +                    } else if (facebook_message.message && facebook_message.message.quick_reply) {
 +
 +                        // trigger BOTH a quick_reply event
 +                        // and a normal message received event.
 +                        // this allows developers to receive quick_reply as part of a conversation.
 +                        var message = {
 +                            text: facebook_message.message.quick_reply.payload,
 +                            payload: facebook_message.message.quick_reply.payload,
 +                            input: facebook_message.message.text,

**Comment by peterswimm** [comment]
Can you explain a little more what is happening that you think is a bug?
