### ISSUE TITLE
reply buttons with Bot Framework

### ISSUE THREAD

**Issue by SilvaLA59** [howdyai/botkit#1052]
I'd like to know if is possible to reply a messagem with buttons using bot framework platform or something similar to builder.Prompts.choice https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-dialog-prompt#promptschoice

**Comment by ouadie-lahdioui** [comment]
Yes you can reply to an incoming message with buttons using Botkit + MS Botframwork by sanding [suggested actions](https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-send-suggested-actions) for example ! like this :

````
bot.reply(message, {
  "type": "message",
  "text": "Are ready ?",
  "suggestedActions": {
    "actions": [
      {
        "type": "imBack",
        "value": "true",
        "title": "Yes"
      },
      {
        "type": "imBack",
        "value": "false",
        "title": "Not yet"
      }
    ]
  }
});
````
This code example shows how to send a message that presents two suggested actions (Yes & Not yet) to the user, the slightly difference between this approche and ````prompts.choice()```` is in how to manage unwanted options. with ````prompts.choice()```` you ask your user to choose from a fixed list of options, so, if he type an unwanted value, MS BotBuilder will handle the error for you and ask the user to choose à correct value again and again. However, if you send suggested actions you should manage the unwanted values manually.

**Comment by SilvaLA59** [comment]
Thank you man, it works.

**Comment by SilvaLA59** [comment]
I get solution following this comment [https://github.com/howdyai/botkit/issues/1052#issuecomment-330959729](url)
