### ISSUE TITLE
How to implement human takeover using botkit?

### ISSUE THREAD

**Issue by gcfabri** [howdyai/botkit#1058]
Is it possible to implement a chatbot using botkit and a feature to the user be supported by a human at some point on conversation flow?

**Comment by peterswimm** [comment]
Wordhop is a good solution!

https://chatbotsmagazine.com/keep-humans-in-the-loop-with-botkit-wordhop-bd295bec5cf9

**Comment by gcfabri** [comment]
@peterswimm , thanks for your attention. Please, this will work with BotFramework to all platforms? Is this a payed service?

**Comment by peterswimm** [comment]
Those questions are better asked of them! The botkit team is thinking of ways to add takeover to our list of offerings, you can also use something like dashbots tools:
https://www.dashbot.io/docs/pause

**Comment by simonfranzen** [comment]
I know this topic is closed, but we are currently working on a botkit solution to take over the chat as a human. I would like here your opinion of what we have @peterswimm and how this could fit in the global botkit-ecosystem.

Currently it's all just prototyping. What we have:

**A standalone backend:**
* tracks history of all conversations & messages
* Has a "Messaging-App character" -> our first version was just for "watching" the bot's conversations
* If a user wants to chat with a real person the support receives a push message if she/he is online
* As support you can take over as a human
* The support can close the conversation -> The bot takes over

**Botkit Middleware**
* Middleware sends messages to standalone backend
* Implements a hacky version of the "take-over-process"

**Skill**
* As a botkit developer you have to define an entry convo for the human takeover
* As a developer you can implement a "after-human-chat" convo which gets triggered to ask stuff like "Was this conversation helpful?"

Is this approach the right way to do?
