### ISSUE TITLE
Cisco Spark direct_message confused with direct_mention after botkit 0.5.8

### ISSUE THREAD

**Issue by ernestgwilsonii** [howdyai/botkit#1059]
Cisco Spark direct_message confused with direct_mention after botkit 0.5.8

I had to roll back to:
0.5.8
to get **direct_message** working.

Note:
It did **not** matter which underlying version of **ciscospark** was used.
Tried both 1.8.0 and 1.10.4

**Comment by benbrown** [comment]
Thank you for this report @ernestgwilsonii! You are correct.

I will release a fix for this ASAP.

**Comment by benbrown** [comment]
@ernestgwilsonii this has been fixed on Github in the `master` branch. I will publish to `npm` soon.

**Comment by benbrown** [comment]
This is part of the v0.6.3 release!
