### ISSUE TITLE
Botkit with node-inspector

### ISSUE THREAD

**Issue by rumit91** [howdyai/botkit#106]
Has anyone been able to get the botkit to work with [node-inspector](https://github.com/node-inspector/node-inspector)? 

When I run `node-debug bot.js` the process terminates after the following line:
 `rtm.start { no_unreads: true, simple_latest: true, token: 'TOKEN' }`

No other errors are shown. Any ideas?

**Comment by peterswimm** [comment]
Did you ever find the answer to your question?

Closing the issue for now, If you have any updates, please feel free to reopen!
