### ISSUE TITLE
Cisco Spark only responds via direct_mention and direct_message

### ISSUE THREAD

**Issue by ernestgwilsonii** [howdyai/botkit#1060]
Cisco Spark only responds via direct_mention and direct_message

These events do nothing:
**mention
message_received
ambient**

Example:

```
controller.hears('ding', 'mention,message_received,ambient', function (bot, message) {
    bot.reply(message, 'dong');
});
```
I would really like the bot to "hear" everything aka **ambient**

Any thoughts?
Thank you!

**Comment by benbrown** [comment]
@ernestgwilsonii this is a limitation of the Spark platform.

Bots on Spark cannot hear any messages that are not either sent as 1:1 messages or prefaced with the bot's @mention.  This precludes Botkit from emitting `ambient` or `mention` events.

`message_received` events are always converted to either a `direct_message` `direct_mention` or `self_message` event.
