### ISSUE TITLE
Add support for Slack Dialogs

### ISSUE THREAD

**Issue by benbrown** [howdyai/botkit#1064]
We should add support for this new feature of Slack:
https://api.slack.com/dialogs

I propose that this would include:
* support for the new `dialog.open` API call
* a new convenience method like `replyWithDialog()`
* (maybe) detect and emit new events for dialog submissions
* (maybe) make it super easy to get dialog values out
* helper methods to build the JSON object

**Comment by benbrown** [comment]
This is mostly implemented! See the pull request above, or wait a day or two for it to be merged in.

**Comment by benbrown** [comment]
This is part of the v0.6.3 release!

**Comment by RomeHein** [comment]
I don't know if it's already the case (maybe I'm missing something), but it would be great to add the initial message that fired the dialog.
So that it would be possible to update that message depending on the dialog results.
