### ISSUE TITLE
TypeScript definition lacks correct signature for 'SlackController'

### ISSUE THREAD

**Issue by fabian-dev** [howdyai/botkit#1068]
When compiling a SlackBot with TypeScript, tsc gives me

`node_modules/botkit/lib/Botkit.d.ts(282,5): error TS7010: 'setupWebserver', which lacks return-type annotation, implicitly has an 'any' return type.`

A workaround is to allow implicit any in tsconfig.json, so that Botkit.d.ts passes the compile.

**Comment by dontmakemethink** [comment]
👍

**Comment by benbrown** [comment]
This should be fixed in 0.6.4

**Comment by fredjsf** [comment]
This error go back in the version ^0.6.16 

`node_modules/botkit/lib/Botkit.d.ts(499,5): error TS7010: 'getUserById', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/botkit/lib/Botkit.d.ts(500,5): error TS7010: 'getUserByUpn', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/botkit/lib/Botkit.d.ts(501,5): error TS7010: 'getConversationMembers', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/botkit/lib/Botkit.d.ts(502,5): error TS7010: 'getTeamRoster', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/botkit/lib/Botkit.d.ts(503,5): error TS7010: 'updateMessage', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/botkit/lib/Botkit.d.ts(504,5): error TS7010: 'getChannels', which lacks return-type annotation, implicitly has an 'any' return type.`

**Comment by peterswimm** [comment]
@fredjsf care to submit a pr?
