### ISSUE TITLE
bot.whisper posts publicly to the channel instead of an ephemeral response in botkit 0.6.3

### ISSUE THREAD

**Issue by fletchrichman** [howdyai/botkit#1071]
We are using the bot.whisper function in a public channel. It was working on 0.6.0, but now it is posting back to the whole channel. 

![image](https://user-images.githubusercontent.com/1915836/31155180-6c938ade-a869-11e7-97f6-5444f6b25026.png)

![image](https://user-images.githubusercontent.com/1915836/31155153-4d2dc24a-a869-11e7-8366-a4cada41fb91.png)

**Comment by benbrown** [comment]
This should be fixed in 0.6.4!
