### ISSUE TITLE
Working with the raw_message

### ISSUE THREAD

**Issue by TabeaSpahn** [howdyai/botkit#1072]
Hey,

I am trying to work with Botkit and Facebook. In the moment I want to use the 'metadata' field from facebook for the ''message_echo'. As metadata is not part of the message object in botkit, I am trying to access the 'raw_message'.
I already went through the following page:
https://github.com/howdyai/botkit/blob/1ca7a16bc9e2daba2d18b3b0224cb18619ce79a9/docs/readme-pipeline.md
and tried to use 
```
controller.middleware.ingest.use(function(bot, message, res, next) {} 
```
but I get the following error: "TypeError: Cannot read property 'use' of undefined".

Am I missing something, like an controlelr option or is there an easier way?

**Comment by benbrown** [comment]
@TabeaSpahn Make sure you are using the latest version of Botkit. The error you are seeing makes me think you are using a version before the pipeline was added.

**Comment by TabeaSpahn** [comment]
@benbrown: thanks, did not see that. Now it works
