### ISSUE TITLE
Slash commands for single teams

### ISSUE THREAD

**Issue by caske33** [howdyai/botkit#108]
https://github.com/howdyai/botkit/blob/9ca6d2e1762a76fa2480f083ffb251ae44b17d5a/lib/SlackBot.js#L79

I'm not sure why the check for team is necessary? I think it should be done by the client, not by the lib. What's wrong with having a team that is null?

**Comment by wilg** [comment]
I've just encountered this as well. It seems like this is for authentication purposes according to the documentation at https://api.slack.com/slash-commands, but I'm not sure why it can't just load up a team either way or use the verification token in some way.

**Comment by wilg** [comment]
I solved this by just saving the team when the bot boots:

```coffee
bot = controller.spawn()
bot.api.team.info {}, (err, response) ->
  controller.saveTeam(response.team, ->
    console.log "Saved the team information..."
  )
```

**Comment by caske33** [comment]
Isn't the team id that's in the message itself enough?

**Comment by wilg** [comment]
I think the idea is you need to capture a "known good" team ID, which you can do by directly asking the Slack API for it, and compare that with the untrusted team ID coming from the slash command web request.

**Comment by caske33** [comment]
well, you don't. The id itself is enough. If i have the next code snippet in the beginning of my app, the thing works.

(payload is the payload from the RTM api, but that doesn't really matter, the thing is that there is no real info in the team object)
```javascript
  //Fix for https://github.com/howdyai/botkit/issues/108
  controller.storage.teams.save({id: payload.team.id, foo:"bar"}, function(err){
    if(err)
      console.error(err)
  });
```

**Comment by timche** [comment]
I still can't figure out how this works in combination with express and the slash command.

I'm saving the team id like you did @caske33 and finally got rid of the error `Received slash command, but could not load team`, but whenever I try to execute the slash command now, I still got `Darn – that slash command didn't work (error message: `Timeout was reached`).` in Slack, without any errors in the console.

Can you maybe post an example how it should work?

My code: 
```js
let bot = controller.spawn({
    token: process.env.SLACK_TOKEN
}).startRTM()

bot.api.team.info({}, (err, res) => {
    controller.storage.teams.save({id: res.team.id}, (err) => {
        if (err) {
            console.error(err)
        }
    })
})

controller.setupWebserver(process.env.PORT, (err, webserver) => {
  controller.createWebhookEndpoints(controller.webserver)
})

controller.on('james', (bot, message) => {
    bot.replyPublic(message,'Everyone can see this part of the slash command')
})
```

Thanks.

**Comment by caske33** [comment]
@timche Can you try `bot.replyPrivate(message, '')` before your public reply? (I'm not 100% sure it will work, but just a guess)

**Comment by timche** [comment]
@caske33 Nope, doesn't work :(

Just to clarify: `controller.on('james', (bot, message) => {` is `james` the slash command I've set up in Slack or the text that comes after `/james <text>`?

**Comment by timche** [comment]
I've solved the problem. I've changed `slash_command` to the command I've set up in Slack, that was a bit confusing.

Before:
```js
controller.on('james', (bot, message) => {
    bot.replyPublic(message,'Everyone can see this part of the slash command')
})
```

After:
```js
controller.on(slash_command', (bot, message) => {
    bot.replyPublic(message,'Everyone can see this part of the slash command')
})
```

Now everything is working like expected.

Thanks anyway for that issue above, was very helpful. Couldn't figure it out by myself.

**Comment by caske33** [comment]
@timche you can check which command was used by checking the value of the `message.command` attribute

**Comment by benjamincharity** [comment]
A bit of clarity for anyone else coming to this issue for a solution.. @timche _did_ find the solution but as there is a missing `'` before `slash_command` I didn't even see the trailing apostraphe... I've been banging my head against this wondering how he could be getting anything other than an `slash_command is undefined` error.

That, on top of the fact that I assumed this was set similar to `hear()` etc in that the command would be passed in (ie `/foobar`).
 
So to reiterate @timche's find.. full correct code:

```
controller.on('slash_command', function (bot, message) {
    console.log('Here is the actual slash command used: ', message.command);

    bot.replyPublic(message, '<@' + message.user + '> is cool!');
});
```

**Comment by timche** [comment]
Oh wow, sorry @benjamincharity! Didn't realize that a `'` is missing :/ I'll fix that.

**Comment by benjamincharity** [comment]
No worries @timche. Not so late at night and I probably would have noticed much sooner! 😪

**Comment by selfcontained** [comment]
I'd second that there isn't a need to check the team id, but it should be checking the slack verify token (I don't think it is currently, maybe I missed it though?).  One of the greatest strengths of webhooks over a websocket is that it can be stateless, which makes everything much simpler to deal with at scale.

**Comment by benbrown** [comment]
This has finally been fixed!

@selfcontained thanks to another PR, there is now an option to verify all these requests with the token!

**Comment by Jon-Biz** [comment]
Has this issue been re-introduced with the new slack interactive messages? 

I am experiencing this issue when trying to receive a response from an interactive message, and resolved it with @wilg's workaround above: https://github.com/howdyai/botkit/issues/108#issuecomment-179644499

**Comment by benbrown** [comment]
@Jon-Biz No, it has not been re-introduced. Slack message buttons, unlike slash commands, are limited ONLY to apps using the slack button oauth system, so the team should always be present in the datastore.

**Comment by Jon-Biz** [comment]
:+1:

Was just coming back here to update my comment :)

**Comment by JesseSingleton** [comment]
Apologies for resurrecting a thread, I'm using the slackbutton_slashcommand example included in the latest botkit to create an app bundled with some custom commands. I've successfully integrated some buttons and interactive message capability into the example and it runs fine using an ngrok front facing local host and manually starting it in node. 

However if I try and start the JS file manually using node CLI it gives an error in command line when the button is clicked called "command slash received: team not found". Any ideas? Can post code if needed.
