### ISSUE TITLE
Error with Dialogs

### ISSUE THREAD

**Issue by uxabdullah** [howdyai/botkit#1084]
I keep getting this Fatal Error:

`Fatal TypeError: this.data.elements.push is not a function`

in: node_modules/botkit/lib/Slackbot_worker.js:676:36

When trying to do the sample Dialog code (as-is) in the docs:

` var dialog =bot.createDialog(
              'Title of dialog',
              'callback_id',
              'Button Label'
            ).addText('Text','text','some text')
              .addSelect('Select','select',null,[{label:'Foo',value:'foo'},{label:'Bar',value:'bar'}],{placeholder: 'Select One'})
             .addTextarea('Textarea','textarea','some longer text',{placeholder: 'Put words here'})
             .addUrl('Website','url','http://botkit.ai');`

`        bot.replyWithDialog(trigger, dialog.asObject(), function(err, res) {
          // handle your errors!
        });`

**Comment by benbrown** [comment]
I cannot reproduce this.

Are you sure your code looks exactly like this?

**Comment by uxabdullah** [comment]
Yep copied it out of my editor.

**Comment by benbrown** [comment]
I am not sure how this is possible, but it appears that the elements item is being set to something strange - this  should only happen if you pass in a fourth parameter to createDialog.

Try amending your code to pass in an empty array as the 4th parameter:

`createDialog(title, callback_id, label, [])`

**Comment by uxabdullah** [comment]
Now I get nothing... error is gone, but Slack gets the message but returns nothing.

Before we go down too far into the rathole, is this related to me using the RTM API as a Bot vs. a Slack App?  Interactive Messages requires me to create an App, which I am _not_ doing.

**Comment by benbrown** [comment]
You definitely have to create an app.

**Comment by uxabdullah** [comment]
Problem resolved.  I don't think this is stated in the docs anywhere.  Might be good to do so, to avoid this in the future.  Thanks!

**Comment by benbrown** [comment]
We generally let Slack handle the documentation for what features are supported where, but good point! Our Slack docs are in need of a refresh as the RTM protocol has become less central.
