### ISSUE TITLE
Can botkit be used as a web-based chatbot app?

### ISSUE THREAD

**Issue by jenniferzhu** [howdyai/botkit#1087]
Thanks! For example, I'd like to integrate my chatbot into a product in my company...

**Comment by lsshawn** [comment]
I'm also looking to use botkit for web-based. Something like [https://botkit-web.glitch.me]().

Am guessing we'll need to build a new webhook.
Anyone with experience with this implementation?

**Comment by benbrown** [comment]
Definitely start with the Botkit web starter kit - this will all be part of the Botkit master branch soon!

http://github.com/howdyai/botkit-starter-web

**Comment by jenniferzhu** [comment]
Thanks. Curious about any screenshot of the UI?

**Comment by peterswimm** [comment]
@jenniferzhu you can check out the glitch link above to see the UI, but building it out right now is in the hands of the developer.
