### ISSUE TITLE
Sending multiple typingOn messages - only first is showing typing on icon in Facebook Messenger

### ISSUE THREAD

**Issue by johmca** [howdyai/botkit#1088]
Hi,

This is more a request for help or information rather than an issue.

My use case....

I want my app to send multiple messages to Facebook Messenger. 
I want the user to have time to read each message before the next appears.
I want the typing in progress (elipse) icon to appear before each message from the bot arrives in FBM so that the user is not tempted to type.

My solution is for my app to run succesive setTimeouts each containing the code to send a message to the bot and to set the typing in progress indicator. Each timeout has incrementally greater delay times set accoring to the size of the message.

So let me simplify this down to a very simple bit of code to illustrate what I'm seeing happen...

I type "Hi" into FBM. My app runs the code below

var typingOn = {
       sender_action: "typing_on"
     };
     global.bot.reply(global.message, typingOn);

It succesfully sets the typing in progress icon ....cool

It then runs the code below and it sends "Hey" to FBM after 25 secs but it does not activate the typing in progress icon again.

setTimeout (function()  {
     
      bot.reply(message, 'Hey');

       var typingOn = {
         sender_action: "typing_on"
       };
       bot.reply(message, typingOn);
},25000);

I then type "Hi" back into FBM and it does the same thing..typing in progress appears, "Hey" appears and then no second typing in progress.

Could someone kindly explain why the second typing in progress (following "Hey") is never displayed?

Thanks in advance

**Comment by johmca** [comment]
Isn't that typical...the answer just came to me when I re-read my post...so problem solved...but here is the explanation in case anyone else is puzzeled by something similar.

I think my second typing on message is being displayed BEFORE "Hey" and is therefore cancelled before it has time to display.

As a test I ran the following code and it did what I expected..ended up by displaying typing in progress

     setTimeout (function()  {
      
      global.bot.reply(global.message, 'Hey');

      setTimeout (function() {
       var typingOn = {
         sender_action: "typing_on"
       };
       global.bot.reply(global.message, typingOn);
      },1000);

     },5000);

**Comment by benbrown** [comment]
You got it! :)

You could theoretically also use a conversation for this, to queue up messages to be sent in order.  Each message can specify a `message.delay` value which is used to delay the sending.

**Comment by johmca** [comment]
Thanks for confirming...I did try out conversations and they are great and I'm sure message.delay would work to do the queuing but could I make it so that the Typing On icon appears between replies from my app in FBM? 

I've seen quite a few posts here to do with this but its not clear to me if this feature is now available for conversations?

Thanks

**Comment by benbrown** [comment]
Ah good point. I don't think this is implemented yet.

**Comment by johmca** [comment]
Ok thanks ben...
