### ISSUE TITLE
Keywords also matches partial words

### ISSUE THREAD

**Issue by caske33** [howdyai/botkit#109]
For example, the sample bot 

```js
controller.hears(['hello','hi'],['direct_message','direct_mention','mention'],function(bot,message) {
    bot.reply(message,"Hello.");
});
```

will also match on `something`

**Comment by hbhakhra** [comment]
This does seem like a defect, but looking at the source, the reason is that all keywords are treated as regular expressions. So if you really only wanted a full word match you could do "\\bhi\\b" for now as a workaround.

**Comment by caske33** [comment]
That does indeed work. The documentation is misleading though.

**Comment by benbrown** [comment]
We will review the docs on this and hope to make them clearer.
