### ISSUE TITLE
Disable a customized Facebook built in nlp

### ISSUE THREAD

**Issue by ouadie-lahdioui** [howdyai/botkit#1090]
Hello,

When i try to disable programmatically a customized built in nlp by calling : ````controller.api.nlp.disable()```` Facebook return an error : ````Invalid parameter : Your preset is currently selected as `custom`. This means you need to have a custom token set as well.````

**Comment by ouadie-lahdioui** [comment]
Fixe #1091

**Comment by Naktibalda** [comment]
This issue can be closed because linked pull request was merged a month ago.
