### ISSUE TITLE
CiscoSparkbot limit_to_domain console.log when bot sends messages

### ISSUE THREAD

**Issue by mhuot** [howdyai/botkit#1092]
Using Botki 0.58 on Centos 7. For every message sent by the bot if the limit_to_domain is set, it sends a console.log like -

WARNING: this message came from a domain that is outside of the allowed list [ 'foo.com', 'bar.com' ]

A workaround is to add the sparkbot.io to the domain array.

**Comment by peterswimm** [comment]
Care to submit your fix as a PR?
