### ISSUE TITLE
Allow anyone to respond to convo.ask in a thread?

### ISSUE THREAD

**Issue by tiagosiebler** [howdyai/botkit#1093]
I've added some logic that needs a reference number to continue. 80% of the time that reference number is already there, and the bot won't need input to continue.

However, 20% of the time that number was never provided and the user needs to be asked. In that case, the bot will ask the person that triggered the logic/conversation, what's the ref number?

I noticed that if I trigger the conversation and the convo.ask, I can respond fine, but no one else can.

This is the workflow:

1. User asks in a channel and starts a thread.
2. I tag the bot `@bot set me as owner`
3. The bot states `What's the ref number?`
4. I ask the user, `@user what's the ref number?`
5. User responds `ref 12345`

If I'm the one that responds to question 3, the bot sees it. But in the scenario above, the bot ignores the response until I respond:
6. I respond in the thread: `ref 12345`.

I'm looking to avoid 6, I hope the above scenario make sense. Is this expected?

**Comment by tiagosiebler** [comment]
Still interested in this, if there's a solution to getting this working.

**Comment by tiagosiebler** [comment]
bump

**Comment by tiagosiebler** [comment]
bump

**Comment by benbrown** [comment]
There is no way to listen for any person to respond.  Conversations are between the bot and a single user.

**Comment by tiagosiebler** [comment]
Couldn't any message event in the same thread be considered as part of the conversation? So it's not important who responds, just where the response happens.

**Comment by benbrown** [comment]
Botkit uses both the channel id and the user id to determine that a message is part of a conversation.

You can override the bot.findConversation method to change this if you want to change this behavior yourself.
