### ISSUE TITLE
Updating Ephemeral Slack Messages

### ISSUE THREAD

**Issue by viktornordling** [howdyai/botkit#1095]
The docs say:

```
Currently, updating interactive messages are not supported by ephemeral messages, but you can still create them and listen to the events.
```

Are there any plans for adding support for this in the near future? Slack's own docs leads me to believe that it _is_ possible (though it's not very clear how). Are there any known workarounds (within our outside of Botkit) for updating ephemeral messages?

Cheers,
Viktor

**Comment by viktornordling** [comment]
I just got a response from Slack and it seems like this isn't supported on their side yet.

**Comment by peterswimm** [comment]
Closing for now, feel free to create a new request when it is possible!
