### ISSUE TITLE
How to send Object in a postback button using Telegram channel via Bot Framework?

### ISSUE THREAD

**Issue by gcfabri** [howdyai/botkit#1096]
Stackoverflow: [Question](https://stackoverflow.com/questions/46797261/how-to-send-object-in-a-postback-button-using-telegram-channel-via-bot-framework)

I am developing a bot using BotFramework and Botkit (nodeJS) with four connected channels, one of these is the Telegram. Seems that Bot Framework translates the 'value' property field to 'callback_data' field from Telegram API, 'InlineKeyboardButton' method ([docs][1]). I am trying to send a payload from post-back button larger than 64B, resulting in an error like: `'Bad request: BUTTON_DATA_INVALID'`

Take a look on snippet below at 'value' field in 'buttons' array, where the problem persists. Note: Other channels work properly sending this object as payload using the structure below.

This is the payload to be sent:

    const foobar = {
      "d": {
        "a": {
          "b": "192.168.0.12",
          "c": "12345678",
          "d": "123123"
        },
        "e": {
          "f": "1",
          "g": "Test User",
          "h": [
            {
              "i": "1",
              "j": "Foobar"
            }
          ]
        }
      }
    }

And this is the rich message structure used in Bot Framework to send a carousel through any channel that supports it, including the Telegram:

    {
        type: `message`,
        attachmentLayout: `carousel`,
        text: ``,
        attachments: [
          {
            contentType: `application/vnd.microsoft.card.hero`,
            content: {
              text: `Test message text`,
              buttons: [
                {
                  type: `postBack`,
                  title: `Send Object`,
                  value: `${JSON.stringify(foobar)}`
                }
              ]
            }
          }
        ]
      }

Once the user clicked on button, I can 'hear' the payload on my bot controller and do my stuff. Eg.: Facebook Messenger, it work nicely.

Is there some alternative to send payload data using another Bot Framework rich component or a specific Telegram component copying the behavior of a post-back button? That is, the text on value is not shown to user and the bot controller can 'hear' it once sent.
    
  [1]: https://core.telegram.org/bots/api#inlinekeyboardbutton

**Comment by irfanzz** [comment]
Hei, i have similar problem too. I am using .net core, and button with type ImBack and PostBack is not received by my bot controller

**Comment by gcfabri** [comment]
There is a size limit for Telegram payloads. Try searching for it in the Telegram documents. If I remember correctly it's 64Kb.
