### ISSUE TITLE
Message keeps stacking in Pipeline

### ISSUE THREAD

**Issue by lsshawn** [howdyai/botkit#1097]
I'm trying to use the pipeline middleware.

As user type new messages, the messages in middleware continue to stacks. Here's how it looks on my console logs:

```
> In Ingest pipeline middleware
> In Receive pipeline middleware
debug: RECEIVED MESSAGE
debug: CUSTOM FIND CONVO 1526248827438655 1526248827438655
> In Ingest pipeline middleware
> In Ingest pipeline middleware
> In Receive pipeline middleware
> In Receive pipeline middleware
debug: RECEIVED MESSAGE
debug: CUSTOM FIND CONVO 1526248827438655 1526248827438655
> In Ingest pipeline middleware
> In Ingest pipeline middleware
> In Ingest pipeline middleware
> In Receive pipeline middleware
> In Receive pipeline middleware
> In Receive pipeline middleware
debug: RECEIVED MESSAGE
debug: CUSTOM FIND CONVO 1526248827438655 1526248827438655
```

The debug only received 1 message, but my pipeline keeps stacking. 
Here's my pipeline middleware.
```
controller.middleware.ingest.use(function(bot, message, result, next) {
    console.log('> In Ingest pipeline middleware')
    next()
})

controller.middleware.receive.use(function (bot, message, next) {
    if (message.text && message.type != 'self_message') {
	console.log('> In Receive pipeline middleware')
    }
    next()
})
```
If I remove the `next()`, this doesn't happen but I can't call the next pipeline.

Also, I've no `controller.on()` codes. I've only one `controller.hears('convo', 'message_received'`

**Comment by peterswimm** [comment]
@lsshawn mind sharing how you fixed this?

**Comment by lsshawn** [comment]
I was using a custom handleWebhookPayload for FacebookBot. Initially, I placed  thay pipeline middleware inside the handleWebhookPayload, which csused this error. 

Placing all middleware outside of that function will fix this.
