### ISSUE TITLE
FB get user's profile data (first_name, last_name etc).

### ISSUE THREAD

**Issue by julianusti** [howdyai/botkit#1100]
I've tried to find out if there is an api for getting user profile data, but unfortunately i didn't found it. Am I missing smth. or it's just not a part of the api? If so, I'd be happy to contribute and extend current api.

**Comment by ouadie-lahdioui** [comment]
take a look at this one #1098

**Comment by benbrown** [comment]
Yeah, this is coming soon! If you grab the branch @ouadie-lahdioui linked to, you'll have both `bot.getMessageUser` and `controller.api.user_profile()` for Facebook.

**Comment by julianusti** [comment]
@benbrown sweet 😻

**Comment by julianusti** [comment]
What is the status of this PR?

**Comment by julianusti** [comment]
I'm closing this issue, since it was resolved within this PR #1098.
