### ISSUE TITLE
Bot not accepting file_share message

### ISSUE THREAD

**Issue by rohilshah95** [howdyai/botkit#1103]
Whenever I am trying to share a file with the bot, it does not reply back with a message giving the file link or anything. Console log remains blank.

It is working in another directory. However, when I copy the code to the project directory and run node bot.js, I can interact with the bot using simple messages, but 'file_share' messages dont work. Also, when i run the working code, i get a `info: ** Setting up custom handlers for processing Slack messages` in my terminal.

I dont get this message in the nonworking bot even though the code is exactly the same.

**Comment by jonchurch** [comment]
Hmmm maybe try the file_shared event?
Put a log statement in your webhook and see if youre getting he event from
slack, and if so what the payload has
