### ISSUE TITLE
Custom Configuration - Help Wanted

### ISSUE THREAD

**Issue by vinceprofeta** [howdyai/botkit#1105]
We have a chat application currently using rasa_nlu, node/express, socket.io, and Postgres... Is there a way to hook into botkit core for context management. Rasa is great for intent but not great for context. Do you have any suggestions?

**Comment by jonchurch** [comment]
Can you clarify context? What would you like to keep track of and when do
you need access to it?

**Comment by vinceprofeta** [comment]
@jonchurch thanks for the reply. I am trying to find a solution for conversation state management. An example would be where the bot asks a question, a reply is returned, and the bot has context on what the reply is in reference to.

I am more so looking for reading material on this or if have any recommendations. Thanks.

**Comment by vkrgowtham** [comment]
@jonchurch When user wants to order pizza, then once this intent is triggered there should be some required entities like size, address, toppings. Until unless all these entities are given by the user, the bot should ask for the same and then it should perform necessary action. 
Can this be done using botkit ?

**Comment by rogerweb** [comment]
Sure it can. Botkit provides the concept of [conversation threads](https://github.com/howdyai/botkit/blob/master/docs/readme.md#multi-message-conversations) where the dialog moves from question to question and you can keep the answers or the results of processing them as state in memory (as simple variables or any data structure you want in JS) or persisted via the supported [storage](https://github.com/howdyai/botkit/blob/master/docs/storage.md) mechanism.

**Comment by vkrgowtham** [comment]
@rogerweb @jonchurch During this conversation thread for example considering order pizza, if bot asks size of pizza and user wants to ask some other thing like location, can he come out of the conversation thread or will the bot keep on asking size ?

**Comment by rogerweb** [comment]
Once the bot has asked something using let's say `convo.addQuestion` you are "stuck" in that thread, i.e., the bot won't "hear" anything besides users's answer. Currently what I'm doing is to handle all the possible different intents in the user's response, not only the one I'm expecting. Usually I check for the "abort" and "help" intents (detected by my model in Wit.ai) so the user has always the option to abort the current thread or ask for help. In your example, you would check for the presence of the "get location" intent (the name is up to you) before handling the response assuming it is the size of the pizza. This is one option and not a good one. Alternatively, I guess you could do the other way around, i.e., try to match user's response with the answer you are expecting (the pizza size). If not possible, handle user's response using a "catch all"-type of logic that supports all the possible intents you have added support to so far, including the "get location" one.
