### ISSUE TITLE
Twilio IPM Cannot set property 'stage' of undefined (controller error)

### ISSUE THREAD

**Issue by kkarlallan** [howdyai/botkit#1113]
Good day guys,
I've followed different starter kits to get a Twilio bot running. So far no good. The logs displays the error `Cannot set property 'stage' of undefined`. Tracing the error shows that's it is because of the `message` object.

==SKIP TO THE PROBLEM START BELOW IF YOU DON'T WANT TO READ THIS SETUP INTRODUCTION=

Here's the setup:
1. I followed the Twilio IPM guide from here (https://github.com/howdyai/botkit/blob/master/docs/readme-twilioipm.md#botkit-and-twilio-ip-messaging)
2. Used the code from [twilio readme] (https://github.com/howdyai/botkit/blob/master/docs/readme-twilioipm.md#working-with-twilio-ip-messaging) as my bot.js and deployed to a public container (I use bluemix)
(Note: I also tried using the example from the botkit examples: twilio_ipm_bot.js)
3. I cloned the [twilio chat demo](https://github.com/twilio/twilio-chat-demo-js) (for my UI) 
and ran this through `localhost` since that's what all the guides suggest.

In the chat demo, I can create a channel, send a message, delete a message, edit etc. When I do that, the logs confirm that my webhook is working (It displays a http post request transaction).

===PROBLEM START===

When I send a message in a channel, the logs in the bot app display this stack trace
![image](https://user-images.githubusercontent.com/17855490/32365065-3ba7f376-c0b3-11e7-8fbb-2d33b697dbe7.png)

Tracing these leads us to the CoreBot.js:109 `receiveMessage` function. This is called by `controller.hears()` if I'm not mistaken.

![image](https://user-images.githubusercontent.com/17855490/32365131-8fe4da3a-c0b3-11e7-9c53-fc75bd66718a.png)

The log displays that `message._pipeline` is never created in any point in time. And the code line here is trying to add a property `stage` to it. From what I understand, `message` is the JSON Payload we receive from the messaging platforms (I've tried using Slackbot and it works there). 

What should be the best course of action here? I'm not quite sure what to do. 

EDIT: I've outputted the message object before anything is done to it. it looks like this

![image](https://user-images.githubusercontent.com/17855490/32370162-fff68982-c0c6-11e7-92d4-fd50ddfa9c56.png)

**Comment by anglol** [comment]
Same problem for me with Facebook.

![group](https://user-images.githubusercontent.com/1424479/32375813-46ddcd3e-c0a3-11e7-9058-97e4e5fea042.jpg)
