### ISSUE TITLE
Facebook messenger platform v2.2 update

### ISSUE THREAD

**Issue by MMayla** [howdyai/botkit#1124]
Facebook messenger platform v2.2 is now supporting a lot of cool stuff like broadcast API and page insights API. Also it require us to messaging type property to all requests ASAP.

Is there a timeline for implementing these updates?

[Read the full update](https://messenger.fb.com/blog/2-2-release/)

**Comment by jonchurch** [comment]
Thanks for asking!

Per that update, the FBM Platform v2.2 new features include:
--------
> ## Broadcast API
>  We are also releasing the Broadcast API in open beta, which gives businesses with the pages_messaging_subscriptions permission the ability to send messages to multiple subscribers with a single API request. For example, a news publisher might use the Broadcast API to send breaking news alerts to all their subscribers, or use custom labels to send game-score alerts to sports fans who follow a specific team.

**This looks really cool! Here is an issue to discuss #1128**

> ## Built in NLP
> We launched Built-in NLP in July as a simple way to automatically detect meaning and context in every text message that a person sends, before it gets passed to a business’s bot. Starting today, in addition to English, Built-in NLP is now available in Chinese, Dutch, French, German, Italian, Polish, Portuguese, Romanian, Spanish and Vietnamese. The default NLP model is able to detect the following entities in all supported languages: date & time, location, amount of money, phone number and email.

**Support for this is already in master and docs are [here](https://github.com/howdyai/botkit/blob/0308da6872e81b466f7fcba1d32cc93fb5111797/docs/readme-facebook.md#built-in-nlp)**

> ## Handover Protocol:
> Launched in beta this past April, Handover Protocol enables multiple Facebook apps to collaborate on the Messenger Platform to enable a better chat experience between people and businesses. Handover Protocol is now available globally, and offers integration with businesses’ Page inboxes, including prior versions.

**#978 Handover Protocol support is almost done**

> Page Insights API: This is a programmatic way to retrieve a number of metrics that are also available in a business’s Page management console, including the number of messages delivered per broadcast ID.

**I haven't seen an PR's for Insights yet, here is an issue with info to get started if anyone wants to pick this up #1126** 

> ## Messaging type flag requirement: 
>Starting today, we’ve created a “messaging_type” property which is required in all requests to the send API. This property identifies the messaging type for the message being sent. This is a more explicit way to ensure developers and businesses are complying with policies for specific messaging types and respecting people’s preferences.
> 
> Please note that after a six month integration period, the messaging_type property will be mandatory and all messages sent without it will not be delivered. We recommend implementing it as soon as possible and also expect to add more required flags in the coming months.

**Here's an issue to discuss implementing `messaging_type` #1127** 

> ## New Message Tags:
> We’ve added two additional Message Tags:
> 
> Application update: Notify the message recipient of an update on the status of an application (e.g. a job application)
> Pairing update: Notify the message recipient that a pairing has been identified based on the recipient’s prior request (e.g. a parking spot is available)
> Send sponsored messages via a Messenger Platform API: We’ve created a new API endpoint that allows you to send sponsored messages with a single API request. Businesses may also continue to buy sponsored messages via the Marketing API.

**These additional message tags are supported by default**
