### ISSUE TITLE
[BREAKING][Facebook] Platform v2.2: messaging_type required field

### ISSUE THREAD

**Issue by jonchurch** [howdyai/botkit#1127]
**This will need to be implemented and eventually all FB Bots below that version will break unless they update**

From Messenger Platform 2.2 [update](https://messenger.fb.com/blog/2-2-release/)
> Messaging type flag requirement: Starting today, we’ve created a “messaging_type” property which is required in all requests to the send API. This property identifies the messaging type for the message being sent. This is a more explicit way to ensure developers and businesses are complying with policies for specific messaging types and respecting people’s preferences.
> 
> Please note that after a six month integration period, the messaging_type property will be mandatory and all messages sent without it will not be delivered. We recommend implementing it as soon as possible and also expect to add more required flags in the coming months.

Here are the [API Docs](https://developers.facebook.com/docs/messenger-platform/send-messages#messaging_types) regarding the necessary changes.

**Comment by ouadie-lahdioui** [comment]
Fix is here #1171 

Thanks
