### ISSUE TITLE
[Facebook] Platform v2.2: Broadcast API

### ISSUE THREAD

**Issue by jonchurch** [howdyai/botkit#1128]
**Facebook added Broadcast API, a way to create mass messages to your users, measure their open rates, and segment users based on custom labels**

[FB Broadcast Docs](https://developers.facebook.com/docs/messenger-platform/send-messages/broadcast-messages)

**Note: Requires FB  Graph API version 2.11**

This is a really neat new feature! Let's get started on it together 👍

**Comment by ouadie-lahdioui** [comment]
Hello @jonchurch i need your review here #1180
