### ISSUE TITLE
channel_joined event not working?

### ISSUE THREAD

**Issue by Oxyrus** [howdyai/botkit#113]
I'm trying to make the bot welcome every new user on the Slack team, however I can't manage to do so with channel_joined

```js
controller.on('channel_joined',function(bot, message) {

    bot.reply(message, 'Welcome aboard!');

});
```

What would be the right way to do so?

Thank you so much!

**Comment by Glowbal** [comment]
You can use the `team_join` event. https://api.slack.com/events/team_join

**Comment by Oxyrus** [comment]
Oh yes, my bad, I was confusing them both. 
Thanks!
