### ISSUE TITLE
promises instead of callbacks?

### ISSUE THREAD

**Issue by jloveric** [howdyai/botkit#1131]
It looks like in bot.reply, callbacks are used instead of promises.  It seems like promises would be better in this situation?

**Comment by Naktibalda** [comment]
You can easily promisify it.

**Comment by urbanslug** [comment]
On this breath the internals of botkit would be helped a lot (at least to understand) if there was less reference to implicit state using `this` (maybe it is just my unfamiliarity with OOP) as well as maps and reduce functions instead of nesting for loops.
