### ISSUE TITLE
Watson Conversation did not reply to message at group direct message channel in slack

### ISSUE THREAD

**Issue by Hikotoshi** [howdyai/botkit#1134]
I used multi-bot, when executing npm start, the slack bot implementing Watson conversation replied to me when I input some message normaly in single direct message channel.
However, when I made a directmessage group channel with more than 2 people including the bot,
the bot did not reply to any input message.
the Log on the console seemesthat it recognized new input even in the directmessage group channel,
showing
info: Warning: using temporary storage. Data will be lost when process restarts.
but the bot did not reply response to any input message.
Does anybody can help me how to solve this issue, I want to make the bot active speaking even in the
directmessagegroup channel.

**Comment by peterswimm** [comment]
Might be better asked over here:
https://github.com/watson-developer-cloud/botkit-middleware
