### ISSUE TITLE
What is the best way to implement 3rd party login into botkit using passportjs

### ISSUE THREAD

**Issue by atherdon** [howdyai/botkit#1135]
Please share any examples of implementation

**Comment by jonchurch** [comment]
Where would you like a login to fit within your bot specifically? Bots run in pre-authed platforms where you have access to a unique userId gated by a successful login.

Passport has various schemes for login through the web, all of which could be completed within a webview that your bot presents to the user. You would implement Passport in Express the usual way, and at some point authenticate your user through a passport strategy.

**Can you describe what sort of functionality you would like to put behind a login?**

**Comment by atherdon** [comment]
Hi @jonchurch, thank you for your message!
I want to integrate a GitHub login in slack bot, but I saw other bots that have for example email features - they had a Gmail integration.

Basic functionality for now is:
1 page - add "bot to slack" button
2 page redirected after success login with 3rd party provider link
3 callback that will receive data from 3rd party 
4 saving profile information into db


Thank you for your time!

**Comment by akhanukov** [comment]
I'm using auth0.com, @atherdon @jonchurch, for both API security as well as platform login on my platform as well as FB. I love it.

**Comment by atherdon** [comment]
Hi @akhanukov , thank you for your comment!
I check auth0 before, but it's don't go further. Not sure why.
Btw, maybe you have some sample of auth0 implementation with botkit? This can save a lot of time for me!
thanks
