### ISSUE TITLE
[question] Why one wouldn’t just use MS Bot Framework without Botkit?

### ISSUE THREAD

**Issue by grundmanise** [howdyai/botkit#1138]
How does Botkit differ from MS Bot Framework?

**Comment by peterswimm** [comment]
There are a couple of reasons off the top of my mind, for ex:
- You have an existing Botkit project and want to add it to more platforms easily
- You want to use Botkit Studio for your Bot Framework based bot
- You prefer to user the conversation management of Botkit over the tools present in The framework alone.
- You only want to use MS teams, or only Slack, or only Facebook and want avoid using the full framework.

It's largely a matter of preference. What type of bots are you looking to build?

**Comment by grundmanise** [comment]
Thanks for answering! I am looking to build a FB bot (keeping email, sms platforms in the mind). The bot will use NLP and conversational flow.

**Comment by jonchurch** [comment]
Id add the community base around botkit is pretty great. Its one of the
most popular repos on github with about 120 contributors. Because platforms
like slack and Facebook Messenger change so frequently, that userbase is
important for implementing new platform features and keeping things up to
date.

Theyre both great platforms, I think MS Botframework leans more towards
write once run anywhere whereas botkit is best for granular control over
interactions on a platform by platform basis.

**Comment by jloveric** [comment]
Correct me if I'm wrong, but it seems difficult or perhaps there is just less documentation about how to connect botbuilder to alternative language services (other than microsoft LUIS), in particular for developing your own as I've done in my case.  BotBuilder is heavily tied to microsoft services it seems.

**Comment by jonchurch** [comment]
This issue inspired me to write a [Medium article](https://medium.com/@jonchurch/picking-a-chatbot-framework-botkit-vs-microsoft-bot-builder-1088db3d075a) for anyone else wondering the same thing!

**Comment by ouadie-lahdioui** [comment]
Yes, it's exactly like Angular vs React, the real comparaison is between Botkit and MS Bot Builder SDK not Ms Bot Framwork.

And as a developer, if you want to contribute to the project, MS Bot Builder is based on typescript superset.

My2C

**Comment by peterswimm** [comment]
This seems pretty well answered!

**Comment by tannakartikey** [comment]
I am commenting after almost 3 years but I think it's relevant.
It's difficult to get control of the look and feel of the messages using the Bot Framework. Seems there is no other way but to go for platform-specific implementation while using Bot Framework. For example, Bot Framework does not support the new BlocKit UI for Slack. Even simple attachments in older Slack syntax also fails and does not give the proper user experience.

I am looking to connect botkit with all the major frameworks via the app written in Bot Framework.
