### ISSUE TITLE
Passport.js x Botkit

### ISSUE THREAD

**Issue by TheDApact** [howdyai/botkit#1142]
Hi, anyone has a working code for passport.js integration (Facebook login) ?

I can't save the user's permissioned data using botkit-storage-mongo (no Mongoose).

Any help is highly appreciated

EDIT: the point here is simple data fetching (email, user id, etc.) from facebook login

**Comment by ouadie-lahdioui** [comment]
Yo, 

Can you share more details about your use case ? This is a Bot or juste a web app ?
