### ISSUE TITLE
Facebook bot custom webhook URL

### ISSUE THREAD

**Issue by CitiVince** [howdyai/botkit#1143]
I want to run different bots on the same server, listening on different webhooks. So I'd like to have

    https://my.domain.net/bot1/facebook/receive
    https://my.domain.net/bot2/facebook/receive
    etc.

I'm using a nginx reverse proxy, mapping to the ports the bots are running on. The setup looks something like this:

````
location bot1/facebook/receive {
 
        proxy_pass http://localhost:1234;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_buffering off;
 
} 
````
I managed to achieve this by changing the code [here](https://github.com/howdyai/botkit/blob/14d477679f8a38823fdd23e038258f12d03b86d0/lib/Facebook.js#L331) and [here](https://github.com/howdyai/botkit/blob/14d477679f8a38823fdd23e038258f12d03b86d0/lib/Facebook.js#L336) but that obviously comes with problems when upgrading etc. 

Is there a way to achieve the same through config?

Thanks!

**Comment by ouadie-lahdioui** [comment]
Yo,

By changing directly in FaceBook.js you will create your own Botkit fork that you need to maintain it ! avoid that as much as possible.

I suggest you two solutions : 

The first one is to start two instants with two different ports (bot1 -> http://localhost:1234 / bot2 -> http://localhost:5678).

The second one is to externalize your web server for more flexibility, that allow you create as much webhooks as you want, take a look at the Botkit FB starter kit exactly [here](https://github.com/howdyai/botkit-starter-facebook/blob/master/components/routes/incoming_webhooks.js).

Let me know if that helps

**Comment by CitiVince** [comment]
Hi @ouadie-lahdioui, thanks for your feedback. 
I realize that creating a fork is a bad idea. But I don't understand why the webhook reference has to be hard coded vs. being a customizable config setting similar to `hostname` and `port` .

```javascript
        facebook_botkit.log(
            '** Serving webhook endpoints for Messenger Platform at: ' +
            'http://' + facebook_botkit.config.hostname + ':' + facebook_botkit.config.port + '/facebook/receive');
        webserver.post( (facebook_botkit.config.webhook || '/facebook/receive'), function(req, res) {
            res.send('ok');
            facebook_botkit.handleWebhookPayload(req, res, bot);
        });

        webserver.get((facebook_botkit.config.webhook || '/facebook/receive'), function(req, res) {
            if (req.query['hub.mode'] == 'subscribe') {
                if (req.query['hub.verify_token'] == configuration.verify_token) {
                    res.send(req.query['hub.challenge']);
                } else {
                    res.send('OK');
                }
            }
        });
```
Is there any downside to permitting this kind of customization?

**Comment by ouadie-lahdioui** [comment]
I don't think so !

Today, at least you can customize you webHook by externalizing the web server, no need to call the method ````facebook_botkit.createWebhookEndpoints```` at all.

````
let controller = Botkit.facebookbot({
    verify_token: process.env.verify_token,
    access_token: process.env.page_token
});

let myExpressWebServer = ...;

myExpressWebServer.post('custom/facebook/receive', function(req, res) {
  controller.handleWebhookPayload(req, res, bot);
});

myExpressWebServer.get('custom/facebook/receive', function(req, res) {
 if (req.query['hub.mode'] == 'subscribe') {
  if (req.query['hub.verify_token'] == controller.config.verify_token) {
   res.send(req.query['hub.challenge']);
  } else {
   res.send('OK');
  }
 }
});
````

**Comment by CitiVince** [comment]
@ouadie-lahdioui thanks for pointing this out. This in combination with [this explanation on stackoverflow](https://stackoverflow.com/a/43667517/3104318) I managed to externalize the webserver!

**Comment by brunotech** [comment]
Olá pessoal, estou iniciando no botkit, quero mudar a port 
Webhook endpoint online:  http://localhost:3000/api/messages
Estou usando ngrok, mais essa port esta fechada 
Tem como alterar ele  no  botkit,  se sim? como ?
