### ISSUE TITLE
Facebook sendApi errors are being swallowed

### ISSUE THREAD

**Issue by nishant-chaturvedi** [howdyai/botkit#1146]
Currently Facebook bot in the botkit, swallows the `error` objects obtained as a result of `sendApi` call, and simply passes the error message (string) to the callbacks. This makes it impossible to check sendApi `error codes` and `error subcodes` and handle those differently based on the business use cases.

It would be very helpful to pass the entire error object as opposed to just the error message to the callbacks.

**Comment by third1020** [comment]
Looks cool!

**Comment by benbrown** [comment]
Merged and shipped!
