### ISSUE TITLE
Api.ai repo for botkit-middleware-apiai has been deleted by owner

### ISSUE THREAD

**Issue by jschnurr** [howdyai/botkit#1159]
It appears that @abeai has deleted the repo hosting the [Api.ai middleware](https://github.com/abeai/botkit-middleware-apiai) (though the npm package still exists).

I've restored the source, and rebranded it to **Dialogflow**, as Api.ai has changed their name.

You can find the new version here: [https://github.com/jschnurr/botkit-middleware-dialogflow](https://github.com/jschnurr/botkit-middleware-dialogflow).

Any concerns with posting this on npm and pointing the Botkit docs to it?  Not sure what happened to the original.

**Comment by peterswimm** [comment]
Is it also your intention to keep it updated?

**Comment by jschnurr** [comment]
Yes.

**Comment by jschnurr** [comment]
PR  #1161 updates the readme, and the repo is available on npm.

If you prefer to maintain this under the howdyai account (as is the case with Wit.ai and Rasa), I'm fine to transition it there too.
