### ISSUE TITLE
Event emitting twice

### ISSUE THREAD

**Issue by vijayrawatsan** [howdyai/botkit#116]
After DRY evenremitter PR merge (https://github.com/howdyai/botkit/pull/101), events are emitting twice. See example code below:
Modify the bot.js to below 
```javascript
if (!process.env.token) {
    console.log('Error: Specify token in environment');
    process.exit(1);
}
var Botkit = require('./lib/Botkit.js');

var controller = Botkit.slackbot({
    debug: false,
});
var bot = controller.spawn({
    token: process.env.token
}).startRTM();
controller.on(['message_received', 'ambient', 'direct_mention', 'mention', 'direct_message'], function (bot, message) {
    console.log(message);
});
```
Run above code and say hello to bot in slack. Message will be logged twice.

**Comment by anonrig** [comment]
It's better to revert that commit I guess. What do you think @benbrown

**Comment by benbrown** [comment]
This has been reverted! Sorry for the trouble, @vijayrawatsan
