### ISSUE TITLE
How to use Api Ai with botkit any documention ?

### ISSUE THREAD

**Issue by Abgaryan** [howdyai/botkit#1160]

**Comment by CitiVince** [comment]
Apparently, the `botkit-middleware-apiai` repo got deleted recently and has been moved to [`botkit-middleware-dialogflow`](https://github.com/jschnurr/botkit-middleware-dialogflow). There you can find some basic introduction.

**Comment by Abgaryan** [comment]
botkit-middleware-dialogflow is not working i opened issue there .

**Comment by teerapat1739** [comment]
look cools answer.
