### ISSUE TITLE
Spark GUI deletes new lines within bot text messages ( causing display trouble)

### ISSUE THREAD

**Issue by pgoldweic** [howdyai/botkit#1162]
(disclaimer: I am not sure what exactly is responsible for this bug, so I apologize if this is not the right place to report this). 
I am using the starter kit for Spark (version 0.0.1) with Watson middleware. The symptom I see is this: in the Spark GUI, newlines (and any immediate white space) contained within the text that the bot displays - as a consequence of a bot.reply- are removed, and this causes the concatenation of the last word in some sentences to the first word of the next sentence. Moreover, for some reason Spark thinks that the longer, concatenated word is an http link and highlights it. Here's an example of what I'm talking about: 

    "Your ticket has just been successfully created, and its number is 123.It was a pleasure helping you today. Have a great day!" 

In the above, the first sentence ends with '123'. Note that '123.It' appears as one word. Moreover, it happens to appear highlighted as an http link. 
In trying to find the cause of the problem, I realized that the (default) bot code inserts newlines in between sentences before calling bot.reply() , and apparently those newlines seem to be ignored in the GUI, causing the issue. 

Can somebody confirm this?

**Comment by peterswimm** [comment]
@pgoldweic in Which client are you seeing this? I've noticed that things can render differently depending on where you are using Spark.

**Comment by pgoldweic** [comment]
Hi @peterswimm, I'm seeing this in the Spark client app on my desktop. (I am using Windows)

**Comment by peterswimm** [comment]
Just confirmed with our team that Botkit doesn't transform that type of formatting, so its either happening on Watson or the Spark API

**Comment by pgoldweic** [comment]
Thanks for confirming this. Then it must be the Spark API then (since Watson simply adds the newlines).

**Comment by peterswimm** [comment]
You could also try asking here: 
https://eurl.io/#SyNZuomKx

There are cisco employees there that may be able chime in on this.
