### ISSUE TITLE
interactive_message_callback keeps causing a timeout and not responding properly

### ISSUE THREAD

**Issue by barrettand** [howdyai/botkit#1163]
I'm trying to make a slackbot with botkit and node.js that uses message buttons. I have the following code run at the start of RTM:

```
bot.startRTM(function(err,bot,payload) {

  
  if (err) {

    throw new Error('Could not connect to Slack');

  }
  bot.say(
        {
        username: 'Daedalus',
        channel: bottestingid,
        icon_url: daedalusemoji,
        attachments:
        [
          {
            title: 'Hey there, player! Welcome to the Labyrinth minigame! Are you ready to begin?',
            callback_id: '123',
            attachment_type: 'default',
            actions: [
            {
            "name" : "enterlabyrinth",
            "text": "Enter Labyrinth",
            "value": "enter",
            "type": "button",
            },
            {
            "name" : "quit",
            "text": "No, I quit.",
            "value": "quit",
            "type": "button",
            }
            ]
          }
        ]
        }
  );

});

controller.on('interactive_message_callback', function(bot, message) {

    bot.reply(message, {
        username: 'Daedalus',
        title: "Room 1 - Daedalus",
        text: message.text,
        channel: bottestingid,
        icon_url: daedalusemoji
    });
});
```
but instead of posting a new message, it loads for 3 seconds and displays the following error:
Darn – that didn't work (error message: `Timeout was reached`)

I have the project hosted on a glitch server, https://married-mandolin.glitch.me/,
and in the slack API, I put the Interactive elements URL at https://married-mandolin.glitch.me/slack/receive and the OAuth URL at https://married-mandolin.glitch.me/oauth along with putting the token in the definition of the slackbot and slackapp of the node.js script.

Ostensibly, I should be getting a new message when I click on a button, but all it does it show the same error message time and time again. Am I doing something wrong?

**Comment by phurinaix** [comment]
no
