### ISSUE TITLE
startup message

### ISSUE THREAD

**Issue by jloveric** [howdyai/botkit#1167]
Is there a way to specify a custom startup message?  If so, how?

Thanks

John

**Comment by Naktibalda** [comment]
Do you mean the text printed to console when the bot starts?

**Comment by jloveric** [comment]
No, I mean the the message the bot sends when to when a session starts.

**Comment by Naktibalda** [comment]
Which "bot" do you use? Slack, Facebook, something else?

**Comment by jloveric** [comment]
socketbot which I don't think has been merged yet.

**Comment by benbrown** [comment]
Yes, the built-in client emits a `hello` event and a `welcome_back` event that you can use to send users welcome messages.

**Comment by peterswimm** [comment]
Closing, let us know if you have any followup questions.
