### ISSUE TITLE
 Cisco Jabber XMPP connector 

### ISSUE THREAD

**Issue by qiongfangzhang** [howdyai/botkit#1168]

**Comment by qiongfangzhang** [comment]
We create Cisco Jabber Bot based on botkit framework. To be able to connect to a Cisco Jabber bot, we add a Cisco Jabber XMPP connector into botkit. You can refer to below doc for more details.
[ChatBot-CallFlow-Example.docx](https://github.com/howdyai/botkit/files/1541493/ChatBot-CallFlow-Example.docx)

**Comment by peterswimm** [comment]
https://github.com/howdyai/botkit/pull/1169 adding a link to this to discuss

**Comment by qiongfangzhang** [comment]
@peterswimm Hi Peter, anything I need to do from my side?
