### ISSUE TITLE
My callback is getting triggered when the ask message is delivered not after I respond.

### ISSUE THREAD

**Issue by Kamalnrf** [howdyai/botkit#1174]
When I'm executing this my callback is being triggered before I respond for the question.

```
controller.hears('Reach Out', 'message_received', (bot, message) => {
    bot.startConversation(message, (err, convo) => {
      if (err) throw err
      convo.ask(`What is your emailID`, (response, convo) => {
        convo.say(`Your email ${response.text}`);
      })
    })
  })
```

**Comment by third1020** [comment]
Looks cool!

**Comment by adantoscano** [comment]
You miss convo.next(), but I don't think that's the issue. Which channel are you dev for?

**Comment by benbrown** [comment]
This is probably due to an issue with Facebook's many event types. A fix for similar problems was included in the latest release - please update to Botkit 0.6.8 and try again!
