### ISSUE TITLE
Can I build a Line Bot to join this project ?

### ISSUE THREAD

**Issue by phurinaix** [howdyai/botkit#1175]
I have an idea to make Line(Application) bot and join this project.

**Comment by jonchurch** [comment]
Yes! I'm almost done with a Line connector for Botkit

**Comment by phurinaix** [comment]
Thank you

**Comment by peterswimm** [comment]
Lets use this existing thread to discuss 

https://github.com/howdyai/botkit/issues/998

**Comment by NuttasitBoonwat** [comment]
Yes you can

**Comment by teerapat1739** [comment]
Good idea  wish you can do it
