### ISSUE TITLE
Use facebook-bot, watson Botkit with koa server

### ISSUE THREAD

**Issue by haroonKhan-10p** [howdyai/botkit#1178]
Can I use facebook, watson botkit within my existing koa server?

**Comment by jonchurch** [comment]
Sure, [here](https://blog.howdy.ai/use-your-own-express-server-with-botkit-86f6a4e10f06) is a link to setting up botkit with an express server. I'm not familiar with koa but all you need is to create a webhook to ingest events.

Here is a Watson Botkit [middleware](https://github.com/watson-developer-cloud/botkit-middleware) to use with Botkit
