### ISSUE TITLE
How to identify user's country?

### ISSUE THREAD

**Issue by julianusti** [howdyai/botkit#1185]

**Comment by Naktibalda** [comment]
What "bot" (Facebook, Slack, etc) are you using?

**Comment by Naktibalda** [comment]
You asked about Facebook profile before.
You should probably be able go get user's address with by requesting address field with controller.api.user_profile() function https://developers.facebook.com/docs/graph-api/reference/user/

**Comment by julianusti** [comment]
@Naktibalda thx mate, exactly what I need.
