### ISSUE TITLE
How to use a Addquestion in a Thread

### ISSUE THREAD

**Issue by baptistecroizer** [howdyai/botkit#1186]
Hello,

I'm actually discovering the magic world of Botkit, but I'm facing some problems for my script.
I want to create a conversational bot, with a chain of question, and for that want to use "addquestion" function in a Thread.

In the example below, if the user answer 1 to the first question, it nevers goes to the "ask_reference" thread where I've put a Addquestion with thread "ask_reference" as a parameter.

If somebody can help me on that, it will be great. Thanks !

 controller.hears(['search'], 'direct_message,direct_mention', function (bot, message) {

        bot.startConversation(message, function (err, convo) {

            convo.addQuestion("What kind of information you have)"
            , [
                {
                    pattern: "1|reference",
                    callback: function (response, convo) {
                        convo.gotoThread('ask_reference');               
                    }
                } 
                , {
                    pattern: "2|customer|name",
                    callback: function (response, convo) {
                        convo.gotoThread('ask_name');
                    }
                }
                , {
                    pattern: "cancel|stop",
                    callback: function (response, convo) {
                        convo.say("Got it, cancelling...");
                        convo.next();
                    }
                }
                , {
                    default: true,
                    callback: function (response, convo) {
                        convo.say("Sorry, I did not understand.");
                        convo.repeat();
                        convo.next();
                    }
                }
            ]);

            // ask_reference thread
           convo.addQuestion("Type the reference of the project", "ask_reference" [
                {
                    pattern: "customer1|number1",
                    callback: function (response, convo) {
                        convo.gotoThread('result_reference-1');
                }
                }
                , {
                    pattern: "customer2|number2",
                    callback: function (response, convo) {
                        convo.gotoThread('result_reference-2');
                }
                }    
                ]);         
            // result_reference 1 thread
            convo.addMessage("This is the customer 1 case and it's about specificities on botkit", "result_reference-1")
            // result_reference 2 thread
            convo.addMessage("This is the customer 1 case and it's about specificities on javascripts", "result_reference-2")

             // ask_name thread
           convo.addMessage("now enter the name of the Customer", "ask_name")
           convo.addMessage("complement", "ask_name")
        });
    });
};

**Comment by benbrown** [comment]
The thread name is actually the third parameter, not the second.

**Comment by baptistecroizer** [comment]
Thanks benbrown. But what do you mean exactly ?

**Comment by benbrown** [comment]
`convo.addQuestion('question',[conditionals],'thread_name')`

In your code example above, you have the thread name as the SECOND parameter instead of the third.

**Comment by baptistecroizer** [comment]
Thanks, it help me very much :-)
