### ISSUE TITLE
startConversation not waiting for response

### ISSUE THREAD

**Issue by dale-french** [howdyai/botkit#1188]
Hey guys

I'm using the basic convo example included in the starter repo

```
controller.hears(['color'], 'message_received', function (bot, message) {

        bot.startConversation(message, function (err, convo) {
            convo.say('This is an example of using convo.ask with a single callback.');

            convo.ask('What is your favorite color?', function (response, convo) {

                convo.say('Cool, I like ' + response.text + ' too!');
                convo.next();

            });
        });

    });
```
My bot does not wait for a response and just goes straight to 'Cool, I like (blank) too!'

I am using a Huawei p9 lite and hosting on Heroku.

Any ideas?

Thanks

**Comment by benbrown** [comment]
Is this happening on Facebook?

**Comment by dale-french** [comment]
Yes, happening on Messenger.

**Comment by benbrown** [comment]
@dale-french the problem is likely that some other event - such as message echos or deliveries - is causing your bot to move forward.  This is a known issue that is being addressed soon.

In the meantime, I suggest turning OFF those events on the Facebook API portal.

**Comment by imrank1** [comment]
I had the same issue and had to turn off message_reads as well

**Comment by benbrown** [comment]
@dale-french update to the latest Botkit 0.6.8 and this problem will go away!
