### ISSUE TITLE
MS Teams using "/" not "/teams/teams" for mention in channel 

### ISSUE THREAD

**Issue by auberryberry** [howdyai/botkit#1189]
Hiiiiiii,  I've had some really great success in the past with BotKit and Slack.  I'm just trying to integrate with MS Teams, a little more tricky but not impossible.  I've reached a point where a 1:1 conversation with the bot is work ing find and my handlers kick in when you say the right stuff, great!

However, if I do an @ bot, instead of using the defined "/teams/receive" endpoint, it switches to using "/", now I've monkey patched a handler in for "/" to do the same as the teams/receive endpoint but It will just send a 200 back and hang for a while before saying there was a problem in teams.

Is this known/expected behaviour? Again really great job, it didn't take me too long to get this up and running the documentation will need an update soon because the registration method for a bot will currently expire in 3 months, I'll try and help with that if I get to it before anyone else.

**Comment by auberryberry** [comment]
There is a strong change this is a nuance with setting up a teams bot, it looks like when you direct add a bot to teams ( the zero pain method ), you end up restricting it to just 1:1 conversations, the pain and manifest version is what get's you team conversations, will report back shortly with learnings.

**Comment by auberryberry** [comment]
Two confirm, this was because the bot needed to be sideloaded, without sideloading you're restricted to 1:1 conversations and mentioning a bot in channel will yield the / root call I was seeing. RTFM ;)

**Comment by peterswimm** [comment]
@auberryberry thanks for figuring that out, we'll think about ways to make that more explicit in the docs.

**Comment by auberryberry** [comment]
No worries @peterswimm and thank you, maybe I’m a bit of a pioneer when it comes to teams and BotKit, I don’t suppose you saw my message in Slack?

**Comment by peterswimm** [comment]
@auberryberry I did not but feel free to @ mention me in a thread based on it if you need anything further!

**Comment by auberryberry** [comment]
Also just wanted to mention, I created a new bot in azure the other day, it didn't honour my updated /teams/receive endpoint in MS Teams for about 8 hours at a guess, nothing to do with code and everything to do with a cache between teams and azure or bot portal, so my original explnation might not have been correct at all. if you're seeing this issue, update your endpoint and wait at least 8 hours for teams to pickup the new endpoint from azure bot def.

**Comment by peterswimm** [comment]
@auberryberry You might want to report that to Microsoft, perhaps the service was having trouble?

**Comment by auberryberry** [comment]
@peterswimm you should have heard my frustration on the support call, maybe you have a better route for me to report? I couldn't get the support person to pass it on.

**Comment by auberryberry** [comment]
I should note, when testing, the test web chat in azure WAS honouring the endpoint change, it was only Teams that wasn't picking up the change

**Comment by peterswimm** [comment]
https://docs.microsoft.com/en-us/bot-framework/bot-service-resources-links-help
