### ISSUE TITLE
Documentation is missing a [

### ISSUE THREAD

**Issue by rselwyn** [howdyai/botkit#119]
If you go to the [docs](http://howdy.ai/botkit/docs/) and go down to the section for "Matching Patterns and Keywords with `hears()`" (I suggest using `Command-F`), you can see that the example

```
controller.hears("keyword","^pattern$"],["direct_message","direct_mention","mention","ambient"],function(bot,message) {

	  // do something to respond to message
	  // all of the fields available in a normal Slack message object are available
	  // https://api.slack.com/events/message
	  bot.reply(message,'You used a keyword!');

	});	
```

is missing a `[` before `"keyword"`, causing the error

`SyntaxError: missing ) after argument list`

**Comment by peterswimm** [comment]
Fixed
