### ISSUE TITLE
[Slack] Bot code examples

### ISSUE THREAD

**Issue by atherdon** [howdyai/botkit#1190]
Did Botkit have some big opensourced Slack bot examples for some inspiration, grow experience and study from pros?

**Comment by peterswimm** [comment]
We have this: 
https://github.com/howdyai/botkit/tree/master/examples/slack

But we are thinking of ways to have more examples of complete bots, probably in conjunction with our Botkit Studio project, akin to what our friends at Cisco have made:

https://github.com/howdyai/trello-ciscospark

**Comment by peterswimm** [comment]
Track these efforts here: https://github.com/howdyai/botkit/projects/2

**Comment by atherdon** [comment]
Like this project: https://github.com/markstickley/spotifyslackbot/blob/master/spotifybot.js

**Comment by peterswimm** [comment]
@atherdon that is a _very_ old version of botkit. It might be more helpful to look at stuff like these cisco projects which are based on more recent versions of Botkit:
https://ciscosparkambassadors.github.io/StarterKits/

We want more slack examples in 2018, so stay tuned!
