### ISSUE TITLE
How to interact with the webhook notification 

### ISSUE THREAD

**Issue by MagSag** [howdyai/botkit#1194]
Facebook has a lot of of webhook to wich I would like to subscribe so that for instance when the user changes his birthdate, name or email, or location I can receive and update  on my side.
[
https://developers.facebook.com/docs/graph-api/webhooks ](Webhook article).. How can I handle these notifications in botkit?

**Comment by ouadie-lahdioui** [comment]
be careful, there's general fb webhooks that's allows you to receive real time http notifications of any changes to specific objects in the graph API, and fb messenger webhooks to send events to your webhook to notify your bot when a variety of interactions or events happen ([doc here](https://developers.facebook.com/docs/messenger-platform/webhook))
