### ISSUE TITLE
How to have multiple bots configured in one projects

### ISSUE THREAD

**Issue by MagSag** [howdyai/botkit#1195]
I have 1000 pages and I don't want to have 1000 node application running for these 1000 pages, I just want 1 node application but with 1000 bots that it is running and each having a different webhook url.

How can I acheive that in Botkit knowing that the numbers of page may increase?

**Comment by peterswimm** [comment]
There is discussion on this topic here:
https://github.com/howdyai/botkit/issues/914

What are you doing with 1000 pages?

**Comment by MagSag** [comment]
Thanks, the thing is I am running bot for many people same feature and some have more feature, maintain all these 1000 projects in different place is kind of hard.

**Comment by peterswimm** [comment]
Ah yes this is tricky, Id post your required features in the RFC thread above and follow development there!
