### ISSUE TITLE
Test the bot in development environment (locally)

### ISSUE THREAD

**Issue by MagSag** [howdyai/botkit#1196]
Is there any feature like that in botkit allowing me to test how my bot react to different action instead of doing it directly on for example facebook messenger...This because once the bot is live it is not good to put the bot again back on the development environment code.

Something like unit test

**Comment by Naktibalda** [comment]
https://github.com/codeforequity-at/testmybot
Sample for botkit: https://github.com/codeforequity-at/testmybot/tree/master/samples/botkit/jasmine

**Comment by MagSag** [comment]
thanks.
