### ISSUE TITLE
Is Studio Token Mandatory

### ISSUE THREAD

**Issue by nexright-krishna** [howdyai/botkit#1198]
I am using bot kit framework for multiple channels in my project. Channels include facebook and Web. We are planning to extend our application for Slack as well. We can see a studio token is used in the starter applications for every channel. I have below few queries on this token.
1- Is the studio token mandatory for all channels. If yes, can we create a studio token from any command line interface
2- Is it mandatory to create a bot app in the studio to use the botkit framework.
Versions:

"botkit": "git+https://git@github.com/howdyai/botkit.git#dev/webchannel",
    "botkit-storage-mongo": "^1.0.7",
    "botkit-studio-metrics": "0.0.1",

**Comment by peterswimm** [comment]
It is *not* mandatory, but strongly encouraged. In the starter kits, simply leaving out the studio token will disable studio functionality if that is your choice.
