### ISSUE TITLE
Is it possible to disable studio?

### ISSUE THREAD

**Issue by jloveric** [howdyai/botkit#1202]
I've been getting errors with each message sent to my bot and the error occurs in studio

```
An error occured in the receive middleware:  Error: Illegal argument null
    at module.exports (node_modules/md5/md5.js:152:13)
    at node_modules/botkit/lib/Studio.js:809:23
    at node_modules/botkit/lib/CoreBot.js:1257:56
    at next (node_modules/ware/lib/index.js:82:27)
    at Ware.run (node_modules/ware/lib/index.js:88:3)
    at Object.Botkit.botkit.trigger (node_modules/botkit/lib/CoreBot.js:1255:45)
    at node_modules/botkit/lib/CoreBot.js:1204:36
    at next (node_modules/ware/lib/index.js:82:27)
    at Ware.run (node_modules/ware/lib/index.js:88:3)
    at Object.<anonymous> (node_modules/botkit/lib/CoreBot.js:1202:49)
```

I commented out the lines at the bottom of CoreBot and resolved the issue.
```
//studio(botkit);
```

The Bot seems to works fine and no longer prints the errors to the console.  Is there a way to disable Studio as a configuration option?

**Comment by peterswimm** [comment]
Did you start with the starter kit? It would be useful to see your custom code, as it should not invoke studio without a studio token.

**Comment by jloveric** [comment]
I started with the botkit web-starter (a while back) which had a studio token and removed a bunch of stuff as I didn't want to connect with studio - I then used parts as the basis for my bot.  I must have something in there that I shouldn't.  I'll look at this.

**Comment by jloveric** [comment]
Ok, it looks like I need to set a controller config option.  This solved the problem
```javascript
let bot_options = {stats_optout : true}
let controller = SocketBot(bot_options)
```

**Comment by peterswimm** [comment]
Still unclear why you are seeing those studio errors, but yes you are correct those will disable anything being sent our way for processing.

**Comment by nmurthy18** [comment]
Hi Peter,
Want to know whether Botkit Studio is open source or not !!!
When trying to connect with it, Botkit Studio is no longer accepting new registrations. pop ups
