### ISSUE TITLE
question/answer logging

### ISSUE THREAD

**Issue by jloveric** [howdyai/botkit#1204]
Is there a mechanism built into botkit for logging the user statements and the response given by the bot.  I'm basically looking for logging, but only for the messages sent between the bot and the user (not error or info logs).

**Comment by peterswimm** [comment]
You can do something like this:
https://github.com/howdyai/botkit/blob/master/docs/logging.md

And have bot and user interactions trigger the advanced logging levels.

**Comment by jloveric** [comment]
Thanks!
