### ISSUE TITLE
Bot Framework Skype channel regular expressions not working

### ISSUE THREAD

**Issue by gcfabri** [howdyai/botkit#1205]
## Bot Info
* SDK Platform: Node.js
* SDK Version: Bot Builder 3.13.1 with Botkit 0.6.7
* Active Channels: Skype, Messenger, Telegram and Web
* Deployment Environment: Azure Bot Service and Azure App Service

## Issue Description
I built a bot using Bot Framework (node.js) with four connected channels (Messenger, Telegram, Skype and Web). At any moment the bot validates an inputted email address using a regular expression like this below:

    /^[-a-z0-9~!$%^&*_=+}{\'?]+(\.[-a-z0-9~!$%^&*_=+}{\'?]+)*@([a-z0-9_][-a-z0-9_]*(\.[-a-z0-9_]+)*\.(aero|arpa|biz|com|coop|edu|gov|info|int|mil|museum|name|net|org|pro|travel|mobi|[a-z][a-z])|([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}))(:[0-9]{1,5})?$/i

It is working properly on all channels, except the Skype. E.g: *gcfabri@gmail.com* match with this regex but on Skype channel it doesn't happens.

## Code Example
`emailRegex.test(`gcfabri@gmail.com`);`

## Expected Behavior
The email address _gcfabri@gmail.com_ should match with the regex above.

## Actual Results
Skype channel just ignore the step with the regex validation.

**Comment by peterswimm** [comment]
The fact that three out of four platforms work makes me think this is a Bot Framework problem, have you tried creating an issue on their Github?
https://github.com/Microsoft/BotBuilder

Botkit is just passing information to Botframework, so if Skype needs special preparation, on their end would the best place for that to happen.
