### ISSUE TITLE
[Messenger] Conversation problem with iterators.

### ISSUE THREAD

**Issue by MarcelloRCestaro** [howdyai/botkit#1210]
Hey guys, 

I'm having a problem on Conversation. I'm using the Watson Botkit Middleware, and if there is multiple messages in a row, it gives a list of strings, each one being a message. So I created an iterator inside a conversation so it can deliver in the right order, but for some reason, he only shows the first message. The code is below. 

```
controller.hears('(.*)', 'message_received', function(bot, message) {
    var aux = message.watsonData.output.text;
    bot.createConversation(message, function(err, convo) {
      for (i = 0; i < aux.length; i++){
        var ax = aux[i];
        convo.say(ax);
      };
      convo.activate();
  });
});
```

Does anyone have any idea of what is wrong?

**Comment by Naktibalda** [comment]
Hi @MarcelloRCestaro,

I use Watson Botkit Middleware with SocketBot, but I've never tried to use Botkit Conversations.
The code  gave an impression that Botkit Conversation will intercept any input when it is active, so I didn't like that.
In the beginning I called `bot.reply` in a loop, but my current code looks like this:
```typescript
const replyAsync = Promise.promisify(bot.reply).bind(bot);

return Promise.mapSeries(replies, (reply: string, index: number) => {
    const replyMessage: any = {
        text: reply
    };
    //add additional attributes here
    
    return replyAsync(message, replyMessage);
}).then(() => {
    //do nothing to return void
});
```

**Comment by MarcelloRCestaro** [comment]
Hello @Naktibalda, 
Thanks for the help! Though I already fixed my code. Seems like what was wrong with it is that there is some kind of bug (?) with the "require_delivery: true" on the Facebook connector, which when it's active, the conversations only send the first message. I removed that line of the code, and now it works perfectly!

**Comment by peterswimm** [comment]
Thanks for sharing, we'll close this issue, and keep an eye on that facebook require bug.
