### ISSUE TITLE
How to add responders to pagerduty from slack through botkit studio (Help)

### ISSUE THREAD

**Issue by ManjunathanR** [howdyai/botkit#1211]
I have done slack to pager duty integration I want to add button in slack for responders and same should reflect in Pager duty pls help

**Comment by ManjunathanR** [comment]
Please provide the code so I need to implement this or advise the steps for the above

**Comment by ManjunathanR** [comment]
Pls check this ASAP.

**Comment by peterswimm** [comment]
@ManjunathanR Sorry to say I am unaware of an example code for this specific use case. You can try asking in the slack community https://community.botkit.ai/
