### ISSUE TITLE
Facebook is taking too long to send message to the bot

### ISSUE THREAD

**Issue by MagSag** [howdyai/botkit#1215]
I have sets up my webhook and when I run the bot it is not showing any error but when I try to talk to the bot from facebook ... the message I sent is not reaching the bot. Facebook is not contacting the bot.

And sometimes facebook is even showing the bot is offline yet the bot is running.

I even check my ngrok inspect page...there is no request coming from facebook even from there.

![webhookproblem](https://user-images.githubusercontent.com/13017395/35033193-bfe45baa-fb7a-11e7-9a0f-c59007ddc2e4.JPG)
So I would like to change the **user** to **page** (top left under webhook title) to see if it will change something but unfortnately when I select page and leave the dashboard it goes back to user again.

**Comment by peterswimm** [comment]
It could be something is blocking ngrok from talking to the outside world, did check your provisioning settings?

**Comment by MagSag** [comment]
It was the problem with the webhook, I subscribed to the user and page webhook each having a different webhook link. Where I unsubscribed to the user everything became normal. 

I would like to know what are the difference and use case of these webhook(user,page,application....)
