### ISSUE TITLE
code for adding button in javascript , add it bot and call it in slack(Help)

### ISSUE THREAD

**Issue by ManjunathanR** [howdyai/botkit#1218]
Please any provide the code for adding button in bot and call it in slack.
explain the steps how it can be done

**Comment by peterswimm** [comment]
Here you go
https://github.com/howdyai/botkit/blob/master/examples/slack/slackbutton_bot_interactivemsg.js

**Comment by ManjunathanR** [comment]
I am getting the below error

Error: Cannot find module 'C:\Users\i316454\Desktop\Slack bot project\botkit-master\examples\slackbutton_bot_interactivemsg.js'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
