### ISSUE TITLE
slackbutton_bot_interactivemsg.js add to the slack but not able to interact(help)

### ISSUE THREAD

**Issue by ManjunathanR** [howdyai/botkit#1220]
Hi Peter,

I read the documentation thanks for that I already know how to create a bot.

But the above script is what I required, after adding it to bot if we interact bot won't reply. Please provide the event subscription url so it will receive. 

Please advise how to use button in the above javascript. @peterswimm

**Comment by peterswimm** [comment]
You will need to host your bot somewhere accessible to the public. Details:

https://github.com/howdyai/botkit/blob/master/docs/hosting-your-own-bot.md

This forum isn't the best place to ask super basic questions, but if you need more help, just reply to this thread.
