### ISSUE TITLE
Accessing set vars

### ISSUE THREAD

**Issue by yleflour** [howdyai/botkit#1227]
Hello,

I have just started using botkit and can't figure out how to access set vars outside of the mustache templates.

I feel like the `Conversation` needs a `getVar` method. I could easily implement this so please tell me if it sounds reasonable.

**Comment by Purus** [comment]
Can we do this something like convo.getVar('key')?

**Comment by peterswimm** [comment]
this is Studio-centric, but the same basic principles apply: https://blog.howdy.ai/build-a-bot-data-powered-conversations-d14991714ac1
