### ISSUE TITLE
Typescript typing for bot.replyAndUpdate

### ISSUE THREAD

**Issue by ThomWright** [howdyai/botkit#1229]
The current type:

https://github.com/howdyai/botkit/blob/6f6ee8c8d88cf5c2e286094b232d477836ec6401/lib/Botkit.d.ts#L257

I think it should be something like:

```ts
replyAndUpdate(src: SlackMessage, resp: string | SlackMessage, cb: (err: Error, res: string, updateResponse: (newResp: string | SlackMessage, cb?: (err: Error) => void) => void): void;
```

This contains the extra `updateResponse` callback found in the docs: https://github.com/howdyai/botkit/blob/master/docs/readme-slack.md#botreplyandupdate

**Comment by Naktibalda** [comment]
@ThomWright Please make a pull request.
