### ISSUE TITLE
Is Botkit handles this requirements from Messanger :  Breaking Change Notice - messaging_type Property Required (Effective May 7, 2018)

### ISSUE THREAD

**Issue by Abgaryan** [howdyai/botkit#1234]
Breaking Change Notice - messaging_type Property Required (Effective May 7, 2018)

As of the release of Messenger Platform v2.2, we are requesting developers to include the messaging_type property in all message sends.

Beginning May 7, 2018, this property will be required for all message sends. After this date, message sends that do not include messaging_type will return an error and not be delivered.

For more information on the messaging_type property, see Messaging Types below.

https://developers.facebook.com/docs/messenger-platform/send-messages#messaging_types

**Comment by peterswimm** [comment]
https://github.com/howdyai/botkit/blob/040ced1aa79a8215b25660651507ecf8be054687/docs/readme-facebook.md#messaging-type I believe this should satisfy the requirement, @ouadie-lahdioui: Do you agree?

**Comment by ouadie-lahdioui** [comment]
Totally agree ! Botkit sends a default messaging_type value each time we try to send a simple message with : ````bot.reply(message, "this is a simple message")```` or ````conversation.say("this is a simple message")```` or ````conversation.ask("this is a simple message", ...)````

So, don't be afraid, your bot still work fine if you migrate to v0.6.8 or higher.

**Comment by peterswimm** [comment]
Closing for now, feel free to ask related questions here!
