### ISSUE TITLE
botkit-middleware-dialogflow  stops working after updating botkit verion to 0.6.9 #4

### ISSUE THREAD

**Issue by Abgaryan** [howdyai/botkit#1236]
This module stops working after updating botkit verion to 0.6.9

**Comment by Abgaryan** [comment]
I added  **_pipeline : ''**  to received message  otherwise app crashed with this error message :
_TypeError: Cannot set property 'stage' of undefined
  File "/usr/src/app/node_modules/botkit/lib/CoreBot.js", line 127, in Object.Botkit.botkit.receiveMessage
            message._pipeline.stage = 'receive';_

**Comment by peterswimm** [comment]
Do you happen to know the last version of Botkit that worked for you?

**Comment by Abgaryan** [comment]
@peterswimm  it was 0.5.2 .

**Comment by peterswimm** [comment]
You might want to make sure your code has made a note of the pipeline changes:
https://github.com/howdyai/botkit/blob/master/docs/howto/upgrade_05to06.md

You can test this with a clean version of the latest starter kit to see if that is the issue.

**Comment by Abgaryan** [comment]
@peterswimm  I checked It seems I followed instructions, but still not working.

**Comment by peterswimm** [comment]
@Abgaryan did you try with a clean starter kit?

**Comment by Abgaryan** [comment]
@peterswimm  Yes I did it is not working still.

**Comment by peterswimm** [comment]
You should post an issue on their github, they might have to make changes to support the most recent versions of botkit:
https://github.com/jschnurr/botkit-middleware-dialogflow

**Comment by Abgaryan** [comment]
I did https://github.com/jschnurr/botkit-middleware-dialogflow/issues/4

**Comment by peterswimm** [comment]
Closing this issue for now, please let us know if you require help from the botkit team over there.

**Comment by Abgaryan** [comment]
Please reopen the issue is still exists
