### ISSUE TITLE
botkit say sending empty message

### ISSUE THREAD

**Issue by asosa9991** [howdyai/botkit#1237]
https://github.com/howdyai/botkit/blob/9cf9bd0dcd193807312572ec9943d728b4e3bf5e/lib/CoreBot.js#L1363

After migrating to this latest version, we are seeing empty message is being passed and it looks like the platform_message is never getting set. Please advise.

**Comment by Naktibalda** [comment]
Which network (Slack, Facebook, etc) is your bot using?

platform_message is populated by format middleware which is specific to network:
https://github.com/howdyai/botkit/blob/6f6ee8c8d88cf5c2e286094b232d477836ec6401/lib/BotFramework.js#L137
https://github.com/howdyai/botkit/blob/dc0e780d3a50ffbfe89bc8f3908d1f8869d61466/lib/Facebook.js#L28
https://github.com/howdyai/botkit/blob/6f6ee8c8d88cf5c2e286094b232d477836ec6401/lib/SlackBot.js#L471

**Comment by asosa9991** [comment]
We migrated from 0.5.4 and using a bot that extended from CoreBot ../botkit/lib/CoreBot.js

**Comment by Naktibalda** [comment]
All Bots extends CoreBot, do you use builtin Bot or a custom made one?

If you have implemented your own custom Bot, the you have to add format middleware to it.
Documentation here: https://github.com/howdyai/botkit/blob/master/docs/readme-pipeline.md#format

**Comment by asosa9991** [comment]
Yes, we have a custom bot. Thanks for the clarification.
