### ISSUE TITLE
Botkit spams console too much, making it hard to look for real debug messages

### ISSUE THREAD

**Issue by catcher-in-the-try** [howdyai/botkit#1238]
On each answer to user, Botkit spams the console with several pages of text, which makes it hard to look for the actual debug messages that I'm printing. The most offending line in BotFramework.js are lines 65 and 85:

```js
console.log('SENDING VIA BOT FRAMEWORK', bf_message);
console.log('SENDING REPLY', msg);
```

Perhaps it makes sense to replace `console.log` with `botkit.debug` or use another way to disable the large amounts of output.

**Comment by Naktibalda** [comment]
logging in different connectors is inconsistent, you are welcome to reduce the number of logging (or remove it completely) and make a pull request.

**Comment by benbrown** [comment]
We should definitely reduce these console log messages! @catcher-in-the-try feel free to send us a pull request, or at least open an issue to address this!

**Comment by AbrahamFergie** [comment]
may I take this issue? @peterswimm?

**Comment by peterswimm** [comment]
@AbrahamFergie anyone who wants to undertake a PR to spark a discussion by all means do so.

**Comment by AbrahamFergie** [comment]
@benbrown or @peterswimm I was hoping to gain a little insight as to the reason for sometimes using ```botkit.log("some string")``` and other times using ```botkit.debug("some string")```. Just hoping to see why those decisions are made so i can make the appropriate fixes with the right functions.
