### ISSUE TITLE
ERROR in messenger profile API call:  API calls from the server require an appsecret_proof argument

### ISSUE THREAD

**Issue by MagSag** [howdyai/botkit#1239]
I configured everything as stated [botkit doc](https://github.com/howdyai/botkit/blob/master/docs/readme-facebook.md#thread-settings-api) and [facebook doc](https://developers.facebook.com/docs/graph-api/securing-requests/) for app secret proof  but I am getting the following error : 

> info: ERROR in messenger profile API call:  API calls from the server require an appsecret_proof argument
> info: ERROR in messenger profile API call:  API calls from the server require an appsecret_proof argument
> info: ERROR in messenger profile API call:  API calls from the server require an appsecret_proof argument

Here is  setup of the bot:
```
 var controller = Botkit.facebookbot({
     //debug: true,
    verify_token: process.env.verify_token,
    access_token: process.env.page_token,
   // app_secret: process.env.app_secret,
   // require_appsecret_proof: true, // Enable send app secret proof
    studio_token: process.env.studio_token,
    studio_command_uri: process.env.studio_command_uri,
});
```

**Comment by Naktibalda** [comment]
Your app_secret and require_appsecret_proof configuration lines are commented out,
delete `//` in both lines.

**Comment by MagSag** [comment]
I commented after it failing to work.

**Comment by ouadie-lahdioui** [comment]
Can you share the exact code you used (without comments) ?
What's the value of process.env.app_secret var env ?

**Comment by MagSag** [comment]
IT was my app secret code ... I have just notice I have to encrypt not use it directly.

**Comment by ouadie-lahdioui** [comment]
You don't need to encrypt using hmac, Botkit already do that for you !

Verify juste if your access token and app secret are ok
