### ISSUE TITLE
Does RTM support team_migration_started event?

### ISSUE THREAD

**Issue by jutaz** [howdyai/botkit#124]
As documented in Slack [team_migration_started](https://api.slack.com/events/team_migration_started) event happens when teams are being switched between servers. Does botkit RTM handle that?

**Comment by benbrown** [comment]
You can listen for that event, but currently Botkit does nothing with it by default.

```
controller.on('team_migration_started',function(bot,message) {
// message contains the original message from slack
});
```

**Comment by jutaz** [comment]
Yeah, so currently we need to re-connect manually?

**Comment by benbrown** [comment]
You can pass in retry: true to your call to controller.spawn
