### ISSUE TITLE
callbacks and Middleware for  addMessage and addQuestion

### ISSUE THREAD

**Issue by MagSag** [howdyai/botkit#1240]
I want to build a complex conversation flow but with a possibility of saving the question that I sent to the user in a way that if they user come back after 2 days to answer I must link the answer to this last question.

I can't see a way to achieve that so I was think that enhancing the addMessage and addQuestion method with call backs and middleware that can be executed after the question is sent before the callback that will be called when there is a response will help so much.

If there is a way of doing that , how can I acheive this?

**Comment by peterswimm** [comment]
This is a similar thread https://github.com/howdyai/botkit/issues/506
