### ISSUE TITLE
Encoding is not support French text from thread_settings.

### ISSUE THREAD

**Issue by MagSag** [howdyai/botkit#1242]
I have setup the greeting text in english and french but the problem is some of french characters are not being displayed correctly : é = � , è=� , à = �

```
controller.api.thread_settings.greeting([{
                "locale": "default",
        "text": "Sent to you."
    
            }, {
                "locale": "fr_FR",
        "text": "Envoyé à toi ."
```
            }]);

**Comment by Naktibalda** [comment]
You french characters are in ISO-8859-1 encoding, try saving your file as UTF-8.

**Comment by MagSag** [comment]
Done. It is working well now. Thanks.
