### ISSUE TITLE
Botkit for Web

### ISSUE THREAD

**Issue by swagat123** [howdyai/botkit#1243]
Can we have a botkit for web example. Botkit starter web is for botkit studio and it required studio token. can we get botkit for web without using any of the studio features and studio token.

**Comment by Naktibalda** [comment]
You can clone it and delete all code related to botkit studio (and make any other modifications you like).
That's how I am using it.

**Comment by peterswimm** [comment]
@swagat123 What @Naktibalda said. Studio provides lots of features you'll need to use your bot, you should give it a try!
