### ISSUE TITLE
Is there an Facebook API to block user?

### ISSUE THREAD

**Issue by MagSag** [howdyai/botkit#1247]
How can I block a user who is sending useless message to my bot?

**Comment by peterswimm** [comment]
There is nothing in botkit pre-built to do this, but perhaps you can store the user record and simple drop requests from that user?
https://developers.facebook.com/docs/messenger-platform/identity/user-profile

Another idea is simply block the user from interacting with your page:
https://www.facebook.com/help/185897171460026
