### ISSUE TITLE
how to prevent a convo to start when another one is current?

### ISSUE THREAD

**Issue by pgoldweic** [howdyai/botkit#1251]
I have a few very simple conversations in my bot that use bot.startConversation (they simply constitute in a question and immediate answer by the user). However, some of them can get triggered while another one is current -and waiting for the user's answer-. Specifically, I have this scenario:
1- one conversation starts when the user talks to the bot after not having talked for X amount of time (and asks the user whether he/she wants to start or resume the conversation). 
2- another conversation starts for other reasons, such as displaying the result of a search and asking the user for feedback. 
So sometimes conversation 2 starts, and if the user presents feedback to the bot *after* X amount of time, then conversation 1 gets triggered. My question then is: is there a way to prevent conversation 1 from starting, given that conversation 2 is current?. Alternatively, is there a way to get the nesting to actually work?

**Comment by OmranAbazid** [comment]
Maybe there is a proper way to do it. But it can be easily done in Javascript.
just create a global variable as a hash table of boolean
when the user enters conversation two just do this: 

`checkSecondConvo[message.user] = true;`

now in the first convo, always check
```
if(!checkSecondConvo[message.user]) {
  // start first convo
}
```
