### ISSUE TITLE
I trying to run a bot program in windows i installed the ruby but whenever i run the program getting the below error msg . Please help

### ISSUE THREAD

**Issue by ManjunathanRajan** [howdyai/botkit#1255]
C:\pagerbot-master>bundle exec ruby pagerbot.rb
Could not find gem 'eventmachine x64-mingw32' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.

C:\pagerbot-master>bundle install
Fetching gem metadata from http://rubygems.org/..........
Fetching gem metadata from http://rubygems.org/..
Resolving dependencies...
Using concurrent-ruby 1.0.5
Using i18n 0.9.5
Using minitest 5.11.3
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using activesupport 4.2.10
Using bundler 1.16.1
Fetching curb 0.9.4
Installing curb 0.9.4 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/curb-0.9.4/ext
C:/Ruby25-x64/bin/ruby.exe -r ./siteconf20180215-16544-2b6jdx.rb extconf.rb
checking for curl-config... no
checking for -lcurl... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby25-x64/bin/$(RUBY_BASE_NAME)
        --with-curl-dir
        --without-curl-dir
        --with-curl-include
        --without-curl-include=${curl-dir}/include
        --with-curl-lib
        --without-curl-lib=${curl-dir}/lib
        --with-curllib
        --without-curllib
extconf.rb:18:in `<main>':   Can't find libcurl or curl/curl.h (RuntimeError)

  Try passing --with-curl-dir or --with-curl-lib and --with-curl-include
  options to extconf.

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

C:/Ruby25-x64/lib/ruby/gems/2.5.0/extensions/x64-mingw32/2.5.0/curb-0.9.4/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/curb-0.9.4 for inspection.
Results logged to
C:/Ruby25-x64/lib/ruby/gems/2.5.0/extensions/x64-mingw32/2.5.0/curb-0.9.4/gem_make.out

An error occurred while installing curb (0.9.4), and Bundler cannot continue.
Make sure that `gem install curb -v '0.9.4'` succeeds before bundling.

In Gemfile:
  curb

**Comment by ManjunathanRajan** [comment]
i tried installing gem install curb -v '0.9.4' even that didn't work please advise on this

**Comment by peterswimm** [comment]
This is not in reference to Botkit code, sorry!
