### ISSUE TITLE
Installing Error on Windows10 64

### ISSUE THREAD

**Issue by ahmmu15** [howdyai/botkit#1258]
I get this error every time I'm trying to install botkit on my machine, it's related with Python. I don't know why I need Python, but I installed it anyway, and also added it to path var on my system, but the same error goes on and and on. :(

Anyone knows how to solve that? Is it a bug, or it's just me doing things wrong? 

Thank you in advance :) 

```
Error: Can't find Python executable "C:\Users\ahmmu\AppData\Local\Programs\Python\Python36-32\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\ahmmu\AppData\Roaming\npm\node_modules\botkit\node_modules\node-expat
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-expat@2.3.16 install: node-gyp rebuild
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-expat@2.3.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ahmmu\AppData\Roaming\npm-cache\_logs\2018-02-21T23_51_02_533Z-debug.log
```

**Comment by ahmmu15** [comment]
Guys! I figured it out. :) It's an error related with node-gyp (Node.js native addon build tool). 

**On Windows, you have to install:**
- [Visual C++ Build Environment](http://landinghub.visualstudio.com/visual-cpp-build-tools)
- [Python 2.7](https://www.python.org/downloads/release/python-2714/) _(Python 3 is NOT supported)_.
- Then configure your machine using the command `npm config set msvs_version 2015`

There's also another option that'll do all of that for you (I didn't try it) `npm install --global --production windows-build-tools` => _you have to run the cmd as administrator in order to run that without errors_.

Check the [documentation](https://github.com/nodejs/node-gyp) for more info :)

**Comment by MagSag** [comment]
It doesn't not solve the error.
