### ISSUE TITLE
I can't update botkit, I am getting error

### ISSUE THREAD

**Issue by MagSag** [howdyai/botkit#1261]
I am trying to update botkit which in packjson is : 

 `   "botkit": "^0.6",`
but I am getting this error :  

> node-expat@2.3.16 install E:\Documents\ca\buou\bo\node_modules\node-expat
> node-gyp rebuild
> 
> E:\Documents\ca\buou\bo\node_modules\node-expat>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
> gyp ERR! configure error
> gyp ERR! stack Error: Can't find Python executable "C:\Users\ams\.windows-build-tools\python27\python.exe", you can set the PYTHON env variable.

**Comment by peterswimm** [comment]
You might want to try an NPM install of Botkit to make sure the needed dependencies are getting built. This is similar to what this user went through last week: https://github.com/howdyai/botkit/issues/1258

**Comment by MagSag** [comment]
I don't get what you mean by trying an NPM install of Botkit...
I have tried doing what is described in #1258 but I am still getting the same error.

**Comment by peterswimm** [comment]
https://github.com/howdyai/botkit#command-line-interface I am referring this install method.

**Comment by benbrown** [comment]
@MagSag You should not upload to 0.6.11

**Comment by MagSag** [comment]
The problem is I was already coding and the bot is working,  it is just I want to update the botkit, using the command line seems as if everything is starting from scratch.

Is it possible to use that method on an existing project ? how ?

**Comment by MagSag** [comment]
I really need help on this.

**Comment by MagSag** [comment]
I really need help on this.

**Comment by peterswimm** [comment]
Did you try downgrading to .6.8?

**Comment by MagSag** [comment]
I changed the version from 0.6 to 0.6.8 in package.json depency and then I run  : npm install -S
and I got this error : 

> npm ERR! path E:\Documents\ca\buou\bo\node_modules\bl\node_modules\isarray
> npm ERR! code ENOENT
> npm ERR! errno -4058
> npm ERR! syscall rename
> npm ERR! enoent ENOENT: no such file or directory, rename 'E:\Documents\ca\buou\bo\node_modules\bl\node_modules\isarray' -> 'E:\Documents\ca\buou\bo\node_modules\concat-stream\node_modules\isarray'
> npm ERR! enoent This is related to npm not being able to find a file.

**Comment by peterswimm** [comment]
What version were you updating from? Where is your bot being hosted?

**Comment by MagSag** [comment]
0.6.5
But Now I have found solution, I ran this command : `npm install -g node-gyp`
