### ISSUE TITLE
Need clarification for how to use the new timeout feature within convo.ask

### ISSUE THREAD

**Issue by pgoldweic** [howdyai/botkit#1262]
It is not clear to me when to call setTimeout on a given conversation to set an explicit timeout for a given question to be answered. For example, I'd like to ensure that this conversation ends if the user does not respond in more than 15 minutes or so. Where exactly should I insert the call? The docs mention a 'convo.ask' handler as the place, but aren't the callbacks below called only when the user actually replies? Please clarify. Thanks in advance.

    bot.startConversation(message, (err, convo) => {
        if (err) throw(err)
        convo.ask("I'd like your feedback. Please enter 1-3, 'none' or 'cancel'",
            [
            { pattern: '1|2|3|none|cancel',
              callback: function(response, convo) {
                    console.log("Yay! we are done...")
                    convo.next()
             },
            { default: true,
              callback: function(response, convo) {
                      console.log("Bot didn't understand... repeating question")
                      convo.repeat()
                     convo.next()
              }
           }
          ], {key: 'feedback'})

**Comment by ronnyli** [comment]
I have the same question except for `convo.addMessage`
