### ISSUE TITLE
docker build fails

### ISSUE THREAD

**Issue by itsgiff** [howdyai/botkit#1267]
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

> node-expat@2.3.16 install /app/node_modules/node-expat
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:397:16)
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:170:21)
gyp ERR! System Linux 4.9.60-linuxkit-aufs
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/node_modules/node-expat
gyp ERR! node -v v9.6.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN lodash-decorators@4.5.0 requires a peer of lodash@4.x but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-expat@2.3.16 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-expat@2.3.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-28T04_14_47_482Z-debug.log
The command '/bin/sh -c cd /app   && npm install --production' returned a non-zero code: 1

**Comment by peterswimm** [comment]
Where are you building this? Is this on a machine that has python installed?

**Comment by peterswimm** [comment]
I found a fix for this here, fixing your path to python in node should help:
https://www.npmjs.com/package/node-gyp

**Comment by v1adko** [comment]
I was having the same issue after upgrading to 0.6.11. We're using CircleCI which builds our app's Docker image, and since we're using alpine, there is no python installed, thus this error.

Downgrading to 0.6.9 fixes the issue.
The dependency in question (node-expat) is a dependency of a dependency of ...... of  `simple-xmpp` from what I can tell upon glancing over the yarn.lock, but I may be wrong.

It is absent from the dependency tree (yarn.lock) completely on version 0.6.9, so I guess that's why it works.

I suggest looking over the dependencies introduced/updated since 0.6.9, track it down and think of a way to avoid it because in my opinion, having a breaking dependency on Python is not a good thing for the module.

**Comment by peterswimm** [comment]
This is actually related to the new cisco-jabber support. I spoke with the Cisco Jabber team and they are going to update/remove the offending repository. If you absolutely have to use .6.9 (Check the changelog) you can edit the package.json to exclude added the added package requirements to avoid the error when building your image.

We are close to announcing changes to Botkit that will reduce the "add every possible supported platform" headaches by making platforms work more like a middleware plugin. More details to follow, as well as a proposed timeline and a call for comments about the proposals.
