### ISSUE TITLE
optin not working with checkbox messanger plugin 

### ISSUE THREAD

**Issue by gilLionKing** [howdyai/botkit#1268]
Hi im implementing the checkbox plugin on my website and when the user optsin im receiving the event
throught the bot kit
im using the below code to trigger the opt in taking the user_ref as the id which will be used to send a message
   else if (facebook_message.optin ||
                        (facebook_message.postback && facebook_message.postback.payload === 'optin')) {
                        message = {
                            optin: facebook_message.optin,
                            user: facebook_message.optin.user_ref,
                            channel: facebook_message.optin.user_ref,
                            timestamp: facebook_message.timestamp
                        }
                        controller.trigger('facebook_optin', [botk, message])
}
but when i try to send a message with 
 controller.on('facebook_optin', function(botk, message) {    
   botk.reply(message, 'Welcome to my app!');
    });
im getting debug: API ERROR { message: '(#100) No matching user found',
  type: 'OAuthException',
  code: 100,
  error_subcode: 2018001,
  fbtrace_id: 'DZBD+d9AsP4' }

what can i do to correct this ? its probably an issue with the reply not using the user_ref id

**Comment by julianusti** [comment]
@gilLionKing that's interesting, I'm also subscribing to `facebook_optin`, but not getting anything.

`controller.trigger('facebook_optin', [botk, message])` - what this line means?

**Comment by peterswimm** [comment]
Is this still a problem?

**Comment by julianusti** [comment]
@peterswimm yes. I still not getting events to my webhook.

**Comment by peterswimm** [comment]
The primary thing to check is your developer portal settings, and if your developer environment is reaching the outside internet.

**Comment by julianusti** [comment]
I'm running two apps. Two of them using localtunnel (Frontend and the bot). Subdomain for frontend is whitelisted, checkbox is visible on in the web app.
