### ISSUE TITLE
OAuth redirect to team's Slack URL

### ISSUE THREAD

**Issue by elahmo** [howdyai/botkit#127]
I would be nice to add support for redirecting, in addition to the `redirect_uri`, to the Slack of the team that added the bot via button.

I was checking the `createOauthEndpoints()` method implementation and was thinking adding a parameter and checking was it there and, if true, redirect to team's URL, but it appears the team's slack URL is not available immediately to that call, and the contents of `req` pass to that method have no additional data that could be used.

**Comment by benbrown** [comment]
If you are still interested in this, do it and send us a pull request!

**Comment by peterswimm** [comment]
Closing the issue for now, If you have any updates, please feel free to reopen!
