### ISSUE TITLE
Send broadcast message missing notification_type and tag

### ISSUE THREAD

**Issue by OmranAbazid** [howdyai/botkit#1271]
The API in facebook docs look like this:
![screen shot 2018-03-04 at 2 20 16 pm](https://user-images.githubusercontent.com/9063094/36944958-376f34fa-1fb7-11e8-868b-535e70094d24.png)

Where the function in facebook.js only include the creative_message_id

![screen shot 2018-03-04 at 2 19 08 pm](https://user-images.githubusercontent.com/9063094/36944949-0ef155c6-1fb7-11e8-9471-9a739ee9e221.png)

I can work on it if needed but we first have to agree on how the pass the missing two parameters.
I think we should convert the first param to an object.

**Comment by ouadie-lahdioui** [comment]
Hello,

You're right ! we should include a two new parameters while sending a broadcast message, this API is no more in beta stage as FB published last week, ````notification_type ```` and ````tag ```` attributes are introduced by this new version.

> How to pass the new parameters ? 

Convert ````message_creative_id ```` to a JSON object is a smart idea, but be careful, maybe a lot of Botkit developers send broadcast messages based on the actual method signature :

````
controller.api.broadcast.send('<STRING_CREATIVE_ID>', <CUSTOM_LABEL>, function (err, body) {
    // Your awesome code here
});
````

To not introduce breaking changes, i think we should rename the parameter ````message_creative_id ```` to ````message_creative ```` and test inside send method if the developer gives us a String or an Object  :

````
if (typeof(message_creative) === 'string') {
     // Put the passed parameter into body.message_creative_id
} else {
     // Clone the passed parameter into body 
}
````

With this approach we'll not introduce breaking changes and we'll give the possibility of sending the new parameters maybe other ones tomorrow !

WDYT ?

**Comment by OmranAbazid** [comment]
Your solution looks good. I created a pull request to add the new args #1280
