### ISSUE TITLE
How to build a connector

### ISSUE THREAD

**Issue by karthikb351** [howdyai/botkit#1272]
Currently there is no documentation on how to build a connector for a new platform.
If not full-fledged documentation, an example connector would be useful to use as reference.

**Comment by peterswimm** [comment]
What platform are you looking to connect? I would suggest looking at one of the existing integrations (for example the facebook integration) for a guide on how you might integrate another connection.

**Comment by julianusti** [comment]
@peterswimm @karthikb351 I believe that a basic documentation would be nice to have anyways as an entry point so to say.

**Comment by peterswimm** [comment]
Absolutely! We’ve been busy creating integrations, but as part of upcoming documentation revision plans we have things like this down as a priority.

**Comment by benbrown** [comment]
I created an example connector and started documenting the process. Check it out!

https://botkit.ai/docs/howto/build_connector.html
