### ISSUE TITLE
replyPublicDelayed encodes special characters.

### ISSUE THREAD

**Issue by moriczgergo** [howdyai/botkit#1274]
When I try to post a code snippet with replyPublicDelayed, it gets encoded. (`(` turns into `%28`, `)` into `%29`, etc.)

**Comment by moriczgergo** [comment]
I may be able to do a PR today w/ a fix

**Comment by peterswimm** [comment]
@moriczgergo it looks like you solved your issue in your other repo, is that the case?

**Comment by peterswimm** [comment]
Adding the bug tag, if anyone wants to take a stab at a Pull request to resolve, chime in!
