### ISSUE TITLE
"help" plugin similar to Hubot's hubot-help module?

### ISSUE THREAD

**Issue by jefftougas** [howdyai/botkit#1275]
Is there some plugin or mechanism available within the botkit community for getting botkit to print out available command syntax documentation in response to "help" messages? I've used https://github.com/hubotio/hubot-help with hubot in the past, but my searching for a botkit equivalent didn't yield anything.

I acknowledge that building some equivalent help registry would be pretty easy without an external plugin - I was just wondering if there was a packaged solution for this problem already.

**Comment by peterswimm** [comment]
I am not aware of a publically available method, but you can do this in Botkit Studio using the controller.studio.getScripts() function:
https://github.com/howdyai/botkit/blob/master/docs/readme-studio.md#controllerstudiogetscripts

The alternative to using studio is similar to what you are getting at, using a middleware handler to return responses based on "help" and a block of text or menu of your available commands "help COMMAND" type syntax.

**Comment by jefftougas** [comment]
Cool, thanks. I can work with that.
