### ISSUE TITLE
Is it good move to use botkit for general chatbot?

### ISSUE THREAD

**Issue by nickppbd** [howdyai/botkit#1277]
Hi, I'm new here.

I used AIML before and I think it's pretty good for limited conversation.

But My boss wanted more general chatbot(something like conversation between friends I mean A.I.).

I researched and found out that it's beyond my ability(especially at deep learning like CNN RNN )

Also, I did some example codes in API.ai(https://dialogflow.com) and I think it's good at NLP and expanding to many other well-known platforms easily, But It's not free.

So, I searched 'chatbot' at github.com I found botkit.

I read some docs and I have questions.

Is it good for general chatbot? 
Docs always mentions about 'SLACK'.
Is it possible to build a botkit chatbot based on GET OR POST REQUEST for WEB, ANDROID?

I'm not familiar with RegExp, But botkit use RegExp for handling user input.
So, is it hard to think that botkit support NLP(I mean like API.ai)?

I found https://github.com/gunthercox/ChatterBot (based on a machine learning) and will use it for making NLP-like function.

Please, Advise me.

**Comment by peterswimm** [comment]
You are getting a very biased opinion, but Botkit is great!
For the web/android I'd suggest getting started with Botkit Anywhere:
https://github.com/howdyai/botkit-starter-web

Botkit also supports a variety of NLP providers:
https://github.com/howdyai/botkit/blob/master/docs/readme-middlewares.md#natural-language-processing-1

Lastly, if you need help getting started I'd suggest joining our public slack to search any questions you might have, and to ask for help:
https://community.botkit.ai/
