### ISSUE TITLE
quick reply with content type email or phone returns error

### ISSUE THREAD

**Issue by gilLionKing** [howdyai/botkit#1279]
hi im trying to use the quick reply for email or phone in the way below
    convo.addQuestion({
                        "text": "Here is a quick reply!",
                        quick_replies: [
                            {
                                content_type: 'user_email',
                            },
                            {
                                content_type: 'user_phone_number',
                            },
                        ],
                    }
and getting this error
nfo: An error occurred while sending a message:  { message: '(#100) The parameter message[quick_replies][0][content_type] is required',
  type: 'OAuthException',
  code: 100,
  fbtrace_id: 'DqOcSLT3A8I' }

if i use content types like text and location they are working without any issue

**Comment by gilLionKing** [comment]
anyone ? its more a bug then help wanted (:

**Comment by gilLionKing** [comment]
@peterswimm  i looked deeper into it and found this piece of code
if (item.content_type === 'text' || !item.content_type) {
                        quick_reply = {
                            content_type: 'text',
                            title: titleLimit(item.title),
                            payload: item.payload,
                            image_url: item.image_url,
                        };
                    } else if (item.content_type === 'location') {
                        quick_reply = {
                            content_type: 'location'
                        };
                    } else {
                        // Future quick replies types
                    }

a really easy fix would be to add the 2 types of quick replies under the else clause
content_type: 'user_email',
content_type: 'user_phone_number',

**Comment by peterswimm** [comment]
@gilLionKing feel free to submit a PR request if you feel that the current code could be refined.

**Comment by ouadie-lahdioui** [comment]
Here's the fix #1301
