### ISSUE TITLE
Issue with Deploying Watson Chatbot on Facebook Messenger: Problem with Webhook Verify Token

### ISSUE THREAD

**Issue by chandril-ghosh** [howdyai/botkit#1282]
I developed a chatbot on IBM Watson. Now I am unable to deploy it on facebook messenger. I am new to coding. Have already tried youtube videos and articles (mentioned below). Did not worked. Seeking Guidance! 

The flow goes like this: Watson Conversation Deployment Options>Publish with Botkit>Multi-channel bot> facebook messenger (https://github.com/watson-developer-cloud/botkit-middleware/tree/master/examples/multi-bot)> I was able to set-up localtunnel locally (got the webhook url). 

ISSUE 1) On trying to add (https://https://048bfce4.ngrok.io/facebook/receive) as Facebook Messenger's webhook it DID NOT ACCEPTED as a valid url on the facebook web-page.

ISSUE 2) The same page of github also assumes: "the verify token (created by you)" without stating how to create the webhook verify token. I also found it was written <Define your own "verify token" - this is a string that you control that Facebook will use to verify your web hook endpoint.> Again I do not know how to do it. 

Other than that, I have tried to resolve the issue from the links mentioned below, however, so far I was not able to deploy my chatbot. I might be making mistake somewhere. Please the find the attached screenshots of my attempt:
![code1](https://user-images.githubusercontent.com/29620882/37222361-bf1b110a-23f2-11e8-8c16-4714cce198d5.PNG)
![code2](https://user-images.githubusercontent.com/29620882/37222365-c0588dcc-23f2-11e8-8c57-5c60c9bd68f3.PNG)
![code3](https://user-images.githubusercontent.com/29620882/37222380-ce50f4dc-23f2-11e8-8d36-adea748ceff2.PNG)
![code4](https://user-images.githubusercontent.com/29620882/37222384-d10bb6b2-23f2-11e8-978b-16c19417f3f8.PNG)

LINKS I HAVE REFERRED TO: 

https://girliemac.com/blog/2017/01/06/facebook-apiai-bot-nodejs/

https://developers.facebook.com/docs/messenger-platform/getting-started/webhook-setup

https://www.youtube.com/watch?v=Z58O5xU57WA

https://www.youtube.com/watch?v=bUwiKFTvmDQ

**Comment by peterswimm** [comment]
1: This url has to be reachable from the outside internet, you should make sure ngrok is up and running.
2: This is some value that you make up. It can be anything you want.

If you keep running into trouble, I would post on the Watson github, but all the above sounds like development environment issues. You might try using glitch to get you started if you keep running into trouble.

**Comment by chandril-ghosh** [comment]
Thanks for your kind response! 

1. ngrok is up and running:
![code5](https://user-images.githubusercontent.com/29620882/37222733-3040ece6-23f4-11e8-9196-f6681532ec14.PNG)
ERROR DISPLAY: 
![image](https://user-images.githubusercontent.com/29620882/37222743-3638d014-23f4-11e8-9f3f-91a6f20a6bd7.png)

2. "This is some value that you make up": Yes, but this value has to be implanted into the codes, right? This is not coming right for me and I am stuck at this. Could you please guide me on this?
For example: 
![screenshot-2018-3-9 creating a simple facebook messenger ai bot with api ai in node js 1](https://user-images.githubusercontent.com/29620882/37222890-ae9efb3c-23f4-11e8-878f-ef5046727e0e.png)

For example, for the codes to I was referring to create the webhook verify token from:
https://girliemac.com/blog/2017/01/06/facebook-apiai-bot-nodejs/
Like I sent you the screenshots, its showing error.

I will try Glitch. Thanks!

**Comment by peterswimm** [comment]
1. You might try restarting it, facebook isnt seeing your application.
2. You can either specify this in your command line arguments, or via a ENV file like in our glitch starter kits:
https://github.com/howdyai/botkit-starter-facebook
