### ISSUE TITLE
Facebook replyWithTyping, allow to override typing delay.

### ISSUE THREAD

**Issue by julianusti** [howdyai/botkit#1286]
Currently, typing delay of `replyWithTyping` is calculated as:
`typingLength = Math.min(Math.floor(textLength / (avgCPM / 60)) * 1000, 5000);`

_Proposal:_ allow to override `typingLength` bypassing `delay` parameter to `replyWithTyping` function.

Any objections? If not, I can contribute.

**Comment by peterswimm** [comment]
@ouadie-lahdioui opinions?

**Comment by ouadie-lahdioui** [comment]
Hello, @julianusti why do you want to override typingLength delay ? can you share your use cas ?

**Comment by julianusti** [comment]
@ouadie-lahdioui Sure, we'd like to speed up on "big messages" and do not emulate real user typing.

**Comment by ouadie-lahdioui** [comment]
Let's go man !

What do you think of adding `````.typingDelay````` attribute to the `````resp````` object to prevent breaking changes.

````
if (resp.typingDelay) {
  typingLength = resp.typingDelay;
} else {
 // What we already do today
}
````
So the new API will be : ````bot.replyWithTyping(message, {text:'Hello there, my friend!', typingDelay: 500});````

**Comment by julianusti** [comment]
@ouadie-lahdioui should we also keep API consistent as it was mentioned [here](https://github.com/howdyai/botkit/issues/1291#issuecomment-374261143)? #1291

**Comment by ouadie-lahdioui** [comment]
LGTM 👍
