### ISSUE TITLE
convo messages with delay

### ISSUE THREAD

**Issue by gilLionKing** [howdyai/botkit#1291]
hi is there a convient way to say things or ask questions in a delay ? 
for example 
  convo.say('hello...') i want to wait 5 seconds until it sends this to the user 
  convo.say("hi again")i want to wait 5 minutes until it sends this to the user
  convo.say("last hi") i want this to be sent immediatly after the previous messages has been sent,

thanks.

**Comment by julianusti** [comment]
@gilLionKing As per my knowladge BotKit doesn't supports this under the hood, but what you can actually do is to monkey patch `say()` and `ask()` functions and have `setTimeout` inside.

An example would be something like this (didn't tested it, but you should get an idea):

```
var oldSay = convo.say;
convo.say = function(text, cb, delay) {
    if (typeof(delay) == 'number' && delay > 0) {
        setTimeout(function() {
            oldSay.call(this, text, cb);
        }, delay)
    } else {
        oldSay.call(this, text, cb);
    }
};
```

**Comment by julianusti** [comment]
This issue is also related to #1286

**Comment by gilLionKing** [comment]
hi thanks . i tried this style the examle doesnt work since this is the timeout context when setting timeout
and it cant add a message so i tried passing a convo instead of this 
  oldSay.call(convo, text, cb);
this has been working sporadically. sometimes the message shows up and sometimes doesn't.
what can cause this  ? also just setting a timeout on a say like this : 
doesn't work for some reason.

**Comment by julianusti** [comment]
@gilLionKing I've updated my example a little bit, i've chek it out and and it's not that easier as I thought. Let me think a bit. I think you have to do some throtteling...

**Comment by julianusti** [comment]
@gilLionKing ok, man, sorry for confusing, it's not possible actually :) because `convo.say()` is not directly sending message but adds it to the sort of task queue wich triggers every `tick`. This `tick` is an internal BotKit clock which ticks at a regular pace, by default every `1500ms`.

You can change this value by calling `setTickDelay()` function. Ex. `controller.setTickDelay(4000);`

Here is a [documentation](https://github.com/howdyai/botkit/blob/e196bfa1b89657d36662dffe81f3b9672fb257a2/docs/readme.md#changing-the-speed-of-botkits-internal-tick) for `setTickDelay()`.

**Comment by julianusti** [comment]
@gilLionKing I would pay attention to this:
```
The 1.5 second delay between sending messages serves two purposes: first, it creates a small delay between outgoing messages, giving some small simulation of typing time. Second, it helps to keep bots API use within a reasonable limit in order to prevent being rate limited by the message platform.
```

**Comment by gilLionKing** [comment]
Hi thanks man but first of all i tried using the tick before like that 
module.exports = function(controller,messagingApi) {
    controller.setTickDelay(6000);

and it has no affect, messages are being sent with a second difference. 
second how would you use it in my example ? just change it on the fly for every message ? would that work ?

**Comment by julianusti** [comment]
I don't think it is a good idea to change it on the fly though. As far as I understood, you can do it once and send messages with the same pace `1500ms` || `6000ms`.

**Comment by julianusti** [comment]
The alternative way to go, would be `replyWithTyping()` function, then it would delay message based on the length of the text.

**Comment by ouadie-lahdioui** [comment]
Hello,

You can

**Comment by ouadie-lahdioui** [comment]
Hello,

You can do that like that :

`````
setTimeout(() => {
    bot.reply(message, 'hello...');
}, 5000);

setTimeout(() => {
    // Start a new conversation here
    convo.say('hi again');
    convo.say("last hi") 
}, 300000);
`````

WDYT ?

**Comment by julianusti** [comment]
@ouadie-lahdioui I think this approach wouldn't be deterministic since `convo.say()` has its own clock when it sends messages (every `1500ms` by default). So, per my understanding, it's kind of hack, which we already discussed above. Or am I missing something? 😃

**Comment by benbrown** [comment]
You can specify a custom delay on each message in a conversation.

```
convo.say({text: 'hello', delay: 3000});
```

**Comment by benbrown** [comment]
I added a note about this to the docs!

https://botkit.ai/docs/core.html#changing-the-pace-of-the-conversation-with-custom-per-message-delay

**Comment by ouadie-lahdioui** [comment]
@julianusti you didn't miss anything 👍

**Comment by peterswimm** [comment]
Closing this as answered

**Comment by akhanukov** [comment]
Hey @benbrown , just to confirm, that delay parameter doesn't work with addMessage and addQuestion, correct, or possibly not with Quick Links and/or attachments? Or is something else of mine broken? :)
