### ISSUE TITLE
[Workplace/(~Facebook)] Persistent Menu Call is dependent on Get Started

### ISSUE THREAD

**Issue by brh55** [howdyai/botkit#1292]
So occasionally I've run into this issue where the bot is initially deployed, and I can't update the `messenger_profile.menu` because the `messenger_profile.get_started` call hasn't successfully been called due to it being initiated asynchronously.

![image](https://user-images.githubusercontent.com/6020066/37616677-ef5ed23e-2b6d-11e8-8dcf-cbb6ba42e277.png)

Any thoughts of allowing a callback for the `get_started`: `get_started (payload, cb)`. Otherwise, I can call `get_get_started` before proceeding with the `menu` call.

Also, I'm running to this issue on Workplace, so not sure if this pertains to Facebook Pages.

**Comment by ouadie-lahdioui** [comment]
Hello,

I worked on promisify all messenger profile API #1300, you just need to wait for the next version.

Thank you for sharing your case :smile:
