### ISSUE TITLE
Accessing Cisco Spark APIs

### ISSUE THREAD

**Issue by jeremywillans** [howdyai/botkit#1294]
Hi All, 

Firstly I'm new to Bot Building so this might be more of a novice mistake!

Botkit v0.6.12

Within Cisco Spark, I am trying to retrieve the current Room Name to use in a Botkit Response.

Based on the final comment in (https://github.com/howdyai/botkit/issues/7) the APIs should be directly accessible, an output of bot.botkit.api shows the objects (bot.api is undefined), but they appear to be empty.

Should this work or is this not available for Cisco Spark or is there another way of accessing the APIs?

Cheers,
Jeremy

**console.log(bot.botkit.api)**
`
{ loaded: true,
  sessionId: 'XXXXXXXXXXX',
  ready: true,
  canAuthorize: true,
  canRefresh: false,
  isAuthorizing: false,
  isAuthenticating: false,
  internal:
   { device:
      { services: {},
        serviceHostMap: [Object],
        features: [Object],
        serviceCatalog: [] },
     feature: {},
     metrics:
      { batcher: {},
        clientMetricsBatcher: {},
        callDiagnosticEventsBatcher: {} },
     mercury: {},
     locus: {} },
  credentials:
   { supertoken:
      { access_token: 'XXXXXXXXXXX',
        token_type: 'Bearer' },
     userTokens: [] },
  logger: {},
  authorization: {},
  people: { batcher: {} },
  phone: { emittedCalls: [] },
  messages: {},
  memberships: {},
  rooms: {},
  teams: {},
  teamMemberships: {},
  webhooks: {} }
`

**Comment by ObjectIsAdvantag** [comment]
@jeremywillans I am surprised this is returning undefined since `bot.botkit.api` does work for me.
May you check this sample:
https://github.com/CiscoDevNet/botkit-webex-samples/blob/master/roomid-phantom.js#L94

**Comment by jeremywillans** [comment]
Thanks Steve - yes after finding that example i got it working successfully. Cheers for the follow up !
