### ISSUE TITLE
Bot is not receiving location from facebook

### ISSUE THREAD

**Issue by MagSag** [howdyai/botkit#1295]
I am sending location from the quick reply send location button, it is not triggering any event neither **message_received** nor **facebook_postback**.
BOTKIT 0.6.8

**Comment by ouadie-lahdioui** [comment]
Can you share some code ?

**Comment by MagSag** [comment]
Which part of code exactly? the one asking for location: 

`{"text":"Where do you stay?","quick_replies":[{ "content_type": "location","payload": `ADD_USER_30_67_LOCATION_`}]};`

       For the one receiving, I put in postback and message_received respectively: 
```
console.log("postback");

console.log("Message received");
```

and non of these is being displayed to the console.

**Comment by ouadie-lahdioui** [comment]
I juste maked a test in each 0.6.8 version and the latest one, and it works as expected !

here's my example : 

````
controller.hears('location', 'message_received',  (bot, message) => {
    bot.reply(message, {
        "text": "Where do you stay?",
        "quick_replies": [{
            "content_type": "location",
            "payload": "ADD_USER_30_67_LOCATION_"
        }]
    });
});

controller.on('message_received', (bot, message) => {
    let location = message.attachments[0];
    bot.reply(message, `Open this link in your browser : ${location.url}`);
});
````

let me know if you still have issue.

**Comment by MagSag** [comment]
I really don't get where the problem is, if it facebook which is not send or the bot which is not receiving, It is still not working.

**Comment by ouadie-lahdioui** [comment]
In this case ensure that your webhook works fine.

**Comment by MagSag** [comment]
> In this case ensure that your webhook works fine. 
Is there any otherway a part verifying and sending message to the bot? what or where should I check else?

**Comment by ouadie-lahdioui** [comment]
Hi @MagSag you still have the problem ?
You can for example check if your webhook works fine by making a curl call.
