### ISSUE TITLE
Support for WhatsApp

### ISSUE THREAD

**Issue by rogerweb** [howdyai/botkit#1297]
As of March 2018 the WhatsApp API is not publicly available yet, being available to a few selected companies only. There is the expectation that Facebook will announce its GA on May 1st/2nd during their F8 developer conference.

This issue is to capture the community interest in having botkit supporting WhatsApp as a new channel.

**Comment by MagSag** [comment]
Botkit being first to put the head in  will be super wonderfull. Let hope they are going to make it public...Facebook's Cambridge Analytica nightmare has made me worry a little.

**Comment by jphillips-modexe** [comment]
Yes, would definitely be interested in this.

**Comment by MagSag** [comment]
Hey guys this API is avaible publically now [here](https://developers.facebook.com/docs/whatsapp/getting-started)

**Comment by menbatisiunissart** [comment]
Hi guys, is anyone actively working on WhatsApp api for botkit ? Just dont want to re-invent the wheel is someone's already have some early version

**Comment by edrich** [comment]
Also interested to use botkit with WhatsApp.

**Comment by hasan-upinion** [comment]
Any update on this issue??

**Comment by batamar** [comment]
Any update ?

**Comment by juanpablo64** [comment]
updates?????????

**Comment by MatheusRV** [comment]
no news?

**Comment by peterswimm** [comment]
No news!

**Comment by juanpablo64** [comment]
ah, bummer. Thank you for keeping us updated!

**Comment by benbrown** [comment]
I believe the best way to get to WhatsApp right now is via Twilio.  This adapter should work:

https://github.com/BotBuilderCommunity/botbuilder-community-js/blob/master/libraries/botbuilder-adapter-twilio-whatsapp/README.md
