### ISSUE TITLE
Fix test coverage thresholds to one that we have right now.

### ISSUE THREAD

**Issue by julianusti** [howdyai/botkit#1304]
I believe it's a good timing to start improve on unit tests.

I would suggest fixing code coverage with existing thresholds, such as:
- Stmts:  13.42 
- Branch: 6.56
- Funcs 9.42
- Lines 13.45

So, we don't get worse than that and with each new line of code, we force ppl to write unit tests.
Do we have any plans to improve unit test overall, if it's on the roadmap can anyone share it here?

//cc @peterswimm

**Comment by peterswimm** [comment]
https://github.com/howdyai/botkit/pull/857
