### ISSUE TITLE
TypeError: Cannot set property 'channel' of undefined

### ISSUE THREAD

**Issue by ca42rico** [howdyai/botkit#1307]
Using botkit: 0.6.7

Hi, I have an asynchronous function (that returns a promise) that generates a list of messages to be sent sequentially:
	
```
var messages = await someAsyncFunction(parameters);
bot.startConversation(message, async (err, convo) => {
   for (let count = -1; count < messages.length && count < 9; count++) {
      convo.say(messages[count]);
   }
});
```
	
It doesn't work, and returns: "TypeError: can not set the 'channel' property of undefined".

What can I do?
Thanks in advance

**Comment by leahzxxz** [comment]
I'm not sure what the context is, but normally `await` only works within a wrapping async function.

**Comment by ca42rico** [comment]
```
controller.hears("(.*)", "message_received", (bot, message) => {
	...
	sendMessages(bot, message) {
	...
}

async function sendMessages(bot, message) {
	var parameter = anotherSomeFunction();
	if (parameter) {
	    let response = message.watsonData;
      
	    try{      
			var messages = await someFunction(response, parameter); //returns a promise
			bot.startConversation(message, (err, convo) => {
				for (let count = 0; count < messages.length && count < 10; count++) {
					convo.say(messages[count]);
				}
		  	});
	   } catch (e) { ... }
   } else { ... }
}
```
the problem is just using bot.startConversation, because if instead I use
```
...
try{      
	var messages = await someFunction(parameter); //returns a promise
	for (let count = 0; count < messages.length && count < 10; count++) {
		bot.reply(message, messages[count]);
	}
}
...
```
there aren't problems

**Comment by jschnurr** [comment]
@ca42rico in your original question, you had this line:
```javascript
for (let count = -1; count < messages.length && count < 9; count++) {
```
`messages` at index  `-1` does not exist, and returns `undefined`.  When that `undefined` was processed by `CoreBot`, it threw when trying to read expected properties from the message object.

In your revision later, you changed it to `0`, which should work.  Not sure why this case would be broken.

In any case, here is a complete, working example.  This uses Slack and looks for `direct_message` instead of `message_received`, but it should behave the same.  I've also simplified the `for` loop to avoid index numbers altogether.

```javascript
function someFunction() {
    return Promise.resolve(['the quick', 'brown fox', 'jumps over', 'the lazy dog']);
}

slackController.hears('(.*)', 'direct_message', (bot, message) => {
    sendMessages(bot, message);
});

async function sendMessages(bot, message) {
    var messages = await someFunction(); // returns a promise

    bot.startConversation(message, (err, convo) => {
        for (let msg of messages) {
            convo.say(msg);
        }
    });
}
```

Let me know if it works.

**Comment by ca42rico** [comment]
Thank you! So it was an `undefined` problem.

O.T. when I use `bot.startConversation`, the bot receives but not process (not enter in `controller.hear` or `controller.on`) all the messages it receives (from Facebook) (in fact it receives all the messages but some are not captured by `controller.hear` or `controller.on`).
I use botkit-middleware-watson, and it does not happen when I use `bot.reply instead` (all messages arrive and are answered). 
I tried either with 
`controller.on("message_received", (bot, message) => {});`  and  `controller.hears(".*)","message_received", (bot, message) => {});` 

Could it be a problem with `bot.startConversation`?
Thanks again

**Comment by jschnurr** [comment]
The events are documented [here](https://github.com/howdyai/botkit/blob/master/docs/readme.md#responding-to-events).

For the second issue, suggest you open a new issue, and provide your code and logs that illustrate the problem.

**Comment by ca42rico** [comment]
Thanks
