### ISSUE TITLE
[SparkBot] Duplicate messages on certain skills

### ISSUE THREAD

**Issue by mlanci** [howdyai/botkit#1308]
I've installed this out of the box and have not messed with any code or added any of my own skills.. I'm testing the current ones that come with the install to better understand the code.

However when I do certain things like @BotName hello or tasks it gives me two responses instead of one.. However when I do things like uptime or color -- it only gives me one response.

I know there are a couple of issues opened around this already but I haven't found them to be of much help and it says it's fixed in a later version however i'm current and it seems it's not fixed. Any ideas?

**Comment by peterswimm** [comment]
Have you connected this to botkit studio by any chance? Where is your bot app hosted?

**Comment by mlanci** [comment]
I'm going to take another wack at this tonight however I don't think I was using botkit studio because I was confused on how it works with the studio/glitch. I'm still not sure how it works.. the code is hosted on glitch? So what do I use as my public URL on the webhook?

**Comment by peterswimm** [comment]
If you chose glitch it will be hosted on there. In Spark, users will look for your bot by its spark user name, but the url will be something like

https://APPNAME.glitch.me/

You can host anywhere you'd like, as long as you have a secure endpoint.
