### ISSUE TITLE
Controller.Hears for multiple arguments to default

### ISSUE THREAD

**Issue by vasujain** [howdyai/botkit#1309]
Hi 

I am using something like : 
`controller.hears(['t (.*) (.*)', 'tweet (.*) (.*)', 'tweets (.*) (.*)']`  in index.js.

This behaves well if I pass 2 arguments from the bot, however, I want to have a default value set if these parameters are not sent. Can someone suggest how that can be done?

using https://github.com/howdyai/botkit/blob/master/lib/CoreBot.js v 0.0.5

**Comment by peterswimm** [comment]
Per your thread on slack, @benbrown responded with
https://dev4slack.slack.com/archives/C0AV5N8NA/p1522615900000073

Put a ? After the optional parameter pattern

**Comment by vasujain** [comment]
Working solution as discussed on Slack:

`controller.hears(['tweet (.*) (.*)','tweet (.*)','tweet'], 'direct_message', function(bot, message) {
        bot.reply(message,JSON.stringify(message.match));
    });`
