### ISSUE TITLE
Missing messenger_extensions property in Botkit Studio button template

### ISSUE THREAD

**Issue by teawaterwire** [howdyai/botkit#1310]
As per facebook's documentation: https://developers.facebook.com/docs/messenger-platform/webview
> If your bot uses the Messenger Extensions described in this section, remember to set the messenger_extensions parameter to true in the menu item or button you are invoking it from!

It's currently impossible to add such parameter in the button template in Botkit Studio, and the webview cannot load the messenger extension sdk. 

Thanks!

**Comment by peterswimm** [comment]
You should be to do this now with customer fields, and custom code in your bot.
