### ISSUE TITLE
Feature to start conversations with users without being messaged first

### ISSUE THREAD

**Issue by dmccrevan** [howdyai/botkit#1314]
A use case for a chat bot could be to message a user first based on some event being triggered. Example could be trivia questions would be sent out to a list of users who signed up for the trivia game. 

As of right now the only way to do this I have found is through this:  #89 

Could there be a more elegant way to do this?

**Comment by peterswimm** [comment]
Also take a look at https://github.com/howdyai/botkit/issues/422
