### ISSUE TITLE
Is there a way to get the user's response attachment?

### ISSUE THREAD

**Issue by yoavanaki** [howdyai/botkit#132]
Hi everyone,

First of all - thanks so much for Botkit! It's awesome.
I'm wondering if there's a way to grab the URL of an attachment in the user's response to my convo.ask query. So far I've only been able to get the text reply using response.text.

Thanks a bunch,
Yoav

**Comment by benbrown** [comment]
Yes! This was missing due to a bug, but has now been added back in.
