### ISSUE TITLE
OAuth Error: Invalid client_id parameter

### ISSUE THREAD

**Issue by neerjad** [howdyai/botkit#1321]
I followed this tutorial https://github.com/howdyai/botkit/blob/master/docs/provisioning/slack-events-api.md#3-configure-oauth and created a Botkit slack bot as well as a bot user on slack. After following all the steps, while accessing https://bot_url/, on clicking the 'Add to Slack' button, I am getting an invalid client_id parameter error. Any solutions?

**Comment by jayneil** [comment]
I am having the same error. How did you resolve it?

**Comment by jayneil** [comment]
So, I fixed the problem by following the documentation and watching the video by @benbrown on this page:

https://botkit.ai/docs/provisioning/slack-events-api.html#3-configure-oauth
