### ISSUE TITLE
Error when npm install botkit

### ISSUE THREAD

**Issue by acarlstein** [howdyai/botkit#1325]
Greetings,

I am getting an error when trying to install botkit with npm:
```
npm ERR! code E404
npm ERR! 404 Not Found: @ciscospark/plugin-people@1.30.1
```

I think it can be fixed by register the right url in the .npmrc file; however, I don't know what url to use.

Any takers?

P/D:
Should the plugins such as ciscospark being separated from the actual BotKit? 
In other words, should BotKit have like a "basic" package and then provide plugins such as ciscospark as packaged to add to BotKit?

**Comment by peterswimm** [comment]
I just tried doing this now and didn't see the problem, are you still seeing it?

We have some internal plans on making Botkit core a separate object from the various platform integrations, allowing people to install only what they need. We will be announcing the roadmap for this and soliciting feedback soon.

**Comment by jloveric** [comment]
I had the same problem with ciscospark.  I only resolved it by removing my .npmrc, though in the future I'll need a better solution.
