### ISSUE TITLE
Can not send quick reply using bot say

### ISSUE THREAD

**Issue by sherryt400** [howdyai/botkit#1328]
how to send quick reply using `bot.say()`?? 
ref [https://botkit.ai/docs/core.html#botsay](url)
documentation is incomplete

**Comment by peterswimm** [comment]
What platform are you trying to create a quick reply for? That will largely dictate what is possible with the generic example you are linking to.

**Comment by sherryt400** [comment]
for messeger

**Comment by ouadie-lahdioui** [comment]
Take a look at the facebook example [here](https://github.com/howdyai/botkit/blob/8663cb05d0fa12e893dd72477fb703322fb01ad8/examples/facebook_bot.js#L232) and use say instead of reply.

**Comment by sherryt400** [comment]
thanks it worked

**Comment by sarigasurendranms** [comment]
controller.hears(['show details'], 'message_received', function (bot, message) {
    var questionText = 'show details'
    var replies = [
      {
        "content_type":"text",
        "title":'go back',
        "payload":'go back'
      },
      {
        "content_type":"text",
        "title":'main menu',
        "payload":'menu'
      },
      {
        "content_type":"text",
        "title":'order',
        "payload":'order'
      }
    ]
    var quickReplyAttachment = {
      'text': questionText,
      'quick_replies': replies
    }
    bot.reply(message, quickReplyAttachment)
  });

I am getting only the text show details .the quick replies are not displayed.can anyone help me?
