### ISSUE TITLE
botkit for monitoring ?

### ISSUE THREAD

**Issue by essaghirsalhi** [howdyai/botkit#1329]
hello guys,
our project is about security, we need to build a website and integrate botkit for monitoring.
for example if someone changed his password, botkit have to alert the user if he is sure or he is the one changing the password, like a verification step.
hope to get some answers from you.
thanks, good day.

**Comment by peterswimm** [comment]
The best method is to setup what monitoring solution you end up using to work with your Botkit instance using middlewares:
https://botkit.ai/docs/middleware.html

I see that you are already on our community slack, I'd suggest you keep asking questions there if you run into trouble.
