### ISSUE TITLE
Acknowledge delayed response

### ISSUE THREAD

**Issue by jonathanwiesel** [howdyai/botkit#134]
According to Slack's documentation, if your going to respond in a delayed fashion to a slash command, you should at least respond back an HTTP 200 as soon as you can to acknowledge the command received.

How this can be achieved?

**Comment by benbrown** [comment]
This happens automatically! Are you having issues?

**Comment by peterswimm** [comment]
Closing the issue for now, If you have any updates, please feel free to reopen!
