### ISSUE TITLE
Server errors in botkit are not logged

### ISSUE THREAD

**Issue by schmitzl** [howdyai/botkit#1340]
I'm using Botkit Socketbot with an Express server. However, the errors in the Botkit files, like skills, are not being logged to the console as usual. While in any other file in the server, I would see an error on the console, if I would try to import a module from a wrong path, I receive the error "Cannot find module" on server start. If the same happens in a skill file, I do not get an error, the chatbot simply does not start at all.
I tried to receive these messages enabling debug and log in bot_options as well as including a winston logger, but I still don't get error if this happens.
Is there a possibility to log this kind of errors?

**Comment by peterswimm** [comment]
The logging is extensible, so you should be able to configure the logging to include any details you need using this as a guide:
https://github.com/howdyai/botkit/blob/master/docs/logging.md

**Comment by schmitzl** [comment]
Thanks for your help. I implemented the logging according to the guide, but still nothing got logged. However, I could solve the problem by wrapping the loading of the bots and the routes into a try catch block. Now the errors that occur in the botkit files are being logged, so I'm closing the issue.

**Comment by benbrown** [comment]
Hey @schmitzl thanks for posting your solution. You should consider submitting that as a pull request!
