### ISSUE TITLE
regex denial of service vulnerability due to transient dependency on "string" package

### ISSUE THREAD

**Issue by nishch** [howdyai/botkit#1345]
Due to following dependency tree

```
├─┬ botkit@0.6.14
│ ├─┬ ciscospark@1.31.3
│ │ ├─┬ @ciscospark/plugin-phone@1.31.3
│ │ │ ├─┬ @ciscospark/internal-plugin-locus@1.31.3
│ │ │ │ ├─┬ @ciscospark/internal-plugin-mercury@1.31.3
│ │ │ │ │ ├── string@3.3.3
```
regex denial of service vulnerability has been introduced, more detail can be found here: https://snyk.io/vuln/npm:string:20170907

Please either remove the dependency on "string" altogether, or we should fix one in the "string" package directly. Either ways this might turn out to be a real issue. Although I am not using `ciscospark` it's kind of vexing, that my application is getting affected by something which I am not using.

**Comment by peterswimm** [comment]
@Stevenic fyi ^

**Comment by peterswimm** [comment]
@nishch Cisco says this should be resolve, please let us know if you are still seeing trouble.

**Comment by peterswimm** [comment]
We are planning to do a general update of the entire sparkbot functions of slack, I was wondering if you had a chance to test with the latest version.
