### ISSUE TITLE
Cisco Spark rebrand to Webex Teams

### ISSUE THREAD

**Issue by ObjectIsAdvantag** [howdyai/botkit#1346]
On April 18th, Cisco Spark to Webex Teams rebrand was [announced](https://developer.webex.com/blog/blog-details-9738.html).

Part of the documentation and code need to be updated to reflect the changes.

I propose we use this issue to arbitrate these changes.

**Comment by ObjectIsAdvantag** [comment]
Documentation
- [docs/readme](https://github.com/howdyai/botkit/blob/master/readme.md)
- [docs/readme-ciscospark.md](https://github.com/howdyai/botkit/blob/master/docs/readme-ciscospark.md)
- [botkit.ai](https://botkit.ai/docs/readme-ciscospark.html)

Code
- [CiscoSparkbot.js](https://github.com/howdyai/botkit/blob/master/lib/CiscoSparkbot.js)
- [examples/spark_bot.js](https://github.com/howdyai/botkit/blob/master/examples/spark_bot.js)

**Comment by ObjectIsAdvantag** [comment]
On the code aspects, there are a few changes we can take right now:
- SparkBot object
- ciscospark_access_token

and others we'll need to wait a few weeks/months for the Webex Teams to take arbitrations:
- require('ciscospark'): waiting for the new npm package name
- HTTP header X-Spark-Signature: waiting for the strategy
- spark-mention inside the markdown message: waiting for the strategy

**Comment by peterswimm** [comment]
We have already started a first round on docs changes in the docs repo:
https://github.com/howdyai/botkit-docs/blob/master/docs/readme-ciscospark.md

The main issue is breaking any external links, which looks unavoidable. best thing to do that for once is making the change all at once.

**Comment by ObjectIsAdvantag** [comment]
Yeh, I could see the docs changes on Botkit.ai. Great!

For the breaking changes to come (waiting for strategy), the "Webex for Developers" team is building a smooth strategy so that there should not be breaking change (basically, deprecation and support for months of the previous implementation). Hard to say when these will come live. 
Moreover, from my analysis of the Botkit connector code, these should not have strong impact (if any) on the Botkit connector API.

Then my proposal is to that now the changes we can take, as this will let us have a pretty stable API, and move forward with the Webex renaming (very soon, every 'Spark' mentions will be removed from all Cisco assets). 

I have sum'ed up above the changes we can now take (controller.sparkbot object, CiscoSparkbot module, ciscospark_access_token to configure the bot, webhook URL /ciscospark/receive, bot.type = 'ciscospark')
and to move things forward, I have just created two implementations in these forts:
- [Breaking changes](https://github.com/ObjectIsAdvantag/botkit/commit/43152186a5affd50bfa207e1f1ea9f99cf5d4452): I changed lib/{CiscoSparkbot.js → WebexBot.js}, and the related lib/Botkit.d.ts and lib/Botkit.js codes (watch out I am not versed in TypeScript, and don't have an example at hand to check it works fine). The migrated example is working fine on my machine {spark_bot.js → webex_bot.js}
- [Non breaking](https://github.com/ObjectIsAdvantag/botkit/commit/bedd16e330e4c21464382f2ec0e3aee3c9e55534): I introduced a check on the presence of the 'ciscospark_access_token' to let existing bots still work with no change. In this branch, both the [migrated example](https://github.com/ObjectIsAdvantag/botkit/blob/non-breaking/examples/webex_bot.js) and the [pre-existing example](https://github.com/ObjectIsAdvantag/botkit/commit/bedd16e330e4c21464382f2ec0e3aee3c9e55534#diff-a1af34354918881910f57da3e090f9ee) do work conjoinly. Note that I also updated the documentation and added a [Webex rebrand - Backward compatibility section](https://github.com/ObjectIsAdvantag/botkit/blob/non-breaking/docs/readme-webex.md#webex-rebrand)

**Comment by peterswimm** [comment]
that sounds reasonable, let this thread know when any pulls are submitted and we will fast track adoption into botkit core.

**Comment by peterswimm** [comment]
Also addressing any outstanding issues at the same time when possible would be great https://github.com/howdyai/botkit/issues?q=is%3Aissue+is%3Aopen+label%3ACisco-related

**Comment by ObjectIsAdvantag** [comment]
Successfully tested the [Non breaking branch](https://github.com/ObjectIsAdvantag/botkit/commit/bedd16e330e4c21464382f2ec0e3aee3c9e55534) for proposed updates on the production/demo bot [deployed on heroku : `convos@sparkbot.io`](https://github.com/ObjectIsAdvantag/botkit-convos)

**Comment by peterswimm** [comment]
We merged a request to support the change in the sparkbot email.

**Comment by benbrown** [comment]
@ObjectIsAdvantag now that I merged your PR, are we good to go? 

Are there going to be shifts in the libary names on NPM that we'll need to account for in the future?

**Comment by ObjectIsAdvantag** [comment]
awesome, thanks for the merge @benbrown and @peterswimm 

there will other changes coming related to the Webex rebrand, but there is no finalized/official timeline for these.
I propose we close the ticket

**Comment by benbrown** [comment]
Sounds good! Thanks @ObjectIsAdvantag!
