### ISSUE TITLE
An error occured in the send middleware:: TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by MagSag** [howdyai/botkit#1347]
I am builiding a facebook messenger bot and I have activated debug and this is the error that I am getting : 
App 26242 stdout: info: An error occured in the send middleware:: TypeError: Cannot read property 'id' of undefined
I don't know what it means and what may probably be the cause since I am not using personnaly a middleware in the bot.
I want to understand it and see if there is any problem with my code.

**Comment by MagSag** [comment]
I didn't make any change on botkit core..I am using the version  "botkit": "0.6.8",
 bot.startConversation(message,function(err,convo){
        messageToSend.forEach(function(el,index){
            convo.say(el);
            convo.next();
            if (index == messageToSend.length-1){
                convo.say({sender_action:'type_off'});
                convo.next();
            }
        });
            
        });

**Comment by ouadie-lahdioui** [comment]
@MagSag can you share more code than :

````
console.log("Not an array");
        console.log(message);
bot.reply(message, { sender_action : "typing_off" });
console.log("Message to send");
console.log(messageToSend);
        bot.reply(message,messageToSend);
````
