### ISSUE TITLE
Messenger Bot Not sending message 

### ISSUE THREAD

**Issue by MagSag** [howdyai/botkit#1348]
I activated debug to see what is going on... sometimes the bot user receive message but sometimes it doesn't. This is the output when a user send a message and the bot has to reply...the reply is not being send 
App 5736 stdout: debug: RECEIVED MESSAGE
App 5736 stdout: debug: CUSTOM FIND CONVO 1668776163210080 1668776163210080
App 5736 stdout: debug: WEBHOOK SUCCESS { recipient_id: '1668776163210080' }

On messenger side when the user sent the message it is not blue ticking : 
![mess](https://user-images.githubusercontent.com/13017395/40108118-be13cb04-5902-11e8-983f-81e57333095d.JPG)

The bot starts working well(sending message again) after me restarting the application . I am using passenger on my server. I am confused, I would like to know what is the problem or where the problem may be.

**Comment by ouadie-lahdioui** [comment]
@MagSag your bot should respond back to facebook every time. make sure that you don't have an error and if so you respond back to fb with 200 status.

I had the same problem each time my local botkit fork and fb doesn't got a response from the server, and i think (not sure as is not officially mentioned in fb documentation) that fb blacklist the server for a while in this case.

I hope that helps

**Comment by MagSag** [comment]
@ouadie-lahdioui I think the error is what I have reported here #1347 I don't know why this error.

**Comment by ouadie-lahdioui** [comment]
let's talk in the other thread
