### ISSUE TITLE
Rocket.Chat Connector

### ISSUE THREAD

**Issue by diegodorgam** [howdyai/botkit#1350]
Howdy guys,

we're starting to develop the BotKit Rocket.Chat connector. I've just [forked this repo](https://github.com/RocketChat/botkit) and @ArthurTemporim is our GSOC student, he will be working in this project to develop this connector.

Any help is very welcome, if you have some experience developing connectors to botkit and can share that with us, please reply to this issue or find us at [#bots](https://open.rocket.chat/channel/bots) channel.

thanks for your attention and very much thank you for this awesome project <3

Cheers

**Comment by benbrown** [comment]
I'll keep an eye on this thread! Let me know if you have any questions.

**Comment by arthurTemporim** [comment]
Hello @benbrown,

 i realized that when you text `botkit new` it's ask for the platform, and when you select the platform the `cli.js` script clone a `botkit-starter-<platform>` repository. So to integrates rocketchat to botkit it is needed to create a `botkit-starter-rocketchat` repository? And have any documentation about what configurations is needed to create a `botkit-starter-<platform>`?

Thanks :D

**Comment by peterswimm** [comment]
We have a dedicated channel for this over in #rocket_chat

**Comment by diegodorgam** [comment]
@benbrown @peterswimm hey, could you guys invite me to that slack? We are needing some help to understand botkit pipeline.

thks.

**Comment by peterswimm** [comment]
https://github.com/RocketChat/botkit-rocketchat-connector
https://github.com/RocketChat/botkit-starter-rocketchat
