### ISSUE TITLE
How to detect unanswered/unhandled messages?

### ISSUE THREAD

**Issue by simonfranzen** [howdyai/botkit#1355]
How can I detect unhandled messages ? We have a running botkit bot (socket) with some custom triggers and dialog.flow as a middleware. I am wondering how to detect the unhandled messages:

User writes something -> The bot is not responding.

Where can I hang in ? The best would be that I can flag the message and as "unhandled" and send this flag to a analytics tools or just save it into a DB.

**Comment by peterswimm** [comment]
This is the main reason we did a console in Botkit studio:
https://botkit.groovehq.com/knowledge_base/topics/console

If you use LUIS and Studio, you can also map unhandled messages heard by your bot to your training data via the console.

Monitoring unhandled with built in studio stats or a stats provider like Dashbot is a good start.

You can also create a fallback hear that reports the unhandled utterance (and prompts the user to refine their input)  https://botkit.ai/docs/core.html#controllerhears

And then use some kind of middleware to send your team a report:
https://botkit.ai/docs/middleware.html

**Comment by simonfranzen** [comment]
> You can also create a fallback hear that reports the unhandled utterance (and prompts the user to refine their input) https://botkit.ai/docs/core.html#controllerhears

I think this is the right thing for us, but how to set it up ? I tried to flag a message in the convo, but my flag didnt made it to the middleware.

**Comment by peterswimm** [comment]
Check out this topic  https://github.com/howdyai/botkit/issues/969#issuecomment-324927682

**Comment by Purus** [comment]
I was struggling with the issue with Botkit  Web + Rasa NLU. The issue was that the bokit-rasa middleware does not process regular expressions.
