### ISSUE TITLE
Problem sending synchronized messages

### ISSUE THREAD

**Issue by ca42rico** [howdyai/botkit#1357]
I'm facing some problems sending synced messages (a block of messages).
I'm using bot.startConversation(), is there some alternative ways?

Note: now I'm using bot.startConversation() for send multiple messages and bot.reply() for send single message to Facebook.

With bot.startConversation (), when some messages arrives while bot.startConversation () is processing, the controller stop working (not catch next messages).
My controller is:
var controller = Botkit.facebookbot({ access_token: <token>, verify_token: <token>, require_delivery: true, storage: myStorage });

Thanks

**Comment by c0nstructer** [comment]
Had similar issue that some messages weren't coming back. Have resolved with following situation:

```
var controller = Botkit.facebookbot({
require_delivery: true
});
```
And on facebook developer page, be sure to mark the following:

![pagesub](https://user-images.githubusercontent.com/3758455/40798479-7183ac9a-650b-11e8-94e0-1f7e0158ad41.png)

This way bot is forced to get confirmation that message is being sent. Worked for me.
