### ISSUE TITLE
Files from public aren't served as expected

### ISSUE THREAD

**Issue by ToddHoff** [howdyai/botkit#136]
I'm not sure if this is a bug or just my misunderstanding. I thought files would be served out of /public in my bot directory because of in SlackBot.js :

slack_botkit.webserver.use(express.static(__dirname + '/public'));

This doesn't work because __dirname resolves to "bot/node_modules/botkit/lib", not my bot directory.

So I added to my code:
webserver.use(require('express').static(__dirname + '/public'));

Now the webserver is finding static files in my public directory.

**Comment by anonrig** [comment]
Nice catch! Can you send a pull request about this? @ToddHoff

**Comment by ToddHoff** [comment]
I'm not exactly sure of the proper fix. I would guess use process.cwd()?

**Comment by m4olivei** [comment]
This was fixed for Slack in #214, but Facebook got left behind :(.  Here is a pul request to remedy that: https://github.com/howdyai/botkit/pull/252

**Comment by peterswimm** [comment]
seemingly resolved, please reopen if this is not the case.
