### ISSUE TITLE
Using Rasa Core for Response Management

### ISSUE THREAD

**Issue by Purus** [howdyai/botkit#1360]
I have successfully created a web-based chat bot using the great BotKit and Rasa NLU. It works great.

In this I have to write lot of code just to verify the user input and send the static response as mentioned below.

```
controller.hears('hello','direct_message', function(bot, message) {
    bot.reply(message,'Hello yourself!');
});
```

I had to repeat this line for all possible intents and messages which can make my code base large.

Rasa Core has the ability to understand the input and give back the proper response. Can this be integrated to BotKit so that I don't have to write lot of code in Javascript?

If not what are the other ways I can reduce my code base?

**Comment by Purus** [comment]
Thanks for info. Let me try that.

In your opinion which will be more powerful? Using rasa response or handling in botkit?

**Comment by Naktibalda** [comment]
I don't know how good is Rasa.
I only use botkit as a proxy for Watson Assistant, so my entire dialog logic is in Watson.
