### ISSUE TITLE
Small Talk Feature like DialogFlow

### ISSUE THREAD

**Issue by Purus** [howdyai/botkit#1361]
Are there ways to implement Small Talk kind of feature in botkit using skills along with Rasa NLU? 

Are there any reference for the same?

**Comment by Purus** [comment]
This feature could be part of botkit by default.. just my thoughts..

**Comment by Purus** [comment]
Great to know.

Due to corporate policies, I can't use the great features

**Comment by peterswimm** [comment]
We also offer an on-premises version of Botkit Studio, you can email me if interested and we can discuss the details: peter@howdy.ai

We will be announcing the roadmap and expected features soon. but until then no ETA right now.

**Comment by Purus** [comment]
Sure . Thanks. I will drop an email.

Regarding smalltalk, I have implemented smalltalk feature based on an existing data set ported to rasa_nlu format.

https://github.com/alyssaong1/botframework-smalltalk/blob/master/smalltalkkb.tsv

How do I contribute it back to the community? What should be the approach for the same.

**Comment by peterswimm** [comment]
It would probably be best to publish it to your own github repo, and then share it as a link on the rasa middleware, we could do something like add a section to it called examples or dataset templates.
