### ISSUE TITLE
How to pass user info at runtime?

### ISSUE THREAD

**Issue by Purus** [howdyai/botkit#1364]
I have read docs on booting with user info. As per my understanding this needs to be done in the public client JavaScript code.

How do I pass entire user object values from my botkit controller, maybe before start hearing on.

**Comment by ouadie-lahdioui** [comment]
@Purus WDYM by booting with user info ?

**Comment by Purus** [comment]
In my understanding we need to pass on user information to store them along
work message. Please correct me if I am wrong.

**Comment by ouadie-lahdioui** [comment]
which one are you using (FB, SLack, WS, Web ...) ?

**Comment by Purus** [comment]
I am using web platform.

**Comment by peterswimm** [comment]
@Purus take a look at these docs for dealing with user data on the web client https://github.com/howdyai/botkit-starter-web/blob/master/docs/botkit_web_client.md#share-user-accounts--profile-data-with-botkit

**Comment by sudk97** [comment]
I have the same issue, can I by any means pass some values from the javascript where I embedded my bot on the web and use it in the controller to say validate the user and then respond accordingly?

**Comment by adantoscano** [comment]
@Purus @sudk97 you can add more keys: values to the object that you send to botkit from the frontend and then manage them with a middleware in botkit.

**Comment by Purus** [comment]
Any example on how to do this will be helpful.

**Comment by adantoscano** [comment]
https://github.com/howdyai/botkit-starter-web/blob/e0cead4da1e0cf84ab9b12f432508e2d4365e865/public/client.js#L70

I copied the function from here and add the following...

```javascript
        that.deliverMessage({
          type: 'message',
          text: text,
          user: this.guid,
          channel: this.options.use_sockets ? 'socket' : 'webhook'
          custom: 'Purus rocks!'
        });
```

then in botkit use middleware

```javascript
controller.middleware.receive.use(function(bot, message, next) {
  console.log(message.custom); //Puru rocks!
  next();
});

```

**Comment by sudk97** [comment]
How do I capture the key: value pair passed from frontend onto my skills code? Is there any specific variable that it's stored in or some mustache value?

**Comment by sudk97** [comment]
Thanks a lot @adantoscano, worked for me :+1:
