### ISSUE TITLE
Showing smilies in message

### ISSUE THREAD

**Issue by Purus** [howdyai/botkit#1365]
How do I show smilies like :) in the message and render it using web platform.

**Comment by adantoscano** [comment]
https://emojikeyboard.org/ just copy and paste

**Comment by Purus** [comment]
I have tried the same and it does does not work in all browsers. Even in
different chrome..

**Comment by adantoscano** [comment]
It depends on typo libraries, OS and browser. Emojis is Unicode but each platform has it own.

https://www.omgubuntu.co.uk/2016/08/enable-color-emoji-linux-google-chrome-noto

**Comment by Purus** [comment]
Thanks. It was helpful.

I just found that Slack plugin has an option of specifying emoji_icon property in the reply. 

Something similar to that can be added for web as well.

**Comment by adantoscano** [comment]
@Purus I forgot that also depends on the website i.e. wordpress sites switch emoji unicode to custom svg.

http://unicode.org/emoji/charts/full-emoji-list.html

**Comment by gp187** [comment]
Use the `Javascript escape string` from any of these https://charbase.com/1f60d-unicode-smiling-face-with-heart-shaped-eyes

Make sure to remove the `'` from the text. Just `\ud83d\ude0d`
