### ISSUE TITLE
Botkit for Telegram?

### ISSUE THREAD

**Issue by tidjee** [howdyai/botkit#1366]

**Comment by peterswimm** [comment]
This is currently supported via the Bot framework. We have not had much interest expressed in a dedicated integration, but ill make this the official request thread for it to track.

**Comment by madtaras** [comment]
@peterswimm is this possible to build a direct integration? Is there any progress on this right now? Bot framework requires a lot of overhead. Half a year ago they removed the free version. To host a small demo with 2 bots, we paid about 100$

**Comment by peterswimm** [comment]
You arent required to pay for Bot framework, you just need to publish on the free Azure tier. You can then host it where you'd like.

Anything is possible, it just requires someone to do/sponsor the work.

**Comment by Jaikant** [comment]
> You arent required to pay for Bot framework, you just need to publish on the free Azure tier. You can then host it where you'd like.
> 
> Anything is possible, it just requires someone to do/sponsor the work.

The free tier of the botframework has a limit of 10,000 msgs. After which it is charged at $0.04 per msg.
