### ISSUE TITLE
Question: Self-hosted Analytics Integration

### ISSUE THREAD

**Issue by Purus** [howdyai/botkit#1368]
All the analytics services available are either hosted by 3rd party organization.

Are there any options for using self-hosted analytics platform to be used with the organization.

**Comment by peterswimm** [comment]
There is a self-hosted version of Botmetrics you can install:
https://github.com/howdyai/botmetrics

**Comment by Purus** [comment]
Thanks. I was about to install that. Thanks for quick response.

**Comment by Purus** [comment]
I installed botmetrics in my own server and found that it's not showing web as a platform. But getbotmetrics.com web shows an option for web chat bots.

Is the repo not updated? Please let me know how to use analytics for web bots.

**Comment by peterswimm** [comment]
Check this out:
https://bot-metrics.com/docs#other

If you want a more recently updated stats solution, I would checkout dashbot
https://www.dashbot.io/docs/generic/

**Comment by peterswimm** [comment]
The self hosted version is largely the same, with the change of pointing the API host at your local instance:
https://github.com/botmetrics/botmetrics.js#setting-your-api-host-for-self-hosting

**Comment by Purus** [comment]
There is a major difference in self hosted version. General web bot option
is not available on GitHub repo.

**Comment by peterswimm** [comment]
You will have to do some work on your own granted. Right now the hosted solutions are more robust and less work for you to do to support.

**Comment by Purus** [comment]
Agreed on this point. But due to corporate restrictions I can't use hosted
service.

Please consider this as a closed.
