### ISSUE TITLE
Hi i am working on a movie-chatbot using recast.ai , and i am using movie database JSON file to fetch data,and when i querry my chabot about a particular movie it shows the related movie, but when i querry some another movie it still show the result of same querry anypossible soultion to that

### ISSUE THREAD

**Issue by DrAwesomexX** [howdyai/botkit#1371]

**Comment by adantoscano** [comment]
Can you share piece of code of your fetch? and witch platform are u dev for?

**Comment by DrAwesomexX** [comment]
function findMovieByName(title){
  
    const find= movieDB.find(p => p.title.toLowerCase() === title.toLowerCase());


    if(!find){
        return null
    }

    return find;
}


function movieInformation(req,res){

    const movie = req.body.conversation.memory.movie;
    const movieInfo = findMovieByName(movie.value);
  
    if(!movieInfo){
        res.json({
            replies:[
                {
                    type:'text',
                    content:'unable to fetch information about movie' 
                }


            ]
        });
        
        
    }
    
    
    else{
         return res.json({
            replies:[{
                type:'text',
                content:movieInfo.year
            },{
                type:'text',
                content:movieInfo.storyline
            },{
                type:'text',
                content:movieInfo.posterurl
            }],
        });
        
    }

    
}

**Comment by DrAwesomexX** [comment]
I am developing for facebook messenger and using node.js

**Comment by peterswimm** [comment]
Not related to Botkit, try posting the question over here
https://github.com/RecastAI

**Comment by adantoscano** [comment]
You are not using botkit... You should ask in any other forum but... let's try to fix it.

put a log to see the value of 'movie.value' and also take care with the other conts values

good luck!

**Comment by DrAwesomexX** [comment]
recast.ai Q&A is not that active

**Comment by DrAwesomexX** [comment]
https://github.com/DrAwesomexX/joke-bot

this is my git repo
