### ISSUE TITLE
New Slack changes due 24th cause file_shared to not trigger

### ISSUE THREAD

**Issue by ken9ross** [howdyai/botkit#1372]
The changes to file handling Slack is implementing on 24th cause a controller.on('file_shared' to not trigger.

The event request body is as per below (note lack of subtype in body.event and changing body.event.file to an array of objects)

{ token: 'xyzzy',
  team_id: 'Txxx',
  api_app_id: 'Axxx',
  event:
   { type: 'message',
     text: '',
     files: [ [Object] ],
     user: 'Uxxx',
     upload: true,
     display_as_bot: false,
     bot_id: null,
     ts: '1528154625.000382',
     channel: 'Cxxx',
     event_ts: '1528154625.000382',
     channel_type: 'channel' },
  type: 'event_callback',
  event_id: 'EvBxxx',
  event_time: 1528154625,
  authed_users: [ 'Uxxx' ] }

**Comment by peterswimm** [comment]
This should be fixed
