### ISSUE TITLE
Botkit spark messages not received

### ISSUE THREAD

**Issue by ShashankaNataraj** [howdyai/botkit#1374]
Hi Im trying to get to get a basic bot up and running by following the tutorial. I have an ngrok tunnel running and am trying to get the bot running by:

`access_token=xyz public_address=https://xyz.ngrok.io node .`

The bot starts up fine. When I mention `@botname hi` in the spark room where Ive added the bot, I also see the webook getting triggered to the ngrok url

![image](https://user-images.githubusercontent.com/650317/40964421-ad6f22e6-68c8-11e8-8330-b6314e86cb49.png)
I get a 502 bad gateway with no further log messages. What am I doing wrong?

**Comment by peterswimm** [comment]
Perhaps try running ngrok separately, then your node app? Are you able to hit your APPURL/ciscospark/receive in a browser?
