### ISSUE TITLE
Facebook standby events for handover are not being triggered

### ISSUE THREAD

**Issue by samuelazran** [howdyai/botkit#1376]
Dear botkit team,

I've implemented a facebook bot with bot kit and also uses the handover protocol.

The problem is that when the bot is on handover mode, the regular "message_received" event is still being triggered and not any of the standby events. (the webhook is subscribed to all the events)

So, this is not being triggered when the user talk to the human agent:

`controller.hears('(.*)', 'standby,message_reads,message_deliveries,messages,messaging_postbacks', function(bot, message) {`

But this event is still being triggered as if it's not the secondary receiver.
`controller.hears('(.*)', 'message_received,facebook_postback', function(bot, message) {`

From the Facebook side the conversation moves to the "Page Inbox" so the handover works as expected, just the botkit is not.

I'm using the latest commit of botkit from the git master.

Please any help and guidance would be much helpful,

Samuel

**Comment by jonlow** [comment]
hey @samuelazran any progress made on this?

**Comment by yaliagap** [comment]
@samuelazran @jonlow  something new about using the handover protocol?

**Comment by adantoscano** [comment]
@samuelazran Have you triggered controller.api.pass_thread_control() before?
