### ISSUE TITLE
How send local file? (Microsoft BotFrameWork)

### ISSUE THREAD

**Issue by theodasilva** [howdyai/botkit#1377]
Hi
I make a botframework chat bot and i try to send a generate pdf.
During a conversation i create a pdf file who summarize user responses and I want to send it to him. But for set a file in attachement for download I need to create a link for this file. How can I make this link or how can I send it to user?

**Comment by peterswimm** [comment]
You might try asking this over here: https://github.com/Microsoft/BotBuilder
