### ISSUE TITLE
Writing the logs by default

### ISSUE THREAD

**Issue by Purus** [howdyai/botkit#1378]
I am using the bokit-web template and it's working fine.

But the chat logs are not stored by default in the .data folder. I am not using MongoDB storage.. I am going with the default option.

Should I use any logic to enable the logging the message feature?

**Comment by peterswimm** [comment]
There is no provision for chat logs in the Web storage by default, even if you were using Mongo. You can either build this yourself, or use Botkit Studio which comes with chatlogs in its metrics package.

**Comment by Purus** [comment]
Thanks. Hopefully I can do it myself.
