### ISSUE TITLE
Carousel for Botkit Anywhere

### ISSUE THREAD

**Issue by phidodido** [howdyai/botkit#1379]
I know the carousel is supported for Facebook Messenger but how do I add this feature in Botkit Anywhere?

**Comment by adantoscano** [comment]
you should design it in frontend

**Comment by theodasilva** [comment]
For add a carousel to chat you can change "/public/chat.html" and associed files

**Comment by peterswimm** [comment]
It is in our long term roadmap to allow the web chat to have basically the best of all the other platforms in terms of attachments. In the meantime, the answers above are correct!

**Comment by Purus** [comment]
I am more interested in web chat features 👍

**Comment by bim-g** [comment]
did any one try carousel on messenger lite?
