### ISSUE TITLE
pass result from rest api into studio script 

### ISSUE THREAD

**Issue by Prithivraj200** [howdyai/botkit#1380]
Hi,
  I need to pass the data I received from rest API to botkit chat. I have tried using convo.setVar('name',result) in script and tried to fetch it using {{vars.name}}. But it's displaying null value. 
  
![dash_js](https://user-images.githubusercontent.com/22617738/41234813-e1ea784a-6daa-11e8-94be-5a2a6d2ffb70.png)
![script_ui2](https://user-images.githubusercontent.com/22617738/41234814-e21fca0e-6daa-11e8-8181-cbdac6140d41.png)
![script-ui](https://user-images.githubusercontent.com/22617738/41234816-e25398de-6daa-11e8-9895-2a07a1709eb2.png)

Kindly assist me.

**Comment by peterswimm** [comment]
Have you seen the following?
https://www.useloom.com/share/9d15953e7b2544fd9a3feba66c05dbf5
https://blog.howdy.ai/build-a-bot-data-powered-conversations-d14991714ac1

**Comment by Prithivraj200** [comment]
Hi Peter,
     Thanks for your reply.
     I have already tried with steps mentioned in above links. But I am getting null values. 
     Kindly find above attached screenshot.
Thanks

**Comment by Prithivraj200** [comment]
Hi Peter,
      When I set convo.setVar('name','body') outside http request I am able to see result. But why it's not working when placed inside http call?

**Comment by Prithivraj200** [comment]
Solved it by using 'request' instead of 'https'
