### ISSUE TITLE
beforeThread isn't being called for 'default'

### ISSUE THREAD

**Issue by pauldariye** [howdyai/botkit#1381]
Unable to enrich conversation using the `beforeThread`.
```javascript
module.exports = (controller, bot, conversation) => {
  conversation.addMessage(
    {
      text: "You're email is *{{vars.user.email}}*.",
      action: "completed"
    }, 'default')
  )
/*
 * Before hooks
 */
conversation.beforeThread('default', async (convo, next) => {
    const { user: userId } = convo.context
    const { err, data: { user } } = await to(controller.storage.users.get(userId))
    ...
    convo.setVar('user', user)
    ...
    next()
})
 conversation.activate()
}
```

See original [issue](https://github.com/gratifyguy/botkit-mock/issues/39)

**Comment by pauldariye** [comment]
For more context, the `beforeThread` handler works for all threads that come after `default`. 

There are two solution that work for me to circumvent this behavior/bug.

1. You can have a script after `default` like `start`. This looks like so:

```javascript
conversation.addMessage(
  {
      text: `Hello`,
      action: 'start'
  }, 'default'
)

conversation.addMessage(
  {
      text: `Hello`
  }, 'start'
)

conversation.beforeThread('start', (convo, next) => {
... 
})
```

2. You can use the [Studio API](https://studio.botkit.ai/app/bots/5a2acf7ef2009c0012849208/scripts)'s `before` handler. With that you'd have something like:
```javascript
controller.studio.before('default', (convo, next) => {})
```

**Comment by benbrown** [comment]
This is a know issue. I can't remember at the moment why it is hard to solve, but for some reason it is, and the work-arounds above have proven satisfactory to us _so far_, but this should at some point get fixed.
