### ISSUE TITLE
do 'advanced metrics' in Botkit studio include support for custom events?

### ISSUE THREAD

**Issue by pgoldweic** [howdyai/botkit#1382]
I am having trouble finding any documentation that describes how to create a custom dashboard that offers a glimpse at the usage of custom events in my bot's conversations. Is this supported?. I am not yet a (paid) subscriber of Botkit Studio, although I've been using botkit, but I would like to know whether the 'advanced metrics' supported by Botkit Studio include support for such analytics (the hope is to be able to answer this question without -or before- becoming a paid customer). Thanks!

**Comment by peterswimm** [comment]
Not yet! Currently you have access to the same metrics you see as a trial user. You can setup a free account to try these out.

**Comment by pgoldweic** [comment]
Thanks for the quick reply!
