### ISSUE TITLE
Error in Botkit Studio Stats: SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by KingsDevelopment** [howdyai/botkit#1393]
6/19/2018 3:43:10 PM    at JSON.parse (<anonymous>)
    6/19/2018 3:43:10 PM    at Request._callback (/opt/app/node_modules/botkit/lib/Studio.js:504:33)
    6/19/2018 3:43:10 PM    at Request.self.callback (/opt/app/node_modules/request/request.js:188:22)
    6/19/2018 3:43:10 PM    at emitTwo (events.js:126:13)
    6/19/2018 3:43:10 PM    at Request.emit (events.js:214:7)
    6/19/2018 3:43:10 PM    at Request.<anonymous> (/opt/app/node_modules/request/request.js:1171:10)
    6/19/2018 3:43:10 PM    at emitOne (events.js:116:13)
    6/19/2018 3:43:10 PM    at Request.emit (events.js:211:7)
    6/19/2018 3:43:10 PM    at IncomingMessage.<anonymous> (/opt/app/node_modules/request/request.js:1091:12)
    6/19/2018 3:43:10 PM    at Object.onceWrapper (events.js:313:30)
    6/19/2018 3:43:10 PM    at emitNone (events.js:111:20)
    6/19/2018 3:43:10 PM    at IncomingMessage.emit (events.js:208:7)
    6/19/2018 3:43:10 PM    at endReadableNT (_stream_readable.js:1064:12)
    6/19/2018 3:43:10 PM    at /opt/app/node_modules/async-listener/glue.js:188:31
    6/19/2018 3:43:10 PM    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    6/19/2018 3:43:10 PM    at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:218:9)

I'm hoping this is the same issue as #1259

**Comment by peterswimm** [comment]
Earlier our hosting provider was doing maintenance, are you still seeing the issue?

**Comment by Emil-A** [comment]
I'm seeing this issue now, is this still issue #1259 ?

**Comment by peterswimm** [comment]
@Emil-A no known issues right now, could you email us what error you are seeing: help@botkit.ai
