### ISSUE TITLE
How can have more than 1 facebook page attached to my bot

### ISSUE THREAD

**Issue by MagSag** [howdyai/botkit#1394]
I have 5 pages and I would like all of them to use the same botkit instance but inside my code I would also like to know which page exactly sent the request.

Is this possible and how can I do that?

**Comment by peterswimm** [comment]
Take a look at this thread:
https://github.com/howdyai/botkit/issues/914

In the meantime, you should probably have a unique botkit application per page, as I mentioned in your earlier post.
