### ISSUE TITLE
Slack "message" event is not fired, but hears detect it

### ISSUE THREAD

**Issue by flashkiller58rus** [howdyai/botkit#1399]
It seems like a bug with a slack "message" event.

Bot joined to channel, slack configured and permissions are set.

When i run this code:
`    controller.on('message',function(bot, event) {
        console.log('Added new message in the channel!');
    });`
and post message into channel, console is clear.

When i run following:
`    controller.hears(['^.*$'], 'ambient', function(bot, event){
      console.log(event);
    });`
console shows up message data:
`{ token: 'xKfFYfeVp77xX82yQBikLY87',

  team_id: 'T0JLA7FT5',

  api_app_id: 'AB9PSP7A8',

  event: 

   { type: 'message',

     user: 'U6K37EU5P',

     text: 'Test message!',

     ts: '1529939933.000014',

     channel: 'CBDJT0F1T',

     event_ts: '1529939933.000014',

     channel_type: 'channel' },

  type: 'ambient',

  event_id: 'EvBEEBT8QN',

  event_time: 1529939933,

  authed_users: [ 'UBA03L7UK' ],

  raw_message: 

   { token: 'xKfFYfeVp77xX82yQBikLY87',

     team_id: 'T0JLA7FT5',

     api_app_id: 'AB9PSP7A8',

     event: 

      { type: 'message',

        user: 'U6K37EU5P',

        text: 'Test message!',

        ts: '1529939933.000014',

        channel: 'CBDJT0F1T',

        event_ts: '1529939933.000014',

        channel_type: 'channel' },

     type: 'event_callback',

     event_id: 'EvBEEBT8QN',

     event_time: 1529939933,

     authed_users: [ 'UBA03L7UK' ] },

  _pipeline: { stage: 'receive' },

  user: 'U6K37EU5P',

  text: 'Test message!',

  ts: '1529939933.000014',

  channel: 'CBDJT0F1T',

  event_ts: '1529939933.000014',

  channel_type: 'channel',

  team: 'T0JLA7FT5',

  events_api: true,

  match: 

   [ 'Test message!',

     index: 0,

     input: 'Test message!' ] }`

Is "message" event functionality broken?

**Comment by peterswimm** [comment]
I don't think so, try a more specific regex string to catch what you are trying to trigger?
