### ISSUE TITLE
bot.closeRTM() does not do anything?

### ISSUE THREAD

**Issue by giang271291** [howdyai/botkit#140]
I have the following scenario, in which calling `bot.closeRTM()` doesn't seems to close the connection. Is there anything I did wrong?

    bot.startRTM(function(err,bot,payload) {
      if (err) {
        throw new Error('Could not connect to Slack');
      }

      ...

      fs.readFile(file, 'utf8', function (err,data) {
          if (err) {
            return console.log(err);
          }

          ...
          bot.sendWebhook({
            ...
          });
          bot.sendWebhook({
            ...
          });
          bot.closeRTM();
      });
    });

**Comment by benbrown** [comment]
This is likely because the real time connection _has not yet fully connected_ when you called bot.closeRTM, so it does nothing.

THAT SAID, If you are doing nothing but sending incoming webhooks, you don't need to connect to the RTM.
