### ISSUE TITLE
Jabber: issue with the rich text message

### ISSUE THREAD

**Issue by guillain** [howdyai/botkit#1402]
Hi,

I've an issue to display rich text message in the Jabber chat windows.
I'm testing with the example but without success.
My stanza msg doesn't have the parameteres get previsouly.
After have requested the function the app crash during the send command.

Thanks for your support !

code:
```
exports.msg = function(bot, message){
    console.log(">>>>>", "message", message);

    let reply_message = {};
    let to = message.user;
    let type = message.group ? 'groupchat' : 'chat';
    let body = 'robot-button demo(only for Jabber Windows)';
    reply_message.text = body;
    console.log(">>>>>", "to", to);
    console.log(">>>>>", "type", type);
    reply_message.stanza = xml `<message to="${to}" type="${type}"><body>${body}</body><html xmlns="http://jabber.org/protocol/xhtml-im"><body xmlns="http://www.w3.org/1999/xhtml"><div class="container"><h6>${body}</h6><button class="btn btn-primary btn-sm center-block" style="margin-top:8px;" robot-type="robot-button" type="button" robot-message="help">Send back help message</button></div></body></html></message>`;
    console.log(">>>>>", "reply_message", reply_message);
    bot.reply(message, reply_message);
};
```
log:
```
>>>>> message { user: 'xxx@xxx.com/jabber_19133',
  text: 'test',
  group: false,
....
>>>>> to xxx@xxx.com/jabber_19133
>>>>> type chat
>>>>> reply_message { text: 'robot-button demo(only for Jabber Windows)',
  stanza:
   Element {
     name:
      [ '<message to="',
        '" type="',
        '"><body>',
...
  xmpp:connection send: <<message to="," type=","><body>,</body><html xmlns="http://jabber.org/protocol/xhtml-im"><body xmlns="http://www.w3.org/1999/xhtml"><div class="container"><h6>,</h6><button class="btn btn-primary btn-sm center-block" style="margin-top:8px;" robot-type="robot-button" type="button" robot-message="help">Send back help message</button></div></body></html></message> xmlns="xxx@xxx.com/jabber_19133" id="xxxxxx">chatrobot-button demo(only for Jabber Windows)robot-button demo(only for Jabber Windows)</<message to="," type=","><body>,</body><html xmlns="http://jabber.org/protocol/xhtml-im"><body xmlns="http://www.w3.org/1999/xhtml"><div class="container"><h6>,</h6><button class="btn btn-primary btn-sm center-block" style="margin-top:8px;" robot-type="robot-button" type="button" robot-message="help">Send back help message</button></div></body></html></message>> +12ms
2018-06-27T15:06:27:connection has been closed!
```

Version:
`node:  v8.11.3`

Thanks ;-)

**Comment by guillain** [comment]
Hi,

No news?

Thanks in advance for your help

**Comment by guillain** [comment]
thanks for your reply but it's already the case with the version 0.3.0

**Comment by guillain** [comment]
I discover a strange behavior and it happens only with the button example.
Code extract below:
```
const Botkit = require('../botkit/lib/Botkit.js');
const xml = require('@xmpp/xml');

var controller = Botkit.jabberbot({
    json_file_store: './jabberbot/'
});

var bot = controller.spawn({
    client: {
        jid: 'xxx',
        password: 'xxx',
        host: "xxx",
        port: xxx
    }
});

controller.hears(['robot-button'], ['direct_mention', 'self_message', 'direct_message'], function (bot, message) {
    let reply_message = {};
    let to = message.user;
    let type = message.group ? 'groupchat' : 'chat';

    let body = 'robot-button demo(only for Jabber Windows)';
    reply_message.text = body;
    reply_message.stanza = xml`<message to="${to}" type="${type}"><body>${body}</body><html xmlns="http://jabber.org/protocol/xhtml-im"><body xmlns="http://www.w3.org/1999/xhtml"><div class="container"> <h6>${body}</h6><button class="btn btn-primary btn-sm center-block" style="margin-top:8px;" robot-type="robot-button" type="button" robot-message="help">Send back help message</button></div></body></html></message>`;
    bot.reply(message, reply_message);
});
```
Two log type (?):
*   xmpp:connection receive: <message from='xxx@xxx'...xmlns='http://jabber.org/protocol/chatstates'/></message> +162ms
* xmpp:connection send: <<message to="," type=","><body></form> </div></body></html></message>> +7ms

So issue on the "send" command as:
* variables are not present into. "to" and "type" are blank as already mentionned in my first post
* I've a doublon of '<' and '>' on the message open and closure

If someone can help.
I know it's Jabber but this product is still alive (and XMPP also specifically when we compare the response time...) :-D so thanks in advance for your support

**Comment by panx981389** [comment]
I have no problem when test the code in my environment.
When you run the code jabber_bot.js under examples, do you met the same issue?

**Comment by guillain** [comment]
Hi @panx981389 ,

Thanks for your support, really appreciated :-)
That's the script that I use for this test. The only change done on this script (./example/jabber_bot.js) is in the credentials and IM&P info. These parameters have been validated as the solution works well without the button feature.

On your tests do you the doublon of '<' & '>' on the button tracelog message?
I tested to remove it from the script, at the end it appears properly in the tracelog but no behavior changing.

Thanks again

**Comment by panx981389** [comment]
The weird thing is that xml' didn't replace "${to}" and  "${type}" correctly. I have no problem for this in my environment. What OS system are you using? Mine is Windows 10 and macOs 10.13.5.
      [ '<message to="',
        '" type="',
        '"><body>',

**Comment by guillain** [comment]
I'm using RedHat 7.5 on x86 64 pf.

Not sure that the issue comes from the @xmpp/xml library as when a execute the example in the README file it works well.
```
# node
> const xml = require('@xmpp/xml')
> const body = ' hello '
> const stanza = xml`
... <message>
... <body>${body}</body>
... </message>
... `

> console.log(stanza.toString())
<
    <message>
    <body>,</body>
    </message>
    xmlns=" hello "/>
>
```

**Comment by panx981389** [comment]
It looks like the const xml = require('@xmpp/xml') didn't works in your environment.
It should log
<body> hello </body>

**Comment by yandanarendra** [comment]
Facing same issue and nee help on this
