### ISSUE TITLE
Facebook Checkbox plugin - subscribe for messaging_optins webhook.

### ISSUE THREAD

**Issue by julianusti** [howdyai/botkit#1403]
I'm trying to integrate with [Checkbox plugin](https://developers.facebook.com/docs/messenger-platform/discovery/checkbox-plugin)

The last step that is missing right now is to handle the `messaging_optins` webhook event.

I found out that we do have an event called [facebook_optin](https://github.com/howdyai/botkit/blob/master/lib/Facebook.js#L443) that I can subscribe to.

Is that the right event to subscribe to? Does anyone tested it? Does it works?

**Comment by wilfredonoyola** [comment]
HI @julianusti , Did you test this? I am having the same problem.

**Comment by nishch** [comment]
@julianusti you are right, `facebook_optin` is the correct event to subscribe to, and you can rely on `message.optin` field in the corresponding event handler to grab the information collected in the checkbox plugin. It does work.
