### ISSUE TITLE
why controller.hear not work when regex is ^\d+$

### ISSUE THREAD

**Issue by aiguang** [howdyai/botkit#1404]
I try to capture the input number using hear() like

   **controller.hears('[/^\d+$/]' ,'message_received', function(bot, message) {}**

but I found it would not worked. E.g. when input is '123123', this function would not trigger and the default function 'unhandledMessage' will handle it. Is it a known issue?

**Comment by benbrown** [comment]
When you specify regular expressions with `hears`, you need to escape them.

Try `^\\d+$` note the double \

**Comment by aiguang** [comment]
thanks @benbrown , it could be worked
