### ISSUE TITLE
Webhook 'facebook_optin' doesn't works.

### ISSUE THREAD

**Issue by julianusti** [howdyai/botkit#1405]
I have subscribed for `facebook_optin` webhook, so I can be notified when the user confirms opt-in for Checkbox plugin and it doesn't receive any notifications.

**Comment by benbrown** [comment]
@julianusti did you get this working?

**Comment by julianusti** [comment]
@benbrown not yet.
So, all I need to do on botkit side, is to subscribe for `facebook_optin` and do my magic, right?
```
controller.on('facebook_optin', (bot, message) => {
    console.log('user subscribed.');
});
```

**Comment by peterswimm** [comment]
That should be it, where is the bot hosted?

**Comment by julianusti** [comment]
@peterswimm @benbrown I've tried to use `Send To Messenger` Plugin and it works, but it is still doesn't work with `Checkbox Plugin`.

**Comment by consigliere23** [comment]
Any news for this? We are using Checkbox Plugin, APP ID, REF, PAGE ID it's all fine, subscribed to events. I am admin of APP and Page, app is development mode. But we are not receiving the notifications?
