### ISSUE TITLE
Troubling messages coming from cerberus-xxxx.lb.slack-msgs.com

### ISSUE THREAD

**Issue by pthieu** [howdyai/botkit#1407]
This may not be specific to just this repo but I use botkit extensively and would like to see if I can PR some security features.

Once a week, my app crashes because I have unsupported messages coming from `cerberus-xxxx.lb.slack-msgs.com`.

Searching this on google shows a number of results with this link, sometimes it's botkit, sometimes it's some other libs in other languages or platforms.

Does anyone know where this link is from? Is it a malicious site or is it part of slack's checks?

**Comment by peterswimm** [comment]
Thats a part of Slack services, I asked Slack about it and its probably related to a load balancer for RTM connections. What function are you running before the crash? Any chance your bot could switch to only using events api? This would be more stable in the long term/

**Comment by peterswimm** [comment]
Yea, thats feedback maybe passed onto slack ;).

If you could post some code that invokes this, it might be something we can fix in botkit, but if its hard to reproduce it might be hard to fix.
