### ISSUE TITLE
Replacing an interactive message button when it is clicked.

### ISSUE THREAD

**Issue by alexframe** [howdyai/botkit#1408]
I can't work out via issues or docs how to achieve the behaviour (replacing a button with text after it's actioned) in the following gif from the slack docs.

![button](https://cfr.slack-edge.com/dcb1/img/api/message_guidelines/Example_6.gif)

If I use `bot.replyInteractive` it replaces the entire attachment instead of just the button text.

According [the documentation found here](https://api.slack.com/interactive-messages#responding_right_away), it says:

> Responding immediately with a JSON message body will replace the current message in its entirety by default. If you explicitly indicate that you want to create a new message instead, specify false in the replace_original field.

I still however cannot work out how to achieve this behaviour. 

Has anyone else managed to replace an interactive button with a message upon it being clicked?

**Comment by benbrown** [comment]
@alexframe As the docs state, the only option available is replacing the entire message.

Luckily, Slack sends the original message back as part of the button click payload, so you can use that as the basis for your response.

**Comment by benbrown** [comment]
This skill, included in the Botkit Starter Kit for Slack, demonstrates this in action:

https://github.com/howdyai/botkit-starter-slack/blob/master/skills/interactive_messages.js#L8

**Comment by silentsnooc** [comment]
So, that's exactly what I am doing. Or at least I thought so.

I send back the exact same message but Slack responds with a HTTP 500.

All I am doing is going through the blocks, change _one_ text field of a button and write back the same message I received. Am I missing something?

Question on stackoverflow: https://stackoverflow.com/questions/57033773/respond-to-user-interaction-how-to-update-message
