### ISSUE TITLE
How to add user icon in chat window?

### ISSUE THREAD

**Issue by aiguang** [howdyai/botkit#1410]
I create a web app using  'botkit new --platform web'.  I found there is no user icon in chat window. Is there anyway to add user pic for customer and chatbot like other IM, e.g. skype?

![image](https://user-images.githubusercontent.com/1451194/42625952-ab0698a4-85fb-11e8-8a84-e5872c58e0ee.png)

**Comment by peterswimm** [comment]
You have access to the CSS and skins files, which would allow you to theme the chat how you want. 
https://github.com/howdyai/botkit-starter-web/tree/master/sass

Your user would be the outgoing message.

You could even get fancy with the user records if you have access to user avatars and populate that in the chat:
https://github.com/howdyai/botkit-starter-web/blob/master/docs/botkit_web_client.md#share-user-accounts--profile-data-with-botkit

**Comment by aiguang** [comment]
@peterswimm , could  you share more case or detail? I found user only have some fields id/name/...in Client API. To add avatar, we must use Botkit Studio?

**Comment by peterswimm** [comment]
No, this is entirely code you would create in the CSS code. We don't have any examples of that, but if you peruse the links I sent you it should tell you where to stick the images in your chat client.

Studio does not provide this functionality.

**Comment by aiguang** [comment]
Thanks @peterswimm
