### ISSUE TITLE
Botkit.d.ts should expose Botkit.core

### ISSUE THREAD

**Issue by musou1500** [howdyai/botkit#1412]
`Botkit.core()`  is necessary to  build a custom Botkit Platform Connector on TypeScript.
Do you have a plan to write these definitions?

**Comment by Naktibalda** [comment]
@musou1500 please make a pull request.

**Comment by frankgerhardt** [comment]
I think that can be closed because this PR has been merged https://github.com/howdyai/botkit/pull/953/files
