### ISSUE TITLE
controller.on() Message Events should be using the same naming standard

### ISSUE THREAD

**Issue by mariusa** [howdyai/botkit#1413]
There are 3 different styles now for naming events:
https://botkit.ai/docs/core.html#receiving-messages-and-events

```
message_received
conversationStarted
heard-trigger
```
Please make all of them the same style. You choose which, but stick to it :)
For backwards compatibility, continue handling previous styles too, but don't document them.

Thanks

**Comment by benbrown** [comment]
Good catch @mariusa!
