### ISSUE TITLE
[Botkit Web] When is the User id regenerated ?

### ISSUE THREAD

**Issue by lucasvercelot** [howdyai/botkit#1417]
Hi guys,

I'm looking for some informations about the user id.
I would like to know on what conditions it is regenerated ?
I guess that one of them is the removal of the cookie `botkit_guid` but I have no ideas about others conditions.

Thanks in advance for your help !
Cheers

**Comment by peterswimm** [comment]
Thats the sole built in reason it would be generated. If your website has user accounts, and you want to identify the existing user to the chat widget, you can include user profile information in the call to Botkit.boot().  

More on this over here:
https://github.com/howdyai/botkit-starter-web/blob/master/docs/botkit_web_client.md#client-api

**Comment by lucasvercelot** [comment]
Thank you very much @peterswimm ! 🙂
