### ISSUE TITLE
Notify all in bot.say?

### ISSUE THREAD

**Issue by rohilshah95** [howdyai/botkit#1418]
Is there a way to notify all users in a channel using bot.say?

I have ```@channel``` in the text field, but it just prints it as ```@channel``` and doesn't send a notification

**Comment by rohilshah95** [comment]
required 
```
link_names: 1,
parse: 'full'
```

in the bot.say parameters

**Comment by peterswimm** [comment]
You can also do something like
<!channel> or <!everyone>

from:
 https://get.slack.help/hc/en-us/articles/202009646-Make-an-announcement
