### ISSUE TITLE
Local installation Web server redirect

### ISSUE THREAD

**Issue by yyzgeorge** [howdyai/botkit#1423]
Please advise what will be the best way to redirect Apache server running on a site with botkit installed, to redirect /facebook/receive requests to a node.js instance running on its own port (3000) instead.

**Comment by SpEcHiDe** [comment]
I think you can set up a reverse proxy in your instance by following this [tutorial](https://www.digitalocean.com/community/tutorials/how-to-use-apache-as-a-reverse-proxy-with-mod_proxy-on-ubuntu-16-04)
