### ISSUE TITLE
Embed iframe in React?

### ISSUE THREAD

**Issue by robbiew** [howdyai/botkit#1424]
When I embed botkit in React, I get this console error and chat doesn't load:

`GET http://arrow-tarn.glitch.me/%7B%7B%7Burl%7D%7D%7D 404 (Not Found)`

[Replicated here in Code Sandbox](https://codesandbox.io/s/qlny17pm6)

Any idea what I'm doing wrong?

**Comment by nickisaacs** [comment]
Works fine for me! (the above sandbox)
