### ISSUE TITLE
A way to sending messages using twilio copilot

### ISSUE THREAD

**Issue by vindu939** [howdyai/botkit#1427]
https://www.twilio.com/docs/sms/services/tutorials/how-to-send-sms-messages-copilot

Twilio has a feature called copiliot, which allows users to configure both short codes and phone numbers and provides a messaging service sid, we can use this sid to send messages and twilio automatically determines whether to user shortcode or phone number to send the sms. This as very useful feature.

**Comment by peterswimm** [comment]
This would have to be implemented either as a middleware or a platform connector.
