### ISSUE TITLE
Slack initiate conversation from external event

### ISSUE THREAD

**Issue by Oliverr** [howdyai/botkit#1428]
Our SlackBot receives a notification from an external source which is then driven into a bot.say() event to the Slack channel.
When someone responds to the output of bot.say() we want it to drive a further action back to the external source (via a POST using some of the message in the response + original message).
Sample flow:

```
BOT: XYZ has just occurred on ABC
USER: Tell me more
BOT: Here are the latest details for the event
```

Is bot.say() the correct method to initiate this workflow?
The conversation will be open to the entire channel, not an individual user.

**Comment by Oliverr** [comment]
@benbrown confirmed that message_replied is returning a non-normalised structure which is not currently supported.
Work around is:

```
controller.middleware.categorize.use(function(bot, message, next) {
if (message.type=='message_replied') {
 message.text = message.message.text;
 // and copy user and other fields 
} 
next() });
```
Please mark as issue/bug

**Comment by peterswimm** [comment]
Will do, will you be submitting a PR?

**Comment by Oliverr** [comment]
I just have: #1441

**Comment by ryansydnor** [comment]
Given the `legacy` branch is in maintenance mode and the associated PR is stale - I'm going to close this issue.
