### ISSUE TITLE
Start slack bot on multiple VM's

### ISSUE THREAD

**Issue by prabhuj** [howdyai/botkit#1429]
I am using node to start a slackbot. I deployed slackbot to multiple VM's. I see that for every message, i get response multiple times (number of VM's). Is there a way to restrict only one VM to respond to my slack message ?

**Comment by asopinka** [comment]
We had this problem when connecting and building the bot with Slack RTM.
I ended up having to re-write everything for Obie.ai to use the Events API.

I'd highly suggest moving to the Events API and just starting off with it for any new bots. You can use a load-balancer in front of your multiple VMs to direct traffic. RTM is a major headache as you grow. The only major loss is the "Bot is typing..." indicator (but that's a Slack limitation, not Botkit).

In the words of one of the Botkit founders Ben Brown: "You **_will_** have issues scaling with RTM".
