### ISSUE TITLE
Matched expressions not showing up in message.match

### ISSUE THREAD

**Issue by markstickley** [howdyai/botkit#143]
```
controller.hears('set volume (\\d+)','direct_message,direct_mention,mention', function(bot, message) {
    console.log(message);
});
```

> @bot: set volume 80

```
{ type: 'message',
  channel: 'xxx',
  user: 'xxx',
  text: 'set volume 80',
  ts: '1456917563.000012',
  team: 'xxx',
  event: 'direct_mention' }
```

It matches the expression but there is no `match` property where I can get the number from.

Is this a bug or am I using it incorrectly? Thanks!

**Comment by dossy** [comment]
I just tried to reproduce your issue, and got:

```
{ type: 'message',
  channel: 'x',
  user: 'x',
  text: 'set volume 80',
  ts: '1459047632.000360',
  team: 'x',
  event: 'direct_mention',
  match: [ 'set volume 80', '80', index: 0, input: 'set volume 80' ] }
```

Can you still reproduce your issue with the latest Botkit code?

**Comment by markstickley** [comment]
Hi! I upgraded to the latest version and it seems to work fine now - thank you :)

**Comment by dossy** [comment]
Fantastic, thanks for letting me know!  :+1:
