### ISSUE TITLE
Slack bot file upload not working anymore

### ISSUE THREAD

**Issue by BogdanAlexandru11** [howdyai/botkit#1434]
Hi. 

The 
```
controller.on('file_share', function (bot, message) {
}
```
is not working anymore, since the last slack update. It looks like it's just not hitting that part of the code.
Are there any work arounds for this ?

**Comment by peterswimm** [comment]
Are you using an Events api based bot? This was recently deprecated for RTM bots:
https://api.slack.com/events/message/file_share

**Comment by BogdanAlexandru11** [comment]
Okay, thanks I will look into this.

**Comment by peterswimm** [comment]
Please let us know if you still see trouble once you have completed your research.
