### ISSUE TITLE
Botkit Hoek Version

### ISSUE THREAD

**Issue by mikeverbeck** [howdyai/botkit#1444]
I recently installed Botkit but npm is reporting that the version of hoek installed as a nested dependency is vulnerable.  What am I missing? Do I need to specify anything special in my package.json file to avoid this?

package.json
```
{
  "name": "deleteme",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "botkit": "^0.6.16"
  }
}
```

npm audit
```
Moderate        Prototype pollution

  Package         hoek

  Patched in      > 4.2.0 < 5.0.0 || >= 5.0.3

  Dependency of   botkit

  Path            botkit > botbuilder > jsonwebtoken > joi > hoek

  More info       https://nodesecurity.io/advisories/566
```
npm ls hoek
```
+-- botkit@0.6.16
| `-- botbuilder@3.15.0
|   `-- jsonwebtoken@7.4.3
|     `-- joi@6.10.1
|       +-- hoek@2.16.3
|       `-- topo@1.1.0
|         `-- hoek@2.16.3  deduped
```

**Comment by Naktibalda** [comment]
It is a very deep down dependency chain,
`jsonwebtoken: 8.*` no longer has a dependency on joi, so upgrading jsonwebtoken would remove hoek from dependency tree.

botbuilder has updated dependencies 2 days ago: https://github.com/Microsoft/BotBuilder/pull/4715
so you have to wait for a new release of botbuilder.

**Comment by peterswimm** [comment]
If the downstream fix linked doesnt solve the issue, let us know and we can reopen this and investigate further.

**Comment by LukeBaulch** [comment]
I'm experiencing the same issue as above. It looks like npm is now hosting botbuilder@4.2.0 which no longer depends on jsonwebtoken@7.*. Can we get this dependency updated?

**Comment by Naktibalda** [comment]
Please take a look at #1473 instead.
