### ISSUE TITLE
Build_connector documentation improvements

### ISSUE THREAD

**Issue by lucasvercelot** [howdyai/botkit#1452]
Hi guys ! 👋 

I'm currently trying to build a Twilio SIP connector, but even when a take a look at the TwilioSMS connector code I am not able to reproduce it in a similar way for the SIP one.

I even tried to build WhatsApp, Telegram and LINE connectors without success. I don't know where to start, which methods are optionals or not, etc.
For example when I add the endpoint I want in the method `createWebhookEndpoints`, my endpoint can't be accessed, event if I load my module like the provided example.

As you can see, I'm struggling to build a connector on my own, hope you'll be able to help me.

Would it be possible to update the 'build_connector' documentation in a more understandable format ?
I find it very complex to understand.

Thanks in advance !

**Comment by peterswimm** [comment]
You should jump in our community slack if you have general questions about building a connector, or want a code review. This can be a complex discussion so it might be best to start over there to get the initial clarity, and we of course will take any suggestions on way to improve the documentation via a PR.
