### ISSUE TITLE
Install error `error:0906D06C:PEM routines:PEM_read_bio:no start line`

### ISSUE THREAD

**Issue by navarrojava** [howdyai/botkit#1459]
I am facing the following error, when trying to install the lib.

![image](https://user-images.githubusercontent.com/7165906/45581477-181c6a80-b875-11e8-94c0-6a5c53f910a0.png)

my node and npm versions

![image](https://user-images.githubusercontent.com/7165906/45581496-a690ec00-b875-11e8-87ac-15e00473bacd.png)

SO informations
![image](https://user-images.githubusercontent.com/7165906/45581509-cc1df580-b875-11e8-9c60-ac00277b9674.png)

**Comment by peterswimm** [comment]
What’s the output of the log it’s referring to?

**Comment by benbrown** [comment]
@navarrojava did this get resolved?  Seems like an issue with npm.

**Comment by navarrojava** [comment]
> @navarrojava did this get resolved? Seems like an issue with npm.

not solved yet, I am using version 0.6.9, if I use above I get this error.

**Comment by benbrown** [comment]
I would upgrade to a more recent version and see if this is resolved.
