### ISSUE TITLE
Having no luck with bot.say with attachments

### ISSUE THREAD

**Issue by ToddHoff** [howdyai/botkit#146]
I have no problem using convo.say, but I can't seem to get bot.say to work with attachments. I do have the most recent code that contains the JSON.stringify change. When I just have the text parameter it works, but when attachments is added there's nothing displayed when I do a bot invite in a channel and there are no errors. Any ideas?

controller.on('channel_joined',function(bot, channel) {
   bot.say({channel: channel.channel.id, text: "Test", attachments: [{'pretext': 'pre-hello', 'text': 'text-wo    rld'}]}, function(err,response){
         if (err) {
          console.log("Error replying to channel_joined err:" + err + " response:" + response);
         }
   });
}

This is the output before slack_api.callAPI('chat.postMessage', options, cb) is called:

{"id":2,"type":"message","channel":"C0Q73K2TF","text":"Test","username":null,"parse":null,"link_names":null,"attachments":"[{\"pretext\":\"pre-hello\",\"text\":\"text-world\"}]","unfurl_links":null,"unfurl_media":null,"icon_url":null,"icon_emoji":null,"as_user":true}

Perhaps bot.say should work like convo.say?

**Comment by ianalexander** [comment]
What is the content of `response` in the callback for `bot.say()`? Is `{ok => true}`?

**Comment by ToddHoff** [comment]
Here's the call:

controller.on('channel_joined',function(bot, channel) {

   console.log("chanel_joined: " + channel.channel.id);

var reply_with_attachments = {
    'username': 'My bot' ,
    'text': 'This is a pre-text',
     'attachments': [
      {
         'fallback': 'To be useful, I need your to invite me in a channel.',
         'title': 'How can I help you?',
         'text': 'To be useful, I need your to invite me in a channel ',
         'color': '#7CD197'
       }
     ],
     'icon_url': 'http://lorempixel.com/48/48'
     }

    bot.say({channel: channel.channel.id, text: "test", attachments:
reply_with_attachments}, function(error, data{
        console.log("error:" + error + " data:" + JSON.stringify(data));
     });

}

Here's the response:

info: ** API CALL: https://slack.com/api/chat.postMessage

error:null
data:{"ok":true,"channel":"C0Q4F58MB","ts":"1457378337.000208","message":{"type":"message","user":"U0PCVMJG7","text":"test","ts":"1457378337.000208"}}


No attachments were displayed on the channel. Only "test".


thanks

**Comment by ianalexander** [comment]
Check PR #144, can you merge that change and see if it fixes your issue?

**Comment by mvaragnat** [comment]
Hello ToddHoff, I think there are two problems with your approach,

First, you could you use bot.reply(channel, your_message, ...) instead of bot.say(your_message). The channel variable that you get from controller.on can be replied to. That saves you from specifying the channel, for example.

Secondly, you mixed up a bit between the message and the attachements. that's why only the text: "test" is picked up. It should look like this:

`controller.hears('another_keyword','direct_message,direct_mention',function(bot,message) {
  var reply_with_attachments = {
    'username': 'My bot' ,
    'text': 'This is a pre-text',
    'attachments': [
      {
        'fallback': 'To be useful, I need your to invite me in a channel.',
        'title': 'How can I help you?',
        'text': 'To be useful, I need your to invite me in a channel ',
        'color': '#7CD197'
      }
    ],
    'icon_url': 'http://lorempixel.com/48/48'
    }

  bot.reply(message, reply_with_attachments);
});`

**Comment by ToddHoff** [comment]
Here's what eventually worked for me:

var reply_with_attachments = {

channel: channel.channel.id,
'username': 'My bot' ,
'text': 'This is a pre-text',
'attachments': [
{
'fallback': 'To be useful, I need your to invite me in a channel.',
'title': 'How can I help you?',
'text': 'To be useful, I need your to invite me in a channel ',
'color': '#7CD197'
}
],
'icon_url': 'http://lorempixel.com/48/48'
}

bot.say(reply_with_attachments);


On Mon, Mar 7, 2016 at 12:34 PM, Matthieu Varagnat <notifications@github.com

**Comment by mvaragnat** [comment]
yep, that looks better (FWIW, you can save the channel: channel.channel.id line by using bot.reply(channel, reply_with_attachments) if you want)

**Comment by ToddHoff** [comment]
I tried that version it didn't work. I forget the error. Maybe
invalid_array_arg? So I went with what I could get to work :-) I appreciate
your help. Working with botkit + slack + nodej has been fun and relatively
easy, but there are still huge wholes in my understanding.

**Comment by dossy** [comment]
Since the issue was with @ToddHoff's code and not a bug/issue in Botkit, should this issue get closed now that @ToddHoff's gotten past his issue?
