### ISSUE TITLE
Slack Unfurl issue if the same app is installed in two different workspace for the same user

### ISSUE THREAD

**Issue by BhuwanBhaskar** [howdyai/botkit#1462]
Hi Everyone,
Currently, I am working on an app which will unfurl links from a particular domain.I have used Botkit framework for app development. 

Installing the same app into multiple slack workspaces for the same user has an unintended effect:
Suppose a user X install app in one slack workspace, say A, then the same user X again installs the same app in a different workspace (without uninstalling the app from workspace A), say B, this leaves the user X with broken unfurl experience in workspace A.

For example:
Scenario 1: If the user adds a link (which can be unfurled from the app) into a non-shared channel of workspace A, the link won't be unfurled (even though the user had already installed the app in workspace A) and 'unfurl' method will throw error saying 'cannot_find_channel' (user token is invalid: https://api.slack.com/methods/chat.unfurl)
Scenario 2: If the user X adds the same link in any non-shared channel of workspace B, the link would be unfurled properly.

Error in scenario 1 (for workspace A) comes because, while installing the app in workspace B, botkit tries to identify 'user X' from the database and since 'user X' already exists (as the same user had already installed the app in workspace A) in database, so botkit will simply update 'access_token' for workspace B and leave the user details same. As botkit replaced previous access_token (which came when the user installed the app in workspace A) with the new access token which came when the user installed the app in workspace B, so the user has already lost access_token for workspace A.
Now when 'unfurl' API gets called from workspace A (i.e. user adds the link in any non-shared workspace of A),  botkit uses new access_token (which is corresponding to workspace B) for posting unfurled link message to the channel of workspace A which results in error 'cannot_find_channel'.

Ask:
1) Is it a known issue on botkit? If yes, is there any plan to fix this issue in a future release?
2) How can we handle the above scenario gracefully with botkit to fix this issue now?

Botkit version: 0.6.7
Below is source code reference which causes above weird behavior:
https://github.com/howdyai/botkit/blob/0259be829e262f4a6d98aff3927a946e558ebfdc/lib/SlackBot.js#L782

I am using mysql storage and have implemented all required storage methods as specified in https://botkit.ai/docs/storage.html

**Comment by asopinka** [comment]
Slack user ids should be different for every team.
For example, my same email is used on many different teams but each unique team gives me a unique user id.

That being said, if you're encountering the issue, you could modify your storage to get/save a different unique like a combining `user_id|team_id`. You'll also need to fork your own copy of botkit and then change all the `user.get`/`user.save` on `slack_botkit.storage` to include the `user_id|team_id` format.
