### ISSUE TITLE
Duplicate line in Facebook connector

### ISSUE THREAD

**Issue by adantoscano** [howdyai/botkit#1463]
there is a `if (!message.sender_action) {...} else {...}` before `if (message.sender_action) {...}`

https://github.com/howdyai/botkit/blob/0259be829e262f4a6d98aff3927a946e558ebfdc/lib/Facebook.js#L68

**Comment by peterswimm** [comment]
Good catch, care to submit a pr?

**Comment by benbrown** [comment]
Thanks @adantoscano
