### ISSUE TITLE
ReplyWithTyping using Slack Events API

### ISSUE THREAD

**Issue by pavelkostyurin** [howdyai/botkit#1464]
As far as I understand, bot.replyWithTyping works only with RTM, and not Slack Events API.

What are my choices if I want my bot to reply with typing and still use Slack Events API? Can I use RTM for typing only or shall I abandon Slack Events API and switch to RTM in this case?

**Comment by benbrown** [comment]
You could, but it would be enormously resource intensive to maintain an open websocket just for this.

I'd say the better option is to submit a request to Slack that they properly support typing indicators via the API!
