### ISSUE TITLE
Facebook Botkit: Controller.hear() isn't triggered although message is received in incoming webhook

### ISSUE THREAD

**Issue by hossa95** [howdyai/botkit#1466]
I got the webhook setup successfully and every thing looks fine but When i chat with the page the message reaches `webserver.post()` function and i can log it their.. but none of the `controller.hear` functions are activated and no response get back to Facebook.

here is the log i get in the `incoming_webhook.js` inside the `webserver.post`:
```
{ object: 'page',
  entry:
   [ { id: '420594811306038',
       time: 1537432160923,
       standby:
        [ { sender: { id: '1769532383135057' },
            recipient: { id: '420594811306038' },
            timestamp: 1537432159906,
            message:
             { mid:
                '9VSrzoZO1wztsWCyCHOsO5IRXKPqM2VpE7kKIGRRC_IjkcNxJqmbtPkVQu64KqFhulzD_Gvl6Pry4vzBnirLFA',
               seq: 1215320,
               text: 'hello' } } ] } ] }
```
Note That: 
I have an app auto deployed on glitch and it works perfectly and i downloaded it and just reupload on ec2 machine.

**Comment by adantoscano** [comment]
@hossa95 you're receiving message as standby, and botkit is categorising as it. That state it's suppose to be about facebook handover protocol. Are you using it?

**Comment by benbrown** [comment]
@hossa95 did this advice help you solve your issue?  It is definitely the correct advice - your bot is not the primary receiver of those messages, so Botkit will see those as `standby` message instead of `message_received` or any other type.

This is as-designed for compatibility with Facebook's handover protocols.
