### ISSUE TITLE
how controller.spawn() works?

### ISSUE THREAD

**Issue by adantoscano** [howdyai/botkit#1467]
Deeping into how botkit works I've just realise that in facebook [example](https://github.com/howdyai/botkit-starter-facebook/blob/111695fe95a306b0f65c800e3c5da7e76a8dfd52/components/routes/incoming_webhooks.js#L14) bot is spawned each message received although, in docs, it is spawned only once.

Which is better and why?

**Comment by benbrown** [comment]
In most webhook related bots, Botkit will spawn a new bot instance for each incoming message. The bot instance contains the configuration information and methods to reply to a specific incoming message.

When used with Slack RTM protocol, the bot is spawned only once and it is tied for the lifetime of the connection to the socket connection.

**Comment by benbrown** [comment]
If your bot only ever connects to a single team or page or user entity somewhere, it can probably spawn once and be reused. However, it is best practice to spawn a bot instance in response to the incoming message.

**Comment by adantoscano** [comment]
Oki thanks :+1:
