### ISSUE TITLE
Using `controller.studio.run` in middleware doesn't work for web version

### ISSUE THREAD

**Issue by calben** [howdyai/botkit#1469]
For a botkit bot that uses middleware to launch a script, it will behave as expected in a platform like Facebook but will not correctly switch to the script in a web version of botkit.

Add the below to a middleware and create a 'MainMenu' script in your studio.

```
if (message.text.match('^(menu)')) {
        controller.studio.run(bot, 'MainMenu', message.user, message.channel, message)
      }
```

In Facebook, your conversation will be switched correctly.

In web, the first line of the new script to be run will present, and the user will be prompted with options for responses.
After this, the response is consumed and ignored.
Instead of continuing the new script, the bot will continue with the previously running script as if it has just received a response for it.

**Comment by benbrown** [comment]
If you want to start a new script, you have to end the previous one.  With 2 active at once, things will not work as expected.

You can do this with the following code:

```
 bot.findConversation(message, function(convo) {
if (convo) {
            // stop the conversation and swallow this message
             convo.stop('quit');
           } else {
                 // nothing ongoing, this message passes through
               next();
           }
      });
```

**Comment by calben** [comment]
Great, thanks!
Why is it the behaviour is different on the different platforms?

**Comment by benbrown** [comment]
It shouldn't be, but there might be a quirk in the way the socket connection works.
