### ISSUE TITLE
Need Help: WS Connection Problem

### ISSUE THREAD

**Issue by javedblch** [howdyai/botkit#1471]
Hi there,

We are currently implementing BotKit AI in one of our projects as an FAQ chat bot. For technical reasons we are trying to establish a cross domain websocket connection. For example, we have our botkit/node js code hosted at 'bot.mywebsite.com'. And we have an endpoint that points to that url which is something like 'www.mywebsite.com/bot.'

However, the WS connection is consistently refused when BotKit is trying to establish a connection. For example, the problem seems to emanate from this particular line of code mentioned below:

var Botkit = {
config: {
ws_url: (location.protocol === 'https:' ? 'wss' : 'ws') + '://' + location.host,

'location.host' happens to be equals to 'www.mywebsite.com/bot.'

However, we have also manually tried to replace the location.host with the following

ws_url: (location.protocol === 'https:' ? 'wss' : 'ws') + '://bot.surveycrest.com',

And yet it keeps refusing the connection on the browser end when you launch the page.

Looking forward to your technical feedback,

best wishes

Javed

**Comment by adantoscano** [comment]
add location.pathname after location host

**Comment by javedblch** [comment]
@adantoscano 

let me reiterate the case again

our application is running on Server A, and bot app is hosted on diffrent server

server A: https://www.surveycrest.com
server B: http://bot.surveycrest.com

We virtually(url redirection via proxy) pointed https://www.surveycrest.com/bot to root of server B, so that /bot could access bot app
https://www.surveycrest.com/bot

it seems to be connected with nodejs, but somehow not with the chat app.

**Comment by adantoscano** [comment]
@javedblch 

let me reiterate the code again

try with `ws_url: 'ws://bot.surveycrest.com'`

just kidding XD

You are getting this code error `connection to 'wss://bot.surveycrest.com/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED` in browser console.
This is caused by this `wss`, it should be `ws` or secure your bot.surveycrest.com endpoint  or try with: 
`ws_url: 'wss://www.surveycrest.com/bot'`

**Comment by sivanandh** [comment]
After hosted on own server space getting botkit web - websocket url error:

**Please suggest my how to fix:**

WebSocket connection to 'wss://abc.xyz.com/my_bot' failed: Error during WebSocket handshake: Unexpected response code: 200
