### ISSUE TITLE
[Botkit Web] New line/line break not working in messages

### ISSUE THREAD

**Issue by lucasvercelot** [howdyai/botkit#1472]
Hi everyone,

I'm wondering how I can send a single message but create new lines/line breaks inside.

I tried the following, with `\n` :
`var text = 'Line 1\nLine2\nLine3'`
`bot.say(text)`

But it's not working at all.

I would be glad to have some help/insight here.
Thank you in advance.

**Comment by adantoscano** [comment]
you should parse it in client, public folder

**Comment by lucasvercelot** [comment]
Thanks @adantoscano.
I used `<br>` instead of `\n` and it's working fine. 🙂
