### ISSUE TITLE
Search within the documentation (web)

### ISSUE THREAD

**Issue by gutierri** [howdyai/botkit#1478]
I have had a bit of work to solve doubts or search resources within the documentation, when I do not find research inside the source code.  This is not a problem, but an improvement.  I believe what is missing is a search for terms on the documentation web page.

One example is documentation generated by SPHINX-DOC.

**Comment by adantoscano** [comment]
Good idea, meanwhile you can use GitHub search [here](https://github.com/howdyai/botkit-docs)

**Comment by peterswimm** [comment]
This is actually on our roadmap, @adantoscano has the workaround exactly.
