### ISSUE TITLE
convo.addMessage and convo.addQuestion don't consider delay

### ISSUE THREAD

**Issue by tomaszbembnista** [howdyai/botkit#1480]
Hi all,

I have tried to set delay on messages added with methods convo.addMessage and convo.addQuestion, like described here: https://botkit.ai/docs/core.html#changing-the-pace-of-the-conversation-with-custom-per-message-delay
My code:

    class Conversation {
	 
	  wholeConversation(bot, message) {
			bot.createConversation(message, function(err, convo) {
				convo.addMessage({text:"Wait a little...", delay:3000, action:"message1"}, "default");
				convo.addMessage({text:"I will ask a question", delay:3000, action:"question"}, "message1");
							
				convo.addQuestion({text : 'Do you like cheese?', delay:3000}, [
					{
						pattern: 'yes',
						callback: function(response, convo) {
							convo.gotoThread('message2');
						},
					},
					{
						pattern: 'no',
						callback: function(response, convo) {
							convo.gotoThread('message3');
						},
					},
					{
						default: true,
						callback: function(response, convo) {
							convo.gotoThread('message4');
						},
					}
				],{},'question');
				
				convo.addMessage({text:"You answered yes", action:"message4"}, "message2");
				convo.addMessage({text:"You answered no", action:"message4"}, "message3");
				convo.addMessage({text:"Have a nice day"}, "message4");
				
				convo.activate();
			});
	  }
	}
	function restartConversation(bot, message) {
	  console.log("Restarting conversation");
	  const conversation = new Conversation;
	  conversation.wholeConversation(bot, message, JSON.parse(process.env.provisioning));
	}
	function startConversation(bot, message) {
	  console.log("Starting conversation");
	  const conversation = new Conversation;
	  conversation.wholeConversation(bot, message, JSON.parse(process.env.provisioning));
	}
	module.exports = function(controller) {
	  controller.setTickDelay(2000);
	  controller.on("hello", startConversation);
	  controller.on("welcome_back", restartConversation);
	};

It seems, the setting delay doesn't work in that methods. Method controller.setTickDelay changes nothing either. Here is a screenshot of bot outputs with timestamps:
![image](https://user-images.githubusercontent.com/25176830/47087605-bad15b80-d21c-11e8-9763-d55bb8851f73.png)

Same problem is mentioned here, but without answer:
https://github.com/howdyai/botkit/issues/1291#issuecomment-375914537

Can you please take a look at this issue?

Thanks and best regards,
Tomek

**Comment by ByrenHiggin** [comment]
G'day, 

Created a fix in #1481 

The timestamp and delay was being ignored since it was added after the message was already being queued to send. 

I have added proper delay functionality, and tested it to get desired behaviour. 

Hope this helps, 

Byren

**Comment by benbrown** [comment]
Fix is in! Pull the latest from master til we get this published to npm.
