### ISSUE TITLE
ios webGl Game navigation with accessibility mode enabled

### ISSUE THREAD

**Issue by MArslanRiaz** [howdyai/botkit#1489]
Hi, i am new you unity and webGL and English is not my native language so pardon my mistakes. I have created a Webgl Game on unity 2017.3.1 for visually impaired users. for that purpose. i used a box which navigates through all the game object through swiping on screen. its working fine on android(while turning accessibility on) but on iPhone. when i run the build on safari or chrome(while turned on voiceOver). neither the box is navigating on swiping nor any of the game UI is working . The swiping of screen as well as button clicking and other option are not reacting at all. kindly need help

Thank you.

**Comment by peterswimm** [comment]
This is seemingly unrelated to Botkit.
