### ISSUE TITLE
Stopping a conversation immediately after saying something silences previous message

### ISSUE THREAD

**Issue by taxigy** [howdyai/botkit#149]
I run a conversation and in response to some answer either stop a conversation or call `conversation.next`. The code:

```javascript
conversation.ask('Proceed?', (response, conversation) => {
  if (response.text === 'no') { // more comprehensive logic here; this sample is purely for this ticket.
    conversation.say('Okay');
    conversation.stop();
  } else {
    conversation.next();
  }
});
```

The conversation stops but I don't see the "Okay" message. Is this behavior correct?

**Comment by anonrig** [comment]
I believe you should use `conversation.reply` method for replying to a conversation instead of say.

**Comment by benbrown** [comment]
You should not call conversation.stop, but rather conversation.next.

This will cause it to move on to the next message ("okay") and then end.

**Comment by taxigy** [comment]
@anonrig, the problem is, `conversation` does not have `reply` property, so doing this way would cause a TypeError (there's however a bot instance in outer scope that does have `reply` property, I'll check it out).

@benbrown, I'm not getting this idea. I want the conversation to stop, why should I not call `conversation.stop`?

**Comment by benbrown** [comment]
Conversations are queues.
They will continue until there are no messages left in the queue, OR, they end immediately when conversation.stop is called.

You do not need to call conversation.stop manually.

**Comment by taxigy** [comment]
Okay, let me clarify. I'm having this code:

```javascript
bot.startConversation(message, (error, conversation) => {
  conversation.ask('abc?', (response, conversation) => {
    if (response.text === 'no') {
      conversation.say('Okay'); // not working
      conversation.stop();
    } else {
      conversation.next();
    }
  });

  conversation.ask('def?', (response, conversation) => conversation.next());
});
```

So, if the user responds "no" for the question "abc?", the bot should say "Okay" and discontinue the conversation. In case the users doesn't respond "no", the bot should ask the next question, "def?", and wait for the user's response.

If I call `conversation.then` in the first `ask`, the conversation will unconditionally go to the next question (and all over questions that's been defined as async calls of `conversation.ask`);

So, once again, why is `ask` that is called along with `stop` not working?

**Comment by airlikidh2** [comment]
Try this:

```
bot.startConversation(message, function (error, conversation)  {
  conversation.ask('abc?', function (response, conversation)  {
    if (response.text === 'no') {
      conversation.say('Okay'); // not working
      conversation.next();// this will move on the next conversation item in the queue. if there is none, it will end the conversation.
    } else {
      conversation.ask('def?', function(response, conversation) {
		  //do something with user input
		  conversation.next(); // this will move on the next conversation item in the queue. if there is none, it will end the conversation.
	  });
    }
  }); 
});
```

**Comment by taxigy** [comment]
That's a good suggestion, but I have already resolved this issue indirectly using ES6 generators and not using `startConversation` at all. Actually, I quite like the solution so I'd propose making a PR. If it turns into a general enough solution, I'll do it straightaway.

**Comment by mmattax** [comment]
This is still an issue - I'm not sure why the issue is closed. If you have messages in a conversation queued, it's important to be able to stop the conversation properly...

**Comment by peterswimm** [comment]
The initial poster indicated the supplied responses fixed his issue. If you believe you've found a bug, or would like to submit a PR that addresses this, we'd be happy to review a new issue.

**Comment by GautierT** [comment]
@taxigy : Can you post an exemple of your solution with ES6 generator ? Thanks !

**Comment by natterstefan** [comment]
@taxigy Would be great if you share your solution with us.

//cc @GautierT

**Comment by taxigy** [comment]
My project is quite complicated and cannot be opensourced even partially, so the only thing I can do is create a separate project stub that shows how to use generators to hold stateful conversations. It's completely out of scope of this issue, but it works for me. You can check it out in [taxigy/slackbot-starter](/taxigy/slackbot-starter/).

The core points:

- botkit is used as provider to Slack RTM API: I use its `hears` method to listen to all the messages from all the users,
- generators are used as stateful conversations: since every generator is stateful, it is instantiated per every user, every channel.
- no NLP, no data storage, but they should be to power up the bot's abilities to respond properly and hold context efficiently.
- every message executes `respond` function that, in turn, picks next value from the generator; now it's up to you to construct generators to provide conversations, request information from the user and provide appropriate answers.
- `yield*` with another generator branches the conversation to that generator from current point in conversation, without restarting anything, but there's no way back; it's impossible to finish branched conversation and jump back to the middle of the previous one (that would be awesome and that's what I'm working on).
