### ISSUE TITLE
Passing Data to Bot with Webhook

### ISSUE THREAD

**Issue by koubenecn** [howdyai/botkit#1492]
How can I pass data from outside the bot controller or webhook functions? Here's what I'm currently doing, which of course isn't working as `messageContent` is undefined...

```
let messageContent = "some content";

const controller = Botkit.slackbot({debug: true})

let bot = controller.spawn({
  incoming_webhook: {
    url: 'https://hooks.slack.com/services/*********************'
  }
});

bot.sendWebhook({
  text: messageContent,
  channel: '#general',
},function(err,res) {
  if (err) {
    // err
  }
});
```

**Comment by benbrown** [comment]
Why would messageContent be undefined there?

**Comment by pablovisual** [comment]
Idk if you are using the bot in a different way but shouldn't it be var bot = instead of let bot =
