### ISSUE TITLE
Error installing 'simple-bot' dependencies

### ISSUE THREAD

**Issue by jjescobaruni** [howdyai/botkit#1493]
Hi,
I am following the guide of the example "simple-bot" but when trying to install the dependencies I get the errors below:
2018-10-26T16_12_42_220Z-debug.log
\examples\simple-bot>npm install
npm WARN deprecated scmp@0.0.3: scmp v2 uses improved core crypto comparison since Node v6.6.0
npm ERR! Unexpected end of JSON input while parsing near '...gdlv8vKIIjf/Dorp7ZCj'

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\ae571xk\AppData\Roaming\npm-cache_logs\2018-10-26T16_12_42_220Z-debug.log

Attached is the log mentioned. I will really appreciate your help. Thanks!
[2018-10-26T16_12_42_220Z-debug.log](https://github.com/howdyai/botkit/files/2520082/2018-10-26T16_12_42_220Z-debug.log)

**Comment by benbrown** [comment]
Not sure what example you are talking about here - we don't have one called simple-bot.

**Comment by Naktibalda** [comment]
@benbrown it is https://github.com/watson-developer-cloud/botkit-middleware/tree/master/examples/simple-bot

@jjescobaruni it works for me:
```js
$ npm install
npm WARN deprecated scmp@0.0.3: scmp v2 uses improved core crypto comparison since Node v6.6.0
npm WARN deprecated hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer

> websocket@1.0.28 install C:\Projects\watson-botkit-middleware\examples\simple-bot\node_modules\websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)


C:\Projects\watson-botkit-middleware\examples\simple-bot\node_modules\websocket>if not defined npm_config_node_gyp (node "C:\Users\Naktibalda\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Naktibalda\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN botkit-middleware-watson-simple-example@0.0.1 No repository field.

added 403 packages from 356 contributors and audited 7328 packages in 37.317s
found 4 vulnerabilities (1 low, 3 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
```

Please look at proposed solution at https://github.com/watson-developer-cloud/botkit-middleware/issues/146#issuecomment-433768920

**Comment by peterswimm** [comment]
@Naktibalda Since this is for an example code outside this repo, closing this thread for now - feel free to post an issue over on the linked project!

**Comment by 7abhik** [comment]
npm install pm2 -g --force 
worked for me
