### ISSUE TITLE
Can I repeat what a user says when there are multiple "listeners" in one controller?

### ISSUE THREAD

**Issue by LAMike310** [howdyai/botkit#15]
var Botkit = require('botkit');

    var controller = Botkit.slackbot({
      debug: false
    });

    // connect the bot to a stream of messages
     controller.spawn({
     token: "XXXX-XXXXXXXXXXXXXXXXXXXXX",
    }).startRTM()

    controller.hears(['Apple', 'Orange'],['direct_message,direct_mention,mention'],function(bot,message, that_thing_that_you_typed) {
	    console.log("You said " + that_thing_that_you_typed)
    });

**Comment by LAMike310** [comment]
I'm trying to write a program that listens for multiple, but similar keywords. I have a separate function that takes in one of these keywords, and spits back some data to Slack. 

I could make a separate controller function for each keyword to send that data to a function I made, but it would save me a lot of typing if I could put multiple keywords in a controller function, and then grabbing what the user says inside one function. Does that make sense? Sorry if it sounded like I'm rambling.

Thanks,

Mike

**Comment by LAMike310** [comment]
controller.hears(['Apple', 'Orange'],['direct_message,direct_mention,mention'],function(bot,message) {
        console.log("You said " + message.text)
    });

**Comment by benbrown** [comment]
You got it.

You can also use normal Javascript string parsing tools like `message.text.match()` which can extract a keyword from a pattern.

**Comment by guillaumepotier** [comment]
Hi there,

I think with my PR #39 you'll be able to directly see in `message.match` what matched in `message.text` and triggered this listener.

That's what I'm expecting to do with RegExp patterns.

Furthermore, I'll have to test but it seems that `controller.hears(['Apple', 'Orange'], ...` is slower than `controller.hears(['(Apple|Orange)']` that would make less `for` loops in the lookup code.

Best

**Comment by guillaumepotier** [comment]
Good news, #39 have been merged, you could now really use `message.match` object (generally `message.match[1]` when only one capturing group) inside the response to see what triggered it :)

Best

**Comment by benbrown** [comment]
Pretty cool!
We should consider cleaning up that object to make it easier to use.

**Comment by LAMike310** [comment]
Thanks for the tips @guillaumepotier I'll definitely be using the message.match object for my next bot!

**Comment by RafaelCosman** [comment]
@LAMike310 let us know if you have any other questions about this.

Should we close the issue?
