### ISSUE TITLE
how we can enter state field with value in dialog box of slack

### ISSUE THREAD

**Issue by ruchikam** [howdyai/botkit#1500]

**Comment by ruchikam** [comment]
![botkit slack](https://user-images.githubusercontent.com/34738835/47715994-5f18c080-dc67-11e8-93f4-fdb8d04ba24a.png)

**Comment by benbrown** [comment]
When you construct your dialog object and call api.dialogs.open, include the state field. Botkit has no special methods for doing this.

If you use bot.createDialog, you can amend the resulting object:

```
const dialog = bot.createDialog(title, callback_id, submit_label, elements);
dialog.state = 'foo';
bot.replyWithDialog(message, dialog); 
```

**Comment by ruchikam** [comment]
> When you construct your dialog object and call api.dialogs.open, include the state field. Botkit has no special methods for doing this.
> 
> If you use bot.createDialog, you can amend the resulting object:
> 
> ```
> const dialog = bot.createDialog(title, callback_id, submit_label, elements);
> dialog.state = 'foo';
> bot.replyWithDialog(message, dialog); 
> ```
