### ISSUE TITLE
Find conversation triggering twice

### ISSUE THREAD

**Issue by adantoscano** [howdyai/botkit#1502]
I've just realice that I always get this log

```bash
debug: CUSTOM FIND CONVO 821bf6c7-7a67-8840-77a0-f0dba48cb170 socket
debug: FOUND EXISTING CONVO!
debug: RECEIVED MESSAGE
debug: CUSTOM FIND CONVO 821bf6c7-7a67-8840-77a0-f0dba48cb170 socket
debug: FOUND EXISTING CONVO!
```

because it's triggered in [Core](https://github.com/howdyai/botkit/blob/b6dfcf38233590043a27e316c3c7f7f5e632788e/lib/CoreBot.js#L145) and in [Web](https://github.com/howdyai/botkit/blob/b6dfcf38233590043a27e316c3c7f7f5e632788e/lib/Web.js#L90)

I did not try with other connector but has it sense?

**Comment by benbrown** [comment]
Aren't you using findConversation for some other task, like in a middleware or something?

**Comment by adantoscano** [comment]
nope, also I tried with web starter pack and same happens

**Comment by benbrown** [comment]
This is related to #1503 - one of the changes in 0.6.19 causes these events to fire improperly.

**Comment by benbrown** [comment]
0.6.20 just hit npm! Let me know if you have any further issues.
