### ISSUE TITLE
"An error occurred in the receive middleware"

### ISSUE THREAD

**Issue by mhjb** [howdyai/botkit#1503]
botkit version: 0.6.19
os: mac os x mojave

Hi folks

Context: I've just updated to the latest botkit in my project. I had been using [this middleware](https://github.com/mrbot-ai/botkit-middleware-fbuser) to get Facebook user's names so that I could use them in replies. The latest botkit update made that middleware stop working. As the middleware hasn't been substantially updated for a year, and I'd got the impression from #1100 that I might be able to do that without extra middleware, I pulled that middleware out. 

Now I'm seeing this error

```
An error occurred in the receive middleware:  TypeError: Cannot read property 'user' of undefined
at <<PATH TO MY BOT>>/node_modules/botkit/lib/Studio.js:832:35
at <<PATH TO MY BOT>>/node_modules/botkit/lib/CoreBot.js:1409:56
at next (<<PATH TO MY BOT>>/node_modules/ware/lib/index.js:82:27)
at Ware.run (<<PATH TO MY BOT>>/node_modules/ware/lib/index.js:88:3)
at Object.Botkit.botkit.trigger (<<PATH TO MY BOT>>/node_modules/botkit/lib/CoreBot.js:1407:45)
at <<PATH TO MY BOT>>/node_modules/botkit/lib/CoreBot.js:1349:36
at next (<<PATH TO MY BOT>>/node_modules/ware/lib/index.js:82:27)
<<etc etc>>
```
… and I can't from the error message, or from lots of `console.log`s, find what bit of my code is causing the problem. 

Any ideas?

**Comment by benbrown** [comment]
This was a problem introduced in 0.6.19. It will be resolved in 0.6.20!

**Comment by mhjb** [comment]
Beautiful :)

**Comment by benbrown** [comment]
0.6.20 just hit npm! Let me know if you have any further issues.
