### ISSUE TITLE
Cluster module?

### ISSUE THREAD

**Issue by emhagman** [howdyai/botkit#1504]
Does anyone have experience using the `cluster` module with botkit? I was just wondering if it was easy to setup or if it was even possible?

Is it as simple as forking the `setupWebserver`?

**Comment by benbrown** [comment]
It is more complicated -- if you use Botkit conversations, all of the conversation state information is stored in the memory of the process.  With cluster, messages might arrive at a different node than the conversation started in, thus confusing the bot.

**Comment by emhagman** [comment]
I understand that, however, if I do not maintain active conversations with users, could I in theory do this? I do not use any conversational flow and rely on single commands and dialogs.

**Comment by benbrown** [comment]
Then yes, it should work!
Let me know how that goes.
