### ISSUE TITLE
[Facebook]Promisify APIs

### ISSUE THREAD

**Issue by ouadie-lahdioui** [howdyai/botkit#1518]
Hello 👋 

Some Facebook APIs need to be Promisified in order to to support Promises in addition to callbacks.

Her's the list of APIs that not yet promisified
- [ ] attachment_upload_api
- [ ] nlp
- [ ] tags
- [ ] handover
- [ ] broadcast_api
- [ ] insights_api

And her's those already promisified :
- [x] messenger_profile_api
- [x] user_profile

Good luck!

**Comment by htaidirt** [comment]
I'm on it @ouadie-lahdioui, if you don't mind.

**Comment by htaidirt** [comment]
@ouadie-lahdioui I've made the necessary changes. Should I also create the related specs? What's the agreement when it comes to testing?

**Comment by ouadie-lahdioui** [comment]
You need to make a new PR to the project.

**Comment by htaidirt** [comment]
Done 👍 https://github.com/howdyai/botkit/pull/1520

**Comment by htaidirt** [comment]
Hi @ouadie-lahdioui,

I'm looking at the docs, and thinking about updating them with my recent changes. But I can't figure out where I should make these changes. Probably there is another repo?

Can you please point out where I can document the promise version of the edited methods?

Thanks

**Comment by ouadie-lahdioui** [comment]
Awesome!

Her's the [new documentation repository](https://github.com/howdyai/botkit-docs).
