### ISSUE TITLE
Can't get API key from settings tab

### ISSUE THREAD

**Issue by vindicokimber** [howdyai/botkit#1519]

**Comment by vindicokimber** [comment]
Can someone help me out I like bot kit but for some reason can't access my api key to make my bot awesome

**Comment by vindicokimber** [comment]
![image](https://user-images.githubusercontent.com/29656587/48715674-71a26c00-ec0d-11e8-8b98-4d894409f0c4.png)

**Comment by peterswimm** [comment]
See https://blog.howdy.ai/xoxco-to-join-microsoft-ad128e5ed6e7
