### ISSUE TITLE
Jabber botkit username

### ISSUE THREAD

**Issue by Ooverandout** [howdyai/botkit#1521]
Hey,

I have been trying to get the username of the person that is sending a message. However, the only thing I am left with is message.user.
In my case my name is Adam Mrozik. Message.user is admrozik@dbschenker.com. I really need name and surname in the original form. Do you have any suggestions how I can retrieve it?

**Comment by Naktibalda** [comment]
I haven't used JabberBot, but I looked at the code and it looks like there should be more data in `message.stanza`, it is up to you to investigate what data is there.

**Comment by Naktibalda** [comment]
Please put your text between ` ``` ` and ` ``` `

**Comment by Naktibalda** [comment]
So it isn't there.
You could read Jabber documentation or ask some Jabber community.
@panx981389 have you got any ideas?
