### ISSUE TITLE
Incorrect declaration causes `match` variable to be added to global scope

### ISSUE THREAD

**Issue by LukeBaulch** [howdyai/botkit#1525]
https://github.com/howdyai/botkit/blob/02258337a84aef2dfe81a9158cdb17562bd81451/lib/CoreBot.js#L1295

Simple fix, declare variable on previous line with `let` or `var`.

**Comment by Naktibalda** [comment]
Please make a pull request.

**Comment by benbrown** [comment]
fixed https://github.com/howdyai/botkit/pull/1527
