### ISSUE TITLE
All documentation refers to the no longer available botkit studio

### ISSUE THREAD

**Issue by LukeusMaximus** [howdyai/botkit#1526]
For whatever reason, Botkit studio is no longer accepting signups (https://studio.botkit.ai/signup). This makes this toolkit very hard to use as most guides depend to some degree on users being able to use that platform, despite repeated claims that the platform's use is optional.

**Comment by casz** [comment]
https://blog.howdy.ai/xoxco-to-join-microsoft-ad128e5ed6e7 should clear things up

**Comment by peterswimm** [comment]
Most of the Starter kits (with the exception of the Web starter) should happily work without a Studio Api connection. There are a few skills in the later that require Studio, but if you delete them the bot should function as normal.

**Comment by shawnr42** [comment]
Neither of you actually provided any useful information.

For example, this guide for getting started references Botkit Studio in the video, and the second step. How do I go to step 3 if I can't finish step 2?

I guess the right question to ask is either of these.

1.) When will botkit studio be revived?
or
2.) When is the documentation going to be fixed?
