### ISSUE TITLE
Utterances should contain emoji

### ISSUE THREAD

**Issue by samhavens** [howdyai/botkit#153]
I know this seems stupid, bot since botkit's default way of communicating contains many emoji, it is natural to respond in kind. As such, it makes sense to extend `botkit.utterances.yes` to include :+1: and :ok_hand: , and similar for no.

**Comment by anonrig** [comment]
These emojis changes from country to country. For example: http://www.ethos3.com/2014/07/dont-give-a-thumbs-up-in-russia-and-other-hand-gesture-facts/
