### ISSUE TITLE
Facebook Handover 

### ISSUE THREAD

**Issue by MagSag** [howdyai/botkit#1530]
Is handover only for 2 apps(chatbots) or I can also pass a thread from my chatbot to the facebook page inbox?

If I can what, How can I do that? I tried doing it this way : 

```
 controller.api.handover.pass_thread_control(currentUser.id, '263902037438966', 'User\'s request', function (result) {
                                        // result = {"success":true}
                                        console.log("Passed successfully.");
                                     }); 
```
but it failed so I wonder iwhat I am missing.

**Comment by ouadie-lahdioui** [comment]
Hi @MagSag,

Handover protocol API enables two or more fb apps to participate in a conversation by passing control of the conversation between them.

You can also pass control of the conversation to the page inbox by enabling live chat and assigning a secondary receiver role to your page inbox. Here's a step-by-step [doc](https://developers.facebook.com/docs/messenger-platform/handover-protocol/pass-thread-control#page_inbox).

then you can use Botkit :

- To take thread control:
```javascript
controller.api.handover.take_thread_control('<RECIPIENT_PSID>', 'String to pass to pass to the secondary receiver', function (result) {
   // result = {"success":true}
});
```
- To pass thread control:
```javascript
controller.api.handover.pass_thread_control('<RECIPIENT_PSID>', '<TARGET_PSID>', 'String to pass to the secondary receiver app', function (result) {
   // result = {"success":true}
});
```

Let me know if that helps!

**Comment by benbrown** [comment]
@MagSag I'm going to close this issue since Ouadie answered. 

Feel free to re-open if you have further questions on this topic.
