### ISSUE TITLE
Reply with image

### ISSUE THREAD

**Issue by sajidbsk** [howdyai/botkit#1531]
Looking through the documentations, there isn't any obvious way of making the bot reply with an image output from local. I was looking for a way for the `convo.says()` or `bot.reply` to have a way to easily reply with a picture to the user. (For future reference having a way to reply with an interactive web object would be nice)

**Comment by ouadie-lahdioui** [comment]
Hi @sajidbsk,

which platform you use ?

**Comment by ihorrusinko** [comment]
hey @sajidbsk i think you can can try `bot.api.callAPI('files.upload'` it supports `multi-part`.

example of that implementation from core https://github.com/howdyai/botkit/blob/1967ae95024175b1bc4f7188124bc1e423984655/lib/Slack_web_api.js#L152-L163

your code could be
```javascript
bot.api.callAPI('files.upload', payload, ()=> convo.say('File uploaded'), multipart);
```
