### ISSUE TITLE
Botkit ENOTFOUND when on AWS Linux

### ISSUE THREAD

**Issue by Ooverandout** [howdyai/botkit#1532]
Hi, I was using my botkit on my local computer and has been able to connect to the jabber work server just fine. When deployed on external AWS though, it fails to connect with ENOTFOUND error. 
I suspect it may be some kind of proxy/firewall issue?
Is there a work around for this?

**Comment by benbrown** [comment]
It should work on AWS. You might need to adjust the port being used or some other setting pertaining to reaching the outside world from your instance.
