### ISSUE TITLE
Google Hangouts Chat: auth on Heroku/Dokku nodes etc

### ISSUE THREAD

**Issue by bobman38** [howdyai/botkit#1533]
Hello

I am testing BotKit with the Google Hangouts Chat Bot, and it working really well locally ! Good job ! (https://github.com/howdyai/botkit-starter-googlehangouts)

I am planning to deploy it on a Dokku/Heroku instance and I am hitting a wall:

I need to set to set the environment variable ``GOOGLE_APPLICATION_CREDENTIALS`` as a link to the google json auth file (like auth.json) but I don't want to put this file on git so I can't push it to Dokku.

[The solution proposed by Google](https://github.com/googleapis/google-auth-library-nodejs/blob/master/README.md#loading-credentials-from-environment-variables) seems pretty easy to implement buy I don't know how to do this in my BotKit :)

Here is my code for another project using Google Hangouts Bot auth that is working well with that:

```
// load the environment variable with our keys
const creds = process.env.CREDS
if (!creds) {
  throw new Error('The $CREDS environment variable was not found!');
}
const keys = JSON.parse(creds)
const client = auth.fromJSON(keys)
client.scopes = ['https://www.googleapis.com/auth/chat.bot']

module.exports = google.chat({
  version: 'v1',
  auth: client
});
```

Do you have an idea ?

Thanks !

**Comment by bobman38** [comment]
Hello

I have created a pull request that allow this behavior : #1543 

Thanks !

**Comment by ouadie-lahdioui** [comment]
Hi @bobman38, i'll take a look asap.

Thank you ;)

**Comment by benbrown** [comment]
This will be in the next published version of Botkit.
