### ISSUE TITLE
Calling API using Botkit

### ISSUE THREAD

**Issue by refai2016** [howdyai/botkit#1535]
Hi,
I am new to Botkit and I am trying to run a third-party API (e.g. weather API), so for example, if I am asking the BOT "What is the temperature in London right now", I expect to get an answer like "It's 6 Celsius"
I have to mention that it's running locally with no issues.

Can you help, please?

**Comment by benbrown** [comment]
Not sure what help you need! You can call whatever API you want from within your Botkit handlers.

**Comment by adantoscano** [comment]
```js
controller.hears('wheather', 'message_received', (bot, message)  => {
  axios(<API_REQ>)
    .then((respponse) => {
       bot.reply(message, `The wheather is ${response.body}`)
  })
})
```

**Comment by benbrown** [comment]
This looks roughly correct.  What is your issue?

**Comment by refai2016** [comment]
What is not clear for me, is how to access the API features from within the Botkit Studio?

**Comment by benbrown** [comment]
@refai2016 A few things:

* Botkit Studio will cease operation in February.  You should transition your bot ASAP to using [botkit-cms](https://github.com/howdyai/botkit-cms)

* There is no way to directly use external APIs from within the Botkit dialog editor UI. What you CAN do is create variables that are referenced within your scripts, using tokens like {{vars.<varname>}}.   

Docs for using variables in conversations are here: 
https://botkit.ai/docs/core.html#using-variable-tokens-and-templates-in-conversation-threads

Docs for hooking into the execution of scripted dialogs (from studio or cms) are here:
https://botkit.ai/docs/readme-studio.html#controllerstudiobefore

**Comment by refai2016** [comment]
@benbrown @adantoscano Thank you for your response.
