### ISSUE TITLE
how access botkit server from curl command

### ISSUE THREAD

**Issue by 9Khaled9** [howdyai/botkit#1538]
Hi dear,
i installed botkit on my local machine and integrated it with rasa nlu.
Now, i need to talk with botkit from my own api, or from curl command... so what is the command and the url should i use to send message to botkit from command line???

**Comment by benbrown** [comment]
By default, Botkit runs a webserver at http://localhost:3000/

**Comment by 9Khaled9** [comment]
dear @benbrown, i ment that i need to pass my message in the url, near the "localhost:3000"...
in other words, i need to pass my message as a parameter in the url, like: "http:localhost:3000?q=hello"

**Comment by 9Khaled9** [comment]
please do not close the issue...

**Comment by adantoscano** [comment]
@9Khaled9 Maybe [this is helpful](https://github.com/howdyai/botkit-starter-web/blob/master/docs/botkit_chat_server.md#using-webhooks) for you. If you explicitly need a GET query, feel free to [change this route](https://github.com/howdyai/botkit-starter-web/blob/master/components/routes/incoming_webhooks.js)
