### ISSUE TITLE
An error occurred in the categorize middleware:  Error: Can't set headers after they are sent.

### ISSUE THREAD

**Issue by justinemar** [howdyai/botkit#1541]
I'm receiving the above error if i use `bot.replyPrivate` on `interactive_message_callback`

`botkit @^0.6.21`

```
controller.on('interactive_message_callback', function(bot, message) {
     // ....Check for the selected option 
    var nonInteractiveResponse = {...}
    bot.replyPrivate(message, nonInteractiveResponse)  // An error occurred in the categorize middleware
}) 
```

Also is there anyway to use slash command without needing a `store`?

**Comment by justinemar** [comment]
`bot.sendEphemeral` is what i needed. But i will be happy for some answer regarding the use of `store` when using slash commands

**Comment by benbrown** [comment]
There is not currently a way to use slash commands without using a full Slack app that utilizes oauth.  This may change in an upcoming version.
