### ISSUE TITLE
clarification about conversation dialogue

### ISSUE THREAD

**Issue by valeadami** [howdyai/botkit#1542]
Hi everybody, I am new to Botkit and I am trying to figure out how it manages conversation dialogue.
Working on the console_bot.js exemple.

I see that convo.status is set to completed everytime there 's an interaction between bot and user.
The point is: is there a way to keep the dialogue alive? My user need to perform  a task which requires connecting to a remote web service, get the list of items, select one and book one of them. I thought the conversation was open until the end of the session... I am missing something. Anyway, what's the best practise to structure a dialogue which requires multiple steps? IT seems strange to me that this should be done in a single hears()...
Do I have to setup multiple controller.hear() to catch the user's input or is there a way to define a dialogue with threads?

This is the actual code:

ontroller.hears("hello", 'message_received', function(bot, message) {

           /* onboarding */
           bot.reply(message, resInBoarding); //resInBoarding is a welcome message

           bot.createConversation(message, (err, convo) => {
            // DEFINISCO I THREAD
            convo.addMessage({text: resLogin},'prenotazione_thread');
            convo.addMessage({text: resLogin},'libretto_thread');
            convo.addMessage({text: resLogin},'esito_thread');
            convo.addMessage({text: resInBoarding},'default');
            convo.addMessage({text: respGuida},'help_thread');
            convo.addMessage({text: respUndo},'undo_thread');
            convo.addMessage({text: respFallback},'fallback_thread');
            convo.addMessage({text: respUscita},'stop_thread');
            convo.addMessage({text:resMenu}, 'menu_thread');
         
           // Create a yes/no question in the default thread...
           convo.addQuestion(questMenu, [

                {
                    pattern: 'prenotazione',
                    callback: function(response, convo) {
                        convo.gotoThread('prenotazione_thread');
                        convo.next();
                    },
                },
                {
                    pattern: 'libretto',
                    callback: function(response, convo) {
                        convo.gotoThread('libretto_thread');
                        convo.next();
                    },
                },
                {
                    pattern: 'esito',
                    callback: function(response, convo) {
                        convo.gotoThread('esito_thread');
                        convo.next();
                    },
                },
               {
                   pattern: 'help',
                   callback: function(response, convo) {
                       convo.gotoThread('help_thread');
                       convo.next();
                   },
               },
               {
                   pattern: 'annulla',
                   callback: function(response, convo) {
                       convo.gotoThread('default');
                       convo.next();
                   },
               },
               {
                pattern: 'stop',
                callback: function(response, convo) {
                    convo.gotoThread('stop_thread');
                    convo.next();
                    },
                },
                {
                    pattern: 'menu',
                    callback: function(response, convo) {
                        convo.gotoThread('menu_thread');
                        convo.next();
                        },
                    },
               {
                   default: true,
                   callback: function(response, convo) {
                       convo.gotoThread('fallback_thread');
                       convo.next();
                   },
               }
           ],{'key': 'scelta'},'default');
          // convo.addMessage('ciao dal default', 'default');
           convo.activate();
           //this is the booking thread -> start process ...
           //ask for username
           convo.addQuestion({text: questPrenUsername}, [
            {
                pattern: 's[0-9]', //pattern
                callback: function(response, convo) {
                   
                       convo.next();
  
                }
            }],{'key': 'username'},'prenotazione_thread');

            //ask for password 
            convo.addQuestion('Your password?', [
                {
                    pattern: '[0-9]', //pattern
                    callback: function(response, convo) {
                       
                           convo.next();
        
                    }
                }],{'key': 'password'},'prenotazione_thread');

            convo.addMessage('this is the menu', 'menu_thread')

           convo.on('end', function(convo){
             //convo. 
               var res=convo.extractResponses();
               console.log('this isthe end and your username ' + res.username );
//do the api call and get the result.... but now how to move from here?
           convo.reply('this is the result of your query', output)
          //   convo.goToThread('default');
           // convo.next();   
           });
        });
    
});

**Comment by adantoscano** [comment]
A conversation should be about only a topic, so in example, controller.hears('hello') may create a onboarding convo with your greeting message and then questMenu(as a message, not a question) and then a controller hears for each thing your bot can do, help, menu, booking and so on

**Comment by valeadami** [comment]
thanks  @adantoscano for the very quick reply, so, if i got it right, I have to divide my main task (booking) into multiple steps, each mapped to a different "hears"... but I do need to ask information from user, login, which item to book, etc...how do I hear to a variety of items? If you could link me to a a complex dialogue example that would be great! ;) Thanks in advance

**Comment by adantoscano** [comment]
Nope, booking should be a convo but i think you don't need a menu, help, stop and so on inside booking.
So the main task of ur bot is manage bookings so give help info is a task, do a book other, cancel a book other, give the menu(if don't get any intent) other and so on.

btw [here is the convo docs](https://www.botkit.ai/docs/core.html#multi-message-conversations) with good exsamples

**Comment by valeadami** [comment]
ok, thanks again @adantoscano :)
