### ISSUE TITLE
Not an issue, just an info and thanks

### ISSUE THREAD

**Issue by guillain** [howdyai/botkit#1550]
Hi,

Just I would like to thank you and let you that I work on project that used your Botkit (and got one Sticker 💃 )
The project is to propose an upper layer of your Botkit that will take into account all configuration to create scenario easily (as puzzle) and be compatible accross the current Business Messaging supported.

So thanks **again** and have fun :-)
Guillain

**Comment by benbrown** [comment]
Drop a link to your project!
