### ISSUE TITLE
Typescript definition for SlackMessage does not include `team` field for interactive messages

### ISSUE THREAD

**Issue by wolfejw86** [howdyai/botkit#1554]
Steps to reproduce:
- setup a bot that allows user to post an interactive_message
- inspect the `reply: SlackMessage`
- notice it has the `reply.team` field populated
- notice the ts definition file does not have `SlackMessage['team']`

Expected:
include `team` field on `SlackMessage` as shown in the [slack API docs](https://api.slack.com/interactive-messages#checking_the_action_type)
 

### Screenshots and animated GIFs
![image](https://user-images.githubusercontent.com/22133869/50529431-be0d8100-0ac2-11e9-8251-862485244653.png)

### Context:

- Botkit version:  0.7.0
- Messaging Platform: Slack
- Node version:  10.4
- Os: macos
- Any other relevant information:

I'm happy to add it, but i wanted to post first and see if there was a specific reason why the team field wasn't on it before just adding it.  Thanks!

**Comment by benbrown** [comment]
No reason - please send a PR! Thanks

**Comment by wolfejw86** [comment]
working on larger typefile improvements. will postback if i come up with something useful 😄
