### ISSUE TITLE
bot.say with html

### ISSUE THREAD

**Issue by Ooverandout** [howdyai/botkit#1559]
Hi!

In the bot.reply function we can use html forms succesfully. My goal was for bot though to initiate conversation himself based on some e-mail trigger - this part has been done.

However, I would like to send to the user an html form in the same manner as I do it with other messages by using reply_message.stanza

````
	bot.say(
  {
    text: HERE I WANT TO PUT MY HTML FORM
    user: "admrozik@dbschenker.com"
  })

````
Is there any way to achieve it?

**Comment by benbrown** [comment]
Are you using the botkit anywhere web chat?  If so, it would theoretically be possible to render the form in the UI.   There is no built in mechanism for this.

**Comment by Ooverandout** [comment]
Unfortunately this is only a jabber bot :(

**Comment by panx981389** [comment]
Please try to create a message statza just like in reply. And use it in bot.say.

**Comment by Ooverandout** [comment]
unfortunately does not work, or I do it wrong. code is:
`````````````
let reply_message = {};
let to = "admrozik@dbschenker.com";
let type = 'chat';
let body = 'robot-button demo(only for Jabber Windows)';
reply_message.text = body;
reply_message.stanza = xml`<message to="${to}" type="${type}">
											<body>${body}</body>
											<html xmlns="http://jabber.org/protocol/xhtml-im">
												<body xmlns="http://www.w3.org/1999/xhtml">
													<div class="container">
														<h6>${body}</h6>
														<button class="btn btn-primary btn-sm center-block" style="margin-top:8px;" robot-type="robot-button" type="button" robot-message="help">Send back help message</button>
														<button class="btn btn-primary btn-sm center-block" style="margin-top:8px;" robot-type="robot-button" type="button" robot-message="help">Send back help message</button>
													</div>
												</body>
											</html>
										</message>`;

bot.say(
  {
    text: reply_message,
    user: "admrozik@dbschenker.com"
  })

``````````````
but jabber answer is: [object Object]

**Comment by panx981389** [comment]
try this  
bot.say(reply_message);

**Comment by Ooverandout** [comment]
Unfortunately it does not say anything at all :(
