### ISSUE TITLE
No way to get message meta from RTM send?

### ISSUE THREAD

**Issue by dclowd9901** [howdyai/botkit#156]
I want to be able to update a message after sending it using the api, but the api requires a precision time stamp and channel to update the message. As far as I can tell, the only instance in which we get usable metadata from botkit is when slackbot "hears" an incoming message. So if slackbot posts a message, that metadata is not retrieved, and that message cannot be updated. Am I missing something?

**Comment by dclowd9901** [comment]
Even when digging deep into the bowels of Slackbot_worker.js to line 254, and console logging out the arguments, the arguments object appears to be completely empty if the request is good. Is this a shortcoming of websockets/rtm?

**Comment by peterswimm** [comment]
Fixed in https://github.com/howdyai/botkit/pull/344
