### ISSUE TITLE
Is it possible to mix send/receive midldleware with NLP and hears middleware?

### ISSUE THREAD

**Issue by valeadami** [howdyai/botkit#1561]
Hi guys,
I am testing Dialogflow-fulfillment library integration in my console chatbot application. ("botkit-middleware-dialogflow": "^2.0.4",)
I registered the send and receive middleware as follows:

```
controller.middleware.receive.use(dialogflowMiddleware.receive);
controller.middleware.send.use(dialogflowMiddleware.use);
```
I also setup the DF middleware like this:
```
const dialogflowMiddleware = require('botkit-middleware-dialogflow')({
    keyFilename: './myagentFile.json',
    ignoreType: ['yes','no','hello'] 
  });
```

So, if i type 'hello', the convo is managed by a callback, and that's fine, but answering  'yes' inside a conversation triggers the  'default fallback intent''s agent...it's not what I expected. 
Is it possible to mix the two ways to listen to user input?
This is the code:
```
controller.hears( 'hello', 'message_received', function (bot, message) {
//start convo here
    bot.createConversation(message, (err, convo) => {
    
      //THREADS
      convo.addMessage({ text: myConvo.respLogin }, 'login_thread');
      convo.addMessage({ text: myConvo.botOnBoarding.respOnBoarding }, 'default');
      convo.addMessage({ text: myConvo.respMenu }, 'menu_thread');
    
 
   
      // Create a yes/no question in the default thread...

      convo.addQuestion(myConvo.botQuestions.questLogin, [

          {
              pattern: 'yes', //-->  IT GOES OUT TO DIALOGFLOW... WHY??
              callback: function (response, convo) {
                  convo.gotoThread('login_thread');
                  convo.next();
              },
          },
          {
              pattern: 'no',
              callback: function (response, convo) {
                  convo.gotoThread('stop_thread');
                  convo.next();
              },
          },
         
          {
              default: true,
              callback: function (response, convo) {
                 // convo.gotoThread('default_thread');
                  convo.repeat();
                  convo.next();
              },
          }
      ], { 'key': 'choice' }, 'default');
     convo.activate();
.
.
.
```
Thanks a lot
Bye

**Comment by benbrown** [comment]
In the code you included, you have not included the `hears middleware` which will cause your bot to hear the "hello" intent.

See here:
https://github.com/jschnurr/botkit-middleware-dialogflow#hears

**Comment by benbrown** [comment]
You are not using ignoreType correctly. This allows you to ignore certain TYPES of messages, based on message.type, not on message.text.

I'm not sure how you would bypass the dialogflow default intent and let Botkit handle messages. the dialogflow middleware will come into play BEFORE the botkit dialog system receives the message.

**Comment by valeadami** [comment]
Thanks @benbrown ! Ok, so, if I got it right, either you go for DialogFlow, or you go for your own intent resolution...
What about configuring the desired middleware according to a condition, for example:
```
if (condition){
controller.middleware.receive.use(dialogflowMiddleware.receive);
controller.middleware.send.use(dialogflowMiddleware.use);
else
...//a different middleware
 }
```

**Comment by benbrown** [comment]
Not sure what that condition would be, but once bound, those middleware are bound for everything.

You might be able to achieve what you want by NOT defining a fallback intent in Dialogflow?

**Comment by benbrown** [comment]
Actually @valeadami after reading through the code of botkit-middleware-dialogflow, I'm not sure what is happening for you.

The `dialogFlowMiddleware.receive` middleware calls Dialogflow, then amends the message with new fields like message.intent, etc.  This message then passes on to Botkit.

In order to "hear" that intent and fire a trigger, you have to use the `dialogflowMiddleware.hears` method in defining your hears handlers. This tells botkit to match the pattern against the intent instead of the message text.

Once inside the handler, you can do whatever type of Botkit conversation or reply you want.  Once inside a conversation using conditionals like you've shown in your first code example, DialogFlow will have no effect.   Yes, it will continue to be called.  However, it shouldn't change the way your bot behaves. 

I'm not sure what you mean when you say that it triggers the "'default fallback intent''s agent"

**Comment by valeadami** [comment]
Ok, got the point, once a middleware is bound, is bound for good, no way to switch on/off (unless you start the application again, I suppose).
If a delete the fallback intent, I fear the response won't come back at all ...but  I'll have a try! :)
thanks again

**Comment by benbrown** [comment]
@valeadami join us at community.botkit.ai and i can help you more :)

**Comment by valeadami** [comment]
@benbrown done! ;)

**Comment by valeadami** [comment]
It is possible to mix both middleware, checked that the conversation is managed by the callback after user types 'yes'/'no' and user is than directed to another thread. I could see no text because of a variable set to null. Thanks again  @benbrown for your precious help, I really appreciated it!
