### ISSUE TITLE
PREVIEW: Botkit #NEXT

### ISSUE THREAD

**Issue by benbrown** [howdyai/botkit#1563]
For those interested in following along (and contributing to) the next major release of Botkit, I've just published it on a separate branch:

https://github.com/howdyai/botkit/tree/next

This is a complete rewrite and reorganization of Botkit.  [Details about our goals and approach are here](https://github.com/howdyai/botkit/tree/next#botkit-next-major-release).

**Comment by casz** [comment]
The second link goes nowhere :grin:

**Comment by benbrown** [comment]
@casz it goes to the readme where I've listed some of the goals!

**Comment by casz** [comment]
Looks extremely promising 😍 Very much looking forward to a more modern syntax.
Could you perhaps spend some time creating issues and labeling them so we pick some open issues and further progress botkit 😊

**Comment by benbrown** [comment]
@casz absolutely! that is next on my list, probably this week!

**Comment by wolfejw86** [comment]
this looks like some really solid work.  is there information somewhere about the move away from dynamically generated conversations? I was looking at this aspect of botkit as a feature, not something to move away from.  I'm sure there are reasons, i was just wondering if they're documented somewhere or in general are a bad practice?

**Comment by benbrown** [comment]
@wolfejw86 good question! 

I think it is important to note that you will still be able to have "dynamic" conversations, where the user is directed through a series of messages and branching points.   It will also still be possible to send dynamic "generated" messages at points in the conversation.  But what you will not be able to do is modify the structure of the conversation once activated as is currently possible.

In the current version of Botkit, it is possible to call convo.ask and convo.say from _within the callback_ of a convo.ask call, thus creating new branches ad hoc.  As a result, it is impossible for Botkit to reliably track a user's state through a conversation and  store / restore that state. This makes it tricky to manage multiple nodes of the same app in a load balanced situation, and impossible to restore state between reboots of the app.

**Comment by wolfejw86** [comment]
thanks for that response, sounds good.
one more question for now when you have time 😄 
in order to use the multi-platform aspects of botkit, will creating a microsoft appid and secret to use the botframework connector functionality in azure become a dependency of using botkit on other platforms? or will you still be able to connect to other platforms without registering a bot in azure / using this azure service as a dependency?

**Comment by pgoldweic** [comment]
Good question @wolfejw86 . I've also been meaning to ask the same. If such a dependency is required, it would of course mean that you won't be able to use the open source code base for free anymore (unless I'm misunderstanding this).

**Comment by benbrown** [comment]
@wolfejw86 @pgoldweic good question!

The answer is no, you will not be required to register with Bot Framework to use Botkit or the adapters built to communicate directly with the platforms (like the Slack and Webex adapters already in the repo).  

Of course, if you do want to use the channel services that Bot Framework/Azure supply, you will need to register - this is the case today, and will continue to be the case.

**Comment by pgoldweic** [comment]
Great! Thanks for clarifying this.

**Comment by wolfejw86** [comment]
ah awesome! once again, thank you for the response!

**Comment by benbrown** [comment]
This is so not stale!! It is SUPA FRESH.

**Comment by Peter-Barrett** [comment]
@benbrown thanks for all of the work on this! We're considering using BotKit in a project soon, what's the ETA on this rewrite?

**Comment by benbrown** [comment]
@Peter-Barrett early next month.  It is now on npm as the @preview tag, you can install it and start using it now:

```
npm install -g yo generator-botkit@preview
yo botkit
```

The new docs are here:
https://botkit.ai/docs/v4

**Comment by adantoscano** [comment]
@benbrown I tried `yo botkit` to create web bot and when I start, it shows the message: 
```
Enabling plugin:  Web Adapter
Loading sample web features...
```
And localhost:3000 shows `Cannot GET /`

**Comment by benbrown** [comment]
@adantoscano good catch - right now, it defaults to /chat.html but it probably should serve up on the index page.  Thanks for the report.

**Comment by benbrown** [comment]
This version has been published!!

**Comment by Oxicode** [comment]
> @adantoscano good catch - right now, it defaults to /chat.html but it probably should serve up on the index page. Thanks for the report.

not working /chat.html
