### ISSUE TITLE
"w" in html is not working (!)

### ISSUE THREAD

**Issue by Ooverandout** [howdyai/botkit#1564]
Hi,

I am using jabber botkit to create html forms to gather some information from users. The weirdest thing is that when typing in the input field, the "w" key is not working! You can paste it in there, but clicking it will not present any output for this letter. 
This is the weirdest bug I have ever experienced. And it is true even for example botkit html forms.

Does anyone know what could be the reason?

**Comment by benbrown** [comment]
If this is happening inside the Jabber client, it is highly unlikely this has anything to do with Botkit.

@qiongfangzhang any thoughts?

**Comment by someonelikeTIM** [comment]
Just want to mention that this was a Cisco bug and was fixed in Jabber v12.6.2

**Comment by benbrown** [comment]
thanks for the follow up!
