### ISSUE TITLE
Timeout issue in Slack RTM API using botkit

### ISSUE THREAD

**Issue by harshilt94** [howdyai/botkit#1578]
I have deployed a bot on slack channel using botkit framework. What happens is after some amount of uncertain time, the session between the bot server and slack channel is timed out and then further conversation fails to happen. Please help me solving this.

I have used the below code to establish a connection between bot server and slack channel.

```
var Botkit = require('botkit');
var bot_controller = Botkit.slackbot();
bot_controller.spawn({
      token: slack_token 
}).startRTM();	
```

**Comment by benbrown** [comment]
Yes, the RTM socket connection will from time to time fail.  You will need to monitor this and reconnect.

I would highly recommend moving to the EventsAPI which uses web hooks instead and does not suffer this issue.
