### ISSUE TITLE
Jabber robot-button not displaying in cisco-jabber 12.5

### ISSUE THREAD

**Issue by anupam99** [howdyai/botkit#1581]
using botkit, I could get my html5 content and robot-button to work on Jabber for windows 12.1. 
However , same setup when connecting to jabber windows 12.5, does not display the robot-buttons.
Has something changed in V12.5 by way of robot-button support?

Jabber Version : 12.5.0.22884 Build 272884

**Comment by anupam99** [comment]
I got a response on devnet. They say it could be due to the recent move to chromium as webview component in 12.5 and the engineering team is investigating.

**Comment by meixuemin** [comment]
There is a design change. Bot need be whitelisted in jabber config file to make the robot-button work. 

AdminConfiguredBot
Applies to Cisco Jabber desktop, iPhone, and iPad clients.
Automatically adds bots to users' contacts list in Jabber, using the Jabber ID assigned to the bot in the company directory. A group _BotGroup is created in the users' contacts list. Your users can also add bots manually to their contacts lists.
Example:
<AdminConfiguredBot>bot1@example.com;bot2@example.com;bot3@example.com</AdminConfiguredBot>

**Comment by anupam99** [comment]
Googled around your suggestion..and found a tag specification for whitelistbot, which clearly states robot-type works only for whitelisted bots.
[link to cisco doc here ](https://www.cisco.com/c/en/us/td/docs/voice_ip_comm/jabber/12_1/cjab_b_parameters-reference-guide-for-cisco_12_1/cjab_b_parameters-reference-guide-for-cisco_12_1_chapter_0111.html#reference_0AFD79ADC64F9615769209AC10C732AD)
Will give this a try and revert.

**Comment by anupam99** [comment]
Thanks @meixuemin 
 AdminConfiguredBot tag it was. Robot-buttons are working now for me in 12.5.1.
