### ISSUE TITLE
Problem using Bot.startconversation

### ISSUE THREAD

**Issue by Vishvadeep93** [howdyai/botkit#1582]
convo.ask('What is your favorite team?', function(response, convo1) {
 if(response.type=="slash_command"){
   

 
   convo1.context.bot.replyAcknowledge()
  
    convo1.context.bot.reply(response,"Slash command")
convo1.next();       
    
  }else{

convo1.next();   
convo1.say('Cool, I like team' + response.text)
                 

  

  }
  
                    
               
               
                })

**Comment by Vishvadeep93** [comment]
convo.ask('What is your favorite team?', function(response1, convo1) {
 if(response1.type=="slash_command"){
   


 
   convo1.context.bot.replyAcknowledge()
  
    convo1.context.bot.reply(response1,"Slash command")
convo1.next();       
    })
  }else{

convo1.next();   
convo1.say('Cool, I like team' + response.text)
                 



  

  }
  
                    
               
               
                })

**Comment by benbrown** [comment]
The Botkit conversation system doesn't work with Slash commands.  Slash commands should be "top level" commands rather than answers to prompts within a conversation.

**Comment by Vishvadeep93** [comment]
The isuue is if there is  a ongoing conversation between bot and a user and user tries slash command instead of replying to question.Slash command message comes as response in conversation instead of going to slash command listener.That is why i am trying to handle it inside conversation.

**Comment by ihorrusinko** [comment]
hey @Vishvadeep93 you could try to apply middleware to exclude slash commands from conversations at all.

```javascript
controller.middleware.receive.use(function (bot, message, next) {
	if (message.type === 'slash_command') {
		return bot.botkit.trigger(message.type, [bot, message]);
	}
	next();
});
```

**Comment by benbrown** [comment]
Good suggestion, @ihorrusinko!  This is exactly what I'd recommend.
