### ISSUE TITLE
Error with dialogs

### ISSUE THREAD

**Issue by akbodapati** [howdyai/botkit#1583]
I got this error while sending reply after accepting dialog using dialog_submission:An error occurred in the categorize middleware:  Error: Can't set headers after they are sent.

--------------------------------
Code:

controller.on('dialog_submission', function(bot, message) {
    
     var Source=message.submission.Source;
     var Destination=message.submission.Destination;
 
     bot.reply(message,{
         text:"message:"+Source+Destination
     })
 
     bot.dialogOk();
     
 });

controller.on('slash_command',function(bot,message){

    switch(message.command) {

   
          case '/direction':

          bot.replyAcknowledge();

          var dialog = bot.createDialog(
            'Direction Info',
            "123",
            'Submit'
          ).addText('Source Location','Source')
           .addText('Destination','Destination')
   
            bot.replyWithDialog(message, dialog.asObject());

            

             break;

            
      }
});

**Comment by ihorrusinko** [comment]
hey @akbodapati  try to remove ```bot.replyAcknowledge();``` from slash command listener
