### ISSUE TITLE
Turn bot off and on

### ISSUE THREAD

**Issue by mike23333** [howdyai/botkit#1584]
Hi. I'm using botkit integration with twilio. We integrated with rasa NLU. We use rasa nlu fallback action so whenever it doesn't understand user it will send text message to support agent. I want to set it to turn off the bot automatically whenever a fallback action occurs. So it would work like real texting back and forth. Then be able to turn bot back on to answer questions.  Is there a way to turn off and on bot with botkit?

Thanks in advance!
Michael

**Comment by benbrown** [comment]
You could associate an on/off type value with the user, and then use a Botkit middleware to stop the message from being processed, or route it somewhere.
