### ISSUE TITLE
Create a React client for Botkit Anywhere

### ISSUE THREAD

**Issue by benbrown** [howdyai/botkit#1585]
Developers using react frequently request a react client that uses websockets to talk to Botkit Anywhere.

This would be a great contribution from the community!

**Comment by benbrown** [comment]
Here is the original, vanilla javascript client:

https://github.com/howdyai/botkit-starter-web/blob/master/public/client.js

**Comment by hendrul** [comment]
I got one, how should I publish it?

**Comment by hendrul** [comment]
I got one. Should this issue be better moved to that project instead?, Should I upload my version as a PR?

**Comment by benbrown** [comment]
@hendrul Yes please file a PR on the botkit-starter-web project. That is awesome!
