### ISSUE TITLE
Default Facebook user_profile call asks for too many user profile fields

### ISSUE THREAD

**Issue by MarcL** [howdyai/botkit#1589]
### What are you trying to achieve or the steps to reproduce?

When attempting to retrieve user data from the Facebook graph API using the `api.user_profile` (or `bot.getMessageUser`) method, the code currently asks for the following permissions:

`first_name,last_name,timezone,gender,locale,email,picture`

https://github.com/howdyai/botkit/blob/master/lib/Facebook.js#L963

As of the release of Graph API v3.1 on July 26, 2018, the default permissions allowed are:

`name,first_name,last_name,profile_pic`

See [Facebook user_profile documentation](https://developers.facebook.com/docs/messenger-platform/identity/user-profile/).

If no additional fields are passed then this causes a failure of the Facebook API with the following error condition:

`(#100) Insufficient permission to access user profile.`

### Suggested solution

I was going to raise a PR to reduce the requested permissions but I'm wary that it's a breaking change. It would have consequences for people who have created Facebook apps prior to July 26, 2018 who use the default fields.

I thought I'd request comments before making the change.
Let me know what you think.

Thanks,
Marc

### Context:

- Botkit version: 0.7.0
- Messaging Platform: Facebook
- Node version: v8.12.0
- Os: OSX 10.13.6

**Comment by MarcL** [comment]
Raised a PR. 👍

**Comment by benbrown** [comment]
Merged!

**Comment by MarcL** [comment]
Thanks @benbrown! 🙌
