### ISSUE TITLE
Setup Webserver on RedHat OpenShift

### ISSUE THREAD

**Issue by airlikidh2** [howdyai/botkit#159]
Hello,
I've tried uploading my botkit project on RedShift but it was not working.
I had the following error:
**Application 'appname' failed to start (port 8080 not available)**

The problem is that the express webserver needs an IP on RedShift to get started.

What I've done is I added the IP in the SlackBot.js at line 160 to get the IP from the environment.

```
......
        slack_botkit.webserver = express();

        slack_botkit.webserver.set('ip', process.env.OPENSHIFT_NODEJS_IP || "127.0.0.1");

        slack_botkit.webserver.use(bodyParser.json());
        slack_botkit.webserver.use(bodyParser.urlencoded({ extended: true }));
        slack_botkit.webserver.use(express.static(__dirname + '/public'));

        var server = slack_botkit.webserver.listen(
           slack_botkit.config.port,slack_botkit.webserver.set('ip'), ......

```

I'm not sure if it is the case on other hosting services but this might be worth integrating the **ip** parameter when calling `controller.setupWebserver(port,function(err,webserver)`
Works like a charm otherwise.

More info here: http://stackoverflow.com/questions/31358992/application-appname-failed-to-start-port-8080-not-available-on-open-shift-no

**Comment by martip-sainsburys** [comment]
+1

Same thing happened to me, I had to create my own express server.

**Comment by rithvikvibhu** [comment]
@airlikidh2 Did you edit SlackBot.js after deploying (and then editing with nano), or make changes before pushing?

**Comment by rithvikvibhu** [comment]
@airlikidh2 Did you edit SlackBot.js after deploying (and then editing with nano), or make changes before pushing?

**Comment by airlikidh2** [comment]
I edited before pushing/deploying

**Comment by benbrown** [comment]
We've added a `hostname` parameter to the Botkit constructor which should solve this issue.

var controller = Botkit.slackbot({hostname: '123.123.123.123'});

Let me know if there are any issues with this!

**Comment by airlikidh2** [comment]
Thanks Ben, I'll try it out :)

2016-11-07 15:02 GMT-08:00 Ben Brown <notifications@github.com>:
