### ISSUE TITLE
Using variables in quick replies

### ISSUE THREAD

**Issue by abd6982** [howdyai/botkit#1591]
According to the [documentation](https://botkit.ai/docs/core.html#using-variable-tokens-and-templates-in-conversation-threads), variables can be used in a text message. Is it possible to achieve the same with quick replies?

For eg.

`var reply = {
  text: 'Hi {{vars.name}}!',
  quick_replies: [
      {
          title: '{{vars.opt1}}',
          payload: '{{vars.opt1}}'
      },
      {
          title: '{{vars.opt2}}',
          payload: '{{vars.opt2}}'
      },
  ]
}`

Variable value gets substituted for the **text** field, but not for **quick replies**. Any solutions or workarounds?

**Comment by benbrown** [comment]
There is not a great workaround for this - Botkit does not pass that field through the token replacement process.

This is a reasonable enhancement - the most expedient way to get this is to do it yourself and submit it as a pull request.  A new version of Botkit will be published soon.

You would need to add a block of code similar to this one:
https://github.com/howdyai/botkit/blob/master/lib/CoreBot.js#L842
