### ISSUE TITLE
Slackbot -- Cannot GET /oath

### ISSUE THREAD

**Issue by bpilkerton** [howdyai/botkit#1593]
### What are you trying to achieve or the steps to reproduce?

Hi, I'm trying to setup a basic Slack bot using botkit following the directions here: ````https://botkit.ai/docs/readme-slack.html````

### What was the result you received?
After creating and configuring the bot on Slack, I go to  ````https://[ngrok_url]/login````, It redirects me to Slack, I authorize the app for my workspace and then get redirected back to ````https://[ngrok_url]/oath?code=[long string]&state=botkit```` and the local server responds:

````Cannot GET /oath````

Nothing get sent to the console.

### What did you expect?

A successful authentication with oath.

### Context:

- Botkit version: 0.7.2
- Messaging Platform: slack
- Node version: 10.15.1
- Os: mac 10.14.1 mojave
- Any other relevant information: tunneling using ngrok

Any tips would be greatly appreciated!

**Comment by benbrown** [comment]
You spelled it wrong.  It is not `oath`, it is `oauth`

**Comment by bpilkerton** [comment]
Well that's embarrassing, thanks so much.
