### ISSUE TITLE
Cisco Webex Team - get all details from people.get

### ISSUE THREAD

**Issue by Korhm** [howdyai/botkit#1599]
Hello,

With my Cisco Webex Team bot, I'm trying to get all information from the sender of the message.
For exemple, this request will not return all available fields, like status or lastActivity

```javascript
controller.api.people.get({ personId: message.data.personId }).then(function (data) {
	console.log(data);
	bot.reply(message, ' Your status is ' + data.status);
});
```

#### Logs
```
{
	id: 'Y2lzY29zcGFy[....]DEzYjI2MTZhZmQ',
	emails: ['xxxx@xxxxx.com'],
	phoneNumbers: [],
	displayName: 'FISRT NAME AND LAST NAME',
	nickName: 'NICK',
	firstName: 'FIRSTNAME',
	lastName: 'LASTNAME',
	avatar:
	'https://2b571e19c5f8dfb2[...]hvQiMuBJTg==~1600',
	orgId:
	'Y2lzY2[...]zIzZDU',
	created: '2016-07-15T08:49:14.570Z',
	type: 'person'
}
```
#### Bot
```Your status is undefined```

#### Logs
```
{
	id:
	'Y2lzY29zcGFy[....]DEzYjI2MTZhZmQ',
	emails: ['xxxx@xxxxx.com'],
	phoneNumbers: [],
	displayName: 'FISRT NAME AND LAST NAME',
	nickName: 'NICK',
	firstName: 'FIRSTNAME',
	lastName: 'LASTNAME',
	avatar:
	'https://2b571e19c5f8dfb2[...]hvQiMuBJTg==~1600',
	orgId:
	'Y2lzY2[...]zIzZDU',
	created: '2016-07-15T08:49:14.570Z',
	lastActivity: '2019-03-06T14:49:14.570Z',
	status: 'active',
	type: 'person'
}
```
#### Bot
```Your status is active```

The same request with curl as expected output :
```
curl -s -X GET -H "Authorization: Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxx" https://api.ciscospark.com/v1/people/Y2lzY29zc[....]OTk2M2M
```

### Context:

- Botkit version: 0.7.4
- Messaging Platform: Cisco Webex Team
- Node version: v11.10.1
- Os: Debian 9
- Any other relevant information:  same behavior with node v8.12.0

**Comment by benbrown** [comment]
When you make the call to `controller.api.people.get`, you are actually using the official [ciscospark api library](https://www.npmjs.com/package/ciscospark) directly.

That means the field is either missing from the response, or not supported yet by that library.

I suggest popping into the [official webex teams chat room for Botkit](https://eurl.io/#SyNZuomKx) to ask!
