### ISSUE TITLE
Hears regex in brackets do not match spaces

### ISSUE THREAD

**Issue by adantoscano** [howdyai/botkit#1609]
### Are you sure this is an issue with the Botkit core module?

~~Yes~~ Maybe not

### What are you trying to achieve or the steps to reproduce?
It is weird because with ['.*'] I write 'word' and it match but 'two words' doesn't. So it depends on what I write instead of what I receive from dialogflow.

```js
controller.hears(['.*'],'message_received', dialog.hears, function(bot, message) {...
```
Does not match sentences with spaces and 
```js
controller.hears('.*','message_received', dialog.hears, function(bot, message) {...
```
Does

### What was the result you received?
Expected controller is not triggered

### What did you expect?
Both triggers

### Context:

- Botkit version: 0.7.4
- Messaging Platform: Web
- Node version: 10.15.0
- Os: Linux
- Any other relevant information: I'm using dialogflow middleware <3

**Comment by benbrown** [comment]
Interesting!

Are you using the Dialog Flow hearing middleware here?

**Comment by adantoscano** [comment]
yup

**Comment by adantoscano** [comment]
I just realize I did not explain it well. It is weird because with `['.*']` I write 'word' and it match but 'two words' doesn't. So it depends on what I write instead of what I receive from dialogflow.

**Comment by adantoscano** [comment]
Deepin into it, I found that dialogflow middleware got a conditional with a minimumConfidence that maybe is inferring

**Comment by adantoscano** [comment]
Fixed [here](https://github.com/jschnurr/botkit-middleware-dialogflow/pull/22)
