### ISSUE TITLE
convo.gotoThread() doesn't lead anywhere and it hangs the bot

### ISSUE THREAD

**Issue by HamzehMuaz** [howdyai/botkit#1610]
Hello all,

I'm working on a project that uses convo.gotoThread() to jump between flows in a conversation, this is working in the live production environment, but when I run it on my local machine, the bot  stops replying after a convo.gotoThread() .

To go into more detail, a convo.addQuestion asks the user to enter some text, then is supposed to jump to another thread by convo.gotoThread which is a convo.addQuestion that asks the user to enter their email.
Once the flow reaches the gotoThread, it doesn't respond at all, even after the user typing anything, it still does not respond. My guess is that the flow is stuck in the conversation and isn't going to the next step.

What I have tried to solve it:
I tried debugging with breakpoints and going step by step, but it doesn't seem to reach anywhere relevant.
I tried to update npm, botkit, and all other modules, and even re-installing the whole project but it did not work.

- Botkit version: 0.6.21 & 0.7.4 (tried both)
- Messaging Platform: Facebook Messenger 
- Node version: v10.15.1
- Os: Windows 10
- Other information: I'm using Microsoft VS studio.

Thank you.

**EDIT:**  Since first post, I tried to run the project on Ubuntu on the same machine but that did not work either.
**EDIT:** Issue is solved by itself.

**Comment by benbrown** [comment]
A few thoughts:

* Are you making any asynchronous calls in your first addQuestion callback function?
* Make 100% sure that the thread name you are passing in already exists

**Comment by HamzehMuaz** [comment]
Thanks for responding Ben, 
The callback of the first addQuestion is not Async and doesn't have any Async functions, and the thread name is 100% correct.
To give more information, the flow works fine in the live version that is deployed to the cloud, and also works fine in my colleagues' machines. Also, I copied the flow to a different project of mine but changed the variables name and removed the functions and it worked perfectly.
This makes me confused and not sure what the problem is or where to go from here.

**Comment by aqsous** [comment]
same problem

**Comment by benbrown** [comment]
Did you start with the Starter kit project?

Do other multi-message conversations work?

**Comment by HamzehMuaz** [comment]
> Did you start with the Starter kit project?
> 
> Do other multi-message conversations work?

I don't think it was started with the starter kit project.
What do you exactly mean by multi-message conversations? I do use mutliple conversations that flow normally without convo.gotoThread , and even ones with it, do work fine but hang when going to other threads.

**Comment by HamzehMuaz** [comment]
Issue suddenly doesn't happen anymore, solved ... I guess.
