### ISSUE TITLE
Avoiding buggy offset in convo

### ISSUE THREAD

**Issue by TheDApact** [howdyai/botkit#1615]
- Botkit version: 0.4.3
- Messaging Platform: Facebook / Messenger
- Node version: 11.4
- Os: OSX & iOS

My bot receives images and call APIs with these images. Sometime it just handle the first attachments (call a third party API with `response.attachments[0]`) sometimes it handles all received attachments (call third party API with `response.attachments`). 

When the code handles all received attachments, a bug happens if the user sends two images in two separate messages, without waiting for the first image to be received and with very little delay. In this case the bot receives/handles both messages but fires the callback of convo.ask twice.
Which will in turn create a never ending offset between bot's questions and user's responses until the bot is rebooted. 

![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/23412460/55606389-cac90180-57a2-11e9-85b7-d249f1dac6ad.gif)

This behaviors does not occurs when handling `response.attachments[0]` only (the app will not receive the second image until the first image has been processed).

Any solution to avoid this? ideally the bot should handle both images (even sent as two different messages) because from the user perspective both images have been sent.

**Comment by benbrown** [comment]
Are you calling convo.next only after you have processed the attachment?  

If so, you might consider calling next immediately, allowing the conversation to move forward and prepare to accept the next message... IE let the upload be processed in the background and use bot.say to send any necessary confirmation.

**Comment by TheDApact** [comment]
I should have mentioned that the bot decides which thread to fire based on the image received. So I need to process the image before `convo.next()`. Can you think of another workaround?

**Comment by TheDApact** [comment]
Hey @benbrown I have a workaround where I set `firstResponseReceived[response.user]` to `true` as soon as I get the first response, so any other message sent before `convo.next()` has been called would be processed but `convo.next()` dos not get called a second time. 

It works but it's very messy as I need to duplicate all my logics to handle a second message without double calling `convo.next()` or any `convo.say()`.

I really think this is a problem that should be solved at framework level, but I'm not qualified enough to really find a clean solution. Do you have leads?
