### ISSUE TITLE
Unable to embed the bot on an HTML page

### ISSUE THREAD

**Issue by samar14641** [howdyai/botkit#1618]
I was following the instructions on https://github.com/howdyai/botkit-starter-web/blob/master/docs/botkit_web_client.md#embed-botkit-in-a-website-with-iframes to embed my bot on an HTML page.

However, I get the following error: 
````
Uncaught DOMException: Failed to construct 'WebSocket': The URL 'ws://' is invalid.
    at Object.connectWebsocket (file:///F:/Clones/bot/public/client.js:161:23)
    at Object.connect (file:///F:/Clones/bot/public/client.js:131:16)
    at receiveCommand (file:///F:/Clones/bot/public/client.js:282:20)
````

My bot is currently running on http://localhost:3000, so the ws_url variable (in client.js) uses 'ws'.
````
ws_url: (location.protocol === 'https:' ? 'wss' : 'ws') + '://' + location.host,
````

**Comment by benbrown** [comment]
It looks like you are linking to/embedding the client.js file from a static location, not from the localhost url.

**Comment by samar14641** [comment]
@benbrown Yeah you were right. I put the HTML page up on localhost:8080 and got it working. The issue can be closed. 
Thanks.
