### ISSUE TITLE
How to send DM messages in slack as a user

### ISSUE THREAD

**Issue by Ilchuk-Mihail** [howdyai/botkit#1619]
Is there any way to create conversation as a user? 
Could bot send messages as a user which installed app? 

Now I can send messages via this method  `bot.api.chat.postMessage` but it is only one message and I can't track conversation. How can I achive this? 

I expect bot can send messages as a real user and make some conversation. Is it possible? 
 
- Botkit version: v0.7.0
- Messaging Platform: Slack
- Node version: v10.14.1
- Os: Windows 10

**Comment by benbrown** [comment]
Botkit isn't really set up to deal with user tokens. However, they _are_ returned by the oauth process and if you capture it, you can use it with the Slack API, or to spawn a bot with that token rather than the normal user token.  However, I have no idea what would be involved in doing all of that or how well it would work.

**Comment by Ilchuk-Mihail** [comment]
@benbrown Thanks for response.
As I can see, through the oauth process botkit saves `app_token` and if I use it in methods `bot.api.chat.postMessage` - it works, message is sent from real user (who installed app) in direct message. 

But , problem I have seen : How to make simple conversations (with a few questions), and get responses from that user, like bot usually works. 

Like bot is a proxy and all messages are sent from a real user. 
maybe it is possible to track that conversation/responses via webhook?

**Comment by benbrown** [comment]
That isn't how Botkit works, really.  I'm not sure what you'd have to change to have the bot conduct conversations as the user -- but this is outside of the scope of Botkit's normal functionality.
