### ISSUE TITLE
Incoming webhooks example?

### ISSUE THREAD

**Issue by plainspace** [howdyai/botkit#162]
Is there an ETA for this? Thanks! Looking forward to it.

**Comment by dossy** [comment]
Are you looking for something more than this? https://github.com/howdyai/botkit/blob/master/examples/slackbutton_incomingwebhooks.js

**Comment by plainspace** [comment]
I was wondering if there were plans to finish this: botkit/examples/incoming_webhooks.js and specifically I am looking for more examples about how to do use `sendWebhook`and Incoming Webhook things.

**Comment by dossy** [comment]
@plainspace Finish it how?  It appears to be a fully functioning (albeit very simple) example of the functionality?  Maybe if you have a specific use case that you can describe, someone could work up an example to demonstrate how to do it?

**Comment by plainspace** [comment]
I was referring to the `todo` here: https://github.com/howdyai/botkit/blob/master/examples/incoming_webhooks.js

**Comment by dossy** [comment]
Ahh, I see, sorry I missed the difference. You're right, those examples need to be fleshed out - the Slack Button example hints at how it might be done, but it would be nice to have a ready-to-run example.

Since I haven't done any webhook stuff myself with Botkit, yet, I don't want to volunteer to write the example, but I might take a stab at it if nobody else will...

**Comment by plainspace** [comment]
Awesome. Sorry I wasn't more clear initially. Who else might touch this?

**Comment by peterswimm** [comment]
This looks like the example is fully formed, but would accept any prs that boost functionality.

**Comment by plainspace** [comment]
Fully formed? I still see the to-do...

**Comment by peterswimm** [comment]
@plainspace sorry for the confused I was looking a wrong example. Low priority on the Howdy side, but we will gladly review any PR's submitted by the community for this.

**Comment by peterswimm** [comment]
added this to the projects board
https://github.com/howdyai/botkit/projects/2
