### ISSUE TITLE
Allow disabling Slack clientSigningSecret warning

### ISSUE THREAD

**Issue by kimsey0** [howdyai/botkit#1623]
From version 0.6.20, botkit displays a warning when creating a `slackbot` without specifying a `clientSigningSecret`. According to a comment in the source, specifying a `clientSigningSecret` or `clientVerificationToken` will be mandatory in the future.
https://github.com/howdyai/botkit/blob/7aedcbc6dca075feb8b2d984a5645caf5216c6b8/lib/SlackBot.js#L13-L15

Adding a `clientSigningSecret` increases security when building an interactive Slack bot, which I assume is the most common use case. However, botkit can also be used to build bots which only post information to Slack from external sources, for example via an incoming webhook, and which never have to receive requests from Slack. In this case, adding a `clientSigningSecret` does nothing, and the warning is unnecessary.

As a workaround, you can disable the warning by specifying an invalid `clientSigningSecret` (`{clientSigningSecret: "Not needed"}`). However, it would be nice to have a cleaner way to indicate to botkit that you do not intend to receive requests from Slack, especially when specifying a `clientSigningSecret` becomes mandatory.

A `sendOnly` option for `slackbot` could potentially prevent calling methods that start listening for requests from Slack.

**Comment by benbrown** [comment]
There are plenty of other tools you can use to make simple webhook requests to Slack.  Botkit is primarily for building interactive chatbot type applications, and keeping those endpoints secure by default is very important. The next version of Botkit does requires this parameter.
