### ISSUE TITLE
Native 'message' event not fired 

### ISSUE THREAD

**Issue by cankut** [howdyai/botkit#163]
On this section [https://github.com/howdyai/botkit#responding-to-events](url)

It states that 

> You can receive and handle any of the [native events thrown by slack](https://api.slack.com/events).

I tried

```
controller.on('message',function(bot,message) {
   console.log("got message.");
});
```

But it doesn't get fired.

**Comment by benbrown** [comment]
True!
Botkit translates the generic message event into a few other more specific events.

If you want to receive *every single message*, do controller.on('message_received')
