### ISSUE TITLE
Begin dialog handler Botkit V4 ':botkit-wrapper'

### ISSUE THREAD

**Issue by xi-osman** [howdyai/botkit#1631]
### Are you sure this is an issue with the Botkit core module?
Not sure if its Botkit but im following the docs.

### What are you trying to achieve or the steps to reproduce?
Trying to begin a WaterfallDialog from botbuilder-dialogs but I get a missing Id error. 

### Describe your issue here, include as much detail as necessary to reproduce the issue or implement a missing functionality.
Following these [docs](https://botkit.ai/docs/v4/core.html#native-bot-builder-dialogs) to add the WaterfallDialog but I get an error that the Id is missing so the only way to get it working is to append ':botkit-wrapper' to the name. 

Failing:
````
 const wfTimeDialog = new WaterfallDialog('time', [
      introStep.bind(this),
      actStep.bind(this),
      finalStep.bind(this)
    ]);

//...

 controller.hears(['time'], 'message', async(bot, message) => {
    await bot.beginDialog('time');
  });
````

Working :
````
 const wfTimeDialog = new WaterfallDialog('time:botkit-wrapper', [
      introStep.bind(this),
      actStep.bind(this),
      finalStep.bind(this)
    ]);

//...

 controller.hears(['time'], 'message', async(bot, message) => {
    await bot.beginDialog('time');
  });
````

### Context:
- Botkit version: 4
- Messaging Platform: Teams
- Node version: 10
- Os: Windows

![image](https://user-images.githubusercontent.com/463779/57183932-49d05900-6e79-11e9-9d5f-50b4965d9961.png)

**Comment by benbrown** [comment]
Ah thank you for the bug report! The docs are slightly incorrect --  use `controller.addDialog` instead of `controller.dialogSet.add` to add that dialog.

**Comment by benbrown** [comment]
The docs have been updated to reflect this.  Thank you for your report!

**Comment by xi-osman** [comment]
Wow your fast! Thanks!

**Comment by benbrown** [comment]
Excited to have you using the latest version!
