### ISSUE TITLE
Slack Add Select validation error when using typescript

### ISSUE THREAD

**Issue by roger-king** [howdyai/botkit#1633]
** DO NOT ERASE THESE INSTRUCTIONS WITHOUT READING THEM FIRST **

Please read this entire template before posting any issue to get faster response.

Open an issue on this repository with your topic or question, providing as much detail as possible. The more we know, the better we can help.

Before posting, search the repository to see if there's already an issue opened to avoid duplicates.

### Are you sure this is an issue with the Botkit core module?

Slack returns a validation error when using `addSelect()` in dialog.

For all other questions, requests or help, please feel free to join the discussion slack : https://community.botkit.ai

### What are you trying to achieve or the steps to reproduce?

Describe your issue here, include as much detail as necessary to reproduce the issue or implement a missing functionality.

When using typescript and botkit, `addSelect()` expects a `string` type for `options_list`.

````
// Wrap code in markdown source tags
````

### Context:

- Botkit version: 4.0.1
- Messaging Platform:
- Node version: 
- Os:
- Any other relevant information:

**Comment by benbrown** [comment]
Thanks for patching this.  The fix will be in the next release!

**Comment by benbrown** [comment]
This was part of botbuilder-adapter-slack 1.0.2!
