### ISSUE TITLE
bot_channel_join event not firing when bot is invited to a channel

### ISSUE THREAD

**Issue by Laptopmini** [howdyai/botkit#1640]
Using the latest botkit starter kit for slack:
`6292478eca29e9560665512bbd2f385b5e88899e`

And having upgraded it to the lastest botkit framework:
`v0.7.4`

And using the following skill definition:
```
module.exports = function(controller) {
  controller.on('bot_channel_join', function(bot, message) {
    bot.reply(
      message,
      "Hey guys... I'm here."
    );
    debug(`Bot has joined "${message.channel}".`);
  });
};
```

The event is never fired.

This ticket is a duplicate of #347. That ticket was 2 years old so I figured this could use a fresh thread, but feel free to close this if the other reopens.

Needs "Slack-Related" tag.

**Comment by benbrown** [comment]
Due to changes in the way Slack sends these events, the `bot_channel_join` event is no longer reliable.  

Use the new event @roger-king mentioned.

**Comment by Laptopmini** [comment]
Thanks guys! I'm gonna try this out.

Looking at the specs, if seems you'd need to make sure the user joining is your own bot to replicate the original event:
```
const { user_id } = await bot.api.bots.info();
if (message.user === user_id) { ... }
```
