### ISSUE TITLE
Disable console.log and console.warn option

### ISSUE THREAD

**Issue by jebarjonet** [howdyai/botkit#1643]
Every time my server restarts this is what I get in my terminal:

```
** Your bot is using memory storage and will forget everything when it reboots!
** To preserve dialog state, specify a storage adapter in your Botkit config:
** const controller = new Botkit({storage: myStorageAdapter});
Enabling plugin:  Slack Adapter
```

This is really annoying, my dev terminal is just full of Botkit logs. I could set a `storage`, but I don't care for now as it's just a `.warn` anyway. No other library is doing that 🙈and I believe no library should ever spam the terminal like this. How about having a `debug` option to Botkit (would be `true` by default) which displays `console.log` and `console.warn` *only* when `debug` is `true`?

**Comment by benbrown** [comment]
Thanks for the feedback and a fair point. I'll consider a mechanism for disabling some or all of these.

**Comment by benbrown** [comment]
In 4.0.2, I am introducing a `disable_console` option on the controller that will turn off this type of message.
