### ISSUE TITLE
Pattern handling inconsistent between hears() and ask()

### ISSUE THREAD

**Issue by jovrtn** [howdyai/botkit#165]
It appears that when passing keyword patterns to hears(), they're [wrapped with the `new RegExp(pattern, 'i')` constructor](https://github.com/howdyai/botkit/blob/efd63e1b664bdaf65763ad1c28cc69fe450ef176/lib/CoreBot.js#L694), however ask() callback patterns [expect an existing regex object](https://github.com/howdyai/botkit/blob/efd63e1b664bdaf65763ad1c28cc69fe450ef176/lib/CoreBot.js#L108).

Since the documentation refers to the patterns for each as 'regular expressions to match' and 'regular_expression' respectively, it's a bit confusing when to pass full regex objects and when to include only a partial regex pattern without flags.

As expected, if you pass a RegExp constructor as a hears() pattern, you get:
```
node_modules/botkit/lib/CoreBot.js:695
if (match = message.text.match(new RegExp(keyword, 'i'))) {
                               ^
TypeError: Cannot supply flags when constructing one RegExp from another
```
As a side note, in ECMAScript 6 the RegExp constructor shouldn't throw this error and would instead create a new regex object, however node appears to lack full support for this and several other new RegExp features as of v5.8.

**Comment by benbrown** [comment]
Thanks! Good point.

The ask pattern matcher should also support the new hears middleware methods.

I will work on this!

**Comment by benbrown** [comment]
OK!

I did this in a branch: 
https://github.com/howdyai/botkit/tree/dev/askpatterns

This normalizes the way those patterns are matched, and allows for either strings or regexp objects to be passed in.

@jovrtn Will you try this branch?

**Comment by jovrtn** [comment]
Just gave it a try passing in both a string and a RegExp object—seems to be working well. Thanks!
