### ISSUE TITLE
 Example of official documentation with a fault

### ISSUE THREAD

**Issue by mcconejero** [howdyai/botkit#1655]
![image](https://user-images.githubusercontent.com/43406904/57627515-67e43a80-7598-11e9-9b89-b63d1a0b40c0.png)

In this code fragment of the official documentation, at least it happens to me, it does not change from the 'Thread' of 'favorite_color' to 'confirmation' and this is because we have to add this code fragment: convo.gotoThread (' confirmation ').

It is added just after the convo.addQuestion that asks us what is our favorite color, being as follows:

convo.addQuestion ('Now, what is your favorite color?', async (response, convo, bot) => {
    convo.gotoThread ('confirmation')
}, 'color', 'favorite_color');

**Comment by benbrown** [comment]
Ah you are correct.  The call to `addAction` is missing its thread name parameter -- this SHOUlD be equivalent to calling it inside the addQuestion callback. Thanks, will fix!
