### ISSUE TITLE
Possibility of a 0.7.5 on the legacy branch?

### ISSUE THREAD

**Issue by calvin-evans** [howdyai/botkit#1662]
Hi Guys,

Looks like there are a few fixes sitting over on the legacy branch that went in after 0.7.4 -- any chance of publishing another version to NPM? Would rather not fork just to get at 81d0d8d :)

**Comment by benbrown** [comment]
Yes, there will be a 0.7.5 - however I believe the commit you are referring to is in 0.7.4 -->

https://github.com/howdyai/botkit/blob/legacy/lib/Web.js#L18

**Comment by benbrown** [comment]
Not stale! 0.7.5 coming soonish.

**Comment by benbrown** [comment]
Ha, "soonish."

**Comment by ryansydnor** [comment]
0.7.5 is published!
