### ISSUE TITLE
Facebook quick replies are improperly pruned from BotkitConversations

### ISSUE THREAD

**Issue by benbrown** [howdyai/botkit#1664]
When using botbuilder-adapter-facebook with Botkit 4, the `quick_replies` field on outgoing messages does not work as expected when used with `BotkitConversation`

This is caused by an improper mapping of those fields into the "SuggestedResponses" field.

This may also apply to the WebAdapter which also uses quick_replies.

This only pertains to using `BotkitConversation`, it works fine using bot.reply

A temporary workaround: put quick_replies field inside `channelData` field:

```javascript
convo.ask({
   text: ['What is your favorite color'],
   channelData: {
     quick_replies: [
        {...}   
     ] 
   }
}, [], 'key');
```

**Comment by PaulContremoulin** [comment]
Hi ! 
Same with other Facebook Message Templates (generic, button, etc.). Doesn't work with ask() but work fine with reply(). 😄
