### ISSUE TITLE
Asking for the location in a conversation repeats the question

### ISSUE THREAD

**Issue by Oksana96** [howdyai/botkit#1665]
### What are you trying to achieve or the steps to reproduce?

I'm trying to request the user location with the "location" quick_reply, in a conversation. When the user submits it, the bots asks the location again, instead of calling the handlers. It seems that the bot repeats the question when "text" is empty, but when asking for a location, the text will always be empty.

```
 convo.ask({
        text: ["We need your location to find the nearest gas station."],
        channelData: {
            quick_replies: [
            {              
               content_type: "location",
            },
        ]}}, [{
            default: true,
            handler: async(response, convo, bot) => {
                console.log(`user location is ${ response }`);
            }
        }], 'location'
    )
```

### What was the result you received?

The bot asks the question again

### What did you expect?

The handler should be called

### Screenshot

![Screen Shot 2019-05-18 at 11 22 38](https://user-images.githubusercontent.com/44060092/57967445-641d3300-795f-11e9-950d-1dc167e5d968.png)

### Context:

- Botkit version: 4.0.2
- Messaging Platform: Facebook
- Node version:  10
- Os: Mac OS X
- Any other relevant information:

**Comment by leesiongchan** [comment]
Do we have any workaround for this? @benbrown

**Comment by benbrown** [comment]
Not really.

The workaround would involve creating a middleware that:

a) changes the type of the event to message
b) moves the location value into the text property so that it can be accessed as the result inside the callback handler
