### ISSUE TITLE
botbuilder-adapter-slack@1.0.2 throws error "this.options.getBotUserByTeam is not a function"

### ISSUE THREAD

**Issue by pawanbhole** [howdyai/botkit#1669]
- Botkit version: 4.0.1
- botbuilder-adapter-slack: 1.0.2
- Messaging Platform: Slack
- Node version: v10.15.1
- Os: macOS 10.13.6
- Any other relevant information:
 I am starting botkit server on first incoming request and i am using botToken for initializing  SlackAdapter.

`const adapter = new SlackAdapter({
      verificationToken: verification_token,
      botToken: bot_access_token
  });
`

In constructor of the SlackAdapter it is calling **this.slack.auth.test()** for populating this.identity.
As this is external call, it takes time to populate **this.identity**. But as I am immediately passing incoming request to **processActivity** function, it fails at function **getBotUserByTeam** with error "**this.options.getBotUserByTeam is not a function**".
As  **this.identity** is yet null, code tries to call **this.options.getBotUserByTeam** which is undefined. There should be some way to know if SlackAdaptor is initialized completely or not. 
I am calling **processActivity** function  in **ready** function of botkit. But this ready function is called before call to **this.slack.auth.test()**  is complete.
So to fix the problem SlackAdaptor should notify botkit that it is ready to process incoming requests and botkit should execut ready function after Adaptor is completely initialized.

**Comment by benbrown** [comment]
Interesting! Thank you for this bug report.

**Comment by benbrown** [comment]
For now there is not a great way to solve this. If you are still experiencing a problem, I would introduce a short delay when your bot boots up before calling the adapter methods.
