### ISSUE TITLE
Type Definition error when using SlackBotWorker

### ISSUE THREAD

**Issue by roger-king** [howdyai/botkit#1670]
** DO NOT ERASE THESE INSTRUCTIONS WITHOUT READING THEM FIRST **

Please read this entire template before posting any issue to get faster response.

Open an issue on this repository with your topic or question, providing as much detail as possible. The more we know, the better we can help.

Before posting, search the repository to see if there's already an issue opened to avoid duplicates.

### Are you sure this is an issue with the Botkit core module?

For all other questions, requests or help, please feel free to join the discussion slack : https://community.botkit.ai

### What are you trying to achieve or the steps to reproduce?

Describe your issue here, include as much detail as necessary to reproduce the issue or implement a missing functionality.

````
controller.hears('test', 'direct_message', async (bot: SlackBotWorker, message: BotkitMessage) => {
    // Code here.
});
````

### What was the result you received?

Type definition for `bot` in callback function for controller (Botkit). Prior to `4.0.2` I was able to use the `SlackBotWorker` as the type for the bot in the controller (botkit) callback function. I am receiving type errors when using that. I defaulted to use BotWorker, but that does not provide me the function of startPrivateConversation.

### Context:

- Botkit version: 4.0.2
- Messaging Platform: slack
- Node version: 10.15.1
- Os:
- Any other relevant information:

Let me know if this is a bug or I am using the library incorrectly with the update of 4.0.2

**Comment by benbrown** [comment]
@roger-king are you importing that class along with Botkit?

**Comment by roger-king** [comment]
@benbrown Yes I am.

**Comment by benbrown** [comment]
@roger-king is this still an issue?

**Comment by roger-king** [comment]
@benbrown I believe this has been resolved.
