### ISSUE TITLE
controller.storage.users returns undefined

### ISSUE THREAD

**Issue by CptMeatball** [howdyai/botkit#1671]
Retrieving data from the "built in storage object" of Botkit does not seem to work when using either a mongoDB connection or just default config. 

`controller.storage.users` always returns `cannot read property users of undefined` 

I'm currently connecting to MongoDB Atlas which confirmed I have connected to my MongoDB, so that shouldn't be the problem. Using the application without a `MONGO_URI` defined returns the same response. 

All docs and examples refer to this, but I can't find any working example out there which work for v4.

**Comment by benbrown** [comment]
`controller.storage.users` only applies to Botkit v0.7 and below.

v4 does not provide a built in mechanism for storing your user info.

**Comment by CptMeatball** [comment]
Sorry for the rookie questions, but what's the thing with the Mongo URI configuration etc if you can't so anything with it? AFAIK there isn't anything documented about actually using the storage. 

How would you replicate for example the tasklist example of the old slack-starter-kit?

**Comment by benbrown** [comment]
The Mongo is used for the underlying Bot Framework storage system, which is used to store conversation state.  In the future, we may expand that (as Bot Framework adds features), but in general it is my recommendation that you use your own database accessor.

This is complete pseudo-code, but it would be something like this:

```
module.exports = function(controller) {
 
 const my_db = new database(uri);

controller.hears('add todo', 'message', async(bot, message) => {
    let task = message.text;
     await my_db.insert(message.user, task);
});





}
