### ISSUE TITLE
Facebook/Messenger message: '(#105) param name_placeholder[elements][0][buttons] has too many elements

### ISSUE THREAD

**Issue by yestouscool** [howdyai/botkit#1672]
### What are you trying to achieve or the steps to reproduce?
I am implementing the share button on a carousel with a content to share following what is shown [here facebook documentation](https://developers.facebook.com/docs/messenger-platform/reference/buttons/share) I am getting an error :

> info: An error occurred while sending a message:  { message: '(#105) param name_placeholder[elements][0][buttons] has too many elements.',
>   type: 'OAuthException',
>   code: 105,
>   fbtrace_id: 'GWj697sH42H' }

This is how my carousel element looks like : 
````
{ title: 'You are very wonderfull',
  image_url: 'https:/mydomain.com/images(5).jpg',
  subtitle: 'Hello to come',
  buttons:
   [ { type: 'postback',
       payload: 'YES',
       title: 'EXPLAIN' },
     { type: 'postback',
       payload: 'KIIL',
       title: 'GO AHEAD' },
     { type: 'element_share', share_contents: [Object] } ] }
````

- Botkit version: 0.7.0
- Messaging Platform: Messenger
- Node version: 8
- Os: windows

**Comment by yestouscool** [comment]
What might be the problem ? is it botkit legacy doesn't support it ? or just a problem with my way of writting things ?

**Comment by yestouscool** [comment]
Any clue would really be appreciated, I want to know where the problem could be.

**Comment by yestouscool** [comment]
I tried to read the document propery and found this :

> share_contents only supports the following:
> 
> Template used must be generic template.
> Maximum of one URL button on the template. If no buttons are specified, the buttons property on the generic template must be set to an empty array.

I tried to remove the buttons I had put (3 buttons) on the share_contents object but now I am getting an error saying : 

> debug: API ERROR { message: '(#-1) Unexpected internal error',
>   type: 'OAuthException',
>   code: -1,
>   error_subcode: 2018012,
>   fbtrace_id: 'BUhM3r6Tjqo' }
> info: An error occurred while sending a message:  { message: '(#-1) Unexpected internal error',
>   type: 'OAuthException',
>   code: -1,
>   error_subcode: 2018012,
>   fbtrace_id: 'BUhM3r6Tjqo' }

The complete carousel is not being send to the user.

**Comment by yestouscool** [comment]
I really need help with this just guidance ...

**Comment by Charefdz1995** [comment]
Hello I had the same problem. i have pass it with shorter payload keyword because i think there is some limit number of characters.
