### ISSUE TITLE
convo.repeat() triggering error message

### ISSUE THREAD

**Issue by akshaykonjier** [howdyai/botkit#1673]
### Are you sure this is an issue with the Botkit core module?

I was running into issues with the convo.repeat() function.  It wasn't working on certain questions and was working on others.

### What are you trying to achieve or the steps to reproduce?

I get it on random questions and have tried numerous tests to figure out what is causing it but cannot determine the issue.  I'm getting an error on conversation.js on line 498 indicating that step.result.match doesn't exist.  I noticed that occasionally step.result is an object instead of a string and that is where it is having the issue.  I outputted the result to show this.

conversation.js in lib

![image](https://user-images.githubusercontent.com/16294309/58507976-f7751600-8160-11e9-9678-79975f7c3ab1.png)

Result in console

![image](https://user-images.githubusercontent.com/16294309/58507945-e9bf9080-8160-11e9-8c18-9e88884af00d.png)

### Context:

- Botkit version: 4
- Messaging Platform: WebSocket
- Node version: 10.15.1
- Os:Windows
- Any other relevant information:

**Comment by Peter-Barrett** [comment]
I am having this issue too. For me it's happening after I begin a dialog based on the response of a question. I'm not too sure at what stage the actual error is happening though because it seems to randomly happen a couple of seconds after the question is answered. 

```
conversation.addQuestion({
      text: ['I can help you with one of the following:'],
      channelData: {
        quick_replies: [{
          content_type: 'text',
          title: 'foo',
          payload: 'bar'
        }],
      },
    }, [{
      handler: async (response: string, convo: BotkitDialogWrapper, bot: BotWorker): Promise<any> => {
        await bot.beginDialog(response);
     }
    }], 'chosenOption', actionName);
```

**Comment by benbrown** [comment]
I have a patch that will stop this from erroring, but I am struggling to find the root cause.

Can either of you send me more information about the full structure of your dialog?

b

**Comment by etiennellipse** [comment]
@c4ndybar I believe this is a different issue; I am having it too. I will open an issue for this specific case.
