### ISSUE TITLE
Should write cms_uri without last /

### ISSUE THREAD

**Issue by adantoscano** [howdyai/botkit#1678]
### What was the result you received?
With `cms_uri=http://localhost:3000/` I get a JSON.parse error because the request is something like `http://localhost:3000//api/v0/` 
### What did you expect?
Uri and path joins in a correct way
### Context:

- Botkit version: latest
- Messaging Platform: Any
- Node version: 10.15.0
- Os: Linux
- Any other relevant information:

**Comment by adantoscano** [comment]
Pull req to fix it #1677

**Comment by benbrown** [comment]
This was fixed in 4.5
