### ISSUE TITLE
Legacy Facebook adapter should be updated to use bot-specific config

### ISSUE THREAD

**Issue by benbrown** [howdyai/botkit#1681]
One of the major limitations of the legacy Facebook adapters it is lack of support for multi-tenant bots.

In large part, this is because the spawned `bot` objects from this adapter use a adapter-wide global configuration option (`configuration.access_token` being the primary culprit) instead of a local config option (`bot.config.access_token`)

This would require a small change to the `defineBot` factory function to mix the global vars into the local config.

**Comment by wolfejw86** [comment]
possible fix in https://github.com/howdyai/botkit/pull/1683
