### ISSUE TITLE
Slack retrying everything, not convinced I'm ever responding quick enough (using localtunnel.me) 

### ISSUE THREAD

**Issue by peabnuts123** [howdyai/botkit#1684]
Hey, I'm not sure what my issue is here so I'm asking on here for some insight. I'm writing a bot for Slack using the SlackAdapter. It sources its data from a third-party API so it needs to first make a request and then reply on Slack after fetching the data it needs. Now, Slack has some pretty strict guidelines around receiving an acknowledgement from your bot within a 3 second window of their request. As per Issue #134, botkit supposedly automatically ACKs with an empty response, so this shouldn't be much of an issue. However, Slack is constantly retrying almost every event it sends me. Slack notes that if you retry too many requests, your app will eventually be disabled.

Now this is just in my local development environment (I have not deployed this anywhere yet), I'm using localtunnel.me to expose my dev server but I have a fast connection, I can't see why it would be more than a 3000ms round-trip to Slack's servers if the Botkit library is in-fact auto ACK'ing for me as soon as it receives its request. This is kind of a problem as I've had to build a cache for my dev server so that my bot only responds to messages once, and who knows what will happen once I deploy the bot to my server. This can't be common behaviour, does anybody have any insight as to what's the slow link in my setup? 

Outline of my code is as-follows:

```TypeScript
// Configure botkit
const adapter = new SlackAdapter({
  clientSigningSecret: process.env.clientSigningSecret,
  botToken: process.env.botToken,
  redirectUri: process.env.redirectUri || '',
});
adapter.use(new SlackEventMiddleware());
adapter.use(new SlackMessageTypeMiddleware());

const controller = new Botkit({
  adapter,
});

// Wait for bot to start
controller.ready(() => {
  controller.hears(['.*'], ['direct_message', 'direct_mention', 'mention'], async function (bot, slackMessage) {
    /* Make a request to another API */
    const response = await fetchDataFromThirdPartyAPI(slackMessage.text);
    
    /* Reply based on the response */
    await bot.reply(slackMessage, `Response from API: ${response.output}`);
  });
});
```

### Context:

- Botkit version: 4.0.2
- Messaging Platform: Slack
- Node version:  v10.13.0
- OS: OSX v10.14

**Comment by benbrown** [comment]
The 4x branch no longer does an immediate ACK - it will wait until your handler finishes. 

You could put your bot.reply inside a .then for your API call function and return without waiting for it to complete. However, since that will result in an "out of turn" message, you will have to refresh the bot's internal context by calling `await bot.changeContext(message.reference);` before using bot.reply as seen here:

https://github.com/howdyai/botkit/blob/master/packages/testbot/features/websocket_features.js#L76

**Comment by peabnuts123** [comment]
Ah I see! Thanks for the heads up, I guess that works just fine. Is there room now to re-introduce a command like [bot.replyAcknowledge](https://botkit.ai/docs/v0/readme-slack.html#botreplyacknowledge), to instruct the Slack adapter to send an ACK back to the server? 

i.e.

```TypeScript
controller.hears(['.*'], ['direct_message', 'direct_mention', 'mention'], async function (bot, slackMessage) {
  /* ACK to Slack */
  await bot.replyAcknowledge();
  
  /* Make a request to another API */
  const response = await fetchDataFromThirdPartyAPI(slackMessage.text);
  
  /* Reply based on the response */
  await bot.reply(slackMessage, `Response from API: ${response.output}`);
});

```

**Comment by benbrown** [comment]
replyAcknowledge doesn't really make sense with the new async/await pattern in place for all those handlers.  To acknowledge, you have to return from the handler. This allows you to throw an http error code if an error occurs, for example. It is also used by the Slack adapter when responding to slash commands, dialog submits and a few other types of webhook that expect a response.

**Comment by MatissJanis** [comment]
Can this be fixed?  It's very annoying that slack keeps re-sending messages if a `await` process is taking really long.

**Comment by minode-raj** [comment]
Can we give an option to avoid all retries?
Slack send `X-Slack-Retry-Num` option in it's header. Can we have a config where all retries are ignored?

**Comment by adamdabbracci** [comment]
This continues to be an issue, especially if you make calls to external services like @peabnuts123 is doing. 

I've tried writing middleware to solve the problem. I tried with webserver middleware, but it doesn't seem to respond to Slack messages at all. Then I tried sending a bot response like "working on it..." to each message, but that fails if the input wasn't from a chat message (such as a dialog submission). I suppose the only option would be to add a response in the code for _every_ interaction, but that seems like an anti-pattern.

I definitely understand why doing this with async processes doesn't make sense, but neither does Slack's 3 second requirement. I +1 the option of re-adding `replyAcknowledge` to resolve this problem, as it seems to be a simple solution without introducing complexity.

Thanks :)

**Comment by AdrianSchneider** [comment]
The best I could come up with was to ignore slack retries (my use case: we'd rather manually retry than deal with duplicates being handled)

```
    webserver_middlewares: [
      (req: any, res: any, next: any) => {
        if (req.headers['x-slack-retry-num']) {
          res.status(200).send()
          return
        }
        next()
      },
```

**Comment by elisherer** [comment]
@AdrianSchneider 
I added the following:
```js
        res.set("X-Slack-No-Retry", "1"); // disable retries
        res.status(400).send();
```
Seems to do the trick after the first retry

see https://api.slack.com/apis/connections/events-api

**Comment by mattw114862** [comment]
None of this seems to work for me and I am banging my head against the wall trying to figure out why my slack bot keeps repeating the same response 2-3 times...It is only with QnA integration that it does this.
