### ISSUE TITLE
An error occured while sending message facebook/messenger

### ISSUE THREAD

**Issue by yestouscool** [howdyai/botkit#1685]
Users are sending message to my chatbot but the chatbot is not responding and it is giving the following error (after activating debug)
> App 22779 output: debug: API ERROR { message: 'An unknown error has occurred.',
> App 22779 output:   type: 'OAuthException',
> App 22779 output:   code: 1,
> App 22779 output:   fbtrace_id: 'CWf2LlNecRy' }
> App 22779 output: info: An error occurred while sending a message:  { message: 'An unknown error has occurred.',
> App 22779 output:   type: 'OAuthException',
> App 22779 output:   code: 1,
> App 22779 output:   fbtrace_id: 'CWf2LlNecRy' }

- Botkit version: 0.7.4
- Messaging Platform: Messenger
- Node version: 
- Os: Linux
- Any other relevant information:

**Comment by benbrown** [comment]
The access token in your config is probably incorrect.

**Comment by yestouscool** [comment]
But what is funny is some times it sends the message and sometimes it brings that error. Today I have really face that issue. 

And also the chatbot sometimes do not prompt any error but the user also do not receive any message from it.

**Comment by yestouscool** [comment]
It has started working by itself again. I talked to facebook guys the say it is a known issue.
