### ISSUE TITLE
carousel on messenger lite

### ISSUE THREAD

**Issue by bim-g** [howdyai/botkit#1688]
Hello, 
i use botkit for my messenger app, and recently i discover that messenger lite doesn't display carousel. what could be the problem.?

**Comment by jordanworner** [comment]
@bim-g I've come across this in the past and it seems Messenger Lite doesn't support templates, buttons or quick replies and there doesn't seem to be anyway to specify a fallback.

I don't know why this isn't documented on the Messenger Platform docs site so there isn't an official list of what Messenger Lite does and doesn't support. It might be useful to join  https://www.facebook.com/groups/messengerplatform, there have been quite a few people in the group asking for a way to identify if a user is on Messenger Lite.
