### ISSUE TITLE
Multi-platform?

### ISSUE THREAD

**Issue by mhjb** [howdyai/botkit#1697]
### Context:

- Botkit version: 0.6.21 (attempting to upgrade to 4.0.2, see #1696)
- Messaging Platform: Messenger & web (I hope)
- Node version: 12.4.0
- Os: Mac OS 10.14.5

I have a botkit bot that’s been working well in production for about 6 months (code [here](https://github.com/Citizen-AI/rentbot), live bot [here](https://m.me/rentbotnz)). It uses Dialogflow and Facebook Messenger. Now I want to add webchat too. Can botkit do multi-platform in one app?

I could have two different apps running, but there's a bunch of logic I've written to deal with Dialogflow's responses, and to talk to my db, that would feel ugly to duplicate.

**Comment by mhjb** [comment]
@benbrown any thoughts on this?

**Comment by benbrown** [comment]
You can bind the same handlers to a different controller in the same app, yes.  However you will likely need to adjust some platform specific things.

**Comment by mhjb** [comment]
Would you do that by passing an array of adapters to the controller?

**Comment by benbrown** [comment]
Oh sorry I missed the note about using 4.x.

No, what you'd do is set up a second webhook endpoint for the new adapter, and pass in the main Botkit turnhandler function -- something like the code here:

https://github.com/howdyai/botkit/blob/master/packages/botkit/src/core.ts#L677

**Comment by mhjb** [comment]
Thanks @benbrown. Sounds a bit beyond my skills.

**Comment by aidonsnous** [comment]
Is there a place where we can get a good documentation about different terms such **context**, **processActivity** ... to properly understand what they are cause it is the key to any customization one would like to bring in.

**Comment by benbrown** [comment]
The code would be something just like this:

```
const secondadapter = new SomeOtherAdapter();

            controller.webserver.post('/YOUR-CUSTOM-ENDPOINT, (req, res) => {
                // Allow the Botbuilder middleware to fire.
                // this middleware is responsible for turning the incoming payload into a BotBuilder Activity
                // which we can then use to turn into a BotkitMessage
                secondadapter.processActivity(req, res, controller.handleTurn.bind(controller)).catch((err) => {
                    console.error('Experienced an error inside the turn handler', err);
                    throw err;
                });
            });
```
