### ISSUE TITLE
Botkit-CMS Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by Parthiban-P** [howdyai/botkit#1698]
I am getting an error when integrate BotkitCMS to botkit

controller.usePlugin(new BotkitCMSHelper({
        uri: process.env.cms_uri,
        token: process.env.cms_token,
    }));

UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (D:\Chatbot\Botkit\Mybotkit\node_modules\botkit-plugin-cms\lib\cms.js:91:41)

My botkit Url  :: http://localhost:8626

URL response 
<h1>Botkit CMS</h1>

<a href="/admin">Access admin tools</a>

<h1>Botkit CMS</h1>

**Comment by adantoscano** [comment]
Try removing last / of your URI

**Comment by Parthiban-P** [comment]
same issue exists even after Try removing last / of your URI

**Comment by adantoscano** [comment]
Which Botkit version are you using?

**Comment by Parthiban-P** [comment]
botkit 4.0.2
  I have integrated with BOTKIT web 

 "dependencies": {
    "botbuilder-adapter-web": "^1.0.3",
    "botbuilder-storage-mongodb": "^0.9.5",
    "botkit": "^4.0.2",
    "botkit-plugin-cms": "^1.0.0",
    "dotenv": "^7.0.0",
    "http": "0.0.0",
    "https": "^1.0.0",
    "request-promise": "^4.2.4"
  }

I have cloned latest botkit-crm report recently , i ran it without modifying any scripts

**Comment by adantoscano** [comment]
There is a new version of plugin-cms, try updating

**Comment by Parthiban-P** [comment]
No luck , i have installed "botkit-plugin-cms": "^1.0.1"

**Comment by adantoscano** [comment]
As default [botkit-cms](https://github.com/howdyai/botkit-cms#readme) runs on 3000. First ensure you are running it at your desired port

**Comment by Parthiban-P** [comment]
i have modfifed the CMS port since my bot is running in 3000!

**Comment by adantoscano** [comment]
Can you access to cms panel?

**Comment by Parthiban-P** [comment]
yeah i can access the CMS Admin panel

**Comment by adantoscano** [comment]
add a console log of the result just before the `JSON.parse()` at `\node_modules\botkit-plugin-cms\lib\cms.js:91:41`. It's quite messy but I don't know other way to debug it

**Comment by Parthiban-P** [comment]
console log says "Invalid token" !! when i give proper token it works fine !!! Thanks for your time !!  but we could have received the same error message from cms-plugin !!!

**Comment by adantoscano** [comment]
Welcome!! Yup should be handled by cms plugin, but i don't know why that try...catch is not working as expected.
