### ISSUE TITLE
Filter received convo messages in middlewares

### ISSUE THREAD

**Issue by adantoscano** [howdyai/botkit#1702]
### Are you sure this is an issue with the Botkit core module?
Yes

### What are you trying to achieve or the steps to reproduce?

I use `botkit-middleware-dialogflow` in ingest middleware, but I don't need to send to dialog messages that responds to a convo question. At which part of the middleware can I realize that the message is to answer to a convo?

### Context:

- Botkit version: 4.0.2
- Messaging Platform: Web
- Node version: 10.15.0
- Os: Linux
- Any other relevant information: Botkit FTW

**Comment by benbrown** [comment]
This will be achieved by the new `interpret` middleware that fires AFTER dialogs are continued, but BEFORE any triggers or events are fired.
