### ISSUE TITLE
Feature request: Web adapter new conversation for same user

### ISSUE THREAD

**Issue by shaikatzir** [howdyai/botkit#1704]
The webadapter sets the conversation Id from user id:
https://github.com/howdyai/botkit/blob/master/packages/botbuilder-adapter-web/src/web_adapter.ts#L115
In order to have a new conversation for the same user, can the conversation id be added to the message too, instead of using the user Id?

**Comment by benbrown** [comment]
Why do you want to have a different conversation id?
