### ISSUE TITLE
how to bot.say or bot.reply without hears anything in webadapter version 4?

### ISSUE THREAD

**Issue by thuanhan** [howdyai/botkit#1705]
I try to reply web client without hears by:
`bot.say({text: 'ok', user:'user', channel:'channel'})`
or
`let bot = await controller.spawn();
  await bot.startConversationWithUser(message.user)
  await bot.say('ok')`
or
`global.bot.startConversationWithUser({user:'user', channel: 'channel'},function(err, dm){
         dm.say('ok')
})`
but nothing success. How to reply or say without hears.

**Comment by adantoscano** [comment]
https://www.botkit.ai/docs/v4/core.html#sending-alerts-and-scheduled-messages

**Comment by thuanhan** [comment]
> https://www.botkit.ai/docs/v4/core.html#sending-alerts-and-scheduled-messages

I followed this doc but there is an error:
(node:4102) UnhandledPromiseRejectionWarning: Error: bot.startConversationWithUser(): missing serviceUrl.
    at BotWorker.<anonymous> (/Users/thuanhan/Workspace/chatbot/node_modules/botkit/src/botworker.ts:249:44)
    at Generator.next (<anonymous>)
    at /Users/thuanhan/Workspace/chatbot/node_modules/botkit/lib/botworker.js:7:71

**Comment by adantoscano** [comment]
Which platform are u developing for?

**Comment by thuanhan** [comment]
The platform is botkit for the web https://botkit.ai/docs/v4/reference/web.html

**Comment by davidfrtala** [comment]
I'm also having a trouble with this.
I've managed to spawn a bot, change context (bot.startConversationWithUser) and successfully sent a message.
But the problem is, this approach basically avoids all my middleware layers, attached to adapter. For instance, one of my middlewares is saving a message to DB (msg history).

I need to trigger `runMiddleware` adapter function with a custom message and then, in a callback TurnContext function call `sendActivity`

**Comment by davidfrtala** [comment]
Preview of my workaround

```
const context = new TurnContext(adapter, activity);

adapter.runMiddleware(
  context,
  async (turnContext: TurnContext): Promise<void> => {
    const reference = TurnContext.getConversationReference(turnContext.activity);
    const turnActivity = TurnContext.applyConversationReference(activity, reference, true);

    // We need to avoid "turnContext.sendActivity", because under the hood, it again swaps
    // recipient's id with sender (as it's calling "applyConversationReference" without "isIncoming = true"
    // therefore, we are manually calling private context methods, copying the `sendActivity` functionality
    turnContext.emit(turnContext._onSendActivities, [turnActivity], () => {
      return adapter.sendActivities(context, [turnActivity]);
    });
  }
);
```

**Comment by benbrown** [comment]
> But the problem is, this approach basically avoids all my middleware layers, attached to adapter. For instance, one of my middlewares is saving a message to DB (msg history).

INTERESTING!  This is a bug that should be addressed.

**Comment by hikariru** [comment]
> https://www.botkit.ai/docs/v4/core.html#sending-alerts-and-scheduled-messages

Can't we use that feature on 4.x yet? use it mainly on my bot...

**Comment by deepakmahakale** [comment]
@thuanhan I know it's been more than 2 years

But were you able to solve this? 

Currently, I am in a similar situation where I want to send a message to web adapter based on an API call

```
controller.webserver.get('/api/from_some_server', async (req, res) => {

  // here I want to send the message to user
  // I have the user_id 
  let bot = await controller.spawn();
  await bot.say('ok');

});
```
