### ISSUE TITLE
BotkitConversation and Slack Buttons

### ISSUE THREAD

**Issue by apemberton** [howdyai/botkit#1711]
I can't seem to get BotkitConversation to respond to block_actions from Slack buttons. Is this still possible in v4? What are the steps to configure?

```
await convo.ask({
                text: ['Looks like you asked a question; do you want help?'],
                channelData: {
                    blocks: [
                        {
                            "type": "section",
                            "text": {
                                "type": "mrkdwn",
                                "text": 'Looks like you asked a question; do you want help?'
                            }
                        },
                        {
                            "type": "actions",
                            "elements": [
                                {
                                    "type": "button",
                                    "text": {
                                        "type": "plain_text",
                                        "text": "Yes"
                                    },
                                    "value": "yes"
                                }   
                            ]
                        }
                    ], 
                    
                }
            }, 
            async(response, convo, bot) => {
                await bot.say('Oh your response is ' + response);
            }
            , {key: 'asking'});
```

### What was the result you received?

Handlers never get fired.

### What did you expect?

Expected the handler to get fired.

### Context:

- Botkit version: v4
- Messaging Platform: Slack
- Node version: 
- Os: Mac
- Any other relevant information:

**Comment by apemberton** [comment]
I think I've found that slack buttons will not work as is... in botbuilder-core/activityHandler.js, it is assumed only activities of type message (`context.activity.type === ActivityTypes.Message`) will trigger dialogs... block_actions are ActivityTypes.Events so don't trigger... still investigating...

**Comment by sfny** [comment]
I'd also like conversations with buttons / blocks.

**Comment by benbrown** [comment]
It is possible to achieve this with a middleware that changes the activity type.
