### ISSUE TITLE
TwilioSMSBot 

### ISSUE THREAD

**Issue by Arrow2702** [howdyai/botkit#1714]
How to trigger an alert text with a twilio number to any other number without texting first for bot to listen?

### Context:

- Botkit version:4.0.2
- Messaging Platform:Twilio
- Node version: 10.16.0
- Os:Mac

**Comment by benbrown** [comment]
See the docs here:

https://botkit.ai/docs/v4/reference/twilio-sms.html#startConversationWithUser
