### ISSUE TITLE
Can't verify v4.x bot with slack events api

### ISSUE THREAD

**Issue by yaron-idan** [howdyai/botkit#1726]
### What was the result you received?
botkit boilerplate generated with `npm install -g yo generator-botkit` and configured to use slack cannot be verified using the slack events api challenge. The bot is responding with `slack/receive 404 error` when slack tries to request this endpoint for verification. Without the events api verified, the bot can't seem to listen to messages on slack.

### What did you expect?
When I used [this boilerplate](https://github.com/howdyai/botkit-starter-slack) and followed [these instructions](https://botkit.ai/docs/provisioning/slack-events-api.html) the bot was verified successfully and the bot could listen to messages sent on slack.

### Screenshots and animated GIFs
Image of error from api.slack.com - 
![image](https://user-images.githubusercontent.com/13436307/61375092-a94dda80-a8a6-11e9-909a-41b39779d2a9.png)

### Context:

- Botkit version: 4.0.2
- Messaging Platform: Slack
- Node version: v10.15.3
- Os: MacOs
- Any other relevant information:

**Comment by benbrown** [comment]
The webhook url in v4 has changed to `/api/messages/`

**Comment by tribakzero** [comment]
Is this documented elsewhere?
Every document so far points to the slack/receive endpoint.

**Comment by yaron-idan** [comment]
This [PR](https://github.com/howdyai/botkit-docs/pull/37) updated the docs to reflect the new route but it's not reachable via the docs website.
Not sure how to fix that because I'm not familiar with the docs website plumbing.
