### ISSUE TITLE
botbuilder-adapter-web message.text length restriction

### ISSUE THREAD

**Issue by mhjb** [howdyai/botkit#1727]
The botbuilder-adapter-web package appears to have a restriction of about 256 characters on messages received by the web adapter server. Longer messages appear to send correctly in the trigger function ([here](https://github.com/howdyai/botkit/blob/master/packages/botbuilder-adapter-web/client/client.js#L31)), but aren't noticed by the server. 

Does anyone know where that message.text length restriction lives?

**Comment by benbrown** [comment]
There is not a length restriction enforced by Botkit.  I can't reproduce this issue.

**Comment by mhjb** [comment]
Sorry @benbrown — I figured it out. It was botkit-middleware-dialogflow erroring any time anything longer than that attempted to be sent to Dialogflow.
