### ISSUE TITLE
Cannot read property 'sendActivity' of undefined with controller.spawn()

### ISSUE THREAD

**Issue by MDSLKTR** [howdyai/botkit#1729]
Botkit version: 4.0.2
Platform: Slack
Node.js version 10.16.0
OS: Debian 9

Expected:
I can send a message to a channel with my spawned instance of the bot.

Actual:
When calling
````
let bot = await controller.spawn({});
````

any attempt in sending a message will return the error below. I think this is related to it requiring some sort of context. But in the event that i need to send a message with `bot.say()` to a public channel there is not context. Listening to channels and responding works perfectly fine but all attempts at using controller.spawn won't allow me to send messages in response webhooks from different sources. This worked fine with the old 0.x API when calling `startRTM` beforehand.

````
TypeError: Cannot read property 'sendActivity' of undefined
0|server  |     at SlackBotWorker.<anonymous> (/var/www/slackbot/node_modules/botkit/lib/botworker.js:100:60)
0|server  |     at Generator.next (<anonymous>)
0|server  |     at /var/www/slackbot/node_modules/botkit/lib/botworker.js:7:71
0|server  |     at new Promise (<anonymous>)
0|server  |     at __awaiter (/var/www/slackbot/node_modules/botkit/lib/botworker.js:3:12)
0|server  |     at _controller.middleware.send.run (/var/www/slackbot/node_modules/botkit/lib/botworker.js:96:94)
0|server  |     at next (/var/www/slackbot/node_modules/ware/lib/index.js:82:27)
0|server  |     at Ware.run (/var/www/slackbot/node_modules/ware/lib/index.js:88:3)
0|server  |     at Promise (/var/www/slackbot/node_modules/botkit/lib/botworker.js:96:50)
0|server  |     at new Promise (<anonymous>)
0|server  |     at SlackBotWorker.<anonymous> (/var/www/slackbot/node_modules/botkit/lib/botworker.js:94:20)
0|server  |     at Generator.next (<anonymous>)
0|server  |     at /var/www/slackbot/node_modules/botkit/lib/botworker.js:7:71
0|server  |     at new Promise (<anonymous>)
0|server  |     at __awaiter (/var/www/slackbot/node_modules/botkit/lib/botworker.js:3:12)
0|server  |     at SlackBotWorker.say (/var/www/slackbot/node_modules/botkit/lib/botworker.js:93:16)
0|server  | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
0|server  | TypeError: Cannot read property 'sendActivity' of undefined
0|server  |     at SlackBotWorker.<anonymous> (/var/www/slackbot/node_modules/botkit/lib/botworker.js:100:60)
0|server  |     at Generator.next (<anonymous>)
0|server  |     at /var/www/slackbot/node_modules/botkit/lib/botworker.js:7:71
0|server  |     at new Promise (<anonymous>)
0|server  |     at __awaiter (/var/www/slackbot/node_modules/botkit/lib/botworker.js:3:12)
0|server  |     at _controller.middleware.send.run (/var/www/slackbot/node_modules/botkit/lib/botworker.js:96:94)
0|server  |     at next (/var/www/slackbot/node_modules/ware/lib/index.js:82:27)
0|server  |     at Ware.run (/var/www/slackbot/node_modules/ware/lib/index.js:88:3)
0|server  |     at Promise (/var/www/slackbot/node_modules/botkit/lib/botworker.js:96:50)
0|server  |     at new Promise (<anonymous>)
0|server  |     at SlackBotWorker.<anonymous> (/var/www/slackbot/node_modules/botkit/lib/botworker.js:94:20)
0|server  |     at Generator.next (<anonymous>)
0|server  |     at /var/www/slackbot/node_modules/botkit/lib/botworker.js:7:71
0|server  |     at new Promise (<anonymous>)
0|server  |     at __awaiter (/var/www/slackbot/node_modules/botkit/lib/botworker.js:3:12)
````

Thanks in advance!

**Comment by benbrown** [comment]
You _do_ need to set a context for the message to be sent in. The bot object provides several helper functions to do that.  

https://botkit.ai/docs/v4/platforms/slack.html#start-or-resume-conversations-with-people

**Comment by MDSLKTR** [comment]
Thanks for the quick reply. However the bot doesn't need to start a private conversation or take the conversation into dms. It should simply post a message into the channel. There is no need to reply or interact. Maybe i am missing something but the docs aren't telling me how to solve this using a simple `bot.say` or what that context would need to be. Maybe i am missing something.

**Comment by benbrown** [comment]
Your bot doesn't exist in a single channel. There is no default.  It has to be told where to take the action.

So you'll need to use startConversationInChannel.  In that case, the user ID is really used, but it is a necessary part of setting up the context. If you don't expect any replies, you could put a fake value in for user id.

**Comment by MDSLKTR** [comment]
I see. This is helpful, will try that 👍

**Comment by designbyadrian** [comment]
I had to add this deep param list to `spawn` for it to no longer throw errors at me:

```javascript
const bot = await controller.spawn({
  activity: {
    conversation: {
      team: MY_TEAM_ID,
    },
 },
})
```

**Comment by rf** [comment]
Thanks @designbyadrian -- this worked for me.

**Comment by 8bu** [comment]
> 
> 
> Thanks @designbyadrian -- this worked for me.

Sorry to bring it up again but I've tried @designbyadrian code. But it didn't work

```typescript
const sendSlackMsg = async (msg: string) => {
    const bot = await controller.spawn({
        activity: {
          conversation: {
            team: TEAM_ID,
          },
       },
    });
    await bot.say({
        channel: slackTargetChannel,
        text: msg,
    })
}
```

Any other solution here? I just need a func to send schedule message.
