### ISSUE TITLE
Rocket.Chat doesn't include support for quick_replies

### ISSUE THREAD

**Issue by refai2016** [howdyai/botkit#1742]
Hello,
I have managed to connect (Botkit to Rocket.Chat) successfully, however, I have noticed that the Rocket.Chat doesn't include support for (quick_replies). Can you please help me resolve this issue?

![2019-07-25_17-03-00](https://user-images.githubusercontent.com/22276530/61882360-0bd75400-af01-11e9-8599-01d0dea74c0b.png)

---------------------------------------------------------

![2019-07-25_17-02-30](https://user-images.githubusercontent.com/22276530/61882382-1560bc00-af01-11e9-8e99-830d2be8bca1.png)

**Comment by refai2016** [comment]
Hello, 
I have managed to connect (Botkit to Rocket.Chat) successfully, however, I have noticed that the Rocket.Chat doesn't include support for (quick_replies). Can you please help me resolve this issue?

![2019-07-25_17-02-30](https://user-images.githubusercontent.com/22276530/61881910-19400e80-af00-11e9-9f04-22ec15556679.png)

---------------------------------------------------

![2019-07-25_17-03-00](https://user-images.githubusercontent.com/22276530/61881911-19d8a500-af00-11e9-9d7c-3641e3744fdd.png)

**Comment by benbrown** [comment]
I don't know anything about rocket chat.  Does it support quick replies?
