### ISSUE TITLE
Add info about endpoint URLs and configuration to Slack docs

### ISSUE THREAD

**Issue by benbrown** [howdyai/botkit#1749]
There is currently some confusion about the included out-of-the-box setup for Slack in Botkit v4. In prior versions of Botkit, the starter kit included more information that is now missing or hard to find.

The default URL for installing a multi-team Slack bot built with Botkit v4's yeoman template is: `http://yourbothost:3000/install`

The default oauth callback URL is: `http://yourbothost:3000/install/auth`

The default endpoint for receiving messages from slack is: `http://yourbothost:3000/api/messages`

**Comment by ianfixes** [comment]
I did find this a bit confusing.  I was walking through https://botkit.ai/docs/provisioning/slack-events-api.html and it mentions `https://YOURURL/slack/receive`.  

After some further reading, I think this is meant to be the same as the `Webhook endpoint online:  http://localhost:3000/api/messages` that pops up when you run a botkit app.  Do I have that right?

**Comment by benbrown** [comment]
@ianfixes yes.  the /api/messages version is correct.

**Comment by benbrown** [comment]
This doc has been updated!
