### ISSUE TITLE
Couldn't connect Bot to botbuilder-adapter-twilio-sms

### ISSUE THREAD

**Issue by HemanthKumarBodemu** [howdyai/botkit#1751]
Hello,

We are using microsoft bot framework 4.0 and we wanted to enable sms channel via Twilio. We do Configured at Azure level and even twilio level to get that enabled, but bot is not responding back to twilio sms.

const { TwilioAdapter } = require('botbuilder-adapter-twilio-sms');

const SMSAdapter = new TwilioAdapter({
        twilio_number: 'Mobile Number',
        account_sid: 'xxxxxxxxx',
        auth_token: 'xxxxxxxxxxx'
 });
server.post('/api/messages', (req, res) => {
     SMSAdapter.processActivity(req, res, async (context) => {
            await context.sendActivity('I heard a message!');
     });
});

**Package versions:**
"botbuilder": "4.4.0",
"botbuilder-adapter-twilio-sms": "^1.0.2",

Code is breaking at processActivity itself. I am using Bot Framework with Node.js. Please help us in finding the issue.

**Comment by benbrown** [comment]
If you are using the Twilio channel service through the Azure portal, you do not need to use the specialized botbuilder-adapter-twilio-sms package.  All you need is the normal Bot Framework Adapter that is part of `botbuilder`. 

The separate twilio adapter in this package is for communicating directly with Twilio - bypassing the Bot Framework channel service.

**Comment by HemanthKumarBodemu** [comment]
I do tried that, but am getting below exception at 
**adapter.processActivity(req, res, async (turnContext) => {
// Bot logic
});**

"SyntaxError: Unexpected token T in JSON at position 0"

**Comment by benbrown** [comment]
Hard to say with such a small code example.
