### ISSUE TITLE
Clarify docs around spawning a bot for proactive messages in Slack

### ISSUE THREAD

**Issue by benbrown** [howdyai/botkit#1754]
Currently the docs only mention using the teamid as a parameter in reference to multi-tenancy. 

This is inaccurate, to spawn a bot for any type of proactive message, the teamid is required.

**Comment by warnero** [comment]
I've been banging my head against this issue for a day or so. How in the world am I supposed to use controller.spawn to get a new instance? What config variables do I need to pass in in order for this to work properly?

**Comment by warnero** [comment]
Turns out it was my async/await and my for loop causing some issues.

**Comment by designbyadrian** [comment]
It's, indeed, not clear in the docs that controller.spawn returns a promise. I'm still having problems with this:

```javascript
controller.spawn({})
  .then(async thisDoesntSeemToBeABotInstance => {
    // await thisDoesntSeemToBeABotInstance.say is invalid  
  })
```

**Comment by benbrown** [comment]
I've added detail here:
https://github.com/howdyai/botkit/blob/master/packages/docs/reference/slack.md#create-a-new-slackbotworker

as well as here:
https://github.com/howdyai/botkit/tree/master/packages/botbuilder-adapter-slack#spawn-a-worker-for-a-specific-team
