### ISSUE TITLE
Unable to send message using botbuilder-adapter-webex

### ISSUE THREAD

**Issue by RamPrasadMeenavalli** [howdyai/botkit#1755]
I am using the WebexAdapter from botbuilder-adapter-webex to connect my BotBuilder bot with Webex teams.

I have used the following code
```Javascript
const server = restify.createServer();
server.listen(process.env.port || process.env.PORT || 3978, () => {
    console.log(`\n${ server.name } listening to ${ server.url }`);
    console.log(`\nGet Bot Framework Emulator: https://aka.ms/botframework-emulator`);
    console.log(`\nTo test your bot, see: https://aka.ms/debug-with-emulator`);
});
var webexOptions = {
    access_token: process.env.ACCESS_TOKEN,
    public_address: process.env.PUBLIC_ADDRESS,
    secret: process.env.SECRET
}

const adapter = new WebexAdapter(webexOptions);
server.use(restify.plugins.bodyParser());
adapter.registerWebhookSubscription('/api/messages');
adapter.getIdentity();
server.post('/api/messages', (req, res) => {
    adapter.processActivity(req, res, async (context) => {
        await context.sendActivity('Hey human!!');
    });
```
When I post a message to the bot (in Webex Teams) the webhook gets called and the bot receives the user's message.
At the step 'await context.sendActivity('Hey human!!');' it fails with the below error message

BadRequest: Unable to retrieve content.
POST https://api.ciscospark.com/v1/messages
WEBEX_TRACKING_ID: spark-js-sdk_9ba910cb-43ea-4800-88be-dde33e7ba825_7

I am using the following packages
"botbuilder": "~4.5.1",
"botbuilder-adapter-webex": "^1.0.2",
"restify": "~8.3.3"
Node version : v10.15.3

**Comment by benbrown** [comment]
@RamPrasadMeenavalli Did you ever sort this out?

I am not able to reproduce this issue.

**Comment by RamPrasadMeenavalli** [comment]
@benbrown - No. I haven't checked this after I reported the issue.
I will check it again if I still face the issue. Thank you.

**Comment by AdityaJasti** [comment]
@benbrown Hi Ben, I recently was working on an integration of MS Bot with WebEx Teams and faced this issue. Can you please help.
