### ISSUE TITLE
slack : dynamically generated blocks/attachments not working in v4.5.0

### ISSUE THREAD

**Issue by convexhull** [howdyai/botkit#1756]
Here's where I landed with this:

In 4.5, you will be able to pass in an async function for quick_replies, blocks, and attachments that are then responsible for generating the actual content.

The signature of these functions is all basically the same:

```async (line, vars) => { return [stuff]) }```

line is the actual template of the message passed in to convo.say or convo.ask or whatever, and vars is the _current_ state of convo.vars whenever the function is called.

This way, there are no new methods or magical keys or special tokens or whatever! I'd love to hear any feedback anyone has!

_Originally posted by @benbrown in https://github.com/howdyai/botkit/issues/1661#issuecomment-514401672_

**Comment by convexhull** [comment]
Hey @benbrown  the above fix is not working for me on slack version of botkit 4.5.0. here is what i tried :
```
    convo.addQuestion(  async (line, vars)=> {
        return { text : "Placeholder", blocks : [
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": "You can add a button alongside text in your message. "
                },
                "accessory": {
                    "type": "button",
                    "text": {
                        "type": "plain_text",
                        "text": "Button",
                        "emoji": true
                    },
                    "value": "click_me_123"
                }
            }
        ]};
    },
    [
        {
            pattern  :"yes",
            type : 'string', 
            handler : async (res, bot, convo) => {
                console.log("exec")
            }
        }
    ],
    {},
    "default");
```


It gave the following error : 

```
Error sending activity to API: { Error: An API error occurred: no_text
    at platformErrorFromResult (/home/ace_of_spades/projects/startiq/startiq0.7/node_modules/@slack/client/dist/WebClient.js:770:42)
    at __await.makeRequest.then (/home/ace_of_spades/projects/startiq/startiq0.7/node_modules/@slack/client/dist/WebClient.js:484:39)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 'slackclient_platform_error',
  data:
   { ok: false,
     error: 'no_text',
     scopes: [ 'identify', 'bot:basic' ],
     acceptedScopes: [ 'chat:write:bot', 'post' ] } }
``` 

I tried removing the blocks , and just sending the text. Doesn't work even then. I am unable to find the reason for this error. Seems above fix does not work with Slack platform.

**Comment by benbrown** [comment]
The function is passed in as part of the message template, not a replacement for the entire template.
See an example here:
https://botkit.ai/docs/v4/conversations.html#dynamic-quick-replies-and-attachments

**Comment by Benedict** [comment]
@convexhull The following works for me:

`convo.addQuestion({text : "Placeholder",
        blocks: async(template, vars) => { 
            return [{
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": "You can add a button alongside text in your message. "
                },
                "accessory": {
                    "type": "button",
                    "text": {
                        "type": "plain_text",
                        "text": "Button",
                        "emoji": true
                    },
                    "value": "click_me_123"
                }
            }]
        }
    },...`

**Comment by convexhull** [comment]
Hi Ben and Benedict, yes that solved the problem !
Thanks a lot for your help!
