### ISSUE TITLE
Broken link to changelog.md in documentation advanced.md

### ISSUE THREAD

**Issue by etiennellipse** [howdyai/botkit#1757]
1. Navigate to https://botkit.ai/docs/v4/advanced.html#whats-different-between-07-and-40
1. The link to the changelog right under this title is broken (404); 

It links to https://github.com/howdyai/botkt/blob/master/changelog.html, it should be https://github.com/howdyai/botkt/blob/master/changelog.md

My understanding is that the engine used to render the documentation for the web transforms every md extension to html. This won't work for an external link.

I would gladly submit a PR, but I do not know what is used to host the documentation site; therefore I cannot test it.

**Comment by benbrown** [comment]
Finally fixed this! Thanks.
