### ISSUE TITLE
Cannot find module ...

### ISSUE THREAD

**Issue by sergelerner** [howdyai/botkit#176]
I am using Meteor 1.3.1 
Installed botkit via npm

While importing botkit 

`
import Botkit from 'botkit';
`

I am getting the following error

`
Uncaught Error: Cannot find module '/node_modules/botkit/lib/CoreBot.js'
`

Which is so strange because the directory path does exist with the file and everything.

I am using many npm modules, this is the only one which is not found.

**Comment by sergelerner** [comment]
Ok my bad, I have moved the code to the server dir and now everything works : )

**Comment by aner87** [comment]
sorry, I'm getting the same error and I can't figure it out how to solve it!
can you please post me what code you moved on the server dir?
thanks mate
