### ISSUE TITLE
Can not require FacebookAPI

### ISSUE THREAD

**Issue by LuckyLuo** [howdyai/botkit#1762]
In the Botkit document, it mentioned to use the FacebookAPI like this:
**const { FacebookAPI } = require('botbuilder-adapter-facebook');**

https://botkit.ai/docs/v4/reference/facebook.html#FacebookAPI

But actual not, it is not exported in the botbuilder-adapter-facebook src/index.ts

Is it missed from the index.ts by mistake? 

Thanks

**Comment by benbrown** [comment]
Ah, interesting!  The inclusion of that line in the docs is a result of the doc generating process - the facebookapi class is not intended to be used on its own but rather used internally by the adapter.

That said, there is no harm in exporting it.

**Comment by LuckyLuo** [comment]
Thanks for the quick reply, Ben. can I add it into the index.ts’s export
and raise a code pull request?

Cheers

**Comment by benbrown** [comment]
go for it

**Comment by benbrown** [comment]
This has been fixed in 1.0.5 of `botbuilder-adapter-facebook`

Thanks @LuckyLuo!
