### ISSUE TITLE
Access Preferences?

### ISSUE THREAD

**Issue by KalebClark** [howdyai/botkit#177]
Hi, awesome project! I want to access preferences so my slack bot shows real name instead of username. Is there a way to do that currently?

Thanks,
-Kaleb

**Comment by peterkinmond** [comment]
<img width="1038" alt="screen shot 2016-04-18 at 9 31 49 pm" src="https://cloud.githubusercontent.com/assets/779389/14627831/0e9304ce-05ad-11e6-82f1-8e3b538aa538.png">

Are you talking about using the `Customize Name` vs `First & Last Name` fields from the bot's settings page? Can you provide more details or screenshot of what you're trying to do?

**Comment by peterswimm** [comment]
Closing the issue for now, If you have any updates, please feel free to reopen!
