### ISSUE TITLE
BotkitConversation with quick_replies in onboarding

### ISSUE THREAD

**Issue by valdu02100** [howdyai/botkit#1770]
I'm trying to get started with Botkit Core 4+ with botbuilder-adapter-facebook.

I would like to create a starter conversation with post_back 'GET_STARTED' with questions (quick_replies) and text. For quick_replies, I only want to capture the answers and continue the conversation. 
I get lost in the documentation. Does anyone have an example code with Botkit Core 4+ for Messenger capturing 'GET_STARTED' and using quick_replies in a discussion?

Thank you in advance for your help

**Comment by AngelosNaoumis** [comment]
Did you manage to find this? I am looking for something similar.

**Comment by valdu02100** [comment]
I never arrive to use it. 
I use Botman now....
