### ISSUE TITLE
Update yeoman boilerplate to use typescript

### ISSUE THREAD

**Issue by yaron-idan** [howdyai/botkit#1772]
Are there any plans to make the yeoman generator produce a typescript boilerplate instead of javascript? I was wondering if this is something currently being done/planned to be done in the future.
Would a PR implementing it be welcome?
Further details below -

### What are you trying to achieve or the steps to reproduce?
Write my bot completely in typescript.

### What was the result you received?
Since bot.js is written in JS, I would have to rewrite it in typescript to have my entire project in TS. Otherwise there are some weird intellisense errors when trying to infer types.

### What did you expect?
Yeoman generator to provide support for creating a TS boilerplate.

- Botkit version: 4.5
- Messaging Platform: Slack
- Node version: 10.15.3
- Os: OSX

**Comment by benbrown** [comment]
There is not a current plan to do this, but I am certainly open to a PR.

However, to achieve this, all of the various platform example features would need to be ported to TS and they'd need to be maintained in parallel.

**Comment by yaron-idan** [comment]
Hmmm...
That makes sense, but definitely more than I can chew on.
Perhaps there's a way to make the transition more gradual? Offer the user the choice of a typescript boilerplate for the platforms who supports that?

If this doesn't sound like a good plan I'll just tweak the boilerplate locally and close the issue, but I do feel that in the long run this should probably be the direction it takes. Perhaps the JS boilerplates can be slowly deprecated when resources for rewriting in TS are available.

**Comment by benbrown** [comment]
The other Bot Framework yeoman template also offers the choice between TS and JS - it is not out of the question.  It just currently requires some extra work due to the way the sample features are included.

**Comment by yaron-idan** [comment]
What do you mean by "other Bot Framework" yeoman template?
There's another generator? or is that another path that can be chosen with the botkit generator?
I've tried to see if you might mean the botframework generator but it also seem to produce JS exclusively.

**Comment by benbrown** [comment]
I mean [this one](https://www.npmjs.com/package/generator-botbuilder), used to scaffold out Bot Framework bots.
