### ISSUE TITLE
How to send a spontaneous message from bot? Doc example not clear...

### ISSUE THREAD

**Issue by dfischer** [howdyai/botkit#178]
The doc shows examples of this:

```
bot.say(
  {
    text: 'my message text',
    channel: 'C0H338YH4' // a valid slack channel, group, mpim, or im ID
  }
);
```

I get this error:

`Error: Cannot use the RTM API to send messages.`

Which I assume means figure out how to use the webhook part but I'm not really sure the flow here. What I want to do is given a condition, then outreach to a particular user or channel about something. Let's say a new user signed up to the slack team, sending them a hello message. Would a webhook flow be used for that?

**Comment by andrewholsted** [comment]
Have you tried bot.startPrivateConversation

**Comment by andrewholsted** [comment]
@dfischer A) Are you sure your bot is connected to the RTM API and B) Have you tried `bot.startPrivateConversation`? I use the latter to do what you are describing above in my callback to `controller.on('create_bot', function() { })`

**Comment by dfischer** [comment]
I got it now. Thanks, your suggestion helped.
