### ISSUE TITLE
Equivalent of 'findConversation' in botkit 4.0x

### ISSUE THREAD

**Issue by naikus** [howdyai/botkit#1781]
Botkit version: 4.0x

What is the equivalent of "findConversation" in the 4.0x version of botkit? I have the following code in an earlier version:
```javascript
          botController.on("reconnect", (bot, message) => {
            console.log(`Reconnected!! ${message.user}:${message.channel}`);
            bot.findConversation(message, convo => {
              if(convo) {
                   // do something
              }else {
                  // do something else
              }
            });
          });
```

How should be this migrated?

I also have a middleware with calls to ```findConversation```
```javascript
module.exports = {
  send(bot, message, next) {
    bot.findConversation(message, convo => {
    });
  },

  receive(bot, message, next) {
    bot.findConversation(message, convo => {
    });
  }
};
```
Edit:
I just thought I'd mention @benbrown Thanks in advance

**Comment by benbrown** [comment]
This can also be achieved using `bot.context.activeDialog`

**Comment by benbrown** [comment]
I updated the reply above because it was incorrect.

The real path to activeDialog is `bot.getConfig('dialogContext').activeDialog`

I am going to introduce a method to access this.
