### ISSUE TITLE
Slack retrying messages when bot is using CMS and the conversation is long

### ISSUE THREAD

**Issue by amaralex** [howdyai/botkit#1788]
Hey!

I've recently tried to move my bot from 0.7 to v4.5 and noticed that what worked great before stopped working in 4.5, namely botkit failed to reply within 3 seconds time which in turn triggers Slack to send message retries.

The source of it is that new version stopped sending immediate ACKs to POST requests issued by slack. I found somewhat similar issue discussed here earlier https://github.com/howdyai/botkit/issues/1684 

My question is, i'm not doing anything myself, i'm just using default generated code
```

    /* catch-all that uses the CMS to trigger dialogs */
    if (controller.plugins.cms) {
        controller.on('direct_message,direct_mention,mention', async (bot, message) => {
            let results = false;
            try{
                results = await controller.plugins.cms.testTrigger(bot, message);
            } catch (err){
                console.log(err)
            }

            if (results !== false) {
                // do not continue middleware!
                return false;
            }
        });
    }
```

If slack message contains a trigger for conversation defined in CMS and that conversation has, say, 10 messages to send, the 200 OK ack message won't be sent back before all 10 messages are pushed out...

### Context:

- Botkit version: 4.5
- Messaging Platform: Slack

**Comment by benbrown** [comment]
It should send the 200 after the _first message_ in the dialog is sent back to Slack.

Is the call out to the CMS taking a long time?

One way around this is to return a promise from the handler, and do the work inside that promise. This will resolve the handler promise and send the 200 while your bot continues to wait for the CMS.

This requires you to call `await bot.changeContext(message.reference)` inside the promise.

**Comment by amaralex** [comment]
Hi Ben, thanks for looking into it.

1. The call to CMS happens really fast, but the 200 OK is not being sent back until after all messages in the dialog are pushed out.

2. Hm, not sure I understand what the workaround is...
The handler is already defined as async, so it returns the Promise already..
`controller.on('direct_message,direct_mention,mention', async (bot, message) => {`

**Comment by amaralex** [comment]
**UPDATE:** I was wrong regarding 
> call to CMS happens really fast

actually call to `await controller.plugins.cms.testTrigger(bot, message);` does not return until all messages are pushed out.

I have tried to trace it and diged deeper. Found a bunch of nested `await` calls going all the way to `beginDialog` and `runStep` -> `onStep` -> `sendActivity()` and then `step.next()` -> `resumeDialog()` -> `runStep()`

so basically the Promise returned by `cms.testTrigger()` never resolves before all messages are pushed out... and that triggers slack Timeout.

**Comment by benbrown** [comment]
@amaralex that is not the expected behavior of dialogs.  Once the dialog begins, should resolve after sending its first message (or first N messages until a prompt is encountered).

I will have to do some experiments and research to see if this is a bug or something else weird!

**Comment by amaralex** [comment]
> or first N messages until a prompt is encountered

@benbrown in my test the conversation looked like 10 messages with no prompt at all. So may be it is an "expected" behaviour after all but it still triggers slack timeout

**Comment by benbrown** [comment]
thank you for the info, I'll dig in asap.
