### ISSUE TITLE
Incoming messages augmented by botkit middlewares are not available to conversation handlers

### ISSUE THREAD

**Issue by naikus** [howdyai/botkit#1793]
### Are you sure this is an issue with the Botkit core module?
Yes

This is a blocker for us currently as we have migrated from 0.7 with some new features like multiple bots per platform (i.e. web, facebook, slack) and also migrated the middlewares to the plugin API of the new version (4.x)

### What are you trying to achieve or the steps to reproduce?
We have a RASA middleware that augments the message with intent and entities. But these messages are not available to conversation handlers.

### Describe your issue here, include as much detail as necessary to reproduce the issue or implement a missing functionality.

We have a RASA Middleware like so
```javascript
controller.usePlugin(botkit => {
  return {
    name: "Rasa NLU",
    middlewares: {
      receive: [
        (bot, message, next) => {
          queryRasa(message.text).then(res => {
            message.entities = res.entities;
            message.intent = res.intent;
            next();
          });
        }
      ],
      send: []
    }
  };
})
```

```javascript
const convo = new BotkitConversation("smalltalk", controller)
convo.addQuestion("Let's chat", (res, convo) => {
   const {intent, entities} = res;
   convo.setVar("intent", intent);
   convo.setVar("entities", entities);
   convo.gotoThread(intent || "dontunderstand");
});
controller.addDialog(conversation);
```

### What was the result you received?
I receive the text sent by the user (```message.text```)
```javascript
convo.addQuestion("Let's chat", (res, convo) => {
  console.log(res); // Hi! (If the user entered Hi!)
});
```

### What did you expect?
The handler for the question to get message with intent and entities augmented by the Rasa NLU middleware
```javascript
convo.addQuestion("Let's chat", (res, convo) => {
  console.log(res);
});
```
This should print:
```javascript
{
  text: "Hi!",
  intent: "greet", // Identified by Rasa NLU
  entities: []
  ...other message properties
}
```

### Context:

- Botkit version: 4.0x
- Any other relevant information: There is also a bug: #1710 which I think might be related to this, where I've commented some of my findings [here](https://github.com/howdyai/botkit/issues/1710#issuecomment-527897136)

**Comment by benbrown** [comment]
This is an interesting problem! I'm not sure how to fully deal with this, but I'll ponder it!

**Comment by naikus** [comment]
@benbrown I've made some changes in packages botkit and botkit-adapter and will submit a pull request in a few minutes. I've tested these changes and now it fixes both the bugs. I'll add you to the list of reviewers

**Comment by naikus** [comment]
Hi @benbrown, after having some more understanding of the botbuilder APIs, I' have created another pull request with modifications to only botkit package. This leaves other packages (adapters) unchanged. Can you please review this whenever possible?
Thanks in advance!

**Comment by naikus** [comment]
I can't build botkit as I keep getting this error

```
../../node_modules/botframework-streaming/lib/webSocket/browserWebSocket.d.ts(17,26): error TS2304: Cannot find name 'WebSocket'.
```

**Comment by benbrown** [comment]
Yikes. I bet if we update the dependencies on Bot Framework to 4.7 this will be resolved.

**Comment by benbrown** [comment]
@naikus i am pursuing this as an issue in botframework. will keep you posted.

**Comment by benbrown** [comment]
@naikus this blocker should now be cleared by 4.6.1

**Comment by naikus** [comment]
@benbrown I've updated the pull request with a fix. 
Thanks!
