### ISSUE TITLE
Upgrade from V 0.7.0 to 4.5 does not work

### ISSUE THREAD

**Issue by jfelten** [howdyai/botkit#1795]
After spending the time to upgrade from Botkit 0.7.0 to 4.5 my app no longer works. It seems to connect without error, but does not come online or respond to anything.  Version 0.7.0 works fine with the same slack app, token and signing secret.

Am I missing something simple?

code:
```
    const slackAdapterOptions: SlackAdapterOptions = {
            botToken: auth.slackToken,
            clientSigningSecret: auth.slackSigningSecret,
            redirectUri: '' // why is this required?
        }) {

      const adapter = new SlackAdapter(slackAdapterOptions);
      const controller = new Botkit({
        adapter,
        webserver_middlewares: [],
        webhook_uri: '/api/messages',
      });


      controller.hears('hello','message', async(bot: BotWorker, message: BotkitMessage) => {
       console.log("word up!")
       await bot.reply(message,'I heard you say hello.');
      });
     controller.spawn();
```

**Comment by benbrown** [comment]
Are you set up to use the events API?

**Comment by jfelten** [comment]
That could be.  Let me read up - Thanks.

**Comment by jfelten** [comment]
Going to close this. We ended up forking 0.7.4 and updating the security vulnerabilities ourselves, because it was less effort and the old code actually works. I'm sorry to see what Microsoft has done.

**Comment by pgoldweic** [comment]
@jfelten, could you comment more on how you updated security vulnerabilities. I'm trying to upgrade my codebase (used botkit-starter-web to get started, at version 0.0.1, which depended on botkit 0.6.12, while remaining open source; also using watson-middleware-watson 1.8.2)

**Comment by benbrown** [comment]
you can update dependencies by running `npm audit -fix`
