### ISSUE TITLE
Support dynamic message generation in conversations

### ISSUE THREAD

**Issue by naikus** [howdyai/botkit#1798]
### Are you sure this is an issue with the Botkit core module?
No. This is a feature request

### What are you trying to achieve?
Sometimes you need to add custom properties to messages so It'd be good to have support for dynamic messages in the botkit conversations. Where the messages are generated by a function instead of text or template. It will be similar to functions that are currently used for attachments, quick_replies and blocks. Below is a sample code for such a feature.
````javascript
convo = new BotkitConversation(id, controller);
convo.addQuestion(
  // template
  {
    // This will generate an object that is assigned to 'channelData' 
    // property of the message
    generator: async(line, vars) => {
      return {
        type: "message",
        text: `This can be used with ${vars}`,
        // quick_replies: [],
        // blocks: [],
        // attachements: []
        additional_content: {}
      }
    }
  }, 

  // handler
  async(response, convo, bot) => {},

  // capture key
  "some_key",

  // conversation thread
  "thread_id"
);
````
This generator can also be used to generate the following:
- quick_replies
- attachments
- blocks

What are your thoughts?

### Context:

- Botkit version: 4.5x
- Messaging Platform: All

**Comment by benbrown** [comment]
Hi @naikus it is already possible to pass in functions for quick replies and other attachments.

I believe there is also a pull request open for using the same method for dynamic text - though it is also possible to make the text dynamic by just putting in a variable as the text.

https://botkit.ai/docs/v4/conversations.html#dynamic-quick-replies-and-attachments

**Comment by naikus** [comment]
Hi @benbrown, thanks for replying. I'm aware of this. But when you have a custom message properties, the text can't be used. e.g. We have a message format that is an extension of of botkit message.
```javascript
{
  text: "Some text",
  contentType: "card/form" // or "options/select_one" | "options/select_many", "calendar/date_time"
                                              // etc.
  header: {
    some: "headers"
  }
  body: {
    form: {
      // structured that is used by the form card in UI to render a form
    }
  }
}
```
There is no way to add custom properties to the message template at runtime. But anyway, this is not a priority.
Thanks,
A

**Comment by beetisushruth** [comment]
I think this feature would help a lot, I've been trying to show the client message options(quick replies) as checkboxes, so having a custom field in message definitely helps.
