### ISSUE TITLE
Can my bot reply without hears any thing?

### ISSUE THREAD

**Issue by ZuzooVn** [howdyai/botkit#18]
This is the normal code:

```javascript
controller.hears(['hello', 'hi'], 'direct_message,direct_mention,mention', function(bot, message) {
  bot.reply(message, "Hello.");
})
````
How can I call bot.reply without controller.hears?

**Comment by Glowbal** [comment]
Yes, you can, but it's `bot.say`

```javascript
bot.say({
      text: "Message text",
      channel: 'C0XXXXX' // channel Id
  });
```
Note: you will need to execute this after connecting to RTM. 

Quick and dirty example:
```javascript
var bot = botController.spawn( {
    token: process.argv[2] //process.env.token
}).startRTM();

setTimeout(function() {
  bot.say({
      text: "this is the message",
      channel: 'C0XXXXX' // my channel id
  });
}, 5000)
```

**Comment by ZuzooVn** [comment]
@Glowbal Thank you
Can bot.say send message to private conversation?

**Comment by Glowbal** [comment]
Yes, you need the direct message channel Id for it. See https://api.slack.com/rtm and search for `sending messages`. The direct channel Ids start with `D`.

**Comment by cchan** [comment]
Is there a way to do this with a Facebook Messenger bot? `startRTM` is only for Slack, it seems.
