### ISSUE TITLE
Duplicate messages when handler is awaiting a function

### ISSUE THREAD

**Issue by yaron-idan** [howdyai/botkit#1802]
### What are you trying to achieve or the steps to reproduce?
I'm creating a dialog that executes functions in response to user answers. It seems that whenever the handler awaits for the function response it triggers again. 
It results in duplicate executions of the function, which is not the desired outcome for my workflow.

The issue can be reproduced by creating the default botkit yeoman boilerplate, then overwriting bot.js with this [gist](https://gist.github.com/yaron-idan/e38de24133841ccfda4f0be75d45034e) and adding the `waiting_on_a_thread.js` file from the same gist to the `features` folder.
Once the bot is live, sending the bot a DM with the text `waiting_on_a_thread` should reproduce the issue.
### What was the result you received?
Answer handlers are executed multiple times, spamming the conversation with duplicate messages.
### What did you expect?
I expect every answer handler to run exactly once.
### Screenshots and animated GIFs
![image](https://user-images.githubusercontent.com/13436307/64516079-8237e600-d2f6-11e9-8859-22457e5b28a0.png)

### Context:

- Botkit version: 4.5.0
- Messaging Platform: Slack
- Node version: 8.9.4
- Os: MacOS
- Any other relevant information:

**Comment by benbrown** [comment]
Hrrm!  I am surprised that this happens deep inside the conversation like that.

I would suggest returning a promise from that handler, and doing the long process inside the promise. I *think* that will cause it to send back the 200 to Slack and stop the retries.

Let me know!

**Comment by yaron-idan** [comment]
Thanks for the quick reply!
My teammate alerted me to the existence of the workaround you've suggested here - https://github.com/howdyai/botkit/issues/1788#issuecomment-527515046

I've altered the handler to return a promise and processing within it, but now the problem is the handler is running to completion and terminates the conversation, and I can't find a way to continue to another thread once the long process is finished.

Here's an example of my workaround -  
```
convo.addQuestion("Would you like this thread to wait a bit?", [{
        pattern: 'no',
        handler: async (response, convo, bot) => {

        }
    },
    {
        pattern: 'yes',
        handler: async (response, convo, bot) => {
            // if user says yes, create the namespace.
            console.log("Waiting a bit...");
            let ctxReference = bot.getConfig("reference");
            funcThatWaits().then(async () => {
               await bot.changeContext(ctxReference); 
               await bot.say("balagan"); 
               await convo.gotoThread("yaron_thread");     
               console.log(bb);
            })
        }
    },
    {
        default: true,
        handler: async (response, convo, bot) => {
            // do nothing, allow convo to complete.
        }
    }
], 'confirm', 'my_thread');

```

Is there anyway to stop the conversation from completing when the handler completes without directing the conversation to another thread?

**Comment by benbrown** [comment]
HRRM!

I think actually the best way to do this IS to direct to another thread -- and then do the time consuming function in the beforeThread handler.

Between threads is really the best and most flexible place to embed this type of functionality.  The ask handlers clearly don't function well with this type of operation.

**Comment by yaron-idan** [comment]
Funny you should say that. 
I actually had the same idea this morning but when I tested it out it turned out slack starts sending retries even during the `before` handler was running.
I've also tried using the `after` event and saw the same behaviour.
This was weird since it really contradicted my expectations, any idea what's causing this behaviour?

**Comment by ashoofly** [comment]
@yaron-idan, did you ever figure this out? Running into the same issue.

**Comment by yaron-idan** [comment]
@ashoofly nope, I've ended up using [bolt](https://slack.dev/bolt-js/concepts) instead, which allows me full control over interactions with Slack's api.
