### ISSUE TITLE
Impossible to return to default thread

### ISSUE THREAD

**Issue by juanpablo64** [howdyai/botkit#1806]
Hi all! I have had this problem that I am not even sure it is one. I can't seem to return to the default thread after asking a question in another thread. For example, I made a question asking if the user had a previous interview, and when choosing yes, asking in another thread when was it. Afterwards, the bot ignored the question asked in the default thread (I used a convo.ask) and stopped there. When I changed the thread to age, though, it seemed to work. 
`    //pasamos del default al thread de entrevista previa
    convo.addMessage('Queremos saber mas datos tuyos para conocerte mas.');

    //se le pregunta al candidato si tuvo entrevista previa, la rta se guarda en la variable prevInterview
    convo.ask({'text':'Tuviste una entrevista previa con nosotros?',
        'quick_replies':[
        {
            title: "Si",
            payload: "Si",
        },{
            title: "No",
            payload: "No",
        }
        ]},
        [{
        pattern : '/Si|si|si/i',
        handler: async (response,convo,bot) => {   
                    convo.setVar('prevInterview', 'si'); 
                    await convo.gotoThread('yes_prev_interview');
                }
    },
    {
        pattern : '/No|no|ni|Ni/i',
        handler: async (response,convo,bot) => {
            await convo.gotoThread('age');
            convo.setVar('prevInterview', 'no');
        }

    },
    {
        default : true,
        handler: async (response,convo,bot) => {
            convo.repeat();
        }
    }
    ], 'prevInterview');

    //thread repeat question yes_prev_interview

    //thread yes_prev_interview
    convo.addQuestion(
    {
    text: 'Hace cuanto fue la entrevista?',
    'quick_replies':[
            {
                title: "Hace mas de un año",
                payload: "Hace mas de un año",
            },{
                title: "Hace menos de un año",
                payload: "Hace menos de un año",
            }
    ]
    },
    [
    {
        pattern : 'Hace mas de un año',
        handler: async (response,convo,bot) => {
            console.log('mas');
            await convo.gotoThread('age');
        }
    },
    {
        pattern : 'Hace menos de un año',
        handler: async (response,convo,bot) => {
            console.log('menos');
            await convo.gotoThread('age');
        }

    },
    {
        default : true,
        handler: async (response,convo,bot) => {
            console.log('ni idea');
            convo.repeat();
        }
    }
    ],
    'prevInterviewDate','yes_prev_interview');

    //convo.addAction('yes_prev_interview','default');

    convo.addQuestion({
        text:'Que edad tenes?',
        'quick_replies':[
            {title:'entre 18 – 20',payload:'entre 18 – 20'},
            {title:'entre 20 – 30',payload:'entre 20 – 30'},
            {title:'entre 30 – 40',payload:'entre 30 – 40'},
            {title:'entre 40 – 50',payload:'entre 40 – 50'},
            {title:'más de 50',payload:'más de 50'},]
        },
        [],
        'age_range','age'
    );
`

am I missing something?

**Comment by juanpablo64** [comment]
what I means is that the last question (Que edad tenes?) was not asked by the bot after I replied the previous one (Hace cuanto fue la entrevista?). The conversation sort of stopped there.

**Comment by adantoscano** [comment]
But none of them are the default thread. Can you try with a simpler example?

**Comment by juanpablo64** [comment]
`convo.addMessage('an easy example');


convo.ask({'text':'Hi, did you come with us yesterday?',
        'quick_replies':[
        {
            title: "yes",
            payload: "yes",
        },{
            title: "no",
            payload: "no",
        }
        ]},
        [{
        pattern : 'yes',
        handler: async (response,convo,bot) => {   
                    await convo.gotoThread('yes_way');
                }
    },
    {
        pattern : 'no',
        handler: async (response,convo,bot) => {
            await convo.gotoThread('age');
            convo.setVar('prevInterview', 'no');
        }

    },
    {
        default : true,
        handler: async (response,convo,bot) => {
            convo.repeat();
        }
    }
    ]);

convo.addQuestion(
    {
    text: 'What did you eat, tacos, or enchilada?',
    'quick_replies':[
            {
                title: "tacos",
                payload: "tacos",
            },{
                title: "enchilada",
                payload: "enchilada",
            }
    ]
    },
    [
    {
        pattern : 'tacos',
        handler: async (response,convo,bot) => {
            //do nothing, should return to the default thread
        }
    },
    {
        pattern : 'enchilada',
        handler: async (response,convo,bot) => {
            //do nothing, should return to the default thread
        }

    },
    {
        default : true,
        handler: async (response,convo,bot) => {
            convo.repeat();
        }
    }
    ],
    'eat_yesterday','yes_way');

convo.addQuestion({
        text:'what is your age range?',
        'quick_replies':[
            {title:'entre 18 – 20',payload:'entre 18 – 20'},
            {title:'entre 20 – 30',payload:'entre 20 – 30'},
            {title:'entre 30 – 40',payload:'entre 30 – 40'},
            {title:'entre 40 – 50',payload:'entre 40 – 50'},
            {title:'más de 50',payload:'más de 50'},]
        },
        [],
        'age_range'
    );
convo.addMessage('thanks for answering!');`

**Comment by adantoscano** [comment]
Ok, now I think I get it. You are thinking in default as a catch all thread but it is not. When you change the thread it wont come again unless you do it specifically and it wont come to the last message that you triggered, it will start from the beginning. So you should divide your default thread.

**Comment by juanpablo64** [comment]
ahhh, I get it now. Thank you! I'll keep it in mind!
