### ISSUE TITLE
[Facebook Adapter] Error in Url Verification for BotFramework bots

### ISSUE THREAD

**Issue by ceciliaavila** [howdyai/botkit#1817]
## Describe the bug
BotFramework TestBot with Facebook Adapter is not validating the Callback Url. We are experiencing an [ERR_INVALID_ARG_TYPE] exception.

## To Reproduce
1. Go to packages -> TestBot. 
2. In botframework.js uncomment the lines to connect the bot with Facebook and provide a verify_token, an app_secret, and an access_token.
![image](https://user-images.githubusercontent.com/44245136/65906338-bef87980-e398-11e9-85d9-fe691e6ff7a3.png)
3. Add a get method to handle the request for URL validation:
![image](https://user-images.githubusercontent.com/44245136/65905725-7a201300-e397-11e9-9057-57c621f0556c.png)
4. Install and build the project. Run the bot.
5. In a [Facebook Developer Account](https://developers.facebook.com/) create a new app and add a Messenger product.
![image](https://user-images.githubusercontent.com/44245136/65905674-64aae900-e397-11e9-9728-a5e07e7445a7.png)
6. Expose the bot's endpoint using [ngrok](https://ngrok.com/download)
7. Go back to the Facebook App and in the Webhook Section of the Messenger Product, click on _Subscribe to Events_ button
![image](https://user-images.githubusercontent.com/44245136/65905983-03cfe080-e398-11e9-8ee6-e78148b44ab3.png)
8. Complete the Callback URL with the ngrok URL adding '_/api/messages_', fill in the Verify Token and click _Verify and Save_ button.
![image](https://user-images.githubusercontent.com/44245136/65906003-0df1df00-e398-11e9-836b-307ca3469c39.png)

## Expected behavior
The URL should get verified.

## Proposed Solution
In [facebook_adapter.ts](https://github.com/howdyai/botkit/blob/master/packages/botbuilder-adapter-facebook/src/facebook_adapter.ts), in processActivity method, add the following code:
```TS
        var url = req.url;
        var params = url.split('?');
        var urlParams =  new URLSearchParams(params[1]);

        if (urlParams.get('hub.mode') === 'subscribe') {
            var verify_token = urlParams.get('hub.verify_token');
            if (verify_token === this.options.verify_token) {
                var challenge = urlParams.get('hub.challenge');
                res.status = 200;
                res.sendRaw(challenge);      
            } else {
                res.status = 401;
                throw new Error('Webhook not validated');      
            }
        } else {    
            if (await this.verifySignature(req, res) === true) {
                         ...
```
[bug]

**Comment by benbrown** [comment]
This is a bit tricky, since the syntax for accessing the  query parameters and sending the response back is specific to the web server package you are using - different between restify and express, for example.

We need to do this in a way that will work for everyone.

**Comment by ceciliaavila** [comment]
> This is a bit tricky, since the syntax for accessing the query parameters and sending the response back is specific to the web server package you are using - different between restify and express, for example.
> 
> We need to do this in a way that will work for everyone.

Ok Ben, let us know if we can help you with this. Thanks

**Comment by benbrown** [comment]
@ceciliaavila of course - this was mostly a comment for myself for when i come back to this in a few days :)
