### ISSUE TITLE
URL from localtunnel.me not working

### ISSUE THREAD

**Issue by sebastianff** [howdyai/botkit#183]
I'm having trouble with the URL I got from localtunnel. When I'm creating my webhook facebook is not accepting the URL. Is there something else I should do?

**Comment by krismuniz** [comment]
@sebastianff Did you make sure you added the '/facebook/receive' endpoint?

For example:
https://yoursubdomain.localtunnel.me/facebook/receive

**Comment by sebastianff** [comment]
Yes that was actually the issue. Thanks.

**Comment by vkjuju** [comment]
Hi, how you solved this? I got the same problem

**Comment by peterswimm** [comment]
@vkjuju did you replace "yoursubdomain" with whatever Localtunnel made when running it?
