### ISSUE TITLE
Last dialog repeated even after calling cancelAllDialogs()

### ISSUE THREAD

**Issue by chahat-arora** [howdyai/botkit#1830]
I am trying to cancel all on-going conversations using cancelAllDialgs() in the interrupt. In the interrupt, I am starting a new dialog then call cancelAllDialogs() to clear all dialogs but the last dialog from last on-going convo is repeating even after canceling all the dialogs.

### Context:
- Botkit version: 4.5.0
- Messaging Platform: Mattermost
- Node version: 12.11.0
- Os: Ubuntu 18.04 LTS

**Comment by benbrown** [comment]
@chahat-arora I am working on this bug right now.

Can you confirm for me that when you say it repeats the `last dialog from last on-going convo`, you mean that it sends one final message from the last active dialog before canceling?

**Comment by benbrown** [comment]
(if so, this should be fixed in v4.6)

**Comment by chahat-arora** [comment]
> @chahat-arora I am working on this bug right now.
> 
> Can you confirm for me that when you say it repeats the `last dialog from last on-going convo`, you mean that it sends one final message from the last active dialog before canceling?

Yes, and also it is not fixed in v4.6. I have tested it.

**Comment by benbrown** [comment]
Please send some sample code that exhibits this issue.
