### ISSUE TITLE
Add option to *not* pass parent variables to child dialogs

### ISSUE THREAD

**Issue by benbrown** [howdyai/botkit#1845]
Currently, when using `addChildDialog`, all of the variables known by the parent dialog will be passed to the child dialog.

This causes those values to be duplicated inside the sub-field of the resulting object - this could be annoying or cause unexpected side effects.

Perhaps an option can be added to `addChildDialog` that would either prevent these variables from being passed in and/or clean them up on the way out so the final results are clean.

**Comment by gp187** [comment]
Any update? The conversation closes and the bot sends the default message once again
