### ISSUE TITLE
Multi adapter in one controller

### ISSUE THREAD

**Issue by RafaelCunhafs** [howdyai/botkit#1847]
Hi,

I cannot find anywhere in the docs how to configure more than one adapter using the same port on the controller like we could do in the old legacy version of Botkit.

I was looking for some way to use Facebook Adapter, Web Adapter and maybe other in the same repo.

Thanks,
Rafael.

**Comment by benbrown** [comment]
This has been addressed in a sample.

https://github.com/howdyai/botkit/blob/master/packages/testbot/multiadapter.js
