### ISSUE TITLE
Botkit conversation one function

### ISSUE THREAD

**Issue by dmccrevan** [howdyai/botkit#185]
So i am using a third party API to handle responses based on inputs. I want to know if there is a way to have a conversation that will keep going to the same function rather than to the next function.

    controller.hears(['pizzatime'], 'message_recieved', function(bot,message) {
        askEverything = function(response, convo) {
          //third party API handles responses based on inputs
        }
        
        bot.startConversation(message, askFlavor);
    });

Is there a way to just keep going to that function? Rather than structuring it so it has to go to the next function?

**Comment by benbrown** [comment]
I think it depends on how your third party API works...

You may want to explore the middleware options, which allow you to pass messages to third party APIs and get additional information added to the message object, which can then be used in the conversations.

**Comment by peterswimm** [comment]
Closing the issue for now, If you have any updates, please feel free to reopen!
