### ISSUE TITLE
botbuilder-adapter-facebook

### ISSUE THREAD

**Issue by sal1n** [howdyai/botkit#1852]
Hi

The botbuilder-adapter-facebook module doesn't appear to fully work.  It sets up the webhook endpoint fine and validates OK with a Facebook App.  However after that no messages seem to be processed even with this basic code:

````
const { Botkit } = require('botkit')
const { FacebookAdapter } = require('botbuilder-adapter-facebook')
require('dotenv').config()

const adapter = new FacebookAdapter({
     verify_token: process.env.FACEBOOK_VERIFY_TOKEN,
     app_secret: process.env.FACEBOOK_APP_SECRET,
     access_token: process.env.FACEBOOK_ACCESS_TOKEN
})

const controller = new Botkit({
   webhook_uri: '/api/messages',
   adapter: adapter
})

controller.ready(() => {
  
    controller.hears('sample','message,direct_message', async(bot, message) => {
        await bot.reply(message, 'I heard a sample message.');
    });

    controller.on('message,direct_message', async(bot, message) => {
        await bot.reply(message, `Echo: ${ message.text }`);
    });
  
})

controller.webserver.get('/', (req, res) => {
    res.send(`This app is running Botkit ${ controller.version }.`);
});
````

This is with botkit 4.6.0 and botbuilder-adapter-facebook 1.0.6.  I've got a test project set up here : https://glitch.com/~fragrant-pansy 

Is there a way I can output to console the Facebook communication to try and debug?  I can't see anything in the docs.

Microsoft is now recommending to use this module as the old approach is being deprecated so I'm a bit stuck.

Thanks.

**Comment by benbrown** [comment]
Do you see traffic to the webhook at all?

You can turn on simple request tracking by passing in a middleware for the webserver, as seen here:
https://github.com/howdyai/botkit/blob/master/packages/testbot/bot.js#L146

Did you go through all the setup steps to enable the various webhook events?

**Comment by sal1n** [comment]
Thanks for the middleware logging tip and coming back to me.

Yes I went through all the steps, thought I was going mad.  I think the issue was at the Facebook end - I created a new app exactly the same as before and it's now working.  I'll close the issue.  If this happens to anyone else I'd recommend creating a new app first to see if that resolves it.
