### ISSUE TITLE
Add support for bot.api.views.publish through @slack/web-api 5.4.0

### ISSUE THREAD

**Issue by reesesm2000** [howdyai/botkit#1853]
In order to use bot.api.views.publish with Slack, the web-api version needs to be bumped to 5.4.0. This is needed to be able to publish to the newly available Home tab for an app. (Perhaps botkit needs to officially support the Home tab, not sure about that though.)

**Comment by benbrown** [comment]
Fixed by release of v1.0.7
https://github.com/howdyai/botkit/blob/master/packages/botbuilder-adapter-slack/CHANGELOG.md#107
