### ISSUE TITLE
"TypeError: Cannot perform 'get' on a proxy that has been revoked" on using setInterval to let bot reply repeatedly

### ISSUE THREAD

**Issue by movi1224** [howdyai/botkit#1856]
- Botkit version:4.5.0
- Messaging Platform: Slack
- Node version: 10.3
I was trying to let the bot reply repeatedly using setInterval but it doesn't work,
My code in a simple way is like this:

```
module.exports = function(controller) {
  controller.hears("repeat","direct_message",async(bot, message)=> {
      timeout = setInterval( () => {
         bot.reply(message, "111");
      });
    },1000);
};
```

It is showing the error:
> (node:12261) UnhandledPromiseRejectionWarning: TypeError: Cannot perform 'get' on a proxy that has been revoked
>     at SlackBotWorker.<anonymous> (/rbd/pnpm-volume/3ab81c03-5933-492b-9fee-14341f0a2880/node_modules/.registry.npmjs.org/botkit/4.5.0/node_modules/botkit/lib/botworker.js:100:60)
>     at Generator.next (<anonymous>)
>     at /rbd/pnpm-volume/3ab81c03-5933-492b-9fee-14341f0a2880/node_modules/.registry.npmjs.org/botkit/4.5.0/node_modules/botkit/lib/botworker.js:7:71
>     at new Promise (<anonymous>)
>     at __awaiter (/rbd/pnpm-volume/3ab81c03-5933-492b-9fee-14341f0a2880/node_modules/.registry.npmjs.org/botkit/4.5.0/node_modules/botkit/lib/botworker.js:3:12)
>     at _controller.middleware.send.run (/rbd/pnpm-volume/3ab81c03-5933-492b-9fee-14341f0a2880/node_modules/.registry.npmjs.org/botkit/4.5.0/node_modules/botkit/lib/botworker.js:96:94)
>     at next (/rbd/pnpm-volume/3ab81c03-5933-492b-9fee-14341f0a2880/node_modules/.registry.npmjs.org/ware/1.3.0/node_modules/ware/lib/index.js:82:27)
>     at Ware.run (/rbd/pnpm-volume/3ab81c03-5933-492b-9fee-14341f0a2880/node_modules/.registry.npmjs.org/ware/1.3.0/node_modules/ware/lib/index.js:88:3)
>     at Promise (/rbd/pnpm-volume/3ab81c03-5933-492b-9fee-14341f0a2880/node_modules/.registry.npmjs.org/botkit/4.5.0/node_modules/botkit/lib/botworker.js:96:50)
>     at new Promise (<anonymous>)

It works well on my 0.7 version webex botkit but there have so many issues like this happen in slack botkit.

**Comment by Naktibalda** [comment]
This is a common issue in v4.
> You need to use `await bot.changeContext(message.reference)` to "refresh" the bot's ability to send.
```js
timeout = setInterval( async () => {
    await bot.changeContext(message.reference)
    await bot.reply(message, "111");
});
```

#1724 #1844

**Comment by benbrown** [comment]
See also #1841

**Comment by movi1224** [comment]
The answer from @Naktibalda doesn't work for me, I tried a lot of async/await things but that doesn't work. Also @benbrown can you please be a bit more specific on #1841 ? I tried this but it's showing TypeError: adp is not a contrctor
replace
`const { SlackAdapter, SlackMessageTypeMiddleware, SlackEventMiddleware } = require('botbuilder-adapter-slack');`
by something like
```
var adp = require('botbuilder-adapter-slack');
var SlackAdapter = new adp;
```

any help please? thank you!

**Comment by benbrown** [comment]
#1841 is a proposal to remove the proxy behavior.  No code change is suggested there.

The key piece of what @Naktibalda mentioned is calling the `changeContext` method:

```
    await bot.changeContext(message.reference)
```

This will reset the proxy and allow you to send messages without error.

**Comment by movi1224** [comment]
I made it! thank you so much I really appreciate it!

**Comment by dror-weiss** [comment]
@Naktibalda, keep note that the proposed solution although fixing the issue, disrupts the `replyInThread`, and messages are sent to the main channel and not to a thread.

```javascript
timeout = setInterval( async () => {
    await bot.changeContext(message.reference)
    await bot.replyInThread(message, "111"); // not in a thread.
});
```
