### ISSUE TITLE
Calling `bot.beginDialog` fails in Botkit.afterDialog

### ISSUE THREAD

**Issue by etiennellipse** [howdyai/botkit#1857]
Defining a simple handler through `Botkit.afterDialog` that starts another dialog crashes.

Example:
```
controller.afterDialog(“how_you_doing”, async (bot) => {
    await bot.beginDialog("tell_me_more");
});
```

It crashes with:
```
Error in trigger handler Error: Call to beginDialog on a bot that did not receive a dialogContext during spawn
```

Looking at the code running the handler [right here](https://github.com/howdyai/botkit/blob/master/packages/botkit/src/core.ts#L1167), it spawns a new bot instance passing it the `step.context` which is a TurnContext. This makes it crash later down the road.

### Workaround

Define the after hook [using the convo.after API](https://www.botkit.ai/docs/v4/reference/core.html#after).

### Context:

- Botkit version: 4.6
- Messaging Platform: Web
- Node version: 10.16
- Os: MacOS

**Comment by benbrown** [comment]
This is due to the fact that the bot instance passed into the after handler no longer has a valid dialog context, which is required to start new dialogs.  I'm not sure there is a great solution.
