### ISSUE TITLE
cannot receive response from IBM watson: Body of error is HTTP ClientRequest

### ISSUE THREAD

**Issue by juanpablo64** [howdyai/botkit#1859]
I deployed the chatbot in another server (using webchat) and while I can send messages just fine, the response from watson is not received in the server where the bot is running. Here's the error message I receive:

![image](https://user-images.githubusercontent.com/7575105/68957529-fdab8d00-07a8-11ea-9b15-cb03815a27d2.png)

I am not sure what could be the problem here.

**Comment by juanpablo64** [comment]
claryfing on the above message, here's what I receive when I console log the message parameter

![image](https://user-images.githubusercontent.com/7575105/68973785-edf26f80-07cd-11ea-899c-1f572de656b6.png)

**Comment by Naktibalda** [comment]
It doesn't look like a Botkit error at all,
I think that a better place for your issue is https://github.com/IBM/node-sdk-core/issues or Watson Slack: http://wdc-slack-inviter.mybluemix.net/
