### ISSUE TITLE
SSL certificate has expired

### ISSUE THREAD

**Issue by gorda** [howdyai/botkit#1861]
Hi, guys.

This is a SSL certificate issue about [https://community.botkit.ai](https://community.botkit.ai) , I can't browse this web site today and It's expired (8/19/2019 - 11/17/2019).

**Comment by deepakmahakale** [comment]
I just saw that 

![image](https://user-images.githubusercontent.com/14993828/69039898-e1128d80-0a12-11ea-8ee3-c95beb3307a4.png)

**Comment by cooperka** [comment]
https://botkit.ai/docs/v4/ is also affected, pinging @benbrown for visibility.

**Comment by justsml** [comment]
Just want to add: This can't be ignored by users because botkit's sites are setup with `HTTP Strict Transport Security` (HSTS).

HSTS is not necessary, unless you are a bank or other security critical application.

> Can HSTS be disabled? It's just docs.

**Comment by benbrown** [comment]
Fixed.

**Comment by justsml** [comment]
Thx
