### ISSUE TITLE
About using slack bot in multiple workspaces

### ISSUE THREAD

**Issue by movi1224** [howdyai/botkit#1863]
I am going to use the app in multiple workspaces but it is showing the error:

> Experienced an error inside the turn handler Error: Missing credentials for team.

I deleted the botToken because that's for single team use but I feel like I still need something like that to use different bot tokens for different teams, I just don't know how to do that. Now my adapter function is

```
const adapter = new SlackAdapter({
    // REMOVE THIS OPTION AFTER YOU HAVE CONFIGURED YOUR APP!
    //enable_incomplete: true,

    // parameters used to secure webhook endpoint
    verificationToken: process.env.verificationToken,
    clientSigningSecret: process.env.clientSigningSecret,  

    // auth token for a single-team app
    //botToken: process.env.botToken,

    // credentials used to set up oauth for multi-team apps
    clientId: process.env.clientId,
    clientSecret: process.env.clientSecret,
    scopes: ['bot'], 
    redirectUri: process.env.redirectUri,
 
    // functions required for retrieving team-specific info
    // for use in multi-team apps
    getTokenForTeam: async(team_id) => {
        // load the token for this team
        // as captured during oauth 
    }, 
    getBotUserByTeam: async(team_id) => {
        // load bot user id for this team   
        // as captured during oauth 
    },
    //botToken: getTokenForTeam
});
```
I think I may need to put something in getTokenForTeam and getBotUserByTeam but I am not sure, also I can see the logs that it captures the oauth information when installing into any workspaces but it can't be stored and used. any help please? Thank you!

- Botkit version: 4.5.0
- Messaging Platform: slack
- Node version: 10
- Os: win

**Comment by benbrown** [comment]
You are correct - you need to flesh out the functionality of those two functions.  This will allow your bot to properly capture (and retrieve) the token that is provided during the oauth process.

**Comment by manuelrodgzz** [comment]
I am lost too, how am I supposed to get the bot user and token for each team? I think that there should be more information about it.
