### ISSUE TITLE
how to handle multiple users (WebAdapter)

### ISSUE THREAD

**Issue by juanpablo64** [howdyai/botkit#1872]
This is more of a question rather than a problem.  The bot I made cannot handle more than one user at a time on my watson . Whenever I connect with another user, the first one is overwritten. Here's part of the code that handles the bot in the server. It's working fine as far as I can tell, receives messages and send me to watson to get the reply.

`
var current_recruit = null,
    interview_dates     = [],
    finale              = false,
    conversation_id     = null;

    const watsonMiddleware = new WatsonMiddleware({
        authenticator: new IamAuthenticator({ apikey: process.env.WATSON_APIKEY }),
        iam_apikey: process.env.WATSON_APIKEY,
        url: process.env.WATSON_URL,
        workspace_id: process.env.WATSON_WORKSPACE_ID,
        version: '2018-07-10',
        minimum_confidence: 0.5, // (Optional) Default is 0.75
        httpsAgent: tunnel.httpsOverHttp({
            proxy: {
              host: 'host',
              port: port_number,
          },
      }),
        proxy: false,
    });

    const adapter = new WebAdapter({});

    watsonMiddleware.before = async (message, payload) => {

        if ((typeof(payload.context) === 'undefined')) {

            var context = {
                context: {
                    user_id               : '',
                    name                  : '',
                }
            };
            Object.assign(payload, context);
        }
        return payload;
    };

    const controller = new Botkit({

        webhook_uri: '/api/messages',
        adapter: adapter,
    });

    controller.middleware.receive.use(

        watsonMiddleware.receive.bind(watsonMiddleware),
    );
`

Is it possible to make it with botkit? if so, what would I need to change?

**Comment by adantoscano** [comment]
Hola Juan Pablo,

Which library is WatsonMiddleware from? botkit middleware receive use() is waiting for a `function(bot,message,next)`. You should ensure `watsonMiddleware.receive.bind(watsonMiddleware)` and figure out what is user_id doing.

**Comment by juanpablo64** [comment]
Hola adan! 

The watsonMiddleware library is the one that connects the bot with IBM Watson assistant: https://botkit.ai/docs/v0/readme-middlewares.html which I am using to allow for text recognition, making a very simple dialogue.

user_id is a context variable that is sent to watson to remember the current user. The problem is, on the server is overwritten once another user enters, for example:

![repeat](https://user-images.githubusercontent.com/7575105/70251917-32cf4d80-175f-11ea-9de4-a784d7bc549f.png)

as you can see, I started with federico, but when on another pc I started with Juan Pablo, the user data was overwritten by the second access. What I want is to start a session with federico, and Juan Pablo at the same time.

**Comment by adantoscano** [comment]
Can you see the user_id is watson receiving? Maybe it is always the same, because of that `before` or your client app is not changing your user_id

**Comment by juanpablo64** [comment]
the user id is actually entered once the conversation begins. I ask the user what his ID is, and then I set it on watson before sending it. 

`
controller.hears(
            ['([0-9]{8})|([0-9]{2}\.[0-9]{3}\.[0-9]{3})|([0-9]{2}\s[0-9]{3}\s[0-9]{3})'],
            'message',
            async function(bot, message) {

                if (message.watsonError) {

                    await bot.reply(message,`I'm sorry, but for technical reasons I can't respond to your message`);
                    console.log(message.watsonError);
                } 
                else {

                    var dni = message.text.replace(/([^0-9])/g,""),recruit = null;

                    if (dni.length != 8){

                        await bot.reply(message,'El dni cargado no es correcto, por favor, ingresalo de nuevo.');                    
                    }
                    else{

                        recruit = await conversationStart(dni);
                        current_recruit = recruit.recruit_data;

                        await bot.reply(message,recruit.start_message);

                        conversation = new db.Conversation();

                        conversation.save((err,data)=>{
                            conversation._id = data._id;
                        })
                    }
                }
            },);
`


only after recognizing the user id, the conversartion with watson begins

**Comment by adantoscano** [comment]
But where is the data being overwritten?

**Comment by juanpablo64** [comment]
when the bot calls for serverStartup(), the variable current_recruit is overwritten after the user gives their ID.

**Comment by juanpablo64** [comment]
as I see it there's only one "botkit session" that, if another user enters, is overwritten with their own data. Is it possible to define more than one session?

**Comment by benbrown** [comment]
Sounds like this is a problem with some sort of global variable.

Every message that comes from your bot will have a message.user field.  Use this to identify them.

**Comment by juanpablo64** [comment]
got it, thank you!
