### ISSUE TITLE
Support for dialog interruption hooks

### ISSUE THREAD

**Issue by cooperka** [howdyai/botkit#1874]
#### Scenario A

We have a Twilio bot that asks the user to submit some information once per day. It's not mandatory, so users don't always reply. The next day, they'll get another (identical) request via `startConversationWithUser`.

We're using dialogs, so yesterday's open question is interrupted by the new dialog, and when the new dialog is completed, botkit automatically resumes the old one. The problem is that the old dialog is asking the exact same question, it's just a day old.

We don't want the old dialog to be resumed in this case.

#### Scenario B

We have both daily and weekly reminders. The daily reminder asks the user "yes/no" if they met their weekly goal. The weekly reminder allows the user to change their weekly goal.

If the user doesn't reply to the daily reminder for a while, then it's interrupted by the weekly reminder, then they change their goal, then resume the original daily reminder, the question will be out of date.

We want to update a conversation variable before resuming the daily reminder dialog so the question is fresh.

### Possible solutions

Any one of the following would help tremendously. I'd love to hear feedback on whether they'd be welcome as PRs (and whether they'd be feasible, if you have thoughts on that).

1. A hook for `onResumeInterruptedDialog(fromDialogId)`
    - This could be used to check for updated info, and either end the convo or modify convo vars before resuming
1. A hook for `onInterruptDialog(newDialogId)`
    - This could be used to cancel the previous dialog as soon as the new dialog is triggered, but it's only helpful for a dialog immediately interrupted by a duplicate (not helpful if the duplicate is deeper in the stack)
1. A method for `findOpenDialog(user/phone, dialogId)`
    - This could be used to return an existing dialog in order to cancel it
    - Could be specific to the Twilio adapter if needed

### Other workarounds

We've considered these possibilities and would rather not use them, if possible.

1. Add business logic on our server to behave differently if we know there's an old dialog still open
    - This would mean we need to track user state across a large array of possible dialogs; perhaps we could read the persisted state in the botkit database (we're using the postgres adapter)
    - Are there public botkit methods available to read this data in a meaningful way? This seems hacky and not a best practice
    - This seems related to the `findOpenDialog` solution above
1. Use simple conversations instead of dialogs
    - This doesn't help us because we do want the interrupt/resume logic, just not if the dialog IDs are identical. There are other, different dialogs that can interrupt the daily dialog and that's perfectly fine

Cheers!

**Comment by benbrown** [comment]
I would recommend using the technique described below to find any active dialog, then cancel it before beginning the new one:
https://github.com/howdyai/botkit/issues/1781

**Comment by benbrown** [comment]
I believe you can check `bot.context.activeDialog` immediately after spawning the bot instance that you'd otherwise use to begin the new dialog.

**Comment by cooperka** [comment]
I may be misunderstanding; with the following code:

```js
const bot = await controller.spawn();
// Point A
await bot.startConversationWithUser(phone);
// Point B
```

At point A there shouldn't be enough context for the bot to know if there's an active dialog (because the bot doesn't know who the user is yet) and at point B the conversation has already been started.

I tried pausing the debugger at point A and `bot.context` is undefined. I haven't been able to find any member vars named `activeDialog`. It's possible that `controller.conversationState` or `controller.dialogSet.dialogState` could have something useful, but that seems hacky. I'm probably misunderstanding something?

**Comment by benbrown** [comment]
In your scenario, you actually would check that attribute at point B.

The call to `startConversationWithUser` is setting up the context.  It doesn't actually begin the new dialog.

**Comment by cooperka** [comment]
Ah thanks, you're right -- but still no luck. I paused the debugger at "point B" above and the same things are undefined. No `activeDialog`. Here's a debugger screenshot for a bit more context:

<img width="861" alt="Screen Shot 2019-12-11 at 15 55 04" src="https://user-images.githubusercontent.com/2047062/70670702-a75a2e80-1c2e-11ea-9c7f-4be09b1085dc.png">

Is this expected?

**Comment by cooperka** [comment]
Despite the above issue, I got a hacky workaround successfully canceling all dialogs only if the most recent one is duplicated:

```js
const bot = await controller.spawn();
await bot.startConversationWithUser(phone);

// Hack: First cancel all existing dialogs with this user
// if the current one has the same ID as the one that's beginning.
//
// TODO: Only cancel the one that's duplicated (I don't know of a method for this).
const stack = bot._config.dialogContext.stack;
const isDuplicateDialog = !isEmpty(stack) && last(stack).id.startsWith(dialogId);
if (isDuplicateDialog) {
  await bot.cancelAllDialogs();
}

await bot.beginDialog(dialogId);
```

So we return to the problem of needing to find and cancel a single dialog (instead of all dialogs like above). It would be simple if `bot.context.activeDialog` were defined, but I can't seem to access that in my situation.

Notes:
- Based on [this search](https://github.com/howdyai/botkit/search?q=activeDialog&unscoped_q=activeDialog) it looks like DialogContext sometimes contains `activeDialog` but not in this case; it's `undefined`
- Using `replaceDialog` instead of `beginDialog` **nearly** works, but there's a bug I've run into before where it weirdly receives a duplicate message instead of replacing the dialog. I'll report that separately.

**Comment by cooperka** [comment]
[not stale]

**Comment by cooperka** [comment]
Update: I've renamed the issue "interruption hooks" instead of "deduplication" and added a second scenario to the description. A hook on resuming an interrupted dialog would make these situations trivial to deal with.

As a reminder, there's still an open question above about why `activeDialog` is undefined. Looking forward to your thoughts!

**Comment by benbrown** [comment]
OK! Finally reconnecting with this and hopefully will resolve.

FIRST, I apologize that my initial suggestion was incorrect. The actual location of the activeDialog field is, as you discovered, on the dialogContext.  So the current best method of accessing this is:

`bot.getConfig('dialogContext').activeDialog`

It should always be set if a dialog is active.

**Comment by benbrown** [comment]
A few thoughts:

* I will add a bot.activeDialog member, that returns the active dialog
* I will add a bot.hasActiveDialog function that returns true or false
* I will add a isDialogActive(id) that will return whether or not the specified dialog is _anywherE_ in the stack, since the activeDialog may actually be a prompt called from the dialog you care about
* I will add a .endActiveDialog that will ... end only the active dialog

**Comment by benbrown** [comment]
@cooperka above changes will be in next release. I hope they solve this issue for you. We can follow on with those interruption hooks that sound like a good idea too! PR definitely welcome.

**Comment by cooperka** [comment]
Thanks for the new features @benbrown! The official `getActiveDialog` and `isDialogActive` APIs will help make my partial workaround for Scenario A easier; it's nice to use official APIs instead of digging into the `_config` object.

Scenario B is still unsolved at this point, but I understand an `onResumeInterruptedDialog` hook is more work. We don't the funding to do that work ourselves right now but I will submit a PR if funding ever comes through.

Do you plan to leave this issue open in case someone else wants to tackle hooks?

**Comment by benbrown** [comment]
@cooperka yes we can leave it open and will continue to investigate how to achieve onResumeInterruptedDialog or something like that.

**Comment by benbrown** [comment]
@cooperka this new features are now in 4.8!

I'd love to schedule a time to chat with you about the new hooks you want. Are you in [the community slack](https://community.botkit.ai)?

**Comment by cooperka** [comment]
Yes I am, @cooperka there too (I just updated the username, it didn't exist before). I'm flexible this week if you want to DM me.

**Comment by cooperka** [comment]
[not stale]
