### ISSUE TITLE
bot.beginDialog causes unexpected message if dialog already open

### ISSUE THREAD

**Issue by cooperka** [howdyai/botkit#1878]
### Issue

Using `bot.beginDialog` or `bot.replaceDialog` when there's already a dialog open (e.g. to switch to the new dialog based on user input) causes the bot to automatically receive an unexpected `{}` message.

This message breaks questions, because the empty message is interpreted by botkit as an answer to the question, and the user doesn't have a chance to give input.

### Demo

I made a simple working demo app [here](https://github.com/cooperka/botkit-issue-demos/commits/2019-dialogJumping) that you can clone to see the issue.

1. Start the emulator
1. Say `hi` to trigger ONBOARDING_DIALOG
1. Say anything for your name
1. Say `yes` to confirm and trigger ONBOARDING_DIALOG_2
1. onboarding2 asks for your name, and immediately receives `{}` as a response without your input. It's impossible to reply with your name.

### Workaround

See [this commit](https://github.com/cooperka/botkit-issue-demos/commit/16abd7a76f676f7c8f9a7c4db72c2de21de55b14) for a successful workaround using `dialog.addGotoDialog` instead of `bot.beginDialog`.

It's great that this works, but it isn't possible to use this in all cases (e.g. [this issue](https://github.com/howdyai/botkit/issues/1874#issuecomment-567296864)).

### Context

- Botkit version: 4.6.1
- Messaging Platform: Emulator
- Node version: 10.15.3
- OS: Mac 10.14

**Comment by cooperka** [comment]
[not stale, looks like others have experienced as well]

**Comment by benbrown** [comment]
I FINALLY FIGURED THIS OUT!

**Comment by benbrown** [comment]
This had to do with the fact that, inside the handler, the active dialog was changing.

AFTER the handler is run, it attempts to continue on to the next step.

Since the dialog had changed, it resumed improperly.
I believe that the proper behavior is to end the turn, because the new child dialog has taken control.

Still some work to do to validate but I *think* this will be addressed soon.

**Comment by benbrown** [comment]
OK! This is going to be addressed in the next release. HOWEVER, there is a follow up bug that I discovered while fixing this. 

Calling beginDialog from an `ask()` will cause the next outgoing message in that dialog to be skipped. :/ 

#1932
