### ISSUE TITLE
Upgrade dependency on botbuilder-dialogs to cut out 300MB of transitive dependencies.

### ISSUE THREAD

**Issue by SirensOfTitan** [howdyai/botkit#1882]
### Are you sure this is an issue with the Botkit core module?

Yes, it's explicitly about a dependency that `botkit` has on `botbuilder-dialogs`.

### What are you trying to achieve or the steps to reproduce?

Right now, using the `botkit` or `botbuilder-adapter-slack` in our application balloons our docker image size by over 300MB due to a `botbuilder-dialogs` dependency on `cldr-data`.  

`botbuilder-dialogs` has been patched to just import the couple json files necessary from `cldr-data` over the full payload here:
https://github.com/microsoft/botbuilder-js/pull/1444

... and this fix was released as 4.7.0.    It would be very worthwhile to upgrade this dependency, as it'll reduce transitive disk costs significantly.  

### What was the result you received?

`botkit` still depends on `botbuilder-dialogs` version 4.6.0, leading to 300MB of unnecessary i18n JSON data being imported into our app.

### What did you expect?

`botkit` upgrades its dependency on `botbuilder-dialogs` (and other `botbuilder` packages) to 4.7.0.

**Comment by benbrown** [comment]
Agreed! Will do so in the next upcoming release.

**Comment by benbrown** [comment]
addressed in 4.6.1
