### ISSUE TITLE
Update docs & samples regarding Facebook echo / delivery confirmations

### ISSUE THREAD

**Issue by stevkan** [howdyai/botkit#1888]
Docs & samples should be updated to notify developers of Facebook's echo and delivery confirmations. If the `message_deliveries` and `message_echoes` webhook events are subscribed to and are not filtered for in the bot's incoming messages, then the user will receive continuous echoes / responses. This is something that does not occur via the Azure Bot Service Facebook channel as that service filters these events at the connector level.

**Comment by Am-okey11** [comment]
Hi
