### ISSUE TITLE
Botkit doesn't get updated content from Botkit CMS

### ISSUE THREAD

**Issue by nguyenphu160196** [howdyai/botkit#1889]
Hi everybody,
I have got an issue when i update content on CMS tool.
I have created a chatbot using botkit (4.6.1), i have also ran Botkit CMS to create the chat content.
The chat content has updated on CMS tool, but botkit doesn't get the updated content until i reboot its server.
Could anyone help me for this? thanks!

**Comment by etiennellipse** [comment]
You need to reboot the bot to get the updated content. That is how it currently works.
