### ISSUE TITLE
Botkit conversation timeout not working

### ISSUE THREAD

**Issue by gp187** [howdyai/botkit#1897]
### What are you trying to achieve or the steps to reproduce?

Install botkit latest version. No solution for timeout. When the user 

````
controller.hears(['hi', 'hello', 'holla', 'ola'], 'message,direct_message', async function(bot,message) {
   // todo-->Set: empty cart

    // -->Begin: dialog
    await bot.beginDialog('orderFlow');
 });
````
There's no way to timeout a conversation if the user doesn't type anything for 1h

### Context:

- Botkit version: 4.6.0
- Messaging Platform: web
- Node version: 12
- Os: Ubuntu 18
- Any other relevant information:

**Comment by damcorp** [comment]
yeah I need this one too, in older version (v.0.7) we can use `convo.setTimeout` but I dont find any way in v.4

**Comment by dhruv10** [comment]
Please respond to this issue, timeout feature is highly needed.

**Comment by ryrahul3** [comment]
Any update on this issue !

**Comment by naikus** [comment]
@peterswimm @benbrown Is there an update to this issue? Seems like some of the features are missing altogether in the 4.x versions and there seems to be no documentation on workaround on how to migrate those. I understand you guys are busy but any pointers would be appreciated :)
