### ISSUE TITLE
Send Proactive Message to Microsoft Teams

### ISSUE THREAD

**Issue by kevinyang372** [howdyai/botkit#1899]
Hi! I am trying use Botkit to send proactive messages to MS team channels.

So far I am able to find a way to send private chat messages. However, I've been struggling to find any documentation about how to send proactive message to MS team channels. Is there any way I could achieve this functionality via Botkit?

Thank you very much!

 _Code for sending private messages _
```
let bot = await mscontroller.spawn();

const params = {channelId: 'msteams', ....};
MicrosoftAppCredentials.trustServiceUrl(process.env.serviceurl);

await bot.startConversationWithUser(params);
await bot.say('hi');
```

- Botkit version: 4.6.0
- Messaging Platform: MS teams
- Node version: 9.5.0
- Os: Mac OS

**Comment by benbrown** [comment]
What problems are you encountering, @kevinyang372? the code you included looks reasonable.

**Comment by kevinyang372** [comment]
@benbrown 

Thank you for the reply! The problem I am facing is `startConversationWithUser` doesn't allow me to send messages to the team. I am able to solve the problem by directly using botbuilder with the following code.

```javascript
let diffbot = await mscontroller.spawn();
MicrosoftAppCredentials.trustServiceUrl(...);
const to_send = MessageFactory.text(message_to_send);

const connectorClient = mscontroller.adapter.createConnectorClient(...);

const params =
{
     isGroup: true,
     channelData: {
           channel: {
                 id: ...
           }
     },
     activity: to_send
}

const conversationResourceResponse = await connectorClient.conversations.createConversation(params);
const conversationReference = channel_data.Item;
conversationReference.conversation.id = conversationResourceResponse.id;

await mscontroller.adapter.continueConversation(conversationReference, () => {console.log('Message Sent!')});
```

Is it possible to add the function `startConversationInChannel` in botkit?

**Comment by khushleen** [comment]
Hi,
Any way to send a proactive message on teams using botkit. Below is my code, trying to send a message but had no success.

`var options = { serviceUrl: <--URL-->,
clientId: botframeworkClientId,
    clientSecret: botframeworkClientSecret

}

var bot =  controller.spawn(options);

var param = {
    "bot": {
        "id": "2*:7****",
        "name": "<--BOT NAME-->"
    },
    "isGroup": false,
    "raw_message":{"from":{"id": "2*:1******",
      "name": <--USER NAME-->}},
    "members": [
        {
            "id": "2*:1******",
            "name": <--USER NAME-->
        }
    ],
    "channelData": { "tenant": { "id": "66039c4b-2333-4d9e-89fd-02f94d0d71bd" } },
    "conversation": {
    "conversationType": "personal",
    "tenantId": "6******",
    "id": "a:1*******"
  },
    "user": "2*:1******",
  "channel": "a:1*******"
}

bot.startPrivateConversation(param,function(err,con_id){

bot.say("PROACTIVE MESSAGE SEND",con_id)
})` 


Can anyone help with a way out to send a proactive message on teams?
