### ISSUE TITLE
Private reply edit doesn't work

### ISSUE THREAD

**Issue by abdonrd** [howdyai/botkit#1902]
### What are you trying to achieve or the steps to reproduce?

I want to edit a private reply.

```javascript
let sent = await bot.replyPrivate(message, 'this is my original reply...');

await bot.updateMessage({
     text: 'this is an update!',
     ...sent
})
```

However, it works with a public reply:

```javascript
let sent = await bot.reply(message, 'this is my original reply...');

await bot.updateMessage({
     text: 'this is an update!',
     ...sent
})
```

### What was the result you received?

The private message is never edited.

### What did you expect?

Edited message.

### Context:

- Botkit version: `v4.6.2`
- Messaging Platform: Slack
- Node version: `v12`
- Os: macOS

**Comment by benbrown** [comment]
This is a limitation of Slack.  "ephemeral" messages cannot be updated in this way.  See here:

https://api.slack.com/messaging/modifying

**Comment by abdonrd** [comment]
Thanks for the answer, @benbrown!

And private reply has to be necessarily ephemeral, right? Or not?

**Comment by benbrown** [comment]
@abdonrd you could always switch to a 1:1 instead of ephemeral...

**Comment by abdonrd** [comment]
@benbrown, what do you mean with 1:1? Sorry, I'm new with Slack and BotKit.
