### ISSUE TITLE
Feature request: introduce a translation layer between Bot Framework cards and suggested actions to Facebook message format

### ISSUE THREAD

**Issue by benbrown** [howdyai/botkit#1909]
A customer has requested an automatic translation of cards and suggested actions - like those created using Bot Framework's MessageFactory - into the appropriate Facebook format.

Currently the Facebook adapter requires cards to be written in the native Facebook format and placed in channelData.

Ideally this would happen automatically within the adapter, though it may be necessary to implement this as an optional middleware if it would introduce breaking changes.

**Comment by benbrown** [comment]
not stale

**Comment by duztyn** [comment]
Man my old lady cheating ink know is she waste all my money has access to all my shit, but I don’t j need to check her Facebook messssges okessse help

**Comment by andresGarciaInfante** [comment]
is there any information about this requirement?

**Comment by benbrown** [comment]
@GarciaInfante the idea would be to map all of the available Bot Framework cards to their Facebook analogs so that cards created with Bot Framework's Activity factories "just work"

**Comment by GarciaInfante** [comment]
OK. Thanks for the reply.
I'm starting to migrate a workplace chatbot from BotFrameworkAdapter to FacebookAdapter. So all the buttons and cards doesn't display. For now I will do the translation using the Facebook API, but it would be useful to have a middleware.
