### ISSUE TITLE
More than one adapter in the same bot

### ISSUE THREAD

**Issue by RafaelCunhafs** [howdyai/botkit#1910]
Hi,

I would like to know how do I use more than one type of adapter inside my bot, I can't find anywhere in the documentation where I can change the port that is opened for each adapter or even a form of integration between them, being more specific I would like to know how I use the facebook adapter and web adapter in the same bot.

Thanks,
Rafael.

**Comment by ricagurgel** [comment]
same here.

**Comment by maxmeinberg** [comment]
Same here

**Comment by benbrown** [comment]
This sample app implements 3 adapters in the same app:

https://github.com/howdyai/botkit/blob/master/packages/testbot/multiadapter.js

**Comment by benbrown** [comment]
Improvements to this will also be in the next release -> #1929
