### ISSUE TITLE
Important slack event details missing from 'message' object.

### ISSUE THREAD

**Issue by BhuwanBhaskar** [howdyai/botkit#1911]
Ref: https://github.com/howdyai/botkit/blob/a02291c7cef04b65ec5066bd8a8d287dd6c41115/packages/botbuilder-adapter-slack/src/slack_adapter.ts#L594

If slack events come as `event_callback` type then  'authed_users' list is missing from botkit 'message' object.
This is an important information which is missing as we use this list of authed users (for unfurl) to get user details from database.
I think whole payload of slack event should be attached in message object (like in previous botkit versions)

**Comment by benbrown** [comment]
@BhuwanBhaskar ah, hrrm! That field is outside of the main payload.

We should at least copy it into channelData along with the main event.

**Comment by benbrown** [comment]
This will be addressed in the next release -> #1929
