### ISSUE TITLE
Requests get handled before loadModules is called, causing unexpected message loss

### ISSUE THREAD

**Issue by bacongravy** [howdyai/botkit#1923]
The `http.listen` method called in [core.ts#L384](https://github.com/howdyai/botkit/blob/d089a66d353a4246f5ccc9683641e620f9a6b698/packages/botkit/src/core.ts#L384) occurs before the ready handlers have been invoked.  However, the documentation suggests that modules should be loaded in the ready handler, e.g.:

```javascript
controller.ready(() => {
 controller.loadModules('./features');
});
```

In my testing in deploying a Botkit project to a function-as-a-service (FaaS) provider — Zeit Now in this case — this combination appears to have the following consequence:

* A request can arrive and be handled by the express app before the ready handler has been invoked and before the modules have been loaded.

In my case, this meant that a slash_command handler added in a module in `./features` hadn't been loaded yet when the first request arrived, and so that request was automatically responded to with an empty 200 OK.  I confirmed via logging that the ready handler was never invoked at any point during the entire lambda execution, before or after the request; the lambda seems to have been suspended the moment the HTTP request was responded to.

I was able to workaround this issue by doing the following in my code:

```javascript
const http = require("http");
const express = require("express");
const bodyParser = require("body-parser");

const webserver = express();

// capture raw body
webserver.use((req, res, next) => {
  req.rawBody = "";
  req.on("data", function(chunk) {
    req.rawBody += chunk;
  });
  next();
});

webserver.use(bodyParser.json());
webserver.use(bodyParser.urlencoded({ extended: true }));

const httpServer = http.createServer(webserver);

const controller = new Botkit({
  webserver
});

controller.ready(async () => {
  controller.loadModules(__dirname + "/features");
  const port = process.env.port || process.env.PORT || 3000;
  httpServer.listen(port, () => {
    console.log("HTTP server listening on port:", port);
  });
});

controller.on("shutdown", async () => {
  httpServer.close();
});
```

This worked: all of the modules were loaded before the first HTTP request was handled.

Unfortunately, this required me to copy some of the internals of `core.ts` into my project, which seems fragile.

I wonder if it would be acceptable to change Botkit to defer calling `http.listen` until after all of the ready handlers have been invoked? Let me know if a PR to that effect would be welcome.

- Botkit version: 4.6.2
- Messaging Platform: Slack
- Node version: v12.0.0
- Os: Linux (glitch.com)
- Any other relevant information: deployed using the `@now/node` builder to Zeit Now

**Comment by benbrown** [comment]
Your solution is the recommended approach here. Since you have special needs for the webserver, you should configure it yourself and pass it in to Botkit.

**Comment by benbrown** [comment]
Thank you for sharing your solution! This will be useful for future developers!
