### ISSUE TITLE
how to `ask` with quick_replies

### ISSUE THREAD

**Issue by dcsan** [howdyai/botkit#1949]
Question if this is possible, want to have a record.

Trying to create a very simple dialog, question with buttons and capture the answer.
eg

----
Take red pill or blue pill?
[red] [blue]
----

=> capture result.payload to variable `pill`

I've tried a bunch of things with botkit conversations API

// this will 'say' the question but payload/results cannot be captured
```js
    convo.say({
        text: "Take which pill?",
        quick_replies: async(tpl, vars) => [
            {title: 'red', payload: 'red'},
            {title: 'blue', payload: 'blue'}
        ]
    })
```

using `convo.ask` I can't seem to pass a menu / quick_replies as the message, it only takes text.

```
convo.ask(
        {
            quick_replies: async(tpl, vars) => [
                {title: 'red', payload: 'red'},
                {title: 'blue', payload: 'blue'}
            ]
        },
        [
            {
                default: true,
                handler: async(response, convo, bot) => {
                    console.log('other.response', response)
                    await convo.gotoThread('other')
                }
            }
        ]
    )
```

> Error sending activity to Facebook: (#100) Message cannot be empty, must provide valid attachment or text

Seems like it almost might work, but basically the error is just a tease.

```js
    convo.ask(
        {
            attachment: {
                quick_replies: async(tpl, vars) => [
 ...
```

> Error sending activity to Facebook: (#100) The parameter message[attachment][type] is required

Tried various ways to pass an attachment but can't figure out the voodoo.

I could presumably just send a message, and somehow capture payload results, but then I can't use any of the conversations framework, so ... >.<

### What are you trying to achieve or the steps to reproduce?
A simple button menu. Botkit _**must**_ be able to do this????

**Comment by benbrown** [comment]
`Error sending activity to Facebook: (#100) Message cannot be empty, must provide valid attachment or text` means you need to include a `text` or `attachment` field in your message.  You can't send quick replies by themselves.

You should also pass in the third parameter for ask, the variable name into which the value is captured.

so...

convo.ask({text: 'QUESTION TEXT', quick_replies: [...]}, [handler], 'name_of_variable');

**Comment by dcsan** [comment]
also 
> you can use the new 4th parameter to receive the entire message payload if you want
