### ISSUE TITLE
Error: Cannot find module 'skills-validator'

### ISSUE THREAD

**Issue by neemah** [howdyai/botkit#1950]
** DO NOT ERASE THESE INSTRUCTIONS WITHOUT READING THEM FIRST **

### Are you sure this is an issue with the Botkit core module?

Yes, it seems the problem was introduced in the last version upgrade.

### What are you trying to achieve or the steps to reproduce?

`const Botkit = require('botkit');`

### What was the result you received?

<img width="567" alt="Screenshot 2020-03-30 at 18 53 04" src="https://user-images.githubusercontent.com/212695/77939580-b1746b80-72b7-11ea-8dd0-10df0033f09d.png">

### What did you expect?

No error

### Context:

- Botkit version:  0.7.6
- Messaging Platform: 
- Node version: 13
- Os: Linux
- Any other relevant information:

**Comment by benbrown** [comment]
Thanks for the report. Does this happen during npm install?

You are using version 0.7.6 of Botkit? Does rolling back to 0.7.5 fix this?

**Comment by neemah** [comment]
Downgraded to 0.7.5 - problem still persists :(

**Comment by neemah** [comment]
```
cat node_modules/botbuilder/lib/bots/ChatConnector.js| grep skills
var skills_validator_1 = require("skills-validator");
            if (this.settings.enableSkills === true && skills_validator_1.SkillValidation.isSkillToken(authHeaderValue)) {
                var authConfiguration = this.settings.authConfiguration || new skills_validator_1.DefaultAuthenticationConfiguration(this.settings.allowedCallers);
                skills_validator_1.JwtTokenValidation.authenticateRequest(skillMsg, authHeaderValue, new skills_validator_1.SimpleCredentialProvider(this.settings.appId, this.settings.appPassword), req.body.serviceUrl, authConfiguration).then(function (claimsIdentity) {
                    var oauthScope = skills_validator_1.JwtTokenValidation.getAppIdFromClaims(claimsIdentity.claims);
                    var creds = new skills_validator_1.MicrosoftAppCredentials(_this.settings.appId, _this.settings.appPassword, oauthScope);
```

```
ls node_modules/botbuilder/package.json| grep skills

empty
```

**Comment by seawatts** [comment]
@neemah did you ever find a fix for this? I'm seeing the same error.

**Comment by Toolo** [comment]
I started debugging this issue as a fresh https://github.com/looker/lookerbot install and deploy to Heroku consistently threw this error. I've found the following hints:

1. Lookerbot is using a very old version of `botkit`: `0.6.19`
1. `botbuilder` has a `postinstall` script to install `skills-validator` that doesn't seem to be executed unless you use `npm install` in Heroku
1. Even if it's installed, `npm ls skills-validator` fails to resolve the dependency.

Workaround:
```
yarn add ./node_modules/botbuilder/skills-validator/skills-validator-1.0.0.tgz
```

**Comment by RahulSharma92** [comment]
I am facing this same issue when I am upgrading botkit version from 0.7.4 to 0.7.6 . It is necessary for me to upgrade it as I believe this version contains fix for slack oauth v2. I tried above workaround as well but with this heroku deployment just keeps running and it keeps showing 

-----> Installing dependencies

       Installing node modules

Is there any fix available for this issue?

**Comment by benw25** [comment]
`heroku config:set NPM_CONFIG_PRODUCTION=false`

or

`heroku config:set YARN_PRODUCTION=false` (for yarn)

Update the heroku config and deploy via heroku cli is a workaround until the core issue is fixed.  The above commands disable pruning when deploying heroku apps to prod

**Comment by Fermich11** [comment]
I solved the issue deleting the node_modules and installing again the dependencies, but now I'm seeing issues this issue: https://github.com/howdyai/botkit/issues/1988
