### ISSUE TITLE
How to  call third-party api , using botkit-web-adapter

### ISSUE THREAD

**Issue by AnitaDai** [howdyai/botkit#1951]
Hi,
I am new to Botkit and I am trying to run a third-party API  
so for example, if I am asking the BOT "hello, i want to know how to change my Windows password?", I expect to get an  dynamic  answer , which just get a response from the third-party API.
now locally when the Botkit hear number like '12', it will give an constant answer, but i want to get dynamic answer. 

Can you help, please?

I have already try like this, 

controller.hears('sample', 'message_received',  function (bot, message) {
        request('/api/change',
            function (err, response, body) {

                console.log('error: ', err); // Handle the error if one occurred
                console.log('statusCode: ', response && response.statusCode); // Check 200 or such

                text = body;

				 bot.reply(message, text);

            });

})

but it give me this error, 
(node:984) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot perform 'get' on a proxy that has been revoked
(node:984) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

so now i don't know how to solve it. can you give me one sample like this?

**Comment by etiennellipse** [comment]
@AnitaDai This is not an issue with the library.

For such questions, join the slack community here https://community.botkit.ai/
