### ISSUE TITLE
Cannot perform 'get' on a proxy that has been revoked

### ISSUE THREAD

**Issue by saurav28** [howdyai/botkit#1957]
I am using Microsoft bot framework and trying to integrate it with external HTTP calls.

However when i invoke the BotWorker.say in the handler BotKitConversation's ask i start getting

```
 (node:5711) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot perform 'get' on a proxy that has been revoked
Below is my code
```

In my handler function's callback i get some values returned from external function. Then i try to perform bot.say on the response returned and i recieve the above mentioned error.

 ```
myDialog.ask('What would like to hear?', [
    {
        pattern: '.*',
        handler: async (response, convo, bot) => {
            await YoutubeHelper.getChannel(response, convo,async function(channels){
            console.log("value returned " + channels.length);
            try {
            await bot.say('Printing values'); //error comes here

            if (channels.length == 0) {

                await bot.say('No items found.');
              } else {
                await bot.say('This items\'s ID is %s. Its title is \'%s\', and ' ,
                            channels[0].id,
                            channels[0].snippet.title
                            );
              }
            }catch (err) {
                console.log('error occurred' , err);

            }
            });
        }
    }

],  {key: 'name'});
}
```
where myDialog is an object of BotkitConversation.

Below is the code for my external utility class

 ```
/**
 * Lists the names and IDs of up to 10 files.
 *
 * 
 */

var {google} = require('googleapis');

var {myDialog} = require("./bot")

const getChannel = function getChannel(searchTerm, convo,callback) {


    var service = google.youtube({
      version : 'v3',
      auth : '<client id>'});


    service.search.list({
      part: 'id,snippet',
      q: searchTerm
    }, function(err, response) {
      if (err) {
        console.log('The API returned an error: ' + err);
        return;
      }
      var channels = response.data.items;
      if (channels.length == 0) {
        console.log('No items found.');
      } else {
        console.log('This items\'s ID is %s. Its title is \'%s\', and ' ,
                    channels[0].id,
                    channels[0].snippet.title
                    );
      }
      console.log(channels.length);
      callback(channels);
    });
    //

  }

  module.exports ={
    getChannel
}
```
I found this document regarding the error . I am coding according to the guidelines mentioned.

Best Regards,

Saurav

- Botkit version: 4.6.2
- Messaging Platform: None, localhost
- Node version: 8.9.4
- Os: MacOS
- Any other relevant information:

**Comment by benbrown** [comment]
There is something wrong in your promise chain. I believe it is in your custom class.

**Comment by saurav28** [comment]
@benbrown thanks for your reply.

Even if i make call to my custom class synchronous i get the same results. For e.g. if i make like this
` YoutubeHelper.getChannel(response, convo, async function(channels){`

Please note that i get the expected values printed in my console statement just before calling bot.say(). So i presume some issue with the internals of BotWorker.

Can you please let me know why and where this error  " Cannot perform 'get' on a proxy that has been revoked" is raised in botkit internals ?

Best Regards,
Saurav

**Comment by benbrown** [comment]
It is part of the underlying Bot Framework adapter class. Trust me, this happens when a promise is not being respected.

Your youtube helper class is not returning a function that can be awaited. this is the core problem.  You are also mixing callbacks and promises.

**Comment by saurav28** [comment]
@benbrown  thanks for your comments again.

Indeed it was a problem with my helper class. Started returning promise from my helper class and made my code await on that. It started working.

Below is my updated code

`//  __   __  ___        ___
// |__) /  \  |  |__/ |  |  
// |__) \__/  |  |  \ |  |  

// This is the main file for the samplebot bot.

// Import Botkit's core features
const { Botkit } = require('botkit');
const { BotkitCMSHelper } = require('botkit-plugin-cms');

const { BotkitConversation} = require('botkit');

// Import a platform-specific adapter for web.

const { WebAdapter } = require('botbuilder-adapter-web');

const { MongoDbStorage } = require('botbuilder-storage-mongodb');

const YoutubeHelper  = require("./youtubeutil.js");

// Load process.env values from .env file
require('dotenv').config();

let storage = null;
if (process.env.MONGO_URI) {
    storage = mongoStorage = new MongoDbStorage({
        url : process.env.MONGO_URI,
    });
}


const adapter = new WebAdapter({});


const controller = new Botkit({
    webhook_uri: '/api/messages',

    adapter: adapter,

    storage
});

if (process.env.CMS_URI) {
    controller.usePlugin(new BotkitCMSHelper({
        uri: process.env.CMS_URI,
        token: process.env.CMS_TOKEN,
    }));
}

// Once the bot has booted up its internal services, you can use them to do stuff.
controller.ready(() => {

    // load traditional developer-created local custom feature modules
    controller.loadModules(__dirname + '/features');

    /* catch-all that uses the CMS to trigger dialogs */
    if (controller.plugins.cms) {
        controller.on('message,direct_message', async (bot, message) => {
            let results = false;
            results = await controller.plugins.cms.testTrigger(bot, message);

            if (results !== false) {
                // do not continue middleware!
                return false;
            }
        });
    }

});



controller.hears('.*','message', async(bot, message) => {

    //await bot.reply(message, 'Hello Human : ' + message.text);
    
    await bot.beginDialog(DIALOG_ID);

});

//adding code for conversation support

let DIALOG_ID = 'my_dialog_1';
let myDialog = new BotkitConversation(DIALOG_ID,controller);

myDialog.say('Hello');
myDialog.ask('What is your name?', async(answer) => { 
    // do nothing.
}, {key: 'name'});

// collect a value with conditional actions
myDialog.ask('Do you hear Music?', [
    {
        pattern: 'yes',
        handler: function(response, convo,bot) {
            askMusicPreferences(response,convo,bot);
        }
    },
    {
        pattern: 'no',
        handler: async function(response, convo, bot) {
            await convo.gotoThread('hates_life');
        }
    }
],{key: 'response'});

//define the conversation


// define a 'likes_tacos' thread
myDialog.addMessage('Then make a biriyani for Saurav', 'likes_tacos');

// define a 'hates_life' thread
myDialog.addMessage('Music is a soul of life', 'hates_life');


// handle the end of the conversation
myDialog.after(async(results, bot) => {
    const name = results.name;
});

//add a dialog to the controller
controller.addDialog(myDialog);


function askMusicPreferences(answer, convo, bot){


myDialog.ask('What would like to hear?', [
    {
        pattern: '.*',
        handler: async(response, convo, bot, message) => {
            try {
            var channels = await YoutubeHelper.getChannel(response);
            
            if (channels.length == 0) {
                
               await bot.say('No items found.');
            }
               else {
                await bot.say(`This items\'s ID is ${channels[0].id}. Its title is ${channels[0].snippet.title}`);
              }
            
            }catch (error){
                console.log( 'error occurred ', err);
            }
           
             
       // }
        // catch (err){
        //     console.log('error occurred', err);
        // }
       
    }
}
],  {key: 'name'});
}

module.exports = myDialog;

`

And my helper class

`/**
 * Lists the names and IDs of up to 10 files.
 *
 * 
 */

var {google} = require('googleapis');

var {myDialog} = require("./bot")

const getChannelPromise = new Promise((resolve,reject) => {

});


const getChannel = function getChannel(searchTerm) {
    return new Promise(function(resolve,reject) {
   
    var service = google.youtube({
      version : 'v3',
      auth : '<client id>'});
  
    
    service.search.list({
      part: 'id,snippet',
      q: searchTerm
    }, function(err, response) {
      if (err) {
        console.log('The API returned an error: ' + err);
        reject(err);
        return;
      }
      var channels = response.data.items;
      if (channels.length == 0) {
        console.log('No items found.');
      } else {
        console.log('This items\'s ID is %s. Its title is \'%s\', and ' ,
                    channels[0].id,
                    channels[0].snippet.title
                    );
      }
      console.log(channels.length);
      resolve(channels);
      //callback(channels);
    });
    //
  }); 
    
  }

  module.exports ={
    getChannel
}`
