### ISSUE TITLE
Cannot add attachments to convo.say

### ISSUE THREAD

**Issue by jayprat95** [howdyai/botkit#196]
Hi, 

I cannot add attachments inside of conversation replies. This means that you cannot reply in a conversation with a structured message for facebook bots and can't send images or such as replies. 

Also, thanks for building an awesome framework! It's so easy to use

**Comment by eshaham** [comment]
👍 cannot figure out how to include attachments and follow up with facebook_postback if in the middle of a conversation.

**Comment by blanxii** [comment]
If you mean send facebook cards the answer is, yes you can.

Just add a json structure (or some function to make it).

And you can use callbacks with json response.

````bot.reply(message, {
        attachment: {
            type: "template",
            payload: {
                template_type: "button",
                text: "Did you llike it?",
                buttons: [{
                    type: "postback",
                    title: "yes",
                    payload: JSON.stringify({
            action,
            value,
            params
        });
                }, {
                    type: "postback",
                    title: "No",
                    payload: JSON.stringify({
            action,
            value,
            params
        });
                }],
            }
        }
    });````

**Comment by eshaham** [comment]
@blanxii but how do you use it as part of a conversation? `convo.ask`
doesn't seem to support attachments.

**Comment by blanxii** [comment]
@eshaham Sorry didn't read about conversation system. This system didn't support the conversation with cards. You should make something like routing all requests (if you see botkid they make this system for conversation, they add in conversation message something like:

`` <controller_name>#<message>`` 

Controller_name route the current message in those conversation. And you should make something like that.

Send Facebook card with payload:

```
  buttons: [{
       type: "postback",
       title: "Free",
       payload: JSON.stringify({action, value, params });
}

```
When user trigger option you should route it

```
controller.on('facebook_postback', (bot, message) => {
    const payload = JSON.parse(message.payload);
    botPostback[payload.action](bot, message, payload);
});

```

With that you can make a "fake conversation system"...

**Comment by crummy** [comment]
I'd like to be able to embed images in conversation.say(), too. Been poking around other methods but haven't been able to get it to work without bot.reply.

**Comment by crummy** [comment]
Looks like someone's already implemented this and opened a pull request for it. Works great for me with embedded images.
https://github.com/howdyai/botkit/pull/208

**Comment by benbrown** [comment]
This has been fixed via PRs! Thanks guys.  You should now be able to include the attachment field everywhere.
