### ISSUE TITLE
Cannot format URL inside addMessage() method in botkit web starter

### ISSUE THREAD

**Issue by beetisushruth** [howdyai/botkit#1970]
I'm trying to show a url inside a message in botkit web. Formatting url works fine, when `{'text': 'Example url <http://sample.com>'}` message is of this format. But it doesn't work when I'm trying to show the url as `{{vars.sample_message}}`, like this: `{'text': '{{vars.sample_message}}'}`. How should I solve this problem? This is the complete code, below:
```
 order_convo.addMessage(
    {
      text: "{{vars.sample_details}}",
      action: "question_thread"
    },
    "sample_thread"
  );
order_convo.addQuestion(
    {
      text: "Please select an option!",
      quick_replies: [
        { title: "Option 1", payload: "sample" }
      ]
    },
    [
      {
        pattern: "sample",
        handler: async function(response, convo, bot) {
          let sample = "Hello there! <http://foo.com/>";
          convo.setVar("sample_details", sample);
          convo.gotoThread("sample_thread");
        }],
    "main",
    "default"
);
```
You can also check the output in the image, first url is formatted properly, second url is using {{vars.some_variable}}
![stackflow](https://user-images.githubusercontent.com/46922446/81896685-c17bac80-95d2-11ea-854b-94ea2a2430ff.jpg)

**Comment by benbrown** [comment]
I suspect that when you put the link inside a variable like that, it is being escaped somehow so that the client does not recognize it as a link. The links are inserted using a Markdown renderer. Make sure the text is valid markdown when it arrives at the client.

**Comment by beetisushruth** [comment]
@benbrown you're right? If I store an url inside a variable, somehow it is being escaped. I'm using <>  tags for link markdown, how do you suggest I write my links for it work properly?
