### ISSUE TITLE
Broken statement in core.ts when selecting the adapter in the spawn() function of version 4.9.0

### ISSUE THREAD

**Issue by etiennellipse** [howdyai/botkit#1984]
While trying to pinpoint an issue with using a custom adapter and worker within unit tests, I came upon a change that happened in #1938 on core.ts [right here](https://github.com/howdyai/botkit/pull/1938/files#diff-55821637a45d41c6f81a38d283fc253aR1080). It is in the spawn function of the core.ts file, when assigning the `adapter` variable.

[Latest version, line 1093](https://github.com/howdyai/botkit/blob/main/packages/botkit/src/core.ts#L1093)

This condition seems faulty:
````
const adapter = custom_adapter || (config && config.context && config.context.adapter) ? config.context.adapter : this.adapter;
````

It will never return the `custom_adapter`, if one was passed. Since the statement is now a ternary, the custom_adapter will not be returned. 

As in this example:
```
true || (false) ? "1" : "2"
```
The returned value is `"1"`, not `true`.

To get something similar to the previous behaviour, the line should look something like:
```
const adapter = custom_adapter || ((config && config.context && config.context.adapter) ? config.context.adapter : this.adapter);
```

I cannot test this since I have no idea how to pass a custom_adapter to the spawn function! I did not find any test code using it.

### Context:

- Botkit version: 4.9.0

**Comment by benbrown** [comment]
Yikes! That is an unexpected behavior!!!
