### ISSUE TITLE
Bot just goes away

### ISSUE THREAD

**Issue by Kerwood** [howdyai/botkit#200]
I made a bot that works flawlessly.. Except that after around 24 hours, it just goes away. The Node JS app is still running after it goes away and the log gives me nothing, literally .

I've made a getPresence on the bot and it gives me this.
`{"ok":true,"presence":"away","online":false,"auto_away":false,"manual_away":false,"connection_count":0}`

Why is the bot disconnecting ?

**Comment by Glowbal** [comment]
Did you check for the `team_migration_started` event? Perhaps the server your team is on got migrated.

https://api.slack.com/events/team_migration_started

**Comment by Kerwood** [comment]
Cool.. That sound reasonable. But where can i check for this 'team_migration_started' event ?

**Comment by benbrown** [comment]
You should also enable connection retries in your call to controller.spawn:
https://github.com/howdyai/botkit/blob/master/readme-slack.md#controllerspawn

**Comment by Kerwood** [comment]
Thanks @benbrown.. That will properly solve my problem :)

**Comment by mastertinner** [comment]
Is there any reason why `retry` defaults to `false`? That doesn't make too much sense in my opinion.
