### ISSUE TITLE
How do you use custom_hear_middleware for the ask method?

### ISSUE THREAD

**Issue by ninajlu** [howdyai/botkit#201]
The documentation explains how custom_hear_middleware can be used the hear method and also how it can be swapped out for the entire conversation controller. However, how do I use it just for an ask method? 
For example, to add in a NPL intent/entity extraction before I process the response from an ask?

**Comment by benbrown** [comment]
@ninajlu this is not currently possible... but it should be! I will try to add this soon.

**Comment by ninajlu** [comment]
I actually realized this wasn't necessary for my purposes as I found a workaround. I just added the NLP intent/entity extraction into controller.middleware.receive.use and then I only look at the added message.intent and message.entity fields in the ask and ignore them during a normal controller.hear method where I default to the pattern matching.

**Comment by benbrown** [comment]
Cool! But we should still make it work like the `hears` function. Thanks for the idea.
