### ISSUE TITLE
Conversation stays open forever

### ISSUE THREAD

**Issue by MiroValchev** [howdyai/botkit#205]
There seems to be a bug. I can't find timeLimit to be set anywhere for a task.
https://github.com/howdyai/botkit/blob/940c3e004f3b3551e83ce102d1bec9f016c4bf32/lib/CoreBot.js#L381
I have added the following on line 380:
console.log("duration: " + duration + " la: " + lastActive + " tl:" + this.task.timeLimit);
result: 
duration: 2612 la: 1003 tl:undefined

In my scenario there is a conversation going on and if the bot asks a question and there is no response in a timely fashion I expect the conversation to end. However, it can stay open for hours waiting for the reply.

**Comment by MiroValchev** [comment]
Wow, just a closed with not even a comment?

**Comment by peterswimm** [comment]
@MiroValchev sorry about that, Was doing some housekeeping and closed by mistake. Have you tried asking this question on slack4dev?

**Comment by anonrig** [comment]
In order to end the conversation you should call `convo.stop()`

You should look at the Conversation Control Functions @ https://github.com/howdyai/botkit#conversation-control-functions

Let me know, if the problem exists, I will reopen the issue.

**Comment by MiroValchev** [comment]
@anonrig lets say you have asked a question and expect the user to reply. If that doesn't happen in a timely manner, the conversation should be closed. Pretty sure that's the intent behind the link that I gave:
https://github.com/howdyai/botkit/blob/940c3e004f3b3551e83ce102d1bec9f016c4bf32/lib/CoreBot.js#L381
The only trouble is that timeLimit is undefined.

Sounds like a bug to me, but might be wrong.
