### ISSUE TITLE
Throw when a block action element is a select and 'Clear Selection' is clicked.

### ISSUE THREAD

**Issue by reesesm2000** [howdyai/botkit#2053]
When sending an actions block as an interactive message with an external_select element there is a 'Clear Selection' option in the dropdown list. If you select 'Clear Select', there is a throw in slack_adapter.js at line 546 as there is no selected_option. Following line needs to be adapted to cater for null values.

From:
````
                        activity.text = event.actions[0].selected_option.value;
````

To:
````
                        activity.text = event.actions[0].selected_option ? event.actions[0].selected_option.value : undefined;
````

- Botkit version: 4.10
- Messaging Platform: Slack
- Node version: 11.6
- Os: CentOS

![image](https://user-images.githubusercontent.com/26067071/104237496-23bcd380-5426-11eb-8613-c17958563592.png)

**Comment by RiceWorld** [comment]
Same here~!
![image](https://user-images.githubusercontent.com/20451591/204211591-2c7bfaa1-7803-4b6d-901d-bc8e281de4e0.png)
