### ISSUE TITLE
Can't get the multi-line answer working

### ISSUE THREAD

**Issue by airlikidh2** [howdyai/botkit#206]
[SLACK]
Hello,

I would like to use the multi-line option but I can't get it to work. Does anyone has an example?

here is the code snippet I'm using:
```
controller.hears('test','direct_message',function(bot,message) {
		
		var capture_options = {"key":"1","multiple":true};
		
		console.log(capture_options.multiple);
		
		bot.startConversation(message,function(err,convo) {
			if (err) {
				console.log(err);
			} else {
														
				convo.ask("1- How do you feel?",function(response,convo) {
									
					convo.ask("2- How do you run?",function(response,convo) {
										
					
					convo.next();
					},{"key":"2","multiple":true});
				
				
				convo.next();
				},{"key":"1","multiple":true});
				
				convo.on('end',function(convo) {

								var values = convo.extractResponses();
								console.log(values);

					  });
			}
		});
	});
```

Thanks!

**Comment by rafaelamorim** [comment]
Something might have happened during the `setupWebserver `, since this lib start a "ticking" system that rules all those conversation flows, and this ticking starts after the lib tries to subscribe to facebook's webhook. Check if you page token is correct.

Best

**Comment by airlikidh2** [comment]
Hi Rafael,

I forgot to mention, this is an issue for Slack.

**Comment by rafaelamorim** [comment]
Might be the same source of problem...

https://github.com/howdyai/botkit/blob/master/lib/Slackbot_worker.js#L190

**Comment by benbrown** [comment]
@airlikidh2 The issue here is that the conversation will stop listening for input and move on whenever you call convo.next().

If you want to continue to receive input and aggregate it into one response (multiple lines of user input), _do not call convo.next()_ until all of your input has been collected.

**Comment by peterswimm** [comment]
Closing the issue for now, If you have any updates, please feel free to reopen!

**Comment by andreichch** [comment]
@benbrown 
Hi Ben,

With regard to "If you want to continue to receive input and aggregate it into one response (multiple lines of user input), do not call convo.next() until all of your input has been collected.":

in our case, we are not calling convo.next(), but we are calling convo.gotoThread which is probably causing the same effect. How can we understand that all of the user's input in this question has been collected?

Thanks!
