### ISSUE TITLE
Website Certificate Expired

### ISSUE THREAD

**Issue by adamdabbracci** [howdyai/botkit#2061]
It appears that the SSL cert for the website has expired. You can still visit it by opening an Incognito window and confirming that you want to ignore the error.

<img width="682" alt="Screen Shot 2021-02-17 at 9 08 21 AM" src="https://user-images.githubusercontent.com/3945646/108215779-b3c5fb00-70ff-11eb-8de2-dbe46cadd507.png">

<img width="478" alt="Screen Shot 2021-02-17 at 9 06 35 AM" src="https://user-images.githubusercontent.com/3945646/108215712-9f81fe00-70ff-11eb-9fa3-9f29ec1ba558.png">

**Comment by pgoldweic** [comment]
I reported this too on the botkit Slack channel.

**Comment by sfiorotti** [comment]
Same problem! I need docs 😢
