### ISSUE TITLE
Webex botkit adapter: Ability to start adapter without creating a new webhook

### ISSUE THREAD

**Issue by nikosalexakis** [howdyai/botkit#2091]
### Botkit Adapter
botbuilder-adapter-webex v. 1.0.9

### What was the result you received?
A new webhook is being created every time the adapter starts

### What did you expect?
Have the ability to disable auto-creation of webhook

In specific:
We use the webex adapter with botkit. We setup multiple webhooks for specific events in front before the adapter is used.
When the adapter first starts, it is always creating a new "all events" webhook which is listening on "/api/messages"
We need the ability to turn off the webhook creation. 

Thanks in advance,
Nikos

**Comment by nikosalexakis** [comment]
Any update on this?
Thanks

**Comment by nikosalexakis** [comment]
Any update?

**Comment by benbrown** [comment]
This is not currently possible. If you'd like to submit a pull request with this feature, I'd happily review it.
