### ISSUE TITLE
Unable to connect when behind a proxy 

### ISSUE THREAD

**Issue by benmatselby** [howdyai/botkit#21]
We are unable to connect when we need to use a proxy

The http_proxy environment variables are set but this doesn't make a difference 

Should this work behind a proxy?

**Comment by anonrig** [comment]
I've inspected slack_web_api.js file. It uses requestjs for HTTP requests and websockets to connect to slacks websocket api. I believe even with a proxy http requests will work. In theory, websockets seem available for proxy use, but I don't know how `ws` library applies in practice.

Do you have any firewall behind your network which inhibits botkit to use websockets?

@benmatselby

**Comment by RafaelCosman** [comment]
@benmatselby, can you answer @anonrig's question if you have a chance?

**Comment by benmatselby** [comment]
Yes. Sorry about the delay. I am not in the office until Monday so cannot do any checks.

**Comment by benmatselby** [comment]
@anonrig @RafaelCosman 

I've spoken to our networks team and they believe this is something on our side, and are making changes to certain policies, so closing, and will re-open with more information should it still not work

**Comment by jmkhael** [comment]
Hello,
I suffer from the same issue behind our work proxy/firewall. My bot works fine from home where there are no proxying/... going on

Behind the proxy/fw the connection fails (times out on port 443) with botkit whereas the official [node-slack-client](https://github.com/slackhq/node-slack-client) works. (The only difference I noticed is that they use https-proxy-agent in their dependencies...)

I'd like to stay on botkit as the abstractions are nicer :)
