### ISSUE TITLE
WebAdapter deploy on AWS cloud

### ISSUE THREAD

**Issue by direisc** [howdyai/botkit#2121]
Hello,

I need deploy botkit with webAdapter on AWS Cloud infrastructure.
But I don`t see what is the best option.

In my cenary, I need the conversation started on chat load a custom conversation script based a param.
I`m try running on AWS Lambda, but don`t have success.

What is the best form to expose websocket on AWS structure?

**Comment by pgoldweic** [comment]
I don’t know what is the best way to do it, but I've been successful deploying on Elastic Beanstalk, using an Application Load Balancer (this type of load balancer was required at the time I installed it in order to support web sockets – not sure whether it is still the case).
