### ISSUE TITLE
Inaccurate information in documentation of the conversations in v4

### ISSUE THREAD

**Issue by nikakhachi** [howdyai/botkit#2129]
In the official website of botkit, In the conversation documentation thread of v4 release, there is an inaccurate information provided.  https://botkit.ai/docs/v4/conversations.html

The problem is in the example of the threads including cheese topic.
#### The problem : 
in the documentation you see -> 
```
let convo = new BotkitConversation(controller, 'cheese');
```
this code runs into an error
#### The solution : 
convo name must be the first argument and controller the second.
```
let convo = new BotkitConversation('cheese', controller);
```

**Comment by benbrown** [comment]
Fixed! Thanks!

-> https://github.com/howdyai/botkit/blob/main/packages/docs/conversations.md#automatically-switch-threads-using-actions
