### ISSUE TITLE
Botkit storage module for Google Cloud Datastore

### ISSUE THREAD

**Issue by fabito** [howdyai/botkit#213]
Hi,

I just wrote a Botkit storage module for [Google Cloud Datastore](https://cloud.google.com/datastore/docs/).
You can find it here: https://github.com/fabito/botkit-storage-datastore.
Let me know if you are interested in add it into your codebase.

greets
Fábio

**Comment by benbrown** [comment]
This is awesome, @fabito!! Can I create a fork of this in the official Howdy organization so it can live alongside the other storage modules?

**Comment by fabito** [comment]
Yes, sure.

**Comment by anonrig** [comment]
@fabito I've created a pull request. https://github.com/fabito/botkit-storage-datastore/pull/1

**Comment by anonrig** [comment]
I've forked the project to howdyai.
