### ISSUE TITLE
CERTIFICATE EXPIRED for botkit.ai

### ISSUE THREAD

**Issue by deepakmahakale** [howdyai/botkit#2154]
** DO NOT ERASE THESE INSTRUCTIONS WITHOUT READING THEM FIRST **

Please read this entire template before posting any issue to get faster response.

Open an issue on this repository with your topic or question, providing as much detail as possible. The more we know, the better we can help.

Before posting, search the repository to see if there's already an issue opened to avoid duplicates.

### Are you sure this is an issue with the Botkit core module?

For all other questions, requests or help, please feel free to join the discussion slack : https://community.botkit.ai

### What are you trying to achieve or the steps to reproduce?

Describe your issue here, include as much detail as necessary to reproduce the issue or implement a missing functionality.

````
// Wrap code in markdown source tags
````

### Screenshots and animated GIFs

![Screenshot 2021-08-23 at 16 32 27](https://user-images.githubusercontent.com/14993828/130437079-89440f1f-36ed-4f64-9ebb-50724b198d6a.png)

![Screenshot 2021-08-23 at 16 32 32](https://user-images.githubusercontent.com/14993828/130437085-93176002-8a73-4acd-b421-1a9eb20a9638.png)

### Context:

- Botkit version:
- Messaging Platform:
- Node version: 
- Os:
- Any other relevant information:

**Comment by deepakmahakale** [comment]
@benbrown Can we add `certbot` or something if possible to ensure auto renewal?

**Comment by benbrown** [comment]
Its supposed to be automated! I'm not sure why it fails from time to time.

**Comment by deepakmahakale** [comment]
Hi @benbrown I know we removed the references of the site now. But can we deploy it using GitHub pages?

I did open an issue with possible solutions https://github.com/howdyai/botkit/issues/2180 

Let me know if we can help with anything.
