### ISSUE TITLE
Slack app_mention event not treated as a message

### ISSUE THREAD

**Issue by elisherer** [howdyai/botkit#2156]
While using the `app_mention` event in Slack (vs using `message.channel`)
([See reference from Slack's docs](https://api.slack.com/bot-users#setup-events-api))

"message" events are treated as messages while "app_mention" are treated as events (can be listened to with `controller.on('app_mention')`)

Steps to reproduce:
- From Slack - App Events
  - Unsubscribe from `message.channels` and `message.groups`
  - Subscribe to `app_mention`
- From Slack - App OAuth2 Scopes
  - Make sure `app_mentions:read` scope is used
  - Remove `channels:history` and `group:history` scopes.
- After installing the bot again with the updated token, Mention the bot on a channel

The expected is that when mentioned the bot from any conversation it will trigger the messages API (i.e `controller.hears`)
While in actual it doesn't.

### Context:

- Botkit version: 4.10.0
- Messaging Platform: Slack
- Node version: 14
- Os: macOS Big Sur 11.4

### Other information

I assume the issue is in `SlackAdapter.processActivity`
https://github.com/howdyai/botkit/blob/93650237bd19a8cc8aac379436c30f8bb0116c14/packages/botbuilder-adapter-slack/src/slack_adapter.ts#L644
The assumption that a message must have a 'message' type event is wrong and it should be changed to the following:
```js
    if ((event.event.type === 'message' || event.event.type === 'app_mention') && !event.event.subtype) {
```

I managed to make it work adding another middleware just before adding `SlackMessageTypeMiddleware`.

SlackAppMentionToMessageMiddleware.js
```js
const { MiddlewareSet, ActivityTypes } = require("botbuilder");

class SlackAppMentionToMessageMiddleware extends MiddlewareSet {
  /**
   * @param context {TurnContext}
   * @param next {function(): Promise<any>}
   */
  async onTurn(context, next) {
    if (
      context.activity.type === "event" &&
      context.activity.channelData &&
      context.activity.channelData.type === "app_mention"
    ) {
      context.activity.type = ActivityTypes.Message;
      context.activity.text = context.activity.channelData.text;
    }
    await next();
  }
}

exports.SlackAppMentionToMessageMiddleware = SlackAppMentionToMessageMiddleware;
```

#### Usage

```js
...
  adapter.use(new SlackAppMentionToMessageMiddleware());

  adapter.use(new SlackMessageTypeMiddleware());
```

**Comment by benbrown** [comment]
Solving this with the middleware as you did was the correct way to do it! Thanks for documenting this for others.
