### ISSUE TITLE
"Ticking" structure for FB Messenger

### ISSUE THREAD

**Issue by rafaelamorim** [howdyai/botkit#216]
Hello there, thanks for this awesome lib! :)

I just want to understand why you guys chose to have this "second-by-second" ticking system, instead of having them called whenever an action occurs, like receive and send a message.
This ticking system will consume memory and will keep open until a users finishes the conversation :(

So, why this ticking for? Isn't there a better and more fast (even more scalable) way of doing this?

PS.: I've managed to "bypass" the ticking system by adding `botkit.tick();` on lines 821 and 876.

Looking forward to hear from you guys!

Best,
Rafa

**Comment by djeraseit** [comment]
maybe... this functions as a "keep-alive."
nevertheless, I agree with you.

**Comment by rafaelamorim** [comment]
as using this library i realised its a "good way" to keep messages sending in the correct order inside a conversation.
however there is no handling for "killing" the ticking after a conversation ends.
so i hat to implement o start the ticking when a message is received and stop the ticking after a conversation ends, or 2 minutes without activity.

i'll try to improve that later an then ill do a pull request here

**Comment by jay-at-avido** [comment]
Too bad this was closed without an official word on the topic from the original framework creators.
This should also be explained in the docs.

Can we reopen this or create an issue to have this added to the docs?

**Comment by peterswimm** [comment]
@jay-at-avido sure i'll reopen and mark as a feature request!

**Comment by benbrown** [comment]
I'll address this finally!

The ticking is what allows botkit to send multiple outgoing messages as part of a conversation. Each `tick` of the loop, Botkit evaluates all active conversations and takes the next appropriate step.  Without the tick, there is now ay for Botkit to work its way through these message queues.
