### ISSUE TITLE
Is facebook message_referrals via a me link still supported?

### ISSUE THREAD

**Issue by pancake-boy** [howdyai/botkit#2169]
### What are you trying to achieve or the steps to reproduce?

1. Add a me link http://m.me/xxx?ref=abc to a facebook post
2. Enabled webhook event subscription for messaging_referrals
3. click on the link

````
controller.on('facebook_referral', function(bot, message) {
 console.log(message.referral)
})
````

4. this code never triggers

### Additional Questions
Can i still set the menu via the api?

### Context:

"botbuilder-adapter-facebook": "^1.0.11",
"botkit": "^4.10.0",

**Comment by benbrown** [comment]
@pancake-boy Sorry for the extremely late response.

If Facebook still sends this value, it should be available in the `message.channelData.referral` field.

Botkit should still emit the `facebook_referral` event.
