### ISSUE TITLE
High memory usage?

### ISSUE THREAD

**Issue by dosberg** [howdyai/botkit#217]
I'm curious if anyone else is experiencing high memory usage with their apps. I have a node.js/express/postgres app using botkit. It's on Heroku with standard 2x dynos and using a steady 630MB of memory. How much memory are your apps using?

**Comment by peterswimm** [comment]
Did you ever get a good response to this question? You might have better luck on our public developers slack:

dev4slack.xoxco.com

**Comment by thbar** [comment]
@dosberg I'd be curious to know how many slack connections you are using to get that amount of memory? (trying to prototype a high-scale botkit). Thanks!

**Comment by dosberg** [comment]
@thbar I have over 2000 connections with 1.4GB average memory.
