### ISSUE TITLE
How to send message to web adapter at a later point with bot reference or websocket

### ISSUE THREAD

**Issue by deepakmahakale** [howdyai/botkit#2174]
### Are you sure this is an issue with the Botkit core module?

Yes.

### What are you trying to achieve or the steps to reproduce?

We are trying to integrate another application that communicates with the Botkit backend.

The initial conversation happens with the bot but later there comes an agent.

Now we want to send the same message to the web that the agent has sent to the backend.
The communication between the agent and backend is over API calls.

````
let bot = await controller.spawn();
await bot.say('ok');
````

NOTE:

I have the `user_id` where I want to send the message

I found a few similar issues but they are no help since botkit has changed a lot in the last 3 years. - https://github.com/howdyai/botkit/issues/1705

### Context:

- Botkit version: 4.10.0
- Messaging Platform: Web
- Node version: 14.17
- Os: MacOS 
- Any other relevant information:

**Comment by georak** [comment]
any answer on this?

**Comment by georak** [comment]
Maybe this will help you! 

        const bot = await this.botkitController.spawn()

        await bot.changeContext({
            user: {
                id: user
            },
            channelId: "websocket",
            bot: {
                id: "bot"
            },
            conversation: {
                id: user
            }
        })

        await bot.say(message)

**Comment by benbrown** [comment]
I think @georak's answer is correct.

Let me know if you have any further questions.
