### ISSUE TITLE
Multiple slack messages posted

### ISSUE THREAD

**Issue by NiklasBorglund** [howdyai/botkit#2175]
Hi! I'm writing a super simple bot to take one message that's bloated and reposting a less bloated one in another channel. But I can't seem to get it to work properly.

### What was the result you received?
I'm getting multiple messages posted in slack when I use the **reply** method

### What did you expect?
I just want one message in slack.

### Screenshots and animated GIFs

I want to take this type of message:
![image](https://user-images.githubusercontent.com/1174613/137336714-480c95bf-88a0-4809-9d08-9ce3fbc8ad57.png)

And make it into this:
![image](https://user-images.githubusercontent.com/1174613/137335958-111f076f-1ee6-4fa3-a293-8619db9e1a10.png)

But i get multiple messages and it looks like this:
![image](https://user-images.githubusercontent.com/1174613/137335190-0b63a210-4a5b-4380-ba43-f1256eb2f166.png)

### Context:

I'm writing a super simple bot just taking a bloated slack message from the Unity 3D Engine Service->rewrite it to be more condensed and post it in another channel.

The original message from unity is posted into a channel named _rawbugreports_. Depending on the content of the message it till be posted into either a _bugreports_ channel or _bugreports-master_ channel in slack.

I cannot figure out what's wrong here. To me the code looks fine. Anyone knows? Or is it a bug?

The git repo for the bot: https://github.com/NiklasBorglund/UnityUserReportingSlackBot/blob/main/start/bugreportersqueezer.js

- Botkit version: 4.10.0
- Messaging Platform: Slack
- Os: Google Cloud Console

I used this guide to create the bot: https://codelabs.developers.google.com/codelabs/cloud-slack-bot#0

Here are the slack scopes:
![image](https://user-images.githubusercontent.com/1174613/137336308-a2cba038-5d4e-445d-8575-5398558d9db7.png)

Here are the event subscriptions:
![image](https://user-images.githubusercontent.com/1174613/137336431-f7fb4b0e-c7f0-4e32-bd11-4f121dbe19f7.png)

Here's the code for the bot:

````
async function init () {
    const adapter = new SlackAdapter({
        clientSigningSecret: await accessSecretVersion('client-signing-secret'),
        botToken: await accessSecretVersion('bot-token')
    });

    adapter.use(new SlackEventMiddleware())

    const controller = new Botkit({
        webhook_uri: '/api/messages',
        adapter: adapter
    })

    controller.ready(() =>
    {
        controller.on('bot_message', async(bot, event) => {
            return new Promise(async(resolve, reject) => {
                resolve('resolved!');
                if (event.attachments !== undefined && event.attachments.length > 0) {
                    var attachment = event.attachments[0];
                    if (attachment.author_name === 'Unity User Reporting') {
                        var channel = 'bugreports';
                        var fixedTitle = attachment.title;

                        if (fixedTitle.includes('[MASTER]')) {
                            fixedTitle = fixedTitle.replace('[MASTER]', '');
                            channel = 'bugreports-master';
                        }

                        await bot.changeContext(event.reference);
                        var fullSlackMessage = '<' + attachment.title_link + '|' + fixedTitle + '>';
                        await bot.reply(event, {channel: channel, text: fullSlackMessage, unfurl_links: false});
                    }
                }
            });
        });
    })
}
````

**Comment by benbrown** [comment]
Why are you wrapping your response code in an additional promise? I think that might be the problem.

**Comment by NiklasBorglund** [comment]
The extra promise was just a desperate attempt to try fix the issue - it was an issue before I had that in. I just forgot to remove it.

I managed to resolve the issue by disabling retries like this:

`const controller = new Botkit({
        webhook_uri: '/api/messages',
        adapter: adapter,
        webserver_middlewares: [
            (req, res, next) => {
                if (req.headers['x-slack-retry-num']) {
                    res.status(200).send()
                    return
                }
                next()
            }]
    })`
    
    and then when I got the message, I immediately set the status to 200 as well with
    
    `bot.httpStatus(200)`
    
    Not sure if this is the best way to solve it. First slack-bot I've ever written, but it solved the issue for me

**Comment by benbrown** [comment]
Ah, Thanks for adding what worked for you!
