### ISSUE TITLE
How to use Slack socket mode with Botkit?

### ISSUE THREAD

**Issue by vmaligireddy** [howdyai/botkit#2177]
May I know who to use the Slack socket mode with the Botkit library? 
Slack socket mode - https://api.slack.com/apis/connections/socket

**Comment by benbrown** [comment]
In order to do this, you would need to build a custom adapter that handles the socket connections.

**Comment by benbrown** [comment]
You can look at any of the adapter packages in the repo for an example.

**Comment by vmaligireddy** [comment]
Thanks for the details @benbrown. That helps! 

Any plans on Botkit supporting this from the Slack adapter?
