### ISSUE TITLE
Is this repository dead? 

### ISSUE THREAD

**Issue by matteoredaelli** [howdyai/botkit#2179]
Is this repository still maintained? Will new features be released in the future? Or botkit has been evolving somewhere else and only inside Microsoft tools? 

I cannot see answers to issues and new features since long time. Just few changes related to Microsoft/azure...

Regards
Matteo

**Comment by benbrown** [comment]
This repo is not dead. However there are no new features under development at this time. Mostly we just keep things up to date.

What feature do you have in mind?
