### ISSUE TITLE
Suitability for building a legal assistant bot with botkit

### ISSUE THREAD

**Issue by Zolooooo** [howdyai/botkit#2184]
Hi!

We are a legal tech company planning to develop a legal assistant chatbot. I’d like to know more about the suitability of your framework with our needs. So, please answer the following questions:

1.	Is Mongolian supported? 
2.	Is your framework capable of building a chatbot that answers all types of legal questions. Is there a similar use case? (maybe in different industries?) 
3.	If your framework is capable of developing a legal assistance chatbot, approximately how many Q&As (intent & response) do we need to train so that our chatbot provides 10,000 different responses? We’re planning to collect 10,000 answers to 100,000 legal questions (10 questions for each response). Is this enough data to train this type of chatbot? 
4.	What AI methods are used or what types of algorithms are used? 

Best,
Zolo

**Comment by benbrown** [comment]
Botkit provides just the programming mechanism for building bots. In order to do the training and provide the logic and content for your bot, you would need to use an NLU system like QnAMaker.ai from Microsoft or Rasa.
