### ISSUE TITLE
simple_storage.js: "Error: could not load data"

### ISSUE THREAD

**Issue by RafaelCosman** [howdyai/botkit#22]
Here's my code
```
var Botkit = require("botkit");
var simpleStorage = require("./simpleStorage")
```
...
```
var controller = Botkit.slackbot({
  debug: false,
  storage: simpleStorage()
});
```
...
```
controller.hears(['hello','hi'],'direct_message,direct_mention,mention',
  function(bot, message) {
    bot.reply(message,"Hello!");
    
    controller.storage.teams.save({id: message.team, foo:"bar"}, function(err){console.log(err)});
    controller.storage.teams.get(message.team, function(err){console.log(err)})
  }
)
```

**Comment by RafaelCosman** [comment]
Note that ```controller.storage.teams.save``` is sucessfully creating a file under the teams directory containing ```{"id":"T0CV4J33N","foo":"bar"}```.

**Comment by RafaelCosman** [comment]
Could it be that I'm calling get too soon after calling save?

**Comment by RafaelCosman** [comment]
My mistake, I misunderstood how simple_storage works.

**Comment by jonchurch** [comment]
This is the top result for "Botkit storage error Could not load data" right now haha.

For posterity, do you recall what you misunderstood?
