### ISSUE TITLE
Bot can send, but not receive anymore

### ISSUE THREAD

**Issue by derchrisuk** [howdyai/botkit#2214]
Hi there,

I'm getting the below 404 error when trying to mention my bot with a command:

`{"message":"Unable to get message.","errors":[{"description":"Unable to get message."}]`

However it can still send messages into Webex.

I have a suspicion and wanted to check if this might be causing this.
As per the [Webex Developers changelog](https://developer.webex.com/docs/api/changelog)  there was a change on 28. April in regards to no longer accepting UUID formated IDs.
Is Botkit and the Webex module using UUID IDs with my used version?
Maybe this is already fixed in the latest version?

- Botkit version: 0.7.5
- Messaging Platform: Webex
- Node version: 11.15.0
- Os: Ubuntu 18.04

Thanks,
derchris

**Comment by benbrown** [comment]
This seems like the webhook configuration for your bot may not be correct.

**Comment by derchrisuk** [comment]
We were using Websockets using another module, as 0.7.5 had no native support.
I'm currently trying to convert all over to 4.15.0.
At least I can send/receive again, but have to rewrite all my modules.
