### ISSUE TITLE
Newbie Question: Multiple accounts

### ISSUE THREAD

**Issue by paulogr** [howdyai/botkit#222]
Is there a way to run multiple accounts in a single server?

The way that was implemented and documented looks like just one facebook account per instance.

Is that correct?

**Comment by benbrown** [comment]
@paulogr as is, the code is set up to handle one Facebook bot. This is correct.

We _should_ support multiple accounts, however. This is something that should be addressed.  It would require the configuration options be passed into the controller.spawn function instead of the controller.facebookbot initialization.

**Comment by m4olivei** [comment]
Would love to see this in botkit!  In my case I'm building a bot for a media outlet with many brands, all with their own FB Page, that all want very similar functionality.

I'm going to dig in a bit and see if I can help here.  Although my node foo is weak.

**Comment by anonrig** [comment]
For the sake of simplicity and ease in resource management, each botkit instance should run over at different processes. Therefore, a manager class that can basically observe the two botkit instances can be done, without the support of a multiple account feature.

**Comment by m4olivei** [comment]
@anonrig not sure I follow, what do you mean by:

> a manager class that can basically observe the two botkit instances can be done

Forgive my ignorance.  Do you maybe have some links/examples that you could point me at explaining such things?

**Comment by anonrig** [comment]
Don't worry @m4olivei 

I was thinking a solution to instantiate two different botkit instances using a super class which has the observer design pattern. (An example: http://www.tutorialspoint.com/design_pattern/observer_pattern.htm)

**Comment by m4olivei** [comment]
@anonrig I see so your still in favour of making this possible, you're just suggesting a certain implementation path?  Is the solution your suggesting something that would ship with Botkit out of the box, or is this something that is the responsibility of me, as a user of the botkit package?

**Comment by anonrig** [comment]
I don't think that Botkit should allow multiple accounts implementation. I believe that the main purpose of Botkit will change if this feature is implemented. If you have any further questions about how to implement such Observer pattern for Botkit instances, feel free to send me a message from dev4slack.slack.com
