### ISSUE TITLE
convo.say doesn't work with Facebook structured messages

### ISSUE THREAD

**Issue by m4olivei** [howdyai/botkit#237]
I'm trying the following and it's not working for me:

```js
controller.hears([/\b(hello|hi)\b/i], 'message_received',
  (bot, message) => {
    bot.startConversation(message, (err, convo) => {
      if (!err) {
        convo.say('Hi there! What would you like to do?');
        convo.say({
          attachment: {
            type: 'image',
            payload: {
              url: 'http://placehold.it/1910x1000/30c7e1/222222?text=Test',
            },
          },
        });
      }
    });
  });
```

Does `convo.say` support structured messages?  If so, what am I doing wrong, if not, is it difficult to support it?

**Comment by benbrown** [comment]
@m4olivei make sure you are using the latest version of Botkit! 0.1.2 introduced a fix for this issue.

**Comment by m4olivei** [comment]
@benbrown ha!  Thanks!  I just found that issue now.  My Google foo is weak.  Sorry about that.

**Comment by benbrown** [comment]
No worries! Happy bot making! Share your final bot with us when you're done!! :)

Have you joined us at dev4slack.xoxco.com? Lots of developers ready to answer questions.
