### ISSUE TITLE
Can a bot listen for ambient messages from other Slack bots?

### ISSUE THREAD

**Issue by jrobalino** [howdyai/botkit#239]
Thanks for providing botkit. I used it to quickly get a Slack bot up and running. The bot listens to ambient messages from users in the channel and performs actions if it hears certain keywords. However, the Slack bot doesn't seem to detect keywords from messages that other bots post in the channel. Do you know if listening to other bots is possible?

**Comment by fradioflyer** [comment]
I had this problem, too, and solved it just yesterday.  You need to listen for the 'bot_message' event.

**Comment by jrobalino** [comment]
Gotcha. So it seems that I would have to add a handler to SlackBot.js, correct? Or is a bot_message event handler already included with botkit?

**Comment by fradioflyer** [comment]
I didn’t mess with SlackBot.js.  

I’m in my own .js file.  I added a method like so - 
controller.on('bot_message', function(bot, message) {
//do some stuff with the bot message
});


where, controller and bot were previously defined as...

var controller = Botkit.slackbot({
  storage: bot_storage  //this is my own storage implementation for Cloudant
});
var bot = controller.spawn({
  token: my_slack_bot_token
})

**Comment by jrobalino** [comment]
Thank you!
