### ISSUE TITLE
Bot status away apparently with no reason

### ISSUE THREAD

**Issue by frangarcia** [howdyai/botkit#253]
I have created a bot which works fine for some hours (even days) but, with no reason, some times the bot is status is marked as away and I cannot interact with it. The bot is still running in the server, it didn't crash and I don't see any error log. Does anybody know what is happening?

**Comment by rbad** [comment]
Same thing happens to me (typically after a week). Wondering if there might be a way to do a periodic check of Slack connection status, and, if necessary, trigger a startRTM method call again.

**Comment by peterswimm** [comment]
Closed due to inactivity, please continue the discussion on dev4slack!
