### ISSUE TITLE
After destroying a conversation

### ISSUE THREAD

**Issue by anonrig** [howdyai/botkit#26]
Upon destroying a conversation, creating a new conversation is buggy. This stacktrace can be used.

In order to reproduce: 
- start a conversation using bot.startConversation
- ask several questions
- on callback of convo.ask('question 1') call convo.stop()
- try to create a new conversation

```
/Users/anonrig/Desktop/projects/botkit/node_modules/botkit/lib/Slackbot_worker.js:234
            if (cb) { cb(null); }
                      ^
TypeError: cb is not a function
    at /Users/anonrig/Desktop/projects/botkit/node_modules/botkit/lib/Slackbot_worker.js:234:23
    at afterWrite (_stream_writable.js:346:3)
    at onwrite (_stream_writable.js:337:7)
    at TLSSocket.WritableState.onwrite (_stream_writable.js:89:5)
    at WriteWrap.afterWrite (net.js:775:12)
```

**Comment by benbrown** [comment]
@anonrig I am not able to duplicate this issue. Can you provide more context?

**Comment by peterswimm** [comment]
No further feedback from OP, closing the ticket for now.
