### ISSUE TITLE
Ask for a question and wait for response based on that question.

### ISSUE THREAD

**Issue by Olamyy** [howdyai/botkit#263]
**Is there any way i can ask my bot a question and make it wait for a response to that particular question so i could do some more things on that particular message?**

**Comment by krismuniz** [comment]
@Olamyy, yes there is!

Just call the `.startConversation()` method and then call `convo.ask()` inside of its callback function. 

Quick (pizza) example:
```javascript
controller.hears(['pizza'], 'message_received', function (bot, message) {
  // start a conversation to handle this response
  bot.startConversation(message, function (err, convo) {
    if (err) console.log(err)
    // start a question
    convo.ask('Did you just say pizza?', function (response, convo) {
      if (response.text === 'yes') {
        convo.say('I knew it! :D I want pizza. NOW!')
      } else {
        convo.say('Oh... okay. I thought I heard... nevermind, sorry :(')
      }
      convo.next() // always call this to keep things flowing (check the readme for more info)
    })
  })
})
```

Check out the [Control Conversation Flow](https://github.com/howdyai/botkit/blob/master/readme.md#control-conversation-flow) section of the `readme.md` for a better, more detailed explanation.

Hope this helps. :)

**Comment by peterswimm** [comment]
If you still have any questions please let us know!
