### ISSUE TITLE
Facebook bot is not working anymore.

### ISSUE THREAD

**Issue by blanxii** [howdyai/botkit#265]
Facebook add a new "callback" message called read, it delivery when the message is read.

```
botkit.log('Got an unexpected message from Facebook: ', facebook_message);
```

It throws a new exception called from "botkit" is not defined. I just changed to console.log at the moment and add a new condition to catch read events and avoid write in the console.log to avoid massive logs on the console.

Greetings

**Comment by krismuniz** [comment]
This has been fixed on PR https://github.com/howdyai/botkit/pull/266 :)
