### ISSUE TITLE
Make my  bot listen to user status

### ISSUE THREAD

**Issue by Olamyy** [howdyai/botkit#267]
Hey, 
So i am writing a bot that acts as my personal assistance(by answering my messages when am not active).
Now, what i need is look for a way for the bot to check my status(If i am active or not) and also a way for the bot to help me switch status(so, i can give it permissions to answer my messages).
Is there anyway i can do this with the framework?

**Comment by nobukatsu** [comment]
You can use users.getPresence API to check someone's status.
https://api.slack.com/methods/users.getPresence

```javascript
controller.hears(['test'],'direct_message,direct_mention,mention',function(bot, message) {
	bot.api.users.getPresence({
		token: 'your-api-token',
		user: 'U1234567890'
	}, function(err, res){
		if(res.presence === 'active'){
			// active
		}else{
			// away
		}
	});
});
```

**Comment by peterswimm** [comment]
@Olamyy did this help your issue?

**Comment by Olamyy** [comment]
Yeah.
Thanks.

**Comment by peterswimm** [comment]
Great! Going to go ahead and close this issue for now.
