### ISSUE TITLE
Adding .com to keyword does not trigger on slack

### ISSUE THREAD

**Issue by mateeyow** [howdyai/botkit#270]
I wonder why this code works:

```js
controller.hears('google is down',['direct_message,direct_mention,mention'],function(bot,message) {
  return bot.reply(message, 'Okay');
});
```

while adding `.com` to the keyword does not work:

```js
controller.hears('google.com is down',['direct_message,direct_mention,mention'],function(bot,message) {
  return bot.reply(message, 'Okay');
});
```

**Comment by amplicity** [comment]
maybe it's interpreting the `.` as part of regex?

I would try setting up another file for your keywords, such as `commands.js`

This way you can do:

let commands = {
    google: ['google.com is down']
}

and then 

controller.hears(commands.google,'direct_message,direct_mention,mention'],function(bot,message) {
  return bot.reply(message, 'Okay');
});

**Comment by mateeyow** [comment]
@amplicity still doesn't work.

**Comment by mateeyow** [comment]
It seems slack adds formatting when giving a url value so `google.com` becomes `<http://google.com|google.com>`

**Comment by lauripiisang** [comment]
yeah, that's the unfurling feature in action. you can disable it for messages you send out. for incoming messages, I recommend parsing them as regex if URLs are involved with other message components.

Parsing a URL on its own works fine though.

**Comment by bongsoloeut** [comment]
hi!!!!!!

<a href="http://bohansports.net">ผลบอล</a>
<a href="http://bwwsbbet.com">บอลวันนี้</a>
<a href="http://www.baccarat44.com">บาคาร่าออนไลน์</a>
