### ISSUE TITLE
Bug: 'client' bots for slack don't reply to owning user's messages

### ISSUE THREAD

**Issue by lauripiisang** [howdyai/botkit#271]
When you use a slack bot with 'client' permission (permission to see all messages the user sees and say stuff on behalf of the user), there's currently a bug where the bot doesn't hear the message of the owning user, since the ID is considered to be the user's ID.

I've fixed this in https://github.com/howdyai/botkit/pull/268 by checking for presence of bot_id in the message, if the user id matches.This ensures a client bot won't hear itself, but will hear it's owner.

An additional fix would be to also check for **ANY** presence of bot_id if you don't want bots to talk to eachother.

// Background
I used botkit to build an RTM listener that allows people to connect with client privileges, spawns a bot for each of those users, which will reply to certain keywords. This enables bot answers based on context, even in private chats. And you never have to invite an actual bot anywhere. You are the bot.

**Comment by lauripiisang** [comment]
What's complicated here? I've already added the pull request that deals with this!

**Comment by peterswimm** [comment]
Pr merged! closing!
