### ISSUE TITLE
How do I scale this?

### ISSUE THREAD

**Issue by thelinuxlich** [howdyai/botkit#272]
Is it just spawning more botkit processes and the frameworks takes care of duplication?

**Comment by Dinoshauer** [comment]
No, you'll need something that takes care of distributing tokens between processes. For example zookeeper can solve that problem for you, I'm sure there are simpler solutions as well :)

**Comment by peterswimm** [comment]
Closing for now, feel free to discuss this further on dev4slack! 
http://dev4slack.xoxco.com/
