### ISSUE TITLE
Please update the Wit-ai middleware.

### ISSUE THREAD

**Issue by vs1682** [howdyai/botkit#273]
On 2016, May 11th, the /message API was updated to reflect the new Bot Engine model: intent are now entities. We updated the SDK to the latest version: 20160516.
There are some new [pull requests](https://github.com/howdyai/botkit-middleware-witai/pulls) in the [botkit-middleware-witai](https://github.com/howdyai/botkit-middleware-witai) repo, please check them out and do the needful.

Thank You.

**Comment by dfischer** [comment]
I updated it here: https://github.com/dfischer/botkit @vs1682

**Comment by vs1682** [comment]
@dfischer I'll check it.
thank you.

**Comment by peterswimm** [comment]
This looks like this has been updated, if not please post an issue on the wit.ai middleware repo.
