### ISSUE TITLE
facebook payload not working

### ISSUE THREAD

**Issue by yaminodestiny** [howdyai/botkit#275]
controller.hears('test', 'message_received', function(bot, message) {

    var attachment = {
        'type':'template',
        'payload':{
            'template_type':'generic',
            'elements':[
                {
                    'title':'Chocolate Cookie',
                    'image_url':'http://cookies.com/cookie.png',
                    'subtitle':'A delicious chocolate cookie',
                    'buttons':[
                        {
                        'type':'postback',
                        'title':'Eat Cookie',
                        'payload':'chocolate'
                        }
                    ]
                },
            ]
        }
    };

    bot.reply(message, {
        attachment: attachment,
    });

});
controller.on('facebook_postback', function(bot, message) {

    if (message.payload == 'chocolate') {
        bot.reply(message, 'You ate the chocolate cookie!')
    }

});

But bot did not reply You ate the chocolate cookie!

Reason found

**Comment by peterswimm** [comment]
Closed due to inactivity.

**Comment by azanoni** [comment]
I have the same issue...any fix about that?

**Comment by peterswimm** [comment]
@azanoni please start a new issue with an example of the code that doesn't work.

**Comment by azanoni** [comment]
I started here https://github.com/howdyai/botkit/issues/814 its rare that a issue still not working for a year ago

**Comment by azanoni** [comment]
I resolve this issue with this comment 
https://github.com/hyperoslo/facebook-messenger/issues/15#issuecomment-216933326

The botkit readme should be updated.

**Comment by peterswimm** [comment]
@azanoni We are planning on a Facebook provisioning doc that contains a sane list of subscriptions to get you started, thanks for the reminder!

**Comment by apotox** [comment]
payload  will not work , you need to check the **messages_postback** in Webhook settings
