### ISSUE TITLE
bot.say doesn't work with facebook structured messages?

### ISSUE THREAD

**Issue by morsidi** [howdyai/botkit#281]
For some reason it doesn't work.. (I tested it on convo.say() and it worked there, but here I have to use bot.say since I initiate a message from the server).

bot.say({ text: {
        "attachment": {
            "type": "template",
            "payload": {
                "template_type": "generic",
                "elements": [{
                    "title": "TITLE",
                    "subtitle": "SUBTITLE",
                    "buttons": [{
                        "type":"postback",
                        "title":"CTA",
                        "payload":"payload_click"
                    }]  
                }]
            }
        }
    }, channel: id });

**Comment by sporkd** [comment]
Getting the same for Slack bot. It looks like bot.say is not implemented https://github.com/howdyai/botkit/blob/master/lib/CoreBot.js#L897-L899

**Comment by agamrafaeli** [comment]
`bot.say()` is not implemented in the Facebook implementation of botkit.

@peterswimm / @benbrown any thoughts on how this should be implemented?

**Comment by alexbudin** [comment]
You can use bot.reply() or bot.replyWithTyping() or you can use convo.say() if you are in a conversation. All these work fine with botkit on FB.
