### ISSUE TITLE
Find UserID from Username?

### ISSUE THREAD

**Issue by joelcasteel** [howdyai/botkit#282]
I'm working on programming a simple bot that you can have send bad news to someone else in your Slack Domain. I've run into a bit of a problem. As far as I've seen, the only way for a bot to initiate a new conversation is to use `startPrivateConversation()`. The problem is that in order to do that the bot needs to know the Users ID. 
      Not to big of an issue, but I want users to be able to type the username  (@joeshmoe for example) rather than having to know the userID. Is there any way to start a conversation using the username rather than the ID. If not, is there a way to extract the userID from the username.
      Thanks for any help! I'm fairly new to this so if the solution is painfully obvious you'll just bear with me.

**Comment by anhuynh** [comment]
Slack's @mentions will get received as `<@userID>`. So you can just parse the message for that string and then extract the userID to use with `startPrivateConversation()`

**Comment by joelcasteel** [comment]
Sweet! Thank you so much!
