### ISSUE TITLE
botkit should respond to multiple hears events

### ISSUE THREAD

**Issue by jayjanssen** [howdyai/botkit#286]
It seems that botkit will only respond to the _first_ pattern matched in a 'hears' callback.  I contend it should match _all_ of them and fire all the callbacks accordingly. 

Is there some reason this doesn't work?

**Comment by whatevernot** [comment]
FWIW, I agree - just ran into the same issue and looking into a workaround.

A flag, or a done callback (or whatever) to handle multiple hears matching would be great - it's an awesome library.
