### ISSUE TITLE
Fibers incompatibility?

### ISSUE THREAD

**Issue by nikolay** [howdyai/botkit#292]
As I'm running something in a Fiber and using a Future to wait for it, `convo.say()` does not seem to work after the Fiber is done. Any ideas?

**Comment by dfischer** [comment]
It's probably not recognizing the environment it's in

**Comment by peterswimm** [comment]
Did you ever sort out a solution for this problem?

**Comment by nikolay** [comment]
@peterswimm No. The conversation goes into a black hole.

**Comment by peterswimm** [comment]
I'll label it as a bug in case anyone wants to dig deeper and submit a PR.
