### ISSUE TITLE
node version?

### ISSUE THREAD

**Issue by dcsan** [howdyai/botkit#310]
I'm using node 5.9
and get the warnings below on installing botkit.
surely it's not requiring a version < 1.0 of node?

```
$ npm install --save botkit
npm WARN package.json botkitapp@0.0.1 No description
npm WARN package.json botkitapp@0.0.1 No repository field.
npm WARN package.json botkitapp@0.0.1 No README data
npm WARN engine back@1.0.1: wanted: {"node":"0.12.x || 0.10.x || 0.8.x"} (current: {"node":"5.9.1","npm":"2.14.20"})
botkit@0.2.2 node_modules/botkit
```

**Comment by donavon** [comment]
Why is this closed without an answer? Will this work with modern Node versions 4.x and higher?

**Comment by YemSalat** [comment]
I think thats a warnning from module `back`, not botkit itself.
Perhaps you installed it with an older version of node? Try `rm -rf node_modules` and `npm install` again.

**Comment by dcsan** [comment]
I closed it after asking, the pointer above is indeed the answer.

**Comment by donavon** [comment]
Have you filed an issue with `back`?
