### ISSUE TITLE
Is there any best practice of anatomy of a script like hubot?

### ISSUE THREAD

**Issue by mttrs** [howdyai/botkit#313]
Would botkit support for anatomy of a script like hubot? My controller is getting bigger when adding a new listener. It's not good idea to write everything in a single file. I'm thinking to make something, but if your team have any idea or suggestion, could you please share it?

* Added sample code
```javascript
// bot.js(main file)
var Botkit = require('botkit');
controller = Botkit.slackbot({});

controller.spawn({
  token: process.env.SLACK_TOKEN,
}).startRTM();

// I'd like to split each listener below in a file.

// ping.js
// first listener
controller.hears([/^ping$/i], ['direct_message', 'direct_mention', 'mention'],
  function(bot, message) {
    bot.reply(message, 'pong');
});

// ping2.js
// second listener
controller.hears([/^ping2$/i], ['direct_message', 'direct_mention', 'mention'],
  function(bot, message) {
    bot.reply(message, 'pong2');
});

// and more...
// controller.hears(...
```

hubot way
https://hubot.github.com/docs/scripting/

Thanks

**Comment by mttrs** [comment]
Added codes to clear my question.

**Comment by mttrs** [comment]
Now I take the following way to load files under scripts dir. The idea is from hubot's robot.coffee 
https://github.com/github/hubot/blob/9fe938f35362e20f7c0e3da57370a3ec9bc5a490/src/robot.coffee#L344

The bad thing is to use `global` object to share the `slackbot` instance. I wanted to load files in CoreBot.js for making the file loading as core function, but didn't find a way. Do you have any suggestions or ideas?

```
const Fs = require('fs');
const Path = require('path');

global.controller = Botkit.slackbot();

controller.spawn({
  token: process.env.SLACK_TOKEN,
}).startRTM();

let loadFile = function(path, file) {
  let ext = Path.extname(file);
  let full = Path.join(path, Path.basename(file, ext));

  if(require.extensions[ext]) {
    try {
      require(full);
    } catch(_err) {
      let err = _err;
      console.log(`Unable to load ${file}: ${err.stack}`);
      return process.exit(1);
    }
  }
};

let path = Path.resolve('.', 'scripts');
Fs.stat(path, function(err, stat) {
  if(err) {
    console.log(err.message);
  } else {
    console.log(`Loading scripts from ${path}`);
    let ref = Fs.readdirSync(path).sort();

    for(let i = 0, len = ref.length; i < len; i++) {
      let file = ref[i];
      loadFile(path, file);
    }
  }
});
```

**Comment by peterswimm** [comment]
Closed due to inactivity, question answered.

**Comment by mttrs** [comment]
I appreciate if any feedbacks!

**Comment by peterswimm** [comment]
You should also posit this question on dev4slack, much more developer traffic there!

**Comment by mttrs** [comment]
oh, thanks!
