### ISSUE TITLE
Question about Botkit's prerequisites

### ISSUE THREAD

**Issue by kenjing** [howdyai/botkit#314]
I had to install node in my lubuntu for my case. So it would help to have some prequestisite list in the procedure to test out this.

**Comment by peterswimm** [comment]
Hello,

The readme says that Botkit requires Node:
https://github.com/howdyai/botkit/blob/master/readme.md

Once that is installed via NPM you should be good to go!

**Comment by kenjing** [comment]
Thanks will try that.  I did the git clone directly so maybe thats why. thanks again!

**Comment by kenjing** [comment]
Totally my fault for not reading all the commands step by step.

**Comment by peterswimm** [comment]
No problem! Closing for now, if you have any other questions let us know!

PS:http://dev4slack.xoxco.com/
