### ISSUE TITLE
Are slack user/channel ids unique across team?

### ISSUE THREAD

**Issue by rokoroku** [howdyai/botkit#315]
I saw slack's user and channel model are related with **team_id**, but the included storage is just using each model's id as unique key without **team_id**.

After googling an hour, I found this SO answer:
http://stackoverflow.com/a/35634747 

So I think it's better to use compound key for storing/restoring them.

**Comment by thbar** [comment]
@rokoroku I wonder if this applies only to channels etc, but not users, maybe? Did you get further informations on that? (I'm connecting a large number of teams, so a collision is more likely). Thanks!

**Comment by peterswimm** [comment]
It is a good idea to use a combination of team and user IDs for bots that need to share information across teams.
