### ISSUE TITLE
Bot(botkit-middleware for Wit.ai and Slack) does not reply anything to SLACK.

### ISSUE THREAD

**Issue by sanster23** [howdyai/botkit#321]
I have followed https://github.com/howdyai/botkit-middleware-witai for Wit.ai created bot to work with Slack

![screenshot from 2016-07-12 17 31 14](https://cloud.githubusercontent.com/assets/15207772/16766231/7c43bf4a-4856-11e6-9a0c-0489c85583a4.png)

But all it does is display this following result in console 

![screenshot from 2016-07-12 17 33 35](https://cloud.githubusercontent.com/assets/15207772/16766287/d14e9b5e-4856-11e6-98da-b05a34250407.png)

So can you guys help as how to get the message to my Slack chatbot(I created a custom integration chatbot)?

Thanks in advance

**Comment by anonrig** [comment]
Unfortunately, wit-ai module for botkit uses the deprecated version of wit-ai. This is an issue with the wit-ai middleware, not with botkit itself.

**Comment by manojkumar1412** [comment]
Is there any plan to update botkit to use wit new api?

**Comment by rossedman** [comment]
@anonrig @sanster23 @manojkumar1412 Not trying to hijack but noticing this is happening with recast middleware as well. I have opened an issue on that, but seeing this makes me wonder if something has changed in botkit?
