### ISSUE TITLE
authenticationMiddleware Wrongfully called on index Route

### ISSUE THREAD

**Issue by gDelgado14** [howdyai/botkit#322]
Using Botkit 0.2.2

`secureWebhookEndpoints` in [SlackBot.js](https://github.com/howdyai/botkit/blob/master/lib/SlackBot.js#L106) uses `authenticationMiddleware`, but does not specify a path. Path should *presumably* be `/slack/receive`. Otherwise, `authenticationMiddleware` gets called on GET requests to landing page. 

As per [Express documentation](http://expressjs.com/en/api.html#app.use), if no path is specified, it defaults to "/".

**Comment by peterswimm** [comment]
If this is still causing trouble for you, would love to see a PR that fixes it in the examples.
