### ISSUE TITLE
Slack Interactive Button presses being passed into conversation if they aren't related to it

### ISSUE THREAD

**Issue by malonehedges** [howdyai/botkit#326]
I send a message with buttons and one of the buttons is `Add a description`.

When that button is pressed I `bot.startConversation` and `bot.ask` a question prompting the user for a description for my item.

If the user presses a button, say the `Add a description` button, instead of typing a response into chat, this event is passed into the conversation and the `interactive_message_callback` listener.

Is there a way to distinguish if there is a conversation going on? Is there a way so that I can either ignore this event at the `interactive_message_callback` or implement logic at the conversation level to ignore this button press?

**Comment by dcsan** [comment]
I have a similar issue, for a global menu, which sends `facebook_postback` messages to the controller.

**Comment by malonehedges** [comment]
I found that you can properly use `bot.findConversation` if this is compensated for: https://github.com/howdyai/botkit/blob/7a2c61c142137a9b3e6bcf5e1dd8ac9e9b2c0ed6/lib/Slackbot_worker.js#L562

I don't know why it currently checks to make sure that the message is of a certain type. By setting `message.type = 'message'` prior to calling `bot.findConversation(message)` it works as it should.
