### ISSUE TITLE
botkit should contain all matches in a regex pattern

### ISSUE THREAD

**Issue by ivanstegic** [howdyai/botkit#327]
With a regex pattern like `[A-Z][A-Z0-9]+-[0-9]+` that matches a typical JIRA issue ID, if the incoming message contains more than one ID, all matches should be included in the matched pattern. Trying to use the standard global modifier `/([A-Z][A-Z0-9]+-[0-9]+)/g` breaks the match completely, with not even the first match coming through a `controller.hears()` call.

If the incoming message is
> Here is some text with a JIRA-11 like issue id in it, and there is actually more than one GT-33 in here. There are  really three FR-390990 issue IDs.

Then this code

```javascript
controller.hears(['[A-Z][A-Z0-9]+-[0-9]+'], ['ambient'], function (bot, message) {
  console.log(message);
});
```

will contain a match for `JIRA-11` but not for `GT-33` or `FR-390990` -- this is expected. If you modify the code to include the global modifier, like this

```javascript
controller.hears(['/([A-Z][A-Z0-9]+-[0-9]+)/g'], ['ambient'], function (bot, message) {
  console.log(message);
});
```
or even like this without the `(` and `)`
```javascript
controller.hears(['/[A-Z][A-Z0-9]+-[0-9]+/g'], ['ambient'], function (bot, message) {
  console.log(message);
});
```
there are no matches. You would expect all three issues to be matched, as can be confirmed here for the structure of the regex: http://regexr.com/3dqpr

Unless I've missed documentation that implements another global modifier, I think this is a valid bug. And I also think it is somewhat related to #286

Using botkit v0.1.1, on Mac OS X El Capitan.

**Comment by YemSalat** [comment]
Try passing it w/o single quotes: 
```
controller.hears([/[A-Z][A-Z0-9]+-[0-9]+/g], ['ambient'], function (bot, message) {
  console.log(message);
});
```

Cause that's JavaScript syntax for regex literals - they are not supposed to have quotes.

**Comment by ivanstegic** [comment]
@YemSalat sorry, but that doesn't work either.

**Comment by peterkinmond** [comment]
Using @YemSalat's solution above (regex with `/g` flag) I'm able to get multiple matches returned from the regex. 

```
controller.hears([/[A-Z][A-Z0-9]+-[0-9]+/g], ['direct_message'], function (bot, message) {
  console.log(message);
  console.log(message.match.length);

  for(var i = 0; i < message.match.length; i += 1) {
    bot.reply(message, `Match found: \`${message.match[i]}\``);
  }
});
```

Here's a screenshot of the bot running locally:
<img width="955" alt="screen shot 2016-07-26 at 4 47 10 pm" src="https://cloud.githubusercontent.com/assets/779389/17159372/90e92bf0-5351-11e6-8a83-b5dc4092638b.png">

Here's the console output for the `message` object:
```
{ type: 'message',
  channel: 'D130WSUDA',
  user: 'U0JP3DY21',
  text: 'Here is some text with a JIRA-11 like issue id in it, and there is actually more than one GT-33 in here. There are really three FR-390990 issue IDs.',
  ts: '1469576859.000083',
  team: 'T0JP7PABG',
  event: 'direct_message',
  match: [ 'JIRA-11', 'GT-33', 'FR-390990' ] }
```

@ivanstegic Can you show what gets outputted when you print the message object to the console?

**Comment by peterswimm** [comment]
Closed for inactivity, if the above did not help please let us know.

**Comment by prichey** [comment]
FWIW I've also had success with the RegExp constructor.

E.g. 
```
controller.hears([new RegExp('[A-Z][A-Z0-9]+-[0-9]+')], ['ambient'],  (bot, message) => {
  console.log(message);
});
```
