### ISSUE TITLE
Persisting conversations

### ISSUE THREAD

**Issue by eshaham** [howdyai/botkit#330]
I wanted to check if anyone here has any thoughts about how to persist the chatbot's conversations. Since a conversation could take a significant amount of time, there are scenarios in which the in-memory nature of conversations does not survive server reboots / deploys / crashes.

Saving the context of the conversation at any point in time is easy. Getting the bot back to the exact same place after an app restart is something I'm not sure how to do.

Any thoughts?

**Comment by bcaller** [comment]
Also, I wonder about multiple instances of the bot running.

**Comment by lucasgreene** [comment]
Yes this is a super important thing to have for horizontal scaling. Anyone have any good ideas?

**Comment by bcaller** [comment]
It would probably require a massive redesign avoiding closures and instead having named functions. For each user you can then store a conversation state and the name of the function to resume when the user replies. [@Microsoft/BotBuilder](https://github.com/Microsoft/BotBuilder) looks quite good for this, with persistence by implementing [IBotStorage](https://github.com/Microsoft/BotBuilder/blob/master/Node/core/src/storage/BotStorage.ts).
> Bots built using Bot Builder are designed to be stateless so that they can easily be scaled to run across multiple compute nodes.

**Comment by peterswimm** [comment]
Closed due to inactivity, but Botkit now supports Bot Builder!

https://github.com/howdyai/botkit/blob/master/readme-botframework.md

**Comment by simonfranzen** [comment]
@peterswimm this link is outdated. I am searching for a solution scale our bot on heroku. So a persistent storage would be awesome

**Comment by peterswimm** [comment]
@simonfranzen Updated the link, but nothing has changed in the world of botkit much to support this, but we have plans to support native persistence out of the box in botkit 1.0. In the meantime many users do use scaled Botkit on hosting like heroku and the storage connectors with some effort.
