### ISSUE TITLE
Feature request: message middleware

### ISSUE THREAD

**Issue by indexzero** [howdyai/botkit#331]
> _Really enjoying using this thus far. Thanks for all your hard work!_ 💯 👍 

I've been working on a simple command that turned out to be a bit more complex than I thought. At its core this command is a [Dead Man's Switch](https://en.wikipedia.org/wiki/Dead_man%27s_switch) (aka a _time-delayed_ auto-responder) which means that after it's setup I need to add a `receive` middleware. In doing so I realized how much overhead each `receive` middleware is since it gets **everything.**

Wondering if there is any interest in expanding on the middleware concept and adding support for middlewares on types of messages: `direct_message`, `direct_mention`, `mention` and `ambient`. 

The proposed API would be very similar:

```js
controller.middleware.direct_message.use(fn);
controller.middleware.direct_mention.use(fn);
controller.middleware.mention.use(fn);
controller.middleware.ambient.use(fn);
```

**Comment by anonrig** [comment]
Why add it on a middleware, when you have the old fashioned `.on('EVENT_TYPE', fn)` 🎱

**Comment by anonrig** [comment]
But again you can do the same thing with `.hears` method with giving an appropriate RegEx. So, I'm not really quite sure why Botkit needs a middleware? Can you be more specific. Thanks!

**Comment by peterswimm** [comment]
Closed due to inactivity, would love to see more discussion or review any pull requests!
