### ISSUE TITLE
Telegram support

### ISSUE THREAD

**Issue by matueranet** [howdyai/botkit#334]
It would be awesome if botkit could also support Telegram messenger bots.

**Comment by Now2407** [comment]
I second this! I also need this as well.

**Comment by peterswimm** [comment]
This has been added if you are a [Microsoft Bot Framework  ]https://github.com/howdyai/botkit/blob/master/readme-botframework.md)user.

**Comment by st-fresh** [comment]
@peterswimm  - Got broken link there -- is link updated ? Can't find it

**Comment by marten-cz** [comment]
@st-fresh https://github.com/howdyai/botkit/blob/master/docs/readme-botframework.md
