### ISSUE TITLE
Message.undefined when sending an attachment with a callback

### ISSUE THREAD

**Issue by mattevans-sf** [howdyai/botkit#335]
Using the example from the readme I'm trying to implement the callback for a button. The app is registered as a slackapp so that we can use buttons and the bot is added and replies to regular conversations. However when trying the below controller.hears(['try']... I get:

[Start]  2  Conversation with  U12NX9NUX in D1TQH4ZDH
at Conversation.tick (/app/node_modules/botkit/lib/CoreBot.js:430:93)
at Task.tick (/app/node_modules/botkit/lib/CoreBot.js:618:36)
TypeError: *_Cannot read property 'length' of undefined message.text
*_[Math.floor(Math.random() \* message.text.length)]
/app/node_modules/botkit/lib/CoreBot.js:430

Code is:
`var controller = Botkit.slackbot({
    //json_file_store: './db_slackbutton_bot/',
    }).configureSlackApp(
        {
            clientId: process.env.clientId ,
            clientSecret: process.env.clientSecret ,
            scopes: ['bot','incoming-webhook','team:read','users:read','channels:read','im:read','im:write','groups:read','emoji:read','chat:write:bot'],
            interactive_replies: true,
        }
    );`

controller.hears(['try'], 'direct_message,direct_mention,mention', (bot, message) => {

```
let askSubject = (response, convo) => {
    convo.ask({
        "attachments": [
            {
                "title": "Do you want to proceed?",
                "callback_id": "123",
                "attachment_type": "default",
                "actions": [
                        {
                            "name":"yes",
                            "text": "Yes",
                            "value": "yes",
                            "type": "button"
                        },
                        {
                            "name":"no",
                            "text": "No",
                            "value": "no",
                            "type": "button"
                        }
                    ]
            }
        ]
    },[
        {
            pattern: "yes",
            callback: function(reply, convo) {
                convo.say('FABULOUS!');
                //convo.next();
                // do something awesome here.
            }
        },
        {
            pattern: "no",
            callback: function(reply, convo) {
                convo.say('Too bad');
                //convo.next();
            }
        },
        {   
            default: true,
            callback: function(reply, convo) {
                // do nothing
            }
        }
    ]);
};

bot.startConversation(message, askSubject);
```

});

**Comment by peterswimm** [comment]
Did you ever find an answer to this question?
