### ISSUE TITLE
vulnerable dependencies

### ISSUE THREAD

**Issue by OliPicard** [howdyai/botkit#338]
The ws module needs to be updated to version 1.1.1 after it was discovered that 1.1.0 contained a attack vector that could allow DoS due to excessively large websocket message.

See https://nodesecurity.io/advisories/socketio_dos-due-to-excessively-large-websocket-message

**Comment by OliPicard** [comment]
In addtion minimatch requires an update to 3.0.2 to resolve a possible regex DoS attack vector.

**Comment by anonrig** [comment]
You're right. Can you open a PR for this?

**Comment by OliPicard** [comment]
@anonrig I have see #339

**Comment by anonrig** [comment]
Thank you! Merged.
