### ISSUE TITLE
bot_channel_join event not firing when bot is invited to a channel

### ISSUE THREAD

**Issue by groppe** [howdyai/botkit#347]
I am listening to the `bot_channel_join` event as follows:

```
controller.on('bot_channel_join',
    function(bot, message) {
        console.log(message);

        // reply with excitement
        bot.reply(message, It\'s me!!');
});
```

However, when I invite the bot to a channel the event doesn't fire.

**Comment by davidrussell731** [comment]
I'm having the same issue with this, as well as the user_channel_join event.

**Comment by EloyRedondo** [comment]
Maybe you need to use bot_group_join and user_group_join instead.

**Comment by dipesh-gandhi** [comment]
Same here, tried both user_channel_join and bot_channel_join but they don't fire.

**Comment by jonchurch** [comment]
@dipesh-gandhi Are you using the latest botkit? version 4.2? Events API or RTM?
I am looking into this currently.

**Comment by dipesh-gandhi** [comment]
Yes, it's latest 4.2 version. Events API. I'm using console bot at moment for testing. 

![image](https://cloud.githubusercontent.com/assets/16947975/20637851/871e2c5c-b359-11e6-8fc0-9821691f2ad4.png)

**Comment by jonchurch** [comment]
Events API does not send `bot_id` fields with channel_join or group_join events, which Slackbot.js looks for. I have removed the check for bot_id and added channel_join and group_join as exceptions to the check for events originated by the bot (which are ignored by default).

Here is a [link to the lines I changed](https://github.com/howdyai/botkit/compare/master...jonchurch:issue347fix).

Will submit a PR for this after coming back and looking at that exception again 👍 
Good catch @dipesh-gandhi!

**Comment by dipesh-gandhi** [comment]
@jonchurch Thanks much for looking into this, especially since its around holidays. :)  The fix you propose seems to be specific to Slack? I'm using Console Bot at moment but I tried regardless, and no luck. I'm fairly new to Botkit so you can correct me.. My goal is for Bot to sent initial greeting message from bot in either case when user joins bot / bot joins user. This is regardless of interface slack, sms, console, web chat, etc. I was thinking there would be some events triggered at bot core, an abstraction?

**Comment by jonchurch** [comment]
Hmm the concept of channel joins is slack specific Im fairly sure. I honestly have not used console bot yet, but will test it today. 

So to be clear, you made the changes to Slackbot.js but are still not receiving bot_channel_join events?

**Comment by jonchurch** [comment]
Not a solution, just another option, but when a bot on slack or facebook is first setup (for slack its when the bot is first added to a team, for facebook its when a user clicks get started) an event called create_bot is fired. For slack this would give you the opportunity to send instructions or welcome message to whoever added the bot to the team. 

This is the intended way to greet users on setup. 

But it seems to me you are trying to have the bot simply say hello when it joins a users channel or vice versa.

**Comment by jonchurch** [comment]
@dipesh-gandhi Currently with ConsoleBot you can only test text input and conversations. There is not a way to tigger events such as `bot_channel_join`.

There should be though! I will look into adding something. 

 Be aware, however, that `bot_channel_join` is Slack specific

**Comment by dipesh-gandhi** [comment]
@jonchurch Thanks dude!

**Comment by chrisberthe** [comment]
I am having this issue as well - Botkit version `0.4.3` (not using ConsoleBot).

**Comment by chrisberthe** [comment]
@jonchurch It works as far as `0.2.2`, once I hit `0.4` it stops working.

**Comment by jonchurch** [comment]
@chrisberthe Take a look at #514

**Comment by JimTheMan** [comment]
@jonchurch @benbrown 

Are you sure this was fixed? `bot_channel_join` event is not ever firing for me...

**Comment by Laptopmini** [comment]
@JimTheMan +1, not working here either.
