### ISSUE TITLE
conversations of a user are not deleted when deleting the conversation from facebook

### ISSUE THREAD

**Issue by OmranAbazid** [howdyai/botkit#349]
Hello , 
I am having the following bug in facebook bot:

if i start a conversation with the bot but without finishing it then i delete the conversation from the facebook menu then if i press get started again the old conversation will mixed with the new conversation triggered.
i need to restart the app for the old conversation to be deleted.

Is there a way  for the same user to did finish the conversation to delete all his conversations when he triggers the welcome message (press get started)

**Comment by peterswimm** [comment]
The recent update included a number of facebook updates, please let us know if the problem persists.
