### ISSUE TITLE
RTM api closes automatically after responding to 1 message

### ISSUE THREAD

**Issue by Kishanrajdev047** [howdyai/botkit#351]
After receiving and sending back the response with 'hear's function, RTM api automatically closes and not reconnecting. Due to this, I am not able to send or receive any further message.

Is this an issue? What is the workaround? I do not want to close the connection with slack.

Here is the code i have used,

`controller.hears('.*', 'direct_message', function(bot, message) {
    bot.reply(message, 'hello world');
  });`

**Comment by tdi** [comment]
First of all you should check why it disconnects. Do you have ` debug: true` in:
```javascript
var controller = Botkit.slackbot({
  debug: true
});
```
With this you can see possible problems in the console log.
