### ISSUE TITLE
Not able to add more than 5 interactive buttons in response.

### ISSUE THREAD

**Issue by Kishanrajdev047** [howdyai/botkit#359]
Botkit sends maximum 5 attachment actions in the response. Is there a way to customize this number? According to slack documentation 20 actions can be sent at a time. 

Here is the message format i am sending back to slack in response.

```
{
  'text': "hello world",
  'mrkdwn': true,
  'unfurl_links': true,
  'attachments': [{
      'text': 'helloworld ',
      'callback_id': 'test',
      'attachment_type': 'default',
      'actions': [{
        'text': 'button 1',
        'name': 'button1',
        'value': 'button1',
        'style': 'danger',
        'type': 'button'
      },
      {
        'text': 'button3',
        'name': 'button3',
        'value': 'button3',
        'style': 'danger',
        'type': 'button'
      },
      {
        'text': 'button3',
        'name': 'button3',
        'value': 'button3',
        'style': 'danger3',
        'type': 'button'
      }]
    }]
};
```

**Comment by ChrisWphoto** [comment]
Right now I am using three attachments and they seem to be working 90% of the time. Every once in a while the response won't post to the channel. 

`info: ** API CALL: https://slack.com/api/chat.postMessage` 
Is logged in the console but the attachment never reaches the channel. Are you having this same issue with >5 attachments?

**Comment by Kishanrajdev047** [comment]
Yep. Don't what is the issue. However, in slack message builder, I am able to add more than 5 buttons.

**Comment by ChrisWphoto** [comment]
Have you tried setting debug: true and checking for errors in the call back from the slack api?

**Comment by Kishanrajdev047** [comment]
Looks like the issue is from Slack end. It only allows maximum 5 buttons.

I have tried running it on slack API tester. It doesn't give any error message but ignores actions buttons which come after count 5.

Closing the issue.

**Comment by peterswimm** [comment]
This is a API limit iirc. If someone from slack chimes in to the contrary we can create a bug issue to fix.

**Comment by mrooseboom** [comment]
use multiple attachments and you can set 5 buttons per attachment
