### ISSUE TITLE
Testing Botkit Blocks

### ISSUE THREAD

**Issue by ghostsquad** [howdyai/botkit#36]
I didn't see any examples or documentation on how to write tests for Botkit blocks. Please add!

**Comment by RafaelCosman** [comment]
@ghostsquad We don't have any system for testing yet -- would you be interested in submitting a PR with one?

**Comment by ghostsquad** [comment]
How did you test Botkit? manual testing?

**Comment by anonrig** [comment]
You can mock the Slacks API responses and make Botkit think that it is connecting with Slack @ghostsquad

**Comment by RafaelCosman** [comment]
@ghostsquad we don't yet have a solid testing system for Botkit and would love help implementing one.

**Comment by karlbright** [comment]
It should be noted that storage options are now in separate repos/modules and have tests using stubs etc against them.

**Comment by aberope** [comment]
I think the best way is to use a web-token and code some command issuing layer over some like `slack-cli` slack client for command line. We can catch answers from bot, we can speak in different ambients, and also it's not need to fake each crucial function nor objects. I just was reading a test for an hour, that is using near to 4 libraries, and I had to do a lot of effort to understand just a % of the whole testing scripts. What do you think?

**Comment by nikbora** [comment]
Hey guys, I too am curious as to what people are doing to automatically test their bot/conversation logic, other than connecting it to Slack and manually interacting with it. 

Does anyone have example code with a mocked up Slack API or a mocked up conversation object used in automated tests?

**Comment by aberope** [comment]
I've got it! I am using nightmare, it works like a charm. But need coding.

**Comment by amplicity** [comment]
My team has created a mock for mocking botkit conversations. We have been using that for automated testing with mocha. We're running some checks to see how fit it would be for botkit as a whole..will cycle back and make a pull request if so.

**Comment by nikbora** [comment]
@amplicity that sounds cool, looking forward to it. Feel free to share your process even if you don't think it belongs inside of botkit, perhaps via another repo or a blog post.

**Comment by amplicity** [comment]
@nikbora I uploaded this and some examples here. hope this is helpful!

https://github.com/amplicity/BotMock

**Comment by peterswimm** [comment]
moving discussion over here https://github.com/howdyai/botkit/issues/850
