### ISSUE TITLE
Need telegram & other bot support 

### ISSUE THREAD

**Issue by Now2407** [howdyai/botkit#362]
is there going to be support for other platforms in the future? Kick, what's app, telegram etc.? This would be awesome! Is this coming soon?

**Comment by peterswimm** [comment]
There are two major ways that platform support happens typically:

- a developer (or the platform) submit a PR
- the platform reaches out to Howdy to work with us to make it happen!

I would suggest you join dev4slack to see if you can drum up interest there, and also send a feature request to these platforms that you'd love to see Botkit integration for their tools, it helps!

**Comment by peterswimm** [comment]
Telegram support has been added via [Microsoft Build Builder](https://github.com/howdyai/botkit/blob/master/readme-botframework.md)

**Comment by peterswimm** [comment]
@st-fresh here is an updated link https://github.com/howdyai/botkit/blob/master/docs/readme-botframework.md
