### ISSUE TITLE
silentRepeat() ends Conversation

### ISSUE THREAD

**Issue by domschiener** [howdyai/botkit#365]
Currently trying to use `convo.silentRepeat()` but it is not behaving as expected. Instead of simply waiting for new input from the user, it ends the conversation altogether. I have tried comparing it with `convo.repeat()` which works just fine (repeats the question and waits for a new response from the user). 

This seems to be a bug. 

**Botkit Version**: 0.2.2 
**OS**: Mac OSX 10.11.6

```
info: [Start]  0  Task for  U1MBJHLQ1 in D1U5QGDGV
info: >   [Start]  0  Conversation with  U1MBJHLQ1 in D1U5QGDGV
info: ** API CALL: https://slack.com/api/im.open
info: >   [Start]  1  Conversation with  U1MBJHLQ1 in D1U5QGDGV
info: >   [End]  0  Conversation with  U1MBJHLQ1 in D1U5QGDGV

SILENT REPEATING

debug: No handler for conversationEnded
debug: No handler for end
info: >   [End]  1  Conversation with  U1MBJHLQ1 in D1U5QGDGV
info: [End]  0  Task for  U1MBJHLQ1 in D1U5QGDGV

```

**Comment by domschiener** [comment]
https://github.com/howdyai/botkit/issues/318 seems to be having similar issues.

**Comment by peterswimm** [comment]
Let's continue the discussion in https://github.com/howdyai/botkit/issues/365

**Comment by itamarro** [comment]
@peterswimm Did you mean the discussion is continued in #318 ? Is @mostr's reply there (from Sep 26) the recommended way of working around this?

**Comment by peterswimm** [comment]
@itamarro just merging two topics into one for more visibility! Did you try the suggested workaround?

**Comment by itamarro** [comment]
Got it :) Yes, I did apply the workaround and it works for me. Just wanted
to be cautious and see if it's indeed the recommended way.

**Comment by JimTheMan** [comment]
hi, what's the deal with this? Can we please make silentRepeat() work in an expected way?
