### ISSUE TITLE
webhooks failing on facebook messenger heroku hosted app

### ISSUE THREAD

**Issue by Now2407** [howdyai/botkit#369]
hello, my webhooks seem to be failing. facebook is sending me alerts saying my webhooks are failing when using this framework. i am hosting node js on heroku. could someone point me in the right direction as far as getting it working? thanks!

<img width="779" alt="screen shot 2016-08-13 at 10 09 35 pm" src="https://cloud.githubusercontent.com/assets/6015402/17647403/b0bce930-61a2-11e6-843d-543a935ee7a2.png">

**Comment by yannderyckedotcom** [comment]
the is a problem with your app on heroku, is crashed.
you have to restart dynos and solve your erros
fb try to reach your app but can t

**Comment by peterswimm** [comment]
Discussion continued in https://github.com/howdyai/botkit/issues/435
