### ISSUE TITLE
Redis storage

### ISSUE THREAD

**Issue by guillaumepotier** [howdyai/botkit#37]
Hi,

I wrote a simple Redis storage using redis `hashes` storage to handle data. Are you interested by it? Do you want me to make a PR here and add it somewhere in the repo, or create a dedicated repo and link it in the README?

Best

**Comment by RafaelCosman** [comment]
So far people (including me) have been submitting PRs for these, but it's not clear if that's what the managers of the repo want. If they accept our PRs today then we'll know the answer.

**Comment by benbrown** [comment]
Yes! Please submit a pull request!! That is a great feature to have!

**Comment by guillaumepotier** [comment]
Okay @benbrown, I just submitted my PR in #38, feel free to comment. I [factorized my code](https://github.com/howdyai/botkit/pull/38/files#diff-efceb781e59d7290103716d0c7b77fa3R21) to handle the API that do not change much bw `teams`, `users` and `channels` and used a code that could be simpler with more lines. If not enough readable I could develop. What I particularly like with this implementation is that very easily [you could add sets](https://github.com/howdyai/botkit/pull/38/files#diff-efceb781e59d7290103716d0c7b77fa3R18), I use that to store some of my application business (tokens or sessions to be able to call my API).

**Comment by RafaelCosman** [comment]
@guillaumepotier I left a note on your PR about passing ```storage_tests.js``` before we merge it.

**Comment by guillaumepotier** [comment]
Since my second pull request have been merged, I think we could close this issue.

Best
