### ISSUE TITLE
Welcome message

### ISSUE THREAD

**Issue by yannderyckedotcom** [howdyai/botkit#372]
Is there a way to use the Get Started Button: https://developers.facebook.com/docs/messenger-platform/thread-settings/get-started-button ?
I don t find it in the module facebook

**Comment by houjunchen** [comment]
It's a one-time setting, just like Facebook app setup. You can send the POST request in your own way. In my case, I wrote another `.js` file to control the **Get Started Button** and **Persistent Menu** which is executed only once not every time the server started.

**Comment by yannderyckedotcom** [comment]
Yes, this is what i Finaly do. It will be great if it was integreted in the module Botkit ;-)

**Comment by agamrafaeli** [comment]
Put in PR #470 to resolve this issue

**Comment by peterswimm** [comment]
Fixed with above!
