### ISSUE TITLE
Update or replace dependencies

### ISSUE THREAD

**Issue by nikolay** [howdyai/botkit#373]
Check the report here: https://snyk.io/test/npm/botkit

On the other hand, `back` has obsoleted engine requirements, making configurations with `engine-strict = true` fail to install due to that baggage.

**Comment by nikolay** [comment]
I've filed an issue with `back` as well: https://github.com/jcrugzz/back/issues/5

**Comment by anonrig** [comment]
Current issues inside the report are all localtunnel related, and it shouldn't be used in production. Therefore, not urgent, but necessary update on localtunnel is required.

**Comment by nikolay** [comment]
@anonrig Filed an issue with them as well: https://github.com/localtunnel/localtunnel/issues/142

**Comment by peterswimm** [comment]
NPM has been updated, please let us know if you see any issues with that still.

**Comment by tgabi333** [comment]
+1
