### ISSUE TITLE
Why the npm version is different?

### ISSUE THREAD

**Issue by daver182** [howdyai/botkit#375]
Why the npm version has different things if it's the same version that the repo? For example the Facebook.js file, in the npm version, it doesn't handle quick replies or sticker. The package.json version is the same but the files are different, how can I get the last updates?

**Comment by webtaculars** [comment]
I don't know the actual answer to this question but I found a way to handle quick replies. In package.json,  copy this ( "botkit": "git+https://git@github.com/howdyai/botkit.git" ) in dependencies and run npm install. Quick replies will work with this.

**Comment by daver182** [comment]
@webtaculars thanks for the answer, it works, I hope they fix the difference between the two sources, is confusing

**Comment by houjunchen** [comment]
You can check the [release tab](https://github.com/howdyai/botkit/releases) on GitHub. The latest release is 0.2.2 which is the same as the version on npm. How I solve this problem is use

```
npm install howdyai/botkit --save
```

to install the latest source.

The better way to solve this is releasing next version by the admin.

**Comment by anonrig** [comment]
@benbrown We should totally need a bump in npm 👍

**Comment by peterswimm** [comment]
@anonrig our plans are to bump the NPM version up when we push the next point release on botkit.

**Comment by peterswimm** [comment]
This has been fixed!
