### ISSUE TITLE
User id retrieval

### ISSUE THREAD

**Issue by jbjohnson86** [howdyai/botkit#379]
Is there a convenient way to get a slack user's id currently conversing with the robot to do some validation? I tried using user.id and it failed.

**Comment by webtaculars** [comment]
Are you asking about facebook message sender id? 
If yes, then sender id = message.user. If not then please specify it clearly.

**Comment by jbjohnson86** [comment]
sorry. I specifically mean the slack user id. I'm wondering is there a way to get the id of that user?

**Comment by jbjohnson86** [comment]
for example, if I was manipulated a controller.storage.users.get call from slack_bot.js like so:

`controller.storage.users.get(message.user, function(err, user) {
        client.get('api/channels.info?...',
                function(err, res, body) {
                    var found = body.channel.members.indexOf(user.id);
                    if (found >-1)
                        //some code of user id found
                });
    });`

user.id doesn't work, but is there some other call I could use? I assumed user.id would work since user.name returns the user name of the account that is talking to the bot.

**Comment by jbjohnson86** [comment]
figured out that for a slack message, message.user is also the user id
