### ISSUE TITLE
Writing tests for botkit

### ISSUE THREAD

**Issue by amplicity** [howdyai/botkit#380]
My team has created a mocking solution to test botkit [here](https://github.com/amplicity/BotMock). Works great for our fairly complex project.

Hope this helps some people.

**Comment by peterswimm** [comment]
Hey this is great! You should share this on dev4slack:
http://dev4slack.xoxco.com

We are trying to keep the github clean to handle actual questions and issues, but I'll leave this up for a week before closing.

**Comment by amplicity** [comment]
Sure thing! Sorry about that. Wasn't share where to post.

**Comment by lucasgreene** [comment]
@amplicity This is awesome thank you!
