### ISSUE TITLE
DM each member of a channel?

### ISSUE THREAD

**Issue by jbjohnson86** [howdyai/botkit#381]
I was wondering if there is a way to DM everyone in a channel? I want to implement something that does that as part of a reaction to a slash command.

**Comment by deubaka** [comment]
Well, you can start by requesting the Slack API, `https://slack.com/api/channels.info` specifically to get the members, and from there, loop and `bot.startPrivateConversation` each one of the members.

**Comment by jbjohnson86** [comment]
how would that startPrivateConversation call go? I only see examples where I pass the message object.

**Comment by deubaka** [comment]
Okay, it would go something like this, with a setup using slash commands (refer [here](https://github.com/howdyai/botkit/blob/master/examples/slackbutton_slashcommand.js)).
```
controller.on('slash_command', function (bot, message) {
    bot.api.channel.info({
        channel: 'C1928309' // Specific channel you refer
    }, function (err, results) {
        if (results.ok && results.ok === true) {
            var members = results.members;

            for (var index = 0; index < members.length; index++) {
                var member = members[index];

                bot.startPrivateConversation({
                    user: member
                }, function (err, convo) {
                    if (!err && convo) {
                        convo.say('Hello there! I messaged you because you where in the channel #general');
                    }
                });
            }
        }
    });
});
```

Hopefully you get the idea. What you'll need to do is where to get the channel code (C######), which you can get when you receive a message and others.

**Comment by PanMan** [comment]
Watch out, if doing this, that you'll quickly hit the rate limit of sending ~ 1 msg/second.

**Comment by deubaka** [comment]
@PanMan Good one! Forgot about that limit writing the sample code. 😄 

@jbjohnson86 Add a delay or queue between send would be great to workaround the limit.

**Comment by anonrig** [comment]
@PanMan Not if you're queuing the messages :)

**Comment by PanMan** [comment]
@anonrig offcourse, but that isn't included in the sample code above, nor in Botkit itself, right? It's an open issue: https://github.com/howdyai/botkit/issues/69
