### ISSUE TITLE
Middleware message.intent doesn't seem to work outside of DM

### ISSUE THREAD

**Issue by DigitalKrony** [howdyai/botkit#385]
I based the code off of the examples written within the repo, but when leveraging the middleware system to listen to message intent, it only seems to work when in a DM conversation with the BOT but not in a group chat or channel. Any ideas?

**Comment by peterswimm** [comment]
Do you have any example code or error logs posted anywhere?

**Comment by peterswimm** [comment]
Closing for now, please reopen if you collect some additional information
