### ISSUE TITLE
No handler for conversationStarted

### ISSUE THREAD

**Issue by karthik-mudiam** [howdyai/botkit#394]
I am using WIT with Howdy. Trying to test a simple 'greeting' intent with botkit and the botkit fails with 'No handler for conversationStarted' message at 'botkit/lib/CoreBot.js:808 worker.send(message, cb);'

I am able to get the intent right from WIT and what I want to do is to ask the user his/her name.

controller.hears([greetingEntityName], 'message_received', wit.hears, function (bot, message) {
controller.storage.users.get(message.user, function(err, user) {
if (user && user.name) {
bot.reply(message, 'Hi ' + user.name + '. Welcome!');
} else {
bot.startConversation(message, function(err, convo) {
if(!err) { 
convo.say('Hi There!');

convo.ask('What is your name?', function(response, convo){

console.log(response);

convo.next();
}, {'key':'nickname'});

                convo.on('end', function(convo) {
                    if (convo.status == 'completed') {
                        bot.reply(message, 'OK');
                    } else {
                        bot.reply(message, 'Not OK');
                    }
                }); 
            }                    
        });
    }
});
});

**Comment by Iodine-** [comment]
@karthik-mudiam can you elaborate on why you closed this issue?  did you find a solution, or an error in your implementation?
