### ISSUE TITLE
botkit for slack needs to restart after after a bot is removed and then readded to a team

### ISSUE THREAD

**Issue by Intellogo** [howdyai/botkit#395]
1. install a bot on a slack team
2. uninstall the bot from the team
3. reinstall the bot to the same team 

outcome: the bot does not respond to anything you type
4. restart the server

outcome: the bot begins to respond

expected behavior: the bot responds after it has been uninstalled and reinstalled without requiring a restart of the server.

**Comment by sundeepgupta** [comment]
What do you mean by "bot does not respond"?  You need to manually start the RTM session on an install. 

Are you listening for the `create_team` and `update_team` events?

**Comment by Intellogo** [comment]
i start the rtm session and the bot does start a convo - I get the bot's messages but when I try to reply the bot does nothing. if I restart the server then the bot starts to act normally.

**Comment by anonrig** [comment]
You can listen for https://api.slack.com/events/bot_changed event.

**Comment by Intellogo** [comment]
many thanks anonrig. i think we can close this as it is not an issue with botkit thank you sundeepgupta.
