### ISSUE TITLE
bot.identity.name

### ISSUE THREAD

**Issue by Intellogo** [howdyai/botkit#399]
the bot passed into the interactive_message event controller does not appear to contain the bot.identity.name attribute... is this normal and if so, how can I get the name?

**Comment by lucasgreene** [comment]
@Intellogo I can confirm that this is the same as on my computer. Not sure exactly why but basically on interactive message callback a new bot is spawned, so in general it might be missing some things (particularly if you attach custom stuff to the bot when the team is first connected like i do). I suspect that when the first bot is created it gets the identity name attached but for the interactive message callback it doesn't happen. Basically the bot on callback is not the same bot that normally "hears", so you have to be careful with what you do with it. You can see this in SlackBot.js: 

                        var bot = slack_botkit.spawn(team);

                        bot.team_info = team;
                        bot.res = res;

                        slack_botkit.trigger('interactive_message_callback', [bot, message]);

                        if (configuration.interactive_replies) {
                            message.type = 'message';
                            slack_botkit.receiveMessage(bot, message);
                        }

**Comment by peterswimm** [comment]
Closed as answered
