### ISSUE TITLE
Lookup userID for startPrivateConversation()

### ISSUE THREAD

**Issue by erikhallander** [howdyai/botkit#401]
Through a slash command I'm getting usernames fed to me in string form.. ie "@username". Since I need a userID to do a startPrivateConversation, how can I possibly look this up from username only?

Note that the person submitting the slash command will not be the same person I want to initiate a conversation with (this is a submission bot, notifying the person that was submitted).

thankful for help.

TA

**Comment by erikhallander** [comment]
Kinda solved it. Feels a bit clunky, but w/e.

First you have to get the list of all users, through the API get @

`unirest.get("https://slack.com/api/users.list")`

Then basically something like this;
`var user_info = user_list.filter(function(f_user){ return f_user.name == trimmed_username })[0]`

returns the entire user object of the person matching the user name.

Getting the entire team user list seems like a poor way of doing it, but in case someone else is stuck, that's how I got around it..

**Comment by jonchurch** [comment]
You can use `bot.api.users.list()` to get that user list, but I'd say the answer is to supply the id along with the usernames if possible.

Slack web API calls covered [here](https://github.com/jonchurch/botkit/blob/telegramBot/readme-slack.md#using-the-slack-web-api)
