### ISSUE TITLE
Can middleware be an array ?

### ISSUE THREAD

**Issue by santiq** [howdyai/botkit#405]
I have several middlewares functions, like `isWorkingDay`and `isOn`  and I want to use them in this way 

```
controller.hears(['hi'], ['direct_message'], [isWorkingDay, isOn], function(bot,message) {
    bot.reply(message, 'hello there!');
  });
```

I searched through the code, and I guess it could be done [HERE](https://github.com/howdyai/botkit/blob/master/lib/CoreBot.js#L729-L760)

**Comment by benbrown** [comment]
No, this currently accepts a single function, and only one that is configured to work as a `hears` middleware.
