### ISSUE TITLE
Mechanism for communicating with bot outside of service?

### ISSUE THREAD

**Issue by derrickpelletier** [howdyai/botkit#406]
Is there a mechanism for communicating with a bot outside of the service it is spawned to?

Perhaps I'm missing something obvious, but it doesn't seem like there is a way...

Two things I'd like to be able to do, which are more or less the same.

First, I'd like to be able to test bot replies to certain messages and their variations in an automated capacity. The service wouldn't be necessary here, i'd just like to tell a bot something, and receive its reply.

Second, I'd like to be able to simulate communications with a bot manually, without needing to be connected to the services. Either for offline development, or for live-testing modifications to a bot's "hear" patterns or responses via external interface, without the user needing to be switching back to a service.

Perhaps what i'm trying to describe is a `Controller` that is service-less? Hopefully this is already available and I'm just missing it!

**Comment by jonchurch** [comment]
Do you mean, talk to a slack bot via command line or some sort of other admin like interface? Perhaps web based or w/e but a channel other than slack?

Is that close to what you are looking for?

**Comment by derrickpelletier** [comment]
Sorry missed this.

No, I don't necessarily mean for it to talk to a _Slack_ bot. I'm meaning a bot that is not tied to a service, that can be communicated with directly, likely just via an internal api.

Then say for tests i could just spawn this standalone bot, and load up the same `hears()` on it. Then maybe directly talk to it via some method like `bot.heard('some message')` and test the responses.

Or, say if i theoretically had some UI where an admin could modify certain bot behaviours, they could use this standalone bot to test communication in this isolated UI.

Not sure if I'm being particularly clear. I think the core idea is to have a bot controller that behaves more or less identically (maybe without the socket/listening) but can be interacted with directly outside of a service.

**Comment by benbrown** [comment]
Take a look at the `dev/webchannel` branch for an answer to this question.

It exposes a socket- and  webhook-based mechanisms for communicating directly with Botkit.
