### ISSUE TITLE
Add support for Internationalization/Localization

### ISSUE THREAD

**Issue by rodrigoalviani** [howdyai/botkit#41]

**Comment by RafaelCosman** [comment]
@rodrigoalviani, great point. This is important.

**Comment by peterswimm** [comment]
Created a new dev4slack channel, #botkit-localization to discuss this Feature Request. If you are interested, please join the conversation!

**Comment by znat** [comment]
For now I am doing the following (with `i18n-node`):

At bot initialization:

```js
var i18n = require('i18n');
i18n.configure({...});
var bot = controller.spawn({...});
bot.i18n = i18n;
```
I wrote a [middleware](https://github.com/mrbot-ai/botkit-middleware-fbuser) to add facebook messenger's `user_profile` to the message object:
```js
{ text: 'ce soir',
  user: '123456789',
  channel: '/#QpmoHYNhZlvOzUXiAAAB', // socket id 
  timestamp: 1484084415264,
  user_profile: 
   { 
     first_name: 'Nathan',
     last_name: 'Zylbersztejn',
     locale: 'fr_CA',
     profile_pic: '<url>',
     timezone: -5,
     gender: 'male',
     is_payment_enabled: true,
     id: '123456789' },
  entities: {...} 
}
```

In the conversation:
```js
 bot.createConversation(message, function (err, convo) {
        convo.setVar("user_profile",message.user_profile);
        convo.addMessage({
            text: bot.i18n.__({phrase:'reminder_confirmation',locale:convo.vars.user_profile.locale}),
            action: 'completed'
        },'set_reminder');
       // rest of convo...
}
```

It would make sense to have the user profile accessible in the convo (which is also semantically defined by the people who run it). This would avoid setting the variable and we could find a way to make i18n aware of it to avoid passing the locale at every translation.
