### ISSUE TITLE
Identify the incoming message source from bot object

### ISSUE THREAD

**Issue by aarora91** [howdyai/botkit#414]
I have multiple bots(from different social channels like Facebook and Slack) listening on a common express server. In one of the functions, I am passing the bot object which is something like:

1. Create a bot:
``var Slack = require('./slack_bot.js');
    var bot = Slack.bot;
``
(**Note:** bot can also be require('./facebook_bot.js').bot)

2. Call a function and pass the _bot_ object:
``
someFunc(bot)
``

At runtime, the above function `someFunc` may get a bot object from any source, could be Fb or Slack. Is there a property of the bot object I can use to identify the source?

**Comment by dmccrevan** [comment]
Hey @aarora91 

I don't think there is a property in the bot object that is universal across the facebook bot object, slack bot object, and twilio bot object that will all tell you what service it is talking to....in slack.api there is a property that contains a URL to slack, but I think the best bet would to set this property yourself in the object you create.

`var Slack = require('./slack_bot.js'); var bot = Slack.bot; bot.socialService = 'slack'`

**Comment by aarora91** [comment]
Thanks @dmccrevan this worked beautifully!

**Comment by peterswimm** [comment]
Issue seems resolved! If you have any follow ups feel free to reopen!
