### ISSUE TITLE
Is it possible to start an instant message with multiple participants?

### ISSUE THREAD

**Issue by stevebakh** [howdyai/botkit#415]
Hi,

I'm trying to start an IM with several participants (including my bot). I'm not sure of the best way to do this, as the API to start an IM expects a single user ID. I have considered simply starting a 1 to 1 IM and then inviting the other users, but I'm not sure how to _send_ slash commands from the bot, as the text is escaped in the request and the slash is simply printed in the message that appears in the conversation.

Any ideas how to progress with this?

Thanks!

**Comment by jonchurch** [comment]
Are you trying to implement this on slack? Putting the bot in a channel with the participants, or private group, sounds like a better way to do this to me for slack. That or let each participant interact with the bot through DM's and collect everyone's answers through individual conversations.

Facebook does not really support this right now, but there is an example [here](https://www.youtube.com/watch?v=zFO1cRr5-qY) of someone creating a very simple "party line" where all messages sent to the bot were sent to everyone else who had added it.
