### ISSUE TITLE
Add timeout feature for conversations and documentations

### ISSUE THREAD

**Issue by lucasgreene** [howdyai/botkit#419]
Opened a new issue, referencing https://github.com/howdyai/botkit/issues/288 and https://github.com/howdyai/botkit/issues/377 . Having a timeout feature for conversations, where if the user hasn't responded in a certain amount of time the conversation is ended, is super useful for a number of scenarios. It is possible to do this by setting the variable convo.task.timeLimit , but you can only figure this out by looking through the botkit issues or source code. I would love to see this documented/supported somewhere so other people can figure this out without all the digging. I can make a PR if that will help!

**Comment by lucasgreene** [comment]
Seems like it was added as convo.setTimeout:
        // how long should the bot wait while a user answers?
        this.setTimeout = function(timeout) {
            this.task.timeLimit = timeout;
        };

Thanks!

**Comment by yannderyckedotcom** [comment]
have you find a solution ?
I want after X seconds do a convo.ask() but the convo is completed before the setTimout..
Thankx
