### ISSUE TITLE
Slack: bot in multiple teams and bot connection is dropped only from one team

### ISSUE THREAD

**Issue by sl800** [howdyai/botkit#420]
Using botkit in our Slack app bot that has multiple installations across many Slack teams. About once every week or two, our bot in one team drops connection (no green light in Slack UI), but we don't receive any notifications/errors on our server-side. We correctly handle the slack migration event as we have restarted once due to a migration, but we never receive events or any unique log messages when our bot's connection is dropped from a single team.

Any ideas?

Thanks

**Comment by MiroValchev** [comment]
I have this issue too - my bot keeps disconnecting from teams for no apparent reason and I get no notifications about it :(

**Comment by benbrown** [comment]
Bots using the RTM websocket connection have to watch for and handle disconnects. These are EXPECTED and should be addressed in your code.
