### ISSUE TITLE
Documentation for creating new bot integrations

### ISSUE THREAD

**Issue by facultymatt** [howdyai/botkit#421]
It would be useful for developers looking to create new integrations (ex Whats app, etc.) if the API for creating  a new bot was defined and documented. Forgive me if this exists but I have not found it. If it does not exist, what is the timeline for creating it?

**Comment by facultymatt** [comment]
Related: 

https://github.com/howdyai/botkit/issues/362
https://github.com/howdyai/botkit/issues/223

**Comment by jonchurch** [comment]
Hey @facultymatt  I've had success by taking the facebookBot.js file as a reference, and replacing the fields facebook expects with whatever platform I am implementing's expected fields. With services that send and receieve via webhook, the botktit stuff is simply a wrapper around making those requests and receiving/formatting incoming messages. I then add any extra methods I want to add, like telegram's `editMessageText()` method, to the bot object created for that platform. There is some interesting stuff exposing the Twilio API via bot.api, but I honestly haven't needed that level of api access for most platforms.

Each platform has it's own set of extra methods or events you can implement. Triggering different events (like `'message_recieved'`, `facebook_postback` etc) can be implemented by looking for specific fields on the incoming message from the platform. E.g. if a `postback:` field is present, format the message recieved and trigger an event. 

What platform are you looking to implement?

**Comment by peterswimm** [comment]
Our long term goal is to better document this, stay tuned!
