### ISSUE TITLE
Is there a way for the bot to initiate a `conversation`?

### ISSUE THREAD

**Issue by sundeepgupta** [howdyai/botkit#422]
I see there's a way to initiate a `say`:  https://github.com/sundeepgupta/botkit#botsay

Is there a way to do something similar for a `conversation` or an `ask`?

**Comment by jonchurch** [comment]
Is `startConversation()` or `startPrivateConversation()` not what you are looking for?
In the docs, [startConversation](https://github.com/sundeepgupta/botkit#botstartconversation)

**Comment by sundeepgupta** [comment]
Excellent, thanks @jonchurch

**Comment by ewdave** [comment]
@jonchurch Really grateful for this.... Finally, I got this feature to work for me. Thanks again!

**Comment by ewdave** [comment]
This was what actually worked for me.

I had to initiate Slack's web API with `bot.api.im.open` -- this will allow you know the user channelID before hand.

Hear:

```
new CronJob('0 */1 * * * *', () => {
	bot.api.im.open({
		user: 'U2WQ0L9FW'
	}, (err, res) => {
		if (err) {
			bot.botkit.log('Failed to open IM with user', err)
		}
		console.log(res);
		bot.startConversation({
			user: 'U2WQ0L9FW',
			channel: res.channel.id,
			text: 'WOWZA... 1....2'
		}, (err, convo) => {
			convo.say('This is the shit')
		});
	})
}, null, true, 'Africa/Lagos')
```

**Comment by Billydubb** [comment]
I can confirm @ewdave's answer. If I try it the way @jonchurch suggested, namely without bot.api.im.open, it will only post the first message, and no further messages or questions after that. Can anyone else confirm?

**Comment by nicholasgubbins** [comment]
hey @ewdave did you get this to work? I'm getting a 'not_authed' error when i use bot.api.im.open...
