### ISSUE TITLE
Slack's "file_shared" event not triggered in channels

### ISSUE THREAD

**Issue by christian-bick** [howdyai/botkit#428]
I'm using botkit 0.2.2 with Slack via the RTM-API and want to my bot to react to files being uploaded/shared by users in groups and channels. 

The following code **works fine** for listening to "file_shared" events **in groups**:

``` Javascript
controller.on('file_shared', (bot, file) => {
  console.log(file.file_id);
});
```

But when a file is uploaded/shared **in a channel** then **the event is not being triggered**.

According to the Slack API, the "file_shared" event is the one that should be triggered in my use case. I also tried other event types like "file_created" and "file_public" to make sure that I don't misinterpret anything but as expected that didn't work as well.

I'm running botkit on node 6.5 within in a multi-team setup managed by [beepboop-botkit](https://github.com/BeepBoopHQ/beepboop-botkit).

**Comment by xuanvinh2005** [comment]
I have the same problem with latest master, it even doesn't not work in groups

**Comment by jonchurch** [comment]
Try listening to `file_share` (exactly the same minus the letter d). They are two different types of events, and the slack docs does not easily differentiate between the two. I asked their support about it last week, they said they would update the docs perhaps to make it more clear. 

I ran into these twin events while testing my fork of the Events API, and was confused for a while.

`file_share` I think is the message that gets sent into a chat, the visible one. Two things happen when files are shared, an event is fired and a message is sent into the destination chat. It seems right now it is more reliable to listen for the `file_share` event (at least in my limited testing).

Oddly enough, the `file_share` json data contains waaaay more metadata than a `file_shared` even. The `file_shared` event only has the file_id to be used with the slack file API to lookup the associated metadata and url.

**Comment by peterswimm** [comment]
@christian-bick Did it fix your issue?

**Comment by xuanvinh2005** [comment]
I fixed my issue, 

Thanks

**Comment by peterswimm** [comment]
Closing as resolved
