### ISSUE TITLE
Ability to request different set of auth scopes in Slack

### ISSUE THREAD

**Issue by sundeepgupta** [howdyai/botkit#429]
The use case is that scopes required for the very first user (the user who installs the app into their Slack team), can be more than for the subsequent users. Subsequent users should be able to auth for only the permissions at a user level. 

For example, the first user could have team level permissions like `bot` and `commands`. Subsequent users wouldn't need to auth for those and see them on the Slack OAuth permissions view.

**Comment by benbrown** [comment]
You can achieve this by creating your own oauth endpoints.

I'd suggest taking a look at the `botkit-starter-slack` project, which exposes its own oauth endpoint.
