### ISSUE TITLE
Initiating a conversation based on bot object received from Interactive Message

### ISSUE THREAD

**Issue by OmarSultan85** [howdyai/botkit#430]
I am trying to initiate a conversation after receiving a button press from an interactive message, i use the bot.startConverstaion() using the bot received from the interactive_message_reply. However, I keep getting 

TypeError: Cannot read property 'send' of undefined

coming from this line of code in CoreBot.js

   worker.say = function(message, cb) {
            botkit.middleware.send.run(worker, message, function(err, worker, message) {
                worker.send(message, cb);
            });
        };

**Comment by lucasgreene** [comment]
@OmarSultan85 would be great if we could see the code in question. Specifically the 
on.('interactive_message_reply', function(...........

**Comment by lucasgreene** [comment]
@OmarSultan85 Actually i think you have your event wrong. It should be 'interactive_message_callback' not 'interactive_message_reply'

**Comment by OmarSultan85** [comment]
so this is the event in my server.js file

```
controller.on('interactive_message_callback', function (bot, message) {

    console.log(message);
    slackHandler.routeMessageInteractive(message, bot, message.actions[0].name)

});
```

The error appears when I generate the Conversation using the bot received from this function. However when I define a bot as 

```
global.bot = controller.spawn({
    token: process.env.slackToken
}).startRTM();
```
And use that bot to start the conversation on  a private channel it works fine.

**Comment by dannyfreed** [comment]
Any update on this? It's happening to me also.

**Comment by mgwalker** [comment]
Seeing the same.  I _suspect_ it's because the webhook handler is actually spawning a new bot object: https://github.com/howdyai/botkit/blob/master/lib/SlackBot.js#L172
