### ISSUE TITLE
Facebook Notification Settings (Regular Push, Silent Push, Silent)

### ISSUE THREAD

**Issue by skurilyak** [howdyai/botkit#432]
Here's an idea - implement **Regular Push**, **Silent Push**, and **Silent** Facebook notifications
1. _Regular Push_ notification will make a sound and display a phone notification. Use it for important messages.
2. _Silent Push_ notification will display a phone notification without sound. Use it for regular messages that don't require immediate action.
3. _Silent_ broadcast will not display any notification. Use it for silently sending content updates.

Inspiration: [ManyChat Facebook Bot](http://manychat.com)

**Comment by agamrafaeli** [comment]
Referencing how the specific type of notification can be set upon request for reference:
https://developers.facebook.com/docs/messenger-platform/send-api-reference#request

**Comment by agamrafaeli** [comment]
Put in PR #472 to resolve this

**Comment by peterswimm** [comment]
closed as merged

**Comment by skurilyak** [comment]
Please update README to reflect these changes to Facebook notifications

**Comment by peterswimm** [comment]
@agamrafaeli Would you like the honors?

**Comment by agamrafaeli** [comment]
https://github.com/howdyai/botkit/pull/501

**Comment by benbrown** [comment]
Thanks for handling that @agamrafaeli!

**Comment by agamrafaeli** [comment]
@benbrown Yup. :)

**Comment by lonche** [comment]
What about C# SDK ? Is there any example or implementation of this ?

**Comment by peterswimm** [comment]
@lonche we are going to be focus on Botkit flavored implementations and examples over here :)

**Comment by shervine** [comment]
@slavakurilyak So interesting to read this and see its from you! Was looking into this just now 😄
