### ISSUE TITLE
Question: How to trigger the `convo.ask` callback only if the user mentions the bot

### ISSUE THREAD

**Issue by ljfranklin** [howdyai/botkit#436]
By default, the `ask` callback is triggered the next time the target user enters any message. I'd like to only trigger this callback if the target user's reply mentions the bot.

Desired behavior:

```
bot: @user how are you?
user: @bot great!
bot: @user you said "great!"

bot: @user how are you?
user: talking to someone else
# no response from bot
...
user: @bot doing fine now!
bot: @user you said "doing fine now!"
```

At a glance, I didn't see any properties in the `response` or `convo` that indicated whether the response included a mention or not. Thanks!

**Comment by lucasgreene** [comment]
@ljfranklin try convo.source_messsage. It should have an event property which will be direct_message, direct_mention, ect.

**Comment by EloyRedondo** [comment]
I think is not possible so the ask callback will be triggered always BUT... you can check the response in the callback function and if this response don't start with @bot use convo.silentRepeat(), you know?
Try this:
´´´
convo.ask('how are you', function(response, convo){
    if("CHECK THE response.text AS YOU WANT"){
        convo.next();
    }else{
        convo.silentRepeat()
        convo.next();
    }
});
´´´

**Comment by peterswimm** [comment]
Closed as answered

**Comment by ljfranklin** [comment]
@EloyRedondo thanks! Checking to see if the text contains `bot.identity.name` should do the trick.
