### ISSUE TITLE
Environment variables should be UPPERCASE

### ISSUE THREAD

**Issue by antonwintergerst** [howdyai/botkit#437]
Specifically, the use of "port" for the environment variables in the examples that contain lines such as this one:
`if (!process.env.clientId || !process.env.clientSecret || !process.env.port) {`
Please change "port" to the more commonly used "PORT" variable.

**Comment by peterswimm** [comment]
If you submit a pull request I'll ask our team to evaluate it!

**Comment by pmdatascientist** [comment]
Making Pull

**Comment by pmdatascientist** [comment]
Dev/newdocs #761

**Comment by peterswimm** [comment]
Can you make it against the current docs? That branch you worked in has been deprecated.
