### ISSUE TITLE
Support for the Slack Events API

### ISSUE THREAD

**Issue by pasali** [howdyai/botkit#438]
Botkit currently supports the RTM API in Slack which is based on WebSockets. Because of this we cannot use BotKit with AWS Lambda. Consider adding support for the  Event API of Slack.

**Comment by peterswimm** [comment]
Coming soon, but if anyone wants to submit a PR with it done, we'd review it! ;)

**Comment by impactmass** [comment]
@pasali I'm building a Slack command (which I think can rely solely on the Events API). I'm thinking in the line of AWS Lambda like you mentioned. Are you working on suggestions to make Botkit work in this way? I'm willing to sync up with you on that.

**Comment by pasali** [comment]
@impactmass I don't have time and actually in a bit of a hurry so i did a quick search on google for other 3-party libraries.

**Comment by colestrode** [comment]
I think this can be closed @peterswimm
