### ISSUE TITLE
No way to determine message type in message_received handler

### ISSUE THREAD

**Issue by ianp** [howdyai/botkit#447]
For example, when a Facebook bot receives a post back it will trigger both the `facebook_postback` and `message_received` events, while this is good for conversational usage it means that messages will be processed twice in some cases. It would be good if there were an easy way to tell if a message had been generated from a post back in the message_received handler.

I'd like to add a `type` field to the message which would be set to `facebook_postback` (similar to how the Slack bot adds a `type` field to some messages).

(Botkit versions 0.4.0 and HEAD)

**Comment by agamrafaeli** [comment]
Submitted PR #469 to resolve this

**Comment by benbrown** [comment]
Merged! Thank you!
