### ISSUE TITLE
Conversation randomly ends when a http post request is made

### ISSUE THREAD

**Issue by EloyRedondo** [howdyai/botkit#449]
When I do a http request in the middle of two questions, the conversation randomly ends with a convo.status "completed". In my complete code, I have like 3-4 questions with a http request before each convo.ask() and sometimes the conversation works well, but other times the conversation finishes after 1,2 or 3 questions without error messages.
This is an example of how I do the requests in my code:

![example](https://cloud.githubusercontent.com/assets/17722956/19442665/6a1dc308-948a-11e6-96ea-ebcd232f6c0d.png)

**Comment by EloyRedondo** [comment]
Well, the problem is that the askKey function finishes before answer comes, so the convo.ask in the askKey function never is does.
This is because the http request is asynchronous. If I do a synchronous request the conversation works well, but I can't use a timeout handler (xmlHttp.ontimeout) to prevent a server down.
Can I do something to prevent the askKey function finishes?

**Comment by benbrown** [comment]
If you want to use asynchronous functions in the middle of your conversations, you will need to use the conversation thread system, as in the example below:

```
// using async functions with a conversation requires use of threads!

// send a message with an action field
// this action will cause botkit to call gotoThread('completed')
// after the message is sent
convo.say({
    text: 'DOING A THING',
    action: 'completed'
});
convo.addMessage('Success!','completed');
convo.addMessage('FAILED!', 'failed');
convo.beforeThread('completed', function(convo, next) {

    asyncprocess().then(function() {
        // continue on to completed thread
        next(); 
    }).catch(function() {
        // ctch error in the failed thread
        convo.gotoThread('failed');
    })

});```
