### ISSUE TITLE
bot.createConversation is not available for facebook ?

### ISSUE THREAD

**Issue by vickymicky** [howdyai/botkit#450]
Hi,

Thanks for the latest updates. I have a doubt.
Is bot.createConversation functionality is available for facebook bot also ? I tried using it, i was getting 500 as response no error message :( . So, when i checked https://github.com/howdyai/botkit/blob/master/lib/Facebook.js I could not find create conversation method, i copy pasted the code which was there in https://github.com/howdyai/botkit/blob/master/lib/Slackbot_worker.js#L297, then it started working. 
Is it missed intentionally ? i.e. specific for slack bots only ?

**Comment by vickymicky** [comment]
@seahen Thanks for PR.

**Comment by peterswimm** [comment]
Merged into Botkit as of 0.4.1

https://github.com/howdyai/botkit/blob/master/changelog.md
