### ISSUE TITLE
Messenger video not loading ...

### ISSUE THREAD

**Issue by ajith007** [howdyai/botkit#451]
Hello, 

Any idea why the below code isn't loading the video? It displays the typing indicator for few seconds and then nothing happens. 

```
          controller.hears('music', 'message_received', function(bot, message) {
        var musicAttachment = {
          'type':'video',
          'payload':{
              'url':'https://www.youtube.com/watch?v=YQHsXMglC9A'
            }
        };

        bot.reply(message,{attachment:musicAttachment});
    });
```

I was following the below doc for the video attachment syntax -
https://developers.facebook.com/docs/messenger-platform/send-api-reference/video-attachment

Thanks!

**Comment by alexbudin** [comment]
Have you managed to resolve this?

Can you try:

```
bot.reply(message, {
	attachment:{
		'type':'video',
		'payload':{
			'url':'https://www.youtube.com/watch?v=YQHsXMglC9A'
		}
	}
});
```

Also what version of Botkit are you using? , can you make sure you have updated to the latest one, also make sure you have setup your webhooks properly in Facebook

**Comment by ajith007** [comment]
Hi alexbudin, this is still an issue. I tried on a new messenger bot with the latest botkit and the video doesn't load. I tried your code as well, but no luck. Is there a specific webhook that we need to setup on Facebook side to reply with a video attachment? I tried image and it's loading correctly.

**Comment by akhanukov** [comment]
Hey @ajith007 and @alexbudin, I have been able to load and play video successfully on Messenger, BUT, as per those docs: "URL of video binary", which means it won't load a stream from youtube for instance. I had to download the youtube videos, convert them to .mp4 and host them myself. Also, be aware, large videos take some time to load so keep that typing notification going and/or let the user know it make take a moment...

**Comment by akhanukov** [comment]
Just to add, since it doesn't make sense you can't just attach a youtube video or at least an FB video, how about an experience where you use a URL template button to launch webview to some sort of "simplified" youtube streaming intermediary page? I'm using webviews to offload a bunch of UI limitations, AND to keep sensitive data out of transcripts...

**Comment by akhanukov** [comment]
Yum! I forget if Messenger allows animated GIFs. I converted video to GIFs for Slack to get some action into it...

**Comment by ajith007** [comment]
@akhanukov I tried with mp4 hosted myself, but no luck getting the video played. 

@alexbudin , @benbrown just curious, were you able to get a video played in Messenger using botkit?

**Comment by jonchurch** [comment]
Messenger will autoplay gifs sent in chat by your bot, as long as they
arent in carousels I believe

**Comment by akhanukov** [comment]
Hey @ajith007, how large is the video? And it's exported as an .mp4 you've verified works in other players? Sometimes a poorly transcoded file won't render either. I went and looked and I believe I tried to keep the videos down to under 10MB. Have you modified the code above since or is that it? Are you getting any errors from FB in console when debugging?

**Comment by ajith007** [comment]
Hi @akhanukov , I converted the mp4 to an animated gif using giphy.com, added the attachment as an image and it's working now. For my use case, this is good enough. Btw, the mp4 was only less than 4MB. Thanks again for all your inputs, really appreciate it. 👍

**Comment by jonchurch** [comment]
I too have had issues with fb and videos
They have an asset api that allows you to upload the file to them and use
an id instead of a link.

Not sure if that helps serve the asset faster on the users end, probably
not but might be something to try

**Comment by ajith007** [comment]
Thanks @jonchurch, thats good to know. 👍
