### ISSUE TITLE
Slack: Edit message during conversation

### ISSUE THREAD

**Issue by brion-fuller** [howdyai/botkit#455]
It looks like when you are in the middle of a conversation with a bot, if you edit your answer the conversation does not update the answer it contains.

**Comment by jonchurch** [comment]
To clarify, you mean when a user edits their own answer to a bot?

**Comment by brion-fuller** [comment]
Correct.

**Comment by benbrown** [comment]
This is correct. Botkit does not have any built in support for handling message edits.

**Comment by JamesMGreene** [comment]
Sadness. 😞
