### ISSUE TITLE
Optional Parameter in addQuestion() requires a blank object to be passed to it

### ISSUE THREAD

**Issue by shrutikk** [howdyai/botkit#456]
The addQuestion() method in conversations has an optional third parameter for capture_options and a required 4th parameter for thread_name. But it is required that a blank object is passed as the thirs parameter even if we dont want any capture_options or otherwise it takes the 4th parameter as the third and gives weird functionality.

**Comment by peterswimm** [comment]
What is your suggestion for this issue? Documentation update or a feature enhancement?

**Comment by shrutikk** [comment]
The document does need to be updated because it gets very confusing as to why the functioning is not as expected. The documentation should state that if no capture options are needed pass in an empty object.
