### ISSUE TITLE
slackbutton_bot.js does not include redirectUri in config

### ISSUE THREAD

**Issue by bambielli** [howdyai/botkit#458]
I'm using botkit v 0.4.0 from NPM. 

https://github.com/howdyai/botkit/blob/master/examples/slackbutton_bot.js#L41

I just got a slackButton bot working from the slackbutton_bot.js starter code. When I was initially trying to get my bot to authenticate via the "login" url, I was getting an error "missing clientId in request". The issue seemed to resolve itself when I passed the redirectUri in as an environment variable. 

I think this should be added to the slackbutton_bot.js at the line highlighted in the snippet above. I can submit a fix once someone verifies that this is an actual issue.

**Comment by jonchurch** [comment]
Submitted PR #465
