### ISSUE TITLE
Unknown message

### ISSUE THREAD

**Issue by torloneg** [howdyai/botkit#464]
how I can intercept messages that are not managed by hear?
thx.

**Comment by jonchurch** [comment]
If you want to handle messages that don't match anything else you are looking for, a catch-all response like "I'm sorry, I don't understand" you can put the following after every other hears
```
controller.on('message_received', function(bot, message) { bot.reply(message, 'Come again?') })
```
This will trigger whenever a message is received, but not caught by a hears function

If you are trying to respond to an event besides a message, those can be caught by `controller.on('event', function(bot, message){})`
where `'event'` is a platform specific or general botkit event. (like `bot_channel_join` or `facebook_postback`)

**Comment by EloyRedondo** [comment]
I do not recommend use the 'message_received' event because it is triggered by too many events, so better use `controller.on(['direct_message','direct_mention','mention'], function(bot, message) { ........ });` instead.

**Comment by benbrown** [comment]
It is also possible to add a wildcard `hears` event, as such:

```
controller.hears('.*','message_received', function(bot, message) {
//...
});
```

**Comment by ricagurgel** [comment]
Hi. I'm looking how wildcard can work with hears. Anyone?
