### ISSUE TITLE
What's kind of message?

### ISSUE THREAD

**Issue by ZuzooVn** [howdyai/botkit#47]
I saw some Bot can post message like below format, I do not look like normal message.

<img width="983" alt="screen shot 2015-12-28 at 4 51 16 pm" src="https://cloud.githubusercontent.com/assets/1429230/12016942/6aacf38c-ad83-11e5-986c-650a43963814.png">

Can we do that with botkit?

Thanks

**Comment by benbrown** [comment]
Yes, you can do this using attachments.

See here for an example:
https://github.com/howdyai/botkit/blob/master/examples/demo_bot.js#L82
