### ISSUE TITLE
Find out who send message and message type in sender middleware

### ISSUE THREAD

**Issue by MarloweW** [howdyai/botkit#475]
I have several patterns that would reply to user with `direct_message` and `direct_metion` and `mention`. I want to append `@user` in reply message when origin message received via any mention methods, and do it automatically. Now I have to do the check in every command as in sender middleware I can only access to channel and text, without original user's info.

Explain with code:

Now I have to do this in every hears:
```
controller.heaers(['patterns'], 'direct_message,mention', (bot, message) => {
var reply = 'xxxx'
// check message comes from mention
var reply = reply + message.user
})
```

Which could be done in sender middleware, except:
```
controller.middleware.send.use(function(bot, message, next) {
// message.user is undefined in middleware
    next();

});
```

**Comment by benbrown** [comment]
As of version 0.6, outgoing messages sent with reply (and sent by conversations) now have a message.to field that should contain the user id of the recipient.
