### ISSUE TITLE
bot.startConversation() stopped working with Facebook Messenger?

### ISSUE THREAD

**Issue by liornaar** [howdyai/botkit#478]
Hi, I have my app running for about two weeks now with no problem, when I change the code in a conversation flow everything seems to be fine and working

Today I've tried to change my code inside a conversation flow but when I try to test the changes I see nothing has changed in the actual conversation with the bot, like he still working on the code from couple of days ago.. when I dived deeper into the problem it seems like everything after bot.startConversation() doesn't change
and in the logs I get the following error:

> debug: API ERROR { message: '(#100) No matching user found',
>   type: 'OAuthException',
>   code: 100,
>   error_subcode: 2018001,
>   fbtrace_id: 'DKeNCoGi1Pz' }

from searching around the error means im trying to test the app with a tester privilege, but i'm not... i'm the administrator of the app

any thoughts? did someone encountered something similiar?
I did add some people as testers in the Roles section in facebook.developers under my app settings but i've deleted all of them and only I have the access to interact with the app

**Comment by GautierT** [comment]
Hi, 
How did you fix this ?
I guess it's fixed because you close the issue.
Thanks.

**Comment by majeedus** [comment]
I have the same problem what was your solution?

**Comment by liornaar** [comment]
Sorry, I am no longer developing this project.. I don't remember exactly what I did to overcome this problem but I remember I had some kinda of type in this.. you should try adding logs in your app and in the module itself, this may help you.
If you are in the start of developing your app, think of another approach or search around to get the same results.
Good luck.
