### ISSUE TITLE
Simple storage method syntax consistency question

### ISSUE THREAD

**Issue by maxrpeterson** [howdyai/botkit#488]
I was getting an error while trying to delete a saved item, and looking at the source code noticed that the `get` method requires the id of the item itself, but `delete` requires you to pass the whole object (or any object that has a property of `id` with the id you're trying to delete). See [here](https://github.com/howdyai/botkit/blob/master/lib/storage/simple_storage.js#L60).

I'm wondering if this is as designed? Or is this a bug and `delete` should accept just the id itself? The docs seem to imply you only need to pass the id itself. ex:
```
controller.storage.users.delete(id, function(err) {...});
```

Happy to submit a PR if this is a bug.

**Comment by benbrown** [comment]
This has been fixed.
