### ISSUE TITLE
Firewall issue

### ISSUE THREAD

**Issue by abhi007tyagi** [howdyai/botkit#489]
While launching the slack_bot.js, I am receiving error:

cmd-> token=<TOKEN> node slack_bot.js
error-> debug: Got response [Error: SELF_SIGNED_CERT_IN_CHAIN] undefined

how can I work behind firewall?

**Comment by peterswimm** [comment]
Have you tried loca tunnel or ngrok?
https://localtunnel.github.io/www/
https://ngrok.com/

**Comment by abhi007tyagi** [comment]
These are not allowed :( Thanks Abhinav Tyagi 

    On Saturday, 12 November 2016 3:17 AM, Peter Swimm <notifications@github.com> wrote:
 

 Have you tried loca tunnel or ngrok?
https://localtunnel.github.io/www/
https://ngrok.com/—

**Comment by peterswimm** [comment]
I dont think there are any solutions for running a remote service on a machine that is locked down from the outside world in that manner, but am happy to be corrected. You may want to consider using a service like Digital Ocean, etc to host the bot.

**Comment by alexbudin** [comment]
You can also try a **VPN** connection and then use what Peter has suggested. The VPN might open you up to the world and then **ngrok** or **localtunnel** will do its thing.

If these don't work then try **DigitalOcean** to setup a **NodeJS** instance (**you can [signup to DigitalOcean]( https://m.do.co/c/c81da0484de9) using my referral link**), or you can use **Heroku** (might still give you some issues with using the CLI depending on your firewall).

Hope it helps.

Alex

**Comment by peterswimm** [comment]
Closed as resolved
