### ISSUE TITLE
Default hostname should be 0.0.0.0 not 127.0.0.1

### ISSUE THREAD

**Issue by EliKrumholz** [howdyai/botkit#492]
The current default hostname is set to 127.0.0.1, which causes errors when deploying to heroku, unless it is overridden with 0.0.0.0. 

The node http module, which express inherits from, uses 0.0.0.0 as the default (as described here: https://nodejs.org/api/http.html#http_server_listen_port_hostname_backlog_callback)

> If the hostname is omitted, the server will accept connections on any IPv6 address (::) when IPv6 is available, or any IPv4 address (0.0.0.0) otherwise.

**Comment by danielckv** [comment]
+1

**Comment by aj-may** [comment]
+1 same issue with docker

**Comment by peterswimm** [comment]
PR above has been merged, pending next update.
