### ISSUE TITLE
Google Hangout bot

### ISSUE THREAD

**Issue by abhi007tyagi** [howdyai/botkit#497]
Can we expect a google hangout bot ?
Can this be added as enhancement or new feature?

**Comment by peterswimm** [comment]
Is there a public API for more info on this?

**Comment by abhi007tyagi** [comment]
Not sure, but found something in Python
HangupsBot 1.6.0 : Python Package Index

  
|  
|   
|   
|   |    |

   |

  |
|  
|   |  
HangupsBot 1.6.0 : Python Package Index
 Bot for Google Hangouts  |   |

  |

  |

 
 Thanks Abhinav Tyagi 

    On Tuesday, 15 November 2016 10:00 PM, Peter Swimm <notifications@github.com> wrote:
 

 Is there a public API for more info on this?—

**Comment by abhi007tyagi** [comment]
more python based repo.
https://github.com/hangoutsbot/hangoutsbot

**Comment by peterswimm** [comment]
https://developers.google.com/hangouts/chat/how-tos/bots-develop
This is now more possible!

**Comment by benbrown** [comment]
I am working on this! Let me know if you are interested in trying it.

**Comment by tconnors** [comment]
I'm definitely interested in this, let me know if there's somewhere I can help

**Comment by ouadie-lahdioui** [comment]
+1 interested too

**Comment by benbrown** [comment]
@tconnors are you a member of community.botkit.ai?

join us in the #botkit-google channel to get involved!

**Comment by guillain** [comment]
Hi @benbrown ,
I'm interesting too, let me know if I can help

**Comment by peterswimm** [comment]
@guillain jump onto our slack for progress or to get involved!

**Comment by peterswimm** [comment]
Anyone following this, there is a PR to test! Follow the link above to test and give feedback.

**Comment by peterswimm** [comment]
And here is a beta starter kit to try out:
https://github.com/howdyai/botkit-starter-googlehangouts
