### ISSUE TITLE
Inquiry: Custom Webhook - Express Required?

### ISSUE THREAD

**Issue by TheJimFactor** [howdyai/botkit#499]
First, thanks for making botkit!

I have a question about trying to make a custom webhook into botkit. I'm trying to hook up so a facebook webhook subscription to a page's feed will post to a slack chat.

With the current botkit framework, what would be the easiest way to do this? From my experience so far with botkit, it would seem as though not much of the server stuff is exposed/customizeable and I would need to instead make an express server to monitor the webhook URL.

Could people who have tackled/attempted to tackle this let me know how they did it/would do it?

Edit:
I forgot to mention that the slackbot would be posting these received messages via a slack incoming webhook ideally. Having both a botkit to handle the OAuth for the slack button integration, yet still have a custom webhook for the facebook webhook.

My current plan is to follow along with the: https://github.com/mvaragnat/botkit-express-demo

**Comment by TheJimFactor** [comment]
I forgot to mention that the slackbot would be posting these received messages via a slack incoming webhook ideally.

**Comment by benbrown** [comment]
The best way to learn how to make custom webhook endpoints that interact with Botkit is to look at the starter kit projects:

https://github.com/howdyai/botkit-starter-slack
https://github.com/howdyai/botkit-starter-facebook
https://github.com/howdyai/botkit-starter-teams
https://github.com/howdyai/botkit-starter-ciscospark
