### ISSUE TITLE
Sometimes i have to stop and start the node app again to receive messages

### ISSUE THREAD

**Issue by alexbudin** [howdyai/botkit#502]
Hi guys,

I am developing a chatbot for Facebook Messenger.

Every time i start the facebook botkit example node app messages i send to the bot dont get to it, but after i stop the app and start it up again the messages go trough.

It happens every time.

I have tried it with localtunnel and on a dedicated nodejs server and it always behaves like this.

First time i run it (when it doesn't receive messages), everything seems fine as i get this:

```
info: ** No persistent storage method specified! Data may be lost when process shuts down.
debug: Setting up a handler for spawned
debug: Setting up a handler for heard_trigger
debug: Setting up a handler for command_triggered
debug: Setting up a handler for remote_command_end
debug: No handler for stats:spawned
debug: Setting up a handler for facebook_optin
debug: Setting up a handler for message_received
debug: Setting up a handler for message_received
debug: Setting up a handler for message_received
debug: Setting up a handler for message_received
debug: Setting up a handler for message_received
debug: Setting up a handler for facebook_postback
debug: Setting up a handler for message_received
debug: Setting up a handler for message_received
debug: Setting up a handler for message_received
debug: Setting up a handler for message_received
debug: Setting up a handler for message_received
debug: Setting up a handler for message_received
info: ** Starting webserver on port 3000
info: ** Serving webhook endpoints for Messenger Platform at: http://0.0.0.0:3000/facebook/receive
ONLINE!
debug: Successfully subscribed to Facebook events: {"success":true}
debug: No handler for tick
debug: No handler for tick
debug: No handler for tick
debug: No handler for tick
debug: No handler for tick
debug: No handler for tick
debug: No handler for tick
```

Second time i run it the debug messages are the same but messages do go trough, sometimes i also get the ones i sent before stopping the process (when messages were not coming trough).

There is no firewall issue, nor server or port issue, i have checked may many times.

Has anyone had any experience with this, or can help me try to find out what is going on?

Thank you so much.

Alex

**Comment by jonchurch** [comment]
This happens to me a lot, it seems like messages aren't being delivered to my webhook, or at least aren't making it to my local machine through localtunnel. 

Personally I think it is a facebook issue. I have experienced this since they first opened up the Messenger platform, but it has gotten a lot less frequent as they've worked on the platform, it seems.

**Comment by peterswimm** [comment]
@alexbudin did you ever get this resolved?

**Comment by alecl** [comment]
I can't say for sure this is localtunnel's fault but just for kicks have you tried ngrok instead? I had all sorts of grief with disconnects and issues with localtunnel. I paid for ngrok and never looked back. Just wasn't worth my time messing with localtunnel. I think it got too popular to be adequately scaled as a free service.
