### ISSUE TITLE
Beginner guide to Messenger bot using Botkit with Heroku

### ISSUE THREAD

**Issue by devhaoy** [howdyai/botkit#504]
Quick feedback on my experience setting up the webhook url for Botkit with Heroku. I am no experienced dev so I had a hard time figuring out what are the necessary steps to add to the Botkit's Getting Started tutorial.

1/ Create a Procfile that directs to a worker dyno. 
`worker: node facebook_bot.js` (for the facebook_bot example)

2/ Create a .env file that includes your page_token and verify_token.

```
page_token=<insert your page token here>
verify_token=<insert your personal token here>
```

3/ In your app in Heroku, go to Settings and add Config vars. This prompt you to add a key and a value. First key should be page_token, value is the token provided by Facebook. Second key should be verify_token, value is your personal token.

4/ In your app in Heroku, in Resources, make sure your worker Dyno is on.

5/ Add `"start": "node facebook_bot.js"`(for the facebook_bot example)  to the scripts in package.json (should be added under `"test": "mocha tests/*.js",`)

6/ In facebook_bot.js, change `process.env.port` to `process.env.PORT`. Indeed Heroku requires capital letter to recognize the port.

7/ In facebook_bot.js, you might need to change all `uptime` to `90`

**Comment by peterswimm** [comment]
Closing in favor of the more popular issue thread linked above
