### ISSUE TITLE
bot.StartConversation() freezes in Slack

### ISSUE THREAD

**Issue by vantonop** [howdyai/botkit#509]
Not always, but quite frequently the bot freezes when attempting to start a conversation. 
It's in Slack, using the RTM. Bot seems connected in the team, but i get no logs, no response at all.
I am using version 0.2.2.

**Comment by benbrown** [comment]
Is there any reason you haven't upgraded to the latest? Shouldn't break anything.

Hard to say what might be happening...can you show some of your code?

**Comment by vantonop** [comment]
No other reason apart from the fear that something may break :-).

Here is the code:

controller.hears(['test'], 'direct_message,direct_mention', function (bot, message) {

    askQuery = function(response, convo) {
          //freezes before user receives the message below
          //latest log: info: > [Start] XX Conversation with U2UXXXX in C1GXXXXX
         convo.ask('Type your query please :mag_right:', function(response, convo) {
             if (response.text.trim() != ''){
                //do smth 
            }
            convo.next();  
          });  
    }

       getUserAuthDataAsync(bot.identity.id)
        .then(function(cid){
          //read some stored data
              var dataCache = db.getSync(bot.identity.id);
              if(dataCache.hasOwnProperty('userid')){
                  var a = dataCache.x
                  var b = dataCache.y

                  //start a conversation to handle this response.
                 //execution reaches this point and attempts to start conversation
                  bot.startConversation(message, askQuery);
              }
              else{
                //Tell user something
              }
        });
}

**Comment by alexbudin** [comment]
Try to upgrade to 0.4.2, there are A LOT of improvements and fixes.

https://github.com/howdyai/botkit/archive/v0.4.2.zip

**Comment by benbrown** [comment]
Your askQuery function has the wrong parameters. It should receive 'convo' only.

**Comment by vantonop** [comment]
I have upgraded to 0.4.2 and i am waiting for it to see if it will freeze again.

Hmm, i guess the first parameter in askQuery() is not needed, will try to fix that, but i don't think that this is causing the issues, as it is not happening all the time, but occasionally.

**Comment by peterswimm** [comment]
Did this solve the issue?

**Comment by vantonop** [comment]
Yes, it has been stable for a long period of time now. I have upgraded to the latest version and removed the extra variable.
