### ISSUE TITLE
bot.say doesn't work for a Slack bot

### ISSUE THREAD

**Issue by TheJimFactor** [howdyai/botkit#511]
bot.reply, .startConversation and .startPrivavateConversation work, but when I try to use
```

bot.say({
text:'something',
channel:'C2CHANNELID'
});
```

it doesn't go through. Currently I am using bot.api.chat.postMessage as a workaround since that appears to be working.

**Comment by alexbudin** [comment]
What version of botkit are you using? If you are using 0.4.2 can you try 0.4.1 (https://github.com/howdyai/botkit/archive/v0.4.1.zip) and see if you get the same issue.

Also posting more code or your entire code would be a lot more helpful and your debug information.

Alex

**Comment by peterswimm** [comment]
@TheJimFactor I think I saw you working through this issue on dev4slack, did you get sorted?

**Comment by abinashmohanty** [comment]
Hey @alexbudin I've tested using the updated Botkit version `0.4.2.` and it's working perfectly fine. 

```
bot.say({
      text: "Welcome to our test zone!",
      channel: 'G38RUGE4D' // channel Id for #slack_integration
  });
```
Results

<img width="363" alt="Slack Chat Bot" src="https://cloud.githubusercontent.com/assets/8434934/20792061/f03010d0-b7e5-11e6-91dd-a357c78acba4.png">

**Comment by jonchurch** [comment]
Is your bot a member of the channel you are trying to post to?
