### ISSUE TITLE
Storage test should be moved into the tests/ folder

### ISSUE THREAD

**Issue by benbrown** [howdyai/botkit#52]
All of the tests should be in there all together.

However, this would require that all the dependencies for any possible storage method would have to be installed... which might be a lot of unnecessary junk.

I think storage module dependencies are a sticky issue in general. It may make sense to break them out into subordinate plugin modules to be installed and managed independently. Something to think about!

**Comment by anonrig** [comment]
While moving tests folder, having a unified testing methodology is I believe important. I suggest using assert with describe 

  - Assert: https://www.npmjs.com/package/assert
  - Describe: https://www.npmjs.com/package/describe

There is a great example by tj @ https://github.com/expressjs/body-parser/blob/master/test/json.js

**Comment by RafaelCosman** [comment]
@anonrig Sounds good. It seems like top priority right now w/r/t/ the storage modules is to move them out of ```storage/``` and into separate NPM repositories. Discussion of this is in #62.

Once we do that we can move ```storage_test.js``` and update it.

**Comment by anonrig** [comment]
Additionally, each storages should have their own tests in their repositories. The need for storage_test will perish because howdyai will not be responsible in the future for 3rd party storage solutions. In theory I think it is the best solution, but I am uncertain in practical. @RafaelCosman @benbrown

**Comment by benbrown** [comment]
This is basically a non-issue now, isn't it? Each storage project has its own tests. @RafaelCosman @anonrig can we close?

**Comment by anonrig** [comment]
We should remove the `/storage` folder in order to close this issue. @benbrown

**Comment by peterswimm** [comment]
@anonrig @benbrown is it ok to close this out yet?

**Comment by anonrig** [comment]
Yup, it is closed.
