### ISSUE TITLE
Installing say yyy..

### ISSUE THREAD

**Issue by Global-Open-Source** [howdyai/botkit#521]
When you install or clone from github, the cmd/terminal just saying yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy for ever....

**Comment by peterswimm** [comment]
At what step? Could you post a screenshot somewhere?

**Comment by peterswimm** [comment]
Closed pending further info
