### ISSUE TITLE
Dynamic Script?

### ISSUE THREAD

**Issue by eformx** [howdyai/botkit#522]
I will have a Bot Builder where a user can configure the 'rules' for the Bot.  Those rules would be based on a BotKit script.  If I can automate the building of the script (probably what your Studio will do) can the script be saved and injected into the page dynamically, before the conversation begins?  Do you have any suggestions if this is possible or a pointer to some script that will demonstrate this?

**Comment by jonchurch** [comment]
Can you elaborate on this?

Do you mean putting your bot.hears conversations into a seperste file and loading those?

Or are you referring to modifying the conversation with dynamic/custom variables just before sending the conversation to a user?

**Comment by ErinsMatthew** [comment]
@eformx: If I understand what you are asking, then this is exactly what I do for a Slack bot I built using Botkit.  Here's an [example](https://gist.github.com/ErinsMatthew/8e3f55ba48e363530eaed13040a9fe06) if you want to take a look.  It can be easily extended to use a template engine such as Handlebars, or made even more dynamic.

**Comment by peterswimm** [comment]
Closed as answered
