### ISSUE TITLE
Propery way to listen for other bot messages in a slack channel?

### ISSUE THREAD

**Issue by TheJimFactor** [howdyai/botkit#523]
I've tried controller.hears('somethng', 'ambient') and controller.on('ambient'), but both of those only pick up user messages and not a bot message.

The bot I'm making is supposed to react to another bot posting in a channel.

**Comment by peterswimm** [comment]
Botkit does not currently support bot to bot communications, but may do so in a future update (perhaps quicker if anyone wants to take a stab at a PR)

**Comment by benbrown** [comment]
@TheJimFactor there is a bot_message event that fires when bots talk!

**Comment by colestrode** [comment]
I thought this was a limitation with Slack? Bots listening to bots could create a really bad infinite loop of responses.
