### ISSUE TITLE
convo.say() not firing in Promise/looping intensive code

### ISSUE THREAD

**Issue by zachschultz** [howdyai/botkit#529]
Hi all,

I am attempting to wrap code that contains forEach loops and Promises inside the bot.startConversation() callback but I'm having weird issues.

For example, my code looks like this:

```
bot.startConversation(message, (err, convo) => {
            convo.say('Here are the announcements from all your classes.');
            courses.forEach((tempCourse) => {
              convo.say('');  // Hack, needed for convo to work
              displayCourseAnnouncements(convo, message, controller, tempCourse)
              .then((returnAttachments) => {
                    returnAttachments.forEach((a) => {
                      convo.say(a);
                   });
                });
              });
      });
```

The above code only works as expected when I include `course.say('')`. If I don't have that, all the convo sends is 'Here are the announcements from all your classes.' and then it dies out. Can anyone with more insight help me figure out why this may be?

**Comment by jonchurch** [comment]
`bot.startConversation()` [creates and then starts a conversation immediately](https://github.com/howdyai/botkit/blob/master/readme.md#botstartconversation), `bot.say()` adds messages to the message queue of the conversation object you are in and sends them immediately. 
Perhaps your convo is finishing before before the other messages are added to the queue, and maybe the convo.say('') is preventing that.

A cleaner way to do this would be [creating a conversation](https://github.com/howdyai/botkit/blob/master/readme.md#botcreateconversation), iterating through your `returnAttatchments` and [adding them to the message queue](https://github.com/howdyai/botkit/blob/master/readme.md#convoaddmessage), then [activating the conversation](https://github.com/howdyai/botkit/blob/master/readme.md#conversationactivate) once all the promises have returned. This way the messages only fire once they've all be queued up.

**Comment by jonchurch** [comment]
Here's an example of waiting for the promises to resolve and then adding them all to the message queue before activating the convo. 

```
// represents the array you were iterating over first
    var courses = [1, 2, 3, 4];

// this can be any async function that returns a promise
// here, as in your example, this function resolves with an array
// setTimeout is used to mimic an async function here
    var asyncFn = function(x) {
    return new Promise(resolve => setTimeout(() => resolve([x, x * 2]), 100));
};

// create a dormant convo
bot.createConversation(message, (err, convo) => {

// queue the first message
            convo.addMessage('Here are the announcements from all your classes.');

// use map to apply our async function that returns a promise to each element of our array
// map returns an array of promises here, which we pass to Promise.all to make a promise 
// that resolves when all the promises in the array resolve
            var response = Promise.all(courses.map(asyncFn));

// once response resolves, we iterate through the array of arrays 
            response.then((data) => {
              data.forEach((element) => {
                element.forEach((a) => {
// add each element of the returned arrays to the message queue
                  convo.addMessage(a.toString());
                  console.log('adding message:',a)
                });
              });

// Activate the conversation and send the queued messages
              convo.activate();
              console.log('Actvate!')
            });
      });

```

**Comment by zachschultz** [comment]
@jonchurch Thank you so much man! When I get back home today I'll try this out and let you know how it works. I really appreciate you taking the time to answer this.

**Comment by zachschultz** [comment]
@jonchurch worked like a charm, thank you very much! The `Promise.all(...)` is really what I needed, I actually used a solution like this earlier on in my code-base and I'm surprised I didn't think of it again!

**Comment by jonchurch** [comment]
Good to hear! Are you a part of the [dev4slack slack team](http://dev4slack.xoxco.com/)?

Lots of great soultions in there if you run into anymore snags!

**Comment by peterswimm** [comment]
Thanks guys! Closing as resolved!

**Comment by thierryskoda** [comment]
Hey @jonchurch I'm using a lot `bot.createConversation` with `convo.activate()` and it works very well. But what should be the pattern if I need to wait for a promise at the end of the conversation depending on the values that the user said? For exemple, I'm asking the user 3 things and depending on those 3 things, I `convo.say()` something different. But I never know the text in `convo.say()` until the user finished to choose the 3 things.

Thank you very much!
Thierry
