### ISSUE TITLE
Slack - Interactive Message requires request url

### ISSUE THREAD

**Issue by abinashmohanty** [howdyai/botkit#534]
Hello,

I was using this interactive message example from botkit's [example](https://github.com/howdyai/botkit/blob/master/examples/slackbutton_bot_interactivemsg.js) folder. Everything works except just one thing that is what `request url` should be there under **Slack App > Interactive Message > Request URL** parameter ? I'm testing this locally, but I would like to know how one can put the url to validate or process the action buttons. 

Currently, by clicking on the buttons it says...
`...because this app is missing a request URL`

<img width="614" alt="screenshot 2016-12-06 13 20 06" src="https://cloud.githubusercontent.com/assets/8434934/20917303/c05ee712-bbb6-11e6-93d1-874b4d62a79e.png">

**Comment by jonchurch** [comment]
The request url should be something like `https://www.YOUR_HOSTNAME.com/slack/receive`

If youre using localtunnel to expose a port from a development machine to slack, then it will be something like `https://YOUR_SUBDOMAIN.localtunnel.me/slackreceive`

**Comment by benbrown** [comment]
The request URL is configured inside the slack dashboard, at this link:

https://api.slack.com/apps

**Comment by jackson-sandland** [comment]
It would be awesome if the requestURL could be sent along with the message, and have slack open a browser window with the URL that is passed.

**Comment by peterswimm** [comment]
@jackson-sandland That's more of a Slack platform request! We will gladly support any supported platforms' provisioning API's as they become available.
