### ISSUE TITLE
Where is bot.createConversation function ? 

### ISSUE THREAD

**Issue by btomashvili** [howdyai/botkit#535]
I just created facebook-bot from samples but I have error regard 
create conversation.

I looked at CoreBot.js and there is no any function called createConversation.

![image](https://cloud.githubusercontent.com/assets/1749122/20964484/2720f344-bc8b-11e6-9859-9b3ba86eef49.png)

**Comment by btomashvili** [comment]
Seems npm is up to date 
I installed from github, and now it works. 

```npm install  --save git+https://github.com/howdyai/botkit.git ```

**Comment by manuelalcantara** [comment]
In the BotFramework there is not a createConversation function. Why?
