### ISSUE TITLE
Quick replies Messenger

### ISSUE THREAD

**Issue by teddav** [howdyai/botkit#536]
Hello, 
I am building a bot on Messenger using Botkit and I am having a problem with quick replies.
I can't tell if it is Botkit related or a problem coming from Messenger, but since I haven't seen it on other bots, I think asking here is a good idea.

Sometimes when the user receives quick replies he cannot click on them. They have to get out of the chat and get back in the conversation in order for the quick reply to reload and be active again.
Then they can click on it and it sends it to the server.

Has anyone else experienced this ?

Thank you

**Comment by benbrown** [comment]
That is strange! If the quick reply appears in Facebook, the part that Botkit controls was successful. Can you reproduce this issue?

**Comment by teddav** [comment]
Hi @benbrown thanks for answering.
Unfortunately I have no idea how to reproduce it. Just happens at random sometimes. I use Messenger's latest version (99.0)  on an iPhone 5.
I also posted on Facebook to see if they have an answer https://developers.facebook.com/bugs/1792804087653201/

If you find out anything related to that, let me know

**Comment by benbrown** [comment]
@teddav have you learned anything else about this issue? This sounds like an issue in Messenger, not Botkit.

**Comment by alexbudin** [comment]
I have no experienced this issue and i've used quick replies. I wold assume its a Facebook issue.

**Comment by teddav** [comment]
Yes, probably more of a Messenger issue, though they haven't been able to reproduce it.
Doesn't seem very common though
