### ISSUE TITLE
can't get Slack event API to work (0.4.2)

### ISSUE THREAD

**Issue by connectdotz** [howdyai/botkit#537]
Hi I am trying to use the new slack event API instead of the RTM, configured the app with all the message events (message.channels, message.groups, etc) and added the following scopes: 

```
var service = Botkit.slackbot({
    interactive_replies : true, // tells botkit to send button clicks into
                                // conversations
    json_file_store : './db_bot/',
   rtm_receive_messages: false, // disable rtm_receive_messages if you enable events api
}).configureSlackApp({
    clientId : process.env.clientId,
    clientSecret : process.env.clientSecret,
    hostname : process.env.hostname,
    scopes : [ 'bot', 'commands', 'user',  
        'users:read', 
        'chat:read:user',
        'channels:history',
        'groups:history',
        'im:history',
        'mpim:history'],
});
```
the team has granted permission accordingly as far as I can see, but I am not receiving any user message with `rtm_receive_messages: false`. The code that receives message should be fine since it worked under RTM if I comment out `rtm_receive_messages: false`.

Not sure what I missed, thoughts? Or is there an example I can take a look?

**Comment by jonchurch** [comment]
Have you configured your webhook and event subscriptions in your Slack App settings on their website?

You also need to expose the bot to the web, by either hosting it somewhere or using a service like localtunnel.me

Last, make sure you are using `controller.setupWebserver()` and `controller.createWebhookEndpoints()` to start a server and to receive messages.

**Comment by connectdotz** [comment]
@jonchurch, 

> Have you configured your webhook and event subscriptions in your Slack App settings on their website?

Yes. snapshots below: 
event endpoint:
![event-sub](https://cloud.githubusercontent.com/assets/891093/21010324/77baccf6-bd19-11e6-819e-acc9fd62be1b.png)

bot events:
![bot-events](https://cloud.githubusercontent.com/assets/891093/21010335/7d5e377e-bd19-11e6-8937-f98512eed66c.png)

> You also need to expose the bot to the web, by either hosting it somewhere or using a service like localtunnel.me

Yes, the slash-commands worked as the evidence

> Last, make sure you are using controller.setupWebserver() and controller.createWebhookEndpoints() to start a server and to receive messages.

yes, done that 2
```
service.setupWebserver(process.env.port, function(err, webserver) {
    service.createHomepageEndpoint(webserver)
       .createWebhookEndpoints(webserver)
       .createOauthEndpoints(
               webserver, function(err, req, res) {
                if (err) {
                    res.status(500).send('ERROR: ' + err);
                } else {
                    res.send('Success!');
                }
            });
});
```
It looks like the WebhookEndpoints's `webserver.post('/slack/receive', function(req, res) ...` is only triggered when I typed slash-commands, does this mean that slack is not sending the message events I subscribed ? Here is the authentication snapshot:

![auth](https://cloud.githubusercontent.com/assets/891093/21011317/b2eadc08-bd1e-11e6-8196-74c8b16b16b4.png)

**Comment by connectdotz** [comment]
never mind, found the problem, right on the snapshot it showed the slack configuration enable-event is OFF, that was dumb, sorry, now I am good. thx.

**Comment by connectdotz** [comment]
resolved. was able to receive events from slack with 0.4.2.

**Comment by jonchurch** [comment]
@connectdotz No worries! I did the exact same thing last night working on a web api example 😂
