### ISSUE TITLE
Identifying a user

### ISSUE THREAD

**Issue by chriskinsman** [howdyai/botkit#54]
I want to get the friendly name of a user. 

Tried: controller.storage.users.get(message.user,function(err,user) {}) which is in the bot.js file but user always come in as undefined.  

Reading through source it appears that there is storage but no methods to lookup users...

Is this right?

**Comment by benbrown** [comment]
Sounds like you want to get the name of the user from Slack. Am I right?

For this, you would use bot.api.users.info()

**Comment by chriskinsman** [comment]
Yep.  Just thought there would be a method backed by storage that would identify the user from storage and only make the call if needed.  I added one.  Will look at a pull request..

**Comment by Shubhamjain112** [comment]
How do I get the user name through bot.api.users.info() ?

**Comment by ding444** [comment]
@Shubhamjain112, it's late to the game but this is how I've done it:

```javascript
controller.hears('hello', ['direct_mention'], (bot, message) => {
    bot.api.users.info({user: message.user}, (error, response) => {
        {name, real_name} = response.user;
        console.log(name, real_name);
    })
})
```

**Comment by lucaskatayama** [comment]
I got 

    { ok: false, error: 'not_authed' }


I added `users:read` to the scope... but still not_auth...

**Comment by littleStudent** [comment]
same problem here. `users:read` added to the scope. still getting `not_authed` error

**Comment by hannesjung** [comment]
same for me, did you find a fix?

**Comment by djanowski** [comment]
(For people finding this issue via Google:)

If you just want to mention the user, you don't need to query the users API to get the handle.

Format the message like this: `Hello <@${user}>`. Slack will turn the ID into a proper mention.

**Comment by littleStudent** [comment]
I could not figure out how to get the user...
I used this package just for getting the list of users https://www.npmjs.com/package/slackbots

**Comment by azizimranz** [comment]
Hi,

I want the bot to hear from only specific user.

(Its drift user that I want to hear only).

**Comment by artur79** [comment]
> (For people finding this issue via Google:)
> 
> If you just want to mention the user, you don't need to query the users API to get the handle.
> 
> Format the message like this: `Hello <@${user}>`. Slack will turn the ID into a proper mention.

what if I'v got user id and I don't want to get mention, just name ?

**Comment by EitanWeMatch** [comment]
@artur79 , did you manage to solve this because i am also trying the same thing that you wanted
