### ISSUE TITLE
say(), reply() not compatible with Event API ?

### ISSUE THREAD

**Issue by connectdotz** [howdyai/botkit#540]
Not sure if it is intended, but the say(), reply() methods do no work in hears() if messages are received via Event API and the `rtm_receive_messages` is turned off. 

the conversation worked however, so I wonder at the minimal maybe just wrap say(), reply() around conversation? otherwise update the document to distinguish which API worked with RTM vs Event...?

**Comment by benbrown** [comment]
@connectdotz Uhoh! It should definitely work. We will do some testing and get back to you.

**Comment by jonchurch** [comment]
Hmmm can you share any error messages you might be receiving, or some code where you are experiencing this?

I'm unable to reproduce this issue currently, using botkit v0.4.3, Events API and `receive_rtm_messages: false`

**Comment by connectdotz** [comment]
hmmm... I can't reproduce it with 0.4.3 either. maybe I was confused with replyPrivate() which  doesn't seem to work outside of slash-commands regardless events or RTM.

sorry for the false alarm.
