### ISSUE TITLE
Facebook share button integration

### ISSUE THREAD

**Issue by devhaoy** [howdyai/botkit#545]
[It should be very easy](https://developers.facebook.com/docs/messenger-platform/send-api-reference/share-button)  but for some reason I can't make it work. Any idea?

```
var controller = Botkit.facebookbot({
    receive_via_postback: true, 
    require_delivery: false,
});
```

```
convo.ask({
            attachment: {
                'type': 'template',
                'payload': {
                    'template_type': 'generic',
                    'text': 'message text',
                    'elements':[
                      {
                        'title':'title',
                'image_url':'https://pbs.twimg.com/profile_images/560691888085168128/cLnDcYTB.jpeg',
                        'buttons':[{
                            'type':'postback',
                            'title': 'title',
                            'payload': 'payload',
                        },
                          {
                            'type':'element_share'
                          }              
                        ]
                      }
                    ]
                  }
              }
        }, function(response, convo) {
            convo.say("Awesome.");
            nextTopic(response, convo);
            convo.next();
        });
};
```

**Comment by jonchurch** [comment]
What exactly is not working?

**Comment by devhaoy** [comment]
The share button does not display

**Comment by devhaoy** [comment]
@jonchurch sorry I don't have more detail, everything in the convo is firing normally except the share button, as if it was just ignored. A I the only one encountering the issue?

**Comment by devhaoy** [comment]
I could make it work just following [Facebook Guidelines](https://developers.facebook.com/docs/messenger-platform/send-api-reference/share-button)

Sorry and closed!

**Comment by jonchurch** [comment]
@devhaoy No worries. Just curious, what was it that you had to fix?

**Comment by devhaoy** [comment]
@jonchurch  not too sure really, I just copy pasted the Facebook example and it worked - I haven't tried to understand why my code wasn't firing the button.
