### ISSUE TITLE
Storage place

### ISSUE THREAD

**Issue by okvic77** [howdyai/botkit#55]
Where we have to publish the storage packages?

https://www.npmjs.com/package/botkit-orchestrate

or here? in ``storage`` folder.

**Comment by RafaelCosman** [comment]
Great question, @okvic77. @benbrown and I are discussing this now.

**Comment by anonrig** [comment]
Nice idea. :+1:

**Comment by RafaelCosman** [comment]
Thanks for bringing this up. @benbrown and I have been discussing this and are leaning towards having the storage modules in separate repos. We'd love your help moving the storage modules that are currently in the ```storage/``` folder to their own NPM packages.

Let's discuss this topic in #62.

**Comment by colestrode** [comment]
Should this be closed since #62 is closed?
