### ISSUE TITLE
bot start conversation based on another bot

### ISSUE THREAD

**Issue by trongdong** [howdyai/botkit#558]
Hi there, 
First, thanks for your great library. 
At the moment, we have another bot (bot A) in our channel. I want my bot (botkit) to listen to these messages and start conversation with another member (John). 
Like this: 
```
Bot A: Yay! Build #1550 passed 
Botkit: hi @john, do you want to deploy it now? 
John: yes, please do it
Botkit: Done! 
```
How can I achieve this use botkit? I can listen on `bot_message` event but I don't know how to start conversation with another member?

**Comment by trongdong** [comment]
Ok, I figured it out. 
I need to create a message object to do so. 
```
    const context = {
      user: config.owner,
      channel: message.channel
    }
    bot.startConversation(context, (err, convo) => {
    // conversation logic goes here
    });
```
Just wondering if this is the right way to do it?

**Comment by benbrown** [comment]
Yes, this is how to do it.
