### ISSUE TITLE
This person isn't receiving messages from you right now

### ISSUE THREAD

**Issue by thierryskoda** [howdyai/botkit#559]
Hey! I'm receiving: 
`info: An error occurred while sending a message:  (#200) This person isn't receiving messages from you right now`
in my log and I found that it's because someone blocked my page messenger (chatbot). Is there any way to know who blocked me?

Thank you for any help!

**Comment by jonchurch** [comment]
I don't think facebook currently gives us insight into this. 

Would be a good feature though! Maybe a bot analytics platform will come up with a clever hack in the meantime.

**Comment by adamzimon** [comment]
**Hope this may help solve the problem “this person isn't receiving messages right now”**

For Mobile use: Open and type facebook.com (do not use site m.facebook.com) on browser press the 3 dots on the upper right corner of the browser then mark check by clicking the check box on the option ‘Desktop Site’. Then proceed on below instructions.

**For PC use:**
1. Check first the Blocking options at à Settings à Blocking Option Page
Block messages- The person should not included on the block message list
Block users – The person should not included on the block list

2. Once clear you may now remove the person’s Facebook name on “Restricted list”. Option may also found at à Settings à Blocking Options Page.

**Here’s how to do it:**
- Go to Restricted list Option
- Select the ‘Edit List’
- Then click the dropdown ‘On This List’ and select “Friends” (Ensure the Check mark is on the Friends selected)
- Lastly click ‘Finish’ button to save the changes.

3. You may now test and send message to your friend if successfully received.

Thank You.
ADamSimon
