### ISSUE TITLE
Application crash

### ISSUE THREAD

**Issue by emorling** [howdyai/botkit#563]
This happened just now, haven't seen it before. It was trying to reconnect to Slack.

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND mpmulti-aush.slack-msgs.com mpmulti-aush.slack-msgs.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by peterswimm** [comment]
Has it happened since? Perhaps there was a momentary Slack issue?

**Comment by jpbaeza** [comment]
Same problem here! My app crashes randomly.
Anyone has a workaround??

Regards,

JP

**Comment by peterswimm** [comment]
@jpbaeza where is your bot hosted? What events is it processing when it crashes?
