### ISSUE TITLE
channel_joined event no longer firing

### ISSUE THREAD

**Issue by chrisberthe** [howdyai/botkit#564]
The `channel_joined` event doesn't seem to be firing. Using Botkit `0.4.4`, and tried `0.4.5` too.
 
```js
controller.on('channel_joined', (bot, message) => {
  console.log(message.user)
})
```

If I replace with `...on('user_channel_join'` instead, it works. Also, firing `channel_leave` works as well.

**Comment by jonchurch** [comment]
Ahhh, somewhere along the line channel_joined was superseded by the more specific `user_channel_join` and `bot_channel_join`. 

In your application, would you rather see both fire? Is this something you relied on previously and has broken since?

**Comment by chrisberthe** [comment]
I'm currently building the application and noticed this, so nothing is broken.

I'm on the fence - I think we should stick to one event (instead of seeing both fire) but the only thing I find oddly inconsistent is having to use `user_channel_join` and `channel_leave`. Not a biggie, just personal preference.

**Comment by jonchurch** [comment]
Well its incorrect in the docs currently, so good catch. The user_ and bot_  channel and group join events are botkit sugar over the slack event, but super handy to differentiate between the those different cases. The docs seem to indicate the botkit events are fired in addition to the original slack ones.

There is something to be said about passing the events as they come from slack, I dont think thered be any harm in popping off both.

**Comment by tansaku** [comment]
looks like it's now `member_joined_channel` ...
