### ISSUE TITLE
convo.transitionTo() is not a function

### ISSUE THREAD

**Issue by Billydubb** [howdyai/botkit#565]
The convo.transitionTo() function does not seem to exist anymore, it is however still mentioned in the docs. 

What other method can I use to send a message right before transitioning to another thread in a pre-built conversation?

Thanks,
dubb

**Comment by benbrown** [comment]
@Billydubb this function was introduced in a recent version of Botkit. You may have an out of date version.

**Comment by peterswimm** [comment]
@Billydubb did you fix your issue?

**Comment by Billydubb** [comment]
Yes, it works now. Thanks
