### ISSUE TITLE
Add tags / releases

### ISSUE THREAD

**Issue by guillaumepotier** [howdyai/botkit#57]
Hi there,

Noticed that recently many PRs and improvements have been pushed to master. It would be great (even awesome) to start tagging some releases and publishing to npm in order for us to rely on stable and fixes commit tags.

Thanks a lot

**Comment by anonrig** [comment]
You're right. We should use Semver Versioning http://semver.org/

**Comment by RafaelCosman** [comment]
@guillaumepotier, that's a good point. I not currently in charge of NPM releases -- let's loop in @benbrown who is.

**Comment by ajwhite** [comment]
+1

We use continuous integration release flows and this would be very useful here. We can currently point to a specific commit hash, but it'd be more ideal to specify a major & minor and be able to receive newer patch versions while staying on a specific major/minor verison

**Comment by anonrig** [comment]
Closing it for now.

**Comment by ajwhite** [comment]
:point_up: this is not happening at this time then?
