### ISSUE TITLE
How to structure botkit project?

### ISSUE THREAD

**Issue by kevinsimper** [howdyai/botkit#570]
Really like the project! <3 

I would like to help with how to organize a botkit project. With express.js you can start a `express.Router()` that you can later mount as a middleware. 

There is middlewares in botkit, but not an easy way to take out functions and put them into other files.

**Comment by peterswimm** [comment]
Breaking out features more is a long term goal of Botkit, we hope to have some documentation around this, and more information about creating middleware soon.

**Comment by kevinsimper** [comment]
I am not talking about breaking out features, but making it possible to structure your project. I began to do it with our bot here
https://github.com/connectedcars/bender/blob/master/server.js#L21-L23

Because then I can also test it like this here
https://github.com/connectedcars/bender/blob/master/test.js

![image](https://cloud.githubusercontent.com/assets/1126497/21507123/fd79671a-cc75-11e6-97fa-7d5f5240c78a.png)

**Comment by benbrown** [comment]
We have a project underway to do this! Take a look here:

https://github.com/howdyai/botkit-starter-slack

**Comment by kevinsimper** [comment]
Seems cool! However I don't like the wrapping everything in `module.exports = function(){}`, it seems like a unconventional way of doing it.
