### ISSUE TITLE
Setting up interactive messages

### ISSUE THREAD

**Issue by musicaljoeker** [howdyai/botkit#572]
Hello,

I am trying to set up interactive messages with my Slackbot and in reading your documentation, I discovered that I needed to setup an interactive messages request URL on my slack app. My server lives at gemification.mio.uwosh.edu so the request URL would be https://gemification.mio.uwosh.edu/slack/receive, correct?

I have a certificate for SSL connection, but haven't yet set this up with botkit. Is there an easy way to install a certificate, or am I going to need to do this manually with another npm package?

Thanks!

**Comment by peterswimm** [comment]
As long as it is a functioning SSL server you should have to do any special config in botkit other than specifying the url.

**Comment by musicaljoeker** [comment]
Okay. If I had a certificate to use for the domain that I'm registered under, how would I go about installing these certificates to allow botkit to use them? I don't use express or any other server to make botkit run. Is there something in the setupWebserver function that I can use to install certificates?

Thanks for your help!

**Comment by peterswimm** [comment]
This part lives outside the botkit code and is part of your dev environment. If botkit is in a folder that can serve https content, everything should just *work*. If you are unsure about whether your schools hosting provides SSL, you should try running it locally using ngrok, or on gomix.

**Comment by musicaljoeker** [comment]
I am able to configure the server to my liking and have valid SSL certificates to allow https connections. Since I am using controller.setupWebserver, I don't have any other webserver running on this machine. Do I need to setup a separate web server with https that botkit runs inside to make this work?

**Comment by benbrown** [comment]
@musicaljoeker Yes, you will want to send your SSL traffic to a web server like nginx and proxy them through to the node app.

**Comment by musicaljoeker** [comment]
I've set up an nginx server listening for traffic on port 80 and 443 with a valid certificate. I've also set this server up to forward all traffic to port 2839 (I randomly picked this port). Now when I start botkit with the port parameter set to 2839, I get this error `Error: listen EADDRINUSE :::443`.

I'm guessing I'm getting this error because botkit and nginx are both trying to listen on port 443, which is HTTPS. Does anybody have a workaround for this?

**Comment by musicaljoeker** [comment]
Thanks for your help everybody. I was able to get interactive messages working by setting up an nginx server with valid SSL certificates and proxy porting all incoming traffic to a different port for botkit. Here is an article that helped me with the proxy porting part: https://www.ghostforbeginners.com/how-to-proxy-port-80-to-2368-for-ghost-with-nginx/
