### ISSUE TITLE
Doing anything in response to bot_message results in Illegal Argument

### ISSUE THREAD

**Issue by bellyjeans55** [howdyai/botkit#576]
I have
```
controller.hears('Test Notification', 'bot_message', function(bot,message)
    {
        console.log(JSON.stringify(message));
    });
```

When the bot posts "Test notification", botkit crashes with:

```
/root/botkit/node_modules/md5/md5.js:152
      throw new Error('Illegal argument ' + message);
      ^

Error: Illegal argument undefined
    at module.exports (/root/botkit/node_modules/md5/md5.js:152:13)
    at Object.<anonymous> (/root/botkit/lib/Studio.js:559:23)
    at Object.Botkit.botkit.trigger (/root/botkit/lib/CoreBot.js:972:49)
    at Object.<anonymous> (/root/botkit/lib/CoreBot.js:946:32)
    at Object.Botkit.botkit.trigger (/root/botkit/lib/CoreBot.js:972:49)
    at Object.<anonymous> (/root/botkit/lib/SlackBot.js:668:34)
    at Object.Botkit.botkit.trigger (/root/botkit/lib/CoreBot.js:972:49)
    at /root/botkit/lib/CoreBot.js:1076:32
    at Object.bot.findConversation (/root/botkit/lib/Slackbot_worker.js:685:9)
    at /root/botkit/lib/CoreBot.js:1072:21
```

**Comment by bellyjeans55** [comment]
md5.js seems to get that the message is null, which is weird because my JSON.stringify(message) prints it out exactly as I would expect (ie not null), so the callback function is definitely receiving the message properly.

**Comment by samadsajanlal** [comment]
did you find any solution? i'm trying to do the same thing here, basically have my bot listen to an incoming webhook for some text. if text is present, do some processing, otherwise gloss it over

**Comment by samadsajanlal** [comment]
Adding @benbrown since I saw he mentioned this event type in another thread, perhaps he can weigh in here?

**Comment by dachev** [comment]
+1

**Comment by bfujii** [comment]
the problem appears to be that it attempts to create and md5 of message.user. a webhook sends the data as a bot, you are listening for a bot_message so this seems to be verified:

the offending code from lib/Studio.js, second line in stack trace.:

>        controller.on('heard_trigger', function(bot, keywords, message) {
>             var data = {
>                 type: 'heard_trigger',
>                 user: md5(message.user), <--------
>                 channel: md5(message.channel),
>                 bot_type: bot.type,
>             };

a sample message from a webhook

> { text: 'xxx',
>   bot_id: 'xxx',
>   type: 'message',
>   subtype: 'bot_message',
>   team: 'xxx',
>   channel: 'xxx',
>   event_ts: '1503881088.000117',
>   ts: '1503881088.000117',
>   match: 
>    [ 'x',
>      'x',
>      'x',
>      'x',
>      index: 0,
>      input: 'text' ] }
> debug: channels.info { channel: 'xxx',
>   token: '<redacted>' }

vs a sample message from a user:

> { type: 'message',
>   channel: 'xxx',
>   user: 'xxx',
>   text: 'xxx',
>   ts: '1503880869.000078',
>   source_team: 'xxx',
>   team: 'xxx',
>   event: 'ambient',
>   match: 
>    [ 'xxx',
>      'xxx',
>      'xxx',
>      'xxx',
>      index: 0,
>      input: 'xxx' ] }


i simply appended a || message.bot_id and it seems to be working.

the comment in Studio.js above this is:

> /* Every time a bot spawns, Botkit calls home to identify this unique bot
>   * so that the maintainers of Botkit can measure the size of the installed
>   * userbase of Botkit-powered bots. */


it appears this is purely for stats and the userid is md5 hashed for privacy (?). i think sending the bot_id is sufficient and seems to solve the problem.

>         controller.on('heard_trigger', function(bot, keywords, message) {
>             var data = {
>                 type: 'heard_trigger',
>                 user: md5(message.user || message.bot_id),
>                 channel: md5(message.channel),
>                 bot_type: bot.type,
>             };
>             controller.trigger('stats:heard_trigger', message);
>             return statsAPI(bot, {
>                 method: 'post',
>                 form: data,
>             }, message);
>         });

**Comment by bfujii** [comment]
alternatively, you can add this to your botkit config

> stats_optout: true
