### ISSUE TITLE
The URL couldn't be validated. Response does not match challenge "<numbers>".

### ISSUE THREAD

**Issue by mofodox** [howdyai/botkit#577]
Hi,

I'm experiencing the callback URL issue created by Heroku. Based on my research on this issue is that the problem is the verify token. But I checked and my verify token setup correctly. I included my access token and verify in the .env file. When I tried running ```heroku local``` and it works locally. I've tested using ```page_token=<MY PAGE TOKEN> verify_token=<MY_VERIFY_TOKEN> node bot.js https://url-name.herokuapp.com/facebook/receive``` and it works too. But whenever I save the callback URL settings on Facebook, it gives the error message as mentioned on the title above.

Anyone can help me verify this? 

Here's the [screenshot](https://cl.ly/2f2h0o3E1e07) to the error message. Let me know if you need more from me.

Thank you!

**Comment by robbawebba** [comment]
Hi @mofodox! Could you include your source code, or a link to your repository, so I can have a better understanding of how you're trying to connect with Facebook?

**Comment by manhcuong2903** [comment]
i have same issue up there. 
here is my code 
<?php

define('VERIFY_TOKEN', '<secret code app>');

$method = isset($_SERVER['REQUEST_METHOD']) ? $_SERVER['REQUEST_METHOD'] : null;

if ($method == 'GET' &&  isset($_GET['hub_mode']) == 'subscribe' && isset($_GET['hub_verify_token']) == VERIFY_TOKEN  && isset($_GET['hub_challenge'])) {
        var_dump($method);
        echo $_GET['hub_challenge'];
        exit;
}
else{
}

**Comment by manhcuong2903** [comment]
i have same issue up there. 
here is my code 
<?php

define('VERIFY_TOKEN', '<secret code app>');

$method = isset($_SERVER['REQUEST_METHOD']) ? $_SERVER['REQUEST_METHOD'] : null;

if ($method == 'GET' &&  isset($_GET['hub_mode']) == 'subscribe' && isset($_GET['hub_verify_token']) == VERIFY_TOKEN  && isset($_GET['hub_challenge'])) {
        var_dump($method);
        echo $_GET['hub_challenge'];
        exit;
}
else{
 $updates = json_decode(file_get_contents("php://input"), true);
        print_r($updates);
}            
and one more thing can i ask what "verify_token" we put on Verify Token when create webhook on facebook??? thanks

**Comment by manhcuong2903** [comment]
i have same issue up there.
here is my code


define('VERIFY_TOKEN', 'secret app');

 $method = isset($_SERVER['REQUEST_METHOD']) ? $_SERVER['REQUEST_METHOD'] : null; 

if ($method == 'GET' && isset($_GET['hub_mode']) == 'subscribe' && isset($_GET['hub_verify_token']) == VERIFY_TOKEN && isset($_GET['hub_challenge'])) { 
var_dump($method); 
echo $_GET['hub_challenge'];
 exit; } 
else{ 
$updates = json_decode(file_get_contents("php://input"), true); 
print_r($updates); 
} 

and one more thing can i ask what "verify_token" we put on Verify Token when create webhook on facebook??? thanks

**Comment by mofodox** [comment]
Hi @robbawebba, here's the link to my [source code](https://github.com/mofodox/KaiBot/blob/master/bot.js)

**Comment by gameboyll** [comment]
Similar problem here! [source](https://github.com/gameboyll/FB-Bot/blob/master/index.js)

**Comment by jimmiebtlr** [comment]
Any word on this?  Seeing it at the moment.  A coworker has had the same code working, so would seem most likely something funky machine/exact version dependent.

**Comment by desokroshan** [comment]
Any updates on this. I too am getting the same error. There is another thread with same issue but even that is unresolved.

**Comment by alshaikh1** [comment]
has anyone got this fixed?

**Comment by jonchurch** [comment]
If like the poster youre running on heroku, set the env variables in the heroku configuration panel.

**Comment by F-Makhokha** [comment]
Im running to the same issue,  has anyone gone through the same problem?, how did you guys fix this

The URL couldn't be validated. Response does not match challenge, expected value="1060150785", received="\"1060150785\""

**Comment by peterswimm** [comment]
Closing with @jonchurch's answer
