### ISSUE TITLE
[Question] Relation between tag and npm version?

### ISSUE THREAD

**Issue by k-kawa** [howdyai/botkit#581]
The latest tag in this repository is `v0.4.2` but the latest version on the [npm]( https://www.npmjs.com/package/botkit) is `v0.4.6` now.
What is the best way to know the relation between the tags and npm version?

**Comment by peterswimm** [comment]
You can always verify the latest version of botkit by checking the [changelog](https://github.com/howdyai/botkit/blob/master/changelog.md). The latest version is indeed 0.4.6.
