### ISSUE TITLE
Send message on behalf of the user not reply from the bot.

### ISSUE THREAD

**Issue by colus001** [howdyai/botkit#583]
An app such as giphy doesn't send gif as bot user but the requested user himself. I'm making an app similar to giphy. One of my user complains about not being able to delete the image because the person has no right. I've looked through the documentation and couldn't find it.

It would be great this feature is supported by botkit.

**Comment by peterswimm** [comment]
Does the user have admin privledges? If they do they should be able to delete the message in slack.
