### ISSUE TITLE
Deploy Botkit for Messenger Bot by using Claudia.js (for AWS Lambda)

### ISSUE THREAD

**Issue by TLevesque** [howdyai/botkit#584]
Hi, does anyone deployed successfully Botkit on AWS Lambda with Claudia.js?
Does it work well? Did you succeed to keep on using MongoDB over DynamoDB? 
Any step by step method or advice are really welcomed!! 
Thanks,
Thibaut

**Comment by macroramesh6** [comment]
huh,  I had the same question. From my knowledge. Botkit runs on expressjs which keep using process in the backend. But lambda has the timeout. But yes we can combine Claudia and bootkit from the core. will get help from someone.

**Comment by alecl** [comment]
Yeah, botkit could have an AWS API Gateway based middleware routing to Lambda functions instead of Express in theory.

**Comment by alecl** [comment]
Can even do the oauth

Connect with OAuth enabled services (like social networks) without any servers.
https://www.linkedin.com/pulse/connect-oauth-enabled-services-like-social-networks-without-van-dijk

https://www.authlete.com/documents/article/custom_authorizer

**Comment by TLevesque** [comment]
Hey Alec, thanks a lot for your help!! 
Did you experienced already to deploy Botkit on Lambda with middleware?
If you have any snippet of code to illustrate or just a simple example of this, it will be really welcomed!! ;)
Thanks!

**Comment by alecl** [comment]
Purely academic experience reading things. I haven't had an opportunity to
try anything yet. Sadly, I've posted all I know so far. :)

On Tue, Jan 10, 2017 at 10:38 AM, Thibaut Levesque <notifications@github.com

**Comment by cesarvarela** [comment]
Any news about this? i think this would require conversations to be stateless.

**Comment by nkhine** [comment]
perhaps this could be useful https://github.com/localytics/lambda-slack-router and you store the states in dynamodb as detailed https://github.com/markhobson/emojibot

**Comment by JadyLiu** [comment]
Same questions as above, how can I use Botkit to integrate with api gateway, e.g. to POST data to lambda function from slack outgoing webhook ?

**Comment by eubruno** [comment]
I think Botkit does not support this. When you restart the server it loses the conversation, so if you put in a service that responds to events he will always "restart"

**Comment by jonchurch** [comment]
Conversations need to be persisted in a db to do serverless, that is if you
want to use conversations as they are currently implemented.

A lot of apps (for fb at least) can easily be built using buttons that
deliver a specific payload that is received by botkit as a message (using
`receive_interactive: true`) to trigger the next step in a conversation. If
you have an interaction that does a lot of user text parsing, this might
not be right for you. But this is a way around the conversation structure
of botkit.

Youd then setup an api gateway that posted the fb data to your
handleWebookPayload function, which would trigger whatever event was
appropriate, and then handle it via controller.hears for the specific
payload you are receiving.

This is theoretical stuff for me too currently, will be testing this soon
and get back to yall.

**Comment by devhaoy** [comment]
I think @jonchurch is referring to receive_via_postback:true config if we re talking Messenger . Receive_interactive is for Slack bots
