### ISSUE TITLE
Botkit architecture?

### ISSUE THREAD

**Issue by anderson-martin** [howdyai/botkit#588]
https://github.com/howdyai/botkit/blob/master/slack_bot.js
I have used the above example of Botkit (It's the simplest one). It's nice and I would like to present it to  my teacher but I need to get more info about  it's architecture and how it works . So, I can develop it further too. Where & how can I get info about the architecture of Botkit (especially that example)?

**Comment by boriscosic** [comment]
Can you be more specific as to architecture of, hosting, development, integration, etc? The example in your post is based on Slack RTM which is documented here https://api.slack.com/rtm. This report is also a good start for overall architecture https://github.com/howdyai/botkit-starter-slack. I've used something along the lines of this example https://github.com/howdyai/botkit/blob/master/examples/slackbutton_incomingwebhooks.js which utilized built in botkit server for oauth, interactive messages and commands.
