### ISSUE TITLE
Having a CONTRIBUTING.md

### ISSUE THREAD

**Issue by anonrig** [howdyai/botkit#59]
There is a great example that folks at atom/electron are using.

https://github.com/atom/electron/blob/master/CONTRIBUTING.md

We can use a similar methodology for submitting both pull requests and issues/bugs

**Comment by RafaelCosman** [comment]
@anonrig great point, we totally need this. Can you submit a pull-request with what you think would be a good ```CONTRIBUTING.md``` for our repo?
