### ISSUE TITLE
Reply not working on('file_shared') for slack bot user

### ISSUE THREAD

**Issue by colus001** [howdyai/botkit#594]
What I did is

```
controller.on('file_shared', (bot, message) => {
  console.log('file_shared', _.keys(bot).join(','));
  bot.reply(message, 'Do you want to keep this file?');
});
```

log shows

```
file_shared type,botkit,config,utterances,api,identity,configureIncomingWebhook,sendWebhook,configureRTM,closeRTM,destroy,startRTM,identifyBot,identifyTeam,startPrivateConversation,startConversation,createConversation,_startDM,send,replyAcknowledge,replyPublic,replyPublicDelayed,replyPrivate,replyPrivateDelayed,replyInteractive,reply,startTyping,replyWithTyping,replyAndUpdate,findConversation,say,team_info,rtm,msgcount
```

but reply function is not working. show nothing. maybe due to some bugs?
doesn't throw error without any notice it just do nothing.

**Comment by colus001** [comment]
```
{ message:
   { type: 'file_shared',
     file_id: '...',
     user_id: '...',
     file: { id: '...' },
     event_ts: '1484233039.418105' },
```

I found out that message.. is not actually message. it is

**Comment by robbawebba** [comment]
Try looking for the `message_received` event and check to see if the message has a type  of `file_shared`. I don't think Botkit has an event called `file_shared`

**Comment by colus001** [comment]
@robbawebba Well, your suggestion was kind of working. But I have another problem. With `.on` you can not use `startConversation` to give some questions about the file. 

```
info: [Start]  0  Task for  undefined in undefined
info: >   [Start]  0  Conversation with  undefined in undefined
```

**Comment by robbawebba** [comment]
I just looked at previous issues and noticed #428 might have your answer. You might be looking for the `file_share` event, not Slack's `file_shared` event (the difference is the `d`) 😄

**Comment by peterswimm** [comment]
@colus001 did the above help?

**Comment by colus001** [comment]
@peterswimm I've been away from the project for a while. So I'll reopen if I encounter same situation. Thanks for the support.
