### ISSUE TITLE
A web based messenger library?

### ISSUE THREAD

**Issue by znat** [howdyai/botkit#599]
I am working on a web-based chat bot.  It's easy to make a basic Socket.io bot from Botkit's `ConsoleBot.js` but I was wondering is someone knew about an good open source web-based messenger library?

**Comment by pandubalraj** [comment]
Hi Znat,
Me too expecting the same to integrate the ConsoleBot.js in web based client.

**Comment by robertturrall** [comment]
Just bumping this thread - anybody found anything or did you carry on and build your own solution using socket.io and ConsoleBot? 

Thanks for any tips,
Robert

**Comment by gcfabri** [comment]
What is the basic structure you @znat use with Botkit and socket.io together?

**Comment by benbrown** [comment]
There is now an official effort to bring Botkit to the web!

See here: https://github.com/howdyai/botkit/issues/871
