### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by anonrig** [howdyai/botkit#60]
Well it's that time of open source projects. Again. :-1: 

"ws" can be updated from ^0.8.1 to ^1.0.0 (Installed: none, Latest: 1.0.0)
"tape" can be updated from ^4.2.2 to ^4.4.0 (Installed: none, Latest: 4.4.0)

I've added this issue to discuss on the projects' changelogs

**Comment by RafaelCosman** [comment]
@anonrig thanks for bringing this up. I'm working on this now.

**Comment by RafaelCosman** [comment]
I tested this with ```demo_bot.js``` to check that nothing breaks.
