### ISSUE TITLE
Responds with 401 unauthorised on /login when using verification token

### ISSUE THREAD

**Issue by osh123** [howdyai/botkit#601]
Setting up the controller with a Slack verification token, like this:

`    controller.createWebhookEndpoints(controller.webserver, ["xxxx"]);
`
Makes botkit responds with 401 for requests to /login.

**Comment by havardthom** [comment]
I encountered this issue today, was the fix applied?

**Comment by peterswimm** [comment]
@nishant-chaturvedi ?

**Comment by nishant-chaturvedi** [comment]
Noticed that, this issue is still present, made the fix and opened the PR https://github.com/howdyai/botkit/pull/1203
