### ISSUE TITLE
Conversations are very slow

### ISSUE THREAD

**Issue by musicaljoeker** [howdyai/botkit#603]
Hello,
I am writing a bot that starts a conversation with the user. Along the line there are a few SQL calls.

The slowness occurs after the 3rd time I add a new admin. I'm _fairly_ certain that I'm not doing convo.next() until all async tasks are finished. However I am nesting two convo.ask. Could that cause the problem?

You'll see in the screenshot below that the lag is up to 10 minutes for the conversation to respond.
![screen shot 2017-01-18 at 2 32 29 pm](https://cloud.githubusercontent.com/assets/5824820/22081909/258f2a98-dd8b-11e6-9c52-c09f2e0ccd8b.png)

Anyone have any ideas on what it could be?

**Comment by musicaljoeker** [comment]
Does anybody know if there is a different rate limit to Slack for users.list? My console log hangs on this line, then doesn't respond back to the user: info: ** API CALL: https://slack.com/api/users.list.

For some strange reason, it if another user interacts with the bot, then it responds to me. Any help would be greatly appreciated on this. I'm really at a loss.

Thanks!

**Comment by ls-ashvitha-sridharan** [comment]
Hey @musicaljoeker I'm experiencing the same issue. How were you able to debug/understand the issue? Thank you for you help :)
