### ISSUE TITLE
Support for FB postbacks as a conversation response

### ISSUE THREAD

**Issue by sbehrends** [howdyai/botkit#604]
While creating a conversation for Facebook Messenger, after creating a conversation, the response is only catched if the user replies with some text, but a postback does not trigger the conversation reply.

Is this a bug or a future improvement?

```

controller.hears(['START_CONVERSATION'], 'facebook_postback', (bot, message) => {
  bot.startConversation(message, function(err, convo) {
    convo.ask({
      attachment: {
          type:"template",
          payload:{
            template_type:"generic",
            elements: [{
              title: "Press Yes or No",
              buttons:[{
                type:"postback",
                title:"Yes 😀",
                payload:"SAID_YES"
              },
              {
                type:"postback",
                title:"No 😔",
                payload:"SAID_NO"
              }]
            }]
          }
        }
      }
    }, (response,convo) => {

      // Except to receive either SAID_YES or SAID_NO
      // Only receives "text" (if user writes), no postbacks
      console.log(response)
    })
  })
})
```

**Comment by wingliu0** [comment]
I'm going to patch this by myself

**Comment by joekh** [comment]
I am facing the same issue :), any updates on this?

**Comment by jonchurch** [comment]
`receive_via_postback: true` is what youre looking for
Goes into your controller like so
```
var controller = Botkit.facebookbot({
access_token: process.env.access_token,
verify_token: process.env.verify_token,
receive_via_postback: true,
})
```
Checkout the [facebook botkit docs](
https://github.com/howdyai/botkit/blob/master/readme-facebook.md) for more
info

**Comment by mhjb** [comment]
Here's a working link: https://github.com/howdyai/botkit/blob/master/docs/readme-facebook.md

**Comment by peterswimm** [comment]
in @jonchurch 's defense it worked when he posted it :D I edited his post on his behalf.
