### ISSUE TITLE
Botkit Studio Stats error

### ISSUE THREAD

**Issue by makstaks** [howdyai/botkit#606]
I was reviewing my logs and noticed this error:

> Error in Botkit Studio Stats: { Error: socket hang up 
> Jan 18 19:20:04 healthybot app/web.1:      at createHangUpError (_http_client.js:254:15) 

I'm not familiar with how Botkit Studio works and I don't have an account. How do fix this error?

**Comment by benbrown** [comment]
Did this issue persist for more than a few seconds?

**Comment by makstaks** [comment]
@benbrown it persisted for 5 minutes (Jan 18 19:20:03 PST - Jan 18 19:25:23 PST)

**Comment by peterswimm** [comment]
Hello @makstaks it sounds like an error with Botkit Statistics: https://github.com/howdyai/botkit/blob/master/readme.md#botkit-statistics-gathering

Thank you for the timestamp, we will take a look into it!

**Comment by makstaks** [comment]
thanks @peterswimm, the issue is creating too much noise in my logs, so I opted out.

**Comment by benbrown** [comment]
Can you please share some of the log output that you saw? It will help us identify the source of this issue.

**Comment by makstaks** [comment]
@benbrown sorry, should have done that in the beggining

```
Feb 01 18:41:13 healthybot app/web.1:  Error in Botkit Studio Stats: { Error: socket hang up 
Feb 01 18:41:13 healthybot app/web.1:      at createHangUpError (_http_client.js:254:15) 
Feb 01 18:41:13 healthybot app/web.1:  Error in Botkit Studio Stats: { Error: socket hang up 
Feb 01 18:41:13 healthybot app/web.1:      at createHangUpError (_http_client.js:254:15) 
Feb 01 18:41:13 healthybot app/web.1:  Error in Botkit Studio Stats: { Error: socket hang up 
Feb 01 18:41:13 healthybot app/web.1:      at createHangUpError (_http_client.js:254:15) 
Feb 01 18:41:13 healthybot app/web.1:  Error in Botkit Studio Stats: { Error: socket hang up 
Feb 01 18:41:13 healthybot app/web.1:      at createHangUpError (_http_client.js:254:15) 
Feb 01 18:41:13 healthybot app/web.1:  Error in Botkit Studio Stats: { Error: socket hang up 
Feb 01 18:41:13 healthybot app/web.1:      at createHangUpError (_http_client.js:254:15) 
Feb 01 18:41:13 healthybot app/web.1:  Error in Botkit Studio Stats: { Error: socket hang up 
Feb 01 18:41:13 healthybot app/web.1:      at createHangUpError (_http_client.js:254:15) 
Feb 01 18:41:13 healthybot app/web.1:  Error in Botkit Studio Stats: { Error: socket hang up 
Feb 01 18:41:13 healthybot app/web.1:      at createHangUpError (_http_client.js:254:15) 
Feb 01 18:41:13 healthybot app/web.1:  Error in Botkit Studio Stats: { Error: socket hang up 
```

**Comment by k001** [comment]
What is the status of this?

**Comment by benbrown** [comment]
This issue was resolved a while ago. It was related to an outage on the server responsible for the anonymous usage stats we collect.
