### ISSUE TITLE
Unexpected token < in JSON at position 0 

### ISSUE THREAD

**Issue by thierryskoda** [howdyai/botkit#615]
Hi all, 

Anyone knows what this error could be ? 

```Error in Botkit Studio Stats: SyntaxError: Unexpected token < in JSON at position 0 ```

I received this error twice today? It seems random because I've sent over 3k messages and I only had it 2 times.

Thanks for any help!

**Comment by peterswimm** [comment]
This sounds like an error with Botkit statistics gathering:
https://github.com/howdyai/botkit/blob/master/readme.md#botkit-statistics-gathering

Would you mind sharing the timestamp of when this occurred?
