### ISSUE TITLE
Back dependency forces node <=0.12.x

### ISSUE THREAD

**Issue by garyjohnson** [howdyai/botkit#619]
Back dependency was added at 4b22dac4bd6acd2233d72fc50ff5b705f9485793, which requires <=0.12.x for node. I haven't been able to update my botkit dependency because of it.

**Comment by peterswimm** [comment]
Since versions below that have been EOL'd by the maintainers of Node, I dont think you will see this change anytime soon. You can always pull from Github, and maintain it outside NPM if you need to support very old services.

**Comment by garyjohnson** [comment]
@peterswimm <=0.12.x means I can't use newer versions of node, 4.x-7.x.

**Comment by peterswimm** [comment]
Aha I misread you! I will ask our team to verify and fix!
