### ISSUE TITLE
Put extra storages out of the botkit

### ISSUE THREAD

**Issue by tilap** [howdyai/botkit#62]
Hi,

I'm happy to see the 0.0.5 release (not tagged?) with many other storages.
However, most of them need extra packages (monk, ...) that are not is the botkit package.json file.

So when installing, it does not work.
And if you had them all in the botkit package.json, it will install lots of useless packages.

What about keeping only the "jfs" as default (light) and move the others in other npm packages like _botkit-storage-mongo_, _botkit-storage-redis_ and so on?

**Comment by robguilfoyle** [comment]
Would it make sense to ship with a REST storage and a local store, then bring the others in as packages?

**Comment by RafaelCosman** [comment]
@robguilfoyle That sounds reasonable too.

@tilap and @robguilfoyle, I've been discussing this with @benbrown and it seems like a good move. Major kudos to either of you if create the ```botkit-storage-*``` npm packges!

**Comment by anonrig** [comment]
We're moving all of the storages into seperate repositories. 

Thank you for your response!

**Comment by christophehurpeau** [comment]
:+1:
