### ISSUE TITLE
TypeError: Cannot set property 'channel' of undefined

### ISSUE THREAD

**Issue by DAlperin** [howdyai/botkit#626]
I am just a beginner but when I start with some simple data persist it breaks at this code:
`controller.hears(['Whats my name'],['direct_message','direct_mention','mention'],function(bot,message) {
controller.storage.teams.get(message.user, function(err, name){
bot.reply('your name is: '+ name);
});
});`

My version: 0.4.9
Mac version: 10.12.1

The error is 
info: ** No persistent storage method specified! Data may be lost when process shuts down.
debug: Setting up a handler for spawned
debug: Setting up a handler for heard_trigger
debug: Setting up a handler for command_triggered
debug: Setting up a handler for remote_command_end
info: ** Setting up custom handlers for processing Slack messages
debug: Setting up a handler for message_received
info: ** Using simple storage. Saving data to ./data
info: ** Setting up custom handlers for processing Slack messages
info: ** API CALL: https://slack.com/api/rtm.start
notice: ** BOT ID: slacky ...attempting to connect to RTM!
notice: RTM websocket opened
/Users/dovalperin/Documents/SlackBot/node_modules/botkit/lib/Slackbot_worker.js:568
        msg.channel = src.channel;
                    ^

TypeError: Cannot set property 'channel' of undefined
    at Object.bot.reply (/Users/dovalperin/Documents/SlackBot/node_modules/botkit/lib/Slackbot_worker.js:568:21)
    at /Users/dovalperin/Documents/SlackBot/index.js:47:5
    at /Users/dovalperin/Documents/SlackBot/node_modules/jfs/lib/Store.js:211:20
    at /Users/dovalperin/Documents/SlackBot/node_modules/jfs/lib/Store.js:100:16
    at tryToString (fs.js:425:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:412:12)

**Comment by jonchurch** [comment]
Bot.reply requires you pass the source message as the first argument, this
error is telling you that its missing the channel to send the response to,
which it pulls off the source message. Try this!

bot.reply(message, 'your name is' + name);

**Comment by DAlperin** [comment]
Ok so now it is not crashing but it is saying: your name is: [object Object]

**Comment by jonchurch** [comment]
Try console.log('this is the name object', name) before your reply

Storage returns a whole user object, so likely you need name.name (at least
since youre calling the user object sent back from storage 'name')

You are trying to print a whole object as a string, likely you will need to
access a key of name that holds the name.

**Comment by DAlperin** [comment]
Thank you for dealing with my beginner junk. I am closing this now... THANK YOU SO MUCH

**Comment by jonchurch** [comment]
No problem! Was there myself not long ago at all!
