### ISSUE TITLE
More robust handling of Slack API requests

### ISSUE THREAD

**Issue by slambdin1** [howdyai/botkit#627]
According to their docs...

`Callers should always check the value of the ok params in the response.`

Therefore, even if you make a request and it returns `200`, it isn't guaranteed that you will receive a JSON object that you expect. It would be nice to see this reflected in the `call_api` method [here](https://github.com/howdyai/botkit/blob/master/lib/SlackBot.js#L387).

**Comment by peterswimm** [comment]
This has been handled https://github.com/howdyai/botkit/pull/387
