### ISSUE TITLE
Convo only sends the first message

### ISSUE THREAD

**Issue by thierryskoda** [howdyai/botkit#628]
Botkit version: 0.4.9

Hi, I have a Facebook messenger bot and I can't figure out why but my conversation are not working anymore. 

Everytime I want to start a new conversation like this: 

```
const startConvo = (err, convo) => {
    convo.say('hi')
    convo.say('hello')
}

bot.startConversation(message, startConvo)
```

Only the `convo.say('hi')` is sent. I was on 0.4.2 and it was working before and now that I'm on 0.4.9 it's not. I also added `receive_via_postback: true` in my controller' setting

Thank you for any help!

**Comment by thierryskoda** [comment]
Oh nevermind I think it's because I had his : `require_delivery: true` in my controller's setting

**Comment by jonchurch** [comment]
Next time try using createConversation if you run into this issue again. It
is the same as startConversation, but does not start sending the messages
until you call convo.activate()

**Comment by thierryskoda** [comment]
Do you have an easy use case in mind of why I should use `createConversation` ? I mean, I always want my message to go right away no?

**Comment by jonchurch** [comment]
Yeah! For things that are async, or your data isnt available until later
down a callback nest. You can create a conversation object, pass it around,
modify it, and then only activate it once you are ready.

EG you need to populate the weather from a seperate api, create the
conversation object, modify it, customize it, and only activate the convo
once your data arrives from your external weather api

**Comment by thierryskoda** [comment]
OH smart! I was always fetching my data first and than starting my convo yeah. But what does this improve other than making code look cleaner? My flow is always straight forward. A question after a question, so creating it before will not improve anything no?

**Comment by jonchurch** [comment]
Its up to you. Botkit isnt very opinionated on these things. No hard fast
rules, as long as youre getting things done, carry on :wink:

**Comment by thierryskoda** [comment]
👍
