### ISSUE TITLE
Too many references to Slack even when explaining generic topics

### ISSUE THREAD

**Issue by jay-at-avido** [howdyai/botkit#633]
As I'm reading thru the docs I keep seeing references to Slack in parts of the documentation that are just trying to explain generic botkit functionality such as skills. 

These slack references are distracting if you are not supporting Slack on  your bot, so it would be nice to remove them altogether.

**Comment by peterswimm** [comment]
Good comment, we are planning a refactoring of the documents to better reflect the platform a user may be using depending on where they decide to start working on their bot. 

Historically we started all docs as slack focused, but in the future you will probably just pick from a number of getting started guides that have platform specific examples.
