### ISSUE TITLE
I can't see my own console logs, even when debug is set to true

### ISSUE THREAD

**Issue by wamoyo** [howdyai/botkit#635]
This just makes it difficult to debug anything at all. I can't examine objects like `bot` and `message`.

Am I doing something wrong?

**Comment by wamoyo** [comment]
This simple example from the README doesn't work unless you're in a direct message conversation with the bot. 

> Simple reply example:
> 
> ```javascript
> controller.hears(['keyword','^pattern$'],['message_received'],function(bot,message) {
> 
>   // do something to respond to message
>   // ...
> 
>   bot.reply(message,"Tell me more!");
> 
> });
> ```
> 

Slack requires you to specify a channel: https://api.slack.com/methods/chat.postMessage#channels

I can't tell if botkit is doing that for me, or if I'm supposed to pull the incoming channel from the `bot` or `message` objects and send in back in the `reply` function parameters.

**Comment by jonchurch** [comment]
Reply takes a message as its source, and pulls the channel field off it.
What Events did you subscribe to? The example above will trigger for the
right keyword on any user message being received (hence the
'message_received') but that only applies to message events youve
subscribed to
The main ones are 'message.channel' for public channel messages and '
message.im' for private messages
Have you subscribed to messages.channel?

**Comment by wamoyo** [comment]
Well, hilariously enough, my code has a bunch of swear words, and replies with the words 'HR!'

It's just a silly test for now. We'll do more useful things after we have some fluency in making bots, I promise : )

**Comment by wamoyo** [comment]
@jonchurch So, I can't figure out how to subscribe my bot to a channel?

**Comment by jonchurch** [comment]
The bot has to be `/invite` to any particular channel you want it to listen to.

I was assuming you are using Events API, if you are then you can add bot permissions under Event Subscriptions in your app's settings http://api.slack.com/apps

**Comment by wamoyo** [comment]
Turns out I had already done that.

![shot](https://cloud.githubusercontent.com/assets/1170326/22601111/7810e41e-ea0b-11e6-95ad-a0ca2df165f2.png)

It still doesn't respond to 'message_received', sorry not really sure what's wrong here. I'm reviewed my code many times, in fact the code I copied straight from the botkit guide doesn't run either.

**Comment by jonchurch** [comment]
hmm try using `'ambient'` instead of `'message_received'`

**Comment by wamoyo** [comment]
Nope, it's just me sending out profanity all by my lonesome. Here's the stackoverflow question for this: http://stackoverflow.com/questions/41964205/slackbot-not-responding-to-message-received-event

**Comment by jonchurch** [comment]
I've had problems with `message_received` and don't use it with Slack anymore, I get more specific by using `'direct_message', 'direct_mention', 'mention', or 'ambient'`
you can combine them like so `['direct_message', 'mention', 'ambient']` which should work for you here.

**Comment by wamoyo** [comment]
@jonchurch No, that doesn't help. I want to make a bot that listens for profanity, and then sends out an alert when that happens, but my use case is just one use case.

The larger issue is that I can't log anything to my console to inspect things and debug.

**Comment by jonchurch** [comment]
Can you show me an example that demonstrates this issue?

There are no console.logs in the above code snippets

**Comment by jonchurch** [comment]
Does some of the code execute? You arent receiving a message from your bot correct?

**Comment by wamoyo** [comment]
Okay, cool! 

```javascript
kit.hears(
  ['poop', 'kaka', 'other-profanity'],
  ['message_received'],
  function (bot, message) {
    console.log('MY LOG', message)
    bot.reply(message, "HR! \n -burp- mmmm I luvz milk.")
  }
)
```

`MY LOG` never shows up, and neither does the the bot message. And, now it becomes obvious why the console log doesn't show up, the event's not firing. 

Baaahahahaa : )
