### ISSUE TITLE
Find out which user added bot to slack team and initiate a conversation

### ISSUE THREAD

**Issue by Billydubb** [howdyai/botkit#646]
Hi, when a user adds my bot to his team I would like to be able to find out who the user was that added the bot the the team, so that I can initiate a conversation with that user.

Is this currently supported in botkit? (The finding out who added my bot to the team part, I already know how to initiate a conversation)

In [this](https://github.com/howdyai/botkit-starter-slack/blob/master/components/onboarding.js) example there seems to be a `bot.config.createdBy` property, which doesn't seem to be there by default though, or am I missing something?

Regards

**Comment by nxz91** [comment]
@Billydubb found it: when you translate the code into a access_token during oauth, you also get a user_id. That's the user_id of the person who granted you access :-)
