### ISSUE TITLE
Send message from the server

### ISSUE THREAD

**Issue by TheDApact** [howdyai/botkit#650]
I need to send a message after a user opens (or better, after he closes) a webview in Messenger. How can I do this?

In facebook.js
```
webserver.get('/index', isLoggedIn, function(req, res){
            res.render('index.ejs',{
                    user : req.user 
                });
            req.on("end", function() {console.log("SEND A MESSAGE?"); });
```

**Comment by GautierT** [comment]
Maybe by broadcasting an event to your botkit controller ? 
I will try that. I need it too !

**Comment by ouadie-lahdioui** [comment]
Guys, you can do that with Messenger Extensions JS SDK, and Her's the [documentation](https://developers.facebook.com/docs/messenger-platform/webview/close)

**Comment by thierryskoda** [comment]
@ouadie-lahdioui The only problem with Messenger Extensions is that it only works for mobile devices no?

**Comment by ouadie-lahdioui** [comment]
According to some [people on internet](https://facebookfordevelopers.github.io/docs-zh_CN/docs/messenger-platform/messenger-extension/), messenger Extensions only work on iOS and Android, but i can't found the confirmation on Facebook docs

**Comment by jonchurch** [comment]
The docs say extensions work on iOS and Android, but not messenger.com (aka desktop user)

Fallback url is used when user is on desktop, in that case you aren't going to close a webview but redirect the user back to your bot's m.me url. Whatever logic you use for triggering a message at the same time as that would be pretty similar across extensions and desktop.

Right before webview close or desktop redirect, I'd make a POST request to a specific endpoint on your botkit server (sending the userID along so we know who to contact), which would then trigger a custom botkit event that would bot.say at that particular user.

**Comment by ouadie-lahdioui** [comment]
Ahaah :flushed:

@jonchurch +1 for your proposition

**Comment by jonchurch** [comment]
Actually on desktop its probably gonna open a tab, so a redirect wouldnt work likely.
