### ISSUE TITLE
Trigger bot response on URL click

### ISSUE THREAD

**Issue by devhaoy** [howdyai/botkit#652]
I need my bot to send user a message after he clicks a web-url type of button. How can I do this?

```
convo.ask({
  	      attachment: {
  	      type: 'template',
  	      payload: {
  	        template_type: 'button',
  	        text: 'Login',
  	        buttons: [
  	          {
  	            type: 'web_url',
  	            title: 'Log in with Facebook',
  	            url: process.env.app_host + '/auth/fb',
  	          }
  	        ]
  	      }
        }
    }, function(response, convo) {   
      convo.say('Thanks');
     convo.next()
 });
};
```

Here the function(response, convo) won't trigger. What should I change to subscribe to the event "user clicked the url button"?

**Comment by jonchurch** [comment]
Facebook doesn't currently support this. What are you seeking to do exactly?

Are you trying to trigger messages in response to user clicking on a
carousel image? That is not supported by fb yet =\

You could hack around it, by using a compact webview with some kind of
confirmation button that closes the webview and triggers a POST request to
a custom webhook or your api which would then trigger the response from
your bot.

**Comment by devhaoy** [comment]
Thanks @jonchurch , as I could not find a solution I did it the way you mentioned, by passing the user id as a query parameter in the URL, then starting a new convo from there.

**Comment by jonchurch** [comment]
Cool! I want this feature too, wish it would just send a request to a
server, which could send back html or just trigger an event.

**Comment by cAstraea** [comment]
Is this related to the account linking feature from messenger platform ?
