### ISSUE TITLE
Can I selectively drop messages?

### ISSUE THREAD

**Issue by ind1go** [howdyai/botkit#654]
I have a `hears(...)` function and I'd like to do a bit of filtering out of messages before I pass them on to Watson, based on message properties (rather than filtering based on keywords or patterns as is achievable through the first argument to `hears`).

To do this, I was going to add some middleware before Watson that just won't call `next()` unless it's a message it wants to pass on. However, I note that the documentation says you should always call `next()` to avoid memory leaks. Is there a way to get middleware to drop messages that it's not interested in?

**Comment by peterswimm** [comment]
https://github.com/howdyai/botkit/blob/master/docs/readme.md#convobeforethread

This is what the new beforethread hook is designed for, take a look!

**Comment by Naktibalda** [comment]
There are 2 documented ways to drop messages in documentation of watson middleware: https://github.com/watson-developer-cloud/botkit-middleware#message-filtering
