### ISSUE TITLE
[Slack] bot.close() outside of a controller method

### ISSUE THREAD

**Issue by JonnyBoy333** [howdyai/botkit#655]
Is it possible to interact with a bot object outside of controller event like controller.hears.

In my particular case I have a number of bots spawned by the controller but there are cases in my app where I need to close down one of those bots outside of an interaction in Slack. Ideally there would be some controller method that would return an instance of a bot based on the token or some other unique identifier of the bot. From that instance I could call bot.close() to close and destroy a specific bot.

I am using controller.storage so maybe there could be some tie in here to controller.storage.get(id, cb).

**Comment by jonchurch** [comment]
Can you share some code around where/when you are spawning bots? And how
you are persisting them?

Also, can you elaborate on when and why you need to destroy bots on demand?

Are you using the rtm api? There is an rtm.close method available.
Otherwise, if youre using events api, I dont think youd need to shutdown a
bot under normal use. There is no connection opened with events api.

**Comment by JonnyBoy333** [comment]
Yes, I am using the rtm bot so that I can use events like 'is typing.' Here is some code to illustrate the issue. It's using an express route that takes in an id and would ideally be able to shut down a bot that is associated with that id.

http://pastebin.com/XatFt1Tk

Couldn't get the code to format very well here so I put it on pastebin.

**Comment by jonchurch** [comment]
Pastebin is better for me viewing via email anyways 👍

What people often do for RTM bots is create a list of bots as they are
spawned.

var _bots = {};
function trackBot(bot) {
_bots[bot.config.token] = bot;
}

Call trackbot whenever you spawn a bot, and then lookup the bot object via
_bots[bot.config.token]

You can then call bot.closeRTM() to terminate the rtm connection.

**Comment by JonnyBoy333** [comment]
A yes, that does the trick. This is also helpful if you need to do something like bot.say outside of one of the controller events to send a message to a team. Thanks a million.
