### ISSUE TITLE
delete method is not required in custom storage 

### ISSUE THREAD

**Issue by davidwneary** [howdyai/botkit#658]
Not sure if this is an issue or a deliberate choice but it seems strange to me that custom storage options don't need to have a `delete` method. This just tripped me up when I was migrating from using simple storage (which has a delete method) and mongodb store. 

My use case is that when I get an `account_invalid` response when attempting to start an RTM connection I want to delete the team from my records since they have uninstalled the app.

**Comment by peterswimm** [comment]
https://github.com/howdyai/botkit/issues/682 duplicate of
