### ISSUE TITLE
bot.utterances do not match when in a Spark conversation

### ISSUE THREAD

**Issue by adamweeks** [howdyai/botkit#661]
While in a conversation with a spark bot, the pattern matching provided in the `bot.utterances` shortcut do not match successfully. This is because conversations only listen to direct_mention's and the first part of the message is the bot's user name. 

```js
convo.ask('Do you like cookies?' , [
  {
    pattern: bot.uttterances.yes,
    callback: function(response, convo) {
      convo.say('YES!');
      convo.next();
    }
  },
  {
    default: true,
    callback: function(response, convo) {
      convo.repeat();
      convo.next();
    }
  }]);
```

> me: @CookieBot Hi
> CookieBot: Do you like cookies?
> me: @CookieBot yes
> CookieBot: Do you like cookies?

The message data looks like this:
```js
{ original_message: 'CookieBot yes' }
```

It would be great if the `ask` pattern matching automatically ignored the bot mention in the message.

**Comment by benbrown** [comment]
This should be fixed!

**Comment by adamweeks** [comment]
Thanks!
