### ISSUE TITLE
bot.say attachment messages not sending for the first 4-5 tries, after that it's fine?

### ISSUE THREAD

**Issue by nomad5** [howdyai/botkit#666]
When the bot is started up, sending the first 4-5 attachment messages using bot.say won't go through, but after that they'll send every time no problem until the bot is restarted. Then the same process happens again.

It's also not a timing issue, I can run the bot and leave it for a few hours, it still needs those 4-5 attachment messages to go through before actually working.

I get `API CALL: https://slack.com/api/chat.postMessage info: **` every time, no errors I can see.

Non-attachment bot.say messages run instantly however, so no issues there.

Very confused. What could be the issue here?

**Comment by jonchurch** [comment]
It could be a malformed attachment, or slack doesnt like something about
it. I think slack has had some issues in the api this last week.

When did you start experiencing this?

**Comment by nomad5** [comment]
It started right when I began using attachments instead of simple text, which was a few months ago. So it could very well be something with my code. It's just very odd that it starts working perfectly after what I like to consider hitting it with a wrench a few times (forcing posts until it starts working).

```json
{
	"fallback" : "",
	"color" : "#fff",
	"author_name" : "",
	"author_icon" : "",
	"footer" : "",
	"footer_icon" : "",
	"mrkdwn_in" : [
		"pretext"
	]
}
```

This is a template I use for the attachment. The app fills in the values. Then  send the attachment to the channel using 

```javascript
slackBot.say({
            "attachments": [connectInfo],
            channel: slackGeneral // general channel
        });
```

**Comment by jonchurch** [comment]
I never use `bot.say` so maybe I'm wrong but I don't think you need attachments to be in json, It should parse it for you.

I've had weird things happen with attachments before, but never so consistently and stubbornly as you describe.

Is your function that fills the template dynamic? Is it possible something is happening there which is breaking a field on your attachment and slack is refusing it?

When you add `debug: true` to your controller's config options, you get a response from the chat.update logged to console after the `chat.postMessage` that should give you more info if slack is rejecting the message.

**Comment by nomad5** [comment]
The function is dynamic, but I'm using the exact same info each time and it eventually goes through. To be more specific, it's not exactly consistent, sometimes 2, 3, 4, 5, 6, 7, 8 times the same content will not post until it just does.

I checked debug and this is all that I get after the `chat.postMessage` : `debug: Got response null `

Very strange.

**Comment by jonchurch** [comment]
Hmm maybe its failing in sending the request, so the response comes back
null

Will take a closer look soon

**Comment by nomad5** [comment]
Much appreciated!

**Comment by jonchurch** [comment]
Anything change on this front for you @nomad5?

**Comment by nomad5** [comment]
Hey, thanks for checking back in. Unfortunately no. I recently changed up how I create the attachment object, while hoping that would solve the issue. It seems that it's pretty persistent.

**Comment by peterswimm** [comment]
Closing for now then!

**Comment by nomad5** [comment]
Out of nowhere, it seems as if the problem fixed itself. Same exact code and content. I'm assuming this has something to do with Slack's end of it. Hopefully it doesn't change!

Thanks for the help.

**Comment by peterswimm** [comment]
Reopening if this is still a problem.
