### ISSUE TITLE
How to enable a menu in Facebook bot?

### ISSUE THREAD

**Issue by razzza** [howdyai/botkit#668]
Hello
In the Facebook messenger window there is the option to have a menu right to the left on the text input chat box: https://developers.facebook.com/docs/messenger-platform/send-api-reference/generic-template

How can this menu be created/edited with botkit?
thanks!
R

**Comment by andreichch** [comment]
Hi,
It looks like you are interested in the persistent menu a.k.a. 'hambuger

Take a look at https://github.com/howdyai/botkit/blob/master/readme-facebook.md#facebook-specific-events if you will, and search for controller.api.thread_settings.menu

Hope this helps

**Comment by razzza** [comment]
thanks!

I did try but I get:
_controller.api.thread_settings.greeting('Hello! I\'m a Botkit bot!');
2017-02-21T19:17:28.997161+00:00 app[web.2]:               ^
2017-02-21T19:17:28.997163+00:00 app[web.2]: TypeError: Cannot read property 'thread_settings' of undefined_

I could eventually create the hamburger menu using a direct POST command detailed on FB developer page...however the controller.api from the botkit bot.js is still throwing above error...

**Comment by andreichch** [comment]
You are welcome :-) Are you using facebook_bot.js to create your bot? It has some skeleton code. It worked for me 'out of the box' first time, and it's quite easy to change it. I don't think you can just add FB-related code to botkit.js.

**Comment by razzza** [comment]
yes, I'm using the standard facebook_bot.js to setup the controller...strange then...

you're right :) I did not add any FB code...I've called the FB URL using a REST client, payload is detailed is: https://developers.facebook.com/docs/messenger-platform/thread-settings/persistent-menu
This did the trick.

**Comment by ouadie-lahdioui** [comment]
@razzza do you still have the same problem ?

**Comment by peterswimm** [comment]
Closing, seems resolved
