### ISSUE TITLE
How to send a timeout based reminder to user in the middle of conversation

### ISSUE THREAD

**Issue by tridib** [howdyai/botkit#671]
Here is my conversation flow:
1. Bot asked a question to user.
2. User did not respond for a minute.
3. Bot want to send a message to user asking if he is still interested to answer. Something like "Hey, are you still there?"

Is there a established  way to do it without loosing the conversation context?

**Comment by AdanTL** [comment]
```javascript
convo.setTimeout(60000 * 60);
convo.onTimeout(function(convo){
    convo.ask('Hey, are you still there');
    convo.next();
})
```
