### ISSUE TITLE
It's not possible install the last version from npm

### ISSUE THREAD

**Issue by estebancatanoe** [howdyai/botkit#676]
npm ERR! Unexpected token < in JSON at position 0
npm ERR! <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
npm ERR! <html><head>
npm ERR! <title>404 Not Found</title>
npm ERR! </head><body>
npm ERR! <h1>Not Found</h1>

**Comment by peterswimm** [comment]
Just verified that it is working on our end, can you explain the steps you are doing to get the above error?

**Comment by estebancatanoe** [comment]
Sorry, it's a problem with npm in my machine, I test in other and the installation is correct. Thanks
