### ISSUE TITLE
no option to turn off default 'Initializing Botkit vXXX' message

### ISSUE THREAD

**Issue by mysticflute** [howdyai/botkit#687]
Version 0.5.1

CoreBot.js has a line that always logs to the console:

console.log('Initializing Botkit v' + botkit.version());

I think this should either use botkit.log, or there should be a config option to turn it off.

**Comment by JoshuaKlassen** [comment]
Has anybody started to look into this? I would like to take a crack at it

**Comment by JoshuaKlassen** [comment]
I have created a PR for this: #703
