### ISSUE TITLE
Error install botKit

### ISSUE THREAD

**Issue by Rhaniel** [howdyai/botkit#698]
Hello guys, I'm trying to install botkit, but it always gives a bug, could anyone help me?

<code>npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config -
-get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:211:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:192:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:890:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:334:1
1)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:189:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:501:12)
npm WARN addRemoteGit  git://github.com/ianwremmel/extend-error.git resetting re
mote C:\Users\rcborges\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ian
wremmel-extend-error-git-024938ae because of error: { Error: Command failed: git
 -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:211:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:192:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:890:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:334:1
1)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:189:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:501:12)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.ori
gin.url' }
npm ERR! git clone --template=C:\Users\rcborges\AppData\Roaming\npm-cache\_git-r
emotes\_templates --mirror git://github.com/ianwremmel/extend-error.git C:\Users
\rcborges\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ianwremmel-exten
d-error-git-024938ae: Cloning into bare repository 'C:\Users\rcborges\AppData\Ro
aming\npm-cache\_git-remotes\git-github-com-ianwremmel-extend-error-git-024938ae
'...
npm ERR! git clone --template=C:\Users\rcborges\AppData\Roaming\npm-cache\_git-r
emotes\_templates --mirror git://github.com/ianwremmel/extend-error.git C:\Users
\rcborges\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ianwremmel-exten
d-error-git-024938ae: fatal: unable to connect to github.com:
npm ERR! git clone --template=C:\Users\rcborges\AppData\Roaming\npm-cache\_git-r
emotes\_templates --mirror git://github.com/ianwremmel/extend-error.git C:\Users
\rcborges\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ianwremmel-exten
d-error-git-024938ae: github.com[0: 192.30.253.113]: errno=No error
npm ERR! git clone --template=C:\Users\rcborges\AppData\Roaming\npm-cache\_git-r
emotes\_templates --mirror git://github.com/ianwremmel/extend-error.git C:\Users
\rcborges\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ianwremmel-exten
d-error-git-024938ae: github.com[1: 192.30.253.112]: errno=No error
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\rcborges\\AppDat
a\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.5.0
npm ERR! npm  v4.3.0
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\rc
borges\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.c
om/ianwremmel/extend-error.git C:\Users\rcborges\AppData\Roaming\npm-cache\_git-
remotes\git-github-com-ianwremmel-extend-error-git-024938ae
npm ERR! Cloning into bare repository 'C:\Users\rcborges\AppData\Roaming\npm-cac
he\_git-remotes\git-github-com-ianwremmel-extend-error-git-024938ae'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.253.113]: errno=No error
npm ERR! github.com[1: 192.30.253.112]: errno=No error
npm ERR!
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\rcborges\AppData\Roaming\npm-cache\_logs\2017-03-08T15_08_
13_729Z-debug.log
</code>

**Comment by peterswimm** [comment]
It looks like git/npm is hosed on your machine, can you try reinstalling those or fixing them and try again?

**Comment by Rhaniel** [comment]
I tried this, but it did not work. I'm using proxy, can that be it?

**Comment by peterswimm** [comment]
Mostly likely! You'd need to make sure the proxy allows access to all the services mentioned in the error above, or use a starter kit to run it on gomix or heroku.

**Comment by frangarcia** [comment]
I am having the same problem. Just in case to fix the issue, it is trying to connect to 192.30.253.113 and 192.30.253.112, which returns a non valid certificate issue when accessing via a browser.

**Comment by peterswimm** [comment]
Both those errors indicate its failing on your private network. You should work with your proxy admin to allow access to Github and NPM.

**Comment by frangarcia** [comment]
I do think I have fully access to github and npm. It is the first time I have this kind of problems.

**Comment by peterswimm** [comment]
You can also skip the NPM install and download a zip directly from the Github if your network is blocking NPM.

**Comment by Rhaniel** [comment]
I tried this, downloaded the file directly from Github and executed npm install, but it still does not work

**Comment by peterswimm** [comment]
Getting beyond the scope of this project, but you might need to check out:
https://github.com/arei/npmbox

**Comment by peterswimm** [comment]
But I think if you are in restrictively proxied environment, you are going to keep running into connection issues all the way down. I would resolve those issues instead of trying workarounds.

**Comment by ddemented** [comment]
I ran into the same exact error when installing:
npm install --save botkit
PS: It may be due to proxy but other packages seem to install fine with npm install, so not sure where the problem is.

**Comment by Rhaniel** [comment]
Comigo acontece a mesma coisa, quando eu executo: 
npm install botkit-middleware-watson --save
Funciona normalmente, o erro só ocorre com: 
npm install --save botkit

**Comment by Rhaniel** [comment]
The same thing happens to me when I execute:
Npm install botkit-middleware-watson --save
It works normally, the error only occurs with:
Npm install --save botkit

**Comment by peterswimm** [comment]
Are you able to clone other github projects on your machine, per your logs it seems like your proxy is blocking git commands.

**Comment by ddemented** [comment]
i guess it is a problem with proxy, i used a vpn connection and i could run the command fine..

**Comment by Rhaniel** [comment]
Eu resolvi o problema ao executar : <code>npm config set proxy http://user:pass@domain:port</code>
