### ISSUE TITLE
bot.say does not work with # prefixed channel name

### ISSUE THREAD

**Issue by metoikos** [howdyai/botkit#7]
When you try to send a message to channel with # prefixed channel name nothing is happening. 
```
bot.say({
    text: "Hello World!",
    channel: "#random"
});
```
Instead of # prefixed channel name, when you try with channel id everything works great.

```
bot.say({
    text: "Hello World!",
    channel: 'C0XXXXXXX'
});
```

**Comment by ben-stover** [comment]
Please try it again but with single quotes like: '#random' instead of double quotes - but keep text double quoted. Thanks

**Comment by ben-stover** [comment]
Has your bot been allowed into the # prefixed channel?

**Comment by tonythomson** [comment]
I believe this is a documentation error; `bot.say()` uses the RTM API, which expects a channel ID.

**Comment by ZuzooVn** [comment]
@metoikos What's your development environment?

**Comment by metoikos** [comment]
Hello @ZuzooVn 
OS X El Capitan

```bash
➜  ~  uname -a
Darwin rocko 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64
➜  ~  node --version
v4.2.2
```

**Comment by ZuzooVn** [comment]
I can not build the source code with 

`➜  ~  uname -a
Darwin hostname.local 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64`

`➜  ~   node --version
v5.0.0`

**Comment by metoikos** [comment]
I installed with `npm install botkit` command.
It generates some errors but it's not related to botkit, it is bufferutil issue. You can check out at issue https://github.com/howdyai/botkit/issues/2

**Comment by anonrig** [comment]
@metoikos How do you learn the channel id?

**Comment by tonythomson** [comment]
We've drifted off-topic from the issue... @benbrown Any plans for a chatroom/forum/email list?

@anonrig A list of current channel IDs is available from the [channel list API](https://api.slack.com/methods/channels.list), but it's probably better to just use the data you get from the bot's initial connection to RTM, and then keep that list up to date. You can edit the file `Slackbot_worker.js` (see line 75 or so) to have the bot cache different data sets for the Slack team to which you're connecting (e.g. users, channels, IMs, etc.)

**Comment by benbrown** [comment]
@tonythomson There is an open slack room waiting for you!! http://dev4slack.xoxco.com/ We've already got a botkit channel open and active.

**Comment by metoikos** [comment]
@anonrig it's already in documentation.
```javascript
bot.api.channels.list({},function(err,response) {
})
````

I've created simple solution for that, loading both users and channels on bot boot-up.

```javascript
var fullTeamList = [];
var fullChannelList = [];
controller.spawn({
    token: config.get("slack_bot_key")
}).startRTM(function (err, bot) {
    if (err) {
        throw new Error(err);
    }

    // @ https://api.slack.com/methods/users.list
    bot.api.users.list({}, function (err, response) {
        if (response.hasOwnProperty('members') && response.ok) {
            fullTeamList = [];
            var total = response.members.length;
            for (var i = 0; i < total; i++) {
                var member = response.members[i];
                fullTeamList.push({name: member.name, id: member.id});
            }
        }
    });

    // @ https://api.slack.com/methods/channels.list
    bot.api.channels.list({}, function (err, response) {
        if (response.hasOwnProperty('channels') && response.ok) {
            fullChannelList = [];
            var total = response.channels.length;
            for (var i = 0; i < total; i++) {
                var channel = response.channels[i];
                fullChannelList.push({name: channel.name, id: channel.id});
            }
        }
    });
});
````

**Comment by PrajaktaNaik** [comment]
How do I get the current channel name in which my bot is replying to the user.

**Comment by jsullivanlive** [comment]
@PrajaktaNaik I had the same question today and here's how I did it (you'll want to cache it since it hits the api):

```
    controller.hears(['test'], ['direct_message', 'mention'],  (bot, message) => {
        bot.api.channels.info({channel: message.channel}, (e, r) => {
            if (r && r.ok) bot.reply(message, 'channel name: ' + r.channel.name)
        })
    })
```
