### ISSUE TITLE
What is the purpose of Task Class

### ISSUE THREAD

**Issue by wingliu0** [howdyai/botkit#700]
I'm currently using botkit for developing facebook bot. 
In this case, each user will start a Task and a Conversation together. 
The Task and Conversation will then be destroyed together. 
I dont quite understand the meaning of building the Task Class

Can any of the contributors answer me? =[

**Comment by jonchurch** [comment]
The task starts the conversation. Conversations live within tasks, tasks "tick" and deliver messages from their active conversations. 

I think at some point there was more distinction between tasks and conversations, and it was a separation of concerns thing, but now I think tasks are mostly deprecated, and Tasks are now 1:1 with a Conversation. 

It isn't something that you need to touch directly.

**Comment by wingliu0** [comment]
haha, since I need some more advance usage of botkit, so I dug into it's source and modify a bit for my usage. I personally hate the ticking mechanism. Apart from this, botkit is awesome

**Comment by jonchurch** [comment]
As in you want all messages to send instantly or you just dont want to see
the tick in your logs?

**Comment by wingliu0** [comment]
@jonchurch I don't like ticking while waiting user to reply (eg convo.ask)
