### ISSUE TITLE
Platform support: RecastAI

### ISSUE THREAD

**Issue by rainmakerho** [howdyai/botkit#705]
Hi,
   is possible using bot-connector in botkit ? 
https://github.com/RecastAI/bot-connector

thanks.

**Comment by ouadie-lahdioui** [comment]
Hello @rainmakerho, 

You cannot do that, Botkit doesn't support recastBotConnector.

**Comment by peterswimm** [comment]
Of course nothing is impossible, if someone wanted to submit a PR request.
