### ISSUE TITLE
Install Help Wanted

### ISSUE THREAD

**Issue by Ronin11** [howdyai/botkit#706]
Im getting an error in npm install, it seems that the extend-error repo wont install for some reason. It does exist, but the build is failing. Is there a work around for this?

Heres the error:
npm ERR! git clone --template=/Users/nate.ashby/.npm/_git-remotes/_templates --mirror git://github.com/ianwremmel/extend-error.git /Users/nate.ashby/.npm/_git-remotes/git-github-com-ianwremmel-extend-error-git-024938ae: Cloning into bare repository '/Users/nate.ashby/.npm/_git-remotes/git-github-com-ianwremmel-extend-error-git-024938ae'...
npm ERR! git clone --template=/Users/nate.ashby/.npm/_git-remotes/_templates --mirror git://github.com/ianwremmel/extend-error.git /Users/nate.ashby/.npm/_git-remotes/git-github-com-ianwremmel-extend-error-git-024938ae: fatal: read error: Operation timed out

**Comment by peterswimm** [comment]
Is this the result of an NPM install command? Do you connect via a proxy or firewall?

**Comment by Ronin11** [comment]
I was on a business network, and I took my machine home and it worked like a champ from there. TIL network security includes preventing devs from getting github repos.

**Comment by peterswimm** [comment]
Heh glad to hear that cleared things up!
