### ISSUE TITLE
JSON file store won't work

### ISSUE THREAD

**Issue by agseco** [howdyai/botkit#708]
Hi,

If I configure Botkit to use `json_file_store` I get the following error:

```
    at /Users/cyf/dev/workspaces/bots/pip/bots/volaris/node_modules/jfs/lib/Store.js:209:15
    at ReadFileContext.callback (/Users/cyf/dev/workspaces/bots/pip/bots/volaris/node_modules/jfs/lib/Store.js:94:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)
```

I have tried to manually create the file it expects with the desired content and it doesn't fails when reading it, but it seems to have no content; then when trying to save, it fails again with a similar error.

Anyone else experiencing a similar issue?

Cheers.

----

* Botkit version: 0.4.9
* OS: OS X 10.9
* Node version: v6.9.3

**Comment by jonchurch** [comment]
Can you include the full error please?

**Comment by peterswimm** [comment]
Any update on this? Still seeing trouble?

**Comment by agseco** [comment]
I haven't experienced the issue again because I wrote my own storage provider.

I have just switched to use Botkit's storage to test it and this is the full error I get:

´´´
2017-05-02T08:07:56.202Z - error:  Error: could not load data
    at /Users/cyf/dev/workspaces/bots/pip/bots/volaris/node_modules/jfs/lib/Store.js:209:15
    at ReadFileContext.callback (/Users/cyf/dev/workspaces/bots/pip/bots/volaris/node_modules/jfs/lib/Store.js:94:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:359:13)
´´´

I'm getting this error in the following context:

- DB empty/clean
- Trying to find a document (getting by key)
- The document might not exist

Thought: may this be caused by the fact that the document doesn't exist yet?

**Comment by Naktibalda** [comment]
> may this be caused by the fact that the document doesn't exist yet?

I experienced the same issue when making changes in watson-middleware.
`storage.users.get` returns error if record does not exist in storage yet.

**Comment by Abgaryan** [comment]
@peterswimm  I have the same issue

**Comment by peterswimm** [comment]
I'm not sure I understand, but you are on the right path in creating your own storage provider, the botkit one is a simple implementation that probably will not work for all users depending on their needs.
