### ISSUE TITLE
Wit.ai receive bot messages 

### ISSUE THREAD

**Issue by AdanTL** [howdyai/botkit#711]
Hi everyone, I got this code

> smarthandler = function(response,convo){
  if(response.text !== 'NOTICIAS_PAYLOAD'){
    wit.message(response.text, {})
      .then((data) => {
        console.log('Yay, got Wit.ai response: ' + JSON.stringify(data));
        console.log('Yay, got Wit.ai response: ' + data.entities);
        if(data.entities.hasOwnProperty('saludo')){
          convo.say('hi');
        }else if(data.entities.hasOwnProperty('noticias')){
          elegirtema(convo);
        }else if(data.entities.hasOwnProperty('suscripcion')){
          suscripcion(convo);
        }else{
          convo.say('No he entendido lo que dices, prueba con \"noticias\"')
        }
      })
      .catch(console.error);
  }
}

As you can see, I'm not using middleware cause I only want to use it a few times.

The issue: I receive bot messages too. Why?

Feel free to criticize my crappy code :)

**Comment by ouadie-lahdioui** [comment]
Hello @AdanTL,

When you call smarthandler ?

Can you put more (formated) code to allow us understand when you call you function !

**Comment by AdanTL** [comment]
```javascript
smarthandler = function(response,convo){
  //if para que no entren los los payload ni las conversaciones del bot, para no ensuciar wit.ai
  if(['NOTICIAS_PAYLOAD','ONBOARDING_PAYLOAD','SUSCRIPCION_PAYLOAD','FUNCIONAMIENTO_PAYLOAD']
.indexOf(response.text) === -1 && !response.is_echo){
    wit.message(response.text, {})
      .then((data) => {
        console.log('Yay, got Wit.ai response: ' + JSON.stringify(data));
        console.log('Yay, got Wit.ai response: ' + data.entities);
      })
      .catch(console.error);
  }
}
```

Sorry for the delay, here is how I fix it. A little explanation before:
I use smarthandler function to try to recognize intent in unexpected responses so I send de convo response to wit to try it. The problem was, bot responses also went to wit because bot conversation goes through the function too messing my wit inbox.

My fix:
I realized that bot responses have a boolean is_echo so I filtered all messages with it :)

**Comment by ouadie-lahdioui** [comment]
Good to hear that you fix it 👍
