### ISSUE TITLE
How to restart conversation

### ISSUE THREAD

**Issue by Rhaniel** [howdyai/botkit#712]
Guys I'm using the IBM Watson conversation to integrate with my SlackBot. When the user says something to my bot like "Goodbye!", It responds as desired and identifies a "goodbyes" intent, what I want is that when I identify this case my bot restarts the conversation so the user can interact Again from the beginning of the conversation flow. Can anybody help me?

**Comment by Rhaniel** [comment]
My code 

<code>slackController.hears(['.*'], ['direct_message', 'direct_mention', 'mention'], function(bot, message) {</code>
 <code> slackController.log('Slack message received');</code>
  <code>middleware.interpret(bot, message, function(err) {</code>
  <code>  console.log(message);</code>
  <code>  if (!err){</code>
  <code>    if(message.watsonData.intents[0].intent != 'goodbyes'){</code>
       <code> bot.reply(message, message.watsonData.output.text.join('\n'));</code>
   <code>   }else{</code>
     <code>   bot.reply(message, message.watsonData.output.text.join('\n'));</code>
       
   <code>//I want to end here and come back to restart the conversation if the user types "Hi" for example.</code>
<code>                            }</code>
<code>                    }</code>
<code>          });</code>
<code>});</code>

**Comment by jonchurch** [comment]
What are you experiencing that isnt workinf? Are you looking to pause the
convo and come back to where you were before?

Or just run it again from the beginning?

Also if bears to say you arent using a botkit conversation here, at least
in the code provided.
In the code provided youre catching all input with the wildcard, so it
certainly would trigger if the user said hi, and run whatever logic is in
that event handler.

**Comment by Rhaniel** [comment]
I want just run it again from the beginning

**Comment by sageexplorer** [comment]
Add a return statement after this =>
if(message.watsonData.intents[0].intent != 'goodbyes'){
bot.reply(message, message.watsonData.output.text.join('\n'));
return;
}

**Comment by juanpablo64** [comment]
how does that even resolve anything?
