### ISSUE TITLE
Consolebot - Convo not working

### ISSUE THREAD

**Issue by alxpereira** [howdyai/botkit#714]
Hi guys,

I'm trying to make run a simple convo from your examples with the `lib/consolebot` but it fails to reply to me on the `convo.say`

The `convo.ask` after the `startConversation` runs well, the callback is well fired, but nothing happens on the `say` triggering the next reply. 

Any idea ? 
Alex

**Comment by alxpereira** [comment]
Actually, i've found the issue. 
You forgot to call the callback on the `worker.send` method : 

```
bot.send = function(message, cb) {
     cb() // was missing to complete the sending in core.js
     console.log('BOT:', message.text);
};
```

**Comment by peterswimm** [comment]
Would you mind submitting a PR to fix the example?
