### ISSUE TITLE
groups.replies, im.replies missing

### ISSUE THREAD

**Issue by joseym** [howdyai/botkit#715]
It seems as tho only `channels.replies` are currently supported.

https://github.com/howdyai/botkit/blob/3b175b68cc5cdf6ae7e9d075cfefcd697a8ed965/lib/Slack_web_api.js#L38

However, the slack web api also has methods for `groups.replies` and `im.replies`.

**Comment by benbrown** [comment]
I merged your PR. It'll make it into the next version published to NPM.
