### ISSUE TITLE
How can I receive attachements that a user sent to my bot to store on my server?

### ISSUE THREAD

**Issue by MagSag** [howdyai/botkit#717]
I don't understand how can I receive attachements(especially images) that a user send to my bot from facebook messenger. Does facebook send the url of the image or the image itself to my bot. If the url the how can I get the saved on my server(because I may need the image to be avaible on my app if the user doesn't use my messenger bot). 

For instance this is a message which comes from the user with attachement, How can I have the attachement saved on my server?
controller.on('message_received', function(bot, message) {
    bot.reply(message, 'Hey there.');
});
I can say what can really help me is to decorticate the parameter message of the event.

**Comment by devhaoy** [comment]
This will do the job

```
var fs = require('fs'); // write/read file on server
// Listen to user's message
controller.on('message_received', function(bot, message) {
  // Check for an attachment
  if(message.attachments) {
    // Check for an image
    if(message.attachments[0].type == 'image') {
      console.log('CONTROLLER RECEIVED AN IMAGE WITH URL ' + message.attachments[0].payload.url);
      // Assign the image URL to a variable
      var receivedImageUrl = message.attachments[0].payload.url;
      // Download the image to your server
      var download = function(uri, filename, callback) {
        request.head(uri, function(err, res, body){
          console.log('content-type:', res.headers['content-type']);
          console.log('content-length:', res.headers['content-length']);
          request(uri).pipe(fs.createWriteStream(filename)).on('close', callback);
        });
      };
      //Here the image is downloaded to ./tmp and named MYIMAGE
      download(receivedImageUrl, '/tmp/MYIMAGE.jpeg', function(body){
      // do something with the image
    });
    }
  }
});
```

**Comment by devhaoy** [comment]
Yes the images are publicly available via their Facebook URL, but I m not too sure how long for. For permanent use you might need to store them somewhere, though I can't tell for sure. For image management I'd recommend you check Cloudinary which has a large free tier + allow you to do plenty of cool things with the images via their API

**Comment by MagSag** [comment]
That's true, I am planning to use Google App Engine for my project. Thanks.
