### ISSUE TITLE
How to use an Express web server alongside BotKit for Facebook Messenger.

### ISSUE THREAD

**Issue by MagSag** [howdyai/botkit#718]
It seems like the example project given in the read me for this purpose doesn't work with the lastest botkit and doesn't support the all facebook api features from what I read on the submitted issue.

I would like to use express.js to build my bot using botkit; the problem is I don't know how to proceed. At first I was thinking to use express I will just have to install it in my botkit project and use it as normal node.js app and that's all; but from the same issue,  it sounds like to have botkit project work with express there a lot to configure, which I don't know how to do.

How I can use express with botkit(lastest version and all facebook api features supported )?

**Comment by peterswimm** [comment]
What errors are you seeing using the example with the latest botkit? We should probably get that fixed rather than find you a workaround!

**Comment by MagSag** [comment]
The packages that the demo project is using are all old (botkit 0.2 yet now it is on 0.5) and seeing the packages.json I don't think they are supposed to be updated. So Is there any other example of using botkit with express?

And also I don't know where exactly to put my code in the server.js file, there is no clear explaination or example of code(botkit functions usage for example).

**Comment by peterswimm** [comment]
These should be updated now
