### ISSUE TITLE
Bug: Using Events API on message.im throws an uncaughtException

### ISSUE THREAD

**Issue by slambdin1** [howdyai/botkit#719]
### Stack Trace
```
error: uncaughtException: Cannot read property 'replace' of undefined 
{ date: 'Mon Mar 20 2017 09:25:59 GMT-0400 (EDT)',
  process: 
   {...},
  trace: 
   [ { column: 84,
       file: '/Users/shannenlambdin/Documents/Whitewater/forks/cogsworth-bot/node_modules/botkit/lib/SlackBot.js',
       function: '',
       line: 650,
       method: null,
       native: false },
     { column: 49,
       file: '/Users/shannenlambdin/Documents/Whitewater/forks/cogsworth-bot/node_modules/botkit/lib/CoreBot.js',
       function: 'Object.Botkit.botkit.trigger',
       line: 986,
       method: 'Botkit.botkit.trigger',
       native: false },
     { column: 32,
       file: '/Users/shannenlambdin/Documents/Whitewater/forks/cogsworth-bot/node_modules/botkit/lib/CoreBot.js',
       function: null,
       line: 1091,
       method: null,
       native: false },
     { column: 9,
       file: '/Users/shannenlambdin/Documents/Whitewater/forks/cogsworth-bot/node_modules/botkit/lib/Slackbot_worker.js',
       function: 'Object.bot.findConversation',
       line: 751,
       method: 'bot.findConversation',
       native: false },
     { column: 21,
       file: '/Users/shannenlambdin/Documents/Whitewater/forks/cogsworth-bot/node_modules/botkit/lib/CoreBot.js',
       function: null,
       line: 1087,
       method: null,
       native: false },
     { column: 27,
       file: '/Users/shannenlambdin/Documents/Whitewater/forks/cogsworth-bot/node_modules/ware/lib/index.js',
       function: 'next',
       line: 82,
       method: null,
       native: false },
     { column: 18,
       file: '/Users/shannenlambdin/Documents/Whitewater/forks/cogsworth-bot/node_modules/wrap-fn/index.js',
       function: null,
       line: 121,
       method: null,
       native: false },
     { column: 13,
       file: '/Users/shannenlambdin/Documents/Whitewater/forks/cogsworth-bot/lib/user-info-middleware.js',
       function: 'bot.api.users.info',
       line: 12,
       method: 'api.users.info',
       native: false },
     { column: 28,
       file: '/Users/shannenlambdin/Documents/Whitewater/forks/cogsworth-bot/node_modules/botkit/lib/Slack_web_api.js',
       function: 'Request._callback',
       line: 235,
       method: '_callback',
       native: false },
     { column: 22,
       file: '/Users/shannenlambdin/Documents/Whitewater/forks/cogsworth-bot/node_modules/request/request.js',
       function: 'Request.self.callback',
       line: 188,
       method: 'self.callback',
       native: false } ],
  stack: 
   [ 'TypeError: Cannot read property \'replace\' of undefined',
     '    at Object.<anonymous> (/Users/shannenlambdin/Documents/Whitewater/forks/cogsworth-bot/node_modules/botkit/lib/SlackBot.js:650:84)',
     '    at Object.Botkit.botkit.trigger (/Users/shannenlambdin/Documents/Whitewater/forks/cogsworth-bot/node_modules/botkit/lib/CoreBot.js:986:49)',
     '    at /Users/shannenlambdin/Documents/Whitewater/forks/cogsworth-bot/node_modules/botkit/lib/CoreBot.js:1091:32',
     '    at Object.bot.findConversation (/Users/shannenlambdin/Documents/Whitewater/forks/cogsworth-bot/node_modules/botkit/lib/Slackbot_worker.js:751:9)',
     '    at /Users/shannenlambdin/Documents/Whitewater/forks/cogsworth-bot/node_modules/botkit/lib/CoreBot.js:1087:21',
     '    at next (/Users/shannenlambdin/Documents/Whitewater/forks/cogsworth-bot/node_modules/ware/lib/index.js:82:27)',
     '    at /Users/shannenlambdin/Documents/Whitewater/forks/cogsworth-bot/node_modules/wrap-fn/index.js:121:18',
     '    at bot.api.users.info (/Users/shannenlambdin/Documents/Whitewater/forks/cogsworth-bot/lib/user-info-middleware.js:12:13)',
     '    at Request._callback (/Users/shannenlambdin/Documents/Whitewater/forks/cogsworth-bot/node_modules/botkit/lib/Slack_web_api.js:235:28)',
     '    at Request.self.callback (/Users/shannenlambdin/Documents/Whitewater/forks/cogsworth-bot/node_modules/request/request.js:188:22)' ] }
```

### Cursory Search: `SlackBot.js line 648`
Bot's identity has not been populated because an RTM connection hasn't been started
```
var mentionSyntax = '<@' + bot.identity.id + '(\\|' + bot.identity.name.replace('.', '\\.') + ')?>';
```

![Sad Panda](https://media.giphy.com/media/Kzb1zdtLHcKti/giphy.gif)

**Comment by ihorrusi** [comment]
checkout function `slack_botkit.findAppropriateTeam` in `SlackBot.js line 190 ` you can see in `line 208` bot's identity populates 
`identity.name` should be in your team storage
{
  id: '',
  ...
  bot:{
    id: '',
    name: '',
   ...
  }
}

**Comment by airlikidh2** [comment]
I have the same error:
`TypeError: Cannot call method 'replace' of undefined
    at Object.<anonymous> (/var/lib/openshift/56f067092d52717977000068/app-root/runtime/repo/node_modules/botkit/lib/SlackBot.js:668:85)
    at Object.Botkit.botkit.trigger (/var/lib/openshift/56f067092d52717977000068/app-root/runtime/repo/node_modules/botkit/lib/CoreBot.js:988:49)
    at /var/lib/openshift/56f067092d52717977000068/app-root/runtime/repo/node_modules/botkit/lib/CoreBot.js:1096:32
    at Object.bot.findConversation (/var/lib/openshift/56f067092d52717977000068/app-root/runtime/repo/node_modules/botkit/lib/Slackbot_worker.js:751:9)
    at /var/lib/openshift/56f067092d52717977000068/app-root/runtime/repo/node_modules/botkit/lib/CoreBot.js:1092:21
    at next (/var/lib/openshift/56f067092d52717977000068/app-root/runtime/repo/node_modules/ware/lib/index.js:82:27)
    at Ware.run (/var/lib/openshift/56f067092d52717977000068/app-root/runtime/repo/node_modules/ware/lib/index.js:88:3)
    at Object.Botkit.botkit.receiveMessage (/var/lib/openshift/56f067092d52717977000068/app-root/runtime/repo/node_modules/botkit/lib/CoreBot.js:1087:35)
    at handleEventsAPI (/var/lib/openshift/56f067092d52717977000068/app-root/runtime/repo/node_modules/botkit/lib/SlackBot.js:295:30)
    at /var/lib/openshift/56f067092d52717977000068/app-root/runtime/repo/node_modules/botkit/lib/SlackBot.js:231:24`

Any luck on fixing this?

**Comment by airlikidh2** [comment]
Update2:

Old botkit storage of a TEAM as a JSON:
```
{"id":"T0xxxxxxxx","createdBy":"Uxxxxxxxx","url":"https://xxxxxxxx.slack.com/","name":"xxxxxxx",
"bot":{
    "token":"xxxx-xxxxxxxxxxxxxxxxxxxxxxxxxx",
    "user_id":"Uxxxxxxxx",
    "createdBy":"Uxxxxxxxx"},
    "token":"xxxx-xxxxxxxxxxxxxxxxxxxxxxxxxx"}
```

Botkit storage as of today as a JSON:
```
{"id":"T0xxxxxxxx","createdBy":"Uxxxxxxxx","url":"https://xxxxxxxx.slack.com/","name":"xxxxxxx","state":"botkit",
"bot":{
    "token":"xxxx-xxxxxxxxxxxxxxxxxxxxxxxxxx",
    "user_id":"U12A8787K",
    "createdBy":"U0V0Z67A4",
    "app_token":"xxxx-xxxxxxxxxxxxxxxxxxxxxxxxxx",
    "name":"xxxxxxxx"},
    "token":"xxxx-xxxxxxxxxxxxxxxxxxxxxxxxxx"}
```

If you notice, the name field has been added and is being used in SlackBot.js.
If you are using an old token, it means that it will throw the `undefined ` error.

Either we have to make our user renew their token which seems like a pain in the b***.
Or we need to make a condition in SlackBot.js that takes both OLD and NEW team JSON in the storage.

Hope it makes sense. I'll try to work on it today.

**Comment by airlikidh2** [comment]
Alright, so small fix for right now:

I just added this `name: team.bot.name || 'name_of_your_bot'` at the line 221 of SlackBot.js

```
        slack_botkit.findAppropriateTeam(payload, function(err, team) {
            if (err) {
                slack_botkit.log.error('Could not load team while processing webhook: ', err);
                return;
            } else if (!team) {
                // if this is NOT a slack app, it is ok to spawn a generic bot
                // this is only likely to happen with custom slash commands
                if (!slack_botkit.config.clientId) {
                    bot = slack_botkit.spawn({});
                } else {
                    return;
                }
            } else {
                // spawn a bot
                bot = slack_botkit.spawn(team);

                // Identify the bot from either team storage or identifyBot()
                bot.team_info = team;

                // The bot identity is only used in handleEventsAPI during this flow
                // Recent changes in Slack will break other integrations as they no longer
                // require a bot and therefore Slack won't send the bot information.
                if (payload.type === 'event_callback') {

                    if (!team.bot) {
                        slack_botkit.log.error('No bot identity found.');
                        return;
                    }

                    bot.identity = {
                        id: team.bot.user_id,
                        name: team.bot.name || 'name_of_your_bot'
                    };
                }
            }
```

**Comment by ihorrusinko** [comment]
> Either we have to make our user renew their token which seems like a pain in the b***.
> Or we need to make a condition in SlackBot.js that takes both OLD and NEW team JSON in the storage.

@airlikidh2 it's not a problem update team info, you can write some migration script for each bot in your storage

```
 bot.api.rtm.start({
            no_unreads: true,
            simple_latest: true,
        }, function(err, res) {
            bot.identity = res.self;
            bot.team_info = res.team; 
            //todo update team storage     
        }
)
```

**Comment by slambdin1** [comment]
I don't think this an issue with how we were storing previously and how it is being stored now.

Our Botkit version has been bumpted to 0.5.2, and I ran locally (with a clean DB). After I installed the bot, and received a `message.im` event, I receive the error I originally reported.

**Comment by slambdin1** [comment]
I've been testing, and I have _always_ gotten a user field back from Slack's API. I've gone through the code and logged everything. What's frustrating is that right before `slack_botkit.storage.teams.save(team, cb)` is called on line 338 of SlackBot.js, the team has the correct name in the `bot.name` field. For some reason, when saving, it is not saved to the DB.

**Comment by airlikidh2** [comment]
I did not have any problem on my side since my fix.
Maybe the Storage middleware for the DB is not doing a proper job?

I'm using the JSON storage.

**Comment by slambdin1** [comment]
This is happening in both JSON storage and Cloudant. I've looked more into it, and I found the issue.  It is _not_ related to Slack's API.

Our app hooks into the `create_team` event and updates the DB. There is a race condition where after botkit does `auth.test` and updates the DB with the `name` field and when we update the DB. It's happening where we will fetch the team record, botkit updates the DB, and then we update the DB thinking we have the most up to date information. But it's sporadic since it's a race condition.

https://github.com/howdyai/botkit/blob/master/lib/SlackBot.js#L572
^In the above function, you need to properly use `async` and trigger the events after you have successfully updated the DB and done everything you needed to do.

**Comment by peterswimm** [comment]
Anyone still seeing this problem on the current version? Its been a while!

**Comment by pauldariye** [comment]
@peterswimm I this error I'm getting is related to it.


<img width="697" alt="screen shot 2018-01-12 at 13 56 30" src="https://user-images.githubusercontent.com/3650761/34890583-7819359e-f7a0-11e7-82bf-556ecdc04e7f.png">

**Comment by peterswimm** [comment]
@pauldariye are you using the latest version of botkit? Can you post a link to the code that triggers this error?
