### ISSUE TITLE
Connect botkit in bot framework

### ISSUE THREAD

**Issue by Rhaniel** [howdyai/botkit#729]
I am new to botkit and would like to connect my bot with the bot framework ... When I am going to register a bot in the bot framework it asks for an endpoint, I do not know how to get this endpoint, if someone can help me I would be very grateful.

I'll put my code to help:

<code>require('dotenv').load();</code>

<code>var express = require('express');</code>
<code>var Botkit = require('botkit');</code>
<code>var middleware = require('botkit-middleware-watson')({</code>
<code>  username: process.env.CONVERSATION_USERNAME,</code>
 <code> password: process.env.CONVERSATION_PASSWORD,</code>
<code>  workspace_id: process.env.WORKSPACE_ID,</code>
 <code> version_date: '2017-02-07'</code>
<code>});</code>

// Configure your bot
<code>var slackController = Botkit.slackbot({</code>
   <code> require_delivery: true,</code>
  });</code>

<code>var nome = "";</code>
<code>var slackBot = slackController.spawn({</code>
 <code> token: process.env.SLACK_TOKEN</code>
<code>}).startRTM();</code>

<code>slackController.hears(['.*'], ['direct_message', 'direct_mention', 'mention'], function(bot, message) {</code>
 <code> slackController.log('Slack message received');</code>
  <code>middleware.interpret(bot, message, function(err) {</code>
    <code>if (!err){</code>
      <code>//NÃO É GOODBYE E INDENTIFICOU UMA INTENÇÃO</code>
    <code>  if(!(typeof message.watsonData.intents[0] == "undefined")){</code>
        //Impressora
        

        switch(message.watsonData.intents[0].intent){
          case 'Impressora':
            bot.startConversation(message,function(err,conv){
            conv.say({attachments:[{
              "text": (message.watsonData.context.name+", "+message.watsonData.output.text[0]),
            },{
              "text": message.watsonData.output.text[1],
            },{
              "text": message.watsonData.output.text[2],
              "image_url":message.watsonData.context.Img1,
            },{
              "text": message.watsonData.output.text[3],
              "image_url":message.watsonData.context.Img2,
            },{
              "text": message.watsonData.output.text[4],
              "image_url":message.watsonData.context.Img3,
            },{
              "text": message.watsonData.output.text[5],
              "image_url":message.watsonData.context.Img4,
            },{
              "text": message.watsonData.output.text[6],
              "image_url":message.watsonData.context.Img5,
            },{
              "text": message.watsonData.output.text[7],
              "image_url":message.watsonData.context.Img6,
            },{
              "text": message.watsonData.output.text[8],
            },{
              "text": message.watsonData.output.text[9],
              "image_url":message.watsonData.context.Img7,
            },{
              "text": message.watsonData.output.text[10],
              "image_url":message.watsonData.context.Img8,
            },{
              "text": message.watsonData.output.text[11],
              "image_url":message.watsonData.context.Img9,
            },{
              "text": message.watsonData.output.text[12],
              "image_url":message.watsonData.context.Img10,
            },{
              "text": message.watsonData.output.text[13],
            }]});
          });
            break;
          case 'Saudação':
            bot.api.users.info({
            token: process.env.SLACK_TOKEN,
            user: message.user}, function(err, info){
              message.watsonData.context.name = info.user.profile.real_name;
              nome =  info.user.profile.first_name;
              bot.reply(message,message.watsonData.output.text.join('\n'));
                            });
            break;
          default:
            bot.reply(message, message.watsonData.output.text.join('\n'));
            break;
        }
      //INTENT INDEFINIDA
      }else{
        //Verifica se ja possui o nome do usuario
        if(message.watsonData.context.name == ""){
          bot.api.users.info({
            token: process.env.SLACK_TOKEN,
            user: message.user}, function(err, info){
              message.watsonData.context.name = info.user.profile.real_name;
              nome =  info.user.profile.first_name;
                            });
          bot.reply(message, message.watsonData.output.text.join('\n'));
        }else{
          bot.reply(message, message.watsonData.output.text.join('\n'));
        }
        
      }
    }//IF ERR
  });
});

<code>var app = express();</code>
<code>var port = process.env.PORT || 3000;</code>
<code>app.set('port', port);</code>
<code>app.listen(port, function() {</code>
 <code> console.log('Client server listening on port ' + port);</code>
<code>});</code>

**Comment by peterswimm** [comment]
Are you referring to the Microsoft Bot framework?

**Comment by Rhaniel** [comment]
Yes, I need to publish the bot to get a URL and link it in the bot framework... 
The code to connect to the bot-framework I know build, but I do not know how to get a URL to put in the bot-framework

**Comment by peterswimm** [comment]
By default the bot framework endpoint will be something like:
YOURSERVERNAME/receive

If you are running ngrok or localtunnel, just append /receive to the end of the url generated when running those programs.

**Comment by Rhaniel** [comment]
Thanks my friend...

**Comment by vimalk78** [comment]
the doc link doesnt work
> You can read more about this in the docs:
> https://github.com/howdyai/botkit/blob/master/readme-botframework.md

**Comment by vimalk78** [comment]
hi,
is it possible to incoke/use a bot created using botkit from a java application? 
the docs for 3rd party integration only mention microsoft bot framework.

is it possible to integrate or embed in another java application?

thax
