### ISSUE TITLE
Botkit.botframeworkbot is not a function

### ISSUE THREAD

**Issue by Rhaniel** [howdyai/botkit#733]
I'm trying to create a bot for bot-framework, but then running my code i receive the message saying the botkit has no function called botframeworkbot, and when print my variable botkit i have the following result: 
```

C:\Users\rcborges\Downloads\botkit-middleware-master\examples\simple-bot>npm sta
rt

 botkit-middleware-watson-simple-example@0.0.1 start C:\Users\rcborges\Download
s\botkit-middleware-master\examples\simple-bot
 node simple-bot-slack.js

{ core: [Function: Botkit],
  slackbot: [Function: Slackbot],
  facebookbot: [Function: Facebookbot],
  twilioipmbot: [Function: Twiliobot] }
```

**Comment by ouadie-lahdioui** [comment]
You always have the same problem ? Wich version of Botkit you use ?

**Comment by benbrown** [comment]
@Rhaniel looks like you are somehow running a very old version of Botkit. Make sure you get the latest version!
