### ISSUE TITLE
Support for Facebook Subscription Messaging?

### ISSUE THREAD

**Issue by razzza** [howdyai/botkit#735]
Hi
How can I use botkit for facebook to make use of the subscription messaging feature described here:
https://developers.facebook.com/blog/post/2016/08/15/updated-messenger-platform-policies/

e.g. a news bot to which the user subscribed to receive daily news updates.

Any reference/example will help, thanks!

**Comment by AdanTL** [comment]
+1

**Comment by devhaoy** [comment]
You could use bCRM middleware for subscription + basic analytics https://github.com/howdyai/botkit-middleware-bcrm

**Comment by AdanTL** [comment]
I though a solution with node-schedule(https://www.npmjs.com/package/node-schedule) and bot.say like:

```var schedule = require('node-schedule');
 
var j = schedule.scheduleJob('42 * * * *', function(){
  bot.say(
  {
    text: 'The answer to life, the universe, and everything!',
    channel: '+1(###)###-####' // a valid facebook user id or phone number
  }
);
});

But I didn't try it yet

**Comment by razzza** [comment]
great! @AdanTL
Thanks for the idea!

the node-scheduler works within botkit!
bot.Say is not supported into botkit but I did manage to make it work with a bot.Conversation:

_var schedule = require('node-schedule');
    var j = schedule.scheduleJob('*/1 * * * *', function(){
    sendMessage();  });

    function sendMessage()
    {
               bot.startConversation({
                            user: 'XXX',
                            channel: 'XXX',
                             text: 'dummy'
                                 }, function(err, convo) {
                                    convo.ask({
                                    channel: 'XXX',
                                    text: 'what?'
                                    }, function(res, convo) {
                                    convo.say('ok!')
                                    convo.next()
                                     })  } );
    }_

Note: you can only contact users that send messages to your chatbot before and for which you can extract their ID using 'message.user' from within controller.hears(... )

I only tried with myself and it worked!...have to test with other users...

**Comment by AdanTL** [comment]
Nice code buddy! but did you try to send a message after the 24h window?

**Comment by natterstefan** [comment]
@razzza what do you mean with

> bot.Say is not supported into botkit 

Thanks.

What do you mean by that @AdanTL?

**Comment by AdanTL** [comment]
@natterstefan it doesn't matter anymore, anyway I meant that if you don't request for Facebook Subscription you can't talk after 24h
