### ISSUE TITLE
team_join gives TypeError for `say` under slack

### ISSUE THREAD

**Issue by abinashmohanty** [howdyai/botkit#736]
Why does `team_join` gives the following error wherein `user_channel_join` works 100% fine.

_TypeError: Cannot read property 'say' of undefined_

```
// DM new users + information about our community
controller.on('team_join', function(bot, message) {
var userID = message.user
  // start a conversation to handle this response.
  bot.startPrivateConversation(message,function(err,convo) {

    convo.say('Welcome to our community!');
    convo.say('Use <#C3EDSP19U> to check new members.');

  });
});
```

**Comment by ihorrusi** [comment]
`team_join` and `user_channel_join ` has different message structure.
https://api.slack.com/events/team_join
https://api.slack.com/events/channel_joined

 just update 
> bot.startPrivateConversation({user: message.user.id},function(err,convo) {

**Comment by peterswimm** [comment]
@abinashmohanty Did this answer your question?
