### ISSUE TITLE
Required Help to Integration MS Bot framework + Node JS + Heroku

### ISSUE THREAD

**Issue by Rhaniel** [howdyai/botkit#744]
Please provide me guidelines to do the above mentioned combination that i am using Microsoft bot framework in node js language where i am planning to deploy it in heroku.

**Comment by gcfabri** [comment]
The same way you do to deploy any other node application on Heroku. You just need to change the endpoint on registered bot in Bot Framework Portal to point to your Heroku address. 
e.g.: https://myapp.herokuapp.com/botframework/receive
