### ISSUE TITLE
How to create Carousel Hero Cards

### ISSUE THREAD

**Issue by Rhaniel** [howdyai/botkit#745]
How can create Carousel hero cards from bot-framework.. Pls help me

**Comment by peterswimm** [comment]
What platform are you building for? Not all platforms support this, but this is a good reference:

https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-send-rich-cards

**Comment by peterswimm** [comment]
this is now a feature of Botkit Studio!
https://botkit.groovehq.com/knowledge_base/topics/microsoft-teams-attachments
