### ISSUE TITLE
How can show a form from botkit in the webview?

### ISSUE THREAD

**Issue by MagSag** [howdyai/botkit#755]
I have a mysql database and would like the user to provide information concerning his product(name, description,price) at once without asking by chatting. While reading I found it could be possible to show a user a form using webview but I don't know how to provide the form from botkit.

I need help.

**Comment by MagSag** [comment]
I need help, I am stack in the project, any idea can that can help.

**Comment by julianfox** [comment]
Hello,
for open a webview, you have to use a web_url button, for example:

`convo.addQuestion({
                attachment: {
                    type: 'template',
                    payload: {
                        template_type: 'button',
                        text: 'Complete the form',
                        buttons: [
                            {
                                type: 'web_url',
                                url: 'https://mydomain.com/form',
                                messenger_extensions: true,
                                title: 'My form'
                            }
                        ]
                    }
                }
            }, {}, {}, 'ask_note');
`

If you want to get the user ID and close the webview (on the frontend part) you have to use the Messenger Extensions script:
https://developers.facebook.com/docs/messenger-platform/webview/extensions

Then you can create a normal form and send a post request to a new endpoint in your server for save the data and create a new convo or just send a message to your user (you can get the user id with Messenger Extensions.

For example you can use:

`bot.say(
    {
        text: 'my message_text',
        channel: '+1(###)###-####' // a valid facebook user id or phone number
    }
);`

**Comment by MagSag** [comment]
Thanks @julianfox I understand what you are explaining but my problem is how can I have or set up that endpoint which will receive the post request in botkit bot? As in in which file should I go to set that endpoint and how exactly should write the code of the endpoint that file?

I am a newbie in Nodejs and botkit.

**Comment by julianfox** [comment]
Here an endpoint example, you can add it in the routes folder of the Facebook starter kit:
```
var path = require('path');

module.exports = function(webserver, controller) {
    webserver.get('/note', function(req, res) {
    	res.sendFile(path.join(__dirname + '/../../public/views/note/form.html'));
    });

    webserver.post('/note', async (req, res) => {
    	var user = req.body.user;
    	var note = req.body.note;

        // Save the data
      
        var bot = controller.spawn({});
       
        bot.say(
            {
                text: 'note receveid',
                channel: user
            }
        );
    });
}
```

End then you can

**Comment by MagSag** [comment]
Thanks so much, that helps.

**Comment by tmundt** [comment]
That sounds great! Is this kind of workflow also possible for Slack Chat?

**Comment by peterswimm** [comment]
@tmundt not exactly but you can register custom domains to be unfurled in your app 
https://api.slack.com/docs/message-link-unfurling
