### ISSUE TITLE
What are the part of code not need from botkit-starter-facebook? and the get started with menu are not working.

### ISSUE THREAD

**Issue by MagSag** [howdyai/botkit#757]
I am building my bot based on the botkit-starter-facebook example but I don't understand some part of the code and I would like to know if they are really need:

In the bot.js there is : 

```
// Send an onboarding message when a user activates the bot
require(__dirname + '/components/onboarding.js')(controller);
```

```
// Enable Dashbot.io plugin
require(__dirname + '/components/plugin_dashbot.js')(controller);
```

```
var normalizedPath = require("path").join(__dirname, "skills");
require("fs").readdirSync(normalizedPath).forEach(function(file) {
  require("./skills/" + file)(controller);
});
```
This one is associated with the use of skills folder which I don't not the use.

A part from those 3 part, I can see also : 
```
// Set up Facebook "thread settings" such as get started button, persistent menu
require(__dirname + '/components/thread_settings.js')(controller);
```
and I understand what is it for, but I would like to know if should I use it to define my get_started, welcome text and persistent menu too? I tried to write this in my bot.js  : 
```
//setting the welcom text
controller.api.thread_settings.greeting("xxxxxx sdflsdlfsdf.");
//setting the get started button
controller.api.thread_settings.get_started("GET_STARTED");
```
I couldn't see the effect( I don't see the get started button neither the greeting text). what is the way to set them? 
And the persistent is still the old sample(hello,Help,Botkit Docs) instead of mine(Account,Support,Contact).

**Comment by MagSag** [comment]
Please I need help.

**Comment by amitbend** [comment]
Hi, Can you see something like `debug: Successfully configured messenger profile {"result":"success"}`
in your console?

**Comment by MagSag** [comment]
I am running the application from GAE(google App Engine), let me first return it to my local environment?

@amitbend I have one question, that's messenger return that result everytime that a person tries to access the bot menu? in other words when does messenger build the menu of the bot(everytime or just the first time the bot is create on messenger or accessed by the user)?

**Comment by MagSag** [comment]
@amitbend I've configure the facebook to work from my local so I set my menu as follow:

` controller.api.thread_settings.menu([{"type":"postback","title":"Nearest Place with Best Price","payload":"hello"},{"type":"postback","title":"Post or Update Offer","payload":"help"},{"type":"postback","title":"Account","payload":"help"}]);`

but the debugger is saying : 
> ERROR in messenger profile API call: <#100> Invalid keys "type, title, payload" were found in param "persistent)menu[0]".

**Comment by amitbend** [comment]
Hi @MagSag, the menu should be sent only once you want to give it an update or usually when the server is starting.

it seems like the menu you are sending has an incorrect structure,
you can see  [over here](https://developers.facebook.com/docs/messenger-platform/messenger-profile/persistent-menu)  the correct way to declare it.

You should also use 
` controller.api.messenger_profile.menu` as this is the new way of sending this data to facebook


here an example json to add to the menu 
`{
      "locale":"default",
      "composer_input_disabled":true,
      "call_to_actions":[
        {
          "title":"My Account",
          "type":"nested",
          "call_to_actions":[
            {
              "title":"Pay Bill",
              "type":"postback",
              "payload":"PAYBILL_PAYLOAD"
            },
            {
              "title":"History",
              "type":"postback",
              "payload":"HISTORY_PAYLOAD"
            },
            {
              "title":"Contact Info",
              "type":"postback",
              "payload":"CONTACT_INFO_PAYLOAD"
            }
          ]
        },
        {
          "type":"web_url",
          "title":"Latest News",
          "url":"http://petershats.parseapp.com/hat-news",
          "webview_height_ratio":"full"
        }
      ]
    },
    {
      "locale":"zh_CN",
      "composer_input_disabled":false
    }`

**Comment by peterswimm** [comment]
We created an internal ticket over here to take a look at this, unless the community provides a PR for it first.

**Comment by MagSag** [comment]
@amitbend  thanks, I follow what you said and here is what I did:
controller.api.messenger_profile.menu([{ "locale":"default", "composer_input_disabled":true, "call_to_actions":[ { "title":"My Account", "type":"nested", "call_to_actions":[ { "title":"Pay Bill", "type":"postback", "payload":"PAYBILL_PAYLOAD" }, { "title":"History", "type":"postback", "payload":"HISTORY_PAYLOAD" }, { "title":"Contact Info", "type":"postback", "payload":"CONTACT_INFO_PAYLOAD" } ] }, { "type":"web_url", "title":"Latest News", "url":"http://petershats.parseapp.com/hat-news", "webview_height_ratio":"full" } ] }, { "locale":"zh_CN", "composer_input_disabled":false }]);

It is woring perfectly well.

**Comment by ilyago** [comment]
it works on the mobile phone but doesn't work in the desktop web browser. 
Any idea?

**Comment by ilyago** [comment]
The menu shows up on the mobile phone but there is no more input text box to type messages, why?
