### ISSUE TITLE
Storage section of docs should point to related storage modules

### ISSUE THREAD

**Issue by benbrown** [howdyai/botkit#76]
We should update the docs and provide some information about the storage related sub-modules.

We should also include information about this in the "Writing your own storage module" section.

**Comment by anonrig** [comment]
I suggest using `botkit-storage-base` to move the "Wrint your own storage module" section.

**Comment by peterswimm** [comment]
Storage modules are now documented here:

https://github.com/howdyai/botkit/blob/master/readme-middlewares.md
