### ISSUE TITLE
Viber Compatibility

### ISSUE THREAD

**Issue by MatejMecka** [howdyai/botkit#760]
So the Viber SDK is out from IDK what time nor do I care about Viber and many people use it at least here in Macedonia.  Bots + Viber = Perfect Opportunity for viber.

Link to the SDK is: http://developers.viber.com/api/nodejs-bot-api/index.html

If someone is interested in Developing this might be easier for you guys to use Botkit.

**Comment by madtaras** [comment]
@MatejMecka @peterswimm we are interested in this feature. Is there any progress running on this?

**Comment by peterswimm** [comment]
We have not seen any PR requests yet!

**Comment by mokeddes** [comment]
I am very interested to develop this featurs, i will start this week-end ! @madtaras

**Comment by peterswimm** [comment]
^ https://botkit.ai/docs/howto/build_connector.html

**Comment by madtaras** [comment]
@mokeddes any progress on this? Do you need help?

**Comment by mokeddes** [comment]
I started last night! I did not go very progress and I did not have a problem .. on your side ?

**Comment by madtaras** [comment]
@mokeddes could you share a link to the repo with current progress?
We haven't started anything on our side because we knew you are going to start
If you need some help ping me here

**Comment by madtaras** [comment]
@mokeddes here is something already implemented. A took a quick glance. A lot of clean up is needed but you can take it as a base https://github.com/cdbhnd/botkit-viber

**Comment by mokeddes** [comment]
It will save me a lot of time ! Thank's a lot

**Comment by madtaras** [comment]
@mokeddes cool! Do you have any plans or timeline on when you'll finish the connector?

**Comment by madtaras** [comment]
@mokeddes ?

**Comment by mokeddes** [comment]
I'm going to spend time this weekend, I'll come back to you early in the week to make a point on a probable timeline @madtaras Sorry ..I did not have time to see this week

**Comment by madtaras** [comment]
@mokeddes check this out https://github.com/howdyai/botkit/pull/1496
