### ISSUE TITLE
Persistent Menu controller api is not working

### ISSUE THREAD

**Issue by MagSag** [howdyai/botkit#764]
controller.api.thread_settings.menu([{"type":"postback","title":"come","payload":"hello"},{"type":"postback","title":"Place","payload":"help"},{"type":"postback","title":"Account","payload":"help"}]);

but the debugger is saying :

    ERROR in messenger profile API call: <#100> Invalid keys "type, title, payload" were found in param "persistent)menu[0]".

A part from that I also try to use curl to delete and set a new menu, the menu is not getting update, it is still showing the one that come with the botkit-starter-facebook (hello,help, botkit docs)

**Comment by znat** [comment]
It's not a bug, the payload format has changed:
See the doc here: https://developers.facebook.com/docs/messenger-platform/messenger-profile/persistent-menu

**Comment by peterswimm** [comment]
We created an internal issue to fix this, unless one of you gets to it first!

**Comment by znat** [comment]
There's nothing to fix (unless you want to change the feature). Devs must just update their payload to reflect the new format.

**Comment by peterswimm** [comment]
True, but we should also update docs to clarify the change. In any case we will need to update Studio to support this change as well!

**Comment by MagSag** [comment]
The solution is :
`controller.api.messenger_profile.menu([{ "locale":"default", "composer_input_disabled":true, "call_to_actions":[ { "title":"My Account", "type":"nested", "call_to_actions":[ { "title":"Pay Bill", "type":"postback", "payload":"PAYBILL_PAYLOAD" }, { "title":"History", "type":"postback", "payload":"HISTORY_PAYLOAD" }, { "title":"Contact Info", "type":"postback", "payload":"CONTACT_INFO_PAYLOAD" } ] }, { "type":"web_url", "title":"Latest News", "url":"http://petershats.parseapp.com/hat-news", "webview_height_ratio":"full" } ] }, { "locale":"zh_CN", "composer_input_disabled":false }]);`

The above code does it well maybe the documentation shoud be updated.
It is woring perfectly well.

**Comment by ducva** [comment]
Actually, I tried and found that only "nested" postback menus work.
The top level menus with type='postback' still didn't work.
