### ISSUE TITLE
What method does botkit call to log?

### ISSUE THREAD

**Issue by MagSag** [howdyai/botkit#765]
I've installed winston and everything is working well but I would also like all the message that I send to the console to be logged too. I try to go through the code of botkit but can't find which method it calls for example when logging the message "** No persistent storage method specified! Data may be lost when process shuts down."

**Comment by MagSag** [comment]
The thing is all the error or warning message that botkit sent to the console are being saved by the logger(winstone), I would also like all the message(warning or error) that I am sending to be saved automatically. I don't which method or function are you using to do that; I would like to know it.

**Comment by urbanslug** [comment]
The funciton is `botkit.log` defined here https://github.com/howdyai/botkit/blob/master/lib/ConsoleBot.js#L1421.

If you set the winston transport to console both winston and botkit.log logs will just be sent to the console.
