### ISSUE TITLE
Question: Confused by configureSlackApp() method

### ISSUE THREAD

**Issue by clintonhalpin** [howdyai/botkit#767]
After burning a bunch of time trying to debug, I was able to get interactive messages working by passing my entire Slack App's config to `Botkit.slackbot()` instead of splitting between `Botkit.slackbot().configureSlackApp()` and the `Botkit.slackbot()` method.

Since you can just setup your Slack App using `Botkit.slackbot()` method I'm wondering if the [examples](https://github.com/howdyai/botkit/blob/master/examples/slackbutton_bot_interactivemsg.js#L36) should be updated to reflect this.

Unable to get this working:
```javascript
const controller = Botkit.slackbot({
  interactive_replies: true,
}).configureSlackBot({
  clientId: config.clientId,
  clientSecret: config.clientSecret,
});
```

This worked:
```javascript
const controller = Botkit.slackbot({
  interactive_replies: true,
  clientId: config.clientId,
  clientSecret: config.clientSecret,
});
```

I would be happy to contribute and take on this work!

Details:
```
Version: 5.2
OS: OSX 10.3, Ubuntu 16.4
```

**Comment by peterswimm** [comment]
We have a project for this, if you wanted a try at some PR to update a given example https://github.com/howdyai/botkit/projects/2

**Comment by clintonhalpin** [comment]
@peterswimm Radical! Wrote this ticket when I was just getting started with Botkit. Should be able to share some of my now production code which I think would help others.

**Comment by peterswimm** [comment]
Great! Im going to close this for now, feel free to create a new issue with you are ready to share any PRs.
