### ISSUE TITLE
Slackbot_worker throws Error when Slack Select menu is used

### ISSUE THREAD

**Issue by clintonhalpin** [howdyai/botkit#768]
Testing out the new Slack Select menu's using a conversation. This line throws an error when sent a slack select response [Slackbot_worker.js#L741](https://github.com/howdyai/botkit/blob/master/lib/Slackbot_worker.js#L741)

```javascript
message.text = message.text.replace(direct_mention, '').replace(/^\s+/, '').replace(/^\:\s+/, '').replace(/^\s+/, '');
```
Error:
```
TypeError: Cannot read property 'replace' of undefined
    at Object.bot.findConversation
```
This is because `message.text` is not there and instead the response is in `message.actions[ 0 ].select_values`

[Gist of Message Response](https://gist.github.com/clintonhalpin/6245ff52257c16f5e7bebf2be714521f)

Details:
```
Version: 5.2
OS: OSX 10.3, Ubuntu 16.4
```

**Comment by matt-oakes** [comment]
This should be closed now I think.

**Comment by clintonhalpin** [comment]
@matt-oakes Yep! I tested this yesterday it it worked for me
