### ISSUE TITLE
Error on step five

### ISSUE THREAD

**Issue by pedroalpha** [howdyai/botkit#777]
I don't understand step five:

I run

page_token=XXXXXXXXverify_token=6565989556 node facebook_bot.js

And I get 'page_token' is not an internal command.

I'm using localtunel. 

Why is that so I can't configure the webhook.

The app I'm running is the simple bot. (https://github.com/watson-developer-cloud/conversation-simple)

**Comment by peterswimm** [comment]
I deleted your token from your ticket. Dont paste that here!

Have you tried the Facebook starter kit?
https://github.com/howdyai/botkit-starter-facebook

**Comment by pedroalpha** [comment]
Hello, I pasted a fake code haha.

Yes, I tried. The webhook is not working.

I have a whatson bot.


Do you some support or video for this?

Em 17/04/2017 11:35, "Peter Swimm" <notifications@github.com> escreveu:

**Comment by peterswimm** [comment]
Your command does not include the localtunnel command, did you get that running ok? It will provide an url you will need to use for the webhooks

page_token=<MY PAGE TOKEN> verify_token=<MY_VERIFY_TOKEN> node facebook_bot.js [--lt [--ltsubdomain CUSTOM_SUBDOMAIN]]

By default it will be something like
https://YOURSERVER/facebook/receive

You should try running the facebook stater on Glitch, it simplifies the need to sort the localtunnel servers if you are having trouble:
https://glitch.com/edit/#!/import/github/howdyai/botkit-starter-facebook

**Comment by pedroalpha** [comment]
Yes, the lt server was running on the port 3000.

Then I opened a new cmd window and I got the message that "my page"  is not
a command.

Also when I go to
https://YOURSERVER/facebook/receive <https://yourserver/facebook/receive> I
receive a message showing that it couldn't get fb information.

I don't know glitch I'll give it a try.



Em 17/04/2017 13:16, "Peter Swimm" <notifications@github.com> escreveu:

Your command does not include the localtunnel command, did you get that
running ok? It will provide an url you will need to use for the webhooks

page_token= verify_token=<MY_VERIFY_TOKEN> node facebook_bot.js [--lt
[--ltsubdomain CUSTOM_SUBDOMAIN]]

By default it will be something like
https://YOURSERVER/facebook/receive

You should try running the facebook stater on Glitch, it simplifies the
need to sort the localtunnel servers if you are having trouble:
https://glitch.com/edit/#!/import/github/howdyai/botkit-starter-facebook

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/howdyai/botkit/issues/777#issuecomment-294519045>, or mute
the thread

**Comment by pedroalpha** [comment]
Thanks! I never used glitch before this is pretty amazing. I run it from there

**Comment by peterswimm** [comment]
Great! Closing for now, feel free to open a new issue if you run into trouble!
