### ISSUE TITLE
Timeout issue being received. Message still sent

### ISSUE THREAD

**Issue by danhodkinson** [howdyai/botkit#778]
Not exactly sure what's going on here:

I am simply echoing out the response for now but don't want the original users message to show so i'm using a delayed response (i believe that's the only way to hide the message?).

Here is my code:
`slashCommand.replyAcknowledge;
            slashCommand.replyPublicDelayed(message, "@"+message.user_name+" has asked: "+message.text)`

However in action this does the following:
i) message is sent
ii) timeout message received privately
iii) box refills with message I was attempting to send.

If i log in as another user I can see that the message was successful. So i'm confused as to why I'm receiving the issue and how to clean it up better?

The below image shows what happens after sending a message

<img width="895" alt="screen shot 2017-04-15 at 15 41 21" src="https://cloud.githubusercontent.com/assets/1689209/25064466/69bea742-21f2-11e7-92c5-1fb92651b547.png">

**Comment by robbawebba** [comment]
@danhodkinson I posted a solution in #595, let me know how it works for you!

**Comment by peterswimm** [comment]
Closing this in order to concentrate the conversation in the linked thread above
