### ISSUE TITLE
bot.say() message to user goes to their slackbot?

### ISSUE THREAD

**Issue by danhodkinson** [howdyai/botkit#781]
i'm building a bot whereby when the user replies to the bot the message is sent to a specified user.
however this comes through to their slackbot and not their personal DM?

is this expected behaviour or can i make it go to their personal DM?

**Comment by robbawebba** [comment]
@danhodkinson Check out [this API documentation](https://api.slack.com/methods/chat.postMessage) from slack regarding sending messages to specific channels. You'll have to scroll down to the section "Channels" and the subsection "Post to an IM Channel".

[Also, Here's how to use the Slack API calls through botkit](https://github.com/howdyai/botkit/blob/master/docs/readme-slack.md#using-the-slack-web-api).

**Comment by danhodkinson** [comment]
@robbawebba thanks for that. 
if anybody else has this issue, I can confirm the link to the Slack API documentation provides with the answer of why it goes to a users slackbot and how to make it not do that.
