### ISSUE TITLE
How can I know that a message received concerns a specific thread?

### ISSUE THREAD

**Issue by MagSag** [howdyai/botkit#782]
I've understood how a thread works, I don't know how I can determine the message the bot received from message_received event concerns a specific thread. For instance: if I want the user to provide three information in the following order: image,name, description all concerning creating a product thread.

Normally I can acheive that using convo.ask as it helps handle the response_message and gives an opportunity to use a callback function but the documentation is saying : 

> In particular, we recommend that developers avoid calling convo.ask() or convo.say() inside a callbacks for convo.ask(). Multi-level callbacks encourage fragile code - for conversations requiring more than one branch, use threads!

**Comment by ouadie-lahdioui** [comment]
Yo @MagSag,

To avoid multi level callbacks you can do refactor you code to be like that :

```js
convo.addQuestion({text: 'Send me the image '} ,function(res, convo) {
  // Code ....
  convo.gotoThread('AskForName');
},{key: 'image'},'AskForImage');

convo.addQuestion({text: 'Name ?'} ,function(res, convo) {
  // Code ....
  convo.gotoThread('AskForDescription');
},{key: 'image'},'AskForName');

convo.addQuestion({text: 'Description ?'} ,function(res, convo) {
  // Code ....
  
},{key: 'image'},'AskForDescription');
```
