### ISSUE TITLE
addQuestion is not working

### ISSUE THREAD

**Issue by MagSag** [howdyai/botkit#783]
I am trying to send a message using addQuestion in my messenger bot but nothing is being sent, here is my code:
```
bot.startConversation(message,function(error,convo){
convo.addQuestion("Please send me the name",function(response_message,convo){
convo.say("Well done");
},{},"product");
});
```
In my console here is what I am getting : 
![whatsapp image 2017-04-17 at 20 21 25](https://cloud.githubusercontent.com/assets/13017395/25097204/2c34fcf8-23ac-11e7-913c-69547bf33b89.jpeg)

**Comment by benbrown** [comment]
`addQuestion()` has 2 additional parameters that you should include after the callback. Check the docs!

**Comment by MagSag** [comment]
I forgot to add them in the issue but in my code it is there.

**Comment by cterrazas2** [comment]
@MagSag  don't you need to call `convo.next();` in addQuestion?
