### ISSUE TITLE
How to send a message to the user when conversation time out happens.

### ISSUE THREAD

**Issue by PrajaktaNaik** [howdyai/botkit#784]
I am adding a timeout in the slack conversation, so that when the user does not reply on convo.ask, the conversation will end. this works fine, but on the end of conversation, I want to send a message to only the user saying, your session has timedout . I have used the below inside the startconversation, is this the correct way to do it. I am not able the message back to the user, I have used convo.say(). But in my console I see the message timeout. Am I missing something?

convo.task.timeLimit = 5000;
convo.on('end',function(convo) {
    if (convo.status=='timeout') {
        console.log("timeout");
        convo.say("session ended");
}
});

**Comment by AdanTL** [comment]
I used
```javascript
convo.setTimeout(60000 * 60);
convo.onTimeout(function(convo){
    convo.say('Adiós')
})
```
