### ISSUE TITLE
When a RegExp is not in an Array in `hears` does not work

### ISSUE THREAD

**Issue by alsuga** [howdyai/botkit#785]
The first does not work but the second does
`
const yesRegex = /^(yes|yep)/i;
controller.hears(yesRegex, [direct_message], (bot, message) => {
  bot.reply(message, 'yes');
});
const noRegex = /^(no|nop)/i
controller.hears([noRegex], [direct_message], (bot, message) => {
  bot.reply(message, 'no');
});
`

**Comment by jonchurch** [comment]
@peterswimm 🚫
