### ISSUE TITLE
how to run botkit within the custom express server instance ?

### ISSUE THREAD

**Issue by deepakmhr** [howdyai/botkit#787]
I was using this **https://github.com/mvaragnat/botkit-messenger-express-demo** sample code for custom server instance but it seems have some issue like conversion is not returning any results.

Is there any other way to use custom server instance with botkit ?

**Comment by ouadie-lahdioui** [comment]
Hello @deepakmhr [here's how you can do that](https://github.com/howdyai/botkit-starter-facebook/blob/master/components/express_webserver.js)

**Comment by peterswimm** [comment]
Closing as answered, please reopen if you run into any trouble
