### ISSUE TITLE
How to use session to store user specific data ?

### ISSUE THREAD

**Issue by deepakmhr** [howdyai/botkit#799]
I want to store user preferences into the session object but I am not able to get any way store in it. is there any way to use inbuilt session variable ?

Please help

**Comment by peterswimm** [comment]
Have you seen this article
https://github.com/howdyai/botkit/blob/master/docs/storage.md

**Comment by IvanCaro** [comment]
i thing @deepakmhr it's talking about 'message' object https://docs.botframework.com/en-us/node/builder/chat/session/
