### ISSUE TITLE
controller.hears not matching regular expressions correctly

### ISSUE THREAD

**Issue by markstickley** [howdyai/botkit#80]
Using this code:

```
controller.hears('set volume (.*)','direct_message,direct_mention,mention', function(bot, message) {
    console.log(message);
});
```

I get this output:

```
{ type: 'message',
  channel: 'G0HNQCS23',
  user: 'U0A1H66FJ',
  text: 'set volume 50',
  ts: '1452007099.000065',
  team: 'T09JJJWKZ',
  event: 'direct_mention' }
```

There is no `match` property on message, just the text which I suppose does mean that the regex matched even if it didn't parse the brackets.

However if the regex is `'set volume (\d+)'` matching the same text doesn't work (which I think it should).

Am I doing something wrong here?

Thanks!

**Comment by mikehmorrissey** [comment]
@markstickley I think you have to escape the escape character like:
```js
'set volume (\\d+)'
```

**Comment by markstickley** [comment]
Oh that’s makes sense yes. Because it’s a string and not a regexp like `/set volume (\d+)/`.

Thanks! I’ll give it a try.

**Comment by markstickley** [comment]
OK well that certainly now seems to match as per the regex. However there still doesn't seem to be a `match` property on the message as mentioned in the readme. Is this inaccurate? Should I parse the message again? Thanks!

**Comment by mikehmorrissey** [comment]
@markstickley are you sure you are using version 0.0.5?

**Comment by markstickley** [comment]
Ah! Well now you mention it, no I'm not! Did that come out recently?

Sorry about that, I'll update and try again :)
