### ISSUE TITLE
Bot doesn't hearing keywords such as "thank you", "Thanks"

### ISSUE THREAD

**Issue by abinashmohanty** [howdyai/botkit#801]
Question for Botkit sending a **random message**. But the problem I’m having with the keywords such as `thanks`, `thank you`, `thanks a lot` etc.. in this case, **the bot doesn’t listen** or ignoring such keywords especially `thanks` … **but it’s running fine the moment I change its keywords**.. *what could be the problem?*

```
// Replies to keywords such as thanks, thx, thank you, etc. 
controller.hears(['Thanks', 'thx', 'thank u', 'thank you', 'thanks a lot', 'thank you so much'], ['direct_message','direct_mention','mention'], function(bot, message) {
    var message_options = [
    	  "You got it",
    	  "Don’t mention it",
          "Not a problem",
          "No worries",
          "My pleasure",
          "I’m happy to help",
    	  "Anytime"
	]
	var random_index = Math.floor(Math.random() * message_options.length)
	var chosen_message = message_options[random_index]

  bot.reply(message, chosen_message)
    // do something here, the "is typing" animation is visible

});
```

**Comment by clintonhalpin** [comment]
I'm not 100% sure on this but I think you need to write your patterns seperated by '|'. So you could do:

```javascript
controller.hears(['Thanks', 'thx', 'thank u', 'thank you', 'thanks a lot', 'thank you so much'].join('|'), ['direct_message','direct_mention','mention'], function(bot, message) {
});
```

OR

```javascript
controller.hears('Thanks|thx|...', ['direct_message','direct_mention','mention'], function(bot, message){
});
```

**Comment by abinashmohanty** [comment]
@clintonhalpin okay! I will test this tomorrow. However, i have 7 more modules like the above one, and they work 100% fine with the same format. I wondered why this particular keywords didn't work :( 

Thanks

**Comment by abinashmohanty** [comment]
@clintonhalpin I've checked, and it didn't work. Like in the following example, **thanks** didn't work, but **party time** worked 100%. Don't understand why this particular keyword doesn't work. @benbrown do you have any idea why it's not taking the keyword `thanks`?

```
// Replies to keywords such as thanks, thx, thank you, etc 
controller.hears(['party time', 'thanks'], ['direct_message','direct_mention','mention'], function(bot, message) {
    var message_options = [
    	  "You got it",
    	  "Don’t mention it",
        "Not a problem",
        "No worries",
        "My pleasure",
        "I’m happy to help",
    	  "Anytime"
	]
	var random_index = Math.floor(Math.random() * message_options.length)
	var chosen_message = message_options[random_index]

  bot.reply(message, chosen_message)
    // do something here, the "is typing" animation is visible

});
```

**Comment by daniloavilez** [comment]
I think you're missing in second parameter where did you put 
`['direct_message','direct_mention','mention']`

To add message_received, try it on.

**Comment by benbrown** [comment]
@abinashmohanty did you ever sort this out?
