### ISSUE TITLE
Message Type string in #hears function

### ISSUE THREAD

**Issue by jonchurch** [howdyai/botkit#807]
I've noticed this a few times, always forget to bring this up.

Spaces between the message type string in hears functions will register the first type, but not any others. Not sure that this is a bug, or just undocumented.

**The following will only trigger on direct_messages, but not ambient.**
`controller.hears('hi', 'direct_message, ambient', function(bot, message) { ... }`

**Without the space between direct_message and ambient they both trigger:**
`controller.hears('hi', 'direct_message,ambient', function(bot, message) { ... }`

Another valid way to do this is in an array (which the docs mention):
`controller.hears('hi', ['direct_message', 'ambient'], function(bot, message) { ... }`

**Suggested changes:** accept spaces in the string, or leave it how it is but give an error if spaces are used. What do you think @peterswimm @benbrown?

This has tripped me up quite a few times, and I'm sure it happens to others as well. Can't recall seeing this info out there in another issue, so here you go!

**Comment by peterswimm** [comment]
Sounds like a bug to me, we should gracefully handle spaces always.
