### ISSUE TITLE
direct_mention in Slack requires @mention to be first

### ISSUE THREAD

**Issue by lumberj** [howdyai/botkit#811]
Version: 0.5.2
OS: MacOS

Testing BotKit on Slack (in a private channel). I notice that for the `direct_mention` event, it's only working if the mention is first

Controller looks like this
```javascript
controller.on('message_received', (bot, message) => {
  logger.debug('Message Received', message)
})

controller.hears('.*', ['direction_mention'], (bot, message) => {
  logger.debug('Works')
})
```

Log output
```shell
[2017-04-28T16:39:51.140Z] DEBUG: bot/65445 on Alans-MacBook-Pro.local:
    Message Received { type: 'desktop_notification',
      subtitle: 'bot-testing',
      msg: '1493397596.076956',
      content: 'alan: hey @bot',
      channel: 'G566Q4GFL', }
```

vs.

```shell
[2017-04-28T16:44:16.055Z] DEBUG: bot/70277 on Alans-MacBook-Pro.local: Works <----------
[2017-04-28T16:44:16.132Z] DEBUG: bot/70277 on Alans-MacBook-Pro.local:
    Message Received { type: 'desktop_notification',
      subtitle: 'bot-testing',
      msg: '1493397860.146096',
      content: 'alan: @bot hey',
      channel: 'G566Q4GFL',
      event_ts: '1493397861.339272' }
```

**Comment by peterswimm** [comment]
Direct mentions are only if the @ bot is mentioned at the *beginning* of the message. You'll want to add 'mention' to your controller.hears to add an @ mention from any other part of the message.

**Comment by lumberj** [comment]
Thanks @peterswimm. Just found the relevant part of the documentation, https://github.com/howdyai/botkit/blob/ed89f621d151ec9408c8ff14e05562615e123b93/docs/readme-slack.md#message-received-events
