### ISSUE TITLE
Quick_replies and Postback doesn't work. Is botkit for learning how to create bot or bot intended to be used?.

### ISSUE THREAD

**Issue by MagSag** [howdyai/botkit#816]
I wonder if everything is ok with botkit and if it is the right tool to use for a serious bot or just for testing how bot works. I ask myself is it my codes or logic or botkit?

I am using botkit version 0.5.2 to build facebook bot and I've been having serious problems:
**Quickreplies :** when someone click on a quick reply button nothing is as event his getting triggered (neither triggering a message_received nor postack event);
**Persistent Menu:** the postback button is not working (neither triggering a message_received nor postack event).

Sometimes they work, sometimes they don't with the same code and then sometimes I change the code; I am really confused, I would like to know if the problem is with my version of botkit?

here is a sample of my code for quick reply,(when the quick_reply is clicked the bot is not being even contacted and sometimes it is working:

```
bot.startConversation(message, function (error, convo) {
                convo.ask({
                            "text": "Should I find for you ?",
                            "quick_replies": [
                                {
                                    "type": "postback",
                                    "title": "Team",
                                    "payload": "TEAM"
                                },
                                {
                                    "type": "postback",
                                    "title": "Players",
                                    "payload": "PLAYER"
                                }
                            ]
                }, [{
                        pattern: "Team", callback: function (response, convo) {
                            saveStep("FIND_TEAM", message.user, "");
                            convo.ask("Which Product are you looking for ?", function (response, convo) {
                                saveStep("WHAT", response.user, response.text);
                                convo.say('Which team do you like?');
                                convo.next();
                            });
                            
                    }
                    }, {
                            pattern: "Service Provider", function(response, convo) {
                                            saveStep("FIND_PLAYER", message.user, "");
                                            convo.ask("Players from which country ?", function (response, convo) {
                                                saveStep("WHAT", response.user, response.text);
                                                convo.say('Who is your favorite player?');
                                                convo.next();
                                            });
                        }
                        }]);
            });
```

**Comment by devhaoy** [comment]
I also noticed some quick replies won't fire from time to time, or the payload will be ignored. Always considered this is an issue with Facebook API, not our beloved Botkit. Would be interesting to have feedbacks from people having successful bots built with Botkit or Botkit creators!
