### ISSUE TITLE
message_received is being triggered for every message the bot sends too. how can I know the difference when it is the user who sent (FACEBOOK)?

### ISSUE THREAD

**Issue by MagSag** [howdyai/botkit#817]
I am working with facebook messenger; there are some instructions that I want to execute when the bot user sent a message to the bot. I've come to notice that message_received is being trigger also when the bot sends a message without receiving one directly from the user.

What event handler is trigger only when the user sends the message and not bot or how can I know that this message_received is because the bot sends a message but not because the user sent a message?

**Comment by jonchurch** [comment]
Do you have message echoes on? The only facebook events your webhook should
subscribe to are messages, postbacks, optins, and referrals if you choose
to use them. Echoes, reads, all the other unnecessary stuff will also
trigger message_received.

It is certainly not meant to trigger message_received when the bot sends a
message, so make sure you have your webhook events configured properly with
facebook. The message_received event is a catchall.

Use the hears method to be more specific about what you're bot responds to.

**Comment by MagSag** [comment]
Thanks @jonchurch I've just realized that message object has the property is_echo so I am avoiding it using that, but I would also like to know how can I differentiate a message that the user typed and the one from action elements(buttons,quick_replies).

**Comment by jonchurch** [comment]
Postback buttons by default trigger the `facebook_postback` event. If you have enabled `receive_via_postback: true` in your controller, the payload of postback buttons will be triggered as if the user uttered the payload as input. This allows you to elegantly catch button input in conversation flows, just treat it like regular user input, but with data! 

I'm pretty sure quick_replies come to you with a quick_reply field on the message body?

**Comment by MagSag** [comment]
Thanks for that but I have another problem, the postback for the persistent menu is not working. When the persitent menu is clicked the bot is receiving nothing, not even a event triggered and sometimes it works. What might be behind this?

**Comment by adantoscano** [comment]
@MagSag if you changed your menu recently, have to wait cause sometime facebook spend more time than usual to react.

@jonchurch When you say message echoes on, what do you mean? Can I turn it off?

**Comment by jonchurch** [comment]
@adantoscano echoes are a FB event you can subscribe your webhook to. Each message will trigger a message event, and an exho event, if youve subscribed to echoes.

**Comment by benbrown** [comment]
As of v0.6.1, message echos are now caught and emitted as their own event: `message_echo` events.

This should prevent the bot from accidentally hearing itself.

**Comment by thgh** [comment]
Seems like `message_echo` is being triggered for both manual and bot messages. Solution is to check `message.raw_message.message.app_id` => will be empty for manual messages.
