### ISSUE TITLE
SOLVED - Cant send formatted URL

### ISSUE THREAD

**Issue by Silverbug** [howdyai/botkit#82]
Hey All,

I'm trying to send a reply message which should include a link (a couple actually).
The issue I'm having is that whenever i format the message response with the <url|link text> it looks like it is escaping the text before sending it through.

I've got something along the lines of:
bot.reply(message,'This is my sample message http://google.com|google');

Any suggestions on what I can check?

**Comment by jeffreylo** [comment]
Think it's because your URL isn't wrapped with angle brackets?

i.e.,
```js
bot.reply(message,'This is my sample message <http://google.com|google>');
```

**Comment by Silverbug** [comment]
Ah looks like github escaped my brackets when I pasted the example. It did have them in there. 

Turns out the issue was with the fact I was using the rtm say, rather than the webapi postMessage call. If you want to send formatted messages (with links) you need to use the webapi.

**Comment by coffee-cup** [comment]
Was this fixed? I am still having this issue when sending messages using RTM.

**Comment by Silverbug** [comment]
I don't think they were going to fix it. I changed my implementation to use webapi postMessage instead and it worked the way I needed it to after that.

**Comment by abinashmohanty** [comment]
It's not fixed, tried both using the `bot.reply` and + `attachment` method.

**Comment by abinashmohanty** [comment]
@Silverbug @coffee-cup I've just tested another link with Slack `Message Builder` and it works with the following snippet. check out this [demo](https://api.slack.com/docs/messages/builder?msg=%7B%22text%22%3A%22Sample%20Text%20Link%20%3Chttp%3A%2F%2Fwww.example.com%7CExample%20Website%3E%22%7D) 

```
{
    "text": "Sample Text Link <http://www.example.com|Example Website>"
}
```

**Comment by peterswimm** [comment]
Reopened, @mkral care to submit an attempt at a fix?
