### ISSUE TITLE
Hear and detect Emojis from Facebook 

### ISSUE THREAD

**Issue by azanoni** [howdyai/botkit#823]
Hi, I receive the messages from FB but if the users wirites emojis, the app converts them into "?" chars, so If the user by FB sendme two emojis I receive two "??"...if send me four...I receive "????", why detect them in "?" chars?, its somenthing related to the charset?, or  a missing plugin for understand the emojis?

Thanks in advance!

**Comment by peterswimm** [comment]
This might be a platform question, but I found this thread where people discuss it:

http://stackoverflow.com/questions/20045268/how-does-facebook-encode-emoji-in-the-json-graph-api
