### ISSUE TITLE
 Capture middleware doesn't work

### ISSUE THREAD

**Issue by Billydubb** [howdyai/botkit#825]
Using the capture middleware like in the following minimal example produces an error in **.../lib/CoreBot.js:92
  if(response.text)
TypeError: Cannot read property 'text' of undefined**

If I write 'what is my name' the bot correctly responds with 'I do not know your name yet!' 'What should I call you'. Upon replying, the application crashes.

The following is the minimal example used to reproduce this error:

    controller.middleware.capture.use(function(controller, bot, message, convo, next) {

        console.log('middleware works');
        next();

    });

    controller.hears(['what is my name', 'who am i'], 'direct_message,direct_mention,mention', 
        function(bot, message) {

    controller.storage.users.get(message.user, function(err, user) {
        if (user && user.name) {
            bot.reply(message, 'Your name is ' + user.name);
        } else {
            bot.startConversation(message, function(err, convo) {
                if (!err) {
                    convo.say('I do not know your name yet!');
                    convo.ask('What should I call you?', function(response, convo) {
                        convo.ask('You want me to call you `' + response.text + '`?', [
                            {
                                pattern: 'yes',
                                callback: function(response, convo) {
                                    // since no further messages are queued after this,
                                    // the conversation will end naturally with status == 'completed'
                                    convo.next();
                                }
                            },
                            {
                                pattern: 'no',
                                callback: function(response, convo) {
                                    // stop the conversation. this will cause it to end with status == 'stopped'
                                    convo.stop();
                                }
                            },
                            {
                                default: true,
                                callback: function(response, convo) {
                                    convo.repeat();
                                    convo.next();
                                }
                            }
                        ]);

                        convo.next();

                    }, {'key': 'nickname'}); // store the results in a field called nickname

                    convo.on('end', function(convo) {
                        if (convo.status == 'completed') {
                            bot.reply(message, 'OK! I will update my dossier...');

                            controller.storage.users.get(message.user, function(err, user) {
                                if (!user) {
                                    user = {
                                        id: message.user,
                                    };
                                }
                                user.name = convo.extractResponse('nickname');
                                controller.storage.users.save(user, function(err, id) {
                                    bot.reply(message, 'Got it. I will call you ' + user.name + ' from now on.');
                                });
                            });

                        } else {
                            // this happens if the conversation ended prematurely for some reason
                            bot.reply(message, 'OK, nevermind!');
                        }
                    });
                }
            });
        }
    });
    });

**Comment by jonchurch** [comment]
You are passing controller as an extra param into that capture middleware. Remove controller, the argument signature for capture middleware is: `bot, message, convo, next`

[Capture Middleware Docs](https://github.com/howdyai/botkit/blob/master/docs/middleware.md#capture-middleware)

@peterswimm 🚫
