### ISSUE TITLE
convo.beforeThread is not a function

### ISSUE THREAD

**Issue by romulorochabr** [howdyai/botkit#831]
Hi guys, Im trying to follow the example available and getting this error: TypeError: convo.beforeThread is not a function. 

Thats my function: 

    bot.createConversation(message, function(err, convo) {

        convo.setTimeout(120000)

        convo.addMessage('I have to go! Call me again if you need!','list') // TODO - TESTING

        convo.addMessage('I have to go! Call me again if you need!','timeout')

        convo.addMessage({
            text: 'I do not understand that yet. What a shame...',
            action:'default'
        },'bad_response')

        convo.beforeThread('list', function(convo, next) {
          console.log("DID SOMETHING BEFORE LIST")
          next()
        })

Someone knows why? 
Thank u in advance. 

Romulo

**Comment by benbrown** [comment]
@romulorochabr are you using the latest version of Botkit?

**Comment by romulorochabr** [comment]
Hey benbrown thats part of my package json.

"dependencies": {
    "botkit": "^0.5.2",

I took a look at the tags available and the most recent is 0.5.4. Do u thing this is the problem?

Thank u
Romulo

**Comment by peterswimm** [comment]
@romulorochabr that is correct, you need to update botkit to support those new hooks.
