### ISSUE TITLE
Regex on hears method

### ISSUE THREAD

**Issue by daniloavilez** [howdyai/botkit#832]
Guys,

I don't know if I'm making a mistake, but I'm using this regex below: 

![image](https://cloud.githubusercontent.com/assets/7416241/25746976/2aee0d16-317c-11e7-88ff-7f278061d757.png)

I don't have the response from this method.

My botkit is "botkit": "^0.5",

Thanks!

**Comment by jonchurch** [comment]
Hello! What issue are you experiencing? Whats not working?

**Comment by daniloavilez** [comment]
When I type "quero ver o cardapio" this sentence has to go to that regex on hears method. Although, it appears that it goes to fallback, the core doesn't find my method hears with my regex.

In consequence, it doesn't answer nothing because I don't have any fallback.

**Comment by jonchurch** [comment]
Try [RegExPal](www.regexpal.com) to debug regex.

**Comment by daniloavilez** [comment]
It worked!! Thanks a lot!!!
