### ISSUE TITLE
Unit Testsssss

### ISSUE THREAD

**Issue by colestrode** [howdyai/botkit#835]
I'd love to add some unit tests to Botkit to make it more stable. Adding unit tests would help by
* making PRs easier to review by making sure internal API contracts didn't change or clearly highlighting what changed
* making PRs easier to submit because developers will better understand the impact of their changes
* give developers more confidence in the code 

It would be great to capture code coverage as well.

I'd love to help out. I'm most familiar with the mocha/chai/sinon stack, but have also worked with Jest as well. If anyone has an opinion on which to use add a comment below 😄 

I think the least disruptive strategy would be several small PRs, maybe one file at a time (even parts of files as some of them are very long). 

As a bonus, once we have some unit tests in place, it would be awesome to wire up a CI server, like TravisCI or CircleCI to run automatically for PRs. Having them run automatically will give submitters early feedback on their PRs and help them resolve issues before needing a reviewer.

**Comment by peterswimm** [comment]
+1 on this. There is also 
https://github.com/gratifyguy/botkit-mock

**Comment by ouadie-lahdioui** [comment]
+1

**Comment by colestrode** [comment]
The baseline has been merged down in #857, using Jest. Tests are under `__test__`. I'm going to close this issue and start adding more tests file by file.
