### ISSUE TITLE
Botkit on The Changelog!

### ISSUE THREAD

**Issue by jerodsanto** [howdyai/botkit#837]
Howdy from [The Changelog](https://changelog.com/podcast)!

We'd love to have you on the show sometime soon. Who would be best person to join us to talk about Botkit and all the cool stuff you're up to?

_(If you haven't heard of The Changelog, it's a weekly conversation that gets to the heart of open source technologies and the people who create them.)_

Please email editors@changelog.com to coordinate. Looking forward to talking to y'all!

**Comment by peterswimm** [comment]
Hello - you can contact the howdy team directly:
info@howdy.ai
