### ISSUE TITLE
Message not recognized? Set a warning

### ISSUE THREAD

**Issue by IronTony** [howdyai/botkit#846]
Hi, I am pretty new to botkit so sorry if the question can be odd.
Is there a way to create a `.hears()` that if the inserted message on Facebook is not recognized, write a warning message?

My bot answers to 'hello' message and I want that if I write 'what's the weather like today?' the bot tells me 'Can't manage this'.
I didn't find anything about this on docs.

Any help would be appreciated.

**Comment by devhaoy** [comment]
Try `controller.on('message_received', function(bot, message) { // do something`

**Comment by jonchurch** [comment]
@peterswimm 🚫
