### ISSUE TITLE
When RTM.Start is phased away in July, how will botkit be affected?

### ISSUE THREAD

**Issue by arawal** [howdyai/botkit#848]
It has come to my knowledge that RTM.Start will be decommed around July. How will bots deployed with botkit be affected?

**Comment by peterswimm** [comment]
If you are using the latest version, we have already made a change that should carry you through the change:

More background
https://github.com/howdyai/botkit/issues/806#issuecomment-298042339

If you update your bot to the latest version of botkit before then, you should be ok!

**Comment by arawal** [comment]
Sweet thanks
