### ISSUE TITLE
Bot not listening to itself

### ISSUE THREAD

**Issue by arawal** [howdyai/botkit#849]
I have a bot that listens to other bots, but it wont listen to itself.

Below is the implementation. When I post "@botname test", it should  

```
var Botkit = require('./node_modules/botkit/lib/Botkit.js');

// Configure bot
var controller = Botkit.slackbot({
    debug: false
});

var bot = controller.spawn({
    token: process.env.token,
}).startRTM();

controller.hears(['howdy'],'ambient',function(bot, message) { 
bot.reply(message, "heard howdy")
console.log(message)
})

controller.hears(['test'],'ambient',function(bot, message) { 
bot.say(
    text: "howdy",
    channel: "CHANNELID"
)
})
```

**Comment by jonchurch** [comment]
That's called a direct mention, starting a message with `@username`. 

You are listening to ambient events, and also note thats likely only in the channels your bot is invited to. Are you able to trigger a response on simply saying `'howdy'` or `''test`? 

try this code to get your bot to responde to the input `@botName test`:

```
controller.hears(['test'],'direct_mention',function(bot, message) { 
  bot.reply(message, 'Howdy!')
})
```

**Comment by peterswimm** [comment]
@arawal did this answer your question?
