### ISSUE TITLE
Unresolved callback on FindAppropiateTeam

### ISSUE THREAD

**Issue by alsuga** [howdyai/botkit#855]
Don't exists else for this [if] (https://github.com/howdyai/botkit/blob/master/lib/SlackBot.js#L154 ) and callback is not called

**Comment by alecl** [comment]
I found fixed this in #887 before realizing it was recorded as an issue. I included the team_id there which is an added help for debugging.

**Comment by jonchurch** [comment]
@peterswimm 🚫
