### ISSUE TITLE
Interactive Message Callback: 

### ISSUE THREAD

**Issue by slambdin1** [howdyai/botkit#858]
**What's the Issue**
According to Slack's documentation, on interactive message callbacks, they return an object for the user and channel with information such as `id` and `name`. After looking into Botkit's code, we found that this information is normalized to just `id` when we have a use case to have the other information returned from Slack's API without wanting to make another API call.

**What we expect**
All the information returned from Slack's API is returned in Botkit's interactive message handler.

**Line of code that is causing the issue**
https://github.com/howdyai/botkit/blob/3b175b68cc5cdf6ae7e9d075cfefcd697a8ed965/lib/SlackBot.js#L258

**What gif most accurately describes how I feel towards this bug?**
![](https://media.giphy.com/media/8GiZ1TPvitkgU/giphy.gif)

**Comment by benbrown** [comment]
As of version 0.6, you can find the original incoming event data in `message.raw_message`
