### ISSUE TITLE
Receiving duplicate messages from controller.hears

### ISSUE THREAD

**Issue by chriskinsman** [howdyai/botkit#859]
Have looked at trying to debounce and haven't been able to effectively drop them out.  Any thoughts on how to remove the dups?

**Comment by jonchurch** [comment]
Can you supply some code please? Also what platform are you on FB or Slack?

Often this is an issue of subscribing to too many events (in the case of fb, echoes, reads, etc) and using a catchall event trigger like `message_received`.

You shouldn't even be getting duplicate messages in the first place, but without code I can't help diagnose anything.
