### ISSUE TITLE
magical default fr locale?

### ISSUE THREAD

**Issue by xpepermint** [howdyai/botkit#863]
If I require `botkit` it magically set `moment` module's locale to `fr`. How is that possible ;)?

```
const moment = require("moment");
console.log(moment.locale()) // -> en

const Botkit = require("botkit");
console.log(moment.locale()) // -> fr
```

**Comment by daniellockard** [comment]
Strange - I can't reproduce this. Do you have `fr` set as your locale anywhere else?
