### ISSUE TITLE
Handle big amount of send API calls 

### ISSUE THREAD

**Issue by adantoscano** [howdyai/botkit#865]
Hi ppl,
I get an error when I send subscription's messages at specific time.

> info: An error occurred while sending a message:  (# 613) Calls to this api have exceeded the rate limit.
debug: API ERROR { message: '(# 613) Calls to this api have exceeded the rate limit.',
  type: 'OAuthException',
  code: 613,
  fbtrace_id: 'C8eF69zBeUS' }

I thought to put a sleep minute or something like that each 100 messages but I would like to know if you do something more "stylish".

And btw, Anybody knows the calls limit?

Thanks.

**Comment by AdanTL** [comment]
I wrote this
```javascript
usuariosBal = function(func){
  controller.storage.users.all(function(err, data){  
    let chunks = data.length/100;
    let datachunk;
    let ini = 0;
    let end = 100;
    console.log(chunks);
    if(!err){
      for (var i = 0; i <= chunks; i++) {
        setTimeout(function(){
        datachunk = data.slice(ini,end);
        datachunk.forEach(function(item, index){func(item);})
        ini = end;
        end += 100;
        console.log('Chunk: '+ini)},1000*60*(i++));
      }
    }else{console.log(err.message)};
  });
}
```
func has to be a function that use a single user.

**Comment by jonchurch** [comment]
What platform's API are you referring to? FB? Slack?

**Comment by AdanTL** [comment]
@jonchurch FB
