### ISSUE TITLE
How do I know when a particular message has been delivered to user or not within the conversation ?

### ISSUE THREAD

**Issue by deepakmhr** [howdyai/botkit#866]
I am using facebook messenger and here is my use case:

I want to take feedback from user only after a conversation has end, and the conversation contains many multimedia content like video, images , and carousels. 

Code:
`
bot.startConversation(message, (error: any, convo: any) => {

                let attachment = FacebookComponent.createTemplate(attachmentType.template, templateType.generic, ads);
                convo.say(Common.formatString("contextualads.start_message"));
                convo.say({ attachment: attachment });
                convo.next();
                this.commonDialog.takeFeedback(bot, message);
            });
        });
`

But the messages are delivering randomly. 

Please help.

**Comment by KarlisJ** [comment]
I am not sure if I got your problem but it seem to me that you need to pass` require_delivery: true,` when initializing controller.

```
var controller = Botkit.facebookbot({
        access_token: process.env.access_token,
        verify_token: process.env.verify_token,
        require_delivery: true,
})
```
Just look it up in docs, hope it helps.
