### ISSUE TITLE
How to integrate a botframework (Microsoft) bot with the botframework-emulator

### ISSUE THREAD

**Issue by fbessez** [howdyai/botkit#873]
Hey, 

I am trying to set up a Microsoft Teams bot with botkit and I am having trouble running the sample bot you provided [here](https://github.com/howdyai/botkit/blob/2700aad94fdd0f6f714f9624f0cac2c751b25387/examples/botframework_bot.js) with the botframework-emulator. Any help on how to accomplish this would be greatly appreciated!

Thank you!

**Comment by peterswimm** [comment]
Can you expand on what problems you are having?

**Comment by fbessez** [comment]
I was actually just setting up the websocket incorrectly. Sorry about that.
