### ISSUE TITLE
Slack RTM Websocket failure [help wanted]

### ISSUE THREAD

**Issue by ruhi1999** [howdyai/botkit#875]
My bot can't maintain a stable RTM websocket connection -- it's constantly opening and closing and often fails to reconnect. This issue just developed, as the websocket connection was stable and fine before. I've tried token cycling and testing other causes. My bot still uses rtm.start as opposed to the newer rtm.connect; would updating the framework change/help the problem? Right now the connection doesn't work regardless of the bot I run.

**Comment by hipitihop** [comment]
@ruhi1999 I hope those aren't real tokens in your screenshot. If they are, then can I humbly suggest you rotate them as soon as possible. It's also probably not a good idea to embed them in code.
