### ISSUE TITLE
How to easily get a user's real name when they execute a slash command

### ISSUE THREAD

**Issue by scolegrove** [howdyai/botkit#876]
I am just learning botkit and bot programming in general and I have a Slack slash command that when a user executes the command the bot gives the user a random personalized greeting. Currently my code is basically this

controller.on('slash_command', function (slashCommand, message) {
 slashCommand.replyPublic(message, greetingStart + message.user_name + " " + greetingEnd);
}

this approach gives me a message where my bot responds to the user by its username, but I need the bot to respond the users real first name. Is there a way I can easily do this without any crazy api calls?

**Comment by peterswimm** [comment]
You can have your bot respond _with_ the user's real name by using something like `Hello <@${user}>` in a reply.

**Comment by scolegrove** [comment]
How  can do that in a slashCommand.replyPublic()? For complicated reasons the person I am building this for wants a bot to say hello in a /nameofbot hi command. From what I've been reading though you can't actually get extended information like that without an RTM connection (Which I think would conflict with the slashcommand?). I have also tried to just call the slack api, I can get it to work in postman but it's always undefined when ran in the bot code.

**Comment by peterswimm** [comment]
You can read some examples on formating replypublic commands here:
https://api.slack.com/tutorials/easy-peasy-slash-commands
