### ISSUE TITLE
How to look up information submitted by another team member?

### ISSUE THREAD

**Issue by amandakgordon** [howdyai/botkit#878]
Hi there,

I'm trying to look up data linked to an customer. I've used the 'create profile' script to create the customer record, and I'm trying to use this (https://blog.howdy.ai/build-a-bot-store-data-for-your-users-2e91fe7023d7) but I think I need a conditional action that will match a search term (i.e. name or email) with whatever is in my database. 

Can you recommend a good way to do so? This is my first time using BotKit, really appreciate the help.

Cheers,
Amanda

**Comment by peterswimm** [comment]
There is a companion article that details how to use stored data in your scripts:

https://blog.howdy.ai/build-a-bot-data-powered-conversations-d14991714ac1
