### ISSUE TITLE
Can't run cisco-starter-spark bot

### ISSUE THREAD

**Issue by AlexandreBotKurmi** [howdyai/botkit#890]
Hello,
I have followed the docs to install botkit on my server.
I extracted the project, created a new app, set all my .env variable unless PORT.
However when I start the bot with `node .` I got this : 
`Initializing Botkit v0.5.4
info: ** No persistent storage method specified! Data may be lost when process shuts down.
info: No DASHBOT_API_KEY specified. For free turnkey analytics for your bot, go to https://www.dashbot.io/ to get your key.
one flight: attempted to invoke _getBinding while previous invocation still in flight
one flight: attempted to invoke _getBinding while previous invocation still in flight
`
then it write his entity and nothing.
Nevertheless in BotkitStudio the bot doesn't appears as deployed. In my spark, the bot doesn't respond.

I have also tried to use the master project but the only difference is that it set the webhook up.

Does someone know where I am wrong ?

**Comment by AlexandreBotKurmi** [comment]
Thank to peterswimm I have found one cause of the problem, the bot server must be with a valid certificate SSL and not a self-signed certificate.

**Comment by peterswimm** [comment]
That is correct, also make sure you have all the tokens in place:
https://github.com/howdyai/botkit/blob/master/docs/provisioning/cisco-spark.md#4-run-your-bot-with-variables-set
