### ISSUE TITLE
Slash command request is received by webserver but doesn't trigger `slash_command`

### ISSUE THREAD

**Issue by ifreecarve** [howdyai/botkit#893]
Despite what seems to be a properly configured slack app (according to https://api.slack.com/tutorials/easy-peasy-slash-commands), the following bot does not work.  

`minimal_botkit.js`
```javascript
// boilerplate suggested at https://api.slack.com/tutorials/easy-peasy-slash-commands
var Botkit = require('botkit');

var appConfig = {
    clientId: process.env.SLACK_CLIENT_ID,
    clientSecret: process.env.SLACK_CLIENT_SECRET,
    scopes: ['commands']
};

var controller = Botkit.slackbot({ debug: true }).configureSlackApp(appConfig);

controller.setupWebserver(process.env.PORT, function (err, webserver) {
    if (err) process.exit(1);

    webserver.use(function (req, res, next) {
        console.log("Incoming web request: " + JSON.stringify(req.body, null, 2));
        next();
    });
    controller.createWebhookEndpoints(webserver);
});

controller.on('slash_command', function (bot, message) {
    console.log("slash_command callback fired -- SUCCESS");
    bot.replyPublic(message, "received `" + message.command + " " + message.text + "`");
});
```

<img width="550" alt="screen shot 2017-06-21 at 7 16 41 am" src="https://user-images.githubusercontent.com/583459/27381688-caa8b096-5651-11e7-8fd7-d9eb52312280.png">

Its output:
```
$ SLACK_CLIENT_ID=11111111.22222222  SLACK_CLIENT_SECRET=abcdefg1234567890 SLACK_VERIFICATION_TOKEN=redacted PORT=4390 node minimal_botkit
Initializing Botkit v0.5.4
info: ** No persistent storage method specified! Data may be lost when process shuts down.
debug: Setting up a handler for spawned
debug: Setting up a handler for heard_trigger
debug: Setting up a handler for command_triggered
debug: Setting up a handler for remote_command_end
info: ** Setting up custom handlers for processing Slack messages
debug: Setting up a handler for message_received
info: ** Configuring app as a Slack App!
debug: Setting up a handler for slash_command
info: ** Starting webserver on port 4390
info: ** Serving webhook endpoints for Slash commands and outgoing webhooks at: http://0.0.0.0:4390/slack/receive
Incoming web request: {
  "token": "redacted",
  "team_id": "T024WU76V",
  "team_domain": "boston",
  "channel_id": "D3BFX94CE",
  "channel_name": "directmessage",
  "user_id": "U3BG8NXFH",
  "user_name": "ifreecarve",
  "command": "/macramoji",
  "text": "foo",
  "response_url": "https://hooks.slack.com/commands/T024WU76V/201087949059/KZ3pYvWejktRd8nJ4af6tWyE"
}
```
<img width="517" alt="screen shot 2017-06-21 at 6 59 23 am" src="https://user-images.githubusercontent.com/583459/27381797-284ffcc2-5652-11e7-8c17-f78dd14479eb.png">

I'm fairly certain that my slack app is configured correctly; the following non-botkit code works and produces an echo.

`minimal_slack_express.js`
```javascript
var slackExpress = require("slack-express");

slackExpress.slash('/macramoji', function (payload, message) {
    console.log("OK! " + JSON.stringify(payload, null, 2));
    message({ text: "received `" + payload.raw.command + " " + payload.raw.text + "`" });
});

slackExpress.start();
```

`slack-express` listens on `/`:
<img width="538" alt="screen shot 2017-06-21 at 7 12 15 am" src="https://user-images.githubusercontent.com/583459/27381548-418daf1e-5651-11e7-9c1d-fa29c01043ed.png">

Its output:
```
$ SLACK_CLIENT_ID=11111111.22222222  SLACK_CLIENT_SECRET=abcdefg1234567890 SLACK_VERIFICATION_TOKEN=redacted PORT=4390 NODE_ENV=development APP_NAME=macramoji node minimal_slack_express
#!/slack-app> http://localhost:4390
OK! {
  "ok": false,
  "raw": {
    "token": "redacted",
    "team_id": "T024WU76V",
    "team_domain": "boston",
    "channel_id": "D3BFX94CE",
    "channel_name": "directmessage",
    "user_id": "U3BG8NXFH",
    "user_name": "ifreecarve",
    "command": "/macramoji",
    "text": "foo",
    "response_url": "https://hooks.slack.com/commands/T024WU76V/201154960946/ZPc0mFGvKZmaa8ByNbDCLLJb"
  },
  "account": {},
  "message": {
    "token": "redacted",
    "response_url": "https://hooks.slack.com/commands/T024WU76V/201154960946/ZPc0mFGvKZmaa8ByNbDCLLJb",
    "channel_id": "D3BFX94CE",
    "channel_name": "directmessage",
    "command": "/macramoji",
    "text": "foo"
  },
  "text": "find method returned an error"
}
```
<img width="518" alt="screen shot 2017-06-21 at 7 04 29 am" src="https://user-images.githubusercontent.com/583459/27381303-4d539404-5650-11e7-91ae-3dfed2350589.png">

Other details:
```
OSX 10.12.5 (16F73)
node v7.4.0
npm 4.0.5
└─┬ botkit@0.5.4
  └── express@4.15.3 
```

**Comment by ifreecarve** [comment]
I can confirm that some part of the webserver is working in botkit, because if I use the slack-express endpoint of `/` instead of `/slack/receive`, the Slack client (properly) picks up the 404 from the webserver:
<img width="522" alt="screen shot 2017-06-21 at 7 26 13 am" src="https://user-images.githubusercontent.com/583459/27382039-2f4747b4-5653-11e7-9287-0cbb1be16d5a.png">

**Comment by benbrown** [comment]
We figured out this issue!

For Slack bots to work, you have to go through the oauth process AND make sure you are using a storage system to persist team details.  In the process of receiving a webhook, Botkit validates the team information against the database. If the team does not exist (IE, botkit does not think the team has installed the app), the webhook is rejected.

**Comment by ifreecarve** [comment]
I'm not sure whether this issue is resolved.  I'm supplying the token, which is tied to the team.  If botkit needs it so badly, a simple API call using my supplied token could retrieve it.  Right?  I mean, the slack-express example works and it uses the same input information.

**Comment by benbrown** [comment]
Botkit no longer supports slash commands on "custom integrations" - the type where you pass in a single team token. This feature is marked by Slack for deprecation.

It is required to use the oauth login if you want to offer Slash commands in your app.

**Comment by ifreecarve** [comment]
I think that's what I'm using.  Is this the deprecated token type you're referring to?

![screen shot 2017-06-22 at 3 05 47 pm](https://user-images.githubusercontent.com/583459/27451285-8823a954-575c-11e7-896b-405a2bd13c24.png)
