### ISSUE TITLE
Botkit carousel for Microsoft Bot Framework and other channels

### ISSUE THREAD

**Issue by mateiana13** [howdyai/botkit#894]
Hi, 
I am working on trying to create a carousel of cards and I have tried to create it by putting multiple array of attachments as shown below.

I am not sure how to display a carousel of cards and any help would be much appreciated.

I can not find any documentation online either.

Many Thanks

Ana

```
bot.reply(message, {
                attachments: [{
                    contentType: 'application/vnd.microsoft.card.hero',
                    content: {
                        title: "Hi! Welcome to Vauban Academy",
                        subtitle: "The perfect place to start your career",
                        text: "How can we help you?",
                        images: [{
                            url: "http://www.dezvoltarea-carierei.com/media/images/o/Vauban_200x150.jpg"
                        }],
                        buttons: [{
                            type: "imBack",
                            title: "Contact Us",
                            value: "Contact Us"
                        }, {
                            type: "imBack",
                            title: "Careers",
                            value: "Careers"
                        }, {
                            type: "imBack",
                            title: "Became Partner",
                            value: "Became Partner"
                        }]
                    }
                },{
                    contentType: 'application/vnd.microsoft.card.hero',
                    content: {
                        title: "Hi! Welcome to Vauban Academy",
                        subtitle: "The perfect place to start your career",
                        text: "How can we help you?",
                        images: [{
                            url: "http://www.dezvoltarea-carierei.com/media/images/o/Vauban_200x150.jpg"
                        }],
                        buttons: [{
                            type: "imBack",
                            title: "Contact Us",
                            value: "Contact Us"
                        }, {
                            type: "imBack",
                            title: "Careers",
                            value: "Careers"
                        }, {
                            type: "imBack",
                            title: "Became Partner",
                            value: "Became Partner"
                        }]
                    }
                }
                ]
            }); //end bot.reply()
```

**Comment by peterswimm** [comment]
What platform are you building for? Not all platforms support carousels, but your code appears correct for those that do.

**Comment by robinsonc** [comment]
bot.reply(message, {
               **attachmentLayout:"carousel",**
                attachments: [{
                    contentType: 'application/vnd.microsoft.card.hero',
                    content: {
                        title: "Hi! Welcome to Vauban Academy",
                        subtitle: "The perfect place to start your career",
                        text: "How can we help you?",
                        images: [{
                            url: "http://www.dezvoltarea-carierei.com/media/images/o/Vauban_200x150.jpg"
                        }],
                        buttons: [{
                            type: "imBack",
                            title: "Contact Us",
                            value: "Contact Us"
                        }, {
                            type: "imBack",
                            title: "Careers",
                            value: "Careers"
                        }, {
                            type: "imBack",
                            title: "Became Partner",
                            value: "Became Partner"
                        }]
                    }
                },{
                    contentType: 'application/vnd.microsoft.card.hero',
                    content: {
                        title: "Hi! Welcome to Vauban Academy",
                        subtitle: "The perfect place to start your career",
                        text: "How can we help you?",
                        images: [{
                            url: "http://www.dezvoltarea-carierei.com/media/images/o/Vauban_200x150.jpg"
                        }],
                        buttons: [{
                            type: "imBack",
                            title: "Contact Us",
                            value: "Contact Us"
                        }, {
                            type: "imBack",
                            title: "Careers",
                            value: "Careers"
                        }, {
                            type: "imBack",
                            title: "Became Partner",
                            value: "Became Partner"
                        }]
                    }
                }
                ]
            }); //end bot.reply()

This code worked for me.

**Comment by mateiana13** [comment]
Thank you so much!

**Comment by peterswimm** [comment]
Closing a resolved, thanks @robinsonc !
