### ISSUE TITLE
convo.repeat() is not working if there are more questions into current thread.

### ISSUE THREAD

**Issue by KarlisJ** [howdyai/botkit#897]
This looks like a bug to me. Tested a lot and found that if I use 
```
convo.sayFirst('something wrong, lets repeat');
convo.repeat();
convo.next();
```
it repeats the question only if it is the last into queue of given thread. If there are any more questions (or messages) then user get the sayFirst message but then jumps to next question.

As I am creating single thread for every question I was able to use `convo.trasitionTo('current_thread', 'something wrong, lets repeat') `where current_thread is the one where the question is. Still, something is not right with that `convo.repeat()`

**Comment by Mickey248** [comment]
this is a good thing

**Comment by tdelam** [comment]
I noticed the same thing here as well... any suggestions or workarounds? The transitionTo workaround is not displaying the message, the question just repeats.

**Comment by benbrown** [comment]
You should definitely not use sayFirst and repeat in the same turn.  Both modify the message queue - and in fact, repeat will call sayFirst in some cases.
