### ISSUE TITLE
Botframework integration future? 

### ISSUE THREAD

**Issue by bilby91** [howdyai/botkit#898]
Hello, 

First I want to congrat on the awesome work on Botkit, it makes building bot super easy!!

Having said that, I have some questions regarding the Botframework integration. I guess that the main idea behind this integration is to support all the non-botkit available integration via Botframework directly.

The idea is to start porting the implementations that Botframework does have but Botkit doesn't ? Like Telegram, MS Teams (don't really know if this is possible), etc ?

Thanks!

**Comment by benbrown** [comment]
@bilby91 Are you asking whether or not we would implement narrower, more platform-specific adapters for platforms otherwise supported by BotFramework? 

If so, the answer is YES.

**Comment by bilby91** [comment]
@benbrown Thanks!
