### ISSUE TITLE
Case sensitive "hears"

### ISSUE THREAD

**Issue by davedelong** [howdyai/botkit#90]
It'd be nice if there were a way to make `.hears` have a case sensitive option. That way our bot can be a proper grammar nazi. 😈

**Comment by bobvanluijt** [comment]
You can do this with a regex.

```
"/(?=SomETHinG).*(?=FooBar)" // matches exactly
"/(?=SomETHinG).*(?=FooBar)/i" // matches also something and foobar... 
```

**Comment by mvaragnat** [comment]
I tried controller.hears("/help/i", ...
it did not work

I have to use controller.hears(['^help', '^Help'],...

What am I doing wrong?

**Comment by bobvanluijt** [comment]
@mvaragnat you can do two things.
1) If you want the bot the respond to _any_ form of 'help' just use `.hears(['help'])`
2) If 1 isn't suitable, use a regex (see my previous answer)

In you case option 1 seems ok.

PS:
If you have multiple `hear()` functions with 'help' you need to use a regex too.
