### ISSUE TITLE
getting encoding message issue when sent ordinary text

### ISSUE THREAD

**Issue by hbakhtiyor** [howdyai/botkit#907]
when i sent `Ooops, something went wrong!`, it displays `Ooops, something went wrong%21`
the `!` char encoded to `%21`

how to resolve it?

**Comment by peterswimm** [comment]
Can you post a snippet of your code?

**Comment by hbakhtiyor** [comment]
i used the [sample](https://github.com/DEGoodmanWilson/easy-peasy-slash-command-app/issues) using with `replyPrivateDelayed` & `replyPublicDelayed`

**Comment by hbakhtiyor** [comment]
@peterswimm any ideas?

**Comment by peterswimm** [comment]
And you didnt edit any code? Did you follow the instructions as he posted on the medium article? 
https://api.slack.com/tutorials/easy-peasy-slash-commands

My guess without seeing your project that either you copy pasted some bad code, or missed a step.

**Comment by hbakhtiyor** [comment]
hmm, just use `Delayed` version, you'll reproduce it, I properly followed and configured!

**Comment by hbakhtiyor** [comment]
@peterswimm did you try it?

**Comment by peterswimm** [comment]
@hbakhtiyor I did not! You might also try posting the quesiton in our deve community if you are 100% sure about your code and Slack side setup

**Comment by moriczgergo** [comment]
Same issue here. :/

**Comment by Oliverr** [comment]
Any more on this? Having encoding issues with Slack and the / character.
1/1 becomes 1&#47;1

**Comment by hbakhtiyor** [comment]
up

**Comment by adantoscano** [comment]
Have you tried with this #240 ?

**Comment by cooperka** [comment]
The issue description here is ambiguous, but I'm encountering this when **sending** messages from the bot. Some random outgoing messages will be url-encoded, with normal characters like apostrophe coming out as `&#39;`.

My workaround is to use a `send` middleware to decode:

```js
import { decode } from 'he';

controller.middleware.send.use((bot, message, next) => {
  // Decode outgoing messages to make sure there are no weird URI encoded characters.
  // Encoding happens automatically sometimes for unknown reasons.
  message.text = decode(message.text);

  next();
});
```
