### ISSUE TITLE
Posting a reply from the companion skills js file of a studio script

### ISSUE THREAD

**Issue by MGTHEBOSS** [howdyai/botkit#910]
I have divided a conversation into two parts. The first part, which collects data from the user is in a studio script. The second part will be in the studio script's companion skills js file. The documentation does not explain how I can post a reply from inside the `convo.successful()` of a companion skills js file. In order to understand the situation, please see the situation comment below.

```
controller.studio.after('script_name', function(convo, next) {

        console.log('AFTER: script_name');

        // handle the outcome of the convo
        if (convo.successful()) {

            var responses = convo.extractResponses();
            // do something with the responses
           //situation: I have sent the responses to an api, received json data from the api, parsed the json, extracted data, and prepared the bot's reply. 

        }

        // don't forget to call next, or your conversation will never properly complete.
        next();
    });


```

**Comment by jonchurch** [comment]
Try convo.say('message') after your api call resolves. Not sure if itll work but thats how Id expect it to work. 

Note, you are attempting to send a message after a script, a whole script, finishes. This could be achieved with threads in a more clear way perhaps. 

My confusion is, if you convo.say or convo.addmessge after a script or convo ends, where does the message? Does it land on the message queue of a dead script? What thread (if any) is your user in during an after script hook?

You dont have direct access to the bot, so you cant use a bot.say just based on the cb signature of after script. 

@benbrown any input here?

**Comment by MGTHEBOSS** [comment]
@jonchurch I checked `convo.say` before posting the issue. It does not work.

**Comment by MGTHEBOSS** [comment]
I discovered it's working if used in a `controller.studio.validate`. There has to be a better solution.

**Comment by MGTHEBOSS** [comment]
I have found another alternate solution. Putting the `convo.say` inside the `controller.studio.beforeThread` of a new thread called end, created in the studio. Jump to end, at the end of branch threads. You can delete any message in that thread in studio as using `convo.say` in the code will queue the message after the already existing message. 
```
controller.studio.beforeThread('accurate_provider_data','end', function(convo, next) {

        /// do something fun and useful
        // convo.setVar('name','value');

        console.log('In the script *accurate_provider_data*, about to start the thread *end*');

        var responses = convo.extractResponses();
        //do something with the responses
        //build the result reply
        //put convo.say here

        // always call next!
        next();
    });


```
