### ISSUE TITLE
facing issue with 'message_received' event

### ISSUE THREAD

**Issue by vipragupta** [howdyai/botkit#913]
Hi,

I have made a slack bot using your library. I added my bot to a channel and I want it to listen to all the messages that are sent in that channel irrespective of, if it's sent to my bot or not. I found out that I can use 'message_received' event for the same. I tried using that, but although in logs I can see that it is receiving my msg, the control doesn't come to the controller.hears and hence no response is sent back.
I tried using ambient too, but it doesn't work either. Any suggestion will be appreciated. 
Thank you.

Here's my code:

```javascript
controller.hears(['(.*)'], 'message_received', function (bot, message) {
    var msg = message.match[1];
    controller.storage.users.get(message.user, function (err, user) {
        if (!user) {
            user = {
                id: message.user,
            };
        }
        controller.storage.users.save(user, function (err, id) {
            bot.reply(message, "Hi there, how are you!");
        });
    });
});
```

This is what the log say when I send a message:
```debug: RECEIVED MESSAGE
debug: CUSTOM FIND CONVO U5MAXD49Y D5MCF15NG
debug: DEFAULT SLACK MSG RECEIVED RESPONDER
debug: RECEIVED MESSAGE
debug: CUSTOM FIND CONVO U5MAXD49Y D5MCF15NG
debug: DEFAULT SLACK MSG RECEIVED RESPONDER
debug: RECEIVED MESSAGE
debug: CUSTOM FIND CONVO undefined D5MCF15NG
debug: DEFAULT SLACK MSG RECEIVED RESPONDER
debug: RECEIVED MESSAGE
debug: CUSTOM FIND CONVO undefined undefined
debug: DEFAULT SLACK MSG RECEIVED RESPONDER
```

**Comment by benbrown** [comment]
All messages in Slack are either `direct_message` `direct_mention` `mention` or `ambient`.

**Comment by vipragupta** [comment]
Ahh! that makes sense. Thank you so much.
