### ISSUE TITLE
problem while installing the package

### ISSUE THREAD

**Issue by akoenig** [howdyai/botkit#915]
Installing the package fails currently (using Node.js v8.1.2 with npm 5.0.3):

`npm i botkit`

```
npm ERR! code E404
npm ERR! 404 Not Found: @ciscospark/common-timers@1.1.9
```

**EDIT:** The previous release (`0.5.4`) installs flawlessly

**Comment by dreki** [comment]
This issue presents itself confusingly to new users -- FYI. You can only find out the actual cause by going into the new console.

Note that when using botkit `0.5.4` in package.json, you must explicitly only use that version; you can't use the `"^..."` syntax. This works: `"botkit": "0.5.4",`

**Comment by benbrown** [comment]
This has been resolved by our friends at Cisco. Try again!
