### ISSUE TITLE
facebook_referrals or messaging_referrals ?

### ISSUE THREAD

**Issue by lsshawn** [howdyai/botkit#916]
My controller didn't pick up the ref parameter that is added to the URL, e.g. `m.me/botname/?ref=params`

Is there any example to show how this is used in botkit?

**Comment by jonchurch** [comment]
Can you share an example of the controller listener thats not getting the ref param?

You should be able to do something like this:

```
controller.on('facebook_referral', function(bot, message) {
 console.log(message.referral)
})
```
