### ISSUE TITLE
Get user info from outgoing message

### ISSUE THREAD

**Issue by thepavangollapalli** [howdyai/botkit#921]
I'm working with the Send and Receive middleware on a Slack chatbot and trying to store the user id of an outgoing message, but wasn't able to find any good ways to do it. I've found methods that use the api like 
```
bot.api.users.profile.get({ user: msg.user }, function(err, response) {
  console.log(response);
});
``` 
or 
```
bot.api.users.info({user: msg.user}, (error, response) => {
  let {name, real_name} = response.user;
  console.log(name, real_name);
  user = real_name;
});
``` 
but msg.user only exists for incoming messages in the Receive middleware and so those solutions do not work for the Send middleware. I was able to get the user id by editing the slack worker so it manually returns the destination user id, but any non-hacky solutions would be great!

**Comment by shashvattrip** [comment]
@thepavangollapalli did you figure this out? I need to mutate my outbound messages and user info is absolutely critical part of this process.

**Comment by jonchurch** [comment]
What user information specifically are you unable to find? Can you share
some code?

User id is not explicitly needed to deliver a message, but is usualy
hanging out on the message depending on how that message is sent.

You are looking to augment the Send middleware, and want access to the
slack userid in that middleware, correct?

**Comment by thepavangollapalli** [comment]
Go to `node_modules/botkit/lib/Slackbot_worker.js` and find the function `bot.replyPublic`. The functions following replyPublic all have a src object passed in that contains userid and several other things you can attach to the outgoing message object, simply by adding something like `msg.user = src.user` after the line `msg.channel = src.channel` that is in each function.

**Comment by thepavangollapalli** [comment]
Update: I was able to get the information I needed by using the Heard middleware instead!
