### ISSUE TITLE
controller.trigger is running before button is clicked!

### ISSUE THREAD

**Issue by fbessez** [howdyai/botkit#922]
Hi all,

I am creating a bot for Microsoft Teams via Botkit's integration with the Bot Framework.
Desired Action: I would like a button to trigger an event upon being pressed.
Resulting Action: Upon loading the card, the value is evaluated and the action is triggered before the button is even pressed.  Basically, just including this button in my card triggers the action as opposed to it triggering after being selected. 

Botkit Version: 0.5.1
`  let previous_button = {
                        type: 'postBack',
                        title: 'Previous Timesheet',
                        value: controller.trigger(action, params)
                      }`

**Comment by Jamiewarb** [comment]
You're calling the `controller.trigger()` method when you create the button. Instead, `value` should be the actual string you want to display on the button.

Instead, you want to give that an actual value, then use the `interactive_message_callback` to handle the specific button press.

```
controller.on('interactive_message_callback', function(bot, trigger) {
    // examine the callback_id and the actions name/value to decide what this button is, then perform logic here
});
```

**Comment by Jamiewarb** [comment]
You're calling the `controller.trigger()` method when you create the button, and trying to set its return value to the button's `value` string. It's calling your method immediately because of this.

Instead you should use the `facebook_postback` event to handle the specific button press and examine the payload to determine what to do with it.

```
controller.on('facebook_postback', function(bot, message) {

    if (message.payload == 'chocolate') {
        bot.reply(message, 'You ate the chocolate cookie!')
    }

});
```

Snippet from the documentation: https://github.com/howdyai/botkit/blob/master/docs/readme-facebook.md#using-structured-messages-and-postbacks

**Comment by fbessez** [comment]
Hey @peterswimm, thank you for helping. Unfortunately, neither of those solutions seem to work.  The controller does not respond to controller.on('interactive_message_callback') because this type of action / event is not compatible with Microsoft Teams. Let me know if I misunderstood you!

**Comment by peterswimm** [comment]
@fbessez im not attempting to solve your request, I am just trying to tag it to make it easier to find when we review issues, or a member of the community is trying to chime in.

Are you saying that this is more of a feature request, that you have confirmed does not currently work in bot builder?

**Comment by peterswimm** [comment]
We now support teams directly!

https://git.botkit.ai/benbrown/teamsbot/blob/teams/docs/readme-teams.md
