### ISSUE TITLE
[Studio] Using {{vars}} to load Carousel Element item's image url

### ISSUE THREAD

**Issue by ellismiranda** [howdyai/botkit#927]
It could be that I missed something in my testing, but using {{vars.my_variable_name}} in the Image Url field under a new Carousel Element doesn't count as a valid url.

I tried storing and loading in a url that I know works, when formatted as an attachment and passed with bot.reply(message, {attachment: myAttachment});, but without any success.
{{vars}} work everywhere else except here, from what I can tell.

Can someone confirm if it works and I just misused it repeatedly, or that maybe it will be included as a feature?

**Comment by benbrown** [comment]
This should be fixed with the latest Botkit!

**Comment by ellismiranda** [comment]
@benbrown thank you!!

**Comment by benbrown** [comment]
@ellismiranda I should have said -- we will be deploying a fix for this to Botkit Studio this week!

**Comment by ellismiranda** [comment]
@benbrown No problem! Just knowing this means I can better work around it for the future! :)
