### ISSUE TITLE
No listen scope cover replies to uploaded images in Slack

### ISSUE THREAD

**Issue by tiagosiebler** [howdyai/botkit#928]
BotKit version: 0.5.5
Operating system version: N/A

I'm working with Botkit integrated with Slack, and I've noticed none of my triggers are firing when they happen in a conversation within an uploaded image.

Steps to reproduce:

1. Setup controller.hears on the scope 'ambient'.
2. Upload an image to a channel.
3. Reply to the image with something that should fire the trigger from step 1.

Is this a known issues? Is there an event I need to listen to in addition to this?

Thanks!

**Comment by tiagosiebler** [comment]
Tried adding file_comment_added as well, from slack's events list, no luck.

**Comment by jonchurch** [comment]
Hmm it might not be receiving the message as a normal message. It is likely
emitting a file_comment_added event.

Add a controller.on to check for that.

Not sure how file comments are threaded off the top of my head, it might be
a different api call to comment on a file, vs messaging a channel id.

**Comment by tiagosiebler** [comment]
@jonchurch do you know where the listen-scope in botkit's controller.hears actually comes from? What do these kind of parameters match against, where in the framework? 'ambient,direct_message,direct_mention,mention'

I wonder if there's some kind of hardcoding that may be extendable to also allow reactions to file_comment_added events from slack, or if I explicitly have to leverage controller.on. Ideally I'd like to treat file comments similar to standard messages, in that matching controller.hears functions trigger in the scopes defined therein (e.g mention vs ambient).
