### ISSUE TITLE
Api calls scale in studio billing page needs correction

### ISSUE THREAD

**Issue by MGTHEBOSS** [howdyai/botkit#929]
It is showing almost half of allowed api calls (500) remaining, whereas 456 calls have already been made.
![screencapture-studio-botkit-ai](https://user-images.githubusercontent.com/3612991/28359257-3ac7ceea-6c8f-11e7-9805-8f17cfbf3daa.jpg)

**Comment by peterswimm** [comment]
Thanks for reporting this, I will create an internal ticket to investigate.
