### ISSUE TITLE
If a controller.hears fires, no other matching controller.hears will fire. Looking for ways around this.

### ISSUE THREAD

**Issue by tiagosiebler** [howdyai/botkit#930]
Thought it might help to first explain the use-case here: I'm using controller.hears to look for references to various systems we use together. 

One module might be related to our development system, so might look for IDs matching BUG12345678, and will query the dev system for related info when that's seen. That module is dedicated to all listeners and functions related to the dev system, and any actions that might need to be taken with that system.

Another module might be related to our support case system, so might look for IDs matching Case1234456 and will query the support system to bring up a snapshot of related info, similar to the dev system module. The systems are completely different, so it's cleaner to have a dedicated module per system.

I'm using regex with controller.hears in each system's module within my slack bot to look for these system specific references. 

### Observation:
What I've noticed is that if more than one matching controller.hears exists, only one of them will actually fire. Not sure in what order. For example, if this kind of message comes up:

> For case 13245667 I'm not sure whether it fits to BUG123456 or BUG4958343, can anyone clarify?

### Desired result:
Right now, the case reference will be seen, and the slack bot will only trigger the controller.hears for the case ref. What I'm hoping to do is that any matching controller.hears trigger will fire, even if there's more than one. So the bot would:

- Run logic case 13245667.
- Run logic on BUG123456.
- Run logic on BUG4958343.

Anyone then getting involved in that discussion has immediate snapshots on all 3 matching references, without needing further action. 

### Questions:

- Can this be achieved with botkit right now? 
- Is there perhaps a flag preventing other controller.hears from firing on a single message, if a matching controller.hears already fired?

I guess the easiest way to do this right now is making a global controller.hears that reacts to every event, and then asking submodules if they want to react to that message.text, but that means a redesign contradicting the lovely modular capabilities of controller.hears only firing against matching messages via regex.

**Comment by jonchurch** [comment]
The first listener triggered, is the one that is run. Top to bottom. That
is currently expected behavior.

Sounds like you want entity extraction, which is what regex matching can
offer.

Extract (match with regex, in a single regex) all instances of strings that
you are interested in.

In the handler, you will have access to 1 ambig match (13245667) and the
two bug matches, you can then run whatever code you like, querying all
three at once or however you choose.

Current botkit behavior, one listener maps to one message.

**Comment by tiagosiebler** [comment]
Hmm that's what I feared, so to fire any matching trigger I really need one global controller.hears for all potentially matching subtriggers, and then separate that within. 

Any other ideas to chain on other potentially matching listeners? Or is the best way to group triggers into a bigger listener?

**Comment by jonchurch** [comment]
@tiagosiebler see this PR and my fork to get this working for you. [Docs](https://github.com/jonchurch/botkit/blob/hears-control/docs/readme.md#control-flow) to go with the change.

**Comment by tiagosiebler** [comment]
@jonchurch just got round to trying it, this is great, works exactly as I hoped and I don't need to break the modular design. Hope to see the pull request officially approved! Thanks a ton!

**Comment by tiagosiebler** [comment]
@peterswimm Hi Peter, I saw you closed this. Any ideas if/when PR #934 is going to be merged? It's extra work each time I update botkit to re-do the change manually, would love for this to be part of the main branch. Thanks!

**Comment by peterswimm** [comment]
@tiagosiebler follow the linked pr for updates! I closed because it seemed your issue was resolved for now.
