### ISSUE TITLE
Slack - Interactive Message URL is not getting invoked

### ISSUE THREAD

**Issue by venkates77** [howdyai/botkit#931]
I have a bot (interactive style with buttons presented in conversation), which is integrated with slack and during the conversation when i press the buttons i get the following error.

``Darn – that didn't work (error message: `404_client_error`). Manage the app at Zeebo.``

In https://api.slack.com/apps/A60U92G5A/interactive-messages, I have configured the correct URL (https url) and this URL is exposed in the internet and i can invoke this from postman successfully. Not sure whats going on at slack end which results in 404_client_error.

**Comment by venkates77** [comment]
@jonchurch @benbrown - I saw your reply on a similar issue. Do you have any thought on how to debug this ?

**Comment by peterswimm** [comment]
Did you check that the slack app settings are setup correctly?

https://github.com/howdyai/botkit/blob/master/docs/provisioning/slack-events-api.md

Can you post some example code?

**Comment by sarathi0333** [comment]
@venkates77 You solved it? I too get the same issue. Can you help me?

**Comment by rfisch** [comment]
Is there any update on a good way to trouble shoot or debut this behavior. I am running into the same issue.  I set a button on an attachment and the same endpoint is reached by a context menu command call, or a / slash command, but the button action does not fire back to the end point.

**Comment by peterswimm** [comment]
@Sateesh77 this is probably related to your dev environment - where are you running the bot? Try glitch if you are still stuck!
