### ISSUE TITLE
It will go offline unless BOT of other team use it one day ("add to slack" button) 

### ISSUE THREAD

**Issue by eric9876** [howdyai/botkit#932]
botkit v0.5.4

Slack,
We distributed My team(A)'s BOT(botkit) to other teams(B) using the slack button ("add to slack").

the team(B) did not use the bot for about a day,
 That bot was offline.

then,
 On my team(A), it was online.

Why do you know if other teams(B) go offline?
Are there countermeasures?

**Comment by jonchurch** [comment]
Well, your issue as youve stated it is that the bot's presence indicator is
sometimes off and sometimes on.

In the slack app settings, you can make your bot appear always online, its
a setting.

If your issues is your bot not responding, that would be a separate issue
Id need to see code for.
