### ISSUE TITLE
regex - \b and ^()?

### ISSUE THREAD

**Issue by amplicity** [howdyai/botkit#94]
Simple issue, I'd like to be able to specify the difference between `hi`  and `hire`..two separate `controller.hears()` functions with different use cases. I've tried `controller.hears('\bhi' .....` and `controller.hears('^hi?' .....` with no luck. any reason why these operators wouldn't work?

**Comment by Glowbal** [comment]
Try `\bhi\b`

**Comment by amplicity** [comment]
I tried that and it also didn't work.

**Comment by chrisbodhi** [comment]
How about `^hi$` for 'hi'?

**Comment by mlallinder** [comment]
Try "\\b", I believe "\b" equates backspace. You need to escape it with an extra \, this worked for me.

**Comment by mlallinder** [comment]
Try `\\bhi\\b`, `\b` equates to backspace.  Adding another \ will escape the first \ so it actually equates to `\b` passed to the regex.

**Comment by anonrig** [comment]
@chrisbodhi https://regex101.com/r/iQ6fC1/1
