### ISSUE TITLE
Multiple Controllers and Bot within the same bot.

### ISSUE THREAD

**Issue by shashvattrip** [howdyai/botkit#945]
So I am working on a chat bot with our custom UI and backend. We are not integrating it with messenger, slack or any of the bot platforms for now but plan to do so in a few months.
I have 3 controllers in my nodejs app : 
1. MainBotController - This receives all the messages from the chat client
The job of main controller is to either delegate  it to another controller, say, AController or BController or to just ignore the message received by the MainBotController. This is because each controller would want to create it's own conversation and logic. 
2. AController does some heavy NLU stuff (with its own set of api calls inside and needs to create conversations flows etc)
3. BController does heavy DB fetch stuff (such as getting order details from various vendors etc)
4. AController and BController are independent of each other and share no code between themselves. They perform mutually exclusive functions. 
5. I need to store all the conversations and chat messages, done through middleware for the Main controller

Now what I'm struggling with is how do I manage connecting the bot instances such that my main controller  middleware that stores all the messages works well. And how do I delegate to different controllers such that they can create, manage conversations and reply to the user.

Or am I doing this wrong? -_-

Here's the code : 

```
let botController = ,({
    debug: true,
    log: true
});

let aController = NluBotController({
    debug: true,
    log: true
});
let bController = DBApiController({
    debug: true,
    log: true
});


function onMesageReceivedFromMainController(bot, message, next) {
    if(message.aController) {
        aController.receiveMessage(mainBot, message, next);   // Now this controller should be able to create conversations
    } else {
        bController.receiveMessage(mainBot, message, next);
    }
    next();
}

function onMessageSendFromMainController(bot, message, next) {
    console.log('************ onMessageSendFromMainController for , ************');
    // do something useful...
    console.log(JSON.stringify(bot));
    console.log(typeof bot)
    console.log(JSON.stringify(bot).length);
    console.log(message);
    console.log('************ onMessageSendFromMainController for , ************');
    next();

}

botController.middleware.receive.use(onMesageReceivedFromMainController);
botController.middleware.send.use(onMessageSendFromMainController);

//Middleware to log all messages in and out of the mainBot

let mainBot = botController.spawn({});
let aBot = aController.spawn({});
let bBot = bController.spawn({});

function onChatMessage(m) {
    mainBot.receiveMessage(mainBot, m);
}
```

**Comment by AshishCode** [comment]
Why are you passing the `mainBot` in `onMesageReceivedFromMainController` to different controllers? Shouldn't you pass different bots?

**Comment by shashvattrip** [comment]
Good questions @AshishCode. TBH, I am struggling with the same question myself. I want to be able to control sending of messages from the `botController`'s `mainBot`.  

Inside the `NluBotController` and `DBApiController` : 
I call `bot.reply()`, `bot.createConversation()` (here bot refers to the mainBot that has been passed to the controller in the `onMesageReceivedFromMainController`) and I expect it to give it to `onMessageSendFromMainController` where I'll be using storage to store that chat messages and publish the message to my clients.

**Comment by peterswimm** [comment]
Did you ever launch this project? Sounds interesting!
