### ISSUE TITLE
Is there any integrate solution in botkit to build a Multilangual bot

### ISSUE THREAD

**Issue by MagSag** [howdyai/botkit#947]
I am building a facebook bot and would like it to be replying in different language according to the user localization or language parameter.

So I would like to know if there is any way to do that with botkit only and how?  if not which module would you suggest with an easy way of integration.

**Comment by peterswimm** [comment]
There is currently no multilingual support in Botkit, but you could perhaps manage something using variables and threads where you:

- Start the conversation with asking a user to chose their language
- Store that choice
- Have all your scripts's text rendered as strings, and as users navigate through the conversations, you add your localized strings from Storage on the fly.

Obviously not ideal, we hope to support localization in the future, but no definite plans as of yet.

**Comment by MagSag** [comment]
Thanks;
