### ISSUE TITLE
Ciscosparkbot.js cannot get bot identity

### ISSUE THREAD

**Issue by rajmohan1955** [howdyai/botkit#948]
I am facing error "uriString must start with **ciscospark://', either in cleartext or base64-encoded.** while getting the identity of the bot in **lib/CiscoSparkbot.js**
`controller.api.people.get('me').then(function(identity) {
            console.log('Cisco Spark: My identity is', identity);
            controller.identity = identity;
`
I tried this on the web console test run too and getting the same error.
I am running the basic example for sparkbot with ngrok on ubuntu 16.04

**Comment by peterswimm** [comment]
This was fixed in 0.5.7

https://github.com/howdyai/botkit/blob/master/changelog.md#057
