### ISSUE TITLE
Is there anything like session variable for storing user's information during the chat session?

### ISSUE THREAD

**Issue by MagSag** [howdyai/botkit#949]
I would like to have the user's local as a session variable without getting it from the database because getting from the database is more costy than accessing directly from node.

Is this possible with botkit ? If Yes how can I acheive this.

**Comment by jonchurch** [comment]
If youre using the conversation system, convo.setVar is available

https://github.com/howdyai/botkit/blob/master/docs/readme.md#using-variable-tokens-and-templates-in-conversation-threads

**Comment by MagSag** [comment]
Ok thanks.
