### ISSUE TITLE
Start thread without initial message

### ISSUE THREAD

**Issue by ChrisLane** [howdyai/botkit#950]
I am currently trying to reply in a thread to a message that is posted by my bot in Slack.

I'm creating a conversation and posting a message in that conversation like this:
```
bot.createConversation({
      user: requestee_slack_id,
      channel: res.channel.id
    }, (err, convo) => {
        convo.setVar('variable', variableThing);
        convo.addMessage({text: "{{vars.projectCode}}"})
    }
})
````

I'd like to be able to respond to this message in a thread but so far have not found a way to do so. Is there a way that I can get the message object from the first posted message so that I can replyInThread?

**Comment by jonchurch** [comment]
Can you clarify expected behavior? I dont follow exactly.

All that replyInThread, startConversationInThread methods do is add the
timestamp of the message youre trying to thread onto to the outgoing
message as field thread_ts.

You can grab any message's ts and do a

`bot.replyInThread({ts: convo.original_message.ts} 'threaded message')`

Check the Botkit docs under slack-readme for more info on replying in
threads

**Comment by ChrisLane** [comment]
The message that I'm trying to reply to in a thread is the message that I'm crafting (shown in the code above). There doesn't seem to be a convo.original_message value

Hoping to:

1. Post a message
2. Reply in a thread to the message in step 1

**Comment by jonchurch** [comment]
@ChrisLane Ah sorry, missed the issue title somehow.

The info you need to thread a message isn't available after an async api call to post the message to slack.

At the least it, couldn't happen synchronously. Currently we are ignoring all messages events that originate from the bot. A fork could add a `bot_message` event that would trigger once your bot has the message, and then you could start the conversation in a thread from there, note the conversation will be between the bot and itself at this point (Meaning that user messages would be ignored) unless you pass a user id when starting the convo. 

Threading can be achieved with interactive buttons more easily, triggering an `interactive_message` event that contains the `original_message` that contained the button.

But if you want to thread your own message without the user interacting, I'm not currently aware of a method out of the box.

**Comment by ChrisLane** [comment]
I'd like to avoid modifying botkit in my own fork. Think I'll just try something else.
Thanks

**Comment by simonmorley** [comment]
@ChrisLane How did you go about resolving this?

**Comment by ChrisLane** [comment]
I haven't :/

**Comment by simonmorley** [comment]
I think our issues are slightly different although still related. See my other reply. 

Am working on a fix - would be good to work together if you think we can solve this. Silly this doesn't just work, seems like a no-brainer...

**Comment by mrnobody-assistant** [comment]
Here's what I did to fix this without forking botkit:

```js
controller.middleware.categorize.use((bot, message, next) => {
  if (message.type === 'self_message' && bot.identity.id === message.user) {
      controller.trigger('bot_message', [bot, message]);
  }
  next();
});
```

It might mean there's a little less metadata on the message, because it's a bit earlier, but so far it's working for me. Hopefully I won't find out it's a bad idea later. :)
