### ISSUE TITLE
convo.ask not receiving the callback on replies- Ciscospark 

### ISSUE THREAD

**Issue by rajmohan1955** [howdyai/botkit#961]
Hi Guys,
I have created a room on cisco spark and I am trying to initiate a conversation in that room. I am able to ask the question in the room but I am not receiving the control in the callback when someone replies.
```javascript
bot.startConversation({
user: TestRoomId,
channel: TestRoomId,
text: 'dummy'}, 
function(err, convo) {
         convo.ask({
         channel: TestRoomId,
         text: 'What are you doing?',
         pattern:'yes'}, 
         function(res, convo) {
                   convo.say(res.text + ' is not a good enough answer.')
                   convo.next()
                   }) })
```

**Comment by jonchurch** [comment]
User needs to be a user id. Conversations are carried out 1 to 1 and
therefore will ignore any messages sent by users other than the one you
initially start the convo with.

This might work as a DM convo, channel and user are probably the same there
idk

Spark is unique in that for some events, like bot_channel_join, the user
field passed on the payload is the subject, not the actor, of an action.

IE bot_join has `user: <BOT_IDENTITY>` with an `actor_id: <ACTING_USER>`

**Comment by rajmohan1955** [comment]
@jonchurch what I am trying to do is, I want the bot to post a question on the cisco spark room based on some logic. Then basis the answer in the room I want to take necessary action.
What is the way to make this happen.

**Comment by benbrown** [comment]
You should pass the _text only_ into convo.ask. Those extra options may be confusing Botkit.

Also, make sure you @mention your bot every time - in Spark, bots can only hear direct mentions.
