### ISSUE TITLE
Support resources in Spark Bot webhook name URL

### ISSUE THREAD

**Issue by adambonny** [howdyai/botkit#964]
Hello,

When creating a spark bot we're able to define a webhook URL however the URL does not support a resource, for instance if you enter:

```https://webhooks.acme.com/mybot```

botkit drops the /mybot resource and the webhook is created as:

```https://webhooks.acme.com/```

As multiple webhooks are often hosted behind a single service URL/load balancer, differentited only by resource it would be benefical if support for this could be added!

Thankyou
Adam

**Comment by jonchurch** [comment]
Idk enough about spark to know why it is setup this way, but take a look at
https://github.com/howdyai/botkit-starter-ciscospark/blob/master/components/subscribe_events.js
to see how to subscribe whatever endpoint you want.

In the example provided, there is a webhook setup (in the same project) at
/ciscospark/receive, and it is manually registering that webhook with spark

Not an elegant solution, but if you need this ASAP id start there!

**Comment by peterswimm** [comment]
There is also this in the routes folder:
https://github.com/howdyai/botkit-starter-ciscospark/blob/master/components/routes/incoming_webhooks.js#L6

As for the why, the starter kit implementation is for the MOST SIMPLE way of handling this, our supposition being if you need custom webhooks, for example if you are running through a load balancer, that you would create your own express (or whatever) implementation to handle a given setup.

**Comment by benbrown** [comment]
@adambonny did the answers above help?
