### ISSUE TITLE
Slack Verification Token for interactive messages and events

### ISSUE THREAD

**Issue by shishirsharma** [howdyai/botkit#967]
Slack specifies a Verification Token for interactive messages and events api. Botkit does not support this out of the box. 

This can't be handled via checking for `req.body.token` in `createWebhookEndpoints` callback, as events get triggered before the call of callback. Also `cb` does not have `req`.

**Comment by shishirsharma** [comment]
If this check makes sense, I am willing to open a PR.

**Comment by peterswimm** [comment]
duplicate of https://github.com/howdyai/botkit/issues/966

**Comment by shishirsharma** [comment]
https://github.com/howdyai/botkit/pull/981
