### ISSUE TITLE
Add 'typing' indicator

### ISSUE THREAD

**Issue by Studnicky** [howdyai/botkit#97]
Small enhancement suggestion.

I find my bot often kicking off actions that take more than a few seconds to complete & callback. Users seem to think he's bugged or broken somewhere if they don't see a reply immediately.

Currently, I use a typing indicator RTM event to keep users informed that the bot did, in fact, hear their message and is processing it, like this:
``` bot.reply(message, {"type": "typing"}); ```

It'd be quite convenient to have that wrapped in a method like:
``` bot.typing(message); ```

If only for the sake of usability affordance.

**Comment by Glowbal** [comment]
@Studnicky checkout #73 I think that is exactly what you are looking for.

**Comment by Studnicky** [comment]
Ooh, yes it is. Sorry I missed that.
