### ISSUE TITLE
Is there a way a good way to start a new conversation from within an existing conversation then pickup the original conversation after the second has finished.

### ISSUE THREAD

**Issue by jloveric** [howdyai/botkit#974]
What I'm looking for is, suppose you are having one conversation, but the user states a phrase that normally triggers a different conversation.  Is there a way to start a second conversation, from within an ongoing conversation?  Is something implemented?  I can imagine this being accomplished using a stack and a something that indicates the position in each conversation, so that when one conversation finishes the next picks up where it left off.

Thanks

**Comment by fewtaeyeon** [comment]
It that like that you are calling someone and you just hold it off to make a call with another one .So, after you finish the conversation then you picks up the first one. Something like that?

**Comment by jloveric** [comment]
Yes, that's basically what I'm looking for.  I think this would allow one to have very natural conversations.

**Comment by benbrown** [comment]
This is not currently supported, but we're thinking about ways to achieve it.

**Comment by soulwire** [comment]
@benbrown any updates on this? It'd certainly be a useful feature and I think quite a common use case (e.g. access a help dialog during a conversation then resume the original convo)

**Comment by peterswimm** [comment]
This will be a core feature of a future Botkit update

**Comment by harshilsharma63** [comment]
@benbrown @peterswimm any updates on this?

**Comment by adantoscano** [comment]
Maybe [this](https://www.botkit.ai/docs/v4/conversations.html#composing-dialogs) can be a way to do it

**Comment by benbrown** [comment]
@adantoscano bingo - using `beginDialog` allows you to do this.

**Comment by MohammadUmer526** [comment]
@adantoscano  could please show how you do it?

**Comment by adantoscano** [comment]
I didn't use it @MohammadUmer526 but I think you only need to create both dialogs and use `addChildDialog` at parent dialog when you need to fire it

**Comment by benbrown** [comment]
@adantoscano correct.
