### ISSUE TITLE
how to fix this error when i start with npm start

### ISSUE THREAD

**Issue by teerapat2539** [howdyai/botkit#982]
Initializing Botkit v0.5.8
info: ** No persistent storage method specified! Data may be lost when process shuts down.
info: No DASHBOT_API_KEY specified. For free turnkey analytics for your bot, go to https://www.dashbot.io/ to get your key.

**Comment by peterswimm** [comment]
Neither of those are actual errors that would stop you from running your bot, rather they are state notifications for optional services. 

You can read about setting up Dashbot here:
https://www.dashbot.io/sdk/slack/botkit

You can read about choosing a storage middleware to replace the built in simple storage here:
https://github.com/howdyai/botkit/blob/master/docs/storage.md
https://github.com/howdyai/botkit/blob/master/docs/readme-middlewares.md#storage-modules
