### ISSUE TITLE
Unable to verify. URL Callback  (messager facebook)

### ISSUE THREAD

**Issue by teerapat2539** [howdyai/botkit#983]
# i'm use ssl(https) but error  >> this error " ** Response does not match challenge, expected value="2022404443", received="OK"** "

edit: Dont post screenshots with your tokens here!

**Comment by peterswimm** [comment]
You posted a screenshot of an atom editor, but did you past all the correct token information in the GLITCH projects ENV file?

**Comment by teerapat2539** [comment]
What is GLITCH projects ENV file?   please explain me.

**Comment by teerapat2539** [comment]
thank you i found and success in thus error.

**Comment by peterswimm** [comment]
Sounds good! Closing for now!
