### ISSUE TITLE
hot to edit 

### ISSUE THREAD

**Issue by Yulgana33** [howdyai/botkit#985]
// Example taken from https://github.com/rubenlagus/TelegramBotsExample
    public class Main {
        public static void main(String[] args) {
    
            TelegramBotsApi telegramBotsApi = new TelegramBotsApi();
            try {
                telegramBotsApi.registerBot(new ChannelHandlers());
                telegramBotsApi.registerBot(new DirectionsHandlers());
                telegramBotsApi.registerBot(new RaeHandlers());
                telegramBotsApi.registerBot(new WeatherHandlers());
                telegramBotsApi.registerBot(new TransifexHandlers());
                telegramBotsApi.registerBot(new FilesHandlers());
            } catch (TelegramApiException e) {
                e.printStackTrace();
            }
        }<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.telegram</groupId>
    <artifactId>Bots</artifactId>
    <packaging>pom</packaging>
    <version>3.3</version>

    <modules>
        <module>telegrambots</module>
        <module>telegrambots-meta</module>
        <module>telegrambots-extensions</module>
        <module>telegrambots-abilities</module>
    </modules>

    <licenses>
        <license>
            <name>MIT License</name>
            <url>http://www.opensource.org/licenses/mit-license.php</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <properties>
        <maven.deploy.skip>true</maven.deploy.skip>
        <bots.version>3.3</bots.version>
    </properties>
</project><?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.telegram</groupId>
    <artifactId>Bots</artifactId>
    <packaging>pom</packaging>
    <version>3.3</version>

    <modules>
        <module>telegrambots</module>
        <module>telegrambots-meta</module>
        <module>telegrambots-extensions</module>
        <module>telegrambots-abilities</module>
    </modules>

    <licenses>
        <license>
            <name>MIT License</name>
            <url>http://www.opensource.org/licenses/mit-license.php</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <properties>
        <maven.deploy.skip>true</maven.deploy.skip>
        <bots.version>3.3</bots.version>
    </properties>
</project><?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.telegram</groupId>
    <artifactId>Bots</artifactId>
    <packaging>pom</packaging>
    <version>3.3</version>

    <modules>
        <module>telegrambots</module>
        <module>telegrambots-meta</module>
        <module>telegrambots-extensions</module>
        <module>telegrambots-abilities</module>
    </modules>

    <licenses>
        <license>
            <name>MIT License</name>
            <url>http://www.opensource.org/licenses/mit-license.php</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <properties>
        <maven.deploy.skip>true</maven.deploy.skip>
        <bots.version>3.3</bots.version>
    </properties>
</project>

**Comment by peterswimm** [comment]
This is not a Botkit related project. Closing as off-topic.
