### ISSUE TITLE
Facebook quick_reply should trigger an event

### ISSUE THREAD

**Issue by adrienbarreau** [howdyai/botkit#992]
When you click on a button with a postback, it triggers the event `facebook_postback`
When you click on a quick replies, which has also a postback, it triggers only the event `message_received`.

It would be nice to have an event dedicated to quick_replies or trigger the event `message_received`

**Comment by afbayonac** [comment]
you can use a middleware
```  /* quick_replies */
  controller.middleware.normalize.use(function handleQuickReply (bot, message, next) {
    if (message.quick_reply) {
      message.text = message.quick_reply.payload
      message.payload = message.quick_reply.payload
      message.type = 'facebook_quick_reply'
    }
    next()
  })
```
