### ISSUE TITLE
Botkit Line?

### ISSUE THREAD

**Issue by teerapat1739** [howdyai/botkit#998]
Why not have bot kit in Line Application?

**Comment by peterswimm** [comment]
Typically platforms approach us to handle support, but it is entirely possible for a third party to do it on their own as well. If anyone in the community wants to take a stab at it, here is some useful information for consideration:

https://github.com/line/line-bot-faq
https://business.line.me/en/services/bot

**Comment by jonchurch** [comment]
Whilst in Thailand dor the next 30 days, I will be working on this

**Comment by sakazuki** [comment]
Hello @jonchurch,  I am interested in Botkit Line.
Could you let me know the status of developing this.

**Comment by megenius** [comment]
Hello @jonchurch I am interested in Botkit Line and I am living in Thailand.
May I help you to develop.

**Comment by MagSag** [comment]
Any news about Botkit line?

**Comment by softmastx** [comment]
Any news about Botkit line?

**Comment by peterswimm** [comment]
We have received no PRs so far, Have you tried contacting Line?
